


Source1 Name : SQ_WIPS_SER_POS_DTLS_PUB


Pre SQL : 



SQL Query : 
SELECT 
WIP.TRANS_ID, 
WIP.ID, 
WIP.BOOKING_FLAG, 
NVL(WIP.SERVICE_TYPE,'UNKNOWN'), 
WIP.ACTIVE_FLAG, 
WIP.CREATED_DATE, 
WIP.CREATED_BY, 
WIP.LAST_UPDATED_DATE, 
WIP.LAST_UPDATED_BY,
NVL(WIP. QUOTE_NUMBER,'UNKNOWN'),
NVL(WIP. CONTRACT_NUMBER,'UNKNOWN'),
NVL(WIP. QUOTE_LINE_ID,-999),
/* NVL(WIP. ORDER_LINE_ID,-9999),*/
CASE WHEN WIP.ORDER_LINE_ID = -6666 THEN -9999 ELSE NVL(WIP.ORDER_LINE_ID,-9999) END AS ORDER_LINE_ID,
NVL(MATCH_TYPE, 'UNKNOWN'),
NVL(CAST(ORDER_HEADER_ID AS VARCHAR2(150)),'-999') ,
NVL(CAST(QUOTE_HEADER_ID AS VARCHAR2(150)),'-9999') ,
NVL(REVENUE_SOURCE_CODE, 'U' ),
NVL(WIP.CONFIDENCE_FLAG, 'N') ,
WIP.PO_EXISTS ,
WIP.PO_DISTI_EXISTS ,
WIP.PO_PID_EXISTS ,
WIP.QUOTE_EXISTS ,
WIP.QUOTE_DISTI_EXISTS ,
WIP.QUOTE_PID_EXISTS ,
WIP.MULTIPLE_SALES_MOTION,
WIP.MULTIPLE_MATCH,        
WIP.APPROVED_ERP_LINKAGE,
WIP.ORDER_IDENTIFIER 
FROM
XXDISTIPUB.WIPS_SER_POS_DTLS_PUB WIP
WHERE WIP.LAST_UPDATED_DATE > TO_DATE('$$LastExtractDate','MM/DD/YYYY HH24:MI:SS')


Post SQL : 



Target1 Name : FF_WIPS_POS_SVC_DETAILS_PUB


Pre SQL : 



Post SQL : 
