


Source1 Name : SQ_MT_SALES_MOTION_RPT_NSQ


Pre SQL : 
COLLECT STATISTICS COLUMN (PRODUCT_KEY) ON $$SLSORDDB.N_BKGS_MEASURE;

 COLLECT STATISTICS COLUMN (BK_PRODUCT_SUBGROUP_ID ,BK_SERVICE_CATEGORY_ID ,BK_ALLOCATED_SERVC_GROUP_ID ,ALLOCATION_PERCENTAGE) 
ON $$COMREFDB.MT_CS_DEAL_SVC_FIN_HIER_ME; 


DELETE FROM $$SLSORDVWDB.MT_SALES_MOTION_RPT
WHERE BKGS_MEASURE_TRANS_TYPE_CODE='ERP' /*AND SUMMARY_QUOTE_FLG='N' */
AND ( FISCAL_YEAR_MONTH_INT = (SELECT FISCAL_YEAR_MTH_NUMBER_INT FROM $$ETLVWDB.BKG_PROCESS_DT_CNTRL)
OR  BOOKINGS_MEASURE_KEY IN ( SELECT  BOOKINGS_MEASURE_KEY  FROM $$SLSORDVWDB.N_BKGS_MEASURE  WHERE  BKGS_MEASURE_TRANS_TYPE_CODE='ERP'   AND 
 CAST(  CAST ( EDW_UPDATE_DATETIME AS FORMAT 'YYYY-MM-DD' ) AS DATE )>= (SELECT PROCESS_DATE-15 FROM $$ETLVWDB.BKG_PROCESS_DT_CNTRL)  GROUP BY 1  )  
OR  BOOKINGS_MEASURE_KEY IN ( SELECT  BOOKINGS_MEASURE_KEY  FROM $$SLSORDVWDB.N_BKGS_MEASURE BKG
INNER JOIN $$SLSORDVWDB.MT_BKG_SLS_MOTION_ATTRIBUTION MT
ON BKG.SK_SALES_MOTION_ATTRIB_KEY=MT.SK_SALES_MOTION_ATTRIB_KEY 
WHERE  BKG.BKGS_MEASURE_TRANS_TYPE_CODE='ERP' AND MT.END_TV_DTM='3500-01-01 00:00:00' AND
CAST( CAST ( MT.EDW_UPDATE_DTM AS FORMAT 'YYYY-MM-DD' ) AS DATE )>= (SELECT PROCESS_DATE-7 FROM $$ETLVWDB.BKG_PROCESS_DT_CNTRL) GROUP BY 1) 
 );


/* Performance changes as part of 19Feb2021 */
-- Volatile table to handle all joins on $$COMREFVWDB.R_PRODUCTS
create volatile table VOL_R_PRODUCTS as
(
		sel	BV_BKGS_MEASURE.PRODUCT_KEY,
		     BP.RU_BK_SERVICE_PROD_SUBGROUP_ID,
		     BP.ITEM_KEY,
		     BP.BK_PRODUCT_ID,
		     BP.PRDT_SETUP_CLASSIFICATION_CD,
		     BP.RU_BK_PRODUCT_FAMILY_ID,
		     BP.RU_COMMISSIONABLE_STATUS_CODE,
			 BP.PRODUCT_FAMILY_DESCRIPTION,
		     BP.RU_BK_SERVICE_PROGRAM_ID,
		     BP.RU_SERVICE_LEVEL_GROUP_CODE,
		     SWSS.BK_GSP_ATTR_VAL_TXT,
		     SFH.BK_SERVICE_CATEGORY_ID,
		     SFH.BK_ALLOCATED_SERVC_GROUP_ID,
		     SFH.BK_PRODUCT_SUBGROUP_ID,
		     SFH.ALLOCATION_PERCENTAGE
		from	$$COMREFVWDB.R_PRODUCTS BP
		INNER JOIN (
				sel	product_key 
				from	$$SLSORDVWDB.N_BKGS_MEASURE 
				where
				BKGS_MEASURE_TRANS_TYPE_CODE IN ('ERP' )
				AND CORPORATE_BOOKINGS_FLG IN ('Y')
				group by 1) BV_BKGS_MEASURE 
			ON BP.ITEM_KEY = BV_BKGS_MEASURE.PRODUCT_KEY
		INNER JOIN 
		           (
				SELECT	 ITEM_KEY,
				            BK_PRODUCT_SUBGROUP_ID,
				            BK_SERVICE_CATEGORY_ID,
				            BK_ALLOCATED_SERVC_GROUP_ID,
				            ALLOCATION_PERCENTAGE
				            FROM	$$COMREFVWDB.MT_SVC_FINANCE_HIERARCHY
				            GROUP BY  1,2,3,4,5) SFH 
			ON SFH.ITEM_KEY = BP.ITEM_KEY
		LEFT JOIN 
		           (
				SELECT	BK_PRDT_SUBGROUP_ID,
				            BK_GSP_ATTR_VAL_TXT
				            FROM	$$SERVICEVWDB.N_GENERIC_SVC_PRDT_ATTR
				            WHERE	1 = 1
				            AND  BK_GSP_ATTR_NAME = 'SW SERVICE CATEGORY') SWSS 
			ON SWSS.BK_PRDT_SUBGROUP_ID =  BP.RU_BK_SERVICE_PROD_SUBGROUP_ID )
with data 
no primary index on commit preserve rows;
INSERT INTO $$SLSORDVWDB.MT_SALES_MOTION_RPT(BOOKINGS_MEASURE_KEY,FISCAL_YEAR_NUMBER_INT, FISCAL_QUARTER_ID, FISCAL_YEAR_MONTH_INT,FISCAL_WEEK_NUMBER_INT, FISCAL_YR_MNTH_WEEK_INT, BOOKINGS_PROCESS_DATE,BKGS_MEASURE_TRANS_TYPE_CODE, DEAL_ID, SALES_ORDER_KEY, BK_SO_SOURCE_NAME,SALES_ORDER_PROGRAM_TYPE_NAME, ORDER_CANCELLED_FLAG, ORDER_HEADER_BOOKED_DATE,SOURCE_ORDER_NUM_INT, DV_SALES_ORDER_LINE_KEY, BK_POS_TRANSACTION_ID_INT,SALES_ORDER_LINE_ID, ORDER_LINE_CREATION_DATE, CISCO_BOOKED_DATETIME,CUST_EXPECTED_START_DT, LINE_SOURCE_NAME, LINE_STATUS_CD, SALES_ORDER_CATEGORY_TYPE,RU_SERVICE_CONTRACT_NUMBER, ORDER_LINE_CANCELLED_FLAG, CONTRACT_DURATION,CONTRACT_START_DATE, CONTRACT_END_DATE, ORDERED_ITEM, ORDERED_SERVICE,SUMMARY_QUOTE_FLG, PRODUCT_KEY, ATTRIBUTED_PRODUCT_ID, RU_BK_SERVICE_PROD_SUBGROUP_ID,FINANCE_BU_SW_TYPE, PRDT_SETUP_CLASSIFICATION_CD, RU_BK_PRODUCT_FAMILY_ID,RU_COMMISSIONABLE_STATUS_CODE, BK_SERVICE_CATEGORY_ID, BK_ALLOCATED_SERVC_GROUP_ID,BK_PRODUCT_SUBGROUP_ID, ALLOCATION_PERCENTAGE, END_CUSTOMER_KEY,END_CUSTOMER_ID, END_CUSTOMER_NAME, ERP_WIPS_ISO_COUNTRY_CD,END_CUST_CRPARTY_ID, BRANCH_HQ_BRANCH_CD, HQ_CRPARTY_ID, HQ_CRPARTY_NAME,GU_ID, GU_PRIMARY_NAME, SALES_TERRITORY_KEY, SALES_COVERAGE_CODE,SALES_SUBCOVERAGE_CODE, L1_SALES_TERRITORY_DESCR, L2_SALES_TERRITORY_DESCR,SALES_TERRITORY_NAME_CODE, SALES_REP_NUMBER, ERP_SALES_REP_NAME,ADJUSTMENT_CODE, RU_SERVICE_CONTRACT_START_DTM, RU_SERVICE_CONTRACT_END_DTM,DV_CONTRACT_DURATION, XCAT_FLG, DSV_FLG, DV_FMV_FLG, SK_SALES_MOTION_ATTRIB_KEY,SMR_SALES_ORDER_LINE_KEY, SALES_MOTION_CD, RTR_SERVICE_CATEGORY_CD,RTR_AS_ARCHITECTURE_NAME, RTR_TECHNOLOGY_GROUP_ID, RTR_OFFER_TYPE,RTR_RENEW_CONTRACT_LINE_ID, RTR_AS_TS_CODE, RTR_SRC_ENTERPRISE_INV_SKU_ID,RTR_PRODUCT_CLASS, RTR_TRANSACTION_CR_PARTY_KEY, RTR_HQ_CR_PRTY_KEY,RTR_RENEWAL_REF_ID, RTR_RENEWAL_REF_CD, RTR_SMR_TAGGING_FAILURE_RSN_CD,RTR_SALES_MOTION_TIMING_CD, RTR_MANUAL_OVERRIDE_ROLE, REQUESTING_CSCO_WRKR_PRTY_KEY,SLS_MTN_CORRECTION_CASE_NUM, SLS_MTN_CORRECTION_CMNT, DV_ALLOCATION_PCT,SERVICE_FLG, DD_COMP_US_NET_PRICE_AMOUNT, DV_AR_TRX_LINE_KEY,AR_TRX_KEY, BK_AR_TRX_NUMBER, AR_TRX_REASON_CODE, ADJUSTMENT_DESCR_KEY,CORPORATE_BOOKINGS_FLG, DV_ATTRIBUTION_CD, MANUAL_TRX_KEY, BK_SALES_ADJ_LINE_NUMBER_INT,BK_SALES_ADJ_NUMBER_INT, IDE_IFC_COMMENT_1_TXT, IDE_IFC_COMMENT_2_TXT,IDE_IFC_COMMENT_3_TXT, IDE_IFC_COMMENT_4_TXT, IDE_IFC_COMMENT_5_TXT,IDE_IFC_DESCRIPTION_TXT, UPLOADED_BY_ERP_USER_NAME, MANUAL_TRANSACTION_TYPE_CD,MANUAL_TRANSACTION_USAGE_CD, MANUAL_TRX_BOOKING_REVENUE_CD, CURRENT_SNAPSHOT_DT,DV_ANNUALIZED_AMT, START_TV_DT, OA_ID, PRODUCT_FAMILY, SERVICE_PROGRAM,SERVICE_LEVEL, ENTERPRISE_SKU, FISCAL_QUARTER, FISCAL_MONTH,SALES_LEVEL_3, CUSTOMER_HQ_NAME, RSC_CODE, DEAL_HQ_CR_PARTY_NAME,LINE_SOURCE, LINE_CREATION_DATE, SMR_RULE_TYPE, INHERITANCE_FLAG,BE, SUB_BE, ITEM_CATEGORY_NAME, DD_BK_SO_NUMBER_INT, MATCHING_MTHD_FOR_TAGGING_NAME,L4_SALES_TERRITORY_DESCR, L5_SALES_TERRITORY_DESCR, L6_SALES_TERRITORY_DESCR,SMR_OFFER_TYPE, SMC_SOURCE_TAG, WEB_ORDER_ID, ORDER_CREATED_DT,SUBSCRIPTION_REFERENCE_ID, SUBSCRIPTION_START_DT, SUBSCRIPTION_END_DT,SHARE_NODE_NAME, EDW_CREATE_DTM, EDW_CREATE_USER, EDW_UPDATE_DTM,EDW_UPDATE_USER)
    SELECT	PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BOOKINGS_MEASURE_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.FISCAL_YEAR_NUMBER_INT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.FISCAL_QUARTER_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.FISCAL_YEAR_MONTH_INT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.FISCAL_WEEK_NUMBER_INT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.FISCAL_YR_MNTH_WEEK_INT,CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BOOKINGS_PROCESS_DATE AS DATE),PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BKGS_MEASURE_TRANS_TYPE_CODE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.DEAL_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SALES_ORDER_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BK_SO_SOURCE_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SALES_ORDER_PROGRAM_TYPE_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ORDER_CANCELLED_FLAG,CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ORDER_HEADER_BOOKED_DATE AS DATE),PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SOURCE_ORDER_NUM_INT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.DV_SALES_ORDER_LINE_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BK_POS_TRANSACTION_ID_INT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SALES_ORDER_LINE_ID,CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ORDER_LINE_CREATION_DATE AS TIMESTAMP(0)),CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.CISCO_BOOKED_DATETIME AS TIMESTAMP(0)),CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.CUST_EXPECTED_START_DT AS DATE),PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.LINE_SOURCE_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.LINE_STATUS_CD,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SALES_ORDER_CATEGORY_TYPE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RU_SERVICE_CONTRACT_NUMBER,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ORDER_LINE_CANCELLED_FLAG,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.CONTRACT_DURATION,CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.CONTRACT_START_DATE AS TIMESTAMP(0)),CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.CONTRACT_END_DATE AS TIMESTAMP(0)),PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ORDERED_ITEM,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ORDERED_SERVICE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SUMMARY_QUOTE_FLG,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.PRODUCT_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ATTRIBUTED_PRODUCT_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RU_BK_SERVICE_PROD_SUBGROUP_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.FINANCE_BU_SW_TYPE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.PRDT_SETUP_CLASSIFICATION_CD,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RU_BK_PRODUCT_FAMILY_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RU_COMMISSIONABLE_STATUS_CODE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BK_SERVICE_CATEGORY_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BK_ALLOCATED_SERVC_GROUP_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BK_PRODUCT_SUBGROUP_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ALLOCATION_PERCENTAGE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.END_CUSTOMER_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.END_CUSTOMER_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.END_CUSTOMER_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ERP_WIPS_ISO_COUNTRY_CD,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.END_CUST_CRPARTY_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BRANCH_HQ_BRANCH_CD,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.HQ_CRPARTY_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.HQ_CRPARTY_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.GU_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.GU_PRIMARY_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SALES_TERRITORY_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SALES_COVERAGE_CODE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SALES_SUBCOVERAGE_CODE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.L1_SALES_TERRITORY_DESCR,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.L2_SALES_TERRITORY_DESCR,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SALES_TERRITORY_NAME_CODE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SALES_REP_NUMBER,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ERP_SALES_REP_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ADJUSTMENT_CODE,CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RU_SERVICE_CONTRACT_START_DTM AS TIMESTAMP(0)),CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RU_SERVICE_CONTRACT_END_DTM AS TIMESTAMP(0)),PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.DV_CONTRACT_DURATION,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.XCAT_FLG,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.DSV_FLG,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.DV_FMV_FLG,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SK_SALES_MOTION_ATTRIB_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SMR_SALES_ORDER_LINE_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SALES_MOTION_CD,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_SERVICE_CATEGORY_CD,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_AS_ARCHITECTURE_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_TECHNOLOGY_GROUP_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_OFFER_TYPE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_RENEW_CONTRACT_LINE_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_AS_TS_CODE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_SRC_ENTERPRISE_INV_SKU_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_PRODUCT_CLASS,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_TRANSACTION_CR_PARTY_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_HQ_CR_PRTY_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_RENEWAL_REF_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_RENEWAL_REF_CD,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_SMR_TAGGING_FAILURE_RSN_CD,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_SALES_MOTION_TIMING_CD,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RTR_MANUAL_OVERRIDE_ROLE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.REQUESTING_CSCO_WRKR_PRTY_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SLS_MTN_CORRECTION_CASE_NUM,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SLS_MTN_CORRECTION_CMNT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.DV_ALLOCATION_PCT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SERVICE_FLG,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.DD_COMP_US_NET_PRICE_AMOUNT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.DV_AR_TRX_LINE_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.AR_TRX_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BK_AR_TRX_NUMBER,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.AR_TRX_REASON_CODE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ADJUSTMENT_DESCR_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.CORPORATE_BOOKINGS_FLG,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.DV_ATTRIBUTION_CD,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.MANUAL_TRX_KEY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BK_SALES_ADJ_LINE_NUMBER_INT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BK_SALES_ADJ_NUMBER_INT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.IDE_IFC_COMMENT_1_TXT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.IDE_IFC_COMMENT_2_TXT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.IDE_IFC_COMMENT_3_TXT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.IDE_IFC_COMMENT_4_TXT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.IDE_IFC_COMMENT_5_TXT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.IDE_IFC_DESCRIPTION_TXT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.UPLOADED_BY_ERP_USER_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.MANUAL_TRANSACTION_TYPE_CD,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.MANUAL_TRANSACTION_USAGE_CD,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.MANUAL_TRX_BOOKING_REVENUE_CD,CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.CURRENT_SNAPSHOT_DT AS DATE),PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.DV_ANNUALIZED_AMT,CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.START_TV_DT AS DATE),PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.OA_ID,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.PRODUCT_FAMILY,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SERVICE_PROGRAM,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SERVICE_LEVEL,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ENTERPRISE_SKU,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.FISCAL_QUARTER,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.FISCAL_MONTH,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SALES_LEVEL_3,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.CUSTOMER_HQ_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.RSC_CODE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.DEAL_HQ_CR_PARTY_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.LINE_SOURCE,CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.LINE_CREATION_DATE AS DATE),PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SMR_RULE_TYPE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.INHERITANCE_FLAG,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.BE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SUB_BE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ITEM_CATEGORY_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.DD_BK_SO_NUMBER_INT,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.MATCHING_MTHD_FOR_TAGGING_NAME,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.L4_SALES_TERRITORY_DESCR,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.L5_SALES_TERRITORY_DESCR,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.L6_SALES_TERRITORY_DESCR,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SMR_OFFER_TYPE,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SMC_SOURCE_TAG,PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.WEB_ORDER_ID,CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.ORDER_CREATED_DT AS DATE),PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SUBSCRIPTION_REFERENCE_ID,CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SUBSCRIPTION_START_DT AS DATE),CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SUBSCRIPTION_END_DT AS DATE),PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.SHARE_NODE_NAME,CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.EDW_CREATE_DTM AS TIMESTAMP(0)),PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.EDW_CREATE_USER,CAST(PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.EDW_UPDATE_DTM AS TIMESTAMP(0)),PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY.EDW_UPDATE_USER
        FROM	 (
	SELECT	BV_BKGS_MEASURE.BOOKINGS_MEASURE_KEY,BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_NUMBER_INT,BV_FISCAL_DAY_TO_YEAR.DV_FISCAL_QUARTER_ID     AS FISCAL_QUARTER_ID,BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_MONTH_INT,BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_WEEK_NUM_INT AS FISCAL_WEEK_NUMBER_INT,BV_FISCAL_DAY_TO_YEAR.DV_FISCAL_YR_MNTH_WEEK_NUM_INT       AS FISCAL_YR_MNTH_WEEK_INT,BV_BKGS_MEASURE.BOOKINGS_PROCESS_DATE,BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE,BV_BKGS_MEASURE.DV_DEAL_ID AS DEAL_ID,BV_BKGS_MEASURE.SALES_ORDER_KEY,SO.BK_SO_SOURCE_NAME,SO.SALES_ORDER_PROGRAM_TYPE_NAME,BV_BKGS_MEASURE.CANCELLED_FLG                 AS ORDER_CANCELLED_FLAG,BV_BKGS_MEASURE.DV_BOOKED_DT                  AS ORDER_HEADER_BOOKED_DATE,BV_BKGS_MEASURE.DV_SOURCE_ORDER_NUM_INT       AS SOURCE_ORDER_NUM_INT,BV_BKGS_MEASURE.DV_SALES_ORDER_LINE_KEY,BV_BKGS_MEASURE.BK_POS_TRANSACTION_ID_INT,BV_SALES_ORDER_LINE_TV.SK_SO_LINE_ID_INT              AS SALES_ORDER_LINE_ID,SO.ORDER_LINE_CREATION_DATE,BV_SALES_ORDER_LINE_TV.CISCO_BOOKED_DATETIME,BV_SALES_ORDER_LINE_TV.CUST_EXPECTED_START_DT         AS CUST_EXPECTED_START_DATE,BV_SALES_ORDER_LINE_TV.BK_SO_SRC_NAME AS LINE_SOURCE_NAME,BV_SALES_ORDER_LINE_TV.LINE_STATUS_CD,BV_SALES_ORDER_LINE_TV.SALES_ORDER_CATEGORY_TYPE,BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_NUMBER        AS RU_SERVICE_CONTRACT_NUMBER,BV_SALES_ORDER_LINE_TV.CANCELLED_FLAG AS ORDER_LINE_CANCELLED_FLAG,COALESCE(NULLIFZERO(
CASE
WHEN BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('SLS_ADJ','POS_ADJ','POS') THEN CAST((CAST(CAST(BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_END_DTM AS DATE) - CAST(BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_START_DTM AS DATE) AS INTEGER)*12(FLOAT))/365 AS DECIMAL(18,0)) ELSE CAST((CAST(CAST(BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_END_DTM AS DATE ) - CAST(BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_START_DTM AS DATE) AS INTEGER)*12(FLOAT))/365 AS DECIMAL(18,0))END ) ,BV_BKGS_MEASURE.DV_CONTRACT_DURATION               )  AS CONTRACT_DURATION,CASE WHEN BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('SLS_ADJ','POS_ADJ', 'POS') THEN BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_START_DTM       ELSE BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_START_DTM END AS CONTRACT_START_DATE,CASE WHEN BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('SLS_ADJ','POS_ADJ', 'POS') THEN BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_END_DTM       ELSE BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_END_DTM END AS CONTRACT_END_DATE,'UNKNOWN'  AS ORDERED_ITEM,BP.RU_BK_SERVICE_PROD_SUBGROUP_ID  AS ORDERED_SERVICE,BV_BKGS_MEASURE.SUMMARY_QUOTE_FLG,BP.ITEM_KEY AS PRODUCT_KEY,BP.BK_PRODUCT_ID  AS ATTRIBUTED_PRODUCT_ID,BP.RU_BK_SERVICE_PROD_SUBGROUP_ID  AS RU_BK_SERVICE_PROD_SUBGROUP_ID,BP.BK_GSP_ATTR_VAL_TXT AS  FINANCE_BU_SW_TYPE,BP.PRDT_SETUP_CLASSIFICATION_CD,BP.RU_BK_PRODUCT_FAMILY_ID AS RU_BK_PRODUCT_FAMILY_ID,BP.RU_COMMISSIONABLE_STATUS_CODE     AS RU_COMMISSIONABLE_STATUS_CODE,BP.BK_SERVICE_CATEGORY_ID,BP.BK_ALLOCATED_SERVC_GROUP_ID,BP.BK_PRODUCT_SUBGROUP_ID,BP.ALLOCATION_PERCENTAGE,BV_BKGS_MEASURE.END_CUSTOMER_KEY,DE.END_CUSTOMER_ID,DE.END_CUSTOMER_NAME,DE.ERP_WIPS_ISO_COUNTRY_CD,DE.END_CUST_CRPARTY_ID,DE.BRANCH_HQ_BRANCH_CD,DE.HQ_CRPARTY_ID,DE.HQ_CRPARTY_NAME,DE.GU_ID,DE.GU_PRIMARY_NAME,BV_BKGS_MEASURE.SALES_TERRITORY_KEY,BV_SALES_HIERARCHY.SALES_COVERAGE_CODE,BV_SALES_HIERARCHY.SALES_SUBCOVERAGE_CODE,BV_SALES_HIERARCHY.L1_SALES_TERRITORY_DESCR,BV_SALES_HIERARCHY.L2_SALES_TERRITORY_DESCR,BV_SALES_HIERARCHY.SALES_TERRITORY_NAME_CODE,BV_BKGS_MEASURE.SALES_REP_NUMBER,SR.ERP_SALES_REP_NAME AS ERP_SALES_REP_NAME,BV_BKGS_MEASURE.ADJUSTMENT_CODE,BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_START_DTM,BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_END_DTM,BV_BKGS_MEASURE.DV_CONTRACT_DURATION,BV_BKGS_MEASURE.XCAT_FLG,BV_BKGS_MEASURE.DSV_FLG,BV_BKGS_MEASURE.DV_FMV_FLG,BV_BKGS_MEASURE.SK_SALES_MOTION_ATTRIB_KEY,RTR.SALES_ORDER_LINE_KEY    AS SMR_SALES_ORDER_LINE_KEY,RTR.SALES_MOTION_CD,RTR.DV_SERVICE_CATEGORY_CD         AS RTR_SERVICE_CATEGORY_CD,RTR.AS_ARCHITECTURE_NAME          AS RTR_AS_ARCHITECTURE_NAME,RTR.TECHNOLOGY_GROUP_ID            AS RTR_TECHNOLOGY_GROUP_ID,RTR.ATTR_PRDT_OFFER_TYPE_NAME AS RTR_OFFER_TYPE,RTR.SK_RENEW_CONTRACT_LINE_ID      AS RTR_RENEW_CONTRACT_LINE_ID,RTR.AS_TS_CODE                    AS RTR_AS_TS_CODE,RTR.DV_ENTERPRISE_INV_SKU_ID AS RTR_SRC_ENTERPRISE_INV_SKU_ID,RTR.PRODUCT_CLASS                  AS RTR_PRODUCT_CLASS,RTR.TRANSACTION_CR_PARTY_KEY AS RTR_TRANSACTION_CR_PARTY_KEY,RTR.HQ_CR_PRTY_KEY                AS RTR_HQ_CR_PRTY_KEY,RTR.RENEWAL_REF_ID                AS RTR_RENEWAL_REF_ID,RTR.RENEWAL_REF_CD AS RTR_RENEWAL_REF_CD,RTR.SMR_TAGGING_FAILURE_RSN_CD    AS RTR_SMR_TAGGING_FAILURE_RSN_CD,RTR.SALES_MOTION_TIMING_CD AS RTR_SALES_MOTION_TIMING_CD,RTR.MANUAL_OVERRIDE_ROLE          AS RTR_MANUAL_OVERRIDE_ROLE,RTR.REQUESTING_CSCO_WRKR_PRTY_KEY AS RTR_REQUESTING_CSCO_WRKR_PRTY_KEY,RTR.SLS_MTN_CORRECTION_CASE_NUM    AS RTR_SLS_MTN_CORRECTION_CASE_NUM,RTR.SLS_MTN_CORRECTION_CMNT AS RTR_SLS_MTN_CORRECTION_CMNT,RTR.DV_ALLOCATION_PCT,BV_BKGS_MEASURE.SERVICE_FLG,BV_BKGS_MEASURE.DD_COMP_US_NET_PRICE_AMOUNT*COALESCE(RTR.DV_ALLOCATION_PCT,1)*COALESCE(BP.ALLOCATION_PERCENTAGE,1)*COALESCE(BE.PRDT_FAMILY_ALLOCATION_PCT,1) AS DD_COMP_US_NET_PRICE_AMOUNT,BV_BKGS_MEASURE.DV_AR_TRX_LINE_KEY,BV_BKGS_MEASURE.AR_TRX_KEY,ART.BK_AR_TRX_NUMBER AS BK_AR_TRX_NUMBER,ART.AR_TRX_REASON_CODE AS AR_TRX_REASON_CODE,BV_BKGS_MEASURE.ADJUSTMENT_DESCR_KEY,BV_BKGS_MEASURE.CORPORATE_BOOKINGS_FLG,BV_BKGS_MEASURE.DV_ATTRIBUTION_CD,BV_BKGS_MEASURE.SO_SBSCRPTN_ITM_SLS_TRX_KEY   AS MANUAL_TRX_KEY,BV_BKGS_MEASURE.BK_SALES_ADJ_LINE_NUMBER_INT,BV_BKGS_MEASURE.BK_SALES_ADJ_NUMBER_INT,SAL.IDE_IFC_COMMENT_1_TXT,SAL.IDE_IFC_COMMENT_2_TXT,SAL.IDE_IFC_COMMENT_3_TXT,SAL.IDE_IFC_COMMENT_4_TXT,SAL.IDE_IFC_COMMENT_5_TXT,SAL.IDE_IFC_DESCRIPTION_TXT,RB.UPLOADED_BY_ERP_USER_NAME,RB.MANUAL_TRANSACTION_TYPE_CD,RB.MANUAL_TRANSACTION_USAGE_CD,RB.MANUAL_TRX_BOOKING_REVENUE_CD,CURRENT_DATE AS CURRENT_SNAPSHOT_DT --,PREVIOUS_SNAPSHOT_DT
,BV_BKGS_MEASURE.DV_ANNUALIZED_US_NET_AMT*COALESCE(RTR.DV_ALLOCATION_PCT,1)*COALESCE(BP.ALLOCATION_PERCENTAGE,1)*COALESCE(BE.PRDT_FAMILY_ALLOCATION_PCT,1),
	                CAST(RTR.START_TV_DTM AS DATE) AS START_TV_DT,
	                BV_BKGS_MEASURE.SK_OFFER_ATTRIBUTION_ID_INT AS OA_ID,
	                BP.PRODUCT_FAMILY_DESCRIPTION AS PRODUCT_FAMILY,
	                BP.RU_BK_SERVICE_PROGRAM_ID   AS SERVICE_PROGRAM,
	                BP.RU_SERVICE_LEVEL_GROUP_CODE  AS SERVICE_LEVEL,
	                -999 AS ENTERPRISE_SKU,
	                BV_FISCAL_DAY_TO_YEAR.FISCAL_QUARTER_NAME AS FISCAL_QUARTER,
	                BV_FISCAL_DAY_TO_YEAR.FISCAL_MONTH_NAME AS FISCAL_MONTH,
	                BV_SALES_HIERARCHY.L3_SALES_TERRITORY_DESCR AS SALES_LEVEL_3,
	                DE.BRANCH_PRIMARY_NAME AS CUSTOMER_HQ_NAME,
	                BV_SALES_ORDER_LINE_TV.REVENUE_TYPE_CODE AS RSC_CODE,
	                DE.BRANCH_PRIMARY_NAME AS DEAL_HQ_CR_PARTY_NAME,
	                BV_SALES_ORDER_LINE_TV.TRX_BOOKING_SRC_CD AS LINE_SOURCE,
	                NULL AS LINE_CREATION_DATE,
	                RTR.ATTR_PRDT_OFFER_TYPE_NAME||RTR.SALES_MOTION_CD||
	            CASE
	                WHEN RENEWAL_REF_CD IN ( 'RENEW COVERED LINE ID',
			'SUBSCRIPTION REFERENCE ID','RENEW INSTANCE ID') THEN RENEWAL_REF_ID 
				ELSE NULL
	            END||
	            CASE
	                WHEN RENEWAL_REF_CD IN ( 'RENEW COVERED LINE ID',
			'SUBSCRIPTION REFERENCE ID','RENEW INSTANCE ID')   THEN RENEWAL_REF_CD 
				ELSE NULL
	            END||
	            CASE
	                WHEN RTR.SALES_MOTION_CD IN 'UNKNOWN' THEN RTR.SMR_TAGGING_FAILURE_RSN_CD 
				ELSE NULL
	            END AS SMR_RULE_TYPE,
	                NULL AS INHERITANCE_FLAG,
	                BE.BK_BUSINESS_ENTITY_NAME AS BE,
	                BE.BK_SUB_BUSINESS_ENTITY_NAME AS SUB_BE,
	                BV_SALES_ORDER_LINE_TV.ITEM_CATEGORY_DESCRIPTION AS ITEM_CATEGORY_NAME,
	                BV_SALES_ORDER_LINE_TV.BK_SO_NUMBER_INT AS DD_BK_SO_NUMBER_INT,
	                NULL AS MATCHING_MTHD_FOR_TAGGING_NAME,
	                BV_SALES_HIERARCHY.L4_SALES_TERRITORY_DESCR,
	                BV_SALES_HIERARCHY.L5_SALES_TERRITORY_DESCR,
	                BV_SALES_HIERARCHY.L6_SALES_TERRITORY_DESCR,
	                'UNKNOWN' AS SMR_OFFER_TYPE,
	                NULL AS SMC_SOURCE_TAG,
	                NULL AS WEB_ORDER_ID,
	                NULL AS ORDER_CREATED_DT,
	                NULL AS SUBSCRIPTION_REFERENCE_ID,
	                NULL AS SUBSCRIPTION_START_DT,
	                NULL AS SUBSCRIPTION_END_DT,
	                BV_SALES_HIERARCHY.SALES_TERRITORY_DESCR AS SHARE_NODE_NAME,
	                CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM,
	                USER EDW_CREATE_USER,
	                CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM,
	                USER EDW_UPDATE_USER
	            FROM	$$SLSORDVWDB.N_BKGS_MEASURE BV_BKGS_MEASURE  
				INNER JOIN $$COMREFVWDB.R_SALES_HIERARCHY BV_SALES_HIERARCHY 
		ON BV_BKGS_MEASURE.SALES_TERRITORY_KEY=BV_SALES_HIERARCHY.SALES_TERRITORY_KEY 
				INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE_TV BV_SALES_ORDER_LINE_TV 
		ON BV_BKGS_MEASURE.DV_SALES_ORDER_LINE_KEY=BV_SALES_ORDER_LINE_TV.SALES_ORDER_LINE_KEY  
				AND BV_SALES_ORDER_LINE_TV.END_TV_DATETIME ='3500-01-01 00:00:00'    
				INNER JOIN $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR BV_FISCAL_DAY_TO_YEAR 
		ON BV_BKGS_MEASURE.BOOKINGS_PROCESS_DATE=BV_FISCAL_DAY_TO_YEAR.CALENDAR_DATE   
				INNER JOIN $$SLSORDVWDB.MT_BKG_SLS_MOTION_ATTRIBUTION RTR 
		ON BV_BKGS_MEASURE.SK_SALES_MOTION_ATTRIB_KEY = RTR.SK_SALES_MOTION_ATTRIB_KEY
				AND RTR.END_TV_DTM > CURRENT_TIMESTAMP(0) 
				-- Replaced with Volatile Table.
				INNER JOIN VOL_R_PRODUCTS BP 
		ON BP.PRODUCT_KEY = BV_BKGS_MEASURE.PRODUCT_KEY 
				INNER JOIN $$STGDB.WI_SFH_RUP ST 
		ON ST.ITEM_KEY = BV_BKGS_MEASURE.DV_PRODUCT_KEY 
				INNER JOIN (
		            SELECT	SALES_ORDER_KEY,
		                BK_SO_SOURCE_NAME,
		                SALES_ORDER_PROGRAM_TYPE_NAME,
		                trunc (BK_SO_SRC_CRT_DATETIME) AS ORDER_LINE_CREATION_DATE,
		                Trunc(RU_CISCO_BOOKED_DATETIME) AS ORDER_HEADER_BOOKED_DATE,
		                CANCELLED_FLAG AS ORDER_CANCELLED_FLAG
		                FROM	$$SLSORDVWDB.N_SALES_ORDER ) SO  
		ON SO.SALES_ORDER_KEY = BV_SALES_ORDER_LINE_TV.SALES_ORDER_KEY   
						INNER JOIN (
		            SELECT	SALES_REP_NUM,
		                ERP_SALES_REP_NAME
		                FROM	$$COMREFVWDB.MT_ERP_SALES_REP) SR  
		ON SR.SALES_REP_NUM = BV_BKGS_MEASURE.SALES_REP_NUMBER	 
						INNER JOIN        (
		            SELECT	EC.END_CUSTOMER_KEY,
		                EC.CUSTOMER_PARTY_KEY,
		                EC.ERP_WIPS_SITE_USE_ID_INT END_CUSTOMER_ID,
		                EC.ERP_WIPS_CUSTOMER_NAME END_CUSTOMER_NAME,
		                EC.ERP_WIPS_ISO_COUNTRY_CD,
		                ECH.BRANCH_PARTY_SSOT_PARTY_ID_INT END_CUST_CRPARTY_ID,
		                ECH.BRANCH_HQ_BRANCH_CD,
		                ECH.BRANCH_PRIMARY_NAME,
		                
		                CASE
		                    WHEN BRANCH_HQ_BRANCH_CD = 'BR' THEN HQ_PARTY_SSOT_PARTY_ID_INT 
					ELSE BRANCH_PARTY_SSOT_PARTY_ID_INT
		                END AS HQ_CRPARTY_ID,
		                    
		                CASE
		                    WHEN BRANCH_HQ_BRANCH_CD = 'BR' THEN HQ_PRIMARY_NAME 
					ELSE BRANCH_PRIMARY_NAME
		                END AS HQ_CRPARTY_NAME,
		                    ECH.GU_PARTY_SSOT_PARTY_ID_INT GU_ID,
		                    ECH.GU_PRIMARY_NAME
		                FROM	$$COMREFVWDB.MT_ERP_POS_ENDCUST EC                
						JOIN $$COMREFVWDB.MT_ENDCUST_CUSTOMER_PARTY_HIER ECH                   
						ON (EC.END_CUSTOMER_KEY = ECH.END_CUSTOMER_KEY)) DE           
		ON (DE.END_CUSTOMER_KEY = BV_BKGS_MEASURE.END_CUSTOMER_KEY)    
					LEFT JOIN (
		            SELECT	MANUAL_TRX_KEY,
		                BK_SALES_ADJ_LINE_NUMBER_INT,
		                BK_SALES_ADJ_NUMBER_INT,
		                IDE_IFC_COMMENT_1_TXT,
		                IDE_IFC_COMMENT_2_TXT,
		                IDE_IFC_COMMENT_3_TXT,
		                IDE_IFC_COMMENT_4_TXT,
		                IDE_IFC_COMMENT_5_TXT,
		                IDE_IFC_DESCRIPTION_TXT
		                FROM	$$SLSORDVWDB.N_SALES_ADJUSTMENT_LINE) SAL 
		ON BV_BKGS_MEASURE.BOOKINGS_MEASURE_KEY = SAL.BK_SALES_ADJ_LINE_NUMBER_INT			 
					LEFT JOIN (
		            SELECT	MANUAL_TRX_KEY,
		                UPLOADED_BY_ERP_USER_NAME,
		                MANUAL_TRANSACTION_TYPE_CD,
		                MANUAL_TRANSACTION_USAGE_CD,
		                MANUAL_TRX_BOOKING_REVENUE_CD
		                FROM	$$SLSORDVWDB.N_SALES_ADJ_REBOK_MNL_TRX) RB 
		ON SAL.MANUAL_TRX_KEY = RB.MANUAL_TRX_KEY	 
					LEFT OUTER JOIN (
		            SELECT	AR_TRX_KEY,
		                BK_AR_TRX_NUMBER,
		                AR_TRX_REASON_CODE
		                FROM	$$FINLGLVWDB.N_AR_TRX) ART           
		ON (BV_BKGS_MEASURE.AR_TRX_KEY = ART.AR_TRX_KEY)   
					INNER JOIN $$COMREFVWDB.MT_BE_HIER_PRDT_FAMILY_ALLOC  BE     
					ON ( BE.ITEM_KEY = BV_BKGS_MEASURE.PRODUCT_KEY      
		AND BE.FISCAL_YEAR_QUARTER_NUMBER_INT = BV_BKGS_MEASURE.FISCAL_YEAR_QUARTER_NUMBER_INT    
					AND BE.BK_BUSINESS_ENTITY_TYPE_CD = 'I' )
	            WHERE	BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('ERP' )
	                AND  BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_NUMBER_INT >= 2020 --AND BV_FISCAL_DAY_TO_YEAR.DV_FISCAL_QUARTER_ID >='2020Q1'
	                 --AND BV_BKGS_MEASURE.SUMMARY_QUOTE_FLG IN ( 'N' )
	                
	                AND  BV_BKGS_MEASURE.DV_REVENUE_RECOGNITION_FLG = 'Y'
	                AND  BV_BKGS_MEASURE.SERVICE_FLG IN ('Y')
	                AND  BV_BKGS_MEASURE.CORPORATE_BOOKINGS_FLG IN ('Y')
	                AND  BV_BKGS_MEASURE.DV_ATTRIBUTION_CD IN ('ATTRIBUTED',
			'STANDALONE')
	                AND  NOT EXISTS (
		            SELECT	1
		                FROM	$$SLSORDVWDB.MT_SALES_MOTION_RPT RPT
		                WHERE	RPT.BOOKINGS_MEASURE_KEY =BV_BKGS_MEASURE.BOOKINGS_MEASURE_KEY
		                    AND  RPT.BOOKINGS_PROCESS_DATE=BV_BKGS_MEASURE.BOOKINGS_PROCESS_DATE
		                    AND  RPT.BKGS_MEASURE_TRANS_TYPE_CODE=BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE
		                 --AND RPT.SUMMARY_QUOTE_FLG='N'
		                )) AS PM_VQFJM7SBPNMHK2HSO3Q3R26E2HY (BOOKINGS_MEASURE_KEY,FISCAL_YEAR_NUMBER_INT, FISCAL_QUARTER_ID, FISCAL_YEAR_MONTH_INT,FISCAL_WEEK_NUMBER_INT, FISCAL_YR_MNTH_WEEK_INT, BOOKINGS_PROCESS_DATE,BKGS_MEASURE_TRANS_TYPE_CODE, DEAL_ID, SALES_ORDER_KEY, BK_SO_SOURCE_NAME,SALES_ORDER_PROGRAM_TYPE_NAME, ORDER_CANCELLED_FLAG, ORDER_HEADER_BOOKED_DATE,SOURCE_ORDER_NUM_INT, DV_SALES_ORDER_LINE_KEY, BK_POS_TRANSACTION_ID_INT,SALES_ORDER_LINE_ID, ORDER_LINE_CREATION_DATE, CISCO_BOOKED_DATETIME,CUST_EXPECTED_START_DT, LINE_SOURCE_NAME, LINE_STATUS_CD, SALES_ORDER_CATEGORY_TYPE,RU_SERVICE_CONTRACT_NUMBER, ORDER_LINE_CANCELLED_FLAG, CONTRACT_DURATION,CONTRACT_START_DATE, CONTRACT_END_DATE, ORDERED_ITEM, ORDERED_SERVICE,SUMMARY_QUOTE_FLG, PRODUCT_KEY, ATTRIBUTED_PRODUCT_ID, RU_BK_SERVICE_PROD_SUBGROUP_ID,FINANCE_BU_SW_TYPE, PRDT_SETUP_CLASSIFICATION_CD, RU_BK_PRODUCT_FAMILY_ID,RU_COMMISSIONABLE_STATUS_CODE, BK_SERVICE_CATEGORY_ID, BK_ALLOCATED_SERVC_GROUP_ID,BK_PRODUCT_SUBGROUP_ID, ALLOCATION_PERCENTAGE, END_CUSTOMER_KEY,END_CUSTOMER_ID, END_CUSTOMER_NAME, ERP_WIPS_ISO_COUNTRY_CD,END_CUST_CRPARTY_ID, BRANCH_HQ_BRANCH_CD, HQ_CRPARTY_ID, HQ_CRPARTY_NAME,GU_ID, GU_PRIMARY_NAME, SALES_TERRITORY_KEY, SALES_COVERAGE_CODE,SALES_SUBCOVERAGE_CODE, L1_SALES_TERRITORY_DESCR, L2_SALES_TERRITORY_DESCR,SALES_TERRITORY_NAME_CODE, SALES_REP_NUMBER, ERP_SALES_REP_NAME,ADJUSTMENT_CODE, RU_SERVICE_CONTRACT_START_DTM, RU_SERVICE_CONTRACT_END_DTM,DV_CONTRACT_DURATION, XCAT_FLG, DSV_FLG, DV_FMV_FLG, SK_SALES_MOTION_ATTRIB_KEY,SMR_SALES_ORDER_LINE_KEY, SALES_MOTION_CD, RTR_SERVICE_CATEGORY_CD,RTR_AS_ARCHITECTURE_NAME, RTR_TECHNOLOGY_GROUP_ID, RTR_OFFER_TYPE,RTR_RENEW_CONTRACT_LINE_ID, RTR_AS_TS_CODE, RTR_SRC_ENTERPRISE_INV_SKU_ID,RTR_PRODUCT_CLASS, RTR_TRANSACTION_CR_PARTY_KEY, RTR_HQ_CR_PRTY_KEY,RTR_RENEWAL_REF_ID, RTR_RENEWAL_REF_CD, RTR_SMR_TAGGING_FAILURE_RSN_CD,RTR_SALES_MOTION_TIMING_CD, RTR_MANUAL_OVERRIDE_ROLE, REQUESTING_CSCO_WRKR_PRTY_KEY,SLS_MTN_CORRECTION_CASE_NUM, SLS_MTN_CORRECTION_CMNT, DV_ALLOCATION_PCT,SERVICE_FLG, DD_COMP_US_NET_PRICE_AMOUNT, DV_AR_TRX_LINE_KEY,AR_TRX_KEY, BK_AR_TRX_NUMBER, AR_TRX_REASON_CODE, ADJUSTMENT_DESCR_KEY,CORPORATE_BOOKINGS_FLG, DV_ATTRIBUTION_CD, MANUAL_TRX_KEY, BK_SALES_ADJ_LINE_NUMBER_INT,BK_SALES_ADJ_NUMBER_INT, IDE_IFC_COMMENT_1_TXT, IDE_IFC_COMMENT_2_TXT,IDE_IFC_COMMENT_3_TXT, IDE_IFC_COMMENT_4_TXT, IDE_IFC_COMMENT_5_TXT,IDE_IFC_DESCRIPTION_TXT, UPLOADED_BY_ERP_USER_NAME, MANUAL_TRANSACTION_TYPE_CD,MANUAL_TRANSACTION_USAGE_CD, MANUAL_TRX_BOOKING_REVENUE_CD, CURRENT_SNAPSHOT_DT,DV_ANNUALIZED_AMT, START_TV_DT, OA_ID, PRODUCT_FAMILY, SERVICE_PROGRAM,SERVICE_LEVEL, ENTERPRISE_SKU, FISCAL_QUARTER, FISCAL_MONTH,SALES_LEVEL_3, CUSTOMER_HQ_NAME, RSC_CODE, DEAL_HQ_CR_PARTY_NAME,LINE_SOURCE, LINE_CREATION_DATE, SMR_RULE_TYPE, INHERITANCE_FLAG,BE, SUB_BE, ITEM_CATEGORY_NAME, DD_BK_SO_NUMBER_INT, MATCHING_MTHD_FOR_TAGGING_NAME,L4_SALES_TERRITORY_DESCR, L5_SALES_TERRITORY_DESCR, L6_SALES_TERRITORY_DESCR,SMR_OFFER_TYPE, SMC_SOURCE_TAG, WEB_ORDER_ID, ORDER_CREATED_DT,SUBSCRIPTION_REFERENCE_ID, SUBSCRIPTION_START_DT, SUBSCRIPTION_END_DT,SHARE_NODE_NAME, EDW_CREATE_DTM, EDW_CREATE_USER, EDW_UPDATE_DTM,EDW_UPDATE_USER);


SQL Query : 
SELECT
BV_BKGS_MEASURE.BOOKINGS_MEASURE_KEY,BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_NUMBER_INT,BV_FISCAL_DAY_TO_YEAR.DV_FISCAL_QUARTER_ID     AS FISCAL_QUARTER_ID,BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_MONTH_INT
,BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_WEEK_NUM_INT AS FISCAL_WEEK_NUMBER_INT,BV_FISCAL_DAY_TO_YEAR.DV_FISCAL_YR_MNTH_WEEK_NUM_INT       AS FISCAL_YR_MNTH_WEEK_INT,BV_BKGS_MEASURE.BOOKINGS_PROCESS_DATE
,BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE,BV_BKGS_MEASURE.DV_DEAL_ID AS DEAL_ID,BV_BKGS_MEASURE.SALES_ORDER_KEY,
SO.BK_SO_SOURCE_NAME
, SO.SALES_ORDER_PROGRAM_TYPE_NAME,
BV_BKGS_MEASURE.CANCELLED_FLG                 AS ORDER_CANCELLED_FLAG,BV_BKGS_MEASURE.DV_BOOKED_DT                  AS ORDER_HEADER_BOOKED_DATE
,BV_BKGS_MEASURE.DV_SOURCE_ORDER_NUM_INT       AS SOURCE_ORDER_NUM_INT,BV_BKGS_MEASURE.DV_SALES_ORDER_LINE_KEY,BV_BKGS_MEASURE.BK_POS_TRANSACTION_ID_INT
,BV_SALES_ORDER_LINE_TV.SK_SO_LINE_ID_INT              AS SALES_ORDER_LINE_ID, SO.ORDER_LINE_CREATION_DATE,
BV_SALES_ORDER_LINE_TV.CISCO_BOOKED_DATETIME,BV_SALES_ORDER_LINE_TV.CUST_EXPECTED_START_DT         AS CUST_EXPECTED_START_DATE
,BV_SALES_ORDER_LINE_TV.BK_SO_SRC_NAME AS LINE_SOURCE_NAME,BV_SALES_ORDER_LINE_TV.LINE_STATUS_CD,BV_SALES_ORDER_LINE_TV.SALES_ORDER_CATEGORY_TYPE
,BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_NUMBER        AS RU_SERVICE_CONTRACT_NUMBER,
BV_SALES_ORDER_LINE_TV.CANCELLED_FLAG AS ORDER_LINE_CANCELLED_FLAG,
 Coalesce(NullIfZero(CASE WHEN BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('SLS_ADJ','POS_ADJ','POS')
THEN Cast((Cast(cast(BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_END_DTM as date) - cast(BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_START_DTM as date) AS INTEGER)*12(FLOAT))/365 AS DECIMAL(18,0))
ELSE Cast((Cast(cast(BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_END_DTM as date ) - cast(BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_START_DTM as date) AS INTEGER)*12(FLOAT))/365 AS DECIMAL(18,0))
END ) , BV_BKGS_MEASURE.DV_CONTRACT_DURATION               )  AS CONTRACT_DURATION,
 CASE WHEN BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('SLS_ADJ', 'POS_ADJ', 'POS') THEN BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_START_DTM
      ELSE BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_START_DTM END AS CONTRACT_START_DATE,
 CASE WHEN BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('SLS_ADJ', 'POS_ADJ', 'POS') THEN BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_END_DTM
      ELSE BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_END_DTM END AS CONTRACT_END_DATE,	  
'UNKNOWN'  AS ORDERED_ITEM
,BP.RU_BK_SERVICE_PROD_SUBGROUP_ID  AS ORDERED_SERVICE,BV_BKGS_MEASURE.SUMMARY_QUOTE_FLG,BP.ITEM_KEY AS PRODUCT_KEY,BP.BK_PRODUCT_ID  AS ATTRIBUTED_PRODUCT_ID,BP.RU_BK_SERVICE_PROD_SUBGROUP_ID  AS RU_BK_SERVICE_PROD_SUBGROUP_ID
,SWSS.BK_GSP_ATTR_VAL_TXT AS  FINANCE_BU_SW_TYPE,BP.PRDT_SETUP_CLASSIFICATION_CD,BP.RU_BK_PRODUCT_FAMILY_ID AS RU_BK_PRODUCT_FAMILY_ID
,BP.RU_COMMISSIONABLE_STATUS_CODE     AS RU_COMMISSIONABLE_STATUS_CODE,SFH.BK_SERVICE_CATEGORY_ID,SFH.BK_ALLOCATED_SERVC_GROUP_ID,SFH.BK_PRODUCT_SUBGROUP_ID
,SFH.ALLOCATION_PERCENTAGE,  BV_BKGS_MEASURE.END_CUSTOMER_KEY
,DE.END_CUSTOMER_ID
,DE.END_CUSTOMER_NAME,DE.ERP_WIPS_ISO_COUNTRY_CD,DE.END_CUST_CRPARTY_ID,DE.BRANCH_HQ_BRANCH_CD,DE.HQ_CRPARTY_ID,DE.HQ_CRPARTY_NAME,
DE.GU_ID,DE.GU_PRIMARY_NAME
,BV_BKGS_MEASURE.SALES_TERRITORY_KEY
,BV_SALES_HIERARCHY.SALES_COVERAGE_CODE,BV_SALES_HIERARCHY.SALES_SUBCOVERAGE_CODE,BV_SALES_HIERARCHY.L1_SALES_TERRITORY_DESCR,BV_SALES_HIERARCHY.L2_SALES_TERRITORY_DESCR,BV_SALES_HIERARCHY.SALES_TERRITORY_NAME_CODE
,BV_BKGS_MEASURE.SALES_REP_NUMBER,SR.ERP_SALES_REP_NAME AS ERP_SALES_REP_NAME,BV_BKGS_MEASURE.ADJUSTMENT_CODE
,BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_START_DTM,BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_END_DTM,BV_BKGS_MEASURE.DV_CONTRACT_DURATION,BV_BKGS_MEASURE.XCAT_FLG,BV_BKGS_MEASURE.DSV_FLG,
BV_BKGS_MEASURE.DV_FMV_FLG,BV_BKGS_MEASURE.SK_SALES_MOTION_ATTRIB_KEY,RTR.SALES_ORDER_LINE_KEY    AS SMR_SALES_ORDER_LINE_KEY,RTR.SALES_MOTION_CD
,RTR.DV_SERVICE_CATEGORY_CD         AS RTR_SERVICE_CATEGORY_CD,RTR.AS_ARCHITECTURE_NAME          AS RTR_AS_ARCHITECTURE_NAME,RTR.TECHNOLOGY_GROUP_ID            AS RTR_TECHNOLOGY_GROUP_ID,
RTR.ATTR_PRDT_OFFER_TYPE_NAME AS RTR_OFFER_TYPE,RTR.SK_RENEW_CONTRACT_LINE_ID      AS RTR_RENEW_CONTRACT_LINE_ID,RTR.AS_TS_CODE                    AS RTR_AS_TS_CODE,
RTR.DV_ENTERPRISE_INV_SKU_ID AS RTR_SRC_ENTERPRISE_INV_SKU_ID,RTR.PRODUCT_CLASS                  AS RTR_PRODUCT_CLASS
,RTR.TRANSACTION_CR_PARTY_KEY AS RTR_TRANSACTION_CR_PARTY_KEY,RTR.HQ_CR_PRTY_KEY                AS RTR_HQ_CR_PRTY_KEY,RTR.RENEWAL_REF_ID                AS RTR_RENEWAL_REF_ID,
RTR.RENEWAL_REF_CD AS RTR_RENEWAL_REF_CD,RTR.SMR_TAGGING_FAILURE_RSN_CD    AS RTR_SMR_TAGGING_FAILURE_RSN_CD,
RTR.SALES_MOTION_TIMING_CD AS RTR_SALES_MOTION_TIMING_CD,RTR.MANUAL_OVERRIDE_ROLE          AS RTR_MANUAL_OVERRIDE_ROLE
,RTR.REQUESTING_CSCO_WRKR_PRTY_KEY AS RTR_REQUESTING_CSCO_WRKR_PRTY_KEY,RTR.SLS_MTN_CORRECTION_CASE_NUM    AS RTR_SLS_MTN_CORRECTION_CASE_NUM,
RTR.SLS_MTN_CORRECTION_CMNT AS RTR_SLS_MTN_CORRECTION_CMNT,RTR.DV_ALLOCATION_PCT
,BV_BKGS_MEASURE.SERVICE_FLG,BV_BKGS_MEASURE.DD_COMP_US_NET_PRICE_AMOUNT*Coalesce(RTR.DV_ALLOCATION_PCT,1)*Coalesce(SFH.ALLOCATION_PERCENTAGE,1)*Coalesce(BE.PRDT_FAMILY_ALLOCATION_PCT,1) AS DD_COMP_US_NET_PRICE_AMOUNT,BV_BKGS_MEASURE.DV_AR_TRX_LINE_KEY
,BV_BKGS_MEASURE.AR_TRX_KEY,ART.BK_AR_TRX_NUMBER AS BK_AR_TRX_NUMBER,ART.AR_TRX_REASON_CODE AS AR_TRX_REASON_CODE,
BV_BKGS_MEASURE.ADJUSTMENT_DESCR_KEY,BV_BKGS_MEASURE.CORPORATE_BOOKINGS_FLG,BV_BKGS_MEASURE.DV_ATTRIBUTION_CD,
BV_BKGS_MEASURE.SO_SBSCRPTN_ITM_SLS_TRX_KEY   AS MANUAL_TRX_KEY,BV_BKGS_MEASURE.BK_SALES_ADJ_LINE_NUMBER_INT,BV_BKGS_MEASURE.BK_SALES_ADJ_NUMBER_INT
,SAL.IDE_IFC_COMMENT_1_TXT,SAL.IDE_IFC_COMMENT_2_TXT,SAL.IDE_IFC_COMMENT_3_TXT,SAL.IDE_IFC_COMMENT_4_TXT,SAL.IDE_IFC_COMMENT_5_TXT,SAL.IDE_IFC_DESCRIPTION_TXT,
RB.UPLOADED_BY_ERP_USER_NAME,RB.MANUAL_TRANSACTION_TYPE_CD
,RB.MANUAL_TRANSACTION_USAGE_CD,RB.MANUAL_TRX_BOOKING_REVENUE_CD,CURRENT_DATE AS CURRENT_SNAPSHOT_DT--,PREVIOUS_SNAPSHOT_DT
,BV_BKGS_MEASURE.DV_ANNUALIZED_US_NET_AMT*Coalesce(RTR.DV_ALLOCATION_PCT,1)*Coalesce(SFH.ALLOCATION_PERCENTAGE,1)*Coalesce(BE.PRDT_FAMILY_ALLOCATION_PCT,1)
,CAST(RTR.START_TV_DTM AS DATE) AS START_TV_DT,    BV_BKGS_MEASURE.SK_OFFER_ATTRIBUTION_ID_INT AS OA_ID,
BP.PRODUCT_FAMILY_DESCRIPTION AS PRODUCT_FAMILY,
BP.RU_BK_SERVICE_PROGRAM_ID   AS SERVICE_PROGRAM,
BP.RU_SERVICE_LEVEL_GROUP_CODE  AS SERVICE_LEVEL,
  -999 AS ENTERPRISE_SKU,
BV_FISCAL_DAY_TO_YEAR.FISCAL_QUARTER_NAME AS FISCAL_QUARTER,
BV_FISCAL_DAY_TO_YEAR.FISCAL_MONTH_NAME AS FISCAL_MONTH,
BV_SALES_HIERARCHY.L3_SALES_TERRITORY_DESCR AS SALES_LEVEL_3,
DE.BRANCH_PRIMARY_NAME AS CUSTOMER_HQ_NAME,
BV_SALES_ORDER_LINE_TV.REVENUE_TYPE_CODE AS RSC_CODE,
DE.BRANCH_PRIMARY_NAME AS DEAL_HQ_CR_PARTY_NAME,
BV_SALES_ORDER_LINE_TV.TRX_BOOKING_SRC_CD AS LINE_SOURCE,
NULL AS LINE_CREATION_DATE,
RTR.ATTR_PRDT_OFFER_TYPE_NAME||RTR.SALES_MOTION_CD||CASE WHEN RENEWAL_REF_CD IN ( 'RENEW COVERED LINE ID','SUBSCRIPTION REFERENCE ID','RENEW INSTANCE ID') THEN RENEWAL_REF_ID ELSE NULL END|| CASE WHEN RENEWAL_REF_CD IN ( 'RENEW COVERED LINE ID','SUBSCRIPTION REFERENCE ID','RENEW INSTANCE ID') 
 THEN RENEWAL_REF_CD ELSE NULL END||CASE WHEN RTR.SALES_MOTION_CD IN 'UNKNOWN' THEN RTR.SMR_TAGGING_FAILURE_RSN_CD ELSE NULL 
 END AS SMR_RULE_TYPE, 
 NULL AS INHERITANCE_FLAG,
BE.BK_BUSINESS_ENTITY_NAME AS BE,
BE.BK_SUB_BUSINESS_ENTITY_NAME AS SUB_BE,
BV_SALES_ORDER_LINE_TV.ITEM_CATEGORY_DESCRIPTION AS ITEM_CATEGORY_NAME,
BV_SALES_ORDER_LINE_TV.BK_SO_NUMBER_INT AS DD_BK_SO_NUMBER_INT,
NULL AS MATCHING_MTHD_FOR_TAGGING_NAME,
BV_SALES_HIERARCHY.L4_SALES_TERRITORY_DESCR,
BV_SALES_HIERARCHY.L5_SALES_TERRITORY_DESCR,
BV_SALES_HIERARCHY.L6_SALES_TERRITORY_DESCR,
'UNKNOWN' AS SMR_OFFER_TYPE,
NULL AS SMC_SOURCE_TAG,
NULL AS WEB_ORDER_ID,             
NULL AS ORDER_CREATED_DT,              
NULL AS SUBSCRIPTION_REFERENCE_ID,     
NULL AS SUBSCRIPTION_START_DT,
NULL AS SUBSCRIPTION_END_DT,
BV_SALES_HIERARCHY.SALES_TERRITORY_DESCR AS SHARE_NODE_NAME,
CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM                ,
USER EDW_CREATE_USER       ,        
CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM       ,         
USER EDW_UPDATE_USER  
FROM $$SLSORDVWDB.N_BKGS_MEASURE BV_BKGS_MEASURE 
INNER JOIN $$COMREFVWDB.R_SALES_HIERARCHY BV_SALES_HIERARCHY
ON BV_BKGS_MEASURE.SALES_TERRITORY_KEY=BV_SALES_HIERARCHY.SALES_TERRITORY_KEY
INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE_TV BV_SALES_ORDER_LINE_TV
ON BV_BKGS_MEASURE.DV_SALES_ORDER_LINE_KEY=BV_SALES_ORDER_LINE_TV.SALES_ORDER_LINE_KEY
 AND BV_SALES_ORDER_LINE_TV.END_TV_DATETIME ='3500-01-01 00:00:00'   
INNER JOIN $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR BV_FISCAL_DAY_TO_YEAR
ON BV_BKGS_MEASURE.BOOKINGS_PROCESS_DATE=BV_FISCAL_DAY_TO_YEAR.CALENDAR_DATE  
INNER JOIN $$SLSORDVWDB.MT_BKG_SLS_MOTION_ATTRIBUTION RTR
ON BV_BKGS_MEASURE.SK_SALES_MOTION_ATTRIB_KEY = RTR.SK_SALES_MOTION_ATTRIB_KEY
AND RTR.END_TV_DTM > CURRENT_TIMESTAMP(0)
INNER JOIN $$COMREFVWDB.R_PRODUCTS BP
ON BP.ITEM_KEY = BV_BKGS_MEASURE.PRODUCT_KEY
INNER JOIN $$STGDB.WI_SFH_RUP ST
ON ST.ITEM_KEY = BV_BKGS_MEASURE.DV_PRODUCT_KEY
INNER JOIN (SELECT SALES_ORDER_KEY,BK_SO_SOURCE_NAME, SALES_ORDER_PROGRAM_TYPE_NAME, trunc (BK_SO_SRC_CRT_DATETIME) AS ORDER_LINE_CREATION_DATE, Trunc(RU_CISCO_BOOKED_DATETIME) AS ORDER_HEADER_BOOKED_DATE,  CANCELLED_FLAG AS ORDER_CANCELLED_FLAG 
 FROM $$SLSORDVWDB.N_SALES_ORDER ) SO
 ON SO.SALES_ORDER_KEY = BV_SALES_ORDER_LINE_TV.SALES_ORDER_KEY
LEFT JOIN (SELECT BK_PRDT_SUBGROUP_ID,BK_GSP_ATTR_VAL_TXT  FROM $$SERVICEVWDB.N_GENERIC_SVC_PRDT_ATTR WHERE 1 = 1 AND BK_GSP_ATTR_NAME = 'SW SERVICE CATEGORY') SWSS
 ON SWSS.BK_PRDT_SUBGROUP_ID =  BP.RU_BK_SERVICE_PROD_SUBGROUP_ID
 INNER JOIN (SELECT SALES_REP_NUM, ERP_SALES_REP_NAME FROM $$COMREFVWDB.MT_ERP_SALES_REP) SR
 ON SR.SALES_REP_NUM = BV_BKGS_MEASURE.SALES_REP_NUMBER  
INNER JOIN (SELECT  ITEM_KEY,BK_PRODUCT_SUBGROUP_ID, BK_SERVICE_CATEGORY_ID,  BK_ALLOCATED_SERVC_GROUP_ID,ALLOCATION_PERCENTAGE
FROM $$COMREFVWDB.MT_SVC_FINANCE_HIERARCHY GROUP BY  1,2,3,4,5) SFH
ON SFH.ITEM_KEY = BP.ITEM_KEY
	 INNER JOIN
       (SELECT EC.END_CUSTOMER_KEY,
               EC.CUSTOMER_PARTY_KEY,
               EC.ERP_WIPS_SITE_USE_ID_INT END_CUSTOMER_ID,
               EC.ERP_WIPS_CUSTOMER_NAME END_CUSTOMER_NAME,
               EC.ERP_WIPS_ISO_COUNTRY_CD,
               ECH.BRANCH_PARTY_SSOT_PARTY_ID_INT END_CUST_CRPARTY_ID,
               ECH.BRANCH_HQ_BRANCH_CD,
                      ECH.BRANCH_PRIMARY_NAME ,
               CASE WHEN BRANCH_HQ_BRANCH_CD = 'BR' THEN HQ_PARTY_SSOT_PARTY_ID_INT ELSE BRANCH_PARTY_SSOT_PARTY_ID_INT END AS HQ_CRPARTY_ID,
               CASE WHEN BRANCH_HQ_BRANCH_CD = 'BR' THEN HQ_PRIMARY_NAME ELSE BRANCH_PRIMARY_NAME END AS HQ_CRPARTY_NAME,
               ECH.GU_PARTY_SSOT_PARTY_ID_INT GU_ID,
               ECH.GU_PRIMARY_NAME
          FROM $$COMREFVWDB.MT_ERP_POS_ENDCUST EC
               JOIN $$COMREFVWDB.MT_ENDCUST_CUSTOMER_PARTY_HIER ECH
                  ON (EC.END_CUSTOMER_KEY = ECH.END_CUSTOMER_KEY)) DE
          ON (DE.END_CUSTOMER_KEY = BV_BKGS_MEASURE.END_CUSTOMER_KEY)
    LEFT JOIN (SELECT MANUAL_TRX_KEY,
                               BK_SALES_ADJ_LINE_NUMBER_INT,
                               BK_SALES_ADJ_NUMBER_INT,
                               IDE_IFC_COMMENT_1_TXT,
                               IDE_IFC_COMMENT_2_TXT,
                               IDE_IFC_COMMENT_3_TXT,
                               IDE_IFC_COMMENT_4_TXT,
                               IDE_IFC_COMMENT_5_TXT,
                               IDE_IFC_DESCRIPTION_TXT
                          FROM $$SLSORDVWDB.N_SALES_ADJUSTMENT_LINE) SAL
ON BV_BKGS_MEASURE.BOOKINGS_MEASURE_KEY = SAL.BK_SALES_ADJ_LINE_NUMBER_INT			
LEFT JOIN (SELECT MANUAL_TRX_KEY,
                               UPLOADED_BY_ERP_USER_NAME,
                               MANUAL_TRANSACTION_TYPE_CD,
                               MANUAL_TRANSACTION_USAGE_CD,
                               MANUAL_TRX_BOOKING_REVENUE_CD
                          FROM $$SLSORDVWDB.N_SALES_ADJ_REBOK_MNL_TRX) RB
ON SAL.MANUAL_TRX_KEY = RB.MANUAL_TRX_KEY	
LEFT OUTER JOIN (SELECT AR_TRX_KEY, BK_AR_TRX_NUMBER, AR_TRX_REASON_CODE           FROM $$FINLGLVWDB.N_AR_TRX) ART
          ON (BV_BKGS_MEASURE.AR_TRX_KEY = ART.AR_TRX_KEY)  
INNER JOIN $$COMREFVWDB.MT_BE_HIER_PRDT_FAMILY_ALLOC  BE
    ON ( BE.ITEM_KEY = BV_BKGS_MEASURE.PRODUCT_KEY 
    AND BE.FISCAL_YEAR_QUARTER_NUMBER_INT = BV_BKGS_MEASURE.FISCAL_YEAR_QUARTER_NUMBER_INT
    AND BE.BK_BUSINESS_ENTITY_TYPE_CD = 'I' )		  
WHERE BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('ERP' )
AND BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_NUMBER_INT >= 2020 
--AND BV_FISCAL_DAY_TO_YEAR.DV_FISCAL_QUARTER_ID >='2020Q1'
--AND BV_BKGS_MEASURE.SUMMARY_QUOTE_FLG IN ( 'N' )
AND BV_BKGS_MEASURE.DV_REVENUE_RECOGNITION_FLG = 'Y'
AND BV_BKGS_MEASURE.SERVICE_FLG IN ('Y')
AND BV_BKGS_MEASURE.CORPORATE_BOOKINGS_FLG IN ('Y')
AND BV_BKGS_MEASURE.DV_ATTRIBUTION_CD IN ('ATTRIBUTED','STANDALONE')
AND 1=2 /* Performance recommendation 19feb2021 */
AND NOT EXISTS (SELECT 1 FROM $$SLSORDVWDB.MT_SALES_MOTION_RPT RPT 
WHERE RPT.BOOKINGS_MEASURE_KEY =BV_BKGS_MEASURE.BOOKINGS_MEASURE_KEY
AND RPT.BOOKINGS_PROCESS_DATE=BV_BKGS_MEASURE.BOOKINGS_PROCESS_DATE
AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE=BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE
--AND RPT.SUMMARY_QUOTE_FLG='N'
)


Post SQL : 



Target1 Name : MT_SALES_MOTION_RPT_NSQ


Pre SQL : 



Post SQL : 
UPDATE RPT FROM
$$SLSORDVWDB.MT_SALES_MOTION_RPT RPT,
$$COMREFVWDB.R_PRODUCTS PRDT ,
$$SLSORDVWDB.N_BKGS_MEASURE BKGS
SET ORDERED_ITEM=PRDT.BK_PRODUCT_ID
, EDW_UPDATE_DTM =CURRENT_TIMESTAMP(0)  
WHERE BKGS.DV_PRODUCT_KEY=PRDT.ITEM_KEY
AND RPT.BOOKINGS_MEASURE_KEY =BKGS.BOOKINGS_MEASURE_KEY
AND RPT.BOOKINGS_PROCESS_DATE=BKGS.BOOKINGS_PROCESS_DATE
AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE=BKGS.BKGS_MEASURE_TRANS_TYPE_CODE
--AND RPT.SUMMARY_QUOTE_FLG='N'
AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE= 'ERP'
AND RPT.ORDERED_ITEM='UNKNOWN' ;
 
UPDATE RPT FROM
$$SLSORDVWDB.MT_SALES_MOTION_RPT RPT,
$$COMREFVWDB.R_PRODUCTS PRDT ,
(SELECT  SK_SALES_MOTION_ATTRIB_KEY,DV_ENTERPRISE_INV_SKU_ID,END_TV_DTM from $$SLSORDVWDB.MT_BKG_SLS_MOTION_ATTRIBUTION 
where END_TV_DTM > CURRENT_TIMESTAMP(0) group by 1,2,3) RTR
SET ENTERPRISE_SKU=PRDT.SK_INVENTORY_ITEM_ID_INT
, EDW_UPDATE_DTM  =CURRENT_TIMESTAMP(0)  
WHERE RTR.DV_ENTERPRISE_INV_SKU_ID=PRDT.ITEM_KEY
AND  RPT.SK_SALES_MOTION_ATTRIB_KEY=RTR.SK_SALES_MOTION_ATTRIB_KEY
AND RPT.RTR_SRC_ENTERPRISE_INV_SKU_ID=RTR.DV_ENTERPRISE_INV_SKU_ID
AND RTR.END_TV_DTM > CURRENT_TIMESTAMP(0)
--AND RPT.SUMMARY_QUOTE_FLG='N'
AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE= 'ERP'
AND RPT.ENTERPRISE_SKU =-999;

--- Notify RTR_OFFER_TYPE used for General offer type logic value
UPDATE RPT FROM
$$SLSORDVWDB.MT_SALES_MOTION_RPT RPT,
( SELECT RPT.BOOKINGS_MEASURE_KEY,RPT.BOOKINGS_PROCESS_DATE,RPT.BK_SERVICE_CATEGORY_ID,
CASE WHEN ST.BK_SERVICE_CATEGORY_ID IN 'COMBINED SERVICES' THEN 'COMBINED SERVICES'
WHEN RPT.BK_ALLOCATED_SERVC_GROUP_ID IN 'FOCUSED TECHNICAL SUPPORT SERVICES' THEN 'FTSS' 
WHEN RPT.FINANCE_BU_SW_TYPE = 'SWSS' THEN 'SWSS' 
WHEN RPT.BK_ALLOCATED_SERVC_GROUP_ID IN ('CLOUD MANAGED SERVICES') THEN 'CMS'
WHEN ( RPT.BK_ALLOCATED_SERVC_GROUP_ID IN 'AS SUBSCRIPTION' AND RPT.RU_BK_SERVICE_PROD_SUBGROUP_ID NOT LIKE 'NC%' ) THEN 'AS-S'
WHEN ( RPT.BK_ALLOCATED_SERVC_GROUP_ID IN ('AS TRANSACTION','TRAINING','AS FIXED') AND RPT.RU_BK_SERVICE_PROD_SUBGROUP_ID NOT LIKE 'NC%' ) THEN RPT.BK_ALLOCATED_SERVC_GROUP_ID                            
WHEN TTS.SALES_ORDER_LINE_KEY IS NOT NULL THEN 'TSS' 
ELSE 'OTHERS' END OFFER_TYPE
FROM $$SLSORDVWDB.MT_SALES_MOTION_RPT RPT
INNER JOIN (SELECT BOOKINGS_MEASURE_KEY,BOOKINGS_PROCESS_DATE,DV_PRODUCT_KEY FROM $$SLSORDVWDB.N_BKGS_MEASURE 
WHERE BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP' GROUP BY 1,2,3) BKGS
ON BKGS.BOOKINGS_MEASURE_KEY=RPT.BOOKINGS_MEASURE_KEY
AND BKGS.BOOKINGS_PROCESS_DATE=RPT.BOOKINGS_PROCESS_DATE
INNER JOIN $$STGDB.WI_SFH_RUP ST
    ON ST.ITEM_KEY = BKGS.DV_PRODUCT_KEY
LEFT JOIN $$STGDB.WI_TTS_SOWB_SOL_LINES TTS
    ON RPT.DV_SALES_ORDER_LINE_KEY = TTS.SALES_ORDER_LINE_KEY
WHERE RPT.BKGS_MEASURE_TRANS_TYPE_CODE= 'ERP'
--AND RPT.SUMMARY_QUOTE_FLG='N'
GROUP BY 1,2,3,4
) OFFER
SET SMR_OFFER_TYPE=OFFER.OFFER_TYPE
, EDW_UPDATE_DTM  =CURRENT_TIMESTAMP(0)  
WHERE  RPT.BOOKINGS_MEASURE_KEY=OFFER.BOOKINGS_MEASURE_KEY
AND RPT.BOOKINGS_PROCESS_DATE=OFFER.BOOKINGS_PROCESS_DATE
AND RPT.BK_SERVICE_CATEGORY_ID=OFFER.BK_SERVICE_CATEGORY_ID
AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP'
--AND RPT.SUMMARY_QUOTE_FLG='N'
AND RPT.SMR_OFFER_TYPE ='UNKNOWN';

UPDATE RPT  
FROM $$SLSORDVWDB.MT_SALES_MOTION_RPT RPT,
( SEL  SK_SALES_MOTION_ATTRIB_KEY,SALES_MOTION_CD,COALESCE( SMR_TAGGING_FAILURE_RSN_CD,'UNK') SMR_TAGGING_FAILURE_RSN_CD, RENEWAL_REF_ID,         
  CASE
  WHEN  SALES_MOTION_CD IN ('NEW','RENEW') AND SMR_TAGGING_FAILURE_RSN_CD IS NOT NULL  THEN
      CASE WHEN   SLS_MTN_CORRECTION_CASE_NUM ='UNKNOWN' AND MANUAL_OVERRIDE_ROLE='N'  THEN 'DEFAULT SLA LOGIC'
                  WHEN   SLS_MTN_CORRECTION_CASE_NUM <>'UNKNOWN' AND MANUAL_OVERRIDE_ROLE='N'  THEN 'MANUAL CORRECTION - PROACTIVE DISPOSITION'
  WHEN   SLS_MTN_CORRECTION_CASE_NUM <>'UNKNOWN' AND MANUAL_OVERRIDE_ROLE='Y'  THEN 'MANUAL CORRECTION - WITH CASE NUMBER'
                  ELSE 'SYSTEM TAGGED'
      END ELSE 'SYSTEM TAGGED'
      END     AS   SMC_SOURCE_TAG
FROM $$SLSORDVWDB.MT_BKG_SLS_MOTION_ATTRIBUTION  
WHERE END_TV_DTM>CURRENT_TIMESTAMP(0)
QUALIFY ROW_NUMBER() OVER(PARTITION BY SK_SALES_MOTION_ATTRIB_KEY,SALES_MOTION_CD,SMR_TAGGING_FAILURE_RSN_CD,RENEWAL_REF_ID
ORDER BY SMC_SOURCE_TAG DESC)=1
  )SRC
SET SMC_SOURCE_TAG=SRC.SMC_SOURCE_TAG
,EDW_UPDATE_DTM =CURRENT_TIMESTAMP(0)  
WHERE  RPT.SK_SALES_MOTION_ATTRIB_KEY=SRC.SK_SALES_MOTION_ATTRIB_KEY
AND RPT.SALES_MOTION_CD=SRC.SALES_MOTION_CD
AND COALESCE(RPT.RTR_SMR_TAGGING_FAILURE_RSN_CD,'UNK')=SRC.SMR_TAGGING_FAILURE_RSN_CD
AND RPT.RTR_RENEWAL_REF_ID=SRC.RENEWAL_REF_ID
AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP'
--AND RPT.SUMMARY_QUOTE_FLG='N'
AND RPT.SMC_SOURCE_TAG IS NULL;