


Source1 Name : SQ_N_ATTR_PRDT_AS_NEW_OR_RNWL


Pre SQL : 



SQL Query : 
SELECT 
    SOL_ATT.SALES_ORDER_LINE_KEY AS SALES_ORDER_LINE_KEY
    ,SOL_ATT.ENTERPRISE_OR_INVOICE_SKU AS DV_ENTERPRISE_INV_SKU_ID
    ,SOL_ATT.SALES_MOTION_CD AS SALES_MOTION_CD
    ,(SOL_ATT.SMC_PCT)/(SOL_ATT.TOTAL_PCT) AS DV_ALLOCATION_PCT  
    ,ITEM_CATEGORY AS DV_SERVICE_CATEGORY_CD  
    ,'Y' AS DV_OA_FLG
    ,SOL_ATT.START_TV_DTM
    ,SOL_ATT.END_TV_DTM
    ,'RTNR' AS DV_SOURCE_TYPE 
    ,BK_AS_ARCHITECTURE_NAME AS AS_ARCHITECTURE_NAME 
    ,BK_TECH_GROUP_ID AS TECHNOLOGY_GROUP_ID
    ,BK_DV_ATTR_PRDT_OFFER_TYPE_NAME AS ATTR_PRDT_OFFER_TYPE_NAME 
    ,AS_TS_CD AS AS_TS_CODE    
    ,SK_RENEW_CONTRACT_LINE_ID AS SK_RENEW_CONTRACT_LINE_ID
    ,SK_AS_PARENT_INVENTORY_ITEM_ID
    ,SK_ATTRIBUTION_ID_INT AS SK_OFFER_ATTRIBUTION_ID_INT
    ,SRC_ENTERPRISE_INV_SKU_ID
    ,PRODUCT_CLASS
,TRANSACTION_CR_PARTY_KEY
, HQ_CR_PRTY_KEY
     , RENEWAL_REF_ID
      ,RENEWAL_REF_CD
      ,SMR_TAGGING_FAILURE_RSN_CD
      ,SALES_MOTION_TIMING_CD
	  ,MANUAL_OVERRIDE_ROLE
	  ,REQUESTING_CSCO_WRKR_PRTY_KEY
	  ,SLS_MTN_CORRECTION_CASE_NUM
	  ,SLS_MTN_CORRECTION_CMNT
	  ,OFFER_ATTRIB_PRDT_KEY
	  ,DV_RENEWAL_GAP_DAYS_CNT
 FROM
 (
 SELECT 
    SALES_ORDER_LINE_KEY,
    ENTERPRISE_OR_INVOICE_SKU,
    SALES_MOTION_CD,
    START_TV_DTM,
    END_TV_DTM,
    SMC_PCT ,
    CASE WHEN TOTAL_PCT =0 THEN 1 ELSE TOTAL_PCT END AS TOTAL_PCT,
    ITEM_CATEGORY,
    BK_AS_ARCHITECTURE_NAME,
    BK_TECH_GROUP_ID,
    BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
    AS_TS_CD,
    SK_RENEW_CONTRACT_LINE_ID,
    SK_AS_PARENT_INVENTORY_ITEM_ID,
    SK_ATTRIBUTION_ID_INT,
    SRC_ENTERPRISE_INV_SKU_ID,
    PRODUCT_CLASS,
TRANSACTION_CR_PARTY_KEY,
HQ_CR_PRTY_KEY,
      RENEWAL_REF_ID,
      RENEWAL_REF_CD,
      SMR_TAGGING_FAILURE_RSN_CD,
      SALES_MOTION_TIMING_CD,
	  MANUAL_OVERRIDE_ROLE,
	  REQUESTING_CSCO_WRKR_PRTY_KEY,
	  SLS_MTN_CORRECTION_CASE_NUM,
	  SLS_MTN_CORRECTION_CMNT,
	  OFFER_ATTRIB_PRDT_KEY,
	  DV_RENEWAL_GAP_DAYS_CNT
 FROM 
 (
 SELECT 
     NATTR.SALES_ORDER_LINE_KEY  
    ,CASE WHEN NSO.CCW_ORDER_ORIGIN_CD IN ('CCW-RENEWALS','CCW-RENEWALS-2T') AND OA.TOP_SKU_SALES_ORDER_LINE_KEY IS NULL THEN  NSOL.PRODUCT_KEY ELSE NATTR.ATTR_PRDT_KEY END AS ENTERPRISE_OR_INVOICE_SKU
    ,NATTR.SALES_MOTION_CD AS SALES_MOTION_CD
    ,CAST(SUM(ATTR_PCT) OVER ( PARTITION BY NATTR.SALES_ORDER_LINE_KEY,NATTR.AS_TS_CD, NATTR.SK_ATTRIBUTION_ID_INT,CASE WHEN NSO.CCW_ORDER_ORIGIN_CD IN ('CCW-RENEWALS','CCW-RENEWALS-2T') AND OA.TOP_SKU_SALES_ORDER_LINE_KEY IS NULL THEN  NSOL.PRODUCT_KEY ELSE NATTR.ATTR_PRDT_KEY END ,NATTR.SK_AS_PARENT_INVENTORY_ITEM_ID,NATTR.SK_RENEW_CONTRACT_LINE_ID,NATTR.SALES_MOTION_CD,NATTR.ATTR_PRDT_CLASS_NAME, NATTR.TRANSACTION_CR_PARTY_KEY, NATTR.HQ_CR_PRTY_KEY, NATTR.RENEWAL_REF_ID, NATTR.RENEWAL_REF_CD, NATTR.SMR_TAGGING_FAILURE_RSN_CD, NATTR.SALES_MOTION_TIMING_CD, CURRENT_TIMESTAMP(0),NATTR.ATTR_PRDT_KEY,NATTR.MANUAL_OVERRIDE_ROLE,NATTR.REQUESTING_CSCO_WRKR_PRTY_KEY,NATTR.SLS_MTN_CORRECTION_CASE_NUM,NATTR.SLS_MTN_CORRECTION_CMNT,NATTR.OFFER_ATTRIB_PRDT_KEY)  AS DECIMAL(18,6)) AS SMC_PCT 
	,CAST(SUM(ATTR_PCT) OVER ( PARTITION BY NATTR.SALES_ORDER_LINE_KEY,NATTR.SK_ATTRIBUTION_ID_INT, CASE WHEN NSO.CCW_ORDER_ORIGIN_CD IN ('CCW-RENEWALS','CCW-RENEWALS-2T') AND OA.TOP_SKU_SALES_ORDER_LINE_KEY IS NULL THEN  NSOL.PRODUCT_KEY ELSE NATTR.ATTR_PRDT_KEY END ,CURRENT_TIMESTAMP(0))   AS DECIMAL(18,6)) AS TOTAL_PCT
    ,CURRENT_TIMESTAMP(0) AS START_TV_DTM
    ,NATTR.END_TV_DTM
    ,NATTR.ITEM_CATEGORY_NAME AS ITEM_CATEGORY
    ,NATTR.BK_AS_ARCHITECTURE_NAME
    ,NATTR.BK_TECH_GROUP_ID
    ,NATTR.BK_DV_ATTR_PRDT_OFFER_TYPE_NAME
    ,NATTR.AS_TS_CD
    ,NATTR.SK_RENEW_CONTRACT_LINE_ID
    ,NATTR.SK_AS_PARENT_INVENTORY_ITEM_ID
    ,NATTR.SK_ATTRIBUTION_ID_INT
    ,NATTR.ATTR_PRDT_KEY AS SRC_ENTERPRISE_INV_SKU_ID
    ,NATTR.ATTR_PRDT_CLASS_NAME AS PRODUCT_CLASS
    ,NATTR.TRANSACTION_CR_PARTY_KEY
     ,NATTR.HQ_CR_PRTY_KEY
     ,NATTR.RENEWAL_REF_ID
     ,NATTR.RENEWAL_REF_CD
     ,NATTR.SMR_TAGGING_FAILURE_RSN_CD
     ,NATTR.SALES_MOTION_TIMING_CD
	 ,NATTR.MANUAL_OVERRIDE_ROLE
	 ,NATTR.REQUESTING_CSCO_WRKR_PRTY_KEY
	 ,NATTR.SLS_MTN_CORRECTION_CASE_NUM
	 ,NATTR.SLS_MTN_CORRECTION_CMNT
     ,NATTR.OFFER_ATTRIB_PRDT_KEY
	 ,NATTR.DV_RENEWAL_GAP_DAYS_CNT
  FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV  NATTR /* New RTNR table as part of day1 fy21 rtr net changes */
  INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE_TV NSOL
    ON NATTR.SALES_ORDER_LINE_KEY = NSOL.SALES_ORDER_LINE_KEY
    AND CAST(NSOL.END_TV_DATETIME AS DATE) =  CAST( '3500-01-01' AS DATE) 
    AND NSOL.SS_CODE = 'CG'
  INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_V1_TV NSO
    ON NSOL.SALES_ORDER_KEY =  NSO.SALES_ORDER_KEY
	AND NSO.END_TV_DTM = '3500-01-01 00:00:00'
	AND NSO.SS_CD = 'CG'
  LEFT JOIN (SELECT TOP_SKU_SALES_ORDER_LINE_KEY FROM $$SLSORDVWDB.N_SOL_OFFER_ATTRIBUTION GROUP BY 1) OA
    ON NATTR.SALES_ORDER_LINE_KEY = OA.TOP_SKU_SALES_ORDER_LINE_KEY     
 WHERE NATTR.EDW_UPDATE_DTM > '$$LastExtractDate'
 AND NATTR.SALES_ORDER_LINE_KEY > 0 /* To restrict xaas related default order line records */
 AND NATTR.ITEM_CATEGORY_NAME NOT IN ('Billing', 'FLEXIBLE CONSUMPTION MODEL') /* To restrict xaas data having valid order line flowing into ERP  */
 AND NATTR.END_TV_DTM = '3500-01-01 00:00:00'
 AND NOT EXISTS ( SEL 1 FROM $$SLSORDVWDB.MT_SUMMARY_QUOTE_SOL_ALLOC SQ WHERE DV_EXPIRATION_DTM = '3500-01-01 00:00:00' AND NATTR.SALES_ORDER_LINE_KEY = SQ.SALES_ORDER_LINE_KEY ) /* To restrict changes from RTR for SQ lines SMR aug 16 release*/
) WI 
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
) SOL_ATT


Post SQL : 



Target1 Name : WI_MT_ERP_SMC_ATTRIB_RTR1


Pre SQL : 
DELETE FROM $$STGDB.WI_MT_ERP_SMC_ATTRIB_RTR ALL;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_MT_ERP_SMC_ATTRIB_RTR','D');


Source2 Name : SQ_MT_SLS_MOTION_ATTRIBUTION


Pre SQL : 



SQL Query : 
SELECT SALES_ORDER_LINE_KEY,
       DV_ENTERPRISE_INV_SKU_ID,
       SALES_MOTION_CD,
       DV_ALLOCATION_PCT,
       DV_SERVICE_CATEGORY_CD,
       DV_OA_FLG,
       START_TV_DTM,
       END_TV_DTM,
       DV_SOURCE_TYPE,
	 AS_ARCHITECTURE_NAME,
	 TECHNOLOGY_GROUP_ID,
	 ATTR_PRDT_OFFER_TYPE_NAME,
	 AS_TS_CODE,
	 SK_RENEW_CONTRACT_LINE_ID,
	 SK_AS_PARENT_INVENTORY_ITEM_ID,
	 SK_OFFER_ATTRIBUTION_ID_INT,
       CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM,
       USER AS EDW_CREATE_USER,
       CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM,
       USER AS EDW_UPDATE_USER,
       SRC_ENTERPRISE_INV_SKU_ID,
	   PRODUCT_CLASS,
TRANSACTION_CR_PARTY_KEY,
 HQ_CR_PRTY_KEY,
 RENEWAL_REF_ID,
RENEWAL_REF_CD,
SMR_TAGGING_FAILURE_RSN_CD,
SALES_MOTION_TIMING_CD,
MANUAL_OVERRIDE_ROLE,
REQUESTING_CSCO_WRKR_PRTY_KEY,
SLS_MTN_CORRECTION_CASE_NUM,
SLS_MTN_CORRECTION_CMNT,
OFFER_ATTRIB_PRDT_KEY,
RENEWAL_GAP_DAYS,
'N' AS BUNDLE_FLG
FROM $$STGDB.WI_MT_ERP_SMC_ATTRIB_RTR WI
WHERE NOT EXISTS ( SELECT 1 FROM $$SLSORDVWDB.MT_SLS_MOTION_ATTRIBUTION MT
                   WHERE WI.SALES_ORDER_LINE_KEY = MT.SALES_ORDER_LINE_KEY
                    /*AND WI.DV_ENTERPRISE_INV_SKU_ID = MT.DV_ENTERPRISE_INV_SKU_ID*//*Commenting this to open and close at line level*/
					--AND WI.OFFER_ATTRIB_PRDT_KEY=MT.OFFER_ATTRIB_PRDT_KEY 
                    AND WI.START_TV_DTM = MT.START_TV_DTM
				 )


Post SQL : 



Target2 Name : MT_SLS_MOTION_ATTRIBUTION


Pre SQL : 
UPDATE MT
FROM $$SLSORDVWDB.MT_SLS_MOTION_ATTRIBUTION MT , 
      ( SELECT SALES_ORDER_LINE_KEY--, DV_ENTERPRISE_INV_SKU_ID
	    , MAX(START_TV_DTM) AS START_TV_DTM 
         FROM $$STGDB.WI_MT_ERP_SMC_ATTRIB_RTR 
        GROUP BY 1
       ) WI
  SET END_TV_DTM = WI.START_TV_DTM - INTERVAL '1' SECOND
     ,EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0)
WHERE MT.SALES_ORDER_LINE_KEY = WI.SALES_ORDER_LINE_KEY
  /*AND MT.DV_ENTERPRISE_INV_SKU_ID = WI.DV_ENTERPRISE_INV_SKU_ID*//*Commenting this to open and close at line level*/
  AND MT.START_TV_DTM <> WI.START_TV_DTM
  AND MT.END_TV_DTM = '3500-01-01 00:00:00';


Post SQL : 
CALL COLLECT_STATS_WRAP('$$SLSORDDB','MT_SLS_MOTION_ATTRIBUTION','D');