


Source1 Name : SQ_MT_RTNR_SMC_ALLOCATION


Pre SQL : 



SQL Query : 
SELECT
    SMC_ALLOC.SALES_ORDER_LINE_KEY
   ,AR.PRODUCT_KEY AS DV_ENTERPRISE_INV_SKU_ID 
   ,SMC_ALLOC.SALES_MOTION_CD 
   ,SMC_ALLOC.DV_ALLOCATION_PCT
   ,SMC_ALLOC.DV_SERVICE_CATEGORY_CD AS DV_SERVICE_CATEGORY_CD
   ,'N' AS DV_OA_FLG
   ,SMC_ALLOC.START_TV_DTM                  
   ,SMC_ALLOC.END_TV_DTM 
   /* ,'RTNR' AS DV_SOURCE_TYPE   */ /* DV SOURCE TYPE derivation change to accommodate SQ */
   ,SMC_ALLOC.DV_SOURCE_TYPE /* DV SOURCE TYPE derivation change to accommodate SQ */
   ,CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM
   ,USER AS EDW_CREATE_USER
   ,CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM
   ,USER AS EDW_UPDATE_USER
   ,SMC_ALLOC.SALES_MOTION_TIMING_CD
  FROM $$SLSORDVWDB.MT_RTNR_SMC_ALLOCATION SMC_ALLOC
  INNER JOIN ( SELECT DV_SALES_ORDER_LINE_KEY AS SALES_ORDER_LINE_KEY
                , DV_PRODUCT_KEY AS PRODUCT_KEY
                 FROM $$FINLGLVWDB.N_DRVD_NCR_REV_TRX_FOR_BKG DRVD, 
                      $$SLSORDVWDB.MT_RTNR_SMC_ALLOCATION EL 
                WHERE SOURCE_SYSTEM_CODE = 'CG'  
                  AND LAST_RECORD_FLAG = 'Y' 
                  AND DRVD.DV_SALES_ORDER_LINE_KEY > 0 
                  AND DRVD.DV_SALES_ORDER_LINE_KEY = EL.SALES_ORDER_LINE_KEY
                  AND EL.END_TV_DTM = '3500-01-01 00:00:00'
                  AND EL.EDW_UPDATE_DTM > '$$LastExtractDate'
                GROUP BY 1,2            
              ) AR 
   ON SMC_ALLOC.SALES_ORDER_LINE_KEY = AR.SALES_ORDER_LINE_KEY 
   WHERE SMC_ALLOC.END_TV_DTM = '3500-01-01 00:00:00'


Post SQL : 



Target1 Name : WI_MT_AR_SMC_ATTRIB_RTR1


Pre SQL : 
DELETE FROM  $$STGDB.WI_MT_AR_SMC_ATTRIB_RTR;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_MT_AR_SMC_ATTRIB_RTR','D');


Source2 Name : SQ_MT_AR_SLS_MOTION_ATTRIB


Pre SQL : 



SQL Query : 
SELECT 
                  SALES_ORDER_LINE_KEY, 
                  DV_ENTERPRISE_INV_SKU_ID, 
                  SALES_MOTION_CD, 
                  DV_ALLOCATION_PCT, 
      DV_SERVICE_CATEGORY_CD        ,
                  DV_OA_FLG, 
                  START_TV_DTM, 
                  END_TV_DTM, 
                  DV_SOURCE_TYPE, 
                  EDW_CREATE_DTM, 
                  EDW_CREATE_USER, 
                  EDW_UPDATE_DTM, 
                  EDW_UPDATE_USER,
      SALES_MOTION_TIMING_CD
  FROM $$STGDB.WI_MT_AR_SMC_ATTRIB_RTR WI
  WHERE NOT EXISTS ( SELECT 1 FROM $$SLSORDVWDB.MT_AR_SLS_MOTION_ATTRIB MT
                                  WHERE WI.SALES_ORDER_LINE_KEY = MT.SALES_ORDER_LINE_KEY
                                    AND WI.DV_ENTERPRISE_INV_SKU_ID = MT.DV_ENTERPRISE_INV_SKU_ID
                                    AND WI.START_TV_DTM = MT.START_TV_DTM
      )


Post SQL : 



Target2 Name : MT_AR_SLS_MOTION_ATTRIB1


Pre SQL : 
/* START: SMR Aug 16th changes - To prevent unnecessary changes going into MT table */
DELETE FROM $$STGDB.WI_AR_SMC_ATTRIB_RTR_CHNG_CHK ;

INSERT INTO $$STGDB.WI_AR_SMC_ATTRIB_RTR_CHNG_CHK
SELECT
	SALES_ORDER_LINE_KEY, 
    DV_ENTERPRISE_INV_SKU_ID, 
    SALES_MOTION_CD, 
    DV_ALLOCATION_PCT, 
	DV_SERVICE_CATEGORY_CD,
    DV_OA_FLG, 
    START_TV_DTM, 
    END_TV_DTM, 
	DV_SOURCE_TYPE,
	SALES_MOTION_TIMING_CD
FROM $$STGDB.WI_MT_AR_SMC_ATTRIB_RTR WI
 WHERE EXISTS ( SEL 1 
				FROM $$SLSORDVWDB.MT_AR_SLS_MOTION_ATTRIB MT_AR
				WHERE MT_AR.END_TV_DTM = '3500-01-01 00:00:00'
				  AND WI.SALES_ORDER_LINE_KEY = MT_AR.SALES_ORDER_LINE_KEY
				  AND WI.DV_ENTERPRISE_INV_SKU_ID = MT_AR.DV_ENTERPRISE_INV_SKU_ID
				  AND WI.SALES_MOTION_CD = MT_AR.SALES_MOTION_CD
				  AND WI.DV_ALLOCATION_PCT = MT_AR.DV_ALLOCATION_PCT
				  AND WI.DV_SERVICE_CATEGORY_CD = MT_AR.DV_SERVICE_CATEGORY_CD
				  AND WI.DV_SOURCE_TYPE = MT_AR.DV_SOURCE_TYPE ) ;

COLLECT STATS ON $$STGDB.WI_AR_SMC_ATTRIB_RTR_CHNG_CHK;

DELETE FROM $$STGDB.WI_AR_SMC_ATTRIB_RTR_CHNG_CHK
WHERE ( SALES_ORDER_LINE_KEY, DV_ENTERPRISE_INV_SKU_ID ) IN
		( SEL SALES_ORDER_LINE_KEY, DV_ENTERPRISE_INV_SKU_ID
			FROM $$STGDB.WI_AR_SMC_ATTRIB_RTR_CHNG_CHK
			GROUP BY 1,2 HAVING ROUND(SUM(DV_ALLOCATION_PCT),4) <> 1.0000		
		) ;

DELETE FROM $$STGDB.WI_MT_AR_SMC_ATTRIB_RTR WI
WHERE EXISTS ( SEL 1 
				FROM $$STGDB.WI_AR_SMC_ATTRIB_RTR_CHNG_CHK NO_CHNG
				WHERE WI.SALES_ORDER_LINE_KEY = NO_CHNG.SALES_ORDER_LINE_KEY
				  AND WI.DV_ENTERPRISE_INV_SKU_ID = NO_CHNG.DV_ENTERPRISE_INV_SKU_ID
			  ) ;
/* END: SMR Aug 16th changes - To prevent unnecessary changes going into MT table */

UPDATE MT
  FROM $$SLSORDDB.MT_AR_SLS_MOTION_ATTRIB MT , 
       ( SELECT SALES_ORDER_LINE_KEY, DV_ENTERPRISE_INV_SKU_ID
	   , MAX(START_TV_DTM) AS START_TV_DTM
           FROM $$STGDB.WI_MT_AR_SMC_ATTRIB_RTR 
          GROUP BY 1,2
        ) WI
  SET END_TV_DTM = WI.START_TV_DTM - INTERVAL '1' SECOND,
	  EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0)
  WHERE MT.SALES_ORDER_LINE_KEY = WI.SALES_ORDER_LINE_KEY
    AND MT.DV_ENTERPRISE_INV_SKU_ID = WI.DV_ENTERPRISE_INV_SKU_ID
    AND MT.START_TV_DTM <> WI.START_TV_DTM
    AND MT.END_TV_DTM = '3500-01-01 00:00:00' ;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$SLSORDDB','MT_AR_SLS_MOTION_ATTRIB','D');