


Source1 Name : SQ_ST_BMK_POS_BKGS_TRANS


Pre SQL : 
DELETE FROM $$STGDB.ST_BMK_POS_BKGS_TRANS ALL;


SQL Query : 
SELECT BK_POS_TRANSACTION_ID_INT, ( VLDTD_NET_UNIT_PRICE_USD_AMT * POS_TRX_LINE_PRODUCT_QUANT ) AS AMOUNT,POS.POS_TRX_LINE_POSTED_DATE,
Cast('DSV_BKG' AS VARCHAR(20)) AS SOURCE_TYPE    
FROM $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE POS 

UNION   
SELECT BK_POS_TRANSACTION_ID_INT, (VLDTD_NET_UNIT_PRICE_USD_AMT * POS_TRX_LINE_PRODUCT_QUANT ) AMOUNT,POS.POS_TRX_LINE_POSTED_DATE  ,
       DSV_OR_POS_TYPE_CD AS SOURCE_TYPE   
  FROM $$SLSORDVWDB.N_POS_TRANSACTION_LINE POS 
   WHERE DSV_OR_POS_TYPE_CD = 'POS'


Post SQL : 



Target1 Name : ST_BMK_POS_BKGS_TRANS1


Pre SQL : 



Post SQL : 
COLLECT STATS ON  $$STGDB.ST_BMK_POS_BKGS_TRANS  COLUMN BK_POS_TRANSACTION_ID_INT;
COLLECT STATS ON  $$STGDB.ST_BMK_POS_BKGS_TRANS  COLUMN POS_TRX_LINE_POSTED_DATE;


Source2 Name : SQ_MT_SALES_MOTION_RPT


Pre SQL : 
DELETE FROM $$SLSORDVWDB.MT_SALES_MOTION_RPT
WHERE BKGS_MEASURE_TRANS_TYPE_CODE='POS'  AND ( FISCAL_YEAR_MONTH_INT = (SELECT FISCAL_YEAR_MTH_NUMBER_INT FROM $$ETLVWDB.BKG_PROCESS_DT_CNTRL)
OR  BOOKINGS_MEASURE_KEY IN ( SELECT  BOOKINGS_MEASURE_KEY  FROM $$SLSORDVWDB.N_BKGS_MEASURE  WHERE  BKGS_MEASURE_TRANS_TYPE_CODE='POS'   AND 
 CAST(  CAST ( EDW_UPDATE_DATETIME AS FORMAT 'YYYY-MM-DD' ) AS DATE )>= (SELECT PROCESS_DATE-15 FROM $$ETLVWDB.BKG_PROCESS_DT_CNTRL)  GROUP BY 1  ) 
 OR  BOOKINGS_MEASURE_KEY IN ( SELECT  BOOKINGS_MEASURE_KEY  FROM $$SLSORDVWDB.N_BKGS_MEASURE BKG
INNER JOIN $$SLSORDVWDB.MT_BKG_SLS_MOTION_ATTRIBUTION MT
ON BKG.SK_SALES_MOTION_ATTRIB_KEY=MT.SK_SALES_MOTION_ATTRIB_KEY 
WHERE  BKG.BKGS_MEASURE_TRANS_TYPE_CODE='POS' AND MT.END_TV_DTM='3500-01-01 00:00:00' AND
CAST( CAST ( MT.EDW_UPDATE_DTM AS FORMAT 'YYYY-MM-DD' ) AS DATE )>= (SELECT PROCESS_DATE-7 FROM $$ETLVWDB.BKG_PROCESS_DT_CNTRL) GROUP BY 1)
 );


SQL Query : 
SELECT
BV_BKGS_MEASURE.BOOKINGS_MEASURE_KEY,
BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_NUMBER_INT,
BV_FISCAL_DAY_TO_YEAR.DV_FISCAL_QUARTER_ID     AS FISCAL_QUARTER_ID,
BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_MONTH_INT
,BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_WEEK_NUM_INT AS FISCAL_WEEK_NUMBER_INT
,BV_FISCAL_DAY_TO_YEAR.DV_FISCAL_YR_MNTH_WEEK_NUM_INT       AS FISCAL_YR_MNTH_WEEK_INT,
BV_BKGS_MEASURE.BOOKINGS_PROCESS_DATE
,BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE,
BV_BKGS_MEASURE.DV_DEAL_ID AS DEAL_ID,
BV_BKGS_MEASURE.SALES_ORDER_KEY,
BV_SALES_ORDER_LINE_TV.BK_SO_SOURCE_NAME
, BV_SALES_ORDER_LINE_TV.SALES_ORDER_PROGRAM_TYPE_NAME,
BV_BKGS_MEASURE.CANCELLED_FLG                 AS ORDER_CANCELLED_FLAG,
BV_BKGS_MEASURE.DV_BOOKED_DT                  AS ORDER_HEADER_BOOKED_DATE
,BV_BKGS_MEASURE.DV_SOURCE_ORDER_NUM_INT       AS SOURCE_ORDER_NUM_INT,
BV_BKGS_MEASURE.DV_SALES_ORDER_LINE_KEY,
BV_BKGS_MEASURE.BK_POS_TRANSACTION_ID_INT
,BV_SALES_ORDER_LINE_TV.SK_SO_LINE_ID_INT              AS SALES_ORDER_LINE_ID,
 BV_SALES_ORDER_LINE_TV.ORDER_LINE_CREATION_DATE,
BV_SALES_ORDER_LINE_TV.CISCO_BOOKED_DATETIME,
BV_SALES_ORDER_LINE_TV.CUST_EXPECTED_START_DT         AS CUST_EXPECTED_START_DATE
,BV_SALES_ORDER_LINE_TV.BK_SO_SRC_NAME AS LINE_SOURCE_NAME,
BV_SALES_ORDER_LINE_TV.LINE_STATUS_CD,
BV_SALES_ORDER_LINE_TV.SALES_ORDER_CATEGORY_TYPE
,BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_NUMBER        AS RU_SERVICE_CONTRACT_NUMBER,
BV_SALES_ORDER_LINE_TV.CANCELLED_FLAG AS ORDER_LINE_CANCELLED_FLAG,
Coalesce(NullIfZero(
CASE
 WHEN BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('SLS_ADJ',
'POS_ADJ',
'POS')THEN Cast((Cast(cast(BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_END_DTM as date) - cast(BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_START_DTM as date) AS INTEGER)*12(FLOAT))/365 AS DECIMAL(18,0))
ELSE Cast((Cast(cast(BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_END_DTM as date ) - cast(BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_START_DTM as date) AS INTEGER)*12(FLOAT))/365 AS DECIMAL(18,0))
END ) ,
 BV_BKGS_MEASURE.DV_CONTRACT_DURATION               )  AS CONTRACT_DURATION,
CASE 
WHEN BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('SLS_ADJ',
 'POS_ADJ',
 'POS') THEN BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_START_DTM
      ELSE BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_START_DTM
 END AS CONTRACT_START_DATE,
CASE 
WHEN BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('SLS_ADJ', 
'POS_ADJ', 
'POS') THEN BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_END_DTM
      ELSE BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_END_DTM 
END AS CONTRACT_END_DATE,      
'UNKNOWN' AS ORDERED_ITEM
,BP.RU_BK_SERVICE_PROD_SUBGROUP_ID  AS ORDERED_SERVICE,
BV_BKGS_MEASURE.SUMMARY_QUOTE_FLG,
BP.ITEM_KEY AS PRODUCT_KEY,
BP.BK_PRODUCT_ID  AS ATTRIBUTED_PRODUCT_ID,
BP.RU_BK_SERVICE_PROD_SUBGROUP_ID  AS RU_BK_SERVICE_PROD_SUBGROUP_ID,
SWSS.BK_GSP_ATTR_VAL_TXT AS  FINANCE_BU_SW_TYPE,
BP.PRDT_SETUP_CLASSIFICATION_CD,
BP.RU_BK_PRODUCT_FAMILY_ID  AS RU_BK_PRODUCT_FAMILY_ID,
BP.RU_COMMISSIONABLE_STATUS_CODE  AS RU_COMMISSIONABLE_STATUS_CODE,
SFH.BK_SERVICE_CATEGORY_ID,
SFH.BK_ALLOCATED_SERVC_GROUP_ID,
SFH.BK_PRODUCT_SUBGROUP_ID,
SFH.ALLOCATION_PERCENTAGE, 
 BV_BKGS_MEASURE.END_CUSTOMER_KEY
,DE.END_CUSTOMER_ID
,DE.END_CUSTOMER_NAME,
DE.ERP_WIPS_ISO_COUNTRY_CD,
DE.END_CUST_CRPARTY_ID,
DE.BRANCH_HQ_BRANCH_CD,
DE.HQ_CRPARTY_ID,
DE.HQ_CRPARTY_NAME,
DE.GU_ID,
DE.GU_PRIMARY_NAME
,BV_BKGS_MEASURE.SALES_TERRITORY_KEY
,BV_SALES_HIERARCHY.SALES_COVERAGE_CODE,
BV_SALES_HIERARCHY.SALES_SUBCOVERAGE_CODE,
BV_SALES_HIERARCHY.L1_SALES_TERRITORY_DESCR,
BV_SALES_HIERARCHY.L2_SALES_TERRITORY_DESCR,
BV_SALES_HIERARCHY.SALES_TERRITORY_NAME_CODE
,BV_BKGS_MEASURE.SALES_REP_NUMBER,
SR.ERP_SALES_REP_NAME AS ERP_SALES_REP_NAME,
BV_BKGS_MEASURE.ADJUSTMENT_CODE
,BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_START_DTM,
BV_BKGS_MEASURE.RU_SERVICE_CONTRACT_END_DTM,
BV_BKGS_MEASURE.DV_CONTRACT_DURATION,
BV_BKGS_MEASURE.XCAT_FLG,
BV_BKGS_MEASURE.DSV_FLG,
BV_BKGS_MEASURE.DV_FMV_FLG,
BV_BKGS_MEASURE.SK_SALES_MOTION_ATTRIB_KEY,
RTR.SALES_ORDER_LINE_KEY    AS SMR_SALES_ORDER_LINE_KEY,
RTR.SALES_MOTION_CD
,RTR.DV_SERVICE_CATEGORY_CD         as RTR_SERVICE_CATEGORY_CD,
RTR.AS_ARCHITECTURE_NAME          AS RTR_AS_ARCHITECTURE_NAME,
RTR.TECHNOLOGY_GROUP_ID            AS RTR_TECHNOLOGY_GROUP_ID,
RTR.ATTR_PRDT_OFFER_TYPE_NAME AS RTR_OFFER_TYPE,
RTR.SK_RENEW_CONTRACT_LINE_ID      AS RTR_RENEW_CONTRACT_LINE_ID,
RTR.AS_TS_CODE                    AS RTR_AS_TS_CODE,
RTR.DV_ENTERPRISE_INV_SKU_ID       AS RTR_SRC_ENTERPRISE_INV_SKU_ID,
RTR.PRODUCT_CLASS                  AS RTR_PRODUCT_CLASS
,RTR.TRANSACTION_CR_PARTY_KEY      AS RTR_TRANSACTION_CR_PARTY_KEY,
RTR.HQ_CR_PRTY_KEY                AS RTR_HQ_CR_PRTY_KEY,
RTR.RENEWAL_REF_ID                AS RTR_RENEWAL_REF_ID,
RTR.RENEWAL_REF_CD                AS RTR_RENEWAL_REF_CD,
RTR.SMR_TAGGING_FAILURE_RSN_CD    AS RTR_SMR_TAGGING_FAILURE_RSN_CD,
RTR.SALES_MOTION_TIMING_CD         AS RTR_SALES_MOTION_TIMING_CD,
RTR.MANUAL_OVERRIDE_ROLE          AS RTR_MANUAL_OVERRIDE_ROLE
,RTR.REQUESTING_CSCO_WRKR_PRTY_KEY AS REQUESTING_CSCO_WRKR_PRTY_KEY,
RTR.SLS_MTN_CORRECTION_CASE_NUM    AS SLS_MTN_CORRECTION_CASE_NUM,
RTR.SLS_MTN_CORRECTION_CMNT       AS SLS_MTN_CORRECTION_CMNT,
RTR.DV_ALLOCATION_PCT,
BV_BKGS_MEASURE.SERVICE_FLG,
BV_BKGS_MEASURE.DD_COMP_US_NET_PRICE_AMOUNT*Coalesce(RTR.DV_ALLOCATION_PCT,1)*Coalesce(SFH.ALLOCATION_PERCENTAGE,1)*Coalesce(BE.PRDT_FAMILY_ALLOCATION_PCT,1) AS DD_COMP_US_NET_PRICE_AMOUNT,
BV_BKGS_MEASURE.DV_AR_TRX_LINE_KEY,
BV_BKGS_MEASURE.AR_TRX_KEY,
ART.BK_AR_TRX_NUMBER AS BK_AR_TRX_NUMBER,
ART.AR_TRX_REASON_CODE AS AR_TRX_REASON_CODE,
BV_BKGS_MEASURE.ADJUSTMENT_DESCR_KEY,
BV_BKGS_MEASURE.CORPORATE_BOOKINGS_FLG,
BV_BKGS_MEASURE.DV_ATTRIBUTION_CD,
BV_BKGS_MEASURE.SO_SBSCRPTN_ITM_SLS_TRX_KEY AS MANUAL_TRX_KEY,
BV_BKGS_MEASURE.BK_SALES_ADJ_LINE_NUMBER_INT,
BV_BKGS_MEASURE.BK_SALES_ADJ_NUMBER_INT
,NULL as IDE_IFC_COMMENT_1_TXT,
NULL as IDE_IFC_COMMENT_2_TXT,
NULL as IDE_IFC_COMMENT_3_TXT,
NULL as IDE_IFC_COMMENT_4_TXT,
NULL as IDE_IFC_COMMENT_5_TXT,
NULL as IDE_IFC_DESCRIPTION_TXT,
NULL as UPLOADED_BY_ERP_USER_NAME,
NULL as MANUAL_TRANSACTION_TYPE_CD
,NULL as MANUAL_TRANSACTION_USAGE_CD,
NULL as MANUAL_TRX_BOOKING_REVENUE_CD,
CURRENT_DATE AS CURRENT_SNAPSHOT_DT
,BV_BKGS_MEASURE.DV_ANNUALIZED_US_NET_AMT*Coalesce(RTR.DV_ALLOCATION_PCT,1)*Coalesce(SFH.ALLOCATION_PERCENTAGE,1)*Coalesce(BE.PRDT_FAMILY_ALLOCATION_PCT,1) AS DV_ANNUALIZED_AMT , 
 CAST(RTR.START_TV_DTM AS DATE) AS START_TV_DT, 
   BV_BKGS_MEASURE.SK_OFFER_ATTRIBUTION_ID_INT AS OA_ID,
BP.PRODUCT_FAMILY_DESCRIPTION AS PRODUCT_FAMILY,
BP.RU_BK_SERVICE_PROGRAM_ID   AS SERVICE_PROGRAM,
BP.RU_SERVICE_LEVEL_GROUP_CODE  AS SERVICE_LEVEL,
  -999 AS ENTERPRISE_SKU,
BV_FISCAL_DAY_TO_YEAR.FISCAL_QUARTER_NAME AS FISCAL_QUARTER,
BV_FISCAL_DAY_TO_YEAR.FISCAL_MONTH_NAME AS FISCAL_MONTH,
BV_SALES_HIERARCHY.L3_SALES_TERRITORY_DESCR AS SALES_LEVEL_3,
DE.BRANCH_PRIMARY_NAME AS CUSTOMER_HQ_NAME,
BV_SALES_ORDER_LINE_TV.REVENUE_TYPE_CODE AS RSC_CODE,
DE.BRANCH_PRIMARY_NAME AS DEAL_HQ_CR_PARTY_NAME,
BV_SALES_ORDER_LINE_TV.TRX_BOOKING_SRC_CD AS LINE_SOURCE,
NULL AS LINE_CREATION_DATE,
RTR.ATTR_PRDT_OFFER_TYPE_NAME||RTR.SALES_MOTION_CD||
CASE 
WHEN RENEWAL_REF_CD IN ( 'RENEW COVERED LINE ID',
'SUBSCRIPTION REFERENCE ID',
'RENEW INSTANCE ID') THEN RENEWAL_REF_ID
 ELSE NULL 
END|| 
CASE
 WHEN RENEWAL_REF_CD IN ( 'RENEW COVERED LINE ID',
'SUBSCRIPTION REFERENCE ID',
'RENEW INSTANCE ID')  THEN RENEWAL_REF_CD 
ELSE NULL 
END||
CASE 
WHEN RTR.SALES_MOTION_CD IN 'UNKNOWN' THEN RTR.SMR_TAGGING_FAILURE_RSN_CD 
ELSE NULL 
 END AS SMR_RULE_TYPE, 
 NULL AS INHERITANCE_FLAG,
BE.BK_BUSINESS_ENTITY_NAME AS BE,
BE.BK_SUB_BUSINESS_ENTITY_NAME AS SUB_BE,
BV_SALES_ORDER_LINE_TV.ITEM_CATEGORY_DESCRIPTION AS ITEM_CATEGORY_NAME,
BKSO.BK_SO_NUMBER_INT AS DD_BK_SO_NUMBER_INT,
CASE
 WHEN  COALESCE(PNVR.MATCHING_MTHD_FOR_TAGGING_NAME,
'UNKNOWN') IN ('UNMAPPED',
'UNKNWON',
'UNKNOWN',
'SO QUOTE SKU ',
'SO ORDER SKU ',
'SHIPTO CUSTOMER CCW ORDER SKU',
'QUOTENUM QUOTE SKU ',
'QUOTENUM ORDER SKU ',
'PO QUOTE SKU ',
'PO ORDER SKU ',
'INSTALL CUSTOMER QUOTE SKU ',
'END CUSTOMER ORDER SKU',
'DEAL ORDER SKU ',
'CONTRACTNUM QUOTE SKU',
'CONTRACTNUM ORDER SKU')THEN 'WIPS' 
ELSE MATCHING_MTHD_FOR_TAGGING_NAME 
END AS MATCHING_MTHD_FOR_TAGGING_NAME,
BV_SALES_HIERARCHY.L4_SALES_TERRITORY_DESCR,
BV_SALES_HIERARCHY.L5_SALES_TERRITORY_DESCR,
BV_SALES_HIERARCHY.L6_SALES_TERRITORY_DESCR,
'UNKNOWN' AS SMR_OFFER_TYPE,
NULL AS SMC_SOURCE_TAG,
NULL AS WEB_ORDER_ID,             
NULL AS ORDER_CREATED_DT,              
NULL AS SUBSCRIPTION_REFERENCE_ID,     
NULL AS SUBSCRIPTION_START_DT,
NULL AS SUBSCRIPTION_END_DT,
BV_SALES_HIERARCHY.SALES_TERRITORY_DESCR AS SHARE_NODE_NAME  ,
CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM                ,
USER EDW_CREATE_USER       ,        
CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM       ,         
USER EDW_UPDATE_USER              
FROM $$SLSORDVWDB.N_BKGS_MEASURE    BV_BKGS_MEASURE    
 INNER JOIN  $$STGDB.ST_BMK_POS_BKGS_TRANS FY20_TRX
ON  FY20_TRX.BK_POS_TRANSACTION_ID_INT = BV_BKGS_MEASURE.BK_POS_TRANSACTION_ID_INT 
INNER JOIN $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR BV_FISCAL_DAY_TO_YEAR
ON BV_BKGS_MEASURE.BOOKINGS_PROCESS_DATE=BV_FISCAL_DAY_TO_YEAR.CALENDAR_DATE    
INNER JOIN $$COMREFVWDB.R_SALES_HIERARCHY BV_SALES_HIERARCHY
ON BV_BKGS_MEASURE.SALES_TERRITORY_KEY=BV_SALES_HIERARCHY.SALES_TERRITORY_KEY
LEFT JOIN ( 
SELECT BK_POS_TRANSACTION_ID_INT,
SALES_ORDER_LINE_KEY ,
MATCHING_MTHD_FOR_TAGGING_NAME 
FROM $$SLSORDVWDB.N_POS_TRX_LN_AS_NEW_OR_RNWL_TV 
WHERE 
  END_TV_DTM='3500-01-01 00:00:00'
 AND MATCHING_MTHD_FOR_TAGGING_NAME<>'UNKNOWN' 
GROUP BY  1,2,3  )PNVR
ON BV_BKGS_MEASURE.BK_POS_TRANSACTION_ID_INT=PNVR.BK_POS_TRANSACTION_ID_INT	
	--ADDING DERIVED TABLE as part of ETL tuning
LEFT JOIN ( SELECT 	DISTINCT 
			BV_SALES_ORDER_LINE_TV.SK_SO_LINE_ID_INT       ,
			BV_SALES_ORDER_LINE_TV.CISCO_BOOKED_DATETIME,
			BV_SALES_ORDER_LINE_TV.CUST_EXPECTED_START_DT       ,
			BV_SALES_ORDER_LINE_TV.BK_SO_SRC_NAME,
			BV_SALES_ORDER_LINE_TV.LINE_STATUS_CD,
			BV_SALES_ORDER_LINE_TV.SALES_ORDER_CATEGORY_TYPE ,
			BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_NUMBER     ,
			BV_SALES_ORDER_LINE_TV.CANCELLED_FLAG ,
			BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_END_DTM ,
			BV_SALES_ORDER_LINE_TV.RU_SERVICE_CONTRACT_START_DTM,
			BV_SALES_ORDER_LINE_TV.REVENUE_TYPE_CODE,
			BV_SALES_ORDER_LINE_TV.TRX_BOOKING_SRC_CD,
			BV_SALES_ORDER_LINE_TV.ITEM_CATEGORY_DESCRIPTION ,
			SO.BK_SO_SOURCE_NAME ,
			SO.SALES_ORDER_PROGRAM_TYPE_NAME,
			SO.ORDER_LINE_CREATION_DATE,
			BV_SALES_ORDER_LINE_TV.END_TV_DATETIME,
			BV_SALES_ORDER_LINE_TV.SALES_ORDER_KEY,
			BV_SALES_ORDER_LINE_TV.SALES_ORDER_LINE_KEY
			FROM 
			$$SLSORDVWDB.N_SALES_ORDER_LINE_TV BV_SALES_ORDER_LINE_TV 
			LEFT JOIN (
			SELECT	SALES_ORDER_KEY,
				BK_SO_SOURCE_NAME,
				SALES_ORDER_PROGRAM_TYPE_NAME,
				trunc (BK_SO_SRC_CRT_DATETIME) AS ORDER_LINE_CREATION_DATE,
				Trunc(RU_CISCO_BOOKED_DATETIME) AS ORDER_HEADER_BOOKED_DATE,
				 CANCELLED_FLAG AS ORDER_CANCELLED_FLAG  
		FROM	$$SLSORDVWDB.N_SALES_ORDER ) SO 
		ON SO.SALES_ORDER_KEY = BV_SALES_ORDER_LINE_TV.SALES_ORDER_KEY 
	INNER JOIN ( SELECT BK_POS_TRANSACTION_ID_INT,SALES_ORDER_LINE_KEY FROM $$SLSORDVWDB.N_POS_TRX_LN_AS_NEW_OR_RNWL_TV  GROUP BY 1,2 ) PNVR 
	ON PNVR.SALES_ORDER_LINE_KEY=BV_SALES_ORDER_LINE_TV.SALES_ORDER_LINE_KEY 
	INNER JOIN ( SELECT BV_BKGS_MEASURE.BK_POS_TRANSACTION_ID_INT
FROM $$SLSORDVWDB.N_BKGS_MEASURE    BV_BKGS_MEASURE      
	INNER JOIN  $$STGDB.ST_BMK_POS_BKGS_TRANS FY20_TRX 
		ON  FY20_TRX.BK_POS_TRANSACTION_ID_INT = BV_BKGS_MEASURE.BK_POS_TRANSACTION_ID_INT  
	INNER JOIN $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR BV_FISCAL_DAY_TO_YEAR 
		ON BV_BKGS_MEASURE.BOOKINGS_PROCESS_DATE=BV_FISCAL_DAY_TO_YEAR.CALENDAR_DATE 
WHERE	 BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('POS') 
		AND BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_NUMBER_INT >= 2020  
		AND BV_BKGS_MEASURE.DV_REVENUE_RECOGNITION_FLG = 'Y' 
		AND BV_BKGS_MEASURE.SERVICE_FLG IN ('Y') 
		AND BV_BKGS_MEASURE.CORPORATE_BOOKINGS_FLG IN ('Y') 
		AND BV_BKGS_MEASURE.DV_ATTRIBUTION_CD IN ('ATTRIBUTED',
			'STANDALONE') 
		AND NOT EXISTS (
		SELECT	1 
		FROM	$$SLSORDVWDB.MT_SALES_MOTION_RPT RPT  
		WHERE	RPT.BOOKINGS_MEASURE_KEY =BV_BKGS_MEASURE.BOOKINGS_MEASURE_KEY 
			AND RPT.BOOKINGS_PROCESS_DATE=BV_BKGS_MEASURE.BOOKINGS_PROCESS_DATE 
			AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE=BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE)
GROUP BY 1  ) BV_BKGS_MEASURE
ON BV_BKGS_MEASURE.BK_POS_TRANSACTION_ID_INT=PNVR.BK_POS_TRANSACTION_ID_INT 
			) BV_SALES_ORDER_LINE_TV
ON PNVR.SALES_ORDER_LINE_KEY=BV_SALES_ORDER_LINE_TV.SALES_ORDER_LINE_KEY
AND BV_SALES_ORDER_LINE_TV.END_TV_DATETIME='3500-01-01 00:00:00'	 
	INNER JOIN $$SLSORDVWDB.MT_BKG_SLS_MOTION_ATTRIBUTION RTR
ON BV_BKGS_MEASURE.SK_SALES_MOTION_ATTRIB_KEY = RTR.SK_SALES_MOTION_ATTRIB_KEY
AND RTR.END_TV_DTM > CURRENT_TIMESTAMP(0)
LEFT JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE BKSO
ON BKSO.SALES_ORDER_LINE_KEY= RTR.SALES_ORDER_LINE_KEY
  INNER JOIN $$COMREFVWDB.R_PRODUCTS BP
ON (BP.ITEM_KEY = BV_BKGS_MEASURE.PRODUCT_KEY)
INNER JOIN $$STGDB.WI_SFH_RUP ST
ON ST.ITEM_KEY = BV_BKGS_MEASURE.DV_PRODUCT_KEY
/*LEFT JOIN (
SELECT SALES_ORDER_KEY,
BK_SO_SOURCE_NAME, 
SALES_ORDER_PROGRAM_TYPE_NAME, 
trunc (BK_SO_SRC_CRT_DATETIME) AS ORDER_LINE_CREATION_DATE,
 Trunc(RU_CISCO_BOOKED_DATETIME) AS ORDER_HEADER_BOOKED_DATE,
  CANCELLED_FLAG AS ORDER_CANCELLED_FLAG 
FROM $$SLSORDVWDB.N_SALES_ORDER ) SO
ON SO.SALES_ORDER_KEY = BV_SALES_ORDER_LINE_TV.SALES_ORDER_KEY*/
LEFT JOIN (
SELECT BK_PRDT_SUBGROUP_ID,
BK_GSP_ATTR_VAL_TXT  
FROM $$SERVICEVWDB.N_GENERIC_SVC_PRDT_ATTR
 WHERE BK_GSP_ATTR_NAME = 'SW SERVICE CATEGORY') SWSS
ON SWSS.BK_PRDT_SUBGROUP_ID =  BP.RU_BK_SERVICE_PROD_SUBGROUP_ID
INNER JOIN (
SELECT SALES_REP_NUM,
 ERP_SALES_REP_NAME 
FROM $$COMREFVWDB.MT_ERP_SALES_REP) SR
ON SR.SALES_REP_NUM = BV_BKGS_MEASURE.SALES_REP_NUMBER  
INNER JOIN (
SELECT  ITEM_KEY,
BK_PRODUCT_SUBGROUP_ID,
 BK_SERVICE_CATEGORY_ID,
  BK_ALLOCATED_SERVC_GROUP_ID,
ALLOCATION_PERCENTAGE
FROM $$COMREFVWDB.MT_SVC_FINANCE_HIERARCHY 
GROUP BY  1,2,3,4,5) SFH
ON SFH.ITEM_KEY = BP.ITEM_KEY
INNER JOIN(
SELECT EC.END_CUSTOMER_KEY,
     EC.CUSTOMER_PARTY_KEY,
     EC.ERP_WIPS_SITE_USE_ID_INT
 END_CUSTOMER_ID,
     EC.ERP_WIPS_CUSTOMER_NAME
 END_CUSTOMER_NAME,
     EC.ERP_WIPS_ISO_COUNTRY_CD,
     ECH.BRANCH_PARTY_SSOT_PARTY_ID_INT 
END_CUST_CRPARTY_ID,
     ECH.BRANCH_HQ_BRANCH_CD,
     ECH.BRANCH_PRIMARY_NAME ,
     CASE
 WHEN BRANCH_HQ_BRANCH_CD = 'BR' THEN HQ_PARTY_SSOT_PARTY_ID_INT
 ELSE BRANCH_PARTY_SSOT_PARTY_ID_INT
 END AS HQ_CRPARTY_ID,
     CASE 
WHEN BRANCH_HQ_BRANCH_CD = 'BR' THEN HQ_PRIMARY_NAME
 ELSE BRANCH_PRIMARY_NAME 
END AS HQ_CRPARTY_NAME,
     ECH.GU_PARTY_SSOT_PARTY_ID_INT GU_ID,
     ECH.GU_PRIMARY_NAME
FROM $$COMREFVWDB.MT_ERP_POS_ENDCUST EC
     JOIN $$COMREFVWDB.MT_ENDCUST_CUSTOMER_PARTY_HIER ECH
        ON (EC.END_CUSTOMER_KEY = ECH.END_CUSTOMER_KEY)) DE
ON (DE.END_CUSTOMER_KEY = BV_BKGS_MEASURE.END_CUSTOMER_KEY)
/*LEFT JOIN (SELECT MANUAL_TRX_KEY,
     BK_SALES_ADJ_LINE_NUMBER_INT,
     BK_SALES_ADJ_NUMBER_INT,
     IDE_IFC_COMMENT_1_TXT,
     IDE_IFC_COMMENT_2_TXT,
     IDE_IFC_COMMENT_3_TXT,
     IDE_IFC_COMMENT_4_TXT,
     IDE_IFC_COMMENT_5_TXT,
     IDE_IFC_DESCRIPTION_TXT
FROM $$SLSORDVWDB.N_SALES_ADJUSTMENT_LINE) SAL
ON BV_BKGS_MEASURE.BOOKINGS_MEASURE_KEY = SAL.BK_SALES_ADJ_LINE_NUMBER_INT            
LEFT JOIN (SELECT MANUAL_TRX_KEY,
                               UPLOADED_BY_ERP_USER_NAME,
                               MANUAL_TRANSACTION_TYPE_CD,
                               MANUAL_TRANSACTION_USAGE_CD,
                               MANUAL_TRX_BOOKING_REVENUE_CD
                          FROM $$SLSORDVWDB.N_SALES_ADJ_REBOK_MNL_TRX) RB
          ON SAL.MANUAL_TRX_KEY = RB.MANUAL_TRX_KEY  */  
LEFT OUTER JOIN (
SELECT AR_TRX_KEY,
 BK_AR_TRX_NUMBER,
 AR_TRX_REASON_CODE 
  FROM $$FINLGLVWDB.N_AR_TRX) ART
          ON (BV_BKGS_MEASURE.AR_TRX_KEY = ART.AR_TRX_KEY)
INNER JOIN $$COMREFVWDB.MT_BE_HIER_PRDT_FAMILY_ALLOC  BE
    ON ( BE.ITEM_KEY = BV_BKGS_MEASURE.PRODUCT_KEY 
    AND BE.FISCAL_YEAR_QUARTER_NUMBER_INT = BV_BKGS_MEASURE.FISCAL_YEAR_QUARTER_NUMBER_INT
    AND BE.BK_BUSINESS_ENTITY_TYPE_CD = 'I' )
WHERE  BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE IN ('POS')
AND BV_FISCAL_DAY_TO_YEAR.FISCAL_YEAR_NUMBER_INT >= 2020 
AND BV_BKGS_MEASURE.DV_REVENUE_RECOGNITION_FLG = 'Y'
AND BV_BKGS_MEASURE.SERVICE_FLG IN ('Y')
AND BV_BKGS_MEASURE.CORPORATE_BOOKINGS_FLG IN ('Y')
AND BV_BKGS_MEASURE.DV_ATTRIBUTION_CD IN ('ATTRIBUTED',
'STANDALONE')
AND NOT EXISTS (
SELECT 1 
FROM $$SLSORDVWDB.MT_SALES_MOTION_RPT RPT 
WHERE RPT.BOOKINGS_MEASURE_KEY =BV_BKGS_MEASURE.BOOKINGS_MEASURE_KEY
AND RPT.BOOKINGS_PROCESS_DATE=BV_BKGS_MEASURE.BOOKINGS_PROCESS_DATE
AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE=BV_BKGS_MEASURE.BKGS_MEASURE_TRANS_TYPE_CODE)


Post SQL : 



Target2 Name : MT_SALES_MOTION_RPT1


Pre SQL : 



Post SQL : 
UPDATE RPT FROM
$$SLSORDVWDB.MT_SALES_MOTION_RPT RPT,
$$COMREFVWDB.R_PRODUCTS PRDT ,
$$SLSORDVWDB.N_BKGS_MEASURE BKGS
SET ORDERED_ITEM=PRDT.BK_PRODUCT_ID
, EDW_UPDATE_DTM =CURRENT_TIMESTAMP(0)  
WHERE BKGS.DV_PRODUCT_KEY=PRDT.ITEM_KEY
AND RPT.BOOKINGS_MEASURE_KEY =BKGS.BOOKINGS_MEASURE_KEY
AND RPT.BOOKINGS_PROCESS_DATE=BKGS.BOOKINGS_PROCESS_DATE
AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE=BKGS.BKGS_MEASURE_TRANS_TYPE_CODE
AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE= 'POS'
AND RPT.ORDERED_ITEM='UNKNOWN' ;
 
UPDATE RPT FROM
$$SLSORDVWDB.MT_SALES_MOTION_RPT RPT,
$$COMREFVWDB.R_PRODUCTS PRDT ,
(SELECT  SK_SALES_MOTION_ATTRIB_KEY,DV_ENTERPRISE_INV_SKU_ID,END_TV_DTM from 
$$SLSORDVWDB.MT_BKG_SLS_MOTION_ATTRIBUTION where END_TV_DTM > CURRENT_TIMESTAMP(0) group by 1,2,3) RTR
SET ENTERPRISE_SKU=PRDT.SK_INVENTORY_ITEM_ID_INT
, EDW_UPDATE_DTM  =CURRENT_TIMESTAMP(0)  
WHERE RTR.DV_ENTERPRISE_INV_SKU_ID=PRDT.ITEM_KEY
AND  RPT.SK_SALES_MOTION_ATTRIB_KEY=RTR.SK_SALES_MOTION_ATTRIB_KEY
AND RPT.RTR_SRC_ENTERPRISE_INV_SKU_ID=RTR.DV_ENTERPRISE_INV_SKU_ID
AND RTR.END_TV_DTM > CURRENT_TIMESTAMP(0)
AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE= 'POS'
AND RPT.ENTERPRISE_SKU =-999;
 
--- Notify RTR_OFFER_TYPE used for General offer type logic value
UPDATE RPT FROM
$$SLSORDVWDB.MT_SALES_MOTION_RPT RPT,
( SELECT RPT.BOOKINGS_MEASURE_KEY,RPT.BOOKINGS_PROCESS_DATE,RPT.BK_SERVICE_CATEGORY_ID,
CASE WHEN ST.BK_SERVICE_CATEGORY_ID IN 'COMBINED SERVICES' THEN 'COMBINED SERVICES'
WHEN RPT.BK_ALLOCATED_SERVC_GROUP_ID IN 'FOCUSED TECHNICAL SUPPORT SERVICES' THEN 'FTSS' 
WHEN RPT.FINANCE_BU_SW_TYPE = 'SWSS' THEN 'SWSS' 
WHEN RPT.BK_ALLOCATED_SERVC_GROUP_ID IN ('CLOUD MANAGED SERVICES') THEN 'CMS'
WHEN ( RPT.BK_ALLOCATED_SERVC_GROUP_ID IN 'AS SUBSCRIPTION' AND RPT.RU_BK_SERVICE_PROD_SUBGROUP_ID NOT LIKE 'NC%' ) THEN 'AS-S'
WHEN ( RPT.BK_ALLOCATED_SERVC_GROUP_ID IN ('AS TRANSACTION','TRAINING','AS FIXED') AND RPT.RU_BK_SERVICE_PROD_SUBGROUP_ID NOT LIKE 'NC%' ) THEN RPT.BK_ALLOCATED_SERVC_GROUP_ID                            
WHEN TTS.SALES_ORDER_LINE_KEY IS NOT NULL THEN 'TSS' 
ELSE 'OTHERS' END OFFER_TYPE
FROM $$SLSORDVWDB.MT_SALES_MOTION_RPT RPT
INNER JOIN (SELECT BOOKINGS_MEASURE_KEY,BOOKINGS_PROCESS_DATE,DV_PRODUCT_KEY FROM $$SLSORDVWDB.N_BKGS_MEASURE 
WHERE BKGS_MEASURE_TRANS_TYPE_CODE = 'POS' GROUP BY 1,2,3) BKGS
ON BKGS.BOOKINGS_MEASURE_KEY=RPT.BOOKINGS_MEASURE_KEY
AND BKGS.BOOKINGS_PROCESS_DATE=RPT.BOOKINGS_PROCESS_DATE
INNER JOIN $$STGDB.WI_SFH_RUP ST
    ON ST.ITEM_KEY = BKGS.DV_PRODUCT_KEY
LEFT JOIN $$STGDB.WI_TTS_SOWB_SOL_LINES TTS
    ON RPT.DV_SALES_ORDER_LINE_KEY = TTS.SALES_ORDER_LINE_KEY
WHERE RPT.BKGS_MEASURE_TRANS_TYPE_CODE= 'POS'
GROUP BY 1,2,3,4
) OFFER
SET SMR_OFFER_TYPE=OFFER.OFFER_TYPE
, EDW_UPDATE_DTM  =CURRENT_TIMESTAMP(0)  
WHERE  RPT.BOOKINGS_MEASURE_KEY=OFFER.BOOKINGS_MEASURE_KEY
AND RPT.BOOKINGS_PROCESS_DATE=OFFER.BOOKINGS_PROCESS_DATE
AND RPT.BK_SERVICE_CATEGORY_ID=OFFER.BK_SERVICE_CATEGORY_ID
AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE = 'POS'
AND RPT.SMR_OFFER_TYPE ='UNKNOWN';

UPDATE RPT 
FROM $$SLSORDVWDB.MT_SALES_MOTION_RPT RPT,
( SELECT BK_POS_TRANSACTION_ID_INT,SALES_MOTION_CD,
CASE 
  WHEN  SALES_MOTION_CD IN ('NEW','RENEW') THEN 
      CASE WHEN MATCHING_MTHD_FOR_TAGGING_NAME IN ('DEFAULT_SM_TAGGING','46_54 ENRICHMENT') THEN 'DEFAULT SLA LOGIC'
                  WHEN MATCHING_MTHD_FOR_TAGGING_NAME IN ('SO ENRICHMENT','DIST_HQ ENRICHMENT','DEFAULT SOL ENRIHMENT') THEN 'POS ENRICHMENT'
                  WHEN (MATCHING_MTHD_FOR_TAGGING_NAME IN ('MANUAL TAGGING') OR MANUAL_OVERRIDE_ROLE ='Y'  ) AND  SLS_MTN_CORRECTION_CASE_NUM = 'UNKNOWN' THEN 'MANUAL CORRECTION - PROACTIVE DISPOSITION'
                  WHEN (MATCHING_MTHD_FOR_TAGGING_NAME IN ('MANUAL TAGGING') OR MANUAL_OVERRIDE_ROLE ='Y'  ) AND  SLS_MTN_CORRECTION_CASE_NUM <> 'UNKNOWN' THEN 'MANUAL CORRECTION - WITH CASE NUMBER'
           ELSE 'SYSTEM TAGGED'
      END ELSE 'SYSTEM TAGGED'
      END     AS   SMC_SOURCE_TAG
FROM 
$$SLSORDVWDB.N_POS_TRX_LN_AS_NEW_OR_RNWL_TV 
WHERE   END_TV_DTM='3500-01-01 00:00:00' 
QUALIFY ROW_NUMBER() OVER(PARTITION BY BK_POS_TRANSACTION_ID_INT,SALES_MOTION_CD ORDER BY SMC_SOURCE_TAG DESC)=1
  )SRC
SET SMC_SOURCE_TAG=SRC.SMC_SOURCE_TAG
,EDW_UPDATE_DTM  =CURRENT_TIMESTAMP(0)  
 WHERE RPT.BK_POS_TRANSACTION_ID_INT=SRC.BK_POS_TRANSACTION_ID_INT
AND RPT.SALES_MOTION_CD=SRC.SALES_MOTION_CD
AND RPT.BKGS_MEASURE_TRANS_TYPE_CODE = 'POS' 
 AND RPT.SMC_SOURCE_TAG IS NULL;

CALL COLLECT_STATS_WRAP ('$$SLSORDDB','MT_SALES_MOTION_RPT','D') ;