


Source1 Name : SQ_W_ATTR_PRDT_AS_NEW_OR_RNWL_ERP


Pre SQL : 



SQL Query : 
SELECT 
ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
DEAL_QUOTE_LINE_KEY,
SK_RTR_ATTRIBUTION_ID,
SALES_ORDER_LINE_KEY,
ATTR_PRDT_KEY,
BK_QUOTE_NUM,
BK_SRC_EFFECTIVE_START_DT,
SRC_EFFECTIVE_END_DT,
COVERED_PRDT_KEY,
ATTR_PRDT_QTY,
ATTR_PCT,
ATTR_NET_PRICE_LOCAL_AMT,
ATTR_EXTD_PRICE_LOCAL_AMT,
SALES_MOTION_CD,
SALES_MOTION_CONTEXT_NAME,
SRC_CREATED_DTM,
DV_SRC_CREATED_DT,
SRC_CREATED_CSCO_WRKR_PRTY_KEY,
SRC_LAST_UPDATED_DTM,
DV_SRC_LAST_UPDATED_DT,
SRC_LST_UPD_CSCO_WRKR_PRTY_KEY,
ERP_CUST_ACCT_LOC_KEY,
AS_TS_CD,
SK_LINE_REF_NUM,
BK_AS_ARCHITECTURE_NAME,
BK_TECH_GROUP_ID,
BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
TRANSACTION_CR_PARTY_KEY,
SK_ERP_BKGS_TRX_ID,
SK_RENEW_CONTRACT_LINE_ID,
SK_AS_PARENT_INVENTORY_ITEM_ID,
ITEM_CATEGORY_NAME,
ERP_TRX_VERSION_INT,
SS_CD,
SK_ATTRIBUTION_ID_INT,
EDW_CREATE_DTM,
EDW_CREATE_USER,
EDW_UPDATE_DTM,
EDW_UPDATE_USER,
START_TV_DTM, 
END_TV_DTM,
ATTR_PRDT_CLASS_NAME,
HQ_CR_PRTY_KEY ,
RENEWAL_REF_ID,
RENEWAL_REF_CD,
SMR_TAGGING_FAILURE_RSN_CD,
SALES_MOTION_TIMING_CD
FROM
$$WORKDB.W_ATTR_PRDT_AS_NEW_OR_RNWL_ERP ST
 WHERE  NOT EXISTS (SELECT 1 FROM  $$SLSORDVWDB.N_ATTR_PRDT_AS_NEW_OR_RNWL_TV N_ATTR_TV
					WHERE N_ATTR_TV.ATTR_PRDT_AS_NEW_OR_RNWL_KEY = ST.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
					AND N_ATTR_TV.END_TV_DTM = '3500-01-01 00:00:00')


Post SQL : 



Target1 Name : N_ATTR_PRDT_AS_NEW_OR_RNWL_TV


Pre SQL : 
UPDATE NXSSIST
FROM $$SLSORDVWDB.N_ATTR_PRDT_AS_NEW_OR_RNWL_TV NXSSIST,
$$WORKDB.W_ATTR_PRDT_AS_NEW_OR_RNWL_ERP WXSSIT
SET 
DEAL_QUOTE_LINE_KEY				= 		WXSSIT.DEAL_QUOTE_LINE_KEY,
SK_RTR_ATTRIBUTION_ID		    = 		WXSSIT.SK_RTR_ATTRIBUTION_ID,
SALES_ORDER_LINE_KEY 			= 		WXSSIT.SALES_ORDER_LINE_KEY,
ATTR_PRDT_KEY     				= 		WXSSIT.ATTR_PRDT_KEY,
BK_QUOTE_NUM     				= 		WXSSIT.BK_QUOTE_NUM,
BK_SRC_EFFECTIVE_START_DT  		= 		WXSSIT.BK_SRC_EFFECTIVE_START_DT,
SRC_EFFECTIVE_END_DT   			= 		WXSSIT.SRC_EFFECTIVE_END_DT, 
COVERED_PRDT_KEY    			= 		WXSSIT.COVERED_PRDT_KEY,
ATTR_PRDT_QTY     				= 		WXSSIT.ATTR_PRDT_QTY,
ATTR_PCT      					= 		WXSSIT.ATTR_PCT,
ATTR_NET_PRICE_LOCAL_AMT  		= 		WXSSIT.ATTR_NET_PRICE_LOCAL_AMT,
ATTR_EXTD_PRICE_LOCAL_AMT  		= 		WXSSIT.ATTR_EXTD_PRICE_LOCAL_AMT,
SALES_MOTION_CD     			= 		WXSSIT.SALES_MOTION_CD,
SALES_MOTION_CONTEXT_NAME  		= 		WXSSIT.SALES_MOTION_CONTEXT_NAME,
SRC_CREATED_DTM         		= 		WXSSIT.SRC_CREATED_DTM,
DV_SRC_CREATED_DT    			= 		WXSSIT.DV_SRC_CREATED_DT,
SRC_CREATED_CSCO_WRKR_PRTY_KEY 	= 		WXSSIT.SRC_CREATED_CSCO_WRKR_PRTY_KEY,
SRC_LAST_UPDATED_DTM   			= 		WXSSIT.SRC_LAST_UPDATED_DTM,
DV_SRC_LAST_UPDATED_DT  		= 		WXSSIT.DV_SRC_LAST_UPDATED_DT,
SRC_LST_UPD_CSCO_WRKR_PRTY_KEY	= 		WXSSIT.SRC_LST_UPD_CSCO_WRKR_PRTY_KEY,
ERP_CUST_ACCT_LOC_KEY   		= 		WXSSIT.ERP_CUST_ACCT_LOC_KEY,
AS_TS_CD 					    = 		WXSSIT.AS_TS_CD,
SK_LINE_REF_NUM   				= 		WXSSIT.SK_LINE_REF_NUM,
BK_AS_ARCHITECTURE_NAME         =  		WXSSIT.BK_AS_ARCHITECTURE_NAME,
BK_TECH_GROUP_ID   				= 		WXSSIT.BK_TECH_GROUP_ID,
BK_DV_ATTR_PRDT_OFFER_TYPE_NAME = 		WXSSIT.BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
TRANSACTION_CR_PARTY_KEY   		= 		WXSSIT.TRANSACTION_CR_PARTY_KEY,
SK_ERP_BKGS_TRX_ID  			= 		WXSSIT.SK_ERP_BKGS_TRX_ID,
SK_RENEW_CONTRACT_LINE_ID  		= 		WXSSIT.SK_RENEW_CONTRACT_LINE_ID,
SK_AS_PARENT_INVENTORY_ITEM_ID  = 		WXSSIT.SK_AS_PARENT_INVENTORY_ITEM_ID,
ITEM_CATEGORY_NAME    			= 		WXSSIT.ITEM_CATEGORY_NAME,
ERP_TRX_VERSION_INT   			= 		WXSSIT.ERP_TRX_VERSION_INT,
EDW_UPDATE_DTM					= 		CURRENT_TIMESTAMP(0) ,
EDW_UPDATE_USER		            =       USER,
START_TV_DTM					=		WXSSIT.START_TV_DTM,
END_TV_DTM					    =		WXSSIT.END_TV_DTM
WHERE 
WXSSIT.ATTR_PRDT_AS_NEW_OR_RNWL_KEY = NXSSIST.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NXSSIST.END_TV_DTM = CAST('3500-01-01 00:00:00' AS TIMESTAMP(0));


Post SQL : 
CALL COLLECT_STATS_WRAP('$$SLSORDDB','N_ATTR_PRDT_AS_NEW_OR_RNWL_TV','D');


Source2 Name : SQ_N_ATTR_PRDT_AS_NEW_OR_RNWL_TV


Pre SQL : 



SQL Query : 
SELECT
ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
DEAL_QUOTE_LINE_KEY,
SK_RTR_ATTRIBUTION_ID,
SALES_ORDER_LINE_KEY,
ATTR_PRDT_KEY,
BK_QUOTE_NUM,
BK_SRC_EFFECTIVE_START_DT,
SRC_EFFECTIVE_END_DT,
COVERED_PRDT_KEY,
ATTR_PRDT_QTY,
ATTR_PCT,
ATTR_NET_PRICE_LOCAL_AMT,
ATTR_EXTD_PRICE_LOCAL_AMT,
SALES_MOTION_CD,
SALES_MOTION_CONTEXT_NAME,
SRC_CREATED_DTM,
DV_SRC_CREATED_DT,
SRC_CREATED_CSCO_WRKR_PRTY_KEY,
SRC_LAST_UPDATED_DTM,
DV_SRC_LAST_UPDATED_DT,
SRC_LST_UPD_CSCO_WRKR_PRTY_KEY,
ERP_CUST_ACCT_LOC_KEY,
AS_TS_CD,
SK_LINE_REF_NUM,
BK_AS_ARCHITECTURE_NAME,
BK_TECH_GROUP_ID,
BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
TRANSACTION_CR_PARTY_KEY,
SK_ERP_BKGS_TRX_ID,
SK_RENEW_CONTRACT_LINE_ID,
SK_AS_PARENT_INVENTORY_ITEM_ID,
ITEM_CATEGORY_NAME,
ERP_TRX_VERSION_INT,
SS_CD,
SK_ATTRIBUTION_ID_INT,
EDW_CREATE_DTM,
EDW_CREATE_USER,
EDW_UPDATE_DTM,
EDW_UPDATE_USER,
ATTR_PRDT_CLASS_NAME,
HQ_CR_PRTY_KEY ,
RENEWAL_REF_ID,
RENEWAL_REF_CD,
SMR_TAGGING_FAILURE_RSN_CD,
SALES_MOTION_TIMING_CD
FROM $$SLSORDVWDB.N_ATTR_PRDT_AS_NEW_OR_RNWL_TV NXSSIS
WHERE NXSSIS.END_TV_DTM=CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))


Post SQL : 



Target2 Name : N_ATTR_PRDT_AS_NEW_OR_RNWL


Pre SQL : 
DELETE FROM $$SLSORDVWDB.N_ATTR_PRDT_AS_NEW_OR_RNWL ALL;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$SLSORDDB','N_ATTR_PRDT_AS_NEW_OR_RNWL','D');