


Source1 Name : SQ_N_ATTR_PRDT_NEW_RNWL_ACV_TV


Pre SQL : 



SQL Query : 
SELECT
ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
SK_RTR_ATTRIBUTION_ID,
ATTR_PRDT_KEY,
SALES_ORDER_LINE_KEY,
HQ_CR_PRTY_KEY,
TRANSACTION_CR_PARTY_KEY,
BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
BK_TECH_GROUP_ID,
BK_AS_ARCHITECTURE_NAME,
COVERED_PRDT_KEY,
ATTR_PRDT_QTY,
ATTR_PCT,
ATTR_NET_PRICE_LOCAL_AMT,
ATTR_EXTD_PRICE_LOCAL_AMT,
SALES_MOTION_CD,
SALES_MOTION_CONTEXT_NAME,
ERP_CUST_ACCT_LOC_KEY,
AS_TS_CD,
SK_LINE_REF_NUM,
SK_ERP_BKGS_TRX_ID,
SK_RENEW_CONTRACT_LINE_ID,
SK_AS_PARENT_INVENTORY_ITEM_ID,
ITEM_CATEGORY_NAME,
ERP_TRX_VERSION_INT,
SS_CD,
SK_ATTRIBUTION_ID_INT,
ATTR_PRDT_CLASS_NAME,
RENEWAL_REF_ID,
RENEWAL_REF_CD,
SMR_TAGGING_FAILURE_RSN_CD,
SALES_MOTION_TIMING_CD,
MANUAL_OVERRIDE_ROLE,
TOTAL_SERVICES_USD_AMT,
ACV_USD_AMT,
TCV_USD_AMT,
EXTENDED_PRICE_USD_AMT,
REQUESTING_CSCO_WRKR_PRTY_KEY,
SLS_MTN_CORRECTION_CASE_NUM,
SLS_MTN_CORRECTION_CMNT,
EDW_CREATE_DTM,
EDW_CREATE_USER,
EDW_UPDATE_DTM,
EDW_UPDATE_USER,
START_TV_DTM,
END_TV_DTM,
OFFER_ATTRIB_PRDT_KEY
FROM $$WORKDB.W_ATTR_PRDT_NEW_RNWL_ACV WSISN


Post SQL : 



Target1 Name : N_ATTR_PRDT_NEW_RNWL_ACV_TV


Pre SQL : 
UPDATE N_ATTR_TV
FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV N_ATTR_TV,
     ( SELECT SK_ERP_BKGS_TRX_ID,ERP_TRX_VERSION_INT,MAX(START_TV_DTM) AS START_TV_DTM
        FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV WI
       GROUP BY 1,2
      ) WI        
SET 
	END_TV_DTM  = WI.START_TV_DTM - INTERVAL '1' DAY,
	EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0), /* added as part of CR CHG0382388 */
	EDW_UPDATE_USER = CURRENT_USER /* added as part of CR CHG0382388 */
WHERE WI.SK_ERP_BKGS_TRX_ID = N_ATTR_TV.SK_ERP_BKGS_TRX_ID
AND WI.START_TV_DTM <> N_ATTR_TV.START_TV_DTM
AND WI.ERP_TRX_VERSION_INT <>N_ATTR_TV.ERP_TRX_VERSION_INT
  AND N_ATTR_TV.END_TV_DTM = '3500-01-01 00:00:00' ;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$SLSORDDB','N_ATTR_PRDT_NEW_RNWL_ACV_TV','D');
COLLECT STATS COLUMN (SALES_ORDER_LINE_KEY ) ON $$STGDB.SMT_RETRO_UPD;


Source2 Name : SQ_N_ATTR_PRDT_NEW_RNWL_ACV


Pre SQL : 



SQL Query : 
SELECT
ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
SK_RTR_ATTRIBUTION_ID,
ATTR_PRDT_KEY,
SALES_ORDER_LINE_KEY,
HQ_CR_PRTY_KEY,
TRANSACTION_CR_PARTY_KEY,
BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
BK_TECH_GROUP_ID,
BK_AS_ARCHITECTURE_NAME,
COVERED_PRDT_KEY,
ATTR_PRDT_QTY,
ATTR_PCT,
ATTR_NET_PRICE_LOCAL_AMT,
ATTR_EXTD_PRICE_LOCAL_AMT,
SALES_MOTION_CD,
SALES_MOTION_CONTEXT_NAME,
ERP_CUST_ACCT_LOC_KEY,
AS_TS_CD,
SK_LINE_REF_NUM,
SK_ERP_BKGS_TRX_ID,
SK_RENEW_CONTRACT_LINE_ID,
SK_AS_PARENT_INVENTORY_ITEM_ID,
ITEM_CATEGORY_NAME,
ERP_TRX_VERSION_INT,
SS_CD,
SK_ATTRIBUTION_ID_INT,
ATTR_PRDT_CLASS_NAME,
RENEWAL_REF_ID,
RENEWAL_REF_CD,
SMR_TAGGING_FAILURE_RSN_CD,
SALES_MOTION_TIMING_CD,
MANUAL_OVERRIDE_ROLE,
TOTAL_SERVICES_USD_AMT,
ACV_USD_AMT,
TCV_USD_AMT,
EXTENDED_PRICE_USD_AMT,
REQUESTING_CSCO_WRKR_PRTY_KEY,
SLS_MTN_CORRECTION_CASE_NUM,
SLS_MTN_CORRECTION_CMNT,
EDW_CREATE_DTM,
EDW_CREATE_USER,
EDW_UPDATE_DTM,
EDW_UPDATE_USER,
OFFER_ATTRIB_PRDT_KEY
FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NXSSIS
WHERE NXSSIS.END_TV_DTM=CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))


Post SQL : 



Target2 Name : N_ATTR_PRDT_NEW_RNWL_ACV


Pre SQL : 
DELETE FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV ALL;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$SLSORDDB','N_ATTR_PRDT_NEW_RNWL_ACV','D');


DELETE FROM $$STGDB.WI_TTS_SOWB_SOL_LINES_ACV ;

INSERT INTO $$STGDB.WI_TTS_SOWB_SOL_LINES_ACV
SELECT 
	NSOL.SALES_ORDER_LINE_KEY ,
	NSOL.SALES_MOTION_CD,
	CASE WHEN NSOL.SALES_MOTION_CD = 'RENEW' THEN NSOL.SALES_MOTION_TIMING_NAME 
	ELSE 'UNKNOWN'
	END SALES_MOTION_TIMING_CD	
FROM $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL 
  WHERE NSOL.SS_CODE = 'CG' 
   /*AND NOT EXISTS ( SELECT 1 FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV ATT WHERE ATT.SALES_ORDER_LINE_KEY = NSOL.SALES_ORDER_LINE_KEY )*/
   AND ( EXISTS (
    SELECT 1 FROM (SELECT 
       P.ITEM_KEY
       FROM
       $$COMREFVWDB.N_PRODUCT P
       INNER JOIN 
       $$COMREFVWDB.MT_SVC_FINANCE_HIERARCHY SFH ON P.ITEM_KEY = SFH.ITEM_KEY
       WHERE P.PRDT_SETUP_CLASSIFICATION_CD <> 'SOFTWARE' --EXCLUDE SW
       AND SFH.BK_SERVICE_CATEGORY_ID = 'TECHNICAL SUPPORT SERVICES' 
       AND SFH.BK_ALLOCATED_SERVC_GROUP_ID NOT IN
       ( 'AS CORE' ,  'AS SUBSCRIPTION' , 'FOCUSED TECHNICAL SUPPORT SERVICES' , 'CLOUD MANAGED SERVICES' )--EXCLUDE FTS,CMS,AS
       AND RU_BK_SERVICE_PROD_SUBGROUP_ID NOT IN (SELECT BK_PRDT_SUBGROUP_ID FROM ( SELECT * FROM $$SERVICEVWDB.N_GENERIC_SVC_PRDT_ATTR WHERE BK_GSP_ATTR_NAME = 'SW SERVICE CATEGORY' ) WI ) --EXCLUDE SWSS
       ) WI
     WHERE NSOL.PRODUCT_KEY = WI.ITEM_KEY
   )
   OR (NSOL.BK_SO_SRC_NAME IN ('Manual', 'Copy' ) AND NSOL.PRODUCT_KEY NOT IN ( SELECT P.ITEM_KEY FROM
      $$COMREFVWDB.N_PRODUCT P
      INNER JOIN 
      $$COMREFVWDB.MT_SVC_FINANCE_HIERARCHY SFH ON P.ITEM_KEY = SFH.ITEM_KEY
      AND SFH.BK_ALLOCATED_SERVC_GROUP_ID  IN ( 'AS FIXED', 'AS TRANSACTION' )
     )
                 )
   )
GROUP BY 1,2,3 ;

COLLECT STATS COLUMN (SALES_ORDER_LINE_KEY ) ON $$STGDB.WI_TTS_SOWB_SOL_LINES_ACV ;