


Source1 Name : SQ_N_ATTR_PRDT_NEW_RNWL_ACV_TV


Pre SQL : 



SQL Query : 
SELECT
ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
SK_RTR_ATTRIBUTION_ID,
ATTR_PRDT_KEY,
SALES_ORDER_LINE_KEY,
HQ_CR_PRTY_KEY,
TRANSACTION_CR_PARTY_KEY,
BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
BK_TECH_GROUP_ID,
BK_AS_ARCHITECTURE_NAME,
COVERED_PRDT_KEY,
ATTR_PRDT_QTY,
ATTR_PCT,
ATTR_NET_PRICE_LOCAL_AMT,
ATTR_EXTD_PRICE_LOCAL_AMT,
SALES_MOTION_CD,
SALES_MOTION_CONTEXT_NAME,
ERP_CUST_ACCT_LOC_KEY,
AS_TS_CD,
SK_LINE_REF_NUM,
SK_ERP_BKGS_TRX_ID,
SK_RENEW_CONTRACT_LINE_ID,
SK_AS_PARENT_INVENTORY_ITEM_ID,
ITEM_CATEGORY_NAME,
ERP_TRX_VERSION_INT,
SS_CD,
SK_ATTRIBUTION_ID_INT,
ATTR_PRDT_CLASS_NAME,
RENEWAL_REF_ID,
RENEWAL_REF_CD,
SMR_TAGGING_FAILURE_RSN_CD,
SALES_MOTION_TIMING_CD,
MANUAL_OVERRIDE_ROLE,
TOTAL_SERVICES_USD_AMT,
ACV_USD_AMT,
TCV_USD_AMT,
EXTENDED_PRICE_USD_AMT,
REQUESTING_CSCO_WRKR_PRTY_KEY,
SLS_MTN_CORRECTION_CASE_NUM,
SLS_MTN_CORRECTION_CMNT,
EDW_CREATE_DTM,
EDW_CREATE_USER,
EDW_UPDATE_DTM,
EDW_UPDATE_USER,
START_TV_DTM,
END_TV_DTM,
OFFER_ATTRIB_PRDT_KEY,
POS_TRANSACTION_ID_INT,
ORDER_ORIGIN_CD,
DV_RENEWAL_GAP_DAYS_CNT
FROM $$WORKDB.W_ATTR_PRDT_NEW_RNWL_ACV WSISN


Post SQL : 



Target1 Name : N_ATTR_PRDT_NEW_RNWL_ACV_TV


Pre SQL : 
UPDATE N_ATTR_TV
FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV N_ATTR_TV,
     ( SELECT SK_ERP_BKGS_TRX_ID,ERP_TRX_VERSION_INT,MAX(START_TV_DTM) AS START_TV_DTM
        FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV WI
		WHERE POS_TRANSACTION_ID_INT < 0
       GROUP BY 1,2
      ) WI        
SET 
	END_TV_DTM  = WI.START_TV_DTM - INTERVAL '1' DAY,
	EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0), /* added as part of CR CHG0382388 */
	EDW_UPDATE_USER = CURRENT_USER /* added as part of CR CHG0382388 */
WHERE WI.SK_ERP_BKGS_TRX_ID = N_ATTR_TV.SK_ERP_BKGS_TRX_ID
AND WI.START_TV_DTM <> N_ATTR_TV.START_TV_DTM
AND WI.ERP_TRX_VERSION_INT <>N_ATTR_TV.ERP_TRX_VERSION_INT
  AND N_ATTR_TV.END_TV_DTM = '3500-01-01 00:00:00' 
  AND N_ATTR_TV.POS_TRANSACTION_ID_INT<0;
  
  UPDATE N_ATTR_TV
FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV N_ATTR_TV,
     ( SELECT POS_TRANSACTION_ID_INT,ERP_TRX_VERSION_INT,MAX(START_TV_DTM) AS START_TV_DTM
        FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV WI
		WHERE POS_TRANSACTION_ID_INT>0
       GROUP BY 1,2
      ) WI        
SET 
	END_TV_DTM  = WI.START_TV_DTM - INTERVAL '1' DAY,
	EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0), /* added as part of CR CHG0382388 */
	EDW_UPDATE_USER = CURRENT_USER /* added as part of CR CHG0382388 */
WHERE WI.POS_TRANSACTION_ID_INT = N_ATTR_TV.POS_TRANSACTION_ID_INT
AND WI.START_TV_DTM <> N_ATTR_TV.START_TV_DTM
AND WI.ERP_TRX_VERSION_INT <>N_ATTR_TV.ERP_TRX_VERSION_INT
  AND N_ATTR_TV.END_TV_DTM = '3500-01-01 00:00:00' 
  AND N_ATTR_TV.POS_TRANSACTION_ID_INT > 0;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$SLSORDDB','N_ATTR_PRDT_NEW_RNWL_ACV_TV','D');
COLLECT STATS COLUMN (SALES_ORDER_LINE_KEY ) ON $$STGDB.SMT_RETRO_UPD;

DELETE FROM $$STGDB.WI_SMR_XAAS_RENEW_TRX_INC;
INSERT INTO  $$STGDB.WI_SMR_XAAS_RENEW_TRX_INC
SELECT TRX.*,NSOL.ORIGINAL_SYSTEM_LINE_REF_ID,NSOL.BK_SALES_CHANNEL_CD 
FROM (SELECT DISTINCT SO_SBSCRPTN_ITM_SLS_TRX_KEY,SK_TRX_ID_INT,TRX.BOOKED_DT,
WEB_ORDER_ID,MINOR_LN_EXAAS_SUBSCR_SOL_KEY,TERM_START_DT,TERM_END_DT,DV_LINE_REF_NUM_INT
FROM
$$EXAASVWDB.N_EXAAS_SUBSCRIPTION_TV  HDRT
INNER JOIN $$SLSORDVWDB.N_XAAS_SO_SBSCR_ITM_SLS_TRX TRX
ON TRX.DV_LINKED_MJR_LN_REF_NUM_KEY=HDRT.MJR_LN_EXAAS_SBSCRN_SO_LN_KEY
AND TRX.SUBSCRIPTION_REFERENCE_ID=HDRT.SUBSCRIPTION_REF_ID
AND TRX.MINOR_LN_EXAAS_SUBSCR_SOL_KEY>0
AND END_TV_DT= '3500-01-01 00:00:00'
QUALIFY ROW_NUMBER() OVER (PARTITION BY SO_SBSCRPTN_ITM_SLS_TRX_KEY ORDER BY END_TV_DT DESC)=1)TRX
INNER JOIN (SELECT BK_LINE_REF_NUM,SALES_ORDER_LINE_KEY,ORIGINAL_SYSTEM_LINE_REF_ID,BK_SALES_CHANNEL_CD
FROM $$SLSORDVWDB.N_SALES_ORDER_LINE
WHERE SS_CODE IN ('CG','OPL')
QUALIFY ROW_NUMBER() OVER ( PARTITION BY BK_LINE_REF_NUM ORDER BY BK_LINE_REF_NUM DESC)=1)NSOL
ON  TRX.MINOR_LN_EXAAS_SUBSCR_SOL_KEY=NSOL.SALES_ORDER_LINE_KEY
AND CAST(TRX.DV_LINE_REF_NUM_INT AS BIGINT)=CAST(NSOL.BK_LINE_REF_NUM  AS BIGINT);

COLLECT STATISTICS COLUMN(SO_SBSCRPTN_ITM_SLS_TRX_KEY)ON $$STGDB.WI_SMR_XAAS_RENEW_TRX_INC;

DELETE FROM $$STGDB.WI_SMR_POS_RENEW_TRX_INC;
INSERT INTO $$STGDB.WI_SMR_POS_RENEW_TRX_INC
SELECT DISTINCT NSOL.SALES_ORDER_LINE_KEY,POS_TV.BK_POS_TRANSACTION_ID_INT,ORIGINAL_SYSTEM_LINE_REF_ID,BKG_POS.RU_SERVICE_CONTRACT_END_DTM
FROM (SELECT SALES_ORDER_LINE_KEY,MIN(BK_POS_TRANSACTION_ID_INT)AS BK_POS_TRANSACTION_ID_INT FROM 
(SELECT * FROM $$SLSORDVWDB.N_POS_TRX_LN_AS_NEW_OR_RNWL_TV 
WHERE END_TV_DTM = '3500-01-01 00:00:00' 
QUALIFY ROW_NUMBER() OVER (PARTITION BY SALES_ORDER_LINE_KEY  ORDER BY SRC_CREATED_DTM ASC)=1)POS
GROUP BY SALES_ORDER_LINE_KEY) POS_TV
INNER JOIN  (SELECT BK_POS_TRANSACTION_ID_INT,RU_SERVICE_CONTRACT_END_DTM FROM
$$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE BKG GROUP BY 1,2
UNION
SELECT BK_POS_TRANSACTION_ID_INT,RU_SERVICE_CONTRACT_END_DTM FROM
$$SLSORDVWDB.N_POS_TRANSACTION_LINE POS GROUP BY 1,2) BKG_POS
ON  POS_TV.BK_POS_TRANSACTION_ID_INT=BKG_POS.BK_POS_TRANSACTION_ID_INT
INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL
ON NSOL.SALES_ORDER_LINE_KEY=POS_TV.SALES_ORDER_LINE_KEY
AND NSOL.BK_SALES_CHANNEL_CD='Two Tier Distributor'
AND NSOL.SS_CODE IN ('CG','OPL') ;

COLLECT STATISTICS COLUMN(BK_POS_TRANSACTION_ID_INT)ON $$STGDB.WI_SMR_POS_RENEW_TRX_INC; 

DELETE FROM $$STGDB.WI_SMR_OPL_SOL_KEY_TEMP ;
INSERT INTO $$STGDB.WI_SMR_OPL_SOL_KEY_TEMP  
SELECT SOL.SALES_ORDER_LINE_KEY FROM 
(SELECT  RTR.SALES_ORDER_LINE_KEY  FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.ORDER_ORIGIN_CD <>  'DISTI-DSV'
AND RTR.RENEWAL_REF_CD IN ('SO LINE ID','LINE REFERENCE NUMBER','OFFER ATTRIBUTION ID','Renew Covered Line ID')
GROUP BY 1 
UNION
SELECT NSOL.SALES_ORDER_LINE_KEY FROM 
(SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.RENEWAL_REF_CD ='SO LINE ID'
GROUP BY 1,2,3) RTR
INNER  JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL 
ON NSOL.SK_SO_LINE_ID_INT =CAST(RTR.RENEWAL_REF_ID AS BIGINT)
AND SS_CODE IN ('CG','OPL')
GROUP BY 1
UNION
SELECT NSOL.SALES_ORDER_LINE_KEY FROM 
(SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.RENEWAL_REF_CD ='LINE REFERENCE NUMBER'
GROUP BY 1,2,3)RTR
INNER  JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL 
ON NSOL.ORIGINAL_SYSTEM_LINE_REF_ID = RTR.RENEWAL_REF_ID 
AND SS_CODE IN ('CG','OPL') 
GROUP BY 1
UNION
SELECT OA_R.SALES_ORDER_LINE_KEY FROM 
(SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999 
AND RTR.RENEWAL_REF_CD ='OFFER ATTRIBUTION ID'
GROUP BY 1,2,3)RTR
INNER JOIN (SELECT SOL_R.SALES_ORDER_LINE_KEY ,SK_OFFER_ATTRIBUTION_ID_INT 
FROM  $$SLSORDVWDB.N_SOL_OFFER_ATTRIBUTION OA INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE SOL_R
ON SOL_R.SALES_ORDER_LINE_KEY=OA.TOP_SKU_SALES_ORDER_LINE_KEY
AND SS_CODE IN ('CG','OPL') )OA_R
ON   OA_R.SK_OFFER_ATTRIBUTION_ID_INT  =  CAST (RTR.RENEWAL_REF_ID  AS BIGINT) 
GROUP BY 1
UNION
SELECT SCL.SALES_ORDER_LINE_KEY FROM 
(SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999 
AND RTR.RENEWAL_REF_CD ='Renew Covered Line ID'
GROUP BY 1,2,3)RTR
INNER  JOIN  $$SERVICEVWDB.N_SVC_CNTRCT_LN_TECH_SERVICES SCL
ON  SCL.SK_ID_LINT  =CAST (RTR.RENEWAL_REF_ID  AS BIGINT)
GROUP BY 1)SOL
WHERE NOT EXISTS (SELECT 1 FROM $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC INC WHERE
INC.TRANS_TYPE_CODE='ERP' AND 
SOL.SALES_ORDER_LINE_KEY=INC.SALES_ORDER_LINE_KEY);

DELETE FROM $$STGDB.WI_SMR_OPL_ERP_RENEW_TEMP;
INSERT INTO $$STGDB.WI_SMR_OPL_ERP_RENEW_TEMP   
SELECT * 
FROM 
(SELECT SOL.SALES_ORDER_LINE_KEY,
CASE
WHEN SOL.PERIODIC_BILLING_START_DT NOT IN ('1900-01-01' , '3500-01-01') 
AND SOL.PERIODIC_BILLING_START_DT IS NOT NULL
AND SOL.PERIODIC_BILLING_START_DT >= '2000-01-01'
THEN SOL.PERIODIC_BILLING_START_DT
END 
AS PB_START_DT,
CASE
WHEN SOL.PERIODIC_BILLING_END_DT NOT IN ('1900-01-01' , '3500-01-01')
AND SOL.PERIODIC_BILLING_END_DT IS NOT NULL
AND SOL.PERIODIC_BILLING_END_DT > SOL.PERIODIC_BILLING_START_DT
THEN SOL.PERIODIC_BILLING_END_DT
END 
AS PB_END_DT,
CAST((PB_END_DT - PB_START_DT) AS DECIMAL(15,6)) * 12 /365
AS PB_CONTRACT_DURATION,
CASE
WHEN SOL.RU_SERVICE_CONTRACT_START_DTM NOT IN ('1900-01-01 00:00:00' , '3500-01-01 00:00:00') 
AND SOL.RU_SERVICE_CONTRACT_START_DTM IS NOT NULL
AND SOL.RU_SERVICE_CONTRACT_START_DTM >= '2000-01-01 00:00:00'
THEN CAST(SOL.RU_SERVICE_CONTRACT_START_DTM AS DATE)
END 
AS SOL_CONTRACT_START_DT,
CASE
WHEN SOL.RU_SERVICE_CONTRACT_END_DTM NOT IN ('1900-01-01 00:00:00' , '3500-01-01 00:00:00')
AND SOL.RU_SERVICE_CONTRACT_END_DTM IS NOT NULL
AND SOL.RU_SERVICE_CONTRACT_END_DTM > SOL.RU_SERVICE_CONTRACT_START_DTM
AND CAST(SOL.RU_SERVICE_CONTRACT_END_DTM AS DATE) <= ADD_MONTHS(CURRENT_DATE,240)
THEN CAST(SOL.RU_SERVICE_CONTRACT_END_DTM AS DATE)
END 
AS SOL_CONTRACT_END_DT,
CAST((SOL_CONTRACT_END_DT - SOL_CONTRACT_START_DT) AS DECIMAL(15,6)) * 12 /365
AS DV_SOL_CONTRACT_DURATION,
CASE WHEN SOLV1.RU_SRVC_CNTRCT_DRTN_MNTHS_CNT <> 0 AND SOLV1.RU_SRVC_CNTRCT_DRTN_MNTHS_CNT <= 240 THEN  SOLV1.RU_SRVC_CNTRCT_DRTN_MNTHS_CNT  END 
AS SOLV1_CONTRACT_DURATION,
CASE WHEN P.PRDT_SETUP_CLASSIFICATION_CD IN ('SOFTWARE') THEN 
(CASE          
WHEN P.PRICING_UNIT_NAME = 'YEAR'   THEN P.PRICING_UNIT_DURATION_INT * 12
WHEN P.PRICING_UNIT_NAME = 'MONTHS' THEN P.PRICING_UNIT_DURATION_INT
WHEN P.PRICING_UNIT_NAME = 'DAYS'   THEN (CAST(P.PRICING_UNIT_DURATION_INT AS DECIMAL(15,6)) * 12)/365
END)
ELSE NULL
END AS PID_TO_TERM_ATTR1,
CASE WHEN PID_TO_TERM_ATTR1 IS NULL AND P.BK_PRODUCT_ID = 'XCAT-ELA-5Y-ENG' THEN  60
ELSE PID_TO_TERM_ATTR1
END AS PID_TO_TERM_ATT,
CASE 
WHEN SOL.RU_SERVICE_CONTRACT_START_DTM NOT IN ('3500-01-01 00:00:00') 
AND SOL.RU_SERVICE_CONTRACT_START_DTM IS NOT NULL  
AND SOL.RU_SERVICE_CONTRACT_START_DTM >= '2000-01-01 00:00:00' 
THEN CAST(SOL.RU_SERVICE_CONTRACT_START_DTM AS DATE)
END
AS BKGS_CONTRACT_START_DT,
CASE 
WHEN SOL.RU_SERVICE_CONTRACT_END_DTM NOT IN ('1900-01-01 00:00:00' , '3500-01-01 00:00:00') 
AND SOL.RU_SERVICE_CONTRACT_END_DTM IS NOT NULL  
AND SOL.RU_SERVICE_CONTRACT_END_DTM > SOL.RU_SERVICE_CONTRACT_START_DTM 
AND CAST(SOL.RU_SERVICE_CONTRACT_END_DTM AS DATE) <= ADD_MONTHS(CURRENT_DATE,240)
THEN CAST(SOL.RU_SERVICE_CONTRACT_END_DTM AS DATE)
END
AS BKGS_CONTRACT_END_DT,
CASE WHEN BKGS_CONTRACT_START_DT IS NOT NULL AND BKGS_CONTRACT_END_DT IS NOT NULL THEN 
CAST((BKGS_CONTRACT_END_DT - BKGS_CONTRACT_START_DT) AS DECIMAL(15,6)) * 12/365
WHEN DV_SOL_CONTRACT_DURATION IS NOT NULL AND  DV_SOL_CONTRACT_DURATION > 0 AND DV_SOL_CONTRACT_DURATION <= 240   THEN DV_SOL_CONTRACT_DURATION
END 
AS DV_BKGS_CONTRACT_DURATION,
CASE 
WHEN SVC.SERVICE_CONTRACT_START_DTM NOT IN ( '3500-01-01 00:00:00')
AND SVC.SERVICE_CONTRACT_START_DTM IS NOT NULL 
AND SVC.SERVICE_CONTRACT_START_DTM >= '2000-01-01 00:00:00'
THEN CAST(SVC.SERVICE_CONTRACT_START_DTM AS DATE)
END
AS SVC_CONTRACT_START_DT,
CASE 
WHEN SVC.SERVICE_CONTRACT_END_DTM NOT IN ('1900-01-01 00:00:00' , '3500-01-01 00:00:00')
AND SVC.SERVICE_CONTRACT_END_DTM IS NOT NULL
AND SVC.SERVICE_CONTRACT_END_DTM > SVC.SERVICE_CONTRACT_START_DTM
AND CAST(SVC.SERVICE_CONTRACT_END_DTM AS DATE) <= ADD_MONTHS(CURRENT_DATE,240)
THEN CAST(SVC.SERVICE_CONTRACT_END_DTM AS DATE)
END
AS SVC_CONTRACT_END_DT,
CAST((SVC_CONTRACT_END_DT - SVC_CONTRACT_START_DT) AS DECIMAL(15,6)) * 12 /365
AS DV_SVC_CONTRACT_DURATION,
CASE
WHEN PB_CONTRACT_DURATION IS NOT NULL AND PB_CONTRACT_DURATION > 0 THEN (CASE WHEN CAST(SOL.EDW_CREATE_DATETIME AS DATE) < '2020-08-16' THEN PB_START_DT
WHEN CAST(SOL.EDW_CREATE_DATETIME AS DATE) >= '2020-08-16' AND DV_SOL_CONTRACT_DURATION > 0 THEN SOL_CONTRACT_START_DT END)
WHEN (DV_SVC_CONTRACT_DURATION IS NOT NULL AND DV_SVC_CONTRACT_DURATION > 0) THEN SVC_CONTRACT_START_DT
WHEN (DV_SOL_CONTRACT_DURATION IS NOT NULL AND DV_SOL_CONTRACT_DURATION > 0) THEN SOL_CONTRACT_START_DT
WHEN (SOLV1_CONTRACT_DURATION IS NOT NULL AND SOLV1_CONTRACT_DURATION > 0) THEN 
COALESCE(SOL_CONTRACT_START_DT,SO.RU_CISCO_BOOKED_DATETIME,PD.PROCESS_DATE)
WHEN (SOL.RU_SERVICE_CONTRACT_START_DTM IS NOT NULL AND SOL.RU_SERVICE_CONTRACT_END_DTM IS NOT NULL) THEN SOL.RU_SERVICE_CONTRACT_START_DTM
ELSE COALESCE(SO.RU_CISCO_BOOKED_DATETIME,PD.PROCESS_DATE)
END
AS NEW_SERVICE_CONTRACT_START_DTM,
CASE
WHEN PB_CONTRACT_DURATION IS NOT NULL AND PB_CONTRACT_DURATION > 0 THEN (CASE WHEN CAST(SOL.EDW_CREATE_DATETIME AS DATE) < '2020-08-16' THEN PB_CONTRACT_DURATION
WHEN CAST(SOL.EDW_CREATE_DATETIME AS DATE) >= '2020-08-16' AND DV_SOL_CONTRACT_DURATION > 0 THEN DV_SOL_CONTRACT_DURATION END)
WHEN (DV_SVC_CONTRACT_DURATION IS NOT NULL AND DV_SVC_CONTRACT_DURATION > 0) THEN DV_SVC_CONTRACT_DURATION
WHEN (DV_SOL_CONTRACT_DURATION IS NOT NULL AND DV_SOL_CONTRACT_DURATION > 0) THEN DV_SOL_CONTRACT_DURATION 
WHEN (SOLV1_CONTRACT_DURATION IS NOT NULL AND SOLV1_CONTRACT_DURATION > 0) THEN SOLV1_CONTRACT_DURATION 
WHEN (DV_BKGS_CONTRACT_DURATION IS NOT NULL AND DV_BKGS_CONTRACT_DURATION > 0) THEN DV_BKGS_CONTRACT_DURATION 
WHEN COALESCE(PID_TO_TERM_ATT,0) > 0 THEN PID_TO_TERM_ATT 
ELSE  12
END
AS LKP_CONTRACT_DURATION,
CASE WHEN LKP_CONTRACT_DURATION > 0 AND LKP_CONTRACT_DURATION <=1 THEN 1 
ELSE LKP_CONTRACT_DURATION 
END AS NEW_CONTRACT_DURATION,
CASE 
WHEN FLOOR(NEW_CONTRACT_DURATION) = CEIL(NEW_CONTRACT_DURATION)
THEN ADD_MONTHS(NEW_SERVICE_CONTRACT_START_DTM, CAST(NEW_CONTRACT_DURATION AS INTEGER)) - 1
ELSE NEW_SERVICE_CONTRACT_START_DTM + (ROUND((NEW_CONTRACT_DURATION / 12.000000) * 365))
END
AS NEW_SERVICE_CONTRACT_END_DTM
FROM (SELECT * FROM $$SLSORDVWDB.N_SALES_ORDER_LINE SOL
WHERE EXISTS (SELECT 1 FROM $$STGDB.WI_SMR_OPL_SOL_KEY_TEMP TEMP
WHERE SOL.SALES_ORDER_LINE_KEY=TEMP.SALES_ORDER_LINE_KEY))SOL 
INNER JOIN $$COMREFVWDB.N_PRODUCT P ON (P.ITEM_KEY = SOL.PRODUCT_KEY)
LEFT JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE_V1_TV SOLV1 
ON ( SOL.SALES_ORDER_LINE_KEY = SOLV1.SALES_ORDER_LINE_KEY AND SOLV1.SS_CODE IN ('CG','OPL') AND SOLV1.END_TV_DTM = '3500-01-01 00:00:00' )
LEFT JOIN (
SELECT
CNTRCT.SERVICE_SOL_KEY AS SALES_ORDER_LINE_KEY
,MIN(CAST (CNTRCT.CONTRACT_LINE_START_DT AS TIMESTAMP(0))) AS SERVICE_CONTRACT_START_DTM
,MAX(CAST(CNTRCT.CONTRACT_LINE_END_DT AS TIMESTAMP(0))) AS SERVICE_CONTRACT_END_DTM
FROM 
$$SERVICEVWDB.N_SRVC_CNTRCT_LN_HANA_SRCD  CNTRCT
WHERE CNTRCT.SERVICE_SOL_KEY > 0 
AND  
(  CNTRCT.CONTRACT_LINE_STYLE_ID_INT =  9 AND  SERVICE_SOL_LINKAGE_LOGIC_NAME LIKE '%OKC%' 
OR CNTRCT.CONTRACT_LINE_STYLE_ID_INT =  7 )
AND CNTRCT.CONTRACT_LINE_STATUS_NAME <> 'TERMINATED'
AND NOT EXISTS  (
SELECT 1 FROM  $$COMREFVWDB.MT_CS_DEAL_SVC_FIN_HIER_ALLOC SFH
WHERE  1=1
AND SFH.ITEM_KEY = CNTRCT.SERVICE_PRODUCT_KEY
AND SFH.BK_ALLOCATED_SERVC_GROUP_ID <> 'UNKNOWN'  AND SFH.DV_PRDT_SUB_GRP_ALLOC_SRC_CD = 'SPA'
AND SFH.BK_SERVICE_CATEGORY_ID = 'ADVANCED SERVICES' AND SFH.ALLOCATION_PERCENTAGE = 1
)
GROUP BY SERVICE_SOL_KEY ) SVC 
ON SVC.SALES_ORDER_LINE_KEY=SOL.SALES_ORDER_LINE_KEY
INNER JOIN $$SLSORDVWDB.N_SALES_ORDER SO
ON SOL.SALES_ORDER_KEY=SO.SALES_ORDER_KEY
CROSS JOIN $$ETLVWDB.BKG_PROCESS_DT_CNTRL PD
WHERE SOL.SS_CODE IN ('CG','OPL'))ERP;

INSERT INTO $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC
SELECT DISTINCT SALES_ORDER_LINE_KEY AS SALES_ORDER_LINE_KEY,
-999 AS SO_SBSCRPTN_ITM_SLS_TRX_KEY,
NEW_SERVICE_CONTRACT_START_DTM,
NEW_SERVICE_CONTRACT_END_DTM,
'ERP' AS TRANS_TYPE_CODE
FROM $$STGDB.WI_SMR_OPL_ERP_RENEW_TEMP;

DELETE FROM $$STGDB.WI_SMR_OPL_TRX_ID_TEMP ;
INSERT INTO $$STGDB.WI_SMR_OPL_TRX_ID_TEMP  
SELECT XAAS.SK_ERP_BKGS_TRX_ID FROM 
(
SELECT RTR.SK_ERP_BKGS_TRX_ID FROM 
(SELECT  RTR.SK_ERP_BKGS_TRX_ID  FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND (RTR.ITEM_CATEGORY_NAME IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
OR RTR.ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )
AND RTR.ORDER_ORIGIN_CD <>  'DISTI-DSV'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.RENEWAL_REF_CD IN ('LINE REFERENCE NUMBER','OFFER ATTRIBUTION ID'))RTR
INNER JOIN  $$STGDB.WI_SMR_XAAS_RENEW_TRX_INC O
ON  RTR.SK_ERP_BKGS_TRX_ID=O.SK_TRX_ID_INT
GROUP BY 1 
UNION
SELECT R.SK_TRX_ID_INT FROM 
(SELECT RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND (RTR.ITEM_CATEGORY_NAME IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
OR RTR.ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.RENEWAL_REF_CD ='LINE REFERENCE NUMBER'
GROUP BY 1)RTR
INNER JOIN (SELECT  ORIGINAL_SYSTEM_LINE_REF_ID,SK_TRX_ID_INT FROM $$STGDB.WI_SMR_XAAS_RENEW_TRX_INC 
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORIGINAL_SYSTEM_LINE_REF_ID ORDER BY BOOKED_DT DESC)=1)R
ON R.ORIGINAL_SYSTEM_LINE_REF_ID=RTR.RENEWAL_REF_ID
GROUP BY 1
UNION
SELECT R.SK_TRX_ID_INT FROM 
(SELECT RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND (RTR.ITEM_CATEGORY_NAME IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
OR RTR.ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999 
AND RTR.RENEWAL_REF_CD ='OFFER ATTRIBUTION ID'
GROUP BY 1)RTR
INNER JOIN (SELECT  TRX.SK_TRX_ID_INT,SK_ATTRIBUTION_ID_INT from
$$STGDB.WI_SMR_XAAS_RENEW_TRX_INC TRX 
INNER JOIN 
$$NRTNCRVWDB.N_XAAS_SO_SBSCRPTN_ATTRBTN_NRT XOA
ON TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY = XOA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY
AND BK_OFFER_ATTRIBUTION_ID_INT > 0
GROUP BY 1,2)R
ON R.SK_ATTRIBUTION_ID_INT =CAST(RTR.RENEWAL_REF_ID  AS BIGINT) 
GROUP BY 1)XAAS
WHERE NOT EXISTS (SELECT 1 FROM $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC INC INNER JOIN 
$$NRTNCRVWDB.N_XAAS_SO_SBCR_ITM_STRX_NRT_TV TRX 
ON INC.SO_SBSCRPTN_ITM_SLS_TRX_KEY=TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY 
AND TRX.END_TV_DTM= '3500-01-01 00:00:00'
WHERE INC.TRANS_TYPE_CODE='XAAS' AND 
XAAS.SK_ERP_BKGS_TRX_ID=TRX.SK_TRX_ID_INT);

INSERT INTO $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC
SELECT MINOR_LN_EXAAS_SUBSCR_SOL_KEY AS SALES_ORDER_LINE_KEY,
SO_SBSCRPTN_ITM_SLS_TRX_KEY AS SO_SBSCRPTN_ITM_SLS_TRX_KEY,
NEW_SERVICE_CONTRACT_START_DTM,
NEW_SERVICE_CONTRACT_END_DTM,
'XAAS' AS TRANS_TYPE_CODE
FROM 
(SELECT TSL.SO_SBSCRPTN_ITM_SLS_TRX_KEY,
TSL.MINOR_LN_EXAAS_SUBSCR_SOL_KEY
,TSL.RU_SERVICE_CONTRACT_START_DTM 
,TSL.RU_SERVICE_CONTRACT_END_DTM   
,TSL.DV_CONTRACT_DURATION    
,'N' AS XCAT_FLAG
,'N' AS ACV_POLICY_FLG,
-- SUB look up
CASE WHEN (SUB.TERM_START_DT >='2000-01-01' AND SUB.TERM_START_DT <> '3500-01-01') THEN SUB.TERM_START_DT END
AS SUB_TERM_START_DT,
CASE WHEN (SUB.TERM_END_DT <> '1900-01-01' AND SUB.TERM_END_DT <> '3500-01-01' AND SUB.TERM_END_DT <= Add_Months(Current_Date,240) ) THEN SUB.TERM_END_DT END
AS SUB_TERM_END_DT,
CASE WHEN (SUB.SUBSCRIPTION_END_DT <> '1900-01-01' AND SUB.SUBSCRIPTION_END_DT <> '3500-01-01' AND SUB.SUBSCRIPTION_END_DT <= Add_Months(Current_Date,240) ) THEN SUB.SUBSCRIPTION_END_DT END 
AS SUB_END_DT,
SUB.INITIAL_TERM_MONTHS_CNT AS SUB_INITIAL_TERM,
SUB.RENEWAL_TERM_MONTHS_CNT AS SUB_RENEWAL_TERM,
SUB.SUBSCRIPTION_RENEW_CNT AS SUB_RENEWAL_CNT,
CASE WHEN SUB_RENEWAL_CNT > 0 THEN SUB_RENEWAL_TERM ELSE SUB_INITIAL_TERM END AS SUB_CURRENT_TERM,
-- TSL look up
TSL.BK_SALES_ORDER_TYPE_CD AS TSL_ORDER_TYPE,
TSL.BK_SALES_ORDER_SELL_TYPE_CD AS TSL_SELL_TYPE,
TSL.ACTION_CD AS TSL_ACTION_CODE,
CASE WHEN TSL.INITIAL_TERM_DUR_MTHS_CNT <> -999 AND TSL.INITIAL_TERM_DUR_MTHS_CNT <> 0  AND  TSL.INITIAL_TERM_DUR_MTHS_CNT <= 240 THEN TSL.INITIAL_TERM_DUR_MTHS_CNT END
AS TSL_INITIAL_TERM,
CASE WHEN TSL.RENEWAL_TERM_MTHS_CNT <> -999 AND TSL.RENEWAL_TERM_MTHS_CNT <=240 THEN TSL.RENEWAL_TERM_MTHS_CNT ELSE 0 END 
AS TSL_RENEWAL_TERM,
TSL.RENEWAL_CNT AS TSL_RENEWAL_CNT,
CASE WHEN TSL_RENEWAL_CNT > 0  THEN Coalesce(SUB_RENEWAL_TERM, TSL_RENEWAL_TERM) ELSE Coalesce(SUB_INITIAL_TERM, TSL_INITIAL_TERM) END
AS TSL_CURRENT_TERM,
Round((Cast(Coalesce(TSL_INITIAL_TERM,0) AS DECIMAL(15,6)) / 12) * 365)
AS TSL_INITIAL_DAYS,
Round((Cast(Coalesce(TSL_RENEWAL_TERM,0) AS DECIMAL(15,6)) / 12) * 365)
AS TSL_RENEWAL_DAYS,
Round((Cast(Coalesce(TSL_CURRENT_TERM, 0) AS DECIMAL(15,6)) / 12) * 365)
AS TSL_CURRENT_TERM_DAYS,
TSL_INITIAL_DAYS + (Coalesce(TSL_RENEWAL_CNT, 0) * TSL_RENEWAL_DAYS)
AS TSL_TOTAL_DAYS,
CASE WHEN TSL.BOOKING_TERM_MONTHS_CNT <> 0 AND NOT(TSL_ORDER_TYPE IN ('REPLACE') AND TSL_ACTION_CODE IN ('REMOVE', 'CANCEL') )
THEN TSL.BOOKING_TERM_MONTHS_CNT END 
AS TSL_BOOKING_TERM,
Round((Cast(Coalesce(TSL_BOOKING_TERM,0) AS DECIMAL(15,6)) / 12) * 365)
AS TSL_BOOKING_DAYS,
CASE 
WHEN TSL_ORDER_TYPE IN ('REPLACE') AND TSL_ACTION_CODE NOT IN ('REMOVE', 'CANCEL') THEN 0
ELSE Coalesce(TSL.FULFILLMENT_TERM_DAYS_CNT, 0) END AS TSL_FULFILLMENT_DAYS,
CASE 
WHEN TSL_FULFILLMENT_DAYS < TSL_CURRENT_TERM_DAYS THEN (TSL_CURRENT_TERM_DAYS - TSL_FULFILLMENT_DAYS)
WHEN TSL_FULFILLMENT_DAYS >= TSL_CURRENT_TERM_DAYS AND TSL_FULFILLMENT_DAYS < TSL_TOTAL_DAYS THEN (TSL_TOTAL_DAYS - TSL_FULFILLMENT_DAYS)
WHEN TSL_FULFILLMENT_DAYS >= TSL_CURRENT_TERM_DAYS AND TSL_FULFILLMENT_DAYS >= TSL_TOTAL_DAYS THEN 0 END AS TSL_REMAINING_DAYS,
COALESCE(CASE WHEN TSL_REMAINING_DAYS > 0 
THEN Cast(TSL_REMAINING_DAYS AS DECIMAL(15,6)) * 12 / 365 END ,0) AS TSL_REMAINING_TERM,
COALESCE(CASE WHEN TSL_CURRENT_TERM_DAYS >= TSL_REMAINING_DAYS
THEN (TSL_CURRENT_TERM_DAYS - TSL_REMAINING_DAYS) END ,0) AS DV_FULFILLMENT_DAYS,
-- TSL Contract Duratiom
CASE 
WHEN TSL_BOOKING_TERM > 0 AND TSL_BOOKING_TERM >= TSL_REMAINING_TERM THEN TSL_BOOKING_TERM
WHEN TSL_BOOKING_TERM > 0 AND TSL_BOOKING_TERM < TSL_REMAINING_TERM  AND TSL_FULFILLMENT_DAYS = 0 THEN TSL_BOOKING_TERM
WHEN TSL_REMAINING_TERM >= 0 AND TSL_FULFILLMENT_DAYS > 0 THEN TSL_REMAINING_TERM
ELSE TSL_CURRENT_TERM
END
AS TSL_CONTRACT_DURATION,
-- Look up duration
CASE
WHEN TSL_CONTRACT_DURATION >= 0 THEN TSL_CONTRACT_DURATION
ELSE TSL.DV_CONTRACT_DURATION    
END
AS LKP_CONTRACT_DURATION,
-- Subscription Effective Date
CASE 
WHEN TSL_BOOKING_TERM > 0 AND TSL_BOOKING_TERM >= TSL_REMAINING_TERM 
THEN (SUB_TERM_START_DT + DV_FULFILLMENT_DAYS)
WHEN TSL_BOOKING_TERM > 0 AND TSL_BOOKING_TERM < TSL_REMAINING_TERM AND TSL_FULFILLMENT_DAYS = 0 
THEN (SUB_TERM_END_DT - TSL_BOOKING_DAYS)
WHEN TSL_REMAINING_TERM > 0 AND TSL_FULFILLMENT_DAYS > 0 
THEN  (SUB_TERM_START_DT + DV_FULFILLMENT_DAYS)
WHEN TSL_REMAINING_TERM = 0 AND SUB_END_DT >= SUB_TERM_END_DT THEN SUB_END_DT 
ELSE  SUB_TERM_START_DT
END AS SUB_EFFECTIVE_DATE,
CASE WHEN (NSOL1.CUST_EXPECTED_START_DT >= '2000-01-01' 
AND NSOL1.CUST_EXPECTED_START_DT <> '3500-01-01') THEN NSOL1.CUST_EXPECTED_START_DT END
AS SOL_REQUESTED_START_DT
,BOOKED_DT AS DV_BOOKED_DT   
,Cast(DV_CONTRACT_DURATION AS DECIMAL(18,0)) AS CONTRACT_DURATION,
-- Enriched Duration
CASE 
WHEN ACV_POLICY_FLG = 'Y' THEN 12 
ELSE  LKP_CONTRACT_DURATION
END
AS NEW_CONTRACT_DURATION,
-- Enriched Start Date
CASE 
WHEN TSL_CONTRACT_DURATION >= 0 THEN COALESCE( SUB_EFFECTIVE_DATE, (COALESCE(SOL_CONTRACT_START_DT,SOL_REQUESTED_START_DT)+DV_FULFILLMENT_DAYS),  DV_BOOKED_DT) 
WHEN  DV_SVC_CONTRACT_DURATION > 0 THEN SVC_CONTRACT_START_DT
WHEN  DV_SOL_CONTRACT_DURATION > 0 THEN SOL_CONTRACT_START_DT
WHEN  SOLV1_CONTRACT_DURATION > 0 THEN COALESCE( SOL_CONTRACT_START_DT, SOL_REQUESTED_START_DT, DV_BOOKED_DT)
ELSE  DV_BOOKED_DT
END
AS NEW_SERVICE_CONTRACT_START_DTM, -- BSFT Change
-- Enriched End Date
CASE 
WHEN  ACV_POLICY_FLG = 'Y' AND NEW_CONTRACT_DURATION = 12 THEN ADD_MONTHS( NEW_SERVICE_CONTRACT_START_DTM, 12) - 1
WHEN TSL_BOOKING_TERM > 0 AND TSL_BOOKING_TERM >= TSL_REMAINING_TERM AND SUB_TERM_START_DT IS NOT NULL THEN (SUB_TERM_START_DT + DV_FULFILLMENT_DAYS + TSL_BOOKING_DAYS)
WHEN TSL_BOOKING_TERM > 0 AND TSL_BOOKING_TERM < TSL_REMAINING_TERM AND TSL_FULFILLMENT_DAYS = 0 AND SUB_TERM_END_DT IS NOT NULL THEN SUB_TERM_END_DT
WHEN TSL_REMAINING_TERM > 0 AND TSL_FULFILLMENT_DAYS > 0 AND SUB_TERM_END_DT IS NOT NULL THEN SUB_TERM_END_DT
WHEN TSL_REMAINING_TERM = 0 AND SUB_END_DT >= SUB_TERM_END_DT THEN SUB_END_DT 
WHEN TSL_REMAINING_TERM IS NULL AND DV_SVC_CONTRACT_DURATION > 0 THEN  SVC_CONTRACT_END_DT
WHEN TSL_REMAINING_TERM IS NULL AND DV_SOL_CONTRACT_DURATION > 0 THEN  SOL_CONTRACT_END_DT
ELSE
(
CASE
WHEN FLOOR( NEW_CONTRACT_DURATION) = CEIL( NEW_CONTRACT_DURATION) AND NEW_CONTRACT_DURATION <> 0
THEN ADD_MONTHS( NEW_SERVICE_CONTRACT_START_DTM, CAST( NEW_CONTRACT_DURATION AS INTEGER)) - 1
ELSE NEW_SERVICE_CONTRACT_START_DTM + ROUND((CAST( NEW_CONTRACT_DURATION AS DECIMAL(15,6)) / 12) * 365)
END
)
END
AS NEW_SERVICE_CONTRACT_END_DTM
FROM
(SELECT 
ROUND(CASE 
WHEN NXSSIS.ACQUISITION_ORDER_ORIGIN_CD IN 'ACQ-BSFT' AND NXSSIS.BOOKING_TERM_MONTHS_CNT>0 THEN NXSSIS.BOOKING_TERM_MONTHS_CNT
WHEN NXSSIS.ACQUISITION_ORDER_ORIGIN_CD IN 'ACQ-BSFT' AND NXSSIS.BOOKING_TERM_MONTHS_CNT <=0 AND NXSSIS.DV_SERVICE_CONTRACT_START_DT IS NOT NULL AND NXSSIS.DV_SERVICE_CONTRACT_END_DT IS NOT NULL THEN CAST(((NXSSIS.DV_SERVICE_CONTRACT_END_DT-NXSSIS.DV_SERVICE_CONTRACT_START_DT+1)/365)*12 as decimal(15,6))
WHEN NXSSIS.BK_SALES_ORDER_TYPE_CD = 'AUTO-RENEWAL' THEN NXSSIS.RENEWAL_TERM_MTHS_CNT 
WHEN NXSSIS.INITIAL_TERM_DUR_MTHS_CNT > 0 THEN  NXSSIS.INITIAL_TERM_DUR_MTHS_CNT
WHEN ( NP.BK_PRODUCT_ID LIKE 'SWOA%' OR  NP.BK_PRODUCT_ID LIKE '%ADJ%' ) AND NP.BK_PRODUCT_ID NOT LIKE 'SWOA-MX%' THEN NULL
ELSE 
CASE 
WHEN NP.PRICING_UNIT_NAME = 'YEAR' THEN NP.PRICING_UNIT_DURATION_INT * 12 
WHEN NP.PRICING_UNIT_NAME = 'MONTHS' THEN NP.PRICING_UNIT_DURATION_INT 
WHEN NP.PRICING_UNIT_NAME = 'DAYS' THEN  CAST(((NP.PRICING_UNIT_DURATION_INT*12(FLOAT))/365) AS DECIMAL(15,6) )
WHEN EL.BIZ_DEF_TERM IS NOT NULL THEN EL.BIZ_DEF_TERM
WHEN EL.DURATION IS NOT NULL THEN EL.DURATION
ELSE NULL
END
END) DV_CONTRACT_DURATION,NXSSIS.* FROM 
(SELECT * FROM $$NRTNCRVWDB.N_XAAS_SO_SBCR_ITM_STRX_NRT_TV TV
WHERE  TV.END_TV_DTM= '3500-01-01 00:00:00'
AND EXISTS (SELECT 1 FROM $$STGDB.WI_SMR_OPL_TRX_ID_TEMP TEMP 
WHERE TV.SK_TRX_ID_INT=TEMP.SK_ERP_BKGS_TRX_ID))NXSSIS
INNER JOIN $$COMREFVWDB.N_PRODUCT NP 
ON (NP.ITEM_KEY = NXSSIS.SUBSCRIPTION_PRODUCT_KEY) 
LEFT OUTER JOIN 
(SELECT SKU,INVENTORY_ITEM_ID,DURATION,BIZ_DEF_TERM FROM $$ETLVWDB.EL_CG1_XXCFIR_PROD_SUBSCR_SKU WHERE END_DATE IS NULL)EL 
ON NP.BK_PRODUCT_ID=EL.SKU
LEFT JOIN $$COMREFVWDB.N_PRODUCT_FAMILY NPF 
ON NP.RU_BK_PRODUCT_FAMILY_ID=NPF.BK_PRODUCT_FAMILY_ID )TSL
LEFT JOIN $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT NSOL
ON NSOL.SALES_ORDER_LINE_KEY=TSL.MINOR_LN_EXAAS_SUBSCR_SOL_KEY 
LEFT JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL1
ON NSOL1.SK_OPL_LINE_ID_INT=NSOL.SK_OPL_LINE_ID_INT
LEFT JOIN (
SELECT * FROM $$EXAASVWDB.N_EXAAS_SUBSCRIPTION_TV
WHERE SUBSCRIPTION_REF_ID <> 'UNKNOWN'
QUALIFY Row_Number() Over (PARTITION BY
SUBSCRIPTION_REF_ID,
BK_EXAAS_SUBSCRIPTION_NUM,
SUBSCRIPTION_RENEW_CNT
ORDER BY SUBSCRIPTION_END_DT DESC) = 1
) SUB
ON (SUB.SUBSCRIPTION_REF_ID = TSL.SUBSCRIPTION_REFERENCE_ID
AND SUB.BK_EXAAS_SUBSCRIPTION_NUM = TSL.SRC_RPTD_SBSCRPTN_CD 
AND SUB.SUBSCRIPTION_RENEW_CNT = TSL.RENEWAL_CNT)
LEFT JOIN $$STGDB.WI_SMR_OPL_ERP_RENEW_TEMP SOL
ON TSL.MINOR_LN_EXAAS_SUBSCR_SOL_KEY=SOL.SALES_ORDER_LINE_KEY )XAAS;

CREATE MULTISET VOLATILE TABLE NSOL_LINE_REF
AS
(SELECT SK_SO_LINE_ID_INT,SALES_ORDER_LINE_KEY,ORIGINAL_SYSTEM_LINE_REF_ID,RU_SERVICE_CONTRACT_START_DTM,RU_SERVICE_CONTRACT_END_DTM,BK_SALES_CHANNEL_CD
FROM $$SLSORDVWDB.N_SALES_ORDER_LINE SOL
WHERE SS_CODE ='CG'
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORIGINAL_SYSTEM_LINE_REF_ID ORDER BY BK_SO_SRC_UPD_DATETIME DESC)=1)
WITH DATA AND STATS ON COMMIT PRESERVE ROWS;

UPDATE NATTR FROM 
$$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NATTR,
(SELECT  DISTINCT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
(CASE WHEN (TRUNC(SOL.RU_SERVICE_CONTRACT_START_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(NSOL.RU_SERVICE_CONTRACT_END_DTM) IN ('3500-01-01','1900-01-01')) THEN -9999 
ELSE 
COALESCE( CAST(COALESCE(SOL.RU_SERVICE_CONTRACT_START_DTM,ENRICH_O.NEW_SERVICE_CONTRACT_START_DTM) AS DATE)-CAST(COALESCE(NSOL.RU_SERVICE_CONTRACT_END_DTM,ENRICH_R.NEW_SERVICE_CONTRACT_END_DTM) AS DATE) ,-9999) END ) AS RENEWAL_GAP_DAYS
FROM (SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.ITEM_CATEGORY_NAME NOT IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
AND RTR.ORDER_ORIGIN_CD <>  'DISTI-DSV'
AND RTR.ORDER_ORIGIN_CD NOT IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN )
AND RTR.RENEWAL_REF_CD='SO LINE ID'
GROUP BY 1,2,3)RTR
INNER JOIN  $$SLSORDVWDB.N_SALES_ORDER_LINE SOL
ON SOL.SALES_ORDER_LINE_KEY=RTR.SALES_ORDER_LINE_KEY
AND SOL.SS_CODE='CG'
INNER  JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL 
ON NSOL.SK_SO_LINE_ID_INT =CAST(RTR.RENEWAL_REF_ID AS BIGINT)
AND NSOL.SS_CODE='CG'
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_O
ON ENRICH_O.SALES_ORDER_LINE_KEY =SOL.SALES_ORDER_LINE_KEY
AND ENRICH_O.TRANS_TYPE_CODE='ERP'
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_R 
ON ENRICH_R.SALES_ORDER_LINE_KEY =NSOL.SALES_ORDER_LINE_KEY
AND ENRICH_R.TRANS_TYPE_CODE='ERP')ERP
SET DV_RENEWAL_GAP_DAYS_CNT=ERP.RENEWAL_GAP_DAYS
WHERE NATTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY=ERP.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NATTR.END_TV_DTM= '3500-01-01 00:00:00'
AND NATTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND NATTR.ITEM_CATEGORY_NAME NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
AND NATTR.ORDER_ORIGIN_CD <>  'DISTI-DSV'
AND NATTR.ORDER_ORIGIN_CD NOT IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN )
AND NATTR.RENEWAL_REF_CD ='SO LINE ID'
AND NATTR.RENEWAL_REF_ID<>'UNKNOWN'
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT<>ERP.RENEWAL_GAP_DAYS;

UPDATE NATTR FROM 
$$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NATTR,
(SELECT  DISTINCT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
(CASE WHEN (TRUNC(SOL.RU_SERVICE_CONTRACT_START_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(NSOL.RU_SERVICE_CONTRACT_END_DTM) IN ('3500-01-01','1900-01-01')) THEN -9999 
ELSE 
COALESCE( CAST(COALESCE(SOL.RU_SERVICE_CONTRACT_START_DTM,ENRICH_O.NEW_SERVICE_CONTRACT_START_DTM) AS DATE)-CAST(COALESCE(NSOL.RU_SERVICE_CONTRACT_END_DTM,ENRICH_R.NEW_SERVICE_CONTRACT_END_DTM) AS DATE) ,-9999) END ) AS RENEWAL_GAP_DAYS
FROM (SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.ITEM_CATEGORY_NAME NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
AND RTR.ORDER_ORIGIN_CD <>  'DISTI-DSV'
AND RTR.ORDER_ORIGIN_CD NOT IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN )
AND RTR.RENEWAL_REF_CD ='LINE REFERENCE NUMBER'
GROUP BY 1,2,3) RTR
INNER JOIN  $$SLSORDVWDB.N_SALES_ORDER_LINE SOL
ON SOL.SALES_ORDER_LINE_KEY=RTR.SALES_ORDER_LINE_KEY
AND SOL.SS_CODE='CG'
INNER  JOIN NSOL_LINE_REF NSOL 
ON NSOL.ORIGINAL_SYSTEM_LINE_REF_ID = RTR.RENEWAL_REF_ID 
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_O
ON ENRICH_O.SALES_ORDER_LINE_KEY =SOL.SALES_ORDER_LINE_KEY
AND ENRICH_O.TRANS_TYPE_CODE='ERP'
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_R 
ON ENRICH_R.SALES_ORDER_LINE_KEY =NSOL.SALES_ORDER_LINE_KEY
AND ENRICH_R.TRANS_TYPE_CODE='ERP'
)ERP
SET DV_RENEWAL_GAP_DAYS_CNT=ERP.RENEWAL_GAP_DAYS
WHERE NATTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY=ERP.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NATTR.END_TV_DTM= '3500-01-01 00:00:00'
AND NATTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND NATTR.ITEM_CATEGORY_NAME NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
AND NATTR.ORDER_ORIGIN_CD <>  'DISTI-DSV'
AND NATTR.ORDER_ORIGIN_CD NOT IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN )
AND NATTR.RENEWAL_REF_CD ='LINE REFERENCE NUMBER'
AND NATTR.RENEWAL_REF_ID<>'UNKNOWN'
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT<>ERP.RENEWAL_GAP_DAYS;

UPDATE NATTR FROM 
$$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NATTR,
(SELECT  DISTINCT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
(CASE WHEN (TRUNC(SOL.RU_SERVICE_CONTRACT_START_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(OA_R.RU_SERVICE_CONTRACT_END_DTM) IN ('3500-01-01','1900-01-01')) THEN -9999 
ELSE
COALESCE(( CAST(COALESCE(SOL.RU_SERVICE_CONTRACT_START_DTM,ENRICH_O.NEW_SERVICE_CONTRACT_START_DTM) AS DATE)-CAST(COALESCE(OA_R.RU_SERVICE_CONTRACT_END_DTM,ENRICH_R.NEW_SERVICE_CONTRACT_END_DTM) AS DATE)) ,-9999) END) RENEWAL_GAP_DAYS
FROM (SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.ITEM_CATEGORY_NAME NOT IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
AND RTR.ORDER_ORIGIN_CD <>  'DISTI-DSV'
AND RTR.ORDER_ORIGIN_CD NOT IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN )
AND RTR.RENEWAL_REF_CD='OFFER ATTRIBUTION ID'
GROUP BY 1,2,3) RTR
INNER JOIN  $$SLSORDVWDB.N_SALES_ORDER_LINE SOL
ON SOL.SALES_ORDER_LINE_KEY=RTR.SALES_ORDER_LINE_KEY
AND SOL.SS_CODE='CG'
INNER JOIN (SELECT SOL_R.SALES_ORDER_LINE_KEY,SK_SO_LINE_ID_INT,SK_OFFER_ATTRIBUTION_ID_INT,RU_SERVICE_CONTRACT_START_DTM,RU_SERVICE_CONTRACT_END_DTM,SS_CODE  FROM  $$SLSORDVWDB.N_SOL_OFFER_ATTRIBUTION OA INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE SOL_R
ON SOL_R.SALES_ORDER_LINE_KEY=OA.TOP_SKU_SALES_ORDER_LINE_KEY
AND SS_CODE='CG' )OA_R
ON   OA_R.SK_OFFER_ATTRIBUTION_ID_INT  =  CAST (RTR.RENEWAL_REF_ID  AS BIGINT) 
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_O
ON ENRICH_O.SALES_ORDER_LINE_KEY =SOL.SALES_ORDER_LINE_KEY
AND ENRICH_O.TRANS_TYPE_CODE='ERP'
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_R 
ON ENRICH_R.SALES_ORDER_LINE_KEY =OA_R.SALES_ORDER_LINE_KEY
AND ENRICH_R.TRANS_TYPE_CODE='ERP')ERP
SET DV_RENEWAL_GAP_DAYS_CNT=ERP.RENEWAL_GAP_DAYS
WHERE NATTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY=ERP.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NATTR.END_TV_DTM= '3500-01-01 00:00:00'
AND NATTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND NATTR.RENEWAL_REF_ID<>'UNKNOWN'
AND NATTR.ITEM_CATEGORY_NAME NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
AND NATTR.ORDER_ORIGIN_CD <>  'DISTI-DSV'
AND NATTR.ORDER_ORIGIN_CD NOT IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN )
AND NATTR.RENEWAL_REF_CD ='OFFER ATTRIBUTION ID'
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT<>ERP.RENEWAL_GAP_DAYS;

UPDATE NATTR FROM 
$$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NATTR,
(SELECT  DISTINCT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
(CASE WHEN (TRUNC(SOL.RU_SERVICE_CONTRACT_START_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(SCL.SVC_CNTRCT_LINE_END_DTM) IN ('3500-01-01','1900-01-01')) THEN -9999 
ELSE
COALESCE(( CAST(COALESCE(SOL.RU_SERVICE_CONTRACT_START_DTM,ENRICH_O.NEW_SERVICE_CONTRACT_START_DTM) AS DATE)-CAST(COALESCE(SCL.SVC_CNTRCT_LINE_END_DTM,ENRICH_R.NEW_SERVICE_CONTRACT_END_DTM) AS DATE)) ,-9999) END) RENEWAL_GAP_DAYS
FROM (SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.ITEM_CATEGORY_NAME NOT IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
AND RTR.ORDER_ORIGIN_CD NOT IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN )
AND RTR.RENEWAL_REF_CD='Renew Covered Line ID'
GROUP BY 1,2,3) RTR
INNER JOIN  $$SLSORDVWDB.N_SALES_ORDER_LINE SOL
ON SOL.SALES_ORDER_LINE_KEY=RTR.SALES_ORDER_LINE_KEY
AND SS_CODE='CG'
INNER  JOIN  $$SERVICEVWDB.N_SVC_CNTRCT_LN_TECH_SERVICES SCL
ON  SCL.SK_ID_LINT  =CAST (RTR.RENEWAL_REF_ID  AS BIGINT)  
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_O
ON ENRICH_O.SALES_ORDER_LINE_KEY =SOL.SALES_ORDER_LINE_KEY
AND ENRICH_O.TRANS_TYPE_CODE='ERP'
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_R 
ON ENRICH_R.SALES_ORDER_LINE_KEY =SCL.SALES_ORDER_LINE_KEY
AND ENRICH_R.TRANS_TYPE_CODE='ERP')ERP
SET DV_RENEWAL_GAP_DAYS_CNT=ERP.RENEWAL_GAP_DAYS
WHERE NATTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY=ERP.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NATTR.END_TV_DTM= '3500-01-01 00:00:00'
AND NATTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND NATTR.RENEWAL_REF_ID<>'UNKNOWN'
AND NATTR.ITEM_CATEGORY_NAME NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' )
AND NATTR.ORDER_ORIGIN_CD NOT IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN )
AND NATTR.RENEWAL_REF_CD ='Renew Covered Line ID'
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT<>ERP.RENEWAL_GAP_DAYS;

UPDATE NATTR FROM 
$$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NATTR,
(SELECT  DISTINCT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
(CASE WHEN (TRUNC(O.TERM_START_DT) IN ('3500-01-01','1900-01-01') OR TRUNC(SCL.SVC_CNTRCT_LINE_END_DTM) IN ('3500-01-01','1900-01-01')) THEN -9999 
ELSE
COALESCE(( CAST(COALESCE(O.TERM_START_DT,ENRICH_O.NEW_SERVICE_CONTRACT_START_DTM) AS DATE)-CAST(COALESCE(SCL.SVC_CNTRCT_LINE_END_DTM,ENRICH_R.NEW_SERVICE_CONTRACT_END_DTM) AS DATE)) ,-9999) END) AS RENEWAL_GAP_DAYS
FROM (SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.SK_ERP_BKGS_TRX_ID,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND ( RTR.ITEM_CATEGORY_NAME IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
OR RTR.ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )
AND RTR.RENEWAL_REF_CD='Renew Covered Line ID'
GROUP BY 1,2,3,4) RTR
INNER JOIN  $$STGDB.WI_SMR_XAAS_RENEW_TRX_INC O
ON  RTR.SK_ERP_BKGS_TRX_ID=O.SK_TRX_ID_INT
INNER  JOIN  $$SERVICEVWDB.N_SVC_CNTRCT_LN_TECH_SERVICES SCL
ON  SCL.SK_ID_LINT  =CAST (RTR.RENEWAL_REF_ID  AS BIGINT)  
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_O
ON ENRICH_O.SO_SBSCRPTN_ITM_SLS_TRX_KEY=O.SO_SBSCRPTN_ITM_SLS_TRX_KEY
AND ENRICH_O.TRANS_TYPE_CODE='XAAS'
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_R
ON ENRICH_R.SALES_ORDER_LINE_KEY=SCL.SALES_ORDER_LINE_KEY
AND ENRICH_R.TRANS_TYPE_CODE='XAAS')XAAS
SET DV_RENEWAL_GAP_DAYS_CNT=XAAS.RENEWAL_GAP_DAYS
WHERE NATTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY=XAAS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NATTR.END_TV_DTM= '3500-01-01 00:00:00'
AND NATTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND NATTR.RENEWAL_REF_ID<>'UNKNOWN'
AND ( NATTR.ITEM_CATEGORY_NAME IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' )
OR NATTR.ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )  
AND NATTR.RENEWAL_REF_CD ='Renew Covered Line ID'
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT<>XAAS.RENEWAL_GAP_DAYS;


UPDATE NATTR FROM 
$$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NATTR,
(SELECT  DISTINCT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
(CASE WHEN (TRUNC(O.TERM_START_DT) IN ('3500-01-01','1900-01-01') OR TRUNC(R.TERM_END_DT) IN ('3500-01-01','1900-01-01')) THEN -9999 
ELSE
COALESCE(( CAST(COALESCE(O.TERM_START_DT,ENRICH_O.NEW_SERVICE_CONTRACT_START_DTM) AS DATE)-CAST(COALESCE(R.TERM_END_DT,ENRICH_R.NEW_SERVICE_CONTRACT_END_DTM) AS DATE)) ,-9999) END)AS RENEWAL_GAP_DAYS
FROM (SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.SK_ERP_BKGS_TRX_ID,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND (RTR.ITEM_CATEGORY_NAME IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
OR RTR.ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )
AND RTR.ORDER_ORIGIN_CD <>  'DISTI-DSV'
AND RTR.RENEWAL_REF_CD='LINE REFERENCE NUMBER'
GROUP BY 1,2,3,4) RTR
INNER JOIN  $$STGDB.WI_SMR_XAAS_RENEW_TRX_INC O
ON  RTR.SK_ERP_BKGS_TRX_ID=O.SK_TRX_ID_INT
INNER JOIN (SELECT SO_SBSCRPTN_ITM_SLS_TRX_KEY,ORIGINAL_SYSTEM_LINE_REF_ID,TERM_END_DT FROM $$STGDB.WI_SMR_XAAS_RENEW_TRX_INC 
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORIGINAL_SYSTEM_LINE_REF_ID ORDER BY BOOKED_DT DESC)=1)R
ON R.ORIGINAL_SYSTEM_LINE_REF_ID=RTR.RENEWAL_REF_ID
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_O
ON ENRICH_O.SO_SBSCRPTN_ITM_SLS_TRX_KEY=O.SO_SBSCRPTN_ITM_SLS_TRX_KEY
AND ENRICH_O.TRANS_TYPE_CODE='XAAS'
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_R
ON ENRICH_R.SO_SBSCRPTN_ITM_SLS_TRX_KEY=R.SO_SBSCRPTN_ITM_SLS_TRX_KEY
AND ENRICH_R.TRANS_TYPE_CODE='XAAS' )XAAS
SET DV_RENEWAL_GAP_DAYS_CNT=XAAS.RENEWAL_GAP_DAYS
WHERE NATTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY=XAAS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NATTR.END_TV_DTM= '3500-01-01 00:00:00'
AND NATTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND NATTR.RENEWAL_REF_ID<>'UNKNOWN'
AND ( NATTR.ITEM_CATEGORY_NAME IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
OR NATTR.ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )
AND NATTR.ORDER_ORIGIN_CD <>  'DISTI-DSV'
AND NATTR.RENEWAL_REF_CD ='LINE REFERENCE NUMBER'
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT<>XAAS.RENEWAL_GAP_DAYS;

UPDATE NATTR FROM 
$$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NATTR,
(SELECT  DISTINCT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
(CASE WHEN (TRUNC(O.TERM_START_DT) IN ('3500-01-01','1900-01-01') OR TRUNC(R.TERM_END_DT) IN ('3500-01-01','1900-01-01')) THEN -9999 
ELSE
COALESCE(( CAST(COALESCE(O.TERM_START_DT,ENRICH_O.NEW_SERVICE_CONTRACT_START_DTM) AS DATE)-CAST(COALESCE(R.TERM_END_DT,ENRICH_R.NEW_SERVICE_CONTRACT_END_DTM) AS DATE)) ,-9999) END) AS RENEWAL_GAP_DAYS
FROM (SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.SK_ERP_BKGS_TRX_ID,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND (RTR.ITEM_CATEGORY_NAME IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
OR RTR.ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )
AND RTR.ORDER_ORIGIN_CD <>  'DISTI-DSV'
AND RTR.RENEWAL_REF_CD='OFFER ATTRIBUTION ID'
GROUP BY 1,2,3,4) RTR
INNER JOIN  $$STGDB.WI_SMR_XAAS_RENEW_TRX_INC O
ON  RTR.SK_ERP_BKGS_TRX_ID=O.SK_TRX_ID_INT
LEFT JOIN (SELECT TRX.*,SK_ATTRIBUTION_ID_INT from
(SELECT * FROM $$STGDB.WI_SMR_XAAS_RENEW_TRX_INC 
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORIGINAL_SYSTEM_LINE_REF_ID ORDER BY BOOKED_DT DESC)=1)TRX 
INNER JOIN 
$$NRTNCRVWDB.N_XAAS_SO_SBSCRPTN_ATTRBTN_NRT XOA
ON TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY = XOA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY
AND BK_OFFER_ATTRIBUTION_ID_INT > 0)R
ON R.SK_ATTRIBUTION_ID_INT =CAST(RTR.RENEWAL_REF_ID  AS BIGINT)
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_O
ON ENRICH_O.SO_SBSCRPTN_ITM_SLS_TRX_KEY=O.SO_SBSCRPTN_ITM_SLS_TRX_KEY
AND ENRICH_O.TRANS_TYPE_CODE='XAAS'
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_R
ON ENRICH_R.SO_SBSCRPTN_ITM_SLS_TRX_KEY=R.SO_SBSCRPTN_ITM_SLS_TRX_KEY
AND ENRICH_R.TRANS_TYPE_CODE='XAAS' )XAAS
SET DV_RENEWAL_GAP_DAYS_CNT=XAAS.RENEWAL_GAP_DAYS
WHERE NATTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY=XAAS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NATTR.END_TV_DTM= '3500-01-01 00:00:00'
AND NATTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND NATTR.RENEWAL_REF_ID<>'UNKNOWN'
AND (NATTR.ITEM_CATEGORY_NAME IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
OR NATTR.ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) ) 
AND NATTR.ORDER_ORIGIN_CD <>  'DISTI-DSV' 
AND NATTR.RENEWAL_REF_CD ='OFFER ATTRIBUTION ID'
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT<>XAAS.RENEWAL_GAP_DAYS;

UPDATE NATTR FROM 
$$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NATTR,
(SELECT  DISTINCT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
(CASE WHEN (TRUNC(BKG_POS.RU_SERVICE_CONTRACT_START_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(POS.RU_SERVICE_CONTRACT_END_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(NSOL.RU_SERVICE_CONTRACT_END_DTM) IN ('3500-01-01','1900-01-01')) THEN -9999 
ELSE
COALESCE(( CAST(BKG_POS.RU_SERVICE_CONTRACT_START_DTM  AS DATE)-CAST(COALESCE((CASE WHEN BK_SALES_CHANNEL_CD ='Two Tier Distributor' THEN POS.RU_SERVICE_CONTRACT_END_DTM ELSE NSOL.RU_SERVICE_CONTRACT_END_DTM END),ENRICH_R.NEW_SERVICE_CONTRACT_END_DTM) AS DATE)) ,-9999) END ) AS RENEWAL_GAP_DAYS
FROM (SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.POS_TRANSACTION_ID_INT,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.ITEM_CATEGORY_NAME NOT IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
AND RTR.ORDER_ORIGIN_CD =  'DISTI-DSV'
AND RTR.RENEWAL_REF_CD='SO LINE ID'
GROUP BY 1,2,3,4)RTR
INNER JOIN  $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE BKG_POS  
ON RTR.POS_TRANSACTION_ID_INT = BKG_POS.BK_POS_TRANSACTION_ID_INT
INNER  JOIN  $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL
ON NSOL.SK_SO_LINE_ID_INT =CAST(RTR.RENEWAL_REF_ID AS BIGINT)
AND NSOL.SS_CODE='CG' 
LEFT  JOIN $$STGDB.WI_SMR_POS_RENEW_TRX_INC POS 
ON NSOL.SALES_ORDER_LINE_KEY=POS.SALES_ORDER_LINE_KEY
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_R 
ON ENRICH_R.SALES_ORDER_LINE_KEY =NSOL.SALES_ORDER_LINE_KEY
AND ENRICH_R.TRANS_TYPE_CODE='ERP')ERP
SET DV_RENEWAL_GAP_DAYS_CNT=ERP.RENEWAL_GAP_DAYS
WHERE NATTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY=ERP.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NATTR.END_TV_DTM= '3500-01-01 00:00:00'
AND NATTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND NATTR.ITEM_CATEGORY_NAME NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
AND NATTR.ORDER_ORIGIN_CD = 'DISTI-DSV'
AND NATTR.RENEWAL_REF_CD ='SO LINE ID'
AND NATTR.RENEWAL_REF_ID<>'UNKNOWN'
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT<>ERP.RENEWAL_GAP_DAYS;

UPDATE NATTR FROM 
$$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NATTR,
(SELECT  DISTINCT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
(CASE WHEN (TRUNC(BKG_POS.RU_SERVICE_CONTRACT_START_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(POS.RU_SERVICE_CONTRACT_END_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(NSOL.RU_SERVICE_CONTRACT_END_DTM) IN ('3500-01-01','1900-01-01')) THEN -9999 
ELSE
COALESCE(( CAST(BKG_POS.RU_SERVICE_CONTRACT_START_DTM  AS DATE)-CAST(COALESCE((CASE WHEN BK_SALES_CHANNEL_CD ='Two Tier Distributor' THEN POS.RU_SERVICE_CONTRACT_END_DTM ELSE NSOL.RU_SERVICE_CONTRACT_END_DTM END),ENRICH_R.NEW_SERVICE_CONTRACT_END_DTM) AS DATE)) ,-9999) END ) AS RENEWAL_GAP_DAYS
FROM (SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.POS_TRANSACTION_ID_INT,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.ITEM_CATEGORY_NAME NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
AND RTR.ORDER_ORIGIN_CD =  'DISTI-DSV' 
AND RTR.RENEWAL_REF_CD ='LINE REFERENCE NUMBER'
GROUP BY 1,2,3,4) RTR
INNER JOIN  $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE BKG_POS  
ON RTR.POS_TRANSACTION_ID_INT = BKG_POS.BK_POS_TRANSACTION_ID_INT
INNER  JOIN NSOL_LINE_REF NSOL 
ON NSOL.ORIGINAL_SYSTEM_LINE_REF_ID = RTR.RENEWAL_REF_ID 
LEFT  JOIN $$STGDB.WI_SMR_POS_RENEW_TRX_INC POS 
ON NSOL.SALES_ORDER_LINE_KEY=POS.SALES_ORDER_LINE_KEY
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_R 
ON ENRICH_R.SALES_ORDER_LINE_KEY =NSOL.SALES_ORDER_LINE_KEY
AND ENRICH_R.TRANS_TYPE_CODE='ERP'
)ERP
SET DV_RENEWAL_GAP_DAYS_CNT=ERP.RENEWAL_GAP_DAYS
WHERE NATTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY=ERP.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NATTR.END_TV_DTM= '3500-01-01 00:00:00'
AND NATTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND NATTR.ITEM_CATEGORY_NAME NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' )  
AND NATTR.ORDER_ORIGIN_CD = 'DISTI-DSV'
AND NATTR.RENEWAL_REF_CD ='LINE REFERENCE NUMBER'
AND NATTR.RENEWAL_REF_ID<>'UNKNOWN'
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT<>ERP.RENEWAL_GAP_DAYS;

UPDATE NATTR FROM 
$$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NATTR,
(SELECT  DISTINCT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
(CASE WHEN (TRUNC(BKG_POS.RU_SERVICE_CONTRACT_START_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(POS_REF.RU_SERVICE_CONTRACT_END_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(NSOL.RU_SERVICE_CONTRACT_END_DTM) IN ('3500-01-01','1900-01-01')) THEN -9999 
ELSE
COALESCE(( CAST(BKG_POS.RU_SERVICE_CONTRACT_START_DTM  AS DATE)-CAST(COALESCE((CASE WHEN BK_SALES_CHANNEL_CD='Two Tier Distributor' THEN POS_REF.RU_SERVICE_CONTRACT_END_DTM ELSE NSOL.RU_SERVICE_CONTRACT_END_DTM END),ENRICH_R.NEW_SERVICE_CONTRACT_END_DTM) AS DATE)) ,-9999) END) AS RENEWAL_GAP_DAYS
FROM (SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.POS_TRANSACTION_ID_INT,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.ITEM_CATEGORY_NAME NOT IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
AND RTR.ORDER_ORIGIN_CD = 'DISTI-DSV'
AND RTR.RENEWAL_REF_CD='OFFER ATTRIBUTION ID'
GROUP BY 1,2,3,4) RTR
INNER JOIN  $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE BKG_POS  
ON RTR.POS_TRANSACTION_ID_INT = BKG_POS.BK_POS_TRANSACTION_ID_INT
INNER JOIN (SELECT SOL_R.SALES_ORDER_LINE_KEY,SK_SO_LINE_ID_INT,SK_OFFER_ATTRIBUTION_ID_INT,RU_SERVICE_CONTRACT_START_DTM,RU_SERVICE_CONTRACT_END_DTM,BK_SALES_CHANNEL_CD FROM  $$SLSORDVWDB.N_SOL_OFFER_ATTRIBUTION OA INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE SOL_R
ON SOL_R.SALES_ORDER_LINE_KEY=OA.TOP_SKU_SALES_ORDER_LINE_KEY
AND SS_CODE='CG' )NSOL
ON   NSOL.SK_OFFER_ATTRIBUTION_ID_INT  = CAST (RTR.RENEWAL_REF_ID  AS BIGINT) 
LEFT JOIN $$STGDB.WI_SMR_POS_RENEW_TRX_INC POS_REF
ON NSOL.SALES_ORDER_LINE_KEY=POS_REF.SALES_ORDER_LINE_KEY
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_R 
ON ENRICH_R.SALES_ORDER_LINE_KEY =NSOL.SALES_ORDER_LINE_KEY
AND ENRICH_R.TRANS_TYPE_CODE='ERP')ERP
SET DV_RENEWAL_GAP_DAYS_CNT=ERP.RENEWAL_GAP_DAYS
WHERE NATTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY=ERP.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NATTR.END_TV_DTM= '3500-01-01 00:00:00'
AND NATTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND NATTR.RENEWAL_REF_ID<>'UNKNOWN'
AND NATTR.ITEM_CATEGORY_NAME NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
AND NATTR.ORDER_ORIGIN_CD = 'DISTI-DSV'  
AND NATTR.RENEWAL_REF_CD ='OFFER ATTRIBUTION ID'
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT<>ERP.RENEWAL_GAP_DAYS;

UPDATE NATTR FROM 
$$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NATTR,
(SELECT  DISTINCT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
(CASE WHEN (TRUNC(BKG_POS.RU_SERVICE_CONTRACT_START_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(POS.RU_SERVICE_CONTRACT_END_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(R.TERM_END_DT) IN ('3500-01-01','1900-01-01')) THEN -9999 
ELSE
COALESCE(( CAST(BKG_POS.RU_SERVICE_CONTRACT_START_DTM  AS DATE)-CAST(COALESCE((CASE WHEN BK_SALES_CHANNEL_CD ='Two Tier Distributor' THEN POS.RU_SERVICE_CONTRACT_END_DTM ELSE R.TERM_END_DT END),ENRICH_R.NEW_SERVICE_CONTRACT_END_DTM) AS DATE)) ,-9999) END ) AS RENEWAL_GAP_DAYS
FROM (SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.POS_TRANSACTION_ID_INT,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.ITEM_CATEGORY_NAME IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
AND RTR.ORDER_ORIGIN_CD = 'DISTI-DSV'
AND RTR.RENEWAL_REF_CD='LINE REFERENCE NUMBER'
GROUP BY 1,2,3,4) RTR
INNER JOIN  $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE BKG_POS  
ON RTR.POS_TRANSACTION_ID_INT = BKG_POS.BK_POS_TRANSACTION_ID_INT
INNER JOIN (SELECT * FROM $$STGDB.WI_SMR_XAAS_RENEW_TRX_INC 
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORIGINAL_SYSTEM_LINE_REF_ID ORDER BY BOOKED_DT DESC)=1)R
ON R.ORIGINAL_SYSTEM_LINE_REF_ID=RTR.RENEWAL_REF_ID
LEFT JOIN $$STGDB.WI_SMR_POS_RENEW_TRX_INC POS 
ON R.MINOR_LN_EXAAS_SUBSCR_SOL_KEY=POS.SALES_ORDER_LINE_KEY
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_R
ON ENRICH_R.SO_SBSCRPTN_ITM_SLS_TRX_KEY=R.SO_SBSCRPTN_ITM_SLS_TRX_KEY
AND ENRICH_R.TRANS_TYPE_CODE='XAAS' )XAAS
SET DV_RENEWAL_GAP_DAYS_CNT=XAAS.RENEWAL_GAP_DAYS
WHERE NATTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY=XAAS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NATTR.END_TV_DTM= '3500-01-01 00:00:00'
AND NATTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND NATTR.RENEWAL_REF_ID<>'UNKNOWN'
AND NATTR.ITEM_CATEGORY_NAME IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
AND NATTR.ORDER_ORIGIN_CD = 'DISTI-DSV'
AND NATTR.RENEWAL_REF_CD ='LINE REFERENCE NUMBER'
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT<>XAAS.RENEWAL_GAP_DAYS;

UPDATE NATTR FROM 
$$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NATTR,
(SELECT  DISTINCT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
(CASE WHEN (TRUNC(BKG_POS.RU_SERVICE_CONTRACT_START_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(POS_REF.RU_SERVICE_CONTRACT_END_DTM) IN ('3500-01-01','1900-01-01') OR TRUNC(R.TERM_END_DT) IN ('3500-01-01','1900-01-01')) THEN -9999 
ELSE
COALESCE(( CAST(BKG_POS.RU_SERVICE_CONTRACT_START_DTM  AS DATE)-CAST(COALESCE((CASE WHEN BK_SALES_CHANNEL_CD='Two Tier Distributor' THEN POS_REF.RU_SERVICE_CONTRACT_END_DTM ELSE R.TERM_END_DT END),ENRICH_R.NEW_SERVICE_CONTRACT_END_DTM) AS DATE)) ,-9999) END) AS RENEWAL_GAP_DAYS
FROM (SELECT RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,RTR.SALES_ORDER_LINE_KEY,RTR.POS_TRANSACTION_ID_INT,RTR.RENEWAL_REF_ID FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV RTR
WHERE RTR.END_TV_DTM='3500-01-01 00:00:00'
AND RTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND RTR.RENEWAL_REF_ID<>'UNKNOWN' 
AND RTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND RTR.ITEM_CATEGORY_NAME IN ('Billing','FLEXIBLE CONSUMPTION MODEL') 
AND RTR.ORDER_ORIGIN_CD='DISTI-DSV'
AND RTR.RENEWAL_REF_CD='OFFER ATTRIBUTION ID'
GROUP BY 1,2,3,4) RTR
INNER JOIN  $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE BKG_POS  
ON RTR.POS_TRANSACTION_ID_INT = BKG_POS.BK_POS_TRANSACTION_ID_INT
LEFT JOIN (SELECT TRX.*,XOA.SK_ATTRIBUTION_ID_INT from 
(SELECT * FROM $$STGDB.WI_SMR_XAAS_RENEW_TRX_INC 
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORIGINAL_SYSTEM_LINE_REF_ID ORDER BY BOOKED_DT DESC)=1) TRX 
INNER JOIN 
$$NRTNCRVWDB.N_XAAS_SO_SBSCRPTN_ATTRBTN_NRT XOA
ON TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY = XOA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY
AND BK_OFFER_ATTRIBUTION_ID_INT > 0)R
ON R.SK_ATTRIBUTION_ID_INT =CAST(RTR.RENEWAL_REF_ID  AS BIGINT)
LEFT JOIN $$STGDB.WI_SMR_POS_RENEW_TRX_INC POS_REF
ON R.MINOR_LN_EXAAS_SUBSCR_SOL_KEY=POS_REF.SALES_ORDER_LINE_KEY
LEFT JOIN $$ETLVWDB.WI_SMR_OPL_RENEW_ENRICH_DT_INC ENRICH_R
ON ENRICH_R.SO_SBSCRPTN_ITM_SLS_TRX_KEY=R.SO_SBSCRPTN_ITM_SLS_TRX_KEY 
AND ENRICH_R.TRANS_TYPE_CODE='XAAS')XAAS
SET DV_RENEWAL_GAP_DAYS_CNT=XAAS.RENEWAL_GAP_DAYS
WHERE NATTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY=XAAS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY
AND NATTR.END_TV_DTM= '3500-01-01 00:00:00'
AND NATTR.EDW_CREATE_DTM>='2021-04-11 00:00:00'
AND NATTR.RENEWAL_REF_ID<>'UNKNOWN'
AND NATTR.ITEM_CATEGORY_NAME IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
AND NATTR.ORDER_ORIGIN_CD='DISTI-DSV'
AND NATTR.RENEWAL_REF_CD ='OFFER ATTRIBUTION ID'
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT=-9999
AND NATTR.DV_RENEWAL_GAP_DAYS_CNT<>XAAS.RENEWAL_GAP_DAYS;


Source2 Name : SQ_N_ATTR_PRDT_NEW_RNWL_ACV


Pre SQL : 



SQL Query : 
SELECT
ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
SK_RTR_ATTRIBUTION_ID,
ATTR_PRDT_KEY,
SALES_ORDER_LINE_KEY,
HQ_CR_PRTY_KEY,
TRANSACTION_CR_PARTY_KEY,
BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
BK_TECH_GROUP_ID,
BK_AS_ARCHITECTURE_NAME,
COVERED_PRDT_KEY,
ATTR_PRDT_QTY,
ATTR_PCT,
ATTR_NET_PRICE_LOCAL_AMT,
ATTR_EXTD_PRICE_LOCAL_AMT,
SALES_MOTION_CD,
SALES_MOTION_CONTEXT_NAME,
ERP_CUST_ACCT_LOC_KEY,
AS_TS_CD,
SK_LINE_REF_NUM,
SK_ERP_BKGS_TRX_ID,
SK_RENEW_CONTRACT_LINE_ID,
SK_AS_PARENT_INVENTORY_ITEM_ID,
ITEM_CATEGORY_NAME,
ERP_TRX_VERSION_INT,
SS_CD,
SK_ATTRIBUTION_ID_INT,
ATTR_PRDT_CLASS_NAME,
RENEWAL_REF_ID,
RENEWAL_REF_CD,
SMR_TAGGING_FAILURE_RSN_CD,
SALES_MOTION_TIMING_CD,
MANUAL_OVERRIDE_ROLE,
TOTAL_SERVICES_USD_AMT,
ACV_USD_AMT,
TCV_USD_AMT,
EXTENDED_PRICE_USD_AMT,
REQUESTING_CSCO_WRKR_PRTY_KEY,
SLS_MTN_CORRECTION_CASE_NUM,
SLS_MTN_CORRECTION_CMNT,
EDW_CREATE_DTM,
EDW_CREATE_USER,
EDW_UPDATE_DTM,
EDW_UPDATE_USER,
OFFER_ATTRIB_PRDT_KEY,
POS_TRANSACTION_ID_INT,
ORDER_ORIGIN_CD,
DV_RENEWAL_GAP_DAYS_CNT
FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV NXSSIS
WHERE NXSSIS.END_TV_DTM=CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))


Post SQL : 



Target2 Name : N_ATTR_PRDT_NEW_RNWL_ACV


Pre SQL : 
DELETE FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV ALL;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$SLSORDDB','N_ATTR_PRDT_NEW_RNWL_ACV','D');


DELETE FROM $$STGDB.WI_TTS_SOWB_SOL_LINES_ACV ;

INSERT INTO $$STGDB.WI_TTS_SOWB_SOL_LINES_ACV
SELECT 
	NSOL.SALES_ORDER_LINE_KEY ,
	NSOL.SALES_MOTION_CD,
	CASE WHEN NSOL.SALES_MOTION_CD = 'RENEW' THEN NSOL.SALES_MOTION_TIMING_NAME 
	ELSE 'UNKNOWN'
	END SALES_MOTION_TIMING_CD	
FROM $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL 
  WHERE NSOL.SS_CODE = 'CG' 
   /*AND NOT EXISTS ( SELECT 1 FROM $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV ATT WHERE ATT.SALES_ORDER_LINE_KEY = NSOL.SALES_ORDER_LINE_KEY )*/
   AND ( EXISTS (
    SELECT 1 FROM (SELECT 
       P.ITEM_KEY
       FROM
       $$COMREFVWDB.N_PRODUCT P
       INNER JOIN 
       $$COMREFVWDB.MT_SVC_FINANCE_HIERARCHY SFH ON P.ITEM_KEY = SFH.ITEM_KEY
       WHERE P.PRDT_SETUP_CLASSIFICATION_CD <> 'SOFTWARE' --EXCLUDE SW
       AND SFH.BK_SERVICE_CATEGORY_ID = 'TECHNICAL SUPPORT SERVICES' 
       AND SFH.BK_ALLOCATED_SERVC_GROUP_ID NOT IN
       ( 'AS CORE' ,  'AS SUBSCRIPTION' , 'FOCUSED TECHNICAL SUPPORT SERVICES' , 'CLOUD MANAGED SERVICES' )--EXCLUDE FTS,CMS,AS
       AND RU_BK_SERVICE_PROD_SUBGROUP_ID NOT IN (SELECT BK_PRDT_SUBGROUP_ID FROM ( SELECT * FROM $$SERVICEVWDB.N_GENERIC_SVC_PRDT_ATTR WHERE BK_GSP_ATTR_NAME = 'SW SERVICE CATEGORY' ) WI ) --EXCLUDE SWSS
       ) WI
     WHERE NSOL.PRODUCT_KEY = WI.ITEM_KEY
   )
   OR (NSOL.BK_SO_SRC_NAME IN ('Manual', 'Copy' ) AND NSOL.PRODUCT_KEY NOT IN ( SELECT P.ITEM_KEY FROM
      $$COMREFVWDB.N_PRODUCT P
      INNER JOIN 
      $$COMREFVWDB.MT_SVC_FINANCE_HIERARCHY SFH ON P.ITEM_KEY = SFH.ITEM_KEY
      AND SFH.BK_ALLOCATED_SERVC_GROUP_ID  IN ( 'AS FIXED', 'AS TRANSACTION' )
     )
                 )
   )
GROUP BY 1,2,3 ;

COLLECT STATS COLUMN (SALES_ORDER_LINE_KEY ) ON $$STGDB.WI_TTS_SOWB_SOL_LINES_ACV ;