


Source1 Name : SQ_W_SALES_ORDER_LINE_NRT_CG1


Pre SQL : 



SQL Query : 
SELECT WSOLNC.SALES_ORDER_LINE_KEY, 
 WSOLNC.EP_HEADER_ID_INT, 
 WSOLNC.SALES_ORDER_KEY, 
 WSOLNC.ORDER_QTY, 
 WSOLNC.UNIT_NET_PRICE_LOCAL_AMT, 
 WSOLNC.BOOKINGS_PERCENT, 
 WSOLNC.SO_LINE_SOURCE_CREATE_DTM, 
 WSOLNC.DV_SO_LINE_SOURCE_CREATE_DT, 
 WSOLNC.SO_LINE_SOURCE_UPDATE_DTM, 
 WSOLNC.DV_SO_LINE_SOURCE_UPDATE_DT, 
 WSOLNC.PRICING_DTM, 
 WSOLNC.DV_PRICING_DT, 
 WSOLNC.UNIT_LIST_PRICE_LOCAL_AMT, 
 WSOLNC.SK_SALES_ORDER_LINE_ID_INT, 
 WSOLNC.INVOICED_QTY, 
 WSOLNC.SS_CD, 
 WSOLNC.CISCO_SCHEDULE_RESULT_DT, 
 WSOLNC.FACTORY_RECOMMIT_DT, 
 WSOLNC.SHIPPED_QTY, 
 WSOLNC.DD_SHPMNT_CONFIRMED_RESULT_CD,
 WSOLNC.SO_LINE_OPEN_FLG, 
 WSOLNC.COMPLETE_LINE_RESULT_CD, 
 WSOLNC.MAJOR_LINE_TYPE, 
 WSOLNC.SCHEDULED_SHIP_DT, 
 WSOLNC.CUSTOMER_SHIPMENT_RECOMMIT_DT, 
 WSOLNC.BK_INVENTORY_ORGANIZATION_KEY, 
 /*WSOLNC.BK_INVENTORY_ORGANIZATION_KEY, commented because found two same columns */
 WSOLNC.DD_BK_INV_ORGANIZATION_NAME_CD, 
 WSOLNC.EP_INV_ORG_SHPFRM_ORG_ID_INT, 
 WSOLNC.PROMISED_TO_CUST_SHIPMENT_DT, 
 WSOLNC.SHIP_TO_CUSTOMER_KEY, 
 WSOLNC.EP_STC_SHIP_TO_ORG_ID_INT, 
 WSOLNC.PRODUCT_KEY, 
 WSOLNC.EP_PRDT_INVENTORY_ITEM_ID_INT, 
 WSOLNC.RU_SHIPSET_NUM_INT, 
 WSOLNC.SOURCE_DELETED_FLG, 
 WSOLNC.RU_PARNT_SLS_ORDER_LINE_KEY, 
 WSOLNC.EDW_CREATE_DTM, 
 WSOLNC.EDW_CREATE_USER, 
 WSOLNC.EDW_UPDATE_DTM, 
 WSOLNC.EDW_UPDATE_USER,
 WSOLNC.DV_OPTION_CLASS_LINE_FLG,
 WSOLNC.SO_LINE_NUM_INT ,
 WSOLNC.REVENUE_TYPE_CD, 
 WSOLNC.DD_SHIPMENT_CONFIRMED_DT,  
 WSOLNC.DD_SHIPMENT_CONFIRMED_DTM, 
 WSOLNC.ITEM_TYPE_CD,
 WSOLNC.SALES_ORDER_LINE_CTGRY_TYPE_CD, 
 WSOLNC.SO_LINE_TYPE_NAME,
 WSOLNC. ORIGINATED_QTC_VIA_CG1_FLG,
 WSOLNC.ACTUAL_SHIPMENT_DTM,
 WSOLNC.DV_ACTUAL_SHIPMENT_DT,
 WSOLNC.DELIVERY_OPTION_CD,
 WSOLNC.BOOKINGS_SOURCE_CD,
 WSOLNC.SALES_MOTION_CD,
 WSOLNC.SK_OPL_LINE_ID_INT,
 WSOLNC.SK_SBP_ORDER_LINE_ID_INT,
 WSOLNC.TRX_BOOKING_SRC_CD,
 WSOLNC.MIGRATION_TRX_SRC_CD,
 WSOLNC.RU_SERVICE_CONTRACT_START_DTM , 
 WSOLNC.RU_SERVICE_CONTRACT_END_DTM ,
 WSOLNC.RU_SRVC_CNTRCT_DRTN_MNTHS_CNT,
 WSOLNC.PRICING_TERM_MTHS_CNT,
 WSOLNC.ORIG_UNIT_LST_PRC_TRXL_AMT ,
 WSOLNC.ORIG_EXTD_LST_PRC_TRXL_AMT,
  /* ADDED AS A PART OF Q1FY21 ACV SCALE*/
 WSOLNC.TRANSACTIONAL_ACV_FLG,
 WSOLNC.ACV_FLG,
 WSOLNC.ANNUAL_TRANSACTIONAL_AMT,
 WSOLNC.BOOKINGS_POLICY_CD
 FROM
 $$WORKDB.W_SALES_ORDER_LINE_NRT_CG1 WSOLNC WHERE 1=2


Post SQL : 



Target1 Name : N_SALES_ORDER_LINE_NRT


Pre SQL : 



Post SQL : 
MERGE INTO $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT NSOLN
USING $$WORKDB.W_SALES_ORDER_LINE_NRT_CG1 WSOLNC
ON 
WSOLNC.SALES_ORDER_LINE_KEY=NSOLN.SALES_ORDER_LINE_KEY
WHEN MATCHED THEN UPDATE 
SET 
EP_HEADER_ID_INT=WSOLNC.EP_HEADER_ID_INT,
SALES_ORDER_KEY=WSOLNC.SALES_ORDER_KEY,
ORDER_QTY=WSOLNC.ORDER_QTY,
UNIT_NET_PRICE_LOCAL_AMT=WSOLNC.UNIT_NET_PRICE_LOCAL_AMT,
BOOKINGS_PERCENT=WSOLNC.BOOKINGS_PERCENT,
SO_LINE_SOURCE_CREATE_DTM=WSOLNC.SO_LINE_SOURCE_CREATE_DTM,
DV_SO_LINE_SOURCE_CREATE_DT=WSOLNC.DV_SO_LINE_SOURCE_CREATE_DT,
SO_LINE_SOURCE_UPDATE_DTM=WSOLNC.SO_LINE_SOURCE_UPDATE_DTM,
DV_SO_LINE_SOURCE_UPDATE_DT=WSOLNC.DV_SO_LINE_SOURCE_UPDATE_DT,
PRICING_DTM=WSOLNC.PRICING_DTM,
DV_PRICING_DT=WSOLNC.DV_PRICING_DT,
UNIT_LIST_PRICE_LOCAL_AMT=WSOLNC.UNIT_LIST_PRICE_LOCAL_AMT,
SK_SALES_ORDER_LINE_ID_INT=WSOLNC.SK_SALES_ORDER_LINE_ID_INT,
INVOICED_QTY=WSOLNC.INVOICED_QTY,
SS_CD=WSOLNC.SS_CD,
FACTORY_RECOMMIT_DT=WSOLNC.FACTORY_RECOMMIT_DT,
SHIPPED_QTY=WSOLNC.SHIPPED_QTY,
SO_LINE_OPEN_FLG=WSOLNC.SO_LINE_OPEN_FLG,
MAJOR_LINE_TYPE=WSOLNC.MAJOR_LINE_TYPE,
SCHEDULED_SHIP_DT=WSOLNC.SCHEDULED_SHIP_DT,
CUSTOMER_SHIPMENT_RECOMMIT_DT=WSOLNC.CUSTOMER_SHIPMENT_RECOMMIT_DT,
BK_INVENTORY_ORGANIZATION_KEY=WSOLNC.BK_INVENTORY_ORGANIZATION_KEY,
DD_BK_INV_ORGANIZATION_NAME_CD=WSOLNC.DD_BK_INV_ORGANIZATION_NAME_CD,
EP_INV_ORG_SHPFRM_ORG_ID_INT=WSOLNC.EP_INV_ORG_SHPFRM_ORG_ID_INT,
PROMISED_TO_CUST_SHIPMENT_DT=WSOLNC.PROMISED_TO_CUST_SHIPMENT_DT,
SHIP_TO_CUSTOMER_KEY=WSOLNC.SHIP_TO_CUSTOMER_KEY,
EP_STC_SHIP_TO_ORG_ID_INT=WSOLNC.EP_STC_SHIP_TO_ORG_ID_INT,
PRODUCT_KEY=WSOLNC.PRODUCT_KEY,
EP_PRDT_INVENTORY_ITEM_ID_INT=WSOLNC.EP_PRDT_INVENTORY_ITEM_ID_INT,
SOURCE_DELETED_FLG=WSOLNC.SOURCE_DELETED_FLG,
RU_PARNT_SLS_ORDER_LINE_KEY=WSOLNC.RU_PARNT_SLS_ORDER_LINE_KEY,
EDW_UPDATE_DTM=WSOLNC.EDW_UPDATE_DTM,
EDW_UPDATE_USER=WSOLNC.EDW_UPDATE_USER,
DV_OPTION_CLASS_LINE_FLG=WSOLNC.DV_OPTION_CLASS_LINE_FLG,
SO_LINE_NUM_INT=WSOLNC.SO_LINE_NUM_INT,
SALES_ORDER_LINE_CTGRY_TYPE_CD=WSOLNC.SALES_ORDER_LINE_CTGRY_TYPE_CD,
REVENUE_TYPE_CD = WSOLNC.REVENUE_TYPE_CD, 
ITEM_TYPE_CD = WSOLNC.ITEM_TYPE_CD  ,
/*,SO_LINE_TYPE_NAME = WSOLNC.SO_LINE_TYPE_NAME */
DELIVERY_OPTION_CD = COALESCE(WSOLNC.DELIVERY_OPTION_CD,'UNKNOWN') ,
ACTUAL_SHIPMENT_DTM  = WSOLNC.ACTUAL_SHIPMENT_DTM, 
DV_ACTUAL_SHIPMENT_DT = WSOLNC.DV_ACTUAL_SHIPMENT_DT,
BOOKINGS_SOURCE_CD=WSOLNC.BOOKINGS_SOURCE_CD, /*ARAJANAL: ADDED AS PART OF XAAS Q4FY15*/
SALES_MOTION_CD = WSOLNC.SALES_MOTION_CD,
 /* Added as part of Q2FY18 goponnus */
   TRX_BOOKING_SRC_CD=WSOLNC.TRX_BOOKING_SRC_CD,
/* Added as part of June 2018 release AMY-NRT Scope*/
RU_SERVICE_CONTRACT_START_DTM=WSOLNC.RU_SERVICE_CONTRACT_START_DTM , 
RU_SERVICE_CONTRACT_END_DTM=WSOLNC.RU_SERVICE_CONTRACT_END_DTM ,
RU_SRVC_CNTRCT_DRTN_MNTHS_CNT=WSOLNC.RU_SRVC_CNTRCT_DRTN_MNTHS_CNT,
ORIG_UNIT_LST_PRC_TRXL_AMT =WSOLNC.ORIG_UNIT_LST_PRC_TRXL_AMT ,
ORIG_EXTD_LST_PRC_TRXL_AMT=WSOLNC.ORIG_EXTD_LST_PRC_TRXL_AMT

WHEN NOT MATCHED THEN INSERT 
(
SALES_ORDER_LINE_KEY          	,
EP_HEADER_ID_INT              	,
SALES_ORDER_KEY               	,
ORDER_QTY                     	,
UNIT_NET_PRICE_LOCAL_AMT      	,
BOOKINGS_PERCENT              	,
SO_LINE_SOURCE_CREATE_DTM     	,
DV_SO_LINE_SOURCE_CREATE_DT   	,
SO_LINE_SOURCE_UPDATE_DTM     	,
DV_SO_LINE_SOURCE_UPDATE_DT   	,
PRICING_DTM                   	,
DV_PRICING_DT                 	,
UNIT_LIST_PRICE_LOCAL_AMT     	,
SK_SALES_ORDER_LINE_ID_INT    	,
INVOICED_QTY                  	,
SS_CD                         	,
CISCO_SCHEDULE_RESULT_DT      	,
FACTORY_RECOMMIT_DT           	,
SHIPPED_QTY                   	,
DD_SHPMNT_CONFIRMED_RESULT_CD 	,
SO_LINE_OPEN_FLG              	,
COMPLETE_LINE_RESULT_CD       	,
MAJOR_LINE_TYPE               	,
SCHEDULED_SHIP_DT             	,
CUSTOMER_SHIPMENT_RECOMMIT_DT 	,
BK_INVENTORY_ORGANIZATION_KEY 	,
DD_BK_INV_ORGANIZATION_NAME_CD	,
EP_INV_ORG_SHPFRM_ORG_ID_INT  	,
PROMISED_TO_CUST_SHIPMENT_DT  	,
SHIP_TO_CUSTOMER_KEY          	,
EP_STC_SHIP_TO_ORG_ID_INT     	,
PRODUCT_KEY                   	,
EP_PRDT_INVENTORY_ITEM_ID_INT 	,
RU_SHIPSET_NUM_INT            	,
SOURCE_DELETED_FLG            	,
RU_PARNT_SLS_ORDER_LINE_KEY   	,
EDW_CREATE_DTM                	,
EDW_CREATE_USER               	,
EDW_UPDATE_DTM                	,
EDW_UPDATE_USER               	,
DV_OPTION_CLASS_LINE_FLG      	,
SO_LINE_NUM_INT               	,
SALES_ORDER_LINE_CTGRY_TYPE_CD	,
REVENUE_TYPE_CD               	,
DD_SHIPMENT_CONFIRMED_DT      	,
DD_SHIPMENT_CONFIRMED_DTM     	,
ITEM_TYPE_CD                  	,
SO_LINE_TYPE_NAME               ,
DELIVERY_OPTION_CD				,
ACTUAL_SHIPMENT_DTM 			,
DV_ACTUAL_SHIPMENT_DT,
BOOKINGS_SOURCE_CD, /*ARAJANAL: ADDED AS PART OF XAAS Q4FY15*/
SALES_MOTION_CD,
  SK_OPL_LINE_ID_INT,
 SK_SBP_ORDER_LINE_ID_INT,
 TRX_BOOKING_SRC_CD,
 MIGRATION_TRX_SRC_CD,
/* Added as part of June 2018 release AMY-NRT Scope*/
RU_SERVICE_CONTRACT_START_DTM , 
RU_SERVICE_CONTRACT_END_DTM ,
RU_SRVC_CNTRCT_DRTN_MNTHS_CNT,
ORIG_UNIT_LST_PRC_TRXL_AMT,
ORIG_EXTD_LST_PRC_TRXL_AMT,
BOOKINGS_POLICY_CD
)
VALUES 
(
WSOLNC.SALES_ORDER_LINE_KEY,
WSOLNC.EP_HEADER_ID_INT,              
WSOLNC.SALES_ORDER_KEY,
WSOLNC.ORDER_QTY,
WSOLNC.UNIT_NET_PRICE_LOCAL_AMT,
WSOLNC.BOOKINGS_PERCENT,
WSOLNC.SO_LINE_SOURCE_CREATE_DTM,
WSOLNC.DV_SO_LINE_SOURCE_CREATE_DT,
WSOLNC.SO_LINE_SOURCE_UPDATE_DTM,
WSOLNC.DV_SO_LINE_SOURCE_UPDATE_DT,
WSOLNC.PRICING_DTM,
WSOLNC.DV_PRICING_DT,
WSOLNC.UNIT_LIST_PRICE_LOCAL_AMT,
WSOLNC.SK_SALES_ORDER_LINE_ID_INT,
WSOLNC.INVOICED_QTY,
WSOLNC.SS_CD,
WSOLNC.CISCO_SCHEDULE_RESULT_DT,
WSOLNC.FACTORY_RECOMMIT_DT,
WSOLNC.SHIPPED_QTY,
WSOLNC.DD_SHPMNT_CONFIRMED_RESULT_CD,
WSOLNC.SO_LINE_OPEN_FLG,
WSOLNC.COMPLETE_LINE_RESULT_CD,
WSOLNC.MAJOR_LINE_TYPE,
WSOLNC.SCHEDULED_SHIP_DT,
WSOLNC.CUSTOMER_SHIPMENT_RECOMMIT_DT,
WSOLNC.BK_INVENTORY_ORGANIZATION_KEY,
WSOLNC.DD_BK_INV_ORGANIZATION_NAME_CD,
WSOLNC.EP_INV_ORG_SHPFRM_ORG_ID_INT,
WSOLNC.PROMISED_TO_CUST_SHIPMENT_DT,
WSOLNC.SHIP_TO_CUSTOMER_KEY,
WSOLNC.EP_STC_SHIP_TO_ORG_ID_INT,
WSOLNC.PRODUCT_KEY,
WSOLNC.EP_PRDT_INVENTORY_ITEM_ID_INT,
WSOLNC.RU_SHIPSET_NUM_INT,
WSOLNC.SOURCE_DELETED_FLG,
WSOLNC.RU_PARNT_SLS_ORDER_LINE_KEY,
WSOLNC.EDW_CREATE_DTM,
WSOLNC.EDW_CREATE_USER,
WSOLNC.EDW_UPDATE_DTM,
WSOLNC.EDW_UPDATE_USER,
WSOLNC.DV_OPTION_CLASS_LINE_FLG,
WSOLNC.SO_LINE_NUM_INT,
WSOLNC.SALES_ORDER_LINE_CTGRY_TYPE_CD,
WSOLNC.REVENUE_TYPE_CD,
WSOLNC.DD_SHIPMENT_CONFIRMED_DT,
WSOLNC.DD_SHIPMENT_CONFIRMED_DTM,
WSOLNC.ITEM_TYPE_CD ,
WSOLNC.SO_LINE_TYPE_NAME,
COALESCE(WSOLNC.DELIVERY_OPTION_CD,'UNKNOWN'),
WSOLNC.ACTUAL_SHIPMENT_DTM,
WSOLNC.DV_ACTUAL_SHIPMENT_DT,
WSOLNC.BOOKINGS_SOURCE_CD, /*ARAJANAL: ADDED AS PART OF XAAS Q4FY15*/
 WSOLNC.SALES_MOTION_CD,
  WSOLNC.SK_OPL_LINE_ID_INT,
 WSOLNC.SK_SBP_ORDER_LINE_ID_INT,
 WSOLNC.TRX_BOOKING_SRC_CD,
 WSOLNC.MIGRATION_TRX_SRC_CD,
/* Added as part of June 2018 release AMY-NRT Scope*/
WSOLNC.RU_SERVICE_CONTRACT_START_DTM , 
WSOLNC.RU_SERVICE_CONTRACT_END_DTM ,
WSOLNC.RU_SRVC_CNTRCT_DRTN_MNTHS_CNT,
WSOLNC.ORIG_UNIT_LST_PRC_TRXL_AMT,
WSOLNC.ORIG_EXTD_LST_PRC_TRXL_AMT,
WSOLNC.BOOKINGS_POLICY_CD
);


UPDATE NSOLN
FROM $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT NSOLN, 
(SELECT SALES_ORDER_LINE_KEY,
BOOKING_PERCENT, 
SOURCE_COMMIT_DTM
FROM $$NRTSTGDB.WI_ORDER_LINES_EXT_NRT_CG1_BP WHERE SALES_ORDER_LINE_KEY<> -7777
QUALIFY ROW_NUMBER() OVER( PARTITION BY LINE_ID ORDER BY SOURCE_COMMIT_DTM DESC) = 1) WI
SET  BOOKINGS_PERCENT = COALESCE(WI.BOOKING_PERCENT,100),			 
	 EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0),
	 EDW_UPDATE_USER = USER               
WHERE NSOLN.SALES_ORDER_LINE_KEY = WI.SALES_ORDER_LINE_KEY;

UPDATE NSOLN
FROM $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT NSOLN, 
(SELECT SALES_ORDER_LINE_KEY,
ORIG_UNIT_LST_PRC_TRXL_AMT, 
ORIG_EXTD_LST_PRC_TRXL_AMT,
SOURCE_COMMIT_DTM
FROM $$NRTSTGDB.WI_ORDER_LINES_EXT_NRT_CG1_OLP WHERE SALES_ORDER_LINE_KEY<> -7777
QUALIFY ROW_NUMBER() OVER( PARTITION BY LINE_ID ORDER BY SOURCE_COMMIT_DTM DESC) = 1) WI
SET  ORIG_UNIT_LST_PRC_TRXL_AMT = COALESCE(WI.ORIG_UNIT_LST_PRC_TRXL_AMT,0),	
     ORIG_EXTD_LST_PRC_TRXL_AMT = COALESCE(WI.ORIG_EXTD_LST_PRC_TRXL_AMT,0),		 
	 EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0),
	 EDW_UPDATE_USER = USER               
WHERE NSOLN.SALES_ORDER_LINE_KEY = WI.SALES_ORDER_LINE_KEY;

/*ADDED AS PART OF PR20609 ACV FY20 MAY RELEASE*/

UPDATE NSOLN
 FROM $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT NSOLN, 
 (
 SELECT 
 WI_ACV.SALES_ORDER_LINE_KEY,
 CAST(WI_ACV.CONTRACT_START_DATE AS DATE) AS PERIODIC_BILLING_START_DT,
 CAST(WI_ACV.CONTRACT_END_DATE AS DATE) AS PERIODIC_BILLING_END_DT,
 SOURCE_COMMIT_DTM
 FROM 
(SELECT * FROM $$NRTSTGDB.WI_ORDER_LINES_EXT_NRT_CG1_PBL WHERE SALES_ORDER_LINE_KEY<> -7777
 QUALIFY ROW_NUMBER() OVER( PARTITION BY LINE_ID ORDER BY SOURCE_COMMIT_DTM DESC) = 1) WI_ACV
 INNER JOIN $$GGSRCVWDB.GG_CG1_OE_ORDER_LINES_ALL CG
 ON CG.LINE_ID = WI_ACV.LINE_ID
 WHERE CG.CREATION_DATE<=(SELECT LAST_EXTRACT_DATE AS ACV_INC_DATE FROM $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES  
    WHERE JOB_STREAM_ID='wf_WI_ORDER_LINES_EXT_NRT_CG1'AND TABLE_NAME='WI_ORDER_LINES_EXT_NRT_CG1_PBL'
     )
 AND WI_ACV.CONTRACT_START_DATE IS NOT NULL OR WI_ACV.CONTRACT_END_DATE IS NOT NULL
 ) WI
 SET              
         PERIODIC_BILLING_START_DT = WI.PERIODIC_BILLING_START_DT,
         PERIODIC_BILLING_END_DT   = WI.PERIODIC_BILLING_END_DT,
         EDW_UPDATE_DTM  =  CURRENT_TIMESTAMP(0),
         EDW_UPDATE_USER =  USER               
 WHERE NSOLN.SALES_ORDER_LINE_KEY = WI.SALES_ORDER_LINE_KEY
 AND   (     
             COALESCE(NSOLN.PERIODIC_BILLING_START_DT,CAST('3500/01/01' AS DATE))
    <> COALESCE(WI.PERIODIC_BILLING_START_DT,CAST('3500/01/01' AS DATE))
          OR COALESCE(NSOLN.PERIODIC_BILLING_END_DT ,CAST('3500/01/01' AS DATE))  
    <> COALESCE(WI.PERIODIC_BILLING_END_DT,CAST('3500/01/01' AS DATE))
       )
AND NSOLN.SS_CD<>'OPL';
 

UPDATE NSOLN
 FROM $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT NSOLN, 
 (
 SELECT 
 WI_ACV.SALES_ORDER_LINE_KEY,
 COALESCE(WI_ACV.CONTRACT_START_DATE,CG.SERVICE_START_DATE) AS RU_SERVICE_CONTRACT_START_DTM ,
 COALESCE(WI_ACV.CONTRACT_END_DATE,CG.SERVICE_END_DATE) AS RU_SERVICE_CONTRACT_END_DTM ,
 CASE WHEN WI_ACV.CONTRACT_START_DATE IS NOT NULL THEN CAST(CG.SERVICE_START_DATE AS DATE)
 ELSE CAST(NULL AS DATE) END AS PERIODIC_BILLING_START_DT,
 CASE WHEN WI_ACV.CONTRACT_END_DATE IS NOT NULL THEN CAST(CG.SERVICE_END_DATE AS DATE) 
 ELSE CAST(NULL AS DATE) END AS PERIODIC_BILLING_END_DT,
 SOURCE_COMMIT_DTM
 FROM 
 (SELECT * FROM $$NRTSTGDB.WI_ORDER_LINES_EXT_NRT_CG1_PBL WHERE SALES_ORDER_LINE_KEY<> -7777 
 QUALIFY ROW_NUMBER() OVER( PARTITION BY LINE_ID ORDER BY SOURCE_COMMIT_DTM DESC) = 1) WI_ACV
 INNER JOIN $$GGSRCVWDB.GG_CG1_OE_ORDER_LINES_ALL CG
 ON CG.LINE_ID = WI_ACV.LINE_ID
 WHERE CG.CREATION_DATE>(SELECT LAST_EXTRACT_DATE AS ACV_INC_DATE FROM $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES  
  WHERE JOB_STREAM_ID='wf_WI_ORDER_LINES_EXT_NRT_CG1'AND TABLE_NAME='WI_ORDER_LINES_EXT_NRT_CG1_PBL')
 ) WI
 SET              
         RU_SERVICE_CONTRACT_START_DTM = WI.RU_SERVICE_CONTRACT_START_DTM,
         RU_SERVICE_CONTRACT_END_DTM   = WI.RU_SERVICE_CONTRACT_END_DTM,
		 PERIODIC_BILLING_START_DT = WI.PERIODIC_BILLING_START_DT,
         PERIODIC_BILLING_END_DT   = WI.PERIODIC_BILLING_END_DT,
         EDW_UPDATE_DTM  =  CURRENT_TIMESTAMP(0),
         EDW_UPDATE_USER =  USER               
 WHERE NSOLN.SALES_ORDER_LINE_KEY = WI.SALES_ORDER_LINE_KEY
 AND   (
		COALESCE(NSOLN.RU_SERVICE_CONTRACT_START_DTM,CAST('3500/01/01 00:00:00' AS TIMESTAMP(0)))
			 <> COALESCE(WI.RU_SERVICE_CONTRACT_START_DTM,CAST('3500/01/01 00:00:00' AS TIMESTAMP(0)))
     OR COALESCE(NSOLN.RU_SERVICE_CONTRACT_END_DTM ,CAST('3500/01/01 00:00:00' AS TIMESTAMP(0)))  
		     <> COALESCE(WI.RU_SERVICE_CONTRACT_END_DTM,CAST('3500/01/01 00:00:00' AS TIMESTAMP(0)))
     OR COALESCE(NSOLN.PERIODIC_BILLING_START_DT,CAST('3500/01/01' AS DATE))
			 <> COALESCE(WI.PERIODIC_BILLING_START_DT,CAST('3500/01/01' AS DATE))
     OR COALESCE(NSOLN.PERIODIC_BILLING_END_DT ,CAST('3500/01/01' AS DATE))  
		  <> COALESCE(WI.PERIODIC_BILLING_END_DT,CAST('3500/01/01' AS DATE))
       )
AND NSOLN.SS_CD<>'OPL';

UPDATE NSOLN
FROM $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT NSOLN, 
(SELECT 
WI_ACV.SALES_ORDER_LINE_KEY,
COALESCE(WI_ACV.TRANSACTIONAL_ACV_FLG,'N') AS TRANSACTIONAL_ACV_FLG, 
COALESCE(WI_ACV.ACV_FLG,'N') AS ACV_FLG,
COALESCE(WI_ACV.ANNUAL_TRANSACTIONAL_AMT,0) AS ANNUAL_TRANSACTIONAL_AMT,
SOURCE_COMMIT_DTM
FROM 
(SEL * FROM $$NRTSTGDB.WI_ORDER_LINES_EXT_NRT_CG1_PBL WHERE SALES_ORDER_LINE_KEY<> -7777
QUALIFY ROW_NUMBER() OVER( PARTITION BY LINE_ID ORDER BY SOURCE_COMMIT_DTM DESC) = 1) WI_ACV
) WI
SET 		 
	 ANNUAL_TRANSACTIONAL_AMT = WI.ANNUAL_TRANSACTIONAL_AMT,
     TRANSACTIONAL_ACV_FLG = WI.TRANSACTIONAL_ACV_FLG,	
     ACV_FLG = WI.ACV_FLG,
	 EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0),
	 EDW_UPDATE_USER = USER               
WHERE NSOLN.SALES_ORDER_LINE_KEY = WI.SALES_ORDER_LINE_KEY
AND   (    NSOLN.ANNUAL_TRANSACTIONAL_AMT <> WI.ANNUAL_TRANSACTIONAL_AMT
	    OR  NSOLN.TRANSACTIONAL_ACV_FLG<>WI.TRANSACTIONAL_ACV_FLG
        OR  NSOLN.ACV_FLG<>WI.ACV_FLG
	   )
AND NSOLN.SS_CD<>'OPL'
;

/* Commented below as part of SQ Net change removal - Day1 FY21 */
/* Added as part of December RTNR release */
/* DELETE FROM $$NRTSTGDB.WI_SUMMARY_QUOTE_SMC_1 ALL;

INSERT INTO $$NRTSTGDB.WI_SUMMARY_QUOTE_SMC_1
SELECT  
     NRT.SALES_ORDER_LINE_KEY, 
     WI.DV_EFFECTIVE_DTM, 
     CASE WHEN WI.SO_CNT > 1 THEN 'MIX' 
	      ELSE WI.SALES_MOTION_CD 
	  END SALES_MOTION_CD, 
     USER EDW_CREATE_USER, 
     WI.EDW_UPDATE_DTM EDW_CREATE_DTM 
FROM ( SELECT SALES_ORDER_LINE_KEY, 
	  SALES_MOTION_CD,
	  MAX(DV_EFFECTIVE_DTM) OVER(PARTITION BY SALES_ORDER_LINE_KEY) AS DV_EFFECTIVE_DTM, 
	  MAX(EDW_UPDATE_DTM) OVER(PARTITION BY SALES_ORDER_LINE_KEY) AS EDW_UPDATE_DTM, 
	  COUNT(*) OVER(PARTITION BY SALES_ORDER_LINE_KEY) SO_CNT,
	  SUM(DV_ALLOCATION_PCT) OVER(PARTITION BY SALES_ORDER_LINE_KEY) DV_ALLOCATION_PCT
         FROM 
		 (
		 SELECT
			SALES_ORDER_LINE_KEY,
			SALES_MOTION_CD,
			DV_EFFECTIVE_DTM,
			EDW_UPDATE_DTM,
			SUM(DV_ALLOCATION_PCT) OVER(PARTITION BY SALES_ORDER_LINE_KEY ) SUM_ALLOCATION_PCT,
			CAST( DV_ALLOCATION_PCT/SUM_ALLOCATION_PCT AS DECIMAL(18,6) ) AS DV_ALLOCATION_PCT	*/ /* Included inner query part to handle CS SQ scenario Sep 26 Q2FY20 Release */	  
		 /*FROM
		 $$SLSORDVWDB.MT_SUMMARY_QUOTE_SOL_ALLOC 
         WHERE DV_EXPIRATION_DTM = '3500-01-01 00:00:00'  
           AND  EDW_UPDATE_DTM > ( SELECT LAST_EXTRACT_DATE FROM $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES WHERE JOB_STREAM_ID = 'wf_N_SALES_ORDER_LINE_NRT_CG1' AND TABLE_NAME = 'WI_SUMMARY_QUOTE_SMC' ) 
		 ) WI  
) WI
INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL
ON NSOL.SALES_ORDER_LINE_KEY = WI.SALES_ORDER_LINE_KEY
INNER JOIN $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT_HIST_TV NRT
ON NRT.SK_SALES_ORDER_LINE_ID_INT = NSOL.SK_SO_LINE_ID_INT
AND NRT.SS_CD = NSOL.SS_CODE
AND NRT.END_TV_DTM = '3500-01-01 00:00:00'
INNER JOIN ( SELECT PROCESS_DT FROM $$NRTNCRVWDB.N_NRT_BKG_PROCESS_DT_CTRL WHERE SS_CD = 'CG' ) CTRL 
	      ON 1=1 
AND ( CASE WHEN ( CURRENT_TIMESTAMP(0) < ( CAST( CURRENT_DATE AS TIMESTAMP(0)) + INTERVAL '21:00:00' HOUR TO SECOND )) AND (CURRENT_DATE = CTRL.PROCESS_DT) THEN 'TRUE' 
		      WHEN ( CURRENT_TIMESTAMP(0) >= ( CAST( CURRENT_DATE AS TIMESTAMP(0)) + INTERVAL '21:00:00' HOUR TO SECOND )) AND (CURRENT_DATE +1 = CTRL.PROCESS_DT) THEN 'TRUE'
		      ELSE 'FALSE'
		  END ) = 'TRUE'    
WHERE ROUND(DV_ALLOCATION_PCT) = 1.00 
GROUP BY 1,2,3,4,5 ;

CALL COLLECT_STATS_WRAP('$$NRTSTGDB', 'WI_SUMMARY_QUOTE_SMC_1', 'D') ;

UPDATE NSOLN
 FROM $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT NSOLN, 
 ( SELECT SALES_ORDER_LINE_KEY, 
          SALES_MOTION_CD , 
          DV_EFFECTIVE_DTM 
    FROM $$NRTSTGDB.WI_SUMMARY_QUOTE_SMC_1 ) WI
SET SALES_MOTION_CD = WI.SALES_MOTION_CD ,
    EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0),
    EDW_UPDATE_USER = USER               
 WHERE NSOLN.SALES_ORDER_LINE_KEY = WI.SALES_ORDER_LINE_KEY 
AND NSOLN.SS_CD <> 'OPL';
 
 UPDATE EL 
FROM $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES EL, 
	 ( SELECT MAX(EDW_CREATE_DTM) MAX_UPD_DATE FROM $$NRTSTGDB.WI_SUMMARY_QUOTE_SMC_1 ) NSOL 
 SET LAST_EXTRACT_DATE = COALESCE(NSOL.MAX_UPD_DATE , EL.LAST_EXTRACT_DATE ) 
WHERE JOB_STREAM_ID = 'wf_N_SALES_ORDER_LINE_NRT_CG1'  
AND TABLE_NAME = 'WI_SUMMARY_QUOTE_SMC';
*/
/* Added as part of December RTNR release */
/* Commented above as part of SQ Net change removal - Day1 FY21 */
 
 /* START Added as part of Oct-2017 rel -  Modified for Dec 14 rel */
 
 UPDATE NSOLN
FROM $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT NSOLN, 
 ( SELECT SALES_ORDER_LINE_KEY, 
          SALES_MOTION_CD , 
          SOURCE_COMMIT_DTM 
    FROM $$NRTSTGDB.WI_ORDER_LINES_EXT_NRT_CG1_SMC 
    WHERE SALES_ORDER_LINE_KEY <> -7777
	/*AND SALES_ORDER_LINE_KEY NOT IN ( SELECT SALES_ORDER_LINE_KEY 
										FROM 
										(
										SELECT
										  SALES_ORDER_LINE_KEY,
										  SUM(DV_ALLOCATION_PCT) OVER(PARTITION BY SALES_ORDER_LINE_KEY ) SUM_ALLOCATION_PCT,
										  CAST( DV_ALLOCATION_PCT/SUM_ALLOCATION_PCT AS DECIMAL(18,6) ) AS DV_ALLOCATION_PCT */ /* Included inner query part to handle CS SQ scenario Sep 26 Q2FY20 Release */
										/* FROM
										$$SLSORDVWDB.MT_SUMMARY_QUOTE_SOL_ALLOC 
										WHERE DV_EXPIRATION_DTM = '3500-01-01 00:00:00' ) WI
										GROUP BY 1 HAVING ROUND(SUM(DV_ALLOCATION_PCT)) = 1.00 
										) */ /* Commented above as part of SQ Net change removal - Day1 FY21 */
	QUALIFY ROW_NUMBER() OVER( PARTITION BY LINE_ID ORDER BY SOURCE_COMMIT_DTM DESC) = 1 ) WI
SET SALES_MOTION_CD = WI.SALES_MOTION_CD ,
    EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0),
    EDW_UPDATE_USER = USER               
 WHERE NSOLN.SALES_ORDER_LINE_KEY = WI.SALES_ORDER_LINE_KEY 
 AND NSOLN.SALES_MOTION_CD <> WI.SALES_MOTION_CD 
AND NSOLN.SS_CD <> 'OPL';

 /* END Added as part of Oct-2017 rel - Modified for Dec 14 rel*/


 
UPDATE NSOLN
FROM $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT NSOLN, 
(SELECT 
SALES_ORDER_LINE_KEY,
CISCO_SHIPCONFIRM_DATE 
FROM $$NRTSTGDB.WI_ORDER_LINES_EXT_NRT_CG1_CSD WHERE SALES_ORDER_LINE_KEY<> -7777
QUALIFY ROW_NUMBER() OVER( PARTITION BY LINE_ID ORDER BY SOURCE_COMMIT_DTM DESC) = 1) WI
SET DD_SHPMNT_CONFIRMED_RESULT_CD=CASE WHEN WI.CISCO_SHIPCONFIRM_DATE IS NOT NULL THEN 'CONFIRMED' END ,
DD_SHIPMENT_CONFIRMED_DT = CAST(WI.CISCO_SHIPCONFIRM_DATE AS DATE FORMAT 'YYYY-MM-DD'), 
DD_SHIPMENT_CONFIRMED_DTM = WI.CISCO_SHIPCONFIRM_DATE, 
EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0),
EDW_UPDATE_USER = USER  
WHERE NSOLN.SALES_ORDER_LINE_KEY= WI.SALES_ORDER_LINE_KEY;




UPDATE A 
FROM   
$$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT  A,  
$$NRTNCRVWDB.N_SALES_ORDER_NRT B
SET 
SALES_ORDER_KEY =B.SALES_ORDER_KEY,
EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0),
EDW_UPDATE_USER = USER                
WHERE A.EP_HEADER_ID_INT= B.SK_SALES_ORDER_HEADER_ID_INT
AND B.SS_CD = A.SS_CD                     
AND A.SALES_ORDER_KEY=-7777;


UPDATE NSOLN
FROM 
$$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT NSOLN,
$$WORKDB.W_SALES_ORDER_LINE_NRT_CG1 WSOLNC
SET SO_LINE_TYPE_NAME = WSOLNC.SO_LINE_TYPE_NAME,
EDW_UPDATE_DTM=CURRENT_TIMESTAMP(0) /* Added as part of CR CHG0463914 */
WHERE WSOLNC.SALES_ORDER_LINE_KEY=NSOLN.SALES_ORDER_LINE_KEY 
AND NSOLN.ORIGINATED_QTC_VIA_CG1_FLG = 'N'
AND NSOLN.SO_LINE_TYPE_NAME <> WSOLNC.SO_LINE_TYPE_NAME;

UPDATE NSOLN
FROM $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT NSOLN, 
(SELECT 
SALES_ORDER_KEY,
ATTRIBUTE31 
FROM $$NRTSTGDB.WI_ORDER_HEADERS_EXT_NRT_CG1_C WHERE SALES_ORDER_KEY<> -7777
QUALIFY ROW_NUMBER() OVER( PARTITION BY HEADER_ID ORDER BY SOURCE_COMMIT_DTM DESC) = 1) WI
SET 
SO_LINE_TYPE_NAME = WI.ATTRIBUTE31, 
EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0),
EDW_UPDATE_USER = USER  
WHERE NSOLN.SALES_ORDER_KEY= WI.SALES_ORDER_KEY AND ORIGINATED_QTC_VIA_CG1_FLG='Y';

/* Start Added as part of Q3FY15 for Actual Shipment Date */
DELETE FROM $$NRTSTGDB.WI_SOL_NRT_ACTUAL_SHIP_DATE_2;

INSERT INTO $$NRTSTGDB.WI_SOL_NRT_ACTUAL_SHIP_DATE_2
SELECT
D.SALES_ORDER_LINE_KEY,
A.LINE_ID,
A.ORG_ID,
C.CMS_SOURCE_LINE_ID,
C.CMS_SOURCE_CODE,
B.ACTUAL_SHIPMENT_DATE,
CAST(B.ACTUAL_SHIPMENT_DATE AS DATE)
FROM $$NRTSTGDB.WI_SOL_NRT_ACTUAL_SHIP_DATE_1 A
INNER JOIN $$GGSRCVWDB.GG_CG1_OE_ORDER_LINES_ALL B
ON A.LINE_ID = B.LINE_ID
INNER JOIN $$GGSRCVWDB.GG_CG1_XXGCO_OE_ORD_LINES_EXT C
ON B.LINE_ID = C.LINE_ID
INNER JOIN $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT D
ON C.CMS_SOURCE_LINE_ID = D.SK_SALES_ORDER_LINE_ID_INT
AND CASE WHEN C.CMS_SOURCE_CODE = 'SJOE.CISCO.COM' THEN 'QTC' ELSE 'BV' END = D.SS_CD;

UPDATE A FROM $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT A, $$NRTSTGDB.WI_SOL_NRT_ACTUAL_SHIP_DATE_2 B
SET ACTUAL_SHIPMENT_DTM = B.ACTUAL_SHIPMENT_DTM,
DV_ACTUAL_SHIPMENT_DT = B.DV_ACTUAL_SHIPMENT_DT,
EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0)
WHERE A.SALES_ORDER_LINE_KEY = B.SALES_ORDER_LINE_KEY
AND A.ACTUAL_SHIPMENT_DTM <> B.ACTUAL_SHIPMENT_DTM
AND A.DV_ACTUAL_SHIPMENT_DT <> B.DV_ACTUAL_SHIPMENT_DT;


/* End as part of Q3FY15 for Actual Shipment Date */


--------------------------------------------------------------------------------------------------- Changes to be made in the ETL --------------------------

/* Need to comment the below Update Statement  as suggested by performance*/ 

/*ARAJANAL: ADDED AS PART OF XAAS Q4FY15*/
/*BEGIN*/

/*
UPDATE $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT
SET BOOKINGS_SOURCE_CD='SBP',
EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0),
EDW_UPDATE_USER = USER
WHERE RU_PARNT_SLS_ORDER_LINE_KEY IN
                (SELECT SALES_ORDER_LINE_KEY FROM $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT
                WHERE BOOKINGS_SOURCE_CD='SBP')
AND BOOKINGS_SOURCE_CD <> 'SBP'
*/

/*END*/

 CREATE VOLATILE TABLE  N_SALES_ORDER_LINE_NRT_V
 AS 
 ( SELECT     SALES_ORDER_LINE_KEY 
 FROM           $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT 
/*WHERE        BOOKINGS_SOURCE_CD = 'SBP') WITH DATA /*Q4FY16 XAAS  */ 
 WHERE        BOOKINGS_SOURCE_CD IN ('TSL', 'SBP')) WITH DATA  
 PRIMARY INDEX (SALES_ORDER_LINE_KEY)
 ON COMMIT PRESERVE ROWS;
 
COLLECT STATS ON N_SALES_ORDER_LINE_NRT_V COLUMN (SALES_ORDER_LINE_KEY);

 UPDATE  $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT 
 SET   
  BOOKINGS_SOURCE_CD = 'SBP' , 
  EDW_UPDATE_DTM = CURRENT_TIMESTAMP( 0 ) ,
  EDW_UPDATE_USER = USER 
 WHERE 
  RU_PARNT_SLS_ORDER_LINE_KEY IN 
  ( 
  /*    SELECT SALES_ORDER_LINE_KEY FROM N_SALES_ORDER_LINE_NRT_V  /*Q4FY16 XAAS  */
   SELECT SALES_ORDER_LINE_KEY FROM N_SALES_ORDER_LINE_NRT_V   WHERE        BOOKINGS_SOURCE_CD IN ('SBP')   
  ) 
 AND   BOOKINGS_SOURCE_CD <> 'SBP';  
 
 /*Q4FY16 XAAS  */ 
   UPDATE  $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT 
 SET   
  BOOKINGS_SOURCE_CD = 'TSL' , 
  EDW_UPDATE_DTM = CURRENT_TIMESTAMP( 0 ) ,
  EDW_UPDATE_USER = USER 
 WHERE  
  RU_PARNT_SLS_ORDER_LINE_KEY IN 
  ( 
   SELECT SALES_ORDER_LINE_KEY FROM N_SALES_ORDER_LINE_NRT_V  WHERE        BOOKINGS_SOURCE_CD IN ('TSL')  
  ) 
 AND   BOOKINGS_SOURCE_CD <> 'TSL';