


Source1 Name : SQ_OPL_XXGCO_RTR_ATTRIBUTION


Pre SQL : 



SQL Query : 
SELECT 
 RTR_ATTRIBUTION_ID,
 TRX_ID,
 TRX_VERSION,
 ATTRIBUTED_EXT_NET_PRICE,
 ATTRIBUTED_UNIT_NET_PRICE,
 ATTRIBUTED_PERCENTAGE,
 ATTRIBUTED_QUANTITY,
 ENTERPRISE_SKU_INV_ITM_ID,
 COVERED_PRD_INV_ITM_ID,
 AS_PARENT_SKU_INV_ITM_ID,
 ARCHITECTURE_ID,
 TECHNOLOGY_ID,
 COALESCE(TXN_CR_PARTY_ID,-999) AS TXN_CR_PARTY_ID,
 COALESCE(CAST(CAST(START_DATE AS VARCHAR(19) )AS TIMESTAMP(0)),CAST('1900-01-01 00:00:00' AS TIMESTAMP(0))) AS START_DATE,
 COALESCE(CAST(CAST(END_DATE AS  VARCHAR(19)) AS TIMESTAMP(0)),CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))) AS END_DATE,
 ERP_HEADER_ID,
 COALESCE(ERP_LINE_ID,-9999) AS ERP_LINE_ID,
 ERP_SO_NUMBER,
 ORDER_NUMBER,
 LINE_REF_NUMBER,
 INSTALL_SITE_LOCATION,
 QUOTE_LINE_ID,
 QUOTE_NUMBER,
 SALES_MOTION,
 SALES_MOTION_CONTEXT,
 AS_TS_FLAG,
 -999 AS RENEW_CLE_ID,
 ITEM_CATEGORIZATION,
 COALESCE (RECGD_PERCENTAGE,0),
 COALESCE (RECGD_ATTRIB_EXT_NET_PRICE, 0),
 'OPL' SS_CD,
 COALESCE(OA_ATTRIBUTION_ID, -9999),
 OFFER_TYPE_ID,
 TD_COMMIT_TIME,
 ATTR_PRDT_CLASS_NAME,
 COALESCE(HQ_CR_PARTY_ID,-999) AS HQ_CR_PARTY_ID ,
 COALESCE(RENEWAL_REF_TYPE,'UNKNOWN') AS RENEWAL_REF_TYPE,
 COALESCE(RENEWAL_REF_VALUE,'UNKNOWN') AS RENEWAL_REF_VALUE,
 COALESCE(REASON_CODE,'UNKNOWN') AS REASON_CODE,
 'UNKNOWN' AS SALES_MOTION_TIMING,
 COALESCE(MANUAL_PROCESS_FLAG,'N'),          
 COALESCE(USER_ID,'UNKNOWN'),                       
 COALESCE(CASE_NUMBER,'UNKNOWN'),                   
 COALESCE(COMMENTS,'UNKNOWN')                      
 FROM
 $$NRTACCUMVWDB.OPL_XXGCO_RTR_ATTRIBUTION
 QUALIFY RANK() OVER (PARTITION BY TRX_ID ORDER BY TRX_VERSION DESC)=1
 WHERE
 TD_COMMIT_TIME >= CAST('$$LastExtractDate'  AS TIMESTAMP(0))  -  INTERVAL '1' MINUTE


Post SQL : 



Target1 Name : ST_OPL_XXGCO_RTR_ATTRIBUTION


Pre SQL : 
DELETE FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIBUTION;


Post SQL : 
DELETE FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIBUTION
WHERE ( ENTERPRISE_SKU_INV_ITM_ID IS NULL OR ATTRIBUTED_EXT_NET_PRICE IS NULL OR ATTRIBUTED_UNIT_NET_PRICE IS NULL ) ;

CALL COLLECT_STATS_WRAP('$$STGDB','ST_OPL_XXGCO_RTR_ATTRIBUTION','D');