


Source1 Name : SQ_ST_OPL_XXGCO_RTR_ATTRIB_CV


Pre SQL : 



SQL Query : 
SELECT
RECORD_OFFSET
,RTR_ATTRIBUTION_ID
,TRX_ID
,TRX_VERSION
,ATTRIBUTED_EXT_NET_PRICE
,ATTRIBUTED_UNIT_NET_PRICE
,ATTRIBUTED_PERCENTAGE
,ATTRIBUTED_QUANTITY
,ENTERPRISE_SKU_INV_ITM_ID
,COVERED_PRD_INV_ITM_ID
,AS_PARENT_SKU_INV_ITM_ID
,ARCHITECTURE_ID
,TECHNOLOGY_ID
,COALESCE(TXN_CR_PARTY_ID,-999) AS TXN_CR_PARTY_ID
,ERP_HEADER_ID
,ERP_LINE_ID
,ERP_SO_NUMBER
,ORDER_NUMBER
,LINE_REF_NUMBER
,SALES_MOTION
,SALES_MOTION_CONTEXT
,AS_TS_FLAG
,ITEM_CATEGORIZATION
,COALESCE(RECGD_ATTRIB_EXT_NET_PRICE,0)
,COALESCE(RECGD_PERCENTAGE,0)
,'OPL' AS SS_CD
,COALESCE(OA_ATTRIBUTION_ID,-9999)
,OFFER_TYPE_ID
,LIST_PRICE
,ATTR_PRDT_CLASS_NAME
,COALESCE(HQ_CR_PARTY_ID,-999) AS HQ_CR_PARTY_ID
,COALESCE(RENEWAL_REF_TYPE,'UNKNOWN') AS RENEWAL_REF_TYPE
,COALESCE(RENEWAL_REF_VALUE,'UNKNOWN') AS RENEWAL_REF_VALUE
,COALESCE(REASON_CODE,'UNKNOWN') AS REASON_CODE
,'UNKNOWN' AS SALES_MOTION_TIMING
,COALESCE(MANUAL_PROCESS_FLAG,'N')
,COALESCE(USER_ID,'UNKNOWN')
,COALESCE(CASE_NUMBER,'UNKNOWN')
,COALESCE(COMMENTS,'UNKNOWN')
,SMR_SALES_VALUE
,SMR_ACV_AMOUNT
,SMR_TCV_AMOUNT
,PRODUCT_CLASS
,-999 AS RENEW_CLE_ID
,MANUAL_OVERRIDE_FLAG
,LINE_EXTENDED_PRICE
,EDW_CREATE_DTM
,PARTITION_NUMBER
,TOPIC_NAME
,INSTALL_SITE_LOCATION
FROM
$$STGDB.OPL_XXGCO_RTR_ATTRIBUTION_CV
QUALIFY RANK() OVER (PARTITION BY TRX_ID ORDER BY TRX_VERSION DESC)=1
WHERE
EDW_CREATE_DTM >= CAST('$$LastExtractDate'  AS TIMESTAMP(0))  -  INTERVAL '1' MINUTE


Post SQL : 



Target1 Name : ST_OPL_XXGCO_RTR_ATTRIB_CV


Pre SQL : 
DELETE FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV;


Post SQL : 
DELETE FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV
WHERE ( ENTERPRISE_SKU_INV_ITM_ID IS NULL OR ATTRIBUTED_EXT_NET_PRICE IS NULL OR ATTRIBUTED_UNIT_NET_PRICE IS NULL ) ;

CALL COLLECT_STATS_WRAP('$$STGDB','ST_OPL_XXGCO_RTR_ATTRIB_CV','D');