


Source1 Name : SQ_ST_XAAS_XXOA_ORDER_ATTRIB_NRT


Pre SQL : 



SQL Query : 
SELECT 
     1 AS BATCH_ID,
    CXOA.ATTRIBUTION_ID, 
    --CXOA.ORDER_NUMBER, 
    COALESCE(CXOA.LINE_REF_NUMBER,-999), 
    COALESCE(CXOA.DATA_SOURCE,'UNK'), 
    CXOA.TRX_ID, 
    CXOA.PARENT_TRX_ID, 
    --CXOA.ORDERED_ITEM, 
   COALESCE(CXOA.INVENTORY_ITEM_ID,-999), 
    COALESCE(CXOA.ATTRIBUTION_FLAG,'N'), 
    --CXOA.CISCO_BOOKED_FLAG, 
    CXOA.BUNDLE_TYPE, 
    COALESCE(CXOA.QUANTITY,0), 
    CXOA.ATTRIBUTED_UNIT_LIST_PRICE, 
    CXOA.ATTRIBUTED_UNIT_NET_PRICE, 
    CXOA.RECOGNIZED_PCT, 
    CXOA.ATTRIBUTED_PCT, 
    --CXOA.PUBLISH_FLAG, 
    CXOA.ATTRIBUTION_TYPE, 
    --CXOA.CREATED_BY, 
    --CXOA.CREATION_DATE, 
    --CXOA.LAST_UPDATED_BY, 
    --CXOA.LAST_UPDATE_DATE, 
    --CXOA.ORIG_OA_ATTRIB_ID,
    'I' AS ACTION_CODE,
    CURRENT_TIMESTAMP(0) AS CREATE_DATETIME,
    --CXOA.SOURCE_DML_TYPE, 
    
    CXOA.EXCEPTION_CODE,
    --CXOA.REFRESH_DATETIME,
    CXOA.ATTRIBUTED_EXT_LIST_PRICE ,
    CXOA.ATTRIBUTED_EXT_NET_PRICE ,
    CXOA.WEB_ORDER_ID,
    --CXOA.SUBSCRIPTION_CODE,
    CXOA.ATTRIBUTED_SALES_VALUE,
    CXOA.ATTRIBUTED_MRR,
    CXOA.ATTRIBUTED_IMRR,
    CXOA.ATTRIBUTED_ARR,
    CXOA.ATTRIBUTED_NRR,
    CXOA.ATTRIBUTED_IARR,
    CXOA.ATTRIBUTED_IMYARR,
    CXOA.TCV,
    CXOA.ATTRIBUTION_CODE,
    CXOA.LINKED_ATTRIB_ID,
    CXOA.EXCEPTION_DETAIL, 
    CXOA.ENT_INVENTORY_ITEM_ID,
  CXOA.PARENT_SUB_SKU_OFFSET_ID     , 
  CXOA.PARENT_SUB_SKU_ID        ,     
  CXOA.MULTI_OA_BUNDLE_ENABLED  ,     
  CXOA.ATTRIBUTION_DETAILS      ,
    CXOA.PARENT_LINE_REF_NUMBER,
    CXOA.ATTRIBUTED_ITEM,
    CXOA.RECOGNIZED_ATTR_SALES_VALUES,
    CXOA.RECOGNIZED_ATTR_TCV,
    CXOA.BOOKING_VERSION,
    CXOA.ERP_LINE_ID,
    CXOA.ERP_PARENT_LINE_ID,
    cast(cast(CREATION_DATE  as varchar(19)) as timestamp(0)),
    cast(cast(EDW_CREATE_DTM as varchar(19)) as timestamp(0)),  
    ACV_ATTRIBUTION_PCT,
	CXOA.PRICING_TERM         /* SIGORANT ADDED AS PART OF Q2FY19 */
    FROM
    $$STGDB.ST_SI_XXOA_ORDER_ATTRIB CXOA
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ATTRIBUTION_ID ORDER BY EDW_CREATE_DTM DESC)=1
    WHERE   
    --SOURCE_DML_TYPE IN ( 'SQL COMPUPDATE','INSERT')
     --AND PUBLISH_FLAG='Y'
  (DATA_SOURCE IN ('TSL','NGCCRM') OR (DATA_SOURCE IN ('OPL') AND ATTRIBUTION_TYPE IN ('BOOKING'))) 
     --AND TRX_USAGE_CODE='R' AND  TRX_TYPE_CODE='B'
     AND EDW_CREATE_DTM  >= '$$LastExtractDate'
	 /* AND CXOA.ATTRIBUTION_CODE NOT IN ('DEAL ATTRIBUTED SUB SKU','DEAL OFFSET MULTI LEVEL SUB SKU') */ /* Q1FY20 Commenting to allow AS ARCH SKUS in regular flow */
     AND EDW_CREATE_DTM  <=(  /*Incremental Extraction based on 9 TO 9 Logic*/
         SELECT 
          CASE 
          WHEN A.DAY_MAX_SOURCE_COMMIT_TIME IS NULL THEN NULL
    WHEN A.NEXT_DAY_SRC_COMMIT_TIME IS NOT NULL AND A.CNT <> 0 THEN B.PROCESS_END_DTM
          WHEN  A.DAY_MAX_SOURCE_COMMIT_TIME <B.PROCESS_END_DTM  
          THEN A.DAY_MAX_SOURCE_COMMIT_TIME 
          ELSE B.PROCESS_END_DTM  
          END  END_LAST_EXTRACT_DATE
         FROM $$NRTSTGDB.ST_XAAS_BKG_INCR_DT_CTRL_NRT A,
              $$ETLVWDB.EL_XAAS_BKG_PRCS_DT_CTRL_NRT B
         WHERE A.JOB_STREAM_ID = 'wf_ST_XAAS_XXOA_ORDER_ATTRIB_NRT'
         AND B.SS_CD='XAAS')


Post SQL : 



Target1 Name : ST_XAAS_XXOA_ORDER_ATTRIB_NRT1


Pre SQL : 
DELETE FROM $$NRTSTGDB.ST_XAAS_XXOA_ORDER_ATTRIB_NRT ALL;


Post SQL : 
COLLECT STATS $$NRTSTGDB.ST_XAAS_XXOA_ORDER_ATTRIB_NRT;