


Source1 Name : SQ_CG1_XXOA_ORDER_ATTRIB


Pre SQL : 



SQL Query : 
SELECT 
  1 AS BATCH_ID,
  CXOA.OA_ATTRIB_ID, 
  CXOA.ORDER_NUMBER, 
  CXOA.HEADER_ID, 
  CXOA.DATA_SOURCE, 
  CXOA.LINE_ID, 
  CXOA.PARENT_LINE_ID, 
  CXOA.ORDERED_ITEM, 
  CXOA.INVENTORY_ITEM_ID, 
  CXOA.ATTRIBUTION_FLAG, 
  CXOA.CISCO_BOOKED_FLAG, 
  CXOA.BUNDLE_TYPE, 
  CXOA.QUANTITY, 
  CXOA.ATTRIBUTED_UNIT_LIST_PRICE, 
  CXOA.ATTRIBUTED_UNIT_NET_PRICE, 
  CXOA.BOOKINGS_PCT, 
  CXOA.ATTRIBUTED_PCT, 
  CXOA.PUBLISH_FLAG, 
  CXOA.TRX_TYPE, 
  CXOA.CREATED_BY, 
  CXOA.CREATION_DATE, 
  CXOA.LAST_UPDATED_BY, 
  CXOA.LAST_UPDATE_DATE, 
  CXOA.ORIG_OA_ATTRIB_ID,
  'I' AS ACTION_CODE,
  CURRENT_TIMESTAMP(0) AS CREATE_DATETIME,
  'CG' AS GLOBAL_NAME,
  CXOA.SOURCE_DML_TYPE, 
  CXOA.SOURCE_COMMIT_TIME,
  CXOA.EXCEPTION_CODE,/*Added this column as part of Q2FY15*/
  CXOA.REFRESH_DATETIME, /*Propogating this Attribute to Stage as part of OA_CR_JAN_FY15*/
  CXOA.ATTRIBUTION_CODE, /* Added as part of OA - Q1FY16*/
  CXOA.EXCEPTION_DETAIL, /* Added as part of OA - Q1FY16*/
  CXOA.ENT_INVENTORY_ITEM_ID,/*thvarghe :Added as part of OA - JUNE-CDR-FY16*/
  CXOA.ATTRIB_ID  /*prmaddal: Added as part of OA - Q1FY17*/
  ,CXOA.PARENT_SUB_SKU_OFFSET_ID   /* 3 NRS MPOB columns added*/
  ,CXOA.PARENT_SUB_SKU_ID 
  ,CXOA.MULTI_OA_BUNDLE_ENABLED
  ,CXOA.ATTRIBUTION_DETAILS
  /*ADDED AS PART OF Q1FY21 ACV SCOPE*/
  ,CXOA.ACV_FLAG
  ,CXOA.ACV_ELIGIBILITY_FLAG AS ACV_ELIGIBLE_FLAG  
  ,CXOA.ACV_AMOUNT
  /* END OF Q1FY21 ACV SCOPE*/
  FROM
  $$NRTACCUMVWDB.CG1_XXOA_ORDER_ATTRIB CXOA
  WHERE 
  CXOA.DATA_SOURCE  NOT IN ('SBP','TSL')  /* Added to restrict XaaS data OA-Q1FY16*/
  AND SOURCE_COMMIT_TIME >= '$$LastExtractDate'/*OA_CR_JAN_FY15 added equalto operator in the incremental condition*/
  /* Capturing DELETE OA records Q1FY15 - OA*/
 AND (  (SOURCE_DML_TYPE IN ( 'SQL COMPUPDATE','INSERT','DELETE')  AND PUBLISH_FLAG='Y') 
   OR  (SOURCE_DML_TYPE ='DELETE'  AND PUBLISH_FLAG ='N')
      )
 /* AND CXOA.ATTRIBUTION_CODE NOT IN ('DEAL ATTRIBUTED SUB SKU','DEAL OFFSET MULTI LEVEL SUB SKU') */ /* Q1FY20 dbommise: Commenting to allow AS ARCH SKUs in Regular OA FLOW */
   /* Implementing 9 to 9 logic   CR-Q1FY16 --OA */
  AND SOURCE_COMMIT_TIME <( 
        SELECT 
         CASE 
         WHEN A.DAY_MAX_SOURCE_COMMIT_TIME IS NULL THEN NULL
   WHEN A.NEXT_DAY_SRC_COMMIT_TIME IS NOT NULL AND A.CNT <> 0 THEN B.PROCESS_END_DTM
         WHEN  A.DAY_MAX_SOURCE_COMMIT_TIME <B.PROCESS_END_DTM  THEN A.DAY_MAX_SOURCE_COMMIT_TIME 
         ELSE B.PROCESS_END_DTM  
         END  END_LAST_EXTRACT_DATE
        FROM $$NRTSTGDB.ST_CG_NRT_BKG_INCR_DT_CTRL A,
          $$NRTNCRVWDB.N_NRT_BKG_PROCESS_DT_CTRL  B
        WHERE A.JOB_STREAM_ID = 'wf_ST_CG1_XXOA_ORDER_ATTRIB'
        AND B.SS_CD='CG')  
  /* SOURCE_COMMIT_TIME DESC is added in ORDER BY clause - OA Q1FY15*/
  /*QUALIFY ROW_NUMBER () OVER (PARTITION BY OA_ATTRIB_ID ORDER BY REFRESH_DATETIME DESC, SOURCE_COMMIT_TIME DESC)=1  */


Post SQL : 



Target1 Name : ST_CG1_XXOA_ORDER_ATTRIB


Pre SQL : 
DELETE FROM $$NRTSTGDB.ST_CG1_XXOA_ORDER_ATTRIB ALL;


Post SQL : 
