


Source1 Name : SQ_XXOTM_PHX_TRX_SC


Pre SQL : 
DELETE FROM $$STGDB.ST_XXOTM_PHX_TRX_SC_NRT ALL;


SQL Query : 
SELECT
CASE WHEN TRX_SC_ID>2147483647 THEN 2147483647-TRX_SC_ID ELSE TRX_SC_ID END TRX_SC_ID,   /* ADDED BY UMA BIGINT CHANGE */
TRX_ID,                        
/*SC_ID,  */
CASE WHEN SC_ID>2147483647 THEN 2147483647-SC_ID ELSE SC_ID END SC_ID,                        
SC_SEQUENCE,                   
TRX_SPLIT_ID,                  
TOTAL_SPLIT_PERCENT,           
SC_SPLIT_PERCENT,              
TRX_SPLIT_PERCENT,             
LATEST_SC_FLAG,                
PARENT_CHILD_FLAG,             
OTM_BATCH_ID,                  
OBJECT_VERSION_NUMBER,         
COALESCE(TRX_SC.SC_DUPLICATE_FLAG,'N') AS SC_DUPLICATE_FLAG,              
CREATION_DATE,                 
CREATED_BY,                    
LAST_UPDATE_DATE,              
LAST_UPDATED_BY,               
LAST_UPDATE_LOGIN,  
COALESCE(START_DATE,TIMESTAMP '1900-01-01 00:00:00' ) AS START_DATE,
COALESCE(EXPIRATION_DATE,TIMESTAMP '3500-01-01 00:00:00') AS EXPIRATION_DATE,
SOURCE_DML_TYPE,               
SOURCE_COMMIT_TIME
FROM 
( SELECT * FROM $$NRTACCUMVWDB.XXOTM_PHX_TRX_SC
  WHERE SOURCE_COMMIT_TIME >= CAST('$$LastExtractDate' AS TIMESTAMP(0))
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TRX_SC_ID ORDER BY REFRESH_DATETIME DESC)=1) TRX_SC


Post SQL : 
COLLECT STATS ON $$STGDB.ST_XXOTM_PHX_TRX_SC_NRT;


Target1 Name : ST_XXOTM_PHX_TRX_SC_NRT


Pre SQL : 



Post SQL : 
