


Source1 Name : SQ_WI_AR_NAPLD_RTR


Pre SQL : 



SQL Query : 
SELECT EL.AR_TRX_KEY,
	   EL.DEAL_ID,
	   CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM
FROM $$ETLVWDB.EL_AR_NAPLD_SMC_DENORM EL
WHERE EL.END_TV_DTM = '3500-01-01 00:00:00'
AND EXISTS 
	(
		SELECT 1
		FROM
			( 
			SELECT AR_TRX_KEY
				FROM $$ETLVWDB.EL_AR_NAPLD_SMC_DENORM EL_INNER
				WHERE EXISTS 
				   (
						SELECT 1
						FROM 
						( SELECT SALES_ORDER_LINE_KEY
							FROM $$SLSORDVWDB.MT_RTNR_SMC_ALLOCATION SMC_ALLOC
							WHERE SMC_ALLOC.EDW_UPDATE_DTM >= '$$LastExtractDate'
						) SMC_ALLOC
					WHERE EL_INNER.SALES_ORDER_LINE_KEY = SMC_ALLOC.SALES_ORDER_LINE_KEY
					)
	
			) EL_INCR
	WHERE EL.AR_TRX_KEY = EL_INCR.AR_TRX_KEY
	)
GROUP BY 1,2,3


Post SQL : 



Target1 Name : WI_AR_NAPLD_RTR


Pre SQL : 
DELETE FROM $$STGDB.WI_AR_NAPLD_RTR ;


Post SQL : 
CALL COLLECT_STATS_WRAP ( '$$STGDB','WI_AR_NAPLD_RTR','D' ) ;