


Source1 Name : SQ_ST_OPL_XXGCO_RTR_ATTRIB_CV


Pre SQL : 
CREATE MULTISET VOLATILE TABLE ST_OPL_XXGCO_RTR_ATTRIB_CV_SET_CV 
 AS 
 (
 SEL * FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV ST
 QUALIFY ROW_NUMBER() OVER(PARTITION BY RTR_ATTRIBUTION_ID, OA_ATTRIBUTION_ID, SS_CD ORDER BY EDW_CREATE_DTM DESC ) = 1
 ) WITH DATA ON COMMIT PRESERVE ROWS;
 
 
 COLLECT STATISTICS COLUMN ( RTR_ATTRIBUTION_ID,OA_ATTRIBUTION_ID )ON ST_OPL_XXGCO_RTR_ATTRIB_CV_SET_CV;
 
 DELETE FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV;
 
 INSERT INTO $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV
 SELECT * FROM ST_OPL_XXGCO_RTR_ATTRIB_CV_SET_CV
GROUP BY RECORD_OFFSET ,RTR_ATTRIBUTION_ID ,TRX_ID,TRX_VERSION,ATTRIBUTED_EXT_NET_PRICE,ATTRIBUTED_UNIT_NET_PRICE ,ATTRIBUTED_PERCENTAGE
,ATTRIBUTED_QUANTITY,ENTERPRISE_SKU_INV_ITM_ID ,COVERED_PRD_INV_ITM_ID ,AS_PARENT_SKU_INV_ITM_ID,ARCHITECTURE_ID
,TECHNOLOGY_ID,TXN_CR_PARTY_ID,ERP_HEADER_ID,ERP_LINE_ID,ERP_SO_NUMBER,ORDER_NUMBER ,LINE_REF_NUMBER,SALES_MOTION 
,SALES_MOTION_CONTEXT ,AS_TS_FLAG ,ITEM_CATEGORIZATION,RECGD_ATTRIB_EXT_NET_PRICE,RECGD_PERCENTAGE,SS_CD ,OA_ATTRIBUTION_ID
,OFFER_TYPE_ID,LIST_PRICE ,ATTR_PRDT_CLASS_NAME ,HQ_CR_PARTY_ID ,RENEWAL_REF_TYPE,RENEWAL_REF_VALUE,REASON_CODE,SALES_MOTION_TIMING
,MANUAL_PROCESS_FLAG,USER_ID ,CASE_NUMBER,COMMENTS,SMR_SALES_VALUE,SMR_ACV_AMOUNT ,SMR_TCV_AMOUNT ,PRODUCT_CLASS,RENEW_CLE_ID 
,MANUAL_OVERRIDE_FLAG ,LINE_EXTENDED_PRICE,EDW_CREATE_DTM ,PARTITION_NUMBER,TOPIC_NAME ,INSTALL_SITE_LOCATION,
POS_TRANSACTION_ID_INT,
ORDER_ORIGIN_CD,
SK_TRX_ID_INT,
SK_OPL_HEADER_ID_INT ,RENEWAL_ERP_REF_VALUE;


SQL Query : 
SELECT
 RECORD_OFFSET,
 RTR_ATTRIBUTION_ID,
 TRX_ID,
 TRX_VERSION,
 ATTRIBUTED_EXT_NET_PRICE,
 ATTRIBUTED_UNIT_NET_PRICE,
 ATTRIBUTED_PERCENTAGE,
 ATTRIBUTED_QUANTITY,
 ENTERPRISE_SKU_INV_ITM_ID,
 COVERED_PRD_INV_ITM_ID,
 AS_PARENT_SKU_INV_ITM_ID,
 ARCHITECTURE_ID,
 TECHNOLOGY_ID,
 TXN_CR_PARTY_ID,
 ERP_HEADER_ID,
 ERP_LINE_ID,
 ERP_SO_NUMBER,
 ORDER_NUMBER,
 LINE_REF_NUMBER,
 SALES_MOTION,
 SALES_MOTION_CONTEXT,
 AS_TS_FLAG,
 ITEM_CATEGORIZATION,
 RECGD_ATTRIB_EXT_NET_PRICE,
 RECGD_PERCENTAGE,
 SS_CD,
 OA_ATTRIBUTION_ID,
 OFFER_TYPE_ID,
 LIST_PRICE,
 ATTR_PRDT_CLASS_NAME,
 HQ_CR_PARTY_ID,
 RENEWAL_REF_TYPE,
 RENEWAL_REF_VALUE,
 REASON_CODE,
 SALES_MOTION_TIMING,
 MANUAL_PROCESS_FLAG,
 USER_ID,
 CASE_NUMBER,
 COMMENTS,
 SMR_SALES_VALUE,
 SMR_ACV_AMOUNT,
 SMR_TCV_AMOUNT,
 PRODUCT_CLASS,
 RENEW_CLE_ID,
 MANUAL_OVERRIDE_FLAG,
 LINE_EXTENDED_PRICE,
 EDW_CREATE_DTM,
 PARTITION_NUMBER,
 TOPIC_NAME,
 INSTALL_SITE_LOCATION,
 POS_TRANSACTION_ID_INT,
 ORDER_ORIGIN_CD,
SK_TRX_ID_INT,
SK_OPL_HEADER_ID_INT,
RENEWAL_ERP_REF_VALUE
FROM $$EXCEPDB.EX_OPL_XXGCO_RTR_ATTRIB_CV EX
WHERE EX.EXCEPTION_TYPE = 'RI' 
AND ORDER_ORIGIN_CD <> 'DISTI-DSV'
AND NOT EXISTS (  SELECT 1 FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV ST  WHERE ST.TRX_ID= EX.TRX_ID  AND ST.ORDER_ORIGIN_CD <> 'DISTI-DSV')
UNION ALL
SELECT
 RECORD_OFFSET,
 RTR_ATTRIBUTION_ID,
 TRX_ID,
 TRX_VERSION,
 ATTRIBUTED_EXT_NET_PRICE,
 ATTRIBUTED_UNIT_NET_PRICE,
 ATTRIBUTED_PERCENTAGE,
 ATTRIBUTED_QUANTITY,
 ENTERPRISE_SKU_INV_ITM_ID,
 COVERED_PRD_INV_ITM_ID,
 AS_PARENT_SKU_INV_ITM_ID,
 ARCHITECTURE_ID,
 TECHNOLOGY_ID,
 TXN_CR_PARTY_ID,
 ERP_HEADER_ID,
 ERP_LINE_ID,
 ERP_SO_NUMBER,
 ORDER_NUMBER,
 LINE_REF_NUMBER,
 SALES_MOTION,
 SALES_MOTION_CONTEXT,
 AS_TS_FLAG,
 ITEM_CATEGORIZATION,
 RECGD_ATTRIB_EXT_NET_PRICE,
 RECGD_PERCENTAGE,
 SS_CD,
 OA_ATTRIBUTION_ID,
 OFFER_TYPE_ID,
 LIST_PRICE,
 ATTR_PRDT_CLASS_NAME,
 HQ_CR_PARTY_ID,
 RENEWAL_REF_TYPE,
 RENEWAL_REF_VALUE,
 REASON_CODE,
 SALES_MOTION_TIMING,
 MANUAL_PROCESS_FLAG,
 USER_ID,
 CASE_NUMBER,
 COMMENTS,
 SMR_SALES_VALUE,
 SMR_ACV_AMOUNT,
 SMR_TCV_AMOUNT,
 PRODUCT_CLASS,
 RENEW_CLE_ID,
 MANUAL_OVERRIDE_FLAG,
 LINE_EXTENDED_PRICE,
 EDW_CREATE_DTM,
 PARTITION_NUMBER,
 TOPIC_NAME,
 INSTALL_SITE_LOCATION,
 POS_TRANSACTION_ID_INT,
 ORDER_ORIGIN_CD,
SK_TRX_ID_INT,
SK_OPL_HEADER_ID_INT,
RENEWAL_ERP_REF_VALUE
FROM $$EXCEPDB.EX_OPL_XXGCO_RTR_ATTRIB_CV EX
WHERE EX.EXCEPTION_TYPE = 'RI' 
AND ORDER_ORIGIN_CD = 'DISTI-DSV'
AND NOT EXISTS ( SELECT 1 FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV ST WHERE ST.POS_TRANSACTION_ID_INT= EX.POS_TRANSACTION_ID_INT  AND ST.ORDER_ORIGIN_CD = 'DISTI-DSV' )


Post SQL : 



Target1 Name : ST_OPL_XXGCO_RTR_ATTRIB_CV


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','ST_OPL_XXGCO_RTR_ATTRIB_CV','D');


Source2 Name : SQ_SM_ATTR_PRDT_NEW_RNWL_ACV


Pre SQL : 



SQL Query : 
SELECT
  SM.MAX_RTR_KEY + RANK() OVER (ORDER BY RTR_ATTRIBUTION_ID, OA_ATTRIBUTION_ID, SS_CD) AS ATTR_PRDT_AS_NEW_OR_RNWL_KEY
  ,DT.RTR_ATTRIBUTION_ID AS SK_RTR_ATTRIBUTION_ID
  ,DT.SS_CD
  ,DT.OA_ATTRIBUTION_ID AS SK_ATTRIBUTION_ID_INT
  ,CURRENT_TIMESTAMP(0) EDW_CREATE_DTM
  ,USER EDW_CREATE_USER
FROM (
    SELECT RTR_ATTRIBUTION_ID, OA_ATTRIBUTION_ID, SS_CD
      FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV ST
     WHERE NOT EXISTS
     ( SELECT SK_RTR_ATTRIBUTION_ID , SK_ATTRIBUTION_ID_INT, SS_CD
         FROM $$ETLVWDB.SM_ATTR_PRDT_NEW_RNWL_ACV SM
     WHERE ST.RTR_ATTRIBUTION_ID = SM.SK_RTR_ATTRIBUTION_ID
  AND ST.OA_ATTRIBUTION_ID = SM.SK_ATTRIBUTION_ID_INT
  AND ST.SS_CD = SM.SS_CD
      )
    GROUP BY 1,2,3  
  ) DT,
(
SELECT COALESCE(MAX(ATTR_PRDT_AS_NEW_OR_RNWL_KEY),0)  MAX_RTR_KEY
FROM ( SEL ATTR_PRDT_AS_NEW_OR_RNWL_KEY FROM $$ETLVWDB.SM_ATTR_PRDT_NEW_RNWL_ACV
UNION SEL ATTR_PRDT_AS_NEW_OR_RNWL_KEY FROM $$ETLVWDB.SM_ATTR_PRDT_AS_NEW_OR_RNWL
UNION SEL ATTR_PRDT_AS_NEW_OR_RNWL_KEY  FROM $$ETLVWDB.SM_ATTR_PRDT_NEW_RNWL_BUNDLE
) WI
) SM


Post SQL : 



Target2 Name : SM_ATTR_PRDT_NEW_RNWL_ACV


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$TRANSLATIONDB','SM_ATTR_PRDT_NEW_RNWL_ACV','D');


Source3 Name : SQ_WI_OPL_XXGCO_RTR_ATTRIB_CV1


Pre SQL : 



SQL Query : 
SELECT
     SMXSS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
     ST.RTR_ATTRIBUTION_ID AS SK_RTR_ATTRIBUTION_ID,
     NPA.ITEM_KEY AS ATTR_PRDT_KEY,
	 NSOL.SALES_ORDER_LINE_KEY,
	 COALESCE(NPHQ.PARTY_KEY,-999) AS HQ_CR_PRTY_KEY,
	 COALESCE(NP.PARTY_KEY,-999) AS TRANSACTION_CR_PARTY_KEY,
	 COALESCE( OFFER.NAME,'UNKNOWN' ) AS BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
	 COALESCE( TECH.NAME, 'UNKNOWN' ) AS BK_TECH_GROUP_ID,
	 COALESCE( ARCH.NAME, 'UNKNOWN' ) AS BK_AS_ARCHITECTURE_NAME,
	 COALESCE(NPC.ITEM_KEY,-999) AS COVERED_PRDT_KEY,
	 ST.ATTRIBUTED_QUANTITY AS ATTR_PRDT_QTY,
	 COALESCE(NULLIF(ST.ATTRIBUTED_PERCENTAGE,0), 0 ) AS ATTR_PCT,
	 COALESCE(ST.ATTRIBUTED_UNIT_NET_PRICE,0.0000) AS ATTR_NET_PRICE_LOCAL_AMT,
	 COALESCE(ST.ATTRIBUTED_EXT_NET_PRICE,0.0000) AS ATTR_EXTD_PRICE_LOCAL_AMT,
     COALESCE(ST.SALES_MOTION, 'UNKNOWN' ) SALES_MOTION_CD,
	 COALESCE(ST.SALES_MOTION_CONTEXT,'UNKNOWN') AS SALES_MOTION_CONTEXT_NAME,
	 COALESCE(SITEUSE.ERP_CUST_ACCOUNT_LOCATION_KEY, -999 ) AS ERP_CUST_ACCT_LOC_KEY,
	 COALESCE(ST.AS_TS_FLAG,'UNK') AS AS_TS_CD,
	 COALESCE( ST.LINE_REF_NUMBER,-999 ) AS SK_LINE_REF_NUM,
	 COALESCE(ST.TRX_ID,-999) AS SK_ERP_BKGS_TRX_ID,
	 COALESCE(ST.RENEW_CLE_ID,-999) AS SK_RENEW_CONTRACT_LINE_ID,
     COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-999) AS SK_AS_PARENT_INVENTORY_ITEM_ID,
     COALESCE(ST.ITEM_CATEGORIZATION,'UNKNOWN') AS ITEM_CATEGORY_NAME,
     COALESCE(ST.TRX_VERSION,-999) AS ERP_TRX_VERSION_INT,
     ST.SS_CD,
	  --ST.OA_ATTRIBUTION_ID AS SK_ATTRIBUTION_ID_INT, /* COmmented as part FCM Scope-US535842 */
	 NSOA.SK_OFFER_ATTRIBUTION_ID_INT AS  SK_ATTRIBUTION_ID_INT, /* Added as part FCM Scope-US535842 */
	 ST.ATTR_PRDT_CLASS_NAME,
	 ST.RENEWAL_REF_VALUE AS RENEWAL_REF_ID,
     ST.RENEWAL_REF_TYPE AS RENEWAL_REF_CD,
	 ST.REASON_CODE AS SMR_TAGGING_FAILURE_RSN_CD,
     ST.SALES_MOTION_TIMING AS SALES_MOTION_TIMING_CD,
     COALESCE(ST.MANUAL_OVERRIDE_FLAG,'N') AS MANUAL_OVERRIDE_ROLE, 
	 COALESCE(ST.SMR_SALES_VALUE, 0.000000 ) AS TOTAL_SERVICES_USD_AMT,
	 COALESCE(ST.SMR_ACV_AMOUNT, 0.000000 ) AS ACV_USD_AMT,
	 COALESCE(ST.SMR_TCV_AMOUNT, 0.000000 ) AS TCV_USD_AMT,
	 COALESCE(ST.LINE_EXTENDED_PRICE, 0.000000 ) AS EXTENDED_PRICE_USD_AMT,
	 COALESCE(NCWP.CISCO_WORKER_PARTY_KEY,-999) AS REQUESTING_CSCO_WRKR_PRTY_KEY,                   
     ST.CASE_NUMBER AS SLS_MTN_CORRECTION_CASE_NUM,                   
     ST.COMMENTS AS SLS_MTN_CORRECTION_CMNT,
     CURRENT_TIMESTAMP(0)  AS START_TV_DTM,
	 NSOA.ATTRIBUTED_PRODUCT_KEY AS OFFER_ATTRIB_PRDT_KEY,
ST.POS_TRANSACTION_ID_INT,
	 ST.ORDER_ORIGIN_CD,
 ST.SK_TRX_ID_INT,
 ST.SK_OPL_HEADER_ID_INT,
 ST.RENEWAL_ERP_REF_VALUE
    FROM ( SEL * FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV WHERE  ITEM_CATEGORIZATION NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' )
	AND ORDER_ORIGIN_CD <> 'DISTI-DSV'
    AND ORDER_ORIGIN_CD NOT IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) ) ST 
    INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL
     ON ST.ERP_LINE_ID = NSOL.SK_SO_LINE_ID_INT
	 AND NSOL.SS_CODE = 'CG'
	INNER JOIN $$COMREFVWDB.N_PRODUCT NPA
     ON ST.ENTERPRISE_SKU_INV_ITM_ID = NPA.SK_INVENTORY_ITEM_ID_INT
	INNER JOIN ( SEL * FROM $$NRTNCRVWDB.N_SOL_OFFER_ATTRIBUTION WHERE SK_OFFER_ATTRIBUTION_ID_INT > 0 ) NSOA /* for hard exception for OA records WITH OA ID */
     ON NSOL.SALES_ORDER_LINE_KEY = NSOA.TOP_SKU_SALES_ORDER_LINE_KEY
	 AND NPA.ITEM_KEY = NSOA.ENTERPRISE_SKU_PRDT_KEY
	 AND COALESCE(ST.OA_ATTRIBUTION_ID,-9999) = (CASE WHEN COALESCE(ST.OA_ATTRIBUTION_ID,-9999) = NSOA.SK_ATTRIBUTION_ID_INT THEN NSOA.SK_ATTRIBUTION_ID_INT ELSE  NSOA.SK_OFFER_ATTRIBUTION_ID_INT END) /* Modified as part FCM Scope-US535842 */
	LEFT JOIN $$COMREFVWDB.N_PRODUCT NPC
     ON COALESCE(ST.COVERED_PRD_INV_ITM_ID,-1012624) = NPC.SK_INVENTORY_ITEM_ID_INT     
    LEFT JOIN $$COMREFVWDB.N_PRODUCT NPP
     ON COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-1012624) = NPP.SK_INVENTORY_ITEM_ID_INT
    LEFT JOIN $$COMREFVWDB.N_ERP_CUST_ACCT_LOC_USE SITEUSE
     ON CAST(COALESCE(ST.INSTALL_SITE_LOCATION,-999) AS BIGINT) = SITEUSE.SK_SITE_USE_ID_INT 
    LEFT JOIN $$COMREFVWDB.N_PARTY NP
     ON COALESCE(ST.TXN_CR_PARTY_ID,-999) = NP.PARTY_SSOT_PARTY_ID_INT
     AND NP.SS_CODE IN ('CR_MODS','CR')
     AND COALESCE(NP.STATUS_CODE,'A')='A'
    LEFT JOIN $$COMREFVWDB.N_PARTY NPHQ
     ON COALESCE(ST.HQ_CR_PARTY_ID,-999) = NPHQ.PARTY_SSOT_PARTY_ID_INT
     AND NPHQ.SS_CODE IN ('CR_MODS','CR')
     AND COALESCE(NPHQ.STATUS_CODE,'A')='A'
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_ARCH ARCH
     ON ST.ARCHITECTURE_ID = ARCH.ARCHITECTURE_ID
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_TECH TECH
     ON ST.TECHNOLOGY_ID = TECH.TECHNOLOGY_ID
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_BIZ_SERVICES OFFER
     ON ST.OFFER_TYPE_ID = OFFER.BS_ID
    LEFT OUTER JOIN $$COMREFVWDB.N_CISCO_WORKER_PARTY_TV NCWP
     ON NCWP.CEC_ID||'@cisco.com' =ST.USER_ID 
     AND NCWP.END_TV_DATE='3500-01-01'
    INNER JOIN $$ETLVWDB.SM_ATTR_PRDT_NEW_RNWL_ACV SMXSS
     ON SMXSS.SK_RTR_ATTRIBUTION_ID=ST.RTR_ATTRIBUTION_ID
     AND SMXSS.SK_ATTRIBUTION_ID_INT = ST.OA_ATTRIBUTION_ID
     AND SMXSS.SS_CD = ST.SS_CD
WHERE EXISTS ( SEL 1 FROM $$NRTNCRVWDB.N_SOL_OFFER_ATTRIBUTION NSOA 
			  WHERE NSOL.SALES_ORDER_LINE_KEY = NSOA.TOP_SKU_SALES_ORDER_LINE_KEY )   /* FOR ATTRIBUTED ERP LINES */


Post SQL : 



Target3 Name : WI_OPL_XXGCO_RTR_ATTRIB_CV1


Pre SQL : 
DELETE FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_OPL_XXGCO_RTR_ATTRIB_CV','D');


Source4 Name : SQ_WI_OPL_XXGCO_RTR_ATTRIB_CV2


Pre SQL : 



SQL Query : 
SELECT
     SMXSS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
     ST.RTR_ATTRIBUTION_ID AS SK_RTR_ATTRIBUTION_ID,
     NPA.ITEM_KEY AS ATTR_PRDT_KEY,
	 NSOL.SALES_ORDER_LINE_KEY,
	 COALESCE(NPHQ.PARTY_KEY,-999) AS HQ_CR_PRTY_KEY,
	 COALESCE(NP.PARTY_KEY,-999) AS TRANSACTION_CR_PARTY_KEY,
	 COALESCE( OFFER.NAME,'UNKNOWN' ) AS BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
	 COALESCE( TECH.NAME, 'UNKNOWN' ) AS BK_TECH_GROUP_ID,
	 COALESCE( ARCH.NAME, 'UNKNOWN' ) AS BK_AS_ARCHITECTURE_NAME,
	 COALESCE(NPC.ITEM_KEY,-999) AS COVERED_PRDT_KEY,
	 ST.ATTRIBUTED_QUANTITY AS ATTR_PRDT_QTY,
	 COALESCE(NULLIF(ST.ATTRIBUTED_PERCENTAGE,0), 0 ) AS ATTR_PCT,
	 COALESCE(ST.ATTRIBUTED_UNIT_NET_PRICE,0.0000) AS ATTR_NET_PRICE_LOCAL_AMT,
	 COALESCE(ST.ATTRIBUTED_EXT_NET_PRICE,0.0000) AS ATTR_EXTD_PRICE_LOCAL_AMT,
     COALESCE(ST.SALES_MOTION, 'UNKNOWN' ) SALES_MOTION_CD,
	 COALESCE(ST.SALES_MOTION_CONTEXT,'UNKNOWN') AS SALES_MOTION_CONTEXT_NAME,
	 COALESCE(SITEUSE.ERP_CUST_ACCOUNT_LOCATION_KEY, -999 ) AS ERP_CUST_ACCT_LOC_KEY,
	 COALESCE(ST.AS_TS_FLAG,'UNK') AS AS_TS_CD,
	 COALESCE( ST.LINE_REF_NUMBER,-999 ) AS SK_LINE_REF_NUM,
	 COALESCE(ST.TRX_ID,-999) AS SK_ERP_BKGS_TRX_ID,
	 COALESCE(ST.RENEW_CLE_ID,-999) AS SK_RENEW_CONTRACT_LINE_ID,
     COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-999) AS SK_AS_PARENT_INVENTORY_ITEM_ID,
     COALESCE(ST.ITEM_CATEGORIZATION,'UNKNOWN') AS ITEM_CATEGORY_NAME,
     COALESCE(ST.TRX_VERSION,-999) AS ERP_TRX_VERSION_INT,
     ST.SS_CD,
	 ST.OA_ATTRIBUTION_ID AS SK_ATTRIBUTION_ID_INT,
	 ST.ATTR_PRDT_CLASS_NAME,
	 ST.RENEWAL_REF_VALUE AS RENEWAL_REF_ID,
     ST.RENEWAL_REF_TYPE AS RENEWAL_REF_CD,
	 ST.REASON_CODE AS SMR_TAGGING_FAILURE_RSN_CD,
     ST.SALES_MOTION_TIMING AS SALES_MOTION_TIMING_CD,
     COALESCE(ST.MANUAL_OVERRIDE_FLAG,'N') AS MANUAL_OVERRIDE_ROLE, 
	 COALESCE(ST.SMR_SALES_VALUE, 0.000000 ) AS TOTAL_SERVICES_USD_AMT,
	 COALESCE(ST.SMR_ACV_AMOUNT, 0.000000 ) AS ACV_USD_AMT,
	 COALESCE(ST.SMR_TCV_AMOUNT, 0.000000 ) AS TCV_USD_AMT,
	 COALESCE(ST.LINE_EXTENDED_PRICE, 0.000000 ) AS EXTENDED_PRICE_USD_AMT,
	 COALESCE(NCWP.CISCO_WORKER_PARTY_KEY,-999) AS REQUESTING_CSCO_WRKR_PRTY_KEY,                   
     ST.CASE_NUMBER AS SLS_MTN_CORRECTION_CASE_NUM,                   
     ST.COMMENTS AS SLS_MTN_CORRECTION_CMNT,
     CURRENT_TIMESTAMP(0)  AS START_TV_DTM,
	 NSOL.PRODUCT_KEY AS OFFER_ATTRIB_PRDT_KEY,
ST.POS_TRANSACTION_ID_INT,
	 ST.ORDER_ORIGIN_CD,
COALESCE(ST.SK_TRX_ID_INT, -999) AS SK_TRX_ID_INT,
 ST.SK_OPL_HEADER_ID_INT,
 ST.RENEWAL_ERP_REF_VALUE
    FROM (  SEL * FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV WHERE ITEM_CATEGORIZATION NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' )
	AND ORDER_ORIGIN_CD <>  'DISTI-DSV' 
	AND ORDER_ORIGIN_CD NOT IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN )  ) ST 
    INNER JOIN $$COMREFVWDB.N_PRODUCT NPA
     ON ST.ENTERPRISE_SKU_INV_ITM_ID = NPA.SK_INVENTORY_ITEM_ID_INT
	 INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL /* NSOL REFERENCE join to get sol key and so key*/
     ON ST.ERP_LINE_ID = NSOL.SK_SO_LINE_ID_INT
	 AND NSOL.SS_CODE = 'CG'
	INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_V1_TV NSO /* NSO join to get CCW ORDER ORIGIN CD COL */
     ON NSOL.SALES_ORDER_KEY =  NSO.SALES_ORDER_KEY
	 AND NSO.END_TV_DTM = '3500-01-01 00:00:00'
	 AND NSO.SS_CD = 'CG'
	INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL_P
     ON NSOL.SALES_ORDER_LINE_KEY = NSOL_P.SALES_ORDER_LINE_KEY
	 AND CASE WHEN NSO.CCW_ORDER_ORIGIN_CD NOT IN ('CCW-RENEWALS','CCW-RENEWALS-2T') THEN NSOL_P.PRODUCT_KEY ELSE -999 END
	 = CASE WHEN NSO.CCW_ORDER_ORIGIN_CD NOT IN ('CCW-RENEWALS','CCW-RENEWALS-2T') THEN NPA.ITEM_KEY ELSE -999 END /* STANDALONE ERP LINES - HARD EXCEPTION FOR INV SKU except CCWR/CCWR-2T lines*/
	 AND NSOL_P.SS_CODE = 'CG'
    LEFT JOIN $$COMREFVWDB.N_PRODUCT NPC
     ON COALESCE(ST.COVERED_PRD_INV_ITM_ID,-1012624) = NPC.SK_INVENTORY_ITEM_ID_INT     
    LEFT JOIN $$COMREFVWDB.N_PRODUCT NPP
     ON COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-1012624) = NPP.SK_INVENTORY_ITEM_ID_INT
    LEFT JOIN $$COMREFVWDB.N_ERP_CUST_ACCT_LOC_USE SITEUSE
     ON CAST(COALESCE(ST.INSTALL_SITE_LOCATION,-999) AS BIGINT)= SITEUSE.SK_SITE_USE_ID_INT 
    LEFT JOIN $$COMREFVWDB.N_PARTY NP
     ON COALESCE(ST.TXN_CR_PARTY_ID,-999) = NP.PARTY_SSOT_PARTY_ID_INT
     AND NP.SS_CODE IN ('CR_MODS','CR')
     AND COALESCE(NP.STATUS_CODE,'A')='A'
    LEFT JOIN $$COMREFVWDB.N_PARTY NPHQ
     ON COALESCE(ST.HQ_CR_PARTY_ID,-999) = NPHQ.PARTY_SSOT_PARTY_ID_INT
     AND NPHQ.SS_CODE IN ('CR_MODS','CR')
     AND COALESCE(NPHQ.STATUS_CODE,'A')='A'
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_ARCH ARCH
     ON ST.ARCHITECTURE_ID = ARCH.ARCHITECTURE_ID
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_TECH TECH
     ON ST.TECHNOLOGY_ID = TECH.TECHNOLOGY_ID
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_BIZ_SERVICES OFFER
     ON ST.OFFER_TYPE_ID = OFFER.BS_ID
    LEFT OUTER JOIN $$COMREFVWDB.N_CISCO_WORKER_PARTY_TV NCWP
     ON NCWP.CEC_ID||'@cisco.com' =ST.USER_ID 
     AND NCWP.END_TV_DATE='3500-01-01'
    INNER JOIN $$ETLVWDB.SM_ATTR_PRDT_NEW_RNWL_ACV SMXSS
     ON SMXSS.SK_RTR_ATTRIBUTION_ID=ST.RTR_ATTRIBUTION_ID
     AND SMXSS.SK_ATTRIBUTION_ID_INT = ST.OA_ATTRIBUTION_ID
     AND SMXSS.SS_CD = ST.SS_CD
WHERE NOT EXISTS ( SEL 1 FROM $$NRTNCRVWDB.N_SOL_OFFER_ATTRIBUTION NSOA
			  WHERE NSOL.SALES_ORDER_LINE_KEY = NSOA.TOP_SKU_SALES_ORDER_LINE_KEY ) /* FOR STANDALONE ERP LINES */


Post SQL : 



Target4 Name : WI_OPL_XXGCO_RTR_ATTRIB_CV2


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_OPL_XXGCO_RTR_ATTRIB_CV','D');


Source5 Name : SQ_WI_OPL_XXGCO_RTR_ATTRIB_CV3


Pre SQL : 



SQL Query : 
SELECT
     SMXSS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
     ST.RTR_ATTRIBUTION_ID AS SK_RTR_ATTRIBUTION_ID,
     NPA.ITEM_KEY AS ATTR_PRDT_KEY,
	 CAST( -7777 AS INTEGER ) AS SALES_ORDER_LINE_KEY,
	 COALESCE(NPHQ.PARTY_KEY,-999) AS HQ_CR_PRTY_KEY,
	 COALESCE(NP.PARTY_KEY,-999) AS TRANSACTION_CR_PARTY_KEY,
	 COALESCE( OFFER.NAME,'UNKNOWN' ) AS BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
	 COALESCE( TECH.NAME, 'UNKNOWN' ) AS BK_TECH_GROUP_ID,
	 COALESCE( ARCH.NAME, 'UNKNOWN' ) AS BK_AS_ARCHITECTURE_NAME,
	 COALESCE(NPC.ITEM_KEY,-999) AS COVERED_PRDT_KEY,
	 ST.ATTRIBUTED_QUANTITY AS ATTR_PRDT_QTY,
	 COALESCE(NULLIF(ST.ATTRIBUTED_PERCENTAGE,0), 0 ) AS ATTR_PCT,
	 COALESCE(ST.ATTRIBUTED_UNIT_NET_PRICE,0.0000) AS ATTR_NET_PRICE_LOCAL_AMT,
	 COALESCE(ST.ATTRIBUTED_EXT_NET_PRICE,0.0000) AS ATTR_EXTD_PRICE_LOCAL_AMT,
     COALESCE(ST.SALES_MOTION, 'UNKNOWN' ) SALES_MOTION_CD,
	 COALESCE(ST.SALES_MOTION_CONTEXT,'UNKNOWN') AS SALES_MOTION_CONTEXT_NAME,
	 COALESCE(SITEUSE.ERP_CUST_ACCOUNT_LOCATION_KEY, -999 ) AS ERP_CUST_ACCT_LOC_KEY,
	 COALESCE(ST.AS_TS_FLAG,'UNK') AS AS_TS_CD,
	 COALESCE( ST.LINE_REF_NUMBER,-999 ) AS SK_LINE_REF_NUM,
	 COALESCE(ST.TRX_ID,-999) AS SK_ERP_BKGS_TRX_ID,
	 COALESCE(ST.RENEW_CLE_ID,-999) AS SK_RENEW_CONTRACT_LINE_ID,
     COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-999) AS SK_AS_PARENT_INVENTORY_ITEM_ID,
     COALESCE(ST.ITEM_CATEGORIZATION,'UNKNOWN') AS ITEM_CATEGORY_NAME,
     COALESCE(ST.TRX_VERSION,-999) AS ERP_TRX_VERSION_INT,
     ST.SS_CD,
	 ST.OA_ATTRIBUTION_ID AS SK_ATTRIBUTION_ID_INT,
	 ST.ATTR_PRDT_CLASS_NAME,
	 ST.RENEWAL_REF_VALUE AS RENEWAL_REF_ID,
     ST.RENEWAL_REF_TYPE AS RENEWAL_REF_CD,
	 ST.REASON_CODE AS SMR_TAGGING_FAILURE_RSN_CD,
     ST.SALES_MOTION_TIMING AS SALES_MOTION_TIMING_CD,
     COALESCE(ST.MANUAL_OVERRIDE_FLAG,'N') AS MANUAL_OVERRIDE_ROLE, 
	 COALESCE(ST.SMR_SALES_VALUE, 0.000000 ) AS TOTAL_SERVICES_USD_AMT,
	 COALESCE(ST.SMR_ACV_AMOUNT, 0.000000 ) AS ACV_USD_AMT,
	 COALESCE(ST.SMR_TCV_AMOUNT, 0.000000 ) AS TCV_USD_AMT,
	 COALESCE(ST.LINE_EXTENDED_PRICE, 0.000000 ) AS EXTENDED_PRICE_USD_AMT,
	 COALESCE(NCWP.CISCO_WORKER_PARTY_KEY,-999) AS REQUESTING_CSCO_WRKR_PRTY_KEY,                   
     ST.CASE_NUMBER AS SLS_MTN_CORRECTION_CASE_NUM,                   
     ST.COMMENTS AS SLS_MTN_CORRECTION_CMNT,
     CURRENT_TIMESTAMP(0)  AS START_TV_DTM,
	 XOA.ORDERED_PRODUCT_KEY AS OFFER_ATTRIB_PRDT_KEY,
ST.POS_TRANSACTION_ID_INT,
	 ST.ORDER_ORIGIN_CD,
 ST.SK_TRX_ID_INT,
 ST.SK_OPL_HEADER_ID_INT,
 ST.RENEWAL_ERP_REF_VALUE
    FROM ( SEL * FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV WHERE ( ITEM_CATEGORIZATION IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
	OR ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )
	AND ORDER_ORIGIN_CD <>  'DISTI-DSV' ) ST 
    INNER JOIN $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ITM_SLSTRX_NRT TRX
	 ON ST.TRX_ID = TRX.SK_TRX_ID_INT
	 AND COALESCE(TRX.TRX_SS_CD, 'UNKNOWN' ) <> 'AR' /* Added filter as part of Nov 2020 SW release to restrict AR XAAS lines from OPL and inherit within EDW */
	 INNER JOIN $$COMREFVWDB.N_PRODUCT NPA
     ON ST.ENTERPRISE_SKU_INV_ITM_ID = NPA.SK_INVENTORY_ITEM_ID_INT
	INNER JOIN ( SEL * FROM $$NRTNCRVWDB.N_XAAS_SO_SBSCRPTN_ATTRBTN_NRT WHERE BK_OFFER_ATTRIBUTION_ID_INT > 0 ) XOA /* for hard exception for OA records WITH OA ID */
     ON TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY = XOA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY
	 AND NPA.ITEM_KEY = XOA.ENTERPRISE_SKU_PRDT_KEY
	 AND COALESCE(ST.OA_ATTRIBUTION_ID,-9999) = XOA.BK_OFFER_ATTRIBUTION_ID_INT
	LEFT JOIN $$COMREFVWDB.N_PRODUCT NPC
     ON COALESCE(ST.COVERED_PRD_INV_ITM_ID,-1012624) = NPC.SK_INVENTORY_ITEM_ID_INT     
    LEFT JOIN $$COMREFVWDB.N_PRODUCT NPP
     ON COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-1012624) = NPP.SK_INVENTORY_ITEM_ID_INT
    LEFT JOIN $$COMREFVWDB.N_ERP_CUST_ACCT_LOC_USE SITEUSE
     ON CAST(COALESCE(ST.INSTALL_SITE_LOCATION,-999) AS BIGINT) = SITEUSE.SK_SITE_USE_ID_INT 
    LEFT JOIN $$COMREFVWDB.N_PARTY NP
     ON COALESCE(ST.TXN_CR_PARTY_ID,-999) = NP.PARTY_SSOT_PARTY_ID_INT
     AND NP.SS_CODE IN ('CR_MODS','CR')
     AND COALESCE(NP.STATUS_CODE,'A')='A'
    LEFT JOIN $$COMREFVWDB.N_PARTY NPHQ
     ON COALESCE(ST.HQ_CR_PARTY_ID,-999) = NPHQ.PARTY_SSOT_PARTY_ID_INT
     AND NPHQ.SS_CODE IN ('CR_MODS','CR')
     AND COALESCE(NPHQ.STATUS_CODE,'A')='A'
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_ARCH ARCH
     ON ST.ARCHITECTURE_ID = ARCH.ARCHITECTURE_ID
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_TECH TECH
     ON ST.TECHNOLOGY_ID = TECH.TECHNOLOGY_ID
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_BIZ_SERVICES OFFER
     ON ST.OFFER_TYPE_ID = OFFER.BS_ID
    LEFT OUTER JOIN $$COMREFVWDB.N_CISCO_WORKER_PARTY_TV NCWP
     ON NCWP.CEC_ID =ST.USER_ID 
     AND NCWP.END_TV_DATE='3500-01-01'
    INNER JOIN $$ETLVWDB.SM_ATTR_PRDT_NEW_RNWL_ACV SMXSS
     ON SMXSS.SK_RTR_ATTRIBUTION_ID=ST.RTR_ATTRIBUTION_ID
     AND SMXSS.SK_ATTRIBUTION_ID_INT = ST.OA_ATTRIBUTION_ID
     AND SMXSS.SS_CD = ST.SS_CD
WHERE EXISTS ( SEL 1 FROM $$NRTNCRVWDB.N_XAAS_SO_SBSCRPTN_ATTRBTN_NRT XOA
			  WHERE TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY = XOA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY ) /* FOR ATTRIBUTED XAAS LINES */


Post SQL : 



Target5 Name : WI_OPL_XXGCO_RTR_ATTRIB_CV3


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_OPL_XXGCO_RTR_ATTRIB_CV','D');


Source6 Name : SQ_WI_OPL_XXGCO_RTR_ATTRIB_CV4


Pre SQL : 



SQL Query : 
SELECT
     SMXSS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
     ST.RTR_ATTRIBUTION_ID AS SK_RTR_ATTRIBUTION_ID,
     NPA.ITEM_KEY AS ATTR_PRDT_KEY,
	 CAST( -7777 AS INTEGER ) AS SALES_ORDER_LINE_KEY,
	 COALESCE(NPHQ.PARTY_KEY,-999) AS HQ_CR_PRTY_KEY,
	 COALESCE(NP.PARTY_KEY,-999) AS TRANSACTION_CR_PARTY_KEY,
	 COALESCE( OFFER.NAME,'UNKNOWN' ) AS BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
	 COALESCE( TECH.NAME, 'UNKNOWN' ) AS BK_TECH_GROUP_ID,
	 COALESCE( ARCH.NAME, 'UNKNOWN' ) AS BK_AS_ARCHITECTURE_NAME,
	 COALESCE(NPC.ITEM_KEY,-999) AS COVERED_PRDT_KEY,
	 ST.ATTRIBUTED_QUANTITY AS ATTR_PRDT_QTY,
	 COALESCE(NULLIF(ST.ATTRIBUTED_PERCENTAGE,0), 0 ) AS ATTR_PCT,
	 COALESCE(ST.ATTRIBUTED_UNIT_NET_PRICE,0.0000) AS ATTR_NET_PRICE_LOCAL_AMT,
	 COALESCE(ST.ATTRIBUTED_EXT_NET_PRICE,0.0000) AS ATTR_EXTD_PRICE_LOCAL_AMT,
     COALESCE(ST.SALES_MOTION, 'UNKNOWN' ) SALES_MOTION_CD,
	 COALESCE(ST.SALES_MOTION_CONTEXT,'UNKNOWN') AS SALES_MOTION_CONTEXT_NAME,
	 COALESCE(SITEUSE.ERP_CUST_ACCOUNT_LOCATION_KEY, -999 ) AS ERP_CUST_ACCT_LOC_KEY,
	 COALESCE(ST.AS_TS_FLAG,'UNK') AS AS_TS_CD,
	 COALESCE( ST.LINE_REF_NUMBER,-999 ) AS SK_LINE_REF_NUM,
	 COALESCE(ST.TRX_ID,-999) AS SK_ERP_BKGS_TRX_ID,
	 COALESCE(ST.RENEW_CLE_ID,-999) AS SK_RENEW_CONTRACT_LINE_ID,
     COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-999) AS SK_AS_PARENT_INVENTORY_ITEM_ID,
     COALESCE(ST.ITEM_CATEGORIZATION,'UNKNOWN') AS ITEM_CATEGORY_NAME,
     COALESCE(ST.TRX_VERSION,-999) AS ERP_TRX_VERSION_INT,
     ST.SS_CD,
	 ST.OA_ATTRIBUTION_ID AS SK_ATTRIBUTION_ID_INT,
	 ST.ATTR_PRDT_CLASS_NAME,
	 ST.RENEWAL_REF_VALUE AS RENEWAL_REF_ID,
     ST.RENEWAL_REF_TYPE AS RENEWAL_REF_CD,
	 ST.REASON_CODE AS SMR_TAGGING_FAILURE_RSN_CD,
     ST.SALES_MOTION_TIMING AS SALES_MOTION_TIMING_CD,
     COALESCE(ST.MANUAL_OVERRIDE_FLAG,'N') AS MANUAL_OVERRIDE_ROLE, 
	 COALESCE(ST.SMR_SALES_VALUE, 0.000000 ) AS TOTAL_SERVICES_USD_AMT,
	 COALESCE(ST.SMR_ACV_AMOUNT, 0.000000 ) AS ACV_USD_AMT,
	 COALESCE(ST.SMR_TCV_AMOUNT, 0.000000 ) AS TCV_USD_AMT,
	 COALESCE(ST.LINE_EXTENDED_PRICE, 0.000000 ) AS EXTENDED_PRICE_USD_AMT,
	 COALESCE(NCWP.CISCO_WORKER_PARTY_KEY,-999) AS REQUESTING_CSCO_WRKR_PRTY_KEY,                   
     ST.CASE_NUMBER AS SLS_MTN_CORRECTION_CASE_NUM,                   
     ST.COMMENTS AS SLS_MTN_CORRECTION_CMNT,
     CURRENT_TIMESTAMP(0)  AS START_TV_DTM,
	 TRX.SUBSCRIPTION_PRODUCT_KEY AS OFFER_ATTRIB_PRDT_KEY,
	 ST.POS_TRANSACTION_ID_INT,
	ST.ORDER_ORIGIN_CD,
COALESCE(ST.SK_TRX_ID_INT, -999) AS SK_TRX_ID_INT,
ST.SK_OPL_HEADER_ID_INT,
ST.RENEWAL_ERP_REF_VALUE
    FROM ( SEL * FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV WHERE ( ITEM_CATEGORIZATION IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' ) 
	OR ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )
	AND ORDER_ORIGIN_CD <> 'DISTI-DSV'
	) ST 
    INNER JOIN $$COMREFVWDB.N_PRODUCT NPA
     ON ST.ENTERPRISE_SKU_INV_ITM_ID = NPA.SK_INVENTORY_ITEM_ID_INT
	INNER JOIN $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ITM_SLSTRX_NRT TRX
	 ON ST.TRX_ID = TRX.SK_TRX_ID_INT
	 AND NPA.ITEM_KEY = TRX.SUBSCRIPTION_PRODUCT_KEY /* STANDALONE XAAS LINES - HARD EXCEPTION FOR INV SKU */
	 AND COALESCE( TRX.TRX_SS_CD, 'UNKNOWN' ) <> 'AR' /* Added as part of Nov 2020 SW release to restrict AR XAAS lines from OPL and inherit within EDW */
    LEFT JOIN $$COMREFVWDB.N_PRODUCT NPC
     ON COALESCE(ST.COVERED_PRD_INV_ITM_ID,-1012624) = NPC.SK_INVENTORY_ITEM_ID_INT     
    LEFT JOIN $$COMREFVWDB.N_PRODUCT NPP
     ON COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-1012624) = NPP.SK_INVENTORY_ITEM_ID_INT
    LEFT JOIN $$COMREFVWDB.N_ERP_CUST_ACCT_LOC_USE SITEUSE
     ON CAST(COALESCE(ST.INSTALL_SITE_LOCATION,-999) AS BIGINT)= SITEUSE.SK_SITE_USE_ID_INT 
    LEFT JOIN $$COMREFVWDB.N_PARTY NP
     ON COALESCE(ST.TXN_CR_PARTY_ID,-999) = NP.PARTY_SSOT_PARTY_ID_INT
     AND NP.SS_CODE IN ('CR_MODS','CR')
     AND COALESCE(NP.STATUS_CODE,'A')='A'
    LEFT JOIN $$COMREFVWDB.N_PARTY NPHQ
     ON COALESCE(ST.HQ_CR_PARTY_ID,-999) = NPHQ.PARTY_SSOT_PARTY_ID_INT
     AND NPHQ.SS_CODE IN ('CR_MODS','CR')
     AND COALESCE(NPHQ.STATUS_CODE,'A')='A'
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_ARCH ARCH
     ON ST.ARCHITECTURE_ID = ARCH.ARCHITECTURE_ID
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_TECH TECH
     ON ST.TECHNOLOGY_ID = TECH.TECHNOLOGY_ID
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_BIZ_SERVICES OFFER
     ON ST.OFFER_TYPE_ID = OFFER.BS_ID
    LEFT OUTER JOIN $$COMREFVWDB.N_CISCO_WORKER_PARTY_TV NCWP
     ON NCWP.CEC_ID =ST.USER_ID 
     AND NCWP.END_TV_DATE='3500-01-01'
    INNER JOIN $$ETLVWDB.SM_ATTR_PRDT_NEW_RNWL_ACV SMXSS
     ON SMXSS.SK_RTR_ATTRIBUTION_ID=ST.RTR_ATTRIBUTION_ID
     AND SMXSS.SK_ATTRIBUTION_ID_INT = ST.OA_ATTRIBUTION_ID
     AND SMXSS.SS_CD = ST.SS_CD
WHERE NOT EXISTS ( SEL 1 FROM $$NRTNCRVWDB.N_XAAS_SO_SBSCRPTN_ATTRBTN_NRT XOA
			  WHERE TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY = XOA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY ) /* FOR STANDALONE XAAS LINES */


Post SQL : 



Target6 Name : WI_OPL_XXGCO_RTR_ATTRIB_CV4


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_OPL_XXGCO_RTR_ATTRIB_CV','D');


Source7 Name : SQ_WI_OPL_XXGCO_RTR_ATTRIB_CV5


Pre SQL : 



SQL Query : 
SELECT
     SMXSS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
     ST.RTR_ATTRIBUTION_ID AS SK_RTR_ATTRIBUTION_ID,
     BKG_POS.PRODUCT_KEY AS ATTR_PRDT_KEY,
	 COALESCE(NSOL.SALES_ORDER_LINE_KEY,CAST(-7777 AS INTEGER)) AS SALES_ORDER_LINE_KEY,
	 COALESCE(NPHQ.PARTY_KEY,-999) AS HQ_CR_PRTY_KEY,
	 COALESCE(NP.PARTY_KEY,-999) AS TRANSACTION_CR_PARTY_KEY,
	 COALESCE( OFFER.NAME,'UNKNOWN' ) AS BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
	 COALESCE( TECH.NAME, 'UNKNOWN' ) AS BK_TECH_GROUP_ID,
	 COALESCE( ARCH.NAME, 'UNKNOWN' ) AS BK_AS_ARCHITECTURE_NAME,
	 COALESCE(NPC.ITEM_KEY,-999) AS COVERED_PRDT_KEY,
	 ST.ATTRIBUTED_QUANTITY AS ATTR_PRDT_QTY,
	 COALESCE(NULLIF(ST.ATTRIBUTED_PERCENTAGE,0), 0 ) AS ATTR_PCT,
	 COALESCE(ST.ATTRIBUTED_UNIT_NET_PRICE,0.0000) AS ATTR_NET_PRICE_LOCAL_AMT,
	 COALESCE(ST.ATTRIBUTED_EXT_NET_PRICE,0.0000) AS ATTR_EXTD_PRICE_LOCAL_AMT,
     COALESCE(ST.SALES_MOTION, 'UNKNOWN' ) SALES_MOTION_CD,
	 COALESCE(ST.SALES_MOTION_CONTEXT,'UNKNOWN') AS SALES_MOTION_CONTEXT_NAME,
	 COALESCE(SITEUSE.WIPS_SITE_USE_KEY, -999 ) AS ERP_CUST_ACCT_LOC_KEY,
	 -- COALESCE(SITEUSE.ERP_CUST_ACCOUNT_LOCATION_KEY, -999 ) AS ERP_CUST_ACCT_LOC_KEY,
	 COALESCE(ST.AS_TS_FLAG,'UNK') AS AS_TS_CD,
	 COALESCE( ST.LINE_REF_NUMBER,-999 ) AS SK_LINE_REF_NUM,
	 COALESCE(ST.TRX_ID,-999) AS SK_ERP_BKGS_TRX_ID,
	 COALESCE(ST.RENEW_CLE_ID,-999) AS SK_RENEW_CONTRACT_LINE_ID,
     COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-999) AS SK_AS_PARENT_INVENTORY_ITEM_ID,
     COALESCE(ST.ITEM_CATEGORIZATION,'UNKNOWN') AS ITEM_CATEGORY_NAME,
     COALESCE(ST.TRX_VERSION,-999) AS ERP_TRX_VERSION_INT,
     ST.SS_CD,
	 ST.OA_ATTRIBUTION_ID AS SK_ATTRIBUTION_ID_INT,
	 ST.ATTR_PRDT_CLASS_NAME,
	 ST.RENEWAL_REF_VALUE AS RENEWAL_REF_ID,
     ST.RENEWAL_REF_TYPE AS RENEWAL_REF_CD,
	 ST.REASON_CODE AS SMR_TAGGING_FAILURE_RSN_CD,
     ST.SALES_MOTION_TIMING AS SALES_MOTION_TIMING_CD,
     COALESCE(ST.MANUAL_OVERRIDE_FLAG,'N') AS MANUAL_OVERRIDE_ROLE, 
	 COALESCE(ST.SMR_SALES_VALUE, 0.000000 ) AS TOTAL_SERVICES_USD_AMT,
	 COALESCE(ST.SMR_ACV_AMOUNT, 0.000000 ) AS ACV_USD_AMT,
	 COALESCE(ST.SMR_TCV_AMOUNT, 0.000000 ) AS TCV_USD_AMT,
	 COALESCE(ST.LINE_EXTENDED_PRICE, 0.000000 ) AS EXTENDED_PRICE_USD_AMT,
	 COALESCE(NCWP.CISCO_WORKER_PARTY_KEY,-999) AS REQUESTING_CSCO_WRKR_PRTY_KEY,                   
     ST.CASE_NUMBER AS SLS_MTN_CORRECTION_CASE_NUM,                   
     ST.COMMENTS AS SLS_MTN_CORRECTION_CMNT,
     CURRENT_TIMESTAMP(0)  AS START_TV_DTM,
	 NPOA.ATTRIBUTED_PRODUCT_KEY AS OFFER_ATTRIB_PRDT_KEY,
	 ST.POS_TRANSACTION_ID_INT,
	 ST.ORDER_ORIGIN_CD,
COALESCE(ST.SK_TRX_ID_INT, -999) AS SK_TRX_ID_INT,
 ST.SK_OPL_HEADER_ID_INT,
 RENEWAL_ERP_REF_VALUE
    FROM ( SEL * FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV WHERE ORDER_ORIGIN_CD = 'DISTI-DSV' AND POS_TRANSACTION_ID_INT > 0 ) ST 
     LEFT JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL
     ON ST.ERP_LINE_ID = NSOL.SK_SO_LINE_ID_INT
	 AND NSOL.SS_CODE = 'CG'
	/*INNER JOIN $$COMREFVWDB.N_PRODUCT NPA
     ON ST.ENTERPRISE_SKU_INV_ITM_ID = NPA.SK_INVENTORY_ITEM_ID_INT*/
	INNER JOIN $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE BKG_POS  
     ON ST.POS_TRANSACTION_ID_INT = BKG_POS.BK_POS_TRANSACTION_ID_INT
	INNER JOIN ( SEL * FROM $$SLSORDVWDB.N_POS_TRX_LINE_OFFER_ATRBTN WHERE BK_OFFER_ATTRIBUTION_ID_INT > 0 ) NPOA   /* for hard exception for OA records WITH OA ID */
     ON ST.POS_TRANSACTION_ID_INT = NPOA.TOP_SKU_POS_TRX_ID_INT 
	 AND COALESCE(ST.OA_ATTRIBUTION_ID,-9999) = NPOA.BK_OFFER_ATTRIBUTION_ID_INT
	 /*AND NPA.ITEM_KEY=NPOA.ATTRIBUTED_PRODUCT_KEY*/
	LEFT JOIN $$COMREFVWDB.N_PRODUCT NPC
     ON COALESCE(ST.COVERED_PRD_INV_ITM_ID,-1012624) = NPC.SK_INVENTORY_ITEM_ID_INT     
    LEFT JOIN $$COMREFVWDB.N_PRODUCT NPP
     ON COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-1012624) = NPP.SK_INVENTORY_ITEM_ID_INT
	 LEFT JOIN $$COMREFVWDB.N_WIPS_CUSTOMER_SITE_TV SITEUSE
	ON CAST(COALESCE(ST.INSTALL_SITE_LOCATION,-999) AS BIGINT) = SITEUSE.BK_SITE_USE_ID_INT
   /* LEFT JOIN $$COMREFVWDB.N_ERP_CUST_ACCT_LOC_USE SITEUSE
     ON CAST(COALESCE(ST.INSTALL_SITE_LOCATION,-999) AS BIGINT) = SITEUSE.SK_SITE_USE_ID_INT */
    LEFT JOIN $$COMREFVWDB.N_PARTY NP
     ON COALESCE(ST.TXN_CR_PARTY_ID,-999) = NP.PARTY_SSOT_PARTY_ID_INT
     AND NP.SS_CODE IN ('CR_MODS','CR')   
     AND COALESCE(NP.STATUS_CODE,'A')='A'   
    LEFT JOIN $$COMREFVWDB.N_PARTY NPHQ
     ON COALESCE(ST.HQ_CR_PARTY_ID,-999) = NPHQ.PARTY_SSOT_PARTY_ID_INT
     AND NPHQ.SS_CODE IN ('CR_MODS','CR')       
     AND COALESCE(NPHQ.STATUS_CODE,'A')='A'     
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_ARCH ARCH
     ON ST.ARCHITECTURE_ID = ARCH.ARCHITECTURE_ID
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_TECH TECH
     ON ST.TECHNOLOGY_ID = TECH.TECHNOLOGY_ID
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_BIZ_SERVICES OFFER
     ON ST.OFFER_TYPE_ID = OFFER.BS_ID
    LEFT OUTER JOIN $$COMREFVWDB.N_CISCO_WORKER_PARTY_TV NCWP
     ON NCWP.CEC_ID||'@cisco.com' =ST.USER_ID 
     AND NCWP.END_TV_DATE='3500-01-01'
    INNER JOIN $$ETLVWDB.SM_ATTR_PRDT_NEW_RNWL_ACV SMXSS
     ON SMXSS.SK_RTR_ATTRIBUTION_ID=ST.RTR_ATTRIBUTION_ID
     AND SMXSS.SK_ATTRIBUTION_ID_INT = ST.OA_ATTRIBUTION_ID
     AND SMXSS.SS_CD = ST.SS_CD
WHERE EXISTS ( SEL 1 FROM $$SLSORDVWDB.N_POS_TRX_LINE_OFFER_ATRBTN NPOA  WHERE ST.POS_TRANSACTION_ID_INT = NPOA.TOP_SKU_POS_TRX_ID_INT )


Post SQL : 



Target7 Name : WI_OPL_XXGCO_RTR_ATTRIB_CV5


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_OPL_XXGCO_RTR_ATTRIB_CV','D');


Source8 Name : SQ_WI_OPL_XXGCO_RTR_ATTRIB_CV6


Pre SQL : 



SQL Query : 
SELECT
     SMXSS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
     ST.RTR_ATTRIBUTION_ID AS SK_RTR_ATTRIBUTION_ID,
     NPA.ITEM_KEY AS ATTR_PRDT_KEY,
	 COALESCE(NSOL.SALES_ORDER_LINE_KEY,CAST(-7777 AS INTEGER)) AS SALES_ORDER_LINE_KEY,
	 COALESCE(NPHQ.PARTY_KEY,-999) AS HQ_CR_PRTY_KEY,
	 COALESCE(NP.PARTY_KEY,-999) AS TRANSACTION_CR_PARTY_KEY,
	 COALESCE( OFFER.NAME,'UNKNOWN' ) AS BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
	 COALESCE( TECH.NAME, 'UNKNOWN' ) AS BK_TECH_GROUP_ID,
	 COALESCE( ARCH.NAME, 'UNKNOWN' ) AS BK_AS_ARCHITECTURE_NAME,
	 COALESCE(NPC.ITEM_KEY,-999) AS COVERED_PRDT_KEY,
	 ST.ATTRIBUTED_QUANTITY AS ATTR_PRDT_QTY,
	 COALESCE(NULLIF(ST.ATTRIBUTED_PERCENTAGE,0), 0 ) AS ATTR_PCT,
	 COALESCE(ST.ATTRIBUTED_UNIT_NET_PRICE,0.0000) AS ATTR_NET_PRICE_LOCAL_AMT,
	 COALESCE(ST.ATTRIBUTED_EXT_NET_PRICE,0.0000) AS ATTR_EXTD_PRICE_LOCAL_AMT,
     COALESCE(ST.SALES_MOTION, 'UNKNOWN' ) SALES_MOTION_CD,
	 COALESCE(ST.SALES_MOTION_CONTEXT,'UNKNOWN') AS SALES_MOTION_CONTEXT_NAME,
	 COALESCE(SITEUSE.WIPS_SITE_USE_KEY, -999 ) AS ERP_CUST_ACCT_LOC_KEY, --COALESCE(SITEUSE.ERP_CUST_ACCOUNT_LOCATION_KEY, -999 ) AS ERP_CUST_ACCT_LOC_KEY,
	 COALESCE(ST.AS_TS_FLAG,'UNK') AS AS_TS_CD,
	 COALESCE( ST.LINE_REF_NUMBER,-999 ) AS SK_LINE_REF_NUM,
	 COALESCE(ST.TRX_ID,-999) AS SK_ERP_BKGS_TRX_ID,
	 COALESCE(ST.RENEW_CLE_ID,-999) AS SK_RENEW_CONTRACT_LINE_ID,
     COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-999) AS SK_AS_PARENT_INVENTORY_ITEM_ID,
     COALESCE(ST.ITEM_CATEGORIZATION,'UNKNOWN') AS ITEM_CATEGORY_NAME,
     COALESCE(ST.TRX_VERSION,-999) AS ERP_TRX_VERSION_INT,
     ST.SS_CD,
	 ST.OA_ATTRIBUTION_ID AS SK_ATTRIBUTION_ID_INT,
	 ST.ATTR_PRDT_CLASS_NAME,
	 ST.RENEWAL_REF_VALUE AS RENEWAL_REF_ID,
     ST.RENEWAL_REF_TYPE AS RENEWAL_REF_CD,
	 ST.REASON_CODE AS SMR_TAGGING_FAILURE_RSN_CD,
     ST.SALES_MOTION_TIMING AS SALES_MOTION_TIMING_CD,
     COALESCE(ST.MANUAL_OVERRIDE_FLAG,'N') AS MANUAL_OVERRIDE_ROLE, 
	 COALESCE(ST.SMR_SALES_VALUE, 0.000000 ) AS TOTAL_SERVICES_USD_AMT,
	 COALESCE(ST.SMR_ACV_AMOUNT, 0.000000 ) AS ACV_USD_AMT,
	 COALESCE(ST.SMR_TCV_AMOUNT, 0.000000 ) AS TCV_USD_AMT,
	 COALESCE(ST.LINE_EXTENDED_PRICE, 0.000000 ) AS EXTENDED_PRICE_USD_AMT,
	 COALESCE(NCWP.CISCO_WORKER_PARTY_KEY,-999) AS REQUESTING_CSCO_WRKR_PRTY_KEY,                   
     ST.CASE_NUMBER AS SLS_MTN_CORRECTION_CASE_NUM,                   
     ST.COMMENTS AS SLS_MTN_CORRECTION_CMNT,
     CURRENT_TIMESTAMP(0)  AS START_TV_DTM,
	 BKG_POS.PRODUCT_KEY AS OFFER_ATTRIB_PRDT_KEY,
	 ST.POS_TRANSACTION_ID_INT,
	 ST.ORDER_ORIGIN_CD,
COALESCE(ST.SK_TRX_ID_INT, -999) AS SK_TRX_ID_INT,
 ST.SK_OPL_HEADER_ID_INT,
 RENEWAL_ERP_REF_VALUE
    FROM ( SEL * FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV WHERE ORDER_ORIGIN_CD = 'DISTI-DSV'  AND POS_TRANSACTION_ID_INT > 0 ) ST 
	LEFT JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL
     ON ST.ERP_LINE_ID = NSOL.SK_SO_LINE_ID_INT
	 AND NSOL.SS_CODE = 'CG'
    INNER JOIN $$COMREFVWDB.N_PRODUCT NPA
     ON ST.ENTERPRISE_SKU_INV_ITM_ID = NPA.SK_INVENTORY_ITEM_ID_INT
	INNER JOIN $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE BKG_POS  
     ON ST.POS_TRANSACTION_ID_INT = BKG_POS.BK_POS_TRANSACTION_ID_INT
	 LEFT JOIN $$COMREFVWDB.N_PRODUCT NPC
     ON COALESCE(ST.COVERED_PRD_INV_ITM_ID,-1012624) = NPC.SK_INVENTORY_ITEM_ID_INT     
    LEFT JOIN $$COMREFVWDB.N_PRODUCT NPP
     ON COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-1012624) = NPP.SK_INVENTORY_ITEM_ID_INT
	 LEFT JOIN $$COMREFVWDB.N_WIPS_CUSTOMER_SITE_TV SITEUSE
     ON CAST(COALESCE(ST.INSTALL_SITE_LOCATION,-999) AS BIGINT) = SITEUSE.BK_SITE_USE_ID_INT
   /* LEFT JOIN $$COMREFVWDB.N_ERP_CUST_ACCT_LOC_USE SITEUSE
     ON CAST(COALESCE(ST.INSTALL_SITE_LOCATION,-999) AS BIGINT)= SITEUSE.SK_SITE_USE_ID_INT */
    LEFT JOIN $$COMREFVWDB.N_PARTY NP
     ON COALESCE(ST.TXN_CR_PARTY_ID,-999) = NP.PARTY_SSOT_PARTY_ID_INT
     AND NP.SS_CODE IN ('CR_MODS','CR')  
     AND COALESCE(NP.STATUS_CODE,'A')='A'
    LEFT JOIN $$COMREFVWDB.N_PARTY NPHQ
     ON COALESCE(ST.HQ_CR_PARTY_ID,-999) = NPHQ.PARTY_SSOT_PARTY_ID_INT
     AND NPHQ.SS_CODE IN ('CR_MODS','CR')  
     AND COALESCE(NPHQ.STATUS_CODE,'A')='A'
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_ARCH ARCH
     ON ST.ARCHITECTURE_ID = ARCH.ARCHITECTURE_ID
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_TECH TECH
     ON ST.TECHNOLOGY_ID = TECH.TECHNOLOGY_ID
    LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_BIZ_SERVICES OFFER
     ON ST.OFFER_TYPE_ID = OFFER.BS_ID
    LEFT OUTER JOIN $$COMREFVWDB.N_CISCO_WORKER_PARTY_TV NCWP
     ON NCWP.CEC_ID||'@cisco.com' =ST.USER_ID 
     AND NCWP.END_TV_DATE='3500-01-01'
    INNER JOIN $$ETLVWDB.SM_ATTR_PRDT_NEW_RNWL_ACV SMXSS
     ON SMXSS.SK_RTR_ATTRIBUTION_ID=ST.RTR_ATTRIBUTION_ID
     AND SMXSS.SK_ATTRIBUTION_ID_INT = ST.OA_ATTRIBUTION_ID
     AND SMXSS.SS_CD = ST.SS_CD
WHERE NOT EXISTS ( SEL 1 FROM $$SLSORDVWDB.N_POS_TRX_LINE_OFFER_ATRBTN NPOA WHERE ST.POS_TRANSACTION_ID_INT = NPOA.TOP_SKU_POS_TRX_ID_INT)


Post SQL : 



Target8 Name : WI_OPL_XXGCO_RTR_ATTRIB_CV6


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_OPL_XXGCO_RTR_ATTRIB_CV','D');


Source9 Name : SQ_EX_OPL_XXGCO_RTR_ATTRIB_CV


Pre SQL : 



SQL Query : 
SELECT
 ST.RECORD_OFFSET,
 ST.RTR_ATTRIBUTION_ID,
 ST.TRX_ID,
 ST.TRX_VERSION,
 ST.ATTRIBUTED_EXT_NET_PRICE,
 ST.ATTRIBUTED_UNIT_NET_PRICE,
 ST.ATTRIBUTED_PERCENTAGE,
 ST.ATTRIBUTED_QUANTITY,
 ST.ENTERPRISE_SKU_INV_ITM_ID,
 ST.COVERED_PRD_INV_ITM_ID,
 ST.AS_PARENT_SKU_INV_ITM_ID,
 ST.ARCHITECTURE_ID,
 ST.TECHNOLOGY_ID,
 ST.TXN_CR_PARTY_ID,
 ST.ERP_HEADER_ID,
 ST.ERP_LINE_ID,
 ST.ERP_SO_NUMBER,
 ST.ORDER_NUMBER,
 ST.LINE_REF_NUMBER,
 ST.SALES_MOTION,
 ST.SALES_MOTION_CONTEXT,
 ST.AS_TS_FLAG,
 ST.ITEM_CATEGORIZATION,
 ST.RECGD_ATTRIB_EXT_NET_PRICE,
 ST.RECGD_PERCENTAGE,
 ST.SS_CD,
 ST.OA_ATTRIBUTION_ID,
 ST.OFFER_TYPE_ID,
 ST.LIST_PRICE,
 ST.ATTR_PRDT_CLASS_NAME,
 ST.HQ_CR_PARTY_ID,
 ST.RENEWAL_REF_TYPE,
 ST.RENEWAL_REF_VALUE,
 ST.REASON_CODE,
 ST.SALES_MOTION_TIMING,
 ST.MANUAL_PROCESS_FLAG,
 ST.USER_ID,
 ST.CASE_NUMBER,
 ST.COMMENTS,
 ST.SMR_SALES_VALUE,
 ST.SMR_ACV_AMOUNT,
 ST.SMR_TCV_AMOUNT,
 ST.PRODUCT_CLASS,
 ST.RENEW_CLE_ID,
 ST.MANUAL_OVERRIDE_FLAG,
 ST.LINE_EXTENDED_PRICE,
 ST.EDW_CREATE_DTM,
 ST.PARTITION_NUMBER,
 ST.TOPIC_NAME,
 ST.INSTALL_SITE_LOCATION,
 CASE WHEN XAAS_TRX.SK_TRX_ID_INT IS NOT NULL THEN 'XAAS_AR_RESTRICTION'
	ELSE 'RI' END AS EXCEPTION_TYPE,
 ST.POS_TRANSACTION_ID_INT,
 ST.ORDER_ORIGIN_CD,
 ST.SK_TRX_ID_INT,
 ST.SK_OPL_HEADER_ID_INT,
 ST.RENEWAL_ERP_REF_VALUE
FROM
 $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV ST 
 INNER JOIN 
 (
   SELECT TRX_ID,POS_TRANSACTION_ID_INT FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV STG 
WHERE NOT EXISTS 
    (  
     SELECT 1 FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV WI
	 LEFT JOIN $$NRTNCRVWDB.N_SOL_OFFER_ATTRIBUTION NSOA
     ON WI.SALES_ORDER_LINE_KEY = NSOA.TOP_SKU_SALES_ORDER_LINE_KEY
     AND WI.SK_ATTRIBUTION_ID_INT=NSOA.SK_OFFER_ATTRIBUTION_ID_INT
     AND NSOA.SK_OFFER_ATTRIBUTION_ID_INT > 0
     WHERE  WI.SK_RTR_ATTRIBUTION_ID = STG.RTR_ATTRIBUTION_ID 
	 AND (CASE WHEN STG.OA_ATTRIBUTION_ID = NSOA.SK_ATTRIBUTION_ID_INT THEN NSOA.SK_ATTRIBUTION_ID_INT ELSE WI.SK_ATTRIBUTION_ID_INT END) = STG.OA_ATTRIBUTION_ID  /* Modified as part FCM Scope-US535842 */
     AND WI.SS_CD = STG.SS_CD 
    ) 
   GROUP BY 1,2
 ) WK
 ON COALESCE(ST.TRX_ID,-999)    = COALESCE(WK.TRX_ID,-999)
 AND COALESCE(ST.POS_TRANSACTION_ID_INT,-999)    = COALESCE(WK.POS_TRANSACTION_ID_INT,-999)
 LEFT JOIN ( SEL SK_TRX_ID_INT FROM $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ITM_SLSTRX_NRT WHERE TRX_SS_CD = 'AR' GROUP BY 1) XAAS_TRX
 ON ST.TRX_ID = XAAS_TRX.SK_TRX_ID_INT


Post SQL : 



Target9 Name : EX_OPL_XXGCO_RTR_ATTRIB_CV


Pre SQL : 
DELETE FROM $$EXCEPDB.EX_OPL_XXGCO_RTR_ATTRIB_CV WHERE EXCEPTION_TYPE = 'RI' ;


Post SQL : 
DELETE FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV WK 
 WHERE EXISTS ( SELECT 1 FROM $$EXCEPDB.EX_OPL_XXGCO_RTR_ATTRIB_CV EX WHERE EX.RTR_ATTRIBUTION_ID = WK.SK_RTR_ATTRIBUTION_ID) ;
 
 CALL COLLECT_STATS_WRAP('$$EXCEPDB','EX_OPL_XXGCO_RTR_ATTRIB_CV','D');
 

 INSERT INTO $$EXCEPDB.EX_OPL_XXGCO_RTR_ATTRIB_CV
SELECT
 ST.RECORD_OFFSET,
 ST.RTR_ATTRIBUTION_ID,
 ST.TRX_ID,
 ST.TRX_VERSION,
 ST.ATTRIBUTED_EXT_NET_PRICE,
 ST.ATTRIBUTED_UNIT_NET_PRICE,
 ST.ATTRIBUTED_PERCENTAGE,
 ST.ATTRIBUTED_QUANTITY,
 ST.ENTERPRISE_SKU_INV_ITM_ID,
 ST.COVERED_PRD_INV_ITM_ID,
 ST.AS_PARENT_SKU_INV_ITM_ID,
 ST.ARCHITECTURE_ID,
 ST.TECHNOLOGY_ID,
 ST.TXN_CR_PARTY_ID,
 ST.ERP_HEADER_ID,
 ST.ERP_LINE_ID,
 ST.ERP_SO_NUMBER,
 ST.ORDER_NUMBER,
 ST.LINE_REF_NUMBER,
 ST.SALES_MOTION,
 ST.SALES_MOTION_CONTEXT,
 ST.AS_TS_FLAG,
 ST.ITEM_CATEGORIZATION,
 ST.RECGD_ATTRIB_EXT_NET_PRICE,
 ST.RECGD_PERCENTAGE,
 ST.SS_CD,
 ST.OA_ATTRIBUTION_ID,
 ST.OFFER_TYPE_ID,
 ST.LIST_PRICE,
 ST.ATTR_PRDT_CLASS_NAME,
 ST.HQ_CR_PARTY_ID,
 ST.RENEWAL_REF_TYPE,
 ST.RENEWAL_REF_VALUE,
 ST.REASON_CODE,
 ST.SALES_MOTION_TIMING,
 ST.MANUAL_PROCESS_FLAG,
 ST.USER_ID,
 ST.CASE_NUMBER,
 ST.COMMENTS,
 ST.SMR_SALES_VALUE,
 ST.SMR_ACV_AMOUNT,
 ST.SMR_TCV_AMOUNT,
 ST.PRODUCT_CLASS,
 ST.RENEW_CLE_ID,
 ST.MANUAL_OVERRIDE_FLAG,
 ST.LINE_EXTENDED_PRICE,
 ST.EDW_CREATE_DTM,
 ST.PARTITION_NUMBER,
 ST.TOPIC_NAME,
 ST.INSTALL_SITE_LOCATION,
 'RI_ZERO_SPLIT' AS EXCEPTION_TYPE,
ST.POS_TRANSACTION_ID_INT,
ST.ORDER_ORIGIN_CD,
 ST.SK_TRX_ID_INT,
 ST.SK_OPL_HEADER_ID_INT,
 ST.RENEWAL_ERP_REF_VALUE
FROM
 $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV ST 
 INNER JOIN 
 ( SELECT  SK_ERP_BKGS_TRX_ID TRX_ID
    FROM ( SEL SALES_ORDER_LINE_KEY, SK_ERP_BKGS_TRX_ID
			FROM  $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV WI WHERE ITEM_CATEGORY_NAME NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' )
			AND ORDER_ORIGIN_CD NOT IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN )
				AND EXISTS ( SEL 1 FROM $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT_HIST_TV NSOL
				WHERE NSOL.SALES_ORDER_LINE_KEY = WI.SALES_ORDER_LINE_KEY
				AND NSOL.END_TV_DTM = '3500-01-01 00:00:00'
                          AND ORDER_ORIGIN_CD <> 'DISTI-DSV'
				AND NSOL.SS_CD = 'CG'
				AND (NSOL.ORDER_QTY*NSOL.UNIT_NET_PRICE_LOCAL_AMT) <> 0.0000 )
			GROUP BY 1,2 HAVING SUM(ATTR_PCT) = 0.000 
		) ERP_EX_LINES -- EXCEPTION CHECK FOR 0 SPLIT RTR DATA FOR 0 DOLLAR ERP LINES
	UNION
	SELECT SK_ERP_BKGS_TRX_ID TRX_ID
	FROM ( SEL SK_ERP_BKGS_TRX_ID
			FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV WI WHERE ( ITEM_CATEGORY_NAME IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' )
			OR ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )
				AND EXISTS ( SEL 1 FROM $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ITM_SLSTRX_NRT TRX
				WHERE TRX.SK_TRX_ID_INT = WI.SK_ERP_BKGS_TRX_ID
				AND TRX.RECOG_SALES_VALUE_LOCAL_AMT <> 0.0000
                         AND ORDER_ORIGIN_CD <> 'DISTI-DSV' )
			GROUP BY 1 HAVING SUM(ATTR_PCT) = 0.000
		) XAAS_EX_LINES
 ) WK
 ON ST.TRX_ID = WK.TRX_ID
AND ORDER_ORIGIN_CD <> 'DISTI-DSV' ;

 INSERT INTO $$EXCEPDB.EX_OPL_XXGCO_RTR_ATTRIB_CV
SELECT
 ST.RECORD_OFFSET,
 ST.RTR_ATTRIBUTION_ID,
 ST.TRX_ID,
 ST.TRX_VERSION,
 ST.ATTRIBUTED_EXT_NET_PRICE,
 ST.ATTRIBUTED_UNIT_NET_PRICE,
 ST.ATTRIBUTED_PERCENTAGE,
 ST.ATTRIBUTED_QUANTITY,
 ST.ENTERPRISE_SKU_INV_ITM_ID,
 ST.COVERED_PRD_INV_ITM_ID,
 ST.AS_PARENT_SKU_INV_ITM_ID,
 ST.ARCHITECTURE_ID,
 ST.TECHNOLOGY_ID,
 ST.TXN_CR_PARTY_ID,
 ST.ERP_HEADER_ID,
 ST.ERP_LINE_ID,
 ST.ERP_SO_NUMBER,
 ST.ORDER_NUMBER,
 ST.LINE_REF_NUMBER,
 ST.SALES_MOTION,
 ST.SALES_MOTION_CONTEXT,
 ST.AS_TS_FLAG,
 ST.ITEM_CATEGORIZATION,
 ST.RECGD_ATTRIB_EXT_NET_PRICE,
 ST.RECGD_PERCENTAGE,
 ST.SS_CD,
 ST.OA_ATTRIBUTION_ID,
 ST.OFFER_TYPE_ID,
 ST.LIST_PRICE,
 ST.ATTR_PRDT_CLASS_NAME,
 ST.HQ_CR_PARTY_ID,
 ST.RENEWAL_REF_TYPE,
 ST.RENEWAL_REF_VALUE,
 ST.REASON_CODE,
 ST.SALES_MOTION_TIMING,
 ST.MANUAL_PROCESS_FLAG,
 ST.USER_ID,
 ST.CASE_NUMBER,
 ST.COMMENTS,
 ST.SMR_SALES_VALUE,
 ST.SMR_ACV_AMOUNT,
 ST.SMR_TCV_AMOUNT,
 ST.PRODUCT_CLASS,
 ST.RENEW_CLE_ID,
 ST.MANUAL_OVERRIDE_FLAG,
 ST.LINE_EXTENDED_PRICE,
 ST.EDW_CREATE_DTM,
 ST.PARTITION_NUMBER,
 ST.TOPIC_NAME,
 ST.INSTALL_SITE_LOCATION,
 'RI_ZERO_SPLIT' AS EXCEPTION_TYPE,
ST.POS_TRANSACTION_ID_INT,
ST.ORDER_ORIGIN_CD,
 ST.SK_TRX_ID_INT,
 ST.SK_OPL_HEADER_ID_INT,
 ST.RENEWAL_ERP_REF_VALUE
FROM
 $$STGDB.ST_OPL_XXGCO_RTR_ATTRIB_CV ST 
 INNER JOIN (SELECT  SK_ERP_BKGS_TRX_ID TRX_ID,POS_TRANSACTION_ID_INT POS_TRX_ID
    FROM ( SEL  SK_ERP_BKGS_TRX_ID  , POS_TRANSACTION_ID_INT
			FROM  $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV WI WHERE  ORDER_ORIGIN_CD = 'DISTI-DSV'
				AND EXISTS ( SEL 1 FROM $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE NPOS
				WHERE NPOS.BK_POS_TRANSACTION_ID_INT = WI.POS_TRANSACTION_ID_INT
				AND ( VLDTD_NET_UNIT_PRICE_USD_AMT * POS_TRX_LINE_PRODUCT_QUANT ) <> 0.0000 )
			GROUP BY 1,2 HAVING SUM(ATTR_PCT) = 0.000 
		) POS_EX_LINES 
) WK
ON ST.POS_TRANSACTION_ID_INT = WK.POS_TRX_ID 
AND ORDER_ORIGIN_CD = 'DISTI-DSV';

 DELETE FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV WK 
 WHERE EXISTS ( SELECT 1 FROM $$EXCEPDB.EX_OPL_XXGCO_RTR_ATTRIB_CV EX WHERE EX.RTR_ATTRIBUTION_ID = WK.SK_RTR_ATTRIBUTION_ID) ;
 
 CALL COLLECT_STATS_WRAP('$$EXCEPDB','EX_OPL_XXGCO_RTR_ATTRIB_CV','D');