


Source1 Name : SQ_WI_POS_SCA_INCR_SC_BKG


Pre SQL : 
DELETE FROM $$STGDB.WI_POS_SCA_INCR_SC_BKG ALL;


SQL Query : 
SELECT 
	SCA.POS_SCAAC_KEY ,
	SCA.PD_BK_POS_TRANSACTION_ID_INT ,
	BK_TRX.BASE_LIST_UNIT_PRDT_PRICE_AMT AS BASE_LIST_UNIT_PROD_PRICE_AMT,
	BK_TRX.DSTRBTR_RPTD_CST_UNT_PRC_AMT  AS DISTI_RPTD_COST_UNIT_PRICE_AMT,
	BK_TRX.VALIDATED_NET_UNT_PRC_USD_AMT AS VLDTD_NET_UNIT_PRICE_USD_AMT,
	BK_TRX.VALUATION_PRICE_USD_AMT  AS VALUATION_PRICE_USD_AMOUNT     ,
	PD_SALES_TERRITORY_KEY,
	PD_SALES_REP_NUM,
	DISTRIBUTOR_OFFSET_FLG ,
	PD_SALES_COMMISSION_PCT ,
	SK3_SC_ID_INT AS SC_ID_INT,
	SCA.SOURCE_DELETED_FLG AS SOURCE_DELETED_FLG,
	SCA.LAST_UPDATED_DTM ,
	SCA.DV_LAST_UPDATED_DT,
	SCA.EDW_UPDATE_DTM,
	SALES_CREDIT_START_DTM AS START_TV_DTM,
	EXPIRATION_DTM AS END_TV_DTM,
	DISTRIBUTOR_BUCKET_FLG,
	BK_TRX.POS_TRX_LN_PRDT_QTY   ,
	SK_TRX_SC_ID_INT AS SK_TRX_SC_ID_INT,
   'DSV_BKG' AS DSV_OR_POS_TYPE_CD, /*ADDED AS PART OF DSV Q1FY16*/
	'N' AS POS_RETURN_ROLE /*ADDED AS PART OF DSV Q1FY16*/
	/* ADDED AS PART OF JUNE 2018 RELEASE AMY-NRT SCOPE*/
,BK_TRX.RU_SERVICE_CONTRACT_START_DTM
,BK_TRX.RU_SERVICE_CONTRACT_END_DTM
,BK_TRX.RU_SRVC_CNTRCT_DRTN_MNTHS_CNT

FROM $$NRTNCRVWDB.N_POS_SCA_ADJ_CNG_DRCT_NRT_TV SCA
INNER JOIN $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE_TV BK_TRX 
ON SCA.PD_BK_POS_TRANSACTION_ID_INT= BK_TRX.BK_POS_TRX_ID_INT 
WHERE SCA.LAST_UPDATED_DTM >'$$LastExtractDate'
AND SCA.START_TV_DTM >'$$LastExtractDate'
AND COALESCE(SALES_CREDIT_DUPLICATE_FLG    ,'N') = 'N' 
AND PD_BK_SALES_CREDIT_TYPE_CD = 'L'
AND SCA.DV_LAST_UPDATED_DT BETWEEN BK_TRX.START_TV_DT AND BK_TRX.END_TV_DT
 
UNION

SELECT 
	SCA.POS_SCAAC_KEY ,
	SCA.PD_BK_POS_TRANSACTION_ID_INT ,
	BK_TRX.BASE_LIST_UNIT_PRDT_PRICE_AMT AS BASE_LIST_UNIT_PROD_PRICE_AMT,
	BK_TRX.DSTRBTR_RPTD_CST_UNT_PRC_AMT  AS DISTI_RPTD_COST_UNIT_PRICE_AMT,
	BK_TRX.VALIDATED_NET_UNT_PRC_USD_AMT AS VLDTD_NET_UNIT_PRICE_USD_AMT,
	BK_TRX.VALUATION_PRICE_USD_AMT  AS VALUATION_PRICE_USD_AMOUNT     ,
	PD_SALES_TERRITORY_KEY,
	PD_SALES_REP_NUM,
	DISTRIBUTOR_OFFSET_FLG ,
	PD_SALES_COMMISSION_PCT ,
	SK3_SC_ID_INT AS SC_ID_INT,
	SCA.SOURCE_DELETED_FLG AS SOURCE_DELETED_FLG,
	SCA.LAST_UPDATED_DTM ,
	SCA.DV_LAST_UPDATED_DT,
	SCA.EDW_UPDATE_DTM,
	SALES_CREDIT_START_DTM AS START_TV_DTM,
	EXPIRATION_DTM AS END_TV_DTM,
	DISTRIBUTOR_BUCKET_FLG ,
	BK_TRX.POS_TRX_LN_PRDT_QTY   ,
	SK_TRX_SC_ID_INT AS SK_TRX_SC_ID_INT,
	'DSV_BKG' AS DSV_OR_POS_TYPE_CD, /*ADDED AS PART OF DSV Q1FY16*/
	'N' AS POS_RETURN_ROLE /*ADDED AS PART OF DSV Q1FY16*/
	/* ADDED AS PART OF JUNE 2018 RELEASE AMY-NRT SCOPE*/
,BK_TRX.RU_SERVICE_CONTRACT_START_DTM
,BK_TRX.RU_SERVICE_CONTRACT_END_DTM
,BK_TRX.RU_SRVC_CNTRCT_DRTN_MNTHS_CNT

FROM $$NRTNCRVWDB.N_POS_SCA_ADJ_CNG_DRCT_NRT_TV SCA
INNER JOIN $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE_TV BK_TRX 
ON SCA.PD_BK_POS_TRANSACTION_ID_INT= BK_TRX.BK_POS_TRX_ID_INT  
WHERE SCA.LAST_UPDATED_DTM >'$$LastExtractDate'
AND SCA.START_TV_DTM >'$$LastExtractDate'
AND SCA.SOURCE_DELETED_FLG = 'Y'
AND PD_BK_SALES_CREDIT_TYPE_CD = 'L'
AND SCA.DV_LAST_UPDATED_DT BETWEEN BK_TRX.START_TV_DT AND BK_TRX.END_TV_DT

UNION
 
SELECT 
	SCA.POS_SCAAC_KEY ,
	SCA.PD_BK_POS_TRANSACTION_ID_INT ,
	BK_TRX.BASE_LIST_UNIT_PRDT_PRICE_AMT AS BASE_LIST_UNIT_PROD_PRICE_AMT,
	BK_TRX.DSTRBTR_RPTD_CST_UNT_PRC_AMT  AS DISTI_RPTD_COST_UNIT_PRICE_AMT,
	BK_TRX.VALIDATED_NET_UNT_PRC_USD_AMT AS VLDTD_NET_UNIT_PRICE_USD_AMT,
	BK_TRX.VALUATION_PRICE_USD_AMT  AS VALUATION_PRICE_USD_AMOUNT     ,
	PD_SALES_TERRITORY_KEY,
	PD_SALES_REP_NUM,
	DISTRIBUTOR_OFFSET_FLG ,
	PD_SALES_COMMISSION_PCT ,
	SK3_SC_ID_INT AS SC_ID_INT,
	SCA.SOURCE_DELETED_FLG AS SOURCE_DELETED_FLG,
	SCA.LAST_UPDATED_DTM ,
	SCA.DV_LAST_UPDATED_DT,
	SCA.EDW_UPDATE_DTM,
	SALES_CREDIT_START_DTM AS START_TV_DTM,
	EXPIRATION_DTM AS END_TV_DTM,
	DISTRIBUTOR_BUCKET_FLG,
	BK_TRX.POS_TRX_LN_PRDT_QTY,
    SK_TRX_SC_ID_INT AS SK_TRX_SC_ID_INT,
	'DSV_BKG' AS DSV_OR_POS_TYPE_CD, /*ADDED AS PART OF DSV Q1FY16*/
	'N' AS POS_RETURN_ROLE /*ADDED AS PART OF DSV Q1FY16*/
/* ADDED AS PART OF JUNE 2018 RELEASE AMY-NRT SCOPE*/
,BK_TRX.RU_SERVICE_CONTRACT_START_DTM
,BK_TRX.RU_SERVICE_CONTRACT_END_DTM
,BK_TRX.RU_SRVC_CNTRCT_DRTN_MNTHS_CNT
	
FROM $$NRTNCRVWDB.N_POS_SCA_ADJ_CNG_DRCT_NRT_TV SCA
INNER JOIN $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE_TV BK_TRX 
ON SCA.PD_BK_POS_TRANSACTION_ID_INT= BK_TRX.BK_POS_TRX_ID_INT 
WHERE SCA.EDW_UPDATE_DTM > ( SEL LAST_EXTRACT_DATE FROM $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES WHERE JOB_STREAM_ID = 'wf_WI_POS_SCA_INCR_SC_BKG' ) 
AND SCA.START_TV_DTM <= '$$LastExtractDate'
AND SCA.END_TV_DTM = '3500-01-01 00:00:00' 
AND PD_BK_SALES_CREDIT_TYPE_CD = 'L'
AND (COALESCE(SALES_CREDIT_DUPLICATE_FLG    ,'N') = 'N' OR  SCA.SOURCE_DELETED_FLG = 'Y') /* ADDED AS A PART OF HANDLING SOURCE COMMIT ISSUE */
AND SCA.DV_LAST_UPDATED_DT BETWEEN BK_TRX.START_TV_DT AND BK_TRX.END_TV_DT
AND NOT EXISTS ( SEL 1 FROM $$SLSORDVWDB.N_DRVD_SCA_POS_ADJ_DETAILS N_DRVD 
                 WHERE N_DRVD.SK_TRX_SALES_CREDIT_ID_INT = SCA.SK_TRX_SC_ID_INT 
				  AND DV_LATEST_FLG = 'Y'
				   AND N_DRVD.SK_TRX_SALES_CREDIT_ID_INT <> - 999 
				   )

UNION

SELECT 
	SCA.POS_SCAAC_KEY ,
	SCA.PD_BK_POS_TRANSACTION_ID_INT ,
	BK_TRX.BASE_LIST_UNIT_PRDT_PRICE_AMT AS BASE_LIST_UNIT_PROD_PRICE_AMT,
	BK_TRX.DSTRBTR_RPTD_CST_UNT_PRC_AMT  AS DISTI_RPTD_COST_UNIT_PRICE_AMT,
	BK_TRX.VALIDATED_NET_UNT_PRC_USD_AMT AS VLDTD_NET_UNIT_PRICE_USD_AMT,
	BK_TRX.VALUATION_PRICE_USD_AMT  AS VALUATION_PRICE_USD_AMOUNT     ,
	PD_SALES_TERRITORY_KEY,
	PD_SALES_REP_NUM,
	DISTRIBUTOR_OFFSET_FLG ,
	PD_SALES_COMMISSION_PCT ,
	SK3_SC_ID_INT AS SC_ID_INT,
	SCA.SOURCE_DELETED_FLG AS SOURCE_DELETED_FLG,
	SCA.LAST_UPDATED_DTM ,
	SCA.DV_LAST_UPDATED_DT,
	SCA.EDW_UPDATE_DTM,
	SALES_CREDIT_START_DTM AS START_TV_DTM,
	EXPIRATION_DTM AS END_TV_DTM,
	DISTRIBUTOR_BUCKET_FLG ,
	BK_TRX.POS_TRX_LN_PRDT_QTY ,
    SK_TRX_SC_ID_INT AS SK_TRX_SC_ID_INT,
	'DSV_BKG' AS DSV_OR_POS_TYPE_CD, /*ADDED AS PART OF DSV Q1FY16*/
	 'N' AS POS_RETURN_ROLE /*ADDED AS PART OF DSV Q1FY16*/
/* ADDED AS PART OF JUNE 2018 RELEASE AMY-NRT SCOPE*/
,BK_TRX.RU_SERVICE_CONTRACT_START_DTM
,BK_TRX.RU_SERVICE_CONTRACT_END_DTM
,BK_TRX.RU_SRVC_CNTRCT_DRTN_MNTHS_CNT

FROM $$NRTNCRVWDB.N_POS_SCA_ADJ_CNG_DRCT_NRT_TV SCA
INNER JOIN $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE_TV BK_TRX 
ON SCA.PD_BK_POS_TRANSACTION_ID_INT= BK_TRX.BK_POS_TRX_ID_INT  
WHERE SCA.EDW_UPDATE_DTM > ( SEL LAST_EXTRACT_DATE FROM $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES WHERE JOB_STREAM_ID = 'wf_WI_POS_SCA_INCR_SC_BKG' )
AND SCA.LAST_UPDATED_DTM <= '$$LastExtractDate'
AND SCA.START_TV_DTM BETWEEN ( CAST('$$LastExtractDate' AS TIMESTAMP(0)) - INTERVAL '15' MINUTE) AND '$$LastExtractDate'
AND COALESCE(SALES_CREDIT_DUPLICATE_FLG    ,'N') = 'N' 
AND PD_BK_SALES_CREDIT_TYPE_CD = 'L'
AND SCA.DV_LAST_UPDATED_DT BETWEEN BK_TRX.START_TV_DT AND BK_TRX.END_TV_DT
AND NOT EXISTS ( SEL 1 FROM $$SLSORDVWDB.N_DRVD_SCA_POS_ADJ_DETAILS N_DRVD 
                 WHERE N_DRVD.SK_TRX_SALES_CREDIT_ID_INT =  SCA.SK_TRX_SC_ID_INT
                  AND N_DRVD.SK_TRX_SALES_CREDIT_ID_INT <> -999 )


Post SQL : 



Target1 Name : WI_POS_SCA_INCR_SC_BKG


Pre SQL : 



Post SQL : 
COLLECT STATS ON $$STGDB.WI_POS_SCA_INCR_SC_BKG;


Source2 Name : SQ_WI_POS_SCA_INC_NET_CHG_DT_BKG


Pre SQL : 
DELETE FROM $$STGDB.WI_POS_SCA_INC_NET_CHG_DT_BKG ALL;


SQL Query : 
SELECT
	POS_SCAAC_KEY,
	PD_BK_POS_TRANSACTION_ID_INT,
	BASE_LIST_UNIT_PROD_PRICE_AMT,
	DISTI_RPTD_COST_UNIT_PRICE_AMT,
	VLDTD_NET_UNIT_PRICE_USD_AMT,
	VALUATION_PRICE_USD_AMOUNT,
	PD_SALES_TERRITORY_KEY,
	PD_SALES_REP_NUM,
	DISTRIBUTOR_OFFSET_FLG,
	PD_SALES_COMMISSION_PCT,
	SC_ID_INT,
	SOURCE_DELETED_FLG,
	LAST_UPDATED_DTM,
	DV_LAST_UPDATED_DT,
	START_TV_DTM,
	END_TV_DTM,
    DISTRIBUTOR_BUCKET_FLG,
    POS_TRX_LN_PRDT_QTY	,
	CASE WHEN CAST(START_TV_DTM AS DATE ) = FISCAL_MONTH_END_DATE AND Cast(Substr(Cast( START_TV_DTM As varchar(20)),12,19) As Interval Hour(2) To Second(0))  BETWEEN CAST ('00:00:00' AS Interval Hour(2) To Second(0))  AND CAST('23:59:59' AS Interval Hour(2) To Second(0))
			THEN CAST( START_TV_DTM AS DATE )
		WHEN CAST( START_TV_DTM AS DATE ) = FISCAL_MONTH_START_DATE AND Cast(Substr(Cast( START_TV_DTM As varchar(20)),12,19) As Interval Hour(2) To Second(0))  BETWEEN CAST ('00:00:00' AS Interval Hour(2) To Second(0))  AND CAST('19:29:59' AS Interval Hour(2) To Second(0))
			THEN CAST ( START_TV_DTM AS DATE )
		WHEN ( CAST( START_TV_DTM AS DATE) > FISCAL_MONTH_START_DATE AND CAST( START_TV_DTM AS DATE) <  FISCAL_MONTH_END_DATE ) AND 
		( START_TV_DTM BETWEEN CAST (CAST( START_TV_DTM AS DATE ) - INTERVAL '1' DAY AS TIMESTAMP(0) ) + INTERVAL '19:30' HOUR TO MINUTE AND
		(CAST(CAST(START_TV_DTM AS DATE) AS TIMESTAMP(0) ) + INTERVAL '19:30' HOUR TO MINUTE ) )
			THEN CAST( START_TV_DTM AS DATE )
		WHEN ( CAST( START_TV_DTM AS DATE) >= FISCAL_MONTH_START_DATE AND CAST( START_TV_DTM AS DATE) <  FISCAL_MONTH_END_DATE ) AND 
		( START_TV_DTM BETWEEN CAST(CAST( START_TV_DTM AS DATE) AS TIMESTAMP(0) ) + INTERVAL '19:30' HOUR TO MINUTE AND
		CAST (CAST( START_TV_DTM AS DATE ) + INTERVAL '1' DAY AS TIMESTAMP(0) ) + INTERVAL '19:30' HOUR TO MINUTE )
			THEN  CAST( START_TV_DTM AS DATE ) + INTERVAL '1' DAY 		 
	END AS NET_CHANGE_PROCESS_DATE ,
	PDC.PROCESS_DATE,
	SK_TRX_SC_ID_INT,
	DSV_OR_POS_TYPE_CD, /*ADDED AS PART OF DSV Q1FY16*/	
	 POS_RETURN_ROLE /*ADDED AS PART OF DSV Q1FY16*/	
	 /* ADDED AS PART OF JUNE 2018 RELEASE AMY-NRT SCOPE*/
,RU_SERVICE_CONTRACT_START_DTM
,RU_SERVICE_CONTRACT_END_DTM
,RU_SRVC_CNTRCT_DRTN_MNTHS_CNT
FROM ( 
SELECT
	POS_SCAAC_KEY,
	PD_BK_POS_TRANSACTION_ID_INT,
	BASE_LIST_UNIT_PROD_PRICE_AMT,
	DISTI_RPTD_COST_UNIT_PRICE_AMT,
	VLDTD_NET_UNIT_PRICE_USD_AMT,
	VALUATION_PRICE_USD_AMOUNT,
	PD_SALES_TERRITORY_KEY,
	PD_SALES_REP_NUM,
	DISTRIBUTOR_OFFSET_FLG,
	PD_SALES_COMMISSION_PCT,
	SC_ID_INT,
	SOURCE_DELETED_FLG,
	LAST_UPDATED_DTM,
	DV_LAST_UPDATED_DT,
	START_TV_DTM,
	END_TV_DTM,
    DISTRIBUTOR_BUCKET_FLG,
    POS_TRX_LN_PRDT_QTY	,
	SK_TRX_SC_ID_INT,
	DSV_OR_POS_TYPE_CD, /*ADDED AS PART OF DSV Q1FY16*/	
	POS_RETURN_ROLE /*ADDED AS PART OF DSV Q1FY16*/
/* ADDED AS PART OF JUNE 2018 RELEASE AMY-NRT SCOPE*/
,RU_SERVICE_CONTRACT_START_DTM
,RU_SERVICE_CONTRACT_END_DTM
,RU_SRVC_CNTRCT_DRTN_MNTHS_CNT	
FROM $$STGDB.WI_POS_SCA_INCR_BKG WI_POS

UNION

SELECT
	POS_SCAAC_KEY,
	PD_BK_POS_TRANSACTION_ID_INT,
	BASE_LIST_UNIT_PROD_PRICE_AMT,
	DISTI_RPTD_COST_UNIT_PRICE_AMT,
	VLDTD_NET_UNIT_PRICE_USD_AMT,
	VALUATION_PRICE_USD_AMOUNT,
	PD_SALES_TERRITORY_KEY,
	PD_SALES_REP_NUM,
	DISTRIBUTOR_OFFSET_FLG,
	PD_SALES_COMMISSION_PCT,
	SC_ID_INT,
	SOURCE_DELETED_FLG,
	LAST_UPDATED_DTM,
	DV_LAST_UPDATED_DT,
	START_TV_DTM,
	END_TV_DTM,
    DISTRIBUTOR_BUCKET_FLG,	
    POS_TRX_LN_PRDT_QTY,
	SK_TRX_SC_ID_INT,
	DSV_OR_POS_TYPE_CD,/*ADDED AS PART OF DSV Q1FY16*/	
	POS_RETURN_ROLE /*ADDED AS PART OF DSV Q1FY16*/	
	/* ADDED AS PART OF JUNE 2018 RELEASE AMY-NRT SCOPE*/
,RU_SERVICE_CONTRACT_START_DTM
,RU_SERVICE_CONTRACT_END_DTM
,RU_SRVC_CNTRCT_DRTN_MNTHS_CNT
FROM $$STGDB.WI_POS_SCA_INCR_SC_BKG WI_SCA 
WHERE NOT EXISTS( SELECT 1 FROM $$STGDB.WI_POS_SCA_INCR_BKG WI
				  WHERE WI_SCA.POS_SCAAC_KEY = WI.POS_SCAAC_KEY 
                ) 
) WI , $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR FDY,
(SELECT PROCESS_DATE FROM $$ETLVWDB.BKG_PROCESS_DT_CNTRL ) PDC
WHERE CAST(WI.START_TV_DTM AS DATE) = FDY.CALENDAR_DATE


Post SQL : 



Target2 Name : WI_POS_SCA_INC_NET_CHG_DT_BKG


Pre SQL : 



Post SQL : 
COLLECT STATS ON $$STGDB.WI_POS_SCA_INC_NET_CHG_DT_BKG;


Source3 Name : SQ_WI_POS_SCA_BKG


Pre SQL : 
DELETE FROM $$STGDB.WI_POS_SCA_BKG ALL;


SQL Query : 
SELECT 
POS_SCAAC_KEY
,PD_BK_POS_TRANSACTION_ID_INT
,BASE_LIST_UNIT_PROD_PRICE_AMT
,DISTI_RPTD_COST_UNIT_PRICE_AMT
,VLDTD_NET_UNIT_PRICE_USD_AMT
,VALUATION_PRICE_USD_AMOUNT    
,PD_SALES_TERRITORY_KEY        
,COALESCE(SC_TEAM.SHR_IND_SALESREP_NUMBER , INCR.PD_SALES_REP_NUM ) AS SALES_REP_NUM
,DISTRIBUTOR_OFFSET_FLG        
/*,COALESCE(SC_TEAM.SHR_IND_SPLIT_PERCENT * 100, INCR.PD_SALES_COMMISSION_PCT ) AS SALES_COMMISSION_PCT*/
 ,CASE WHEN SC_TEAM.SHR_IND_SPLIT_PERCENT IS NULL THEN(INCR.PD_SALES_COMMISSION_PCT) ELSE (SC_TEAM.SHR_IND_SPLIT_PERCENT *INCR.PD_SALES_COMMISSION_PCT) END PD_SALES_COMMISSION_PCT /* modified as part of team split CR by ugandhav */
,SC_ID_INT                     
,SOURCE_DELETED_FLG            
,LAST_UPDATED_DTM              
,DV_LAST_UPDATED_DT            
,START_TV_DTM                  
,END_TV_DTM                    
,DISTRIBUTOR_BUCKET_FLG        
,POS_TRX_LN_PRDT_QTY           
,NET_CHANGE_PROCESS_DT   
,SK_TRX_SC_ID_INT
,DSV_OR_POS_TYPE_CD/*ADDED AS PART OF DSV Q1FY16*/	
,POS_RETURN_ROLE /*ADDED AS PART OF DSV Q1FY16*/
/* ADDED AS PART OF JUNE 2018 RELEASE AMY-NRT SCOPE*/
,RU_SERVICE_CONTRACT_START_DTM
,RU_SERVICE_CONTRACT_END_DTM
,RU_SRVC_CNTRCT_DRTN_MNTHS_CNT 
FROM
$$STGDB.WI_POS_SCA_INC_NET_CHG_DT_BKG INCR
LEFT JOIN $$ETLVWDB.EL_OTM_PHX_SC_TEAM SC_TEAM
ON SC_TEAM.SC_ID=INCR.SC_ID_INT 
WHERE INCR.START_TV_DTM <> INCR.END_TV_DTM


Post SQL : 



Target3 Name : WI_POS_SCA_BKG


Pre SQL : 



Post SQL : 
COLLECT STATS ON $$STGDB.WI_POS_SCA_BKG;


UPDATE $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES
    SET LAST_EXTRACT_DATE = (SEL MAX(EDW_UPDATE_DTM) FROM $$NRTNCRVWDB.N_POS_SCA_ADJ_CNG_DRCT_NRT_TV )
   WHERE JOB_STREAM_ID = 'wf_WI_POS_SCA_INCR_SC_BKG'  AND TABLE_NAME = 'N_POS_SCA_ADJ_CNG_DRCT_NRT_TV' ;