


Source1 Name : SQ_WI_SOL_OFFER_ATTRIB_UOBO


Pre SQL : 
DELETE FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO ALL;
 
 COLLECT STATS ON $$NRTSTGDB.ST_UO_XXOA_ORDER_ATTRIB;
 COLLECT STATS ON $$NRTSTGDB.ST_BO_XXOA_ORDER_ATTRIB;
 
 /*DELETE  EXCEPTION records that have latest updates from Source*/
 DELETE FROM $$EXCEPDB.EX_XXOA_ORDER_ATTRIB EXOA
 WHERE EXISTS (SELECT 1 FROM $$NRTSTGDB.ST_UO_XXOA_ORDER_ATTRIB SOA 
  WHERE EXOA.OA_ATTRIB_ID = SOA.OA_ATTRIB_ID  AND EXOA.GLOBAL_NAME = SOA.GLOBAL_NAME)
 OR EXISTS (SELECT 1 FROM $$NRTSTGDB.ST_BO_XXOA_ORDER_ATTRIB SOA 
  WHERE EXOA.OA_ATTRIB_ID = SOA.OA_ATTRIB_ID  AND EXOA.GLOBAL_NAME = SOA.GLOBAL_NAME)
 ;                     

 
/* Q1FY15 CR */
DELETE FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_DELS WHERE GLOBAL_NAME IN ('UO', 'BO');
 
/* Q1FY15 CR - OA Populate DELETES */
INSERT INTO $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_DELS
SELECT 
	  STOA1.OA_ATTRIB_ID
	, STOA1.SS_CD
	, STOA1.GLOBAL_NAME
	, STOA1.SOURCE_COMMIT_TIME
FROM(
 SELECT
	STOA.OA_ATTRIB_ID, 
	NSSC.SOURCE_SYSTEM_CODE AS SS_CD,
	STOA.GLOBAL_NAME, 
	STOA.SOURCE_COMMIT_TIME
FROM	$$NRTSTGDB.ST_UO_XXOA_ORDER_ATTRIB STOA
	INNER JOIN $$COMREFVWDB.N_SOURCE_SYSTEM_CODES NSSC
	  ON NSSC.GLOBAL_NAME = STOA.GLOBAL_NAME
WHERE	STOA.SOURCE_DML_TYPE = 'DELETE' 
QUALIFY ROW_NUMBER () OVER (PARTITION BY STOA.OA_ATTRIB_ID ORDER BY STOA.SOURCE_COMMIT_TIME  DESC, REFRESH_DATETIME DESC)=1

UNION ALL

 SELECT
	STOA.OA_ATTRIB_ID, 
	NSSC.SOURCE_SYSTEM_CODE AS SS_CD,
	STOA.GLOBAL_NAME, 
	STOA.SOURCE_COMMIT_TIME
FROM	$$NRTSTGDB.ST_BO_XXOA_ORDER_ATTRIB STOA
	INNER JOIN $$COMREFVWDB.N_SOURCE_SYSTEM_CODES NSSC
	  ON NSSC.GLOBAL_NAME = STOA.GLOBAL_NAME
WHERE	STOA.SOURCE_DML_TYPE = 'DELETE' 
QUALIFY ROW_NUMBER () OVER (PARTITION BY STOA.OA_ATTRIB_ID ORDER BY STOA.SOURCE_COMMIT_TIME  DESC, REFRESH_DATETIME DESC)=1
)STOA1  /*Added REFRESH_DATETIME column as part of Q3FY15*/
;

COLLECT STATS $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_DELS ;


/* CLOSE  OA  3NF records   that have latest deletes from source   Q1FY15 - OA */
UPDATE NSOAT
FROM $$NRTNCRVWDB.N_SOL_OFFER_ATTRIBUTION_TV NSOAT, 
 $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_DELS  WI_DELS
SET  END_TV_DTM = WI_DELS.SOURCE_COMMIT_TIME,
	EDW_UPDATE_DTM=CURRENT_TIMESTAMP(0),
	EDW_UPDATE_USER = USER               
WHERE NSOAT.SK_OFFER_ATTRIBUTION_ID_INT = WI_DELS.OA_ATTRIB_ID
AND NSOAT.SS_CD = WI_DELS.SS_CD
AND WI_DELS.GLOBAL_NAME IN ('UO', 'BO')
AND NSOAT.END_TV_DTM = CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)) ;


SQL Query : 
SELECT 
     SXOA.BATCH_ID
   , SXOA.OA_ATTRIB_ID
   , SXOA.ORDER_NUMBER
   , SXOA.HEADER_ID
   , SXOA.DATA_SOURCE
   , SXOA.LINE_ID
   , SXOA.PARENT_LINE_ID
   , SXOA.ORDERED_ITEM
   , SXOA.INVENTORY_ITEM_ID
   , SXOA.ATTRIBUTION_FLAG
   , SXOA.CISCO_BOOKED_FLAG
   , SXOA.BUNDLE_TYPE
   , SXOA.QUANTITY
   , SXOA.ATTRIBUTED_UNIT_LIST_PRICE
   , SXOA.ATTRIBUTED_UNIT_NET_PRICE
   , SXOA.BOOKINGS_PCT
   , SXOA.ATTRIBUTED_PCT
   , SXOA.PUBLISH_FLAG
   , SXOA.TRX_TYPE
   , SXOA.CREATED_BY
   , SXOA.CREATION_DATE
   , SXOA.LAST_UPDATED_BY
   , SXOA.LAST_UPDATE_DATE
   , SXOA.ORIG_OA_ATTRIB_ID
   , SXOA.ACTION_CODE
   , SXOA.CREATE_DATETIME
   , SXOA.GLOBAL_NAME
   , SXOA.SOURCE_DML_TYPE
   , SXOA.SOURCE_COMMIT_TIME
   , CASE WHEN (SXOA.LINE_ID IS NOT NULL AND SXOA.PARENT_LINE_ID IS NOT NULL) THEN  NSOLH1.SALES_ORDER_LINE_KEY
		   ELSE -9999 END  AS SALES_ORDER_LINE_KEY /* Q3FY15 OA Sub SKU Line */ 
   , NP.ITEM_KEY AS ATTRIBUTED_PRODUCT_KEY
   , NSOLH.PRODUCT_KEY AS BUNDLE_PRODUCT_KEY
   , NSOLH.ORDER_QTY AS BUNDLE_ORDER_QTY
   , NSOLH.BOOKINGS_PCT AS BUNDLE_BOOKINGS_PCT
   , NSOLH.UNIT_NET_PRICE_LOCAL_AMT AS BUNDLE_NET_PRICE_LOCAL_AMT
   , NULL AS BUNDLE_CISCO_BOOKED_FLAG
   , NSOLH.SS_CD
   , 'SRC' AS DV_DATA_SRC_CD
   , 'Y' AS VALID_FLG
   , 'NE' AS EXCEPTION_TYPE
   ,SXOA.EXCEPTION_CODE AS EXCEPTION_REASON_CD/*Added this as part of OA-Q2FY15 */
   ,NSOLH.SALES_ORDER_LINE_KEY AS TOP_SKU_SALES_ORDER_LINE_KEY /* Added as part of OA-Q3FY15*/
   ,CASE WHEN SXOA.PARENT_LINE_ID IS NULL THEN 'OFFSET' ELSE 'ATTRIBUTED' END AS ATTRIBUTION_CD /* Added as part of OA-Q3FY15*/
   ,SXOA.ATTRIBUTION_CODE /* Added as part of OA-Q1FY16*/
   ,SXOA.EXCEPTION_DETAIL  /* Added as part of OA-Q1FY16*/
   FROM $$NRTSTGDB.ST_UO_XXOA_ORDER_ATTRIB SXOA
     INNER JOIN $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT_HIST_TV NSOLH /* TOP SKU line */
     ON COALESCE(SXOA.PARENT_LINE_ID, SXOA.LINE_ID) = NSOLH.SK_SALES_ORDER_LINE_ID_INT /*Q3FY15 - OA*/
     AND CAST(NSOLH.END_TV_DTM AS DATE) = '3500-01-01'
     AND NSOLH.SS_CD = 'QTC'
     AND SXOA.SOURCE_DML_TYPE <>'DELETE'   /*Q1FY15 - OA*/
     INNER JOIN $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT_HIST_TV NSOLH1  /* SUB SKU line */ /*Q3FY15 - OA*/
     ON COALESCE(SXOA.LINE_ID, SXOA.PARENT_LINE_ID) = NSOLH1.SK_SALES_ORDER_LINE_ID_INT 
     AND CAST(NSOLH1.END_TV_DTM AS DATE) = '3500-01-01'
     AND NSOLH1.SS_CD = 'QTC'
    INNER JOIN $$COMREFVWDB.N_PRODUCT NP 
     ON(SXOA.INVENTORY_ITEM_ID = NP.SK_INVENTORY_ITEM_ID_INT) 
    INNER JOIN $$COMREFVWDB.N_SOURCE_SYSTEM_CODES NSSC 
     ON ( NSSC.SOURCE_SYSTEM_CODE = NSOLH.SS_CD
     AND NSSC.GLOBAL_NAME = SXOA.GLOBAL_NAME )
   WHERE NSOLH.PRODUCT_KEY <> -999
    AND NOT EXISTS     /*Q2FY15 -OA  Donot consider records that also have DELETES */
  (
   SELECT 1
   FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_DELS WI_DELS
   WHERE SXOA.OA_ATTRIB_ID = WI_DELS.OA_ATTRIB_ID  
    AND SXOA.GLOBAL_NAME = WI_DELS.GLOBAL_NAME 
  )
   QUALIFY ROW_NUMBER () OVER (PARTITION BY SXOA.OA_ATTRIB_ID ORDER BY SXOA.SOURCE_COMMIT_TIME DESC, SXOA.REFRESH_DATETIME DESC)=1   /* Q1FY15 - OA   Added REFRESH_DATETIME column as part of Q3FY15*/
   
   UNION ALL
    SELECT 
     SXOA.BATCH_ID
   , SXOA.OA_ATTRIB_ID
   , SXOA.ORDER_NUMBER
   , SXOA.HEADER_ID
   , SXOA.DATA_SOURCE
   , SXOA.LINE_ID
   , SXOA.PARENT_LINE_ID
   , SXOA.ORDERED_ITEM
   , SXOA.INVENTORY_ITEM_ID
   , SXOA.ATTRIBUTION_FLAG
   , SXOA.CISCO_BOOKED_FLAG
   , SXOA.BUNDLE_TYPE
   , SXOA.QUANTITY
   , SXOA.ATTRIBUTED_UNIT_LIST_PRICE
   , SXOA.ATTRIBUTED_UNIT_NET_PRICE
   , SXOA.BOOKINGS_PCT
   , SXOA.ATTRIBUTED_PCT
   , SXOA.PUBLISH_FLAG
   , SXOA.TRX_TYPE
   , SXOA.CREATED_BY
   , SXOA.CREATION_DATE
   , SXOA.LAST_UPDATED_BY
   , SXOA.LAST_UPDATE_DATE
   , SXOA.ORIG_OA_ATTRIB_ID
   , SXOA.ACTION_CODE
   , SXOA.CREATE_DATETIME
   , SXOA.GLOBAL_NAME
   , SXOA.SOURCE_DML_TYPE
   , SXOA.SOURCE_COMMIT_TIME
   , CASE WHEN (SXOA.LINE_ID IS NOT NULL AND SXOA.PARENT_LINE_ID IS NOT NULL) THEN  NSOLH1.SALES_ORDER_LINE_KEY
		   ELSE -9999 END  AS SALES_ORDER_LINE_KEY /* Q3FY15 OA Sub SKU Line */ 
   , NP.ITEM_KEY AS ATTRIBUTED_PRODUCT_KEY
   , NSOLH.PRODUCT_KEY AS BUNDLE_PRODUCT_KEY
   , NSOLH.ORDER_QTY AS BUNDLE_ORDER_QTY
   , NSOLH.BOOKINGS_PCT AS BUNDLE_BOOKINGS_PCT
   , NSOLH.UNIT_NET_PRICE_LOCAL_AMT AS BUNDLE_NET_PRICE_LOCAL_AMT
   , NULL AS BUNDLE_CISCO_BOOKED_FLAG
   , NSOLH.SS_CD
   , 'SRC' AS DV_DATA_SRC_CD
   , 'Y' AS VALID_FLG
   , 'NE' AS EXCEPTION_TYPE
   ,SXOA.EXCEPTION_CODE AS EXCEPTION_REASON_CD/*Added this as part of OA-Q2FY15 */
   ,NSOLH.SALES_ORDER_LINE_KEY AS TOP_SKU_SALES_ORDER_LINE_KEY /* Added as part of OA-Q3FY15*/
   ,CASE WHEN SXOA.PARENT_LINE_ID IS NULL THEN 'OFFSET' ELSE 'ATTRIBUTED' END AS ATTRIBUTION_CD /* Added as part of OA-Q3FY15*/
   ,SXOA.ATTRIBUTION_CODE /* Added as part of OA-Q1FY16*/
   ,SXOA.EXCEPTION_DETAIL  /* Added as part of OA-Q1FY16*/
   FROM $$NRTSTGDB.ST_BO_XXOA_ORDER_ATTRIB SXOA
     INNER JOIN $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT_HIST_TV NSOLH /* TOP SKU line */
     ON COALESCE(SXOA.PARENT_LINE_ID, SXOA.LINE_ID) = NSOLH.SK_SALES_ORDER_LINE_ID_INT /*Q3FY15 - OA*/
     AND CAST(NSOLH.END_TV_DTM AS DATE) = '3500-01-01'
     AND NSOLH.SS_CD = 'BV'
     AND SXOA.SOURCE_DML_TYPE <>'DELETE'   /*Q1FY15 - OA*/
     INNER JOIN $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT_HIST_TV NSOLH1  /* SUB SKU line */ /*Q3FY15 - OA*/
     ON COALESCE(SXOA.LINE_ID, SXOA.PARENT_LINE_ID) = NSOLH1.SK_SALES_ORDER_LINE_ID_INT 
     AND CAST(NSOLH1.END_TV_DTM AS DATE) = '3500-01-01'
     AND NSOLH1.SS_CD = 'BV'
    INNER JOIN $$COMREFVWDB.N_PRODUCT NP 
     ON(SXOA.INVENTORY_ITEM_ID = NP.SK_INVENTORY_ITEM_ID_INT) 
    INNER JOIN $$COMREFVWDB.N_SOURCE_SYSTEM_CODES NSSC 
     ON ( NSSC.SOURCE_SYSTEM_CODE = NSOLH.SS_CD
     AND NSSC.GLOBAL_NAME = SXOA.GLOBAL_NAME )
   WHERE NSOLH.PRODUCT_KEY <> -999
    AND NOT EXISTS   /*Q2FY15 -OA  Donot consider records that also have DELETES */
  (
   SELECT 1
   FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_DELS WI_DELS
   WHERE SXOA.OA_ATTRIB_ID = WI_DELS.OA_ATTRIB_ID  
    AND SXOA.GLOBAL_NAME = WI_DELS.GLOBAL_NAME 
  )
   QUALIFY ROW_NUMBER () OVER (PARTITION BY SXOA.OA_ATTRIB_ID ORDER BY SXOA.SOURCE_COMMIT_TIME DESC, SXOA.REFRESH_DATETIME DESC)=1   /* Q1FY15 - OA  Added REFRESH_DATETIME column as part of Q3FY15*/
    
   UNION  ALL
   SELECT 
     EXOA.BATCH_ID
   , EXOA.OA_ATTRIB_ID
   , EXOA.ORDER_NUMBER
   , EXOA.HEADER_ID
   , EXOA.DATA_SOURCE
   , EXOA.LINE_ID
   , EXOA.PARENT_LINE_ID
   , EXOA.ORDERED_ITEM
   , EXOA.INVENTORY_ITEM_ID
   , EXOA.ATTRIBUTION_FLAG
   , EXOA.CISCO_BOOKED_FLAG
   , EXOA.BUNDLE_TYPE
   , EXOA.QUANTITY
   , EXOA.ATTRIBUTED_UNIT_LIST_PRICE
   , EXOA.ATTRIBUTED_UNIT_NET_PRICE
   , EXOA.BOOKINGS_PCT
   , EXOA.ATTRIBUTED_PCT
   , EXOA.PUBLISH_FLAG
   , EXOA.TRX_TYPE
   , EXOA.CREATED_BY
   , EXOA.CREATION_DATE
   , EXOA.LAST_UPDATED_BY
   , EXOA.LAST_UPDATE_DATE
   , EXOA.OA_ATTRIB_ID AS ORIG_OA_ATTRIB_ID
   , EXOA.ACTION_CODE
   , EXOA.CREATE_DATETIME
   , EXOA.GLOBAL_NAME
   , EXOA.SOURCE_DML_TYPE
   , EXOA.SOURCE_COMMIT_TIME
   , CASE WHEN (EXOA.LINE_ID IS NOT NULL AND EXOA.PARENT_LINE_ID IS NOT NULL) THEN  NSOLH1.SALES_ORDER_LINE_KEY
		   ELSE -9999 END  AS SALES_ORDER_LINE_KEY /* Q3FY15 OA Sub SKU Line */    
   , NP.ITEM_KEY AS ATTRIBUTED_PRODUCT_KEY
   , NSOLH.PRODUCT_KEY AS BUNDLE_PRODUCT_KEY
   , NSOLH.ORDER_QTY AS BUNDLE_ORDER_QTY
   , NSOLH.BOOKINGS_PCT AS BUNDLE_BOOKINGS_PCT
   , NSOLH.UNIT_NET_PRICE_LOCAL_AMT AS BUNDLE_NET_PRICE_LOCAL_AMT
   , NULL AS BUNDLE_CISCO_BOOKED_FLAG
   , NSOLH.SS_CD
   , 'SRC' AS DV_DATA_SRC_CD
   , 'Y' AS VALID_FLG
   , 'NE' AS EXCEPTION_TYPE
   ,EXOA.EXCEPTION_CODE AS EXCEPTION_REASON_CD/*Added this as part of OA-Q2FY15 */
   ,NSOLH.SALES_ORDER_LINE_KEY AS TOP_SKU_SALES_ORDER_LINE_KEY /* Added as part of OA-Q3FY15*/
   ,CASE WHEN EXOA.PARENT_LINE_ID IS NULL THEN 'OFFSET' ELSE 'ATTRIBUTED' END AS ATTRIBUTION_CD /* Added as part of OA-Q3FY15*/
   ,EXOA.ATTRIBUTION_CODE /* Added as part of OA-Q1FY16*/
   ,EXOA.EXCEPTION_DETAIL /* Added as part of OA-Q1FY16*/
   FROM $$EXCEPDB.EX_XXOA_ORDER_ATTRIB EXOA
     INNER JOIN $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT_HIST_TV NSOLH /* TOP SKU line */
     ON COALESCE(EXOA.PARENT_LINE_ID, EXOA.LINE_ID) = NSOLH.SK_SALES_ORDER_LINE_ID_INT /*Q3FY15 - OA*/
     AND CAST(NSOLH.END_TV_DTM AS DATE) = '3500-01-01'
     AND NSOLH.SS_CD = (CASE WHEN EXOA.GLOBAL_NAME = 'UO' THEN 'QTC' WHEN EXOA.GLOBAL_NAME = 'BO' THEN 'BV' END)
	 LEFT JOIN $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT_HIST_TV NSOLH1  /* SUB SKU line */ /*Q3FY15 - OA*/
     ON COALESCE(EXOA.LINE_ID,EXOA.PARENT_LINE_ID) = NSOLH1.SK_SALES_ORDER_LINE_ID_INT 
     AND CAST(NSOLH1.END_TV_DTM AS DATE) = '3500-01-01'
	 AND NSOLH1.SS_CD = (CASE WHEN EXOA.GLOBAL_NAME = 'UO' THEN 'QTC' WHEN EXOA.GLOBAL_NAME = 'BO' THEN 'BV' END)
    INNER JOIN $$COMREFVWDB.N_PRODUCT NP 
     ON(EXOA.INVENTORY_ITEM_ID = NP.SK_INVENTORY_ITEM_ID_INT) 
    INNER JOIN $$COMREFVWDB.N_SOURCE_SYSTEM_CODES NSSC 
     ON ( NSSC.SOURCE_SYSTEM_CODE = NSOLH.SS_CD
     AND NSSC.GLOBAL_NAME = EXOA.GLOBAL_NAME )
   WHERE NSOLH.PRODUCT_KEY <> -999


Post SQL : 



Target1 Name : WI_SOL_OFFER_ATTRIB_UOBO1


Pre SQL : 



Post SQL : 



Source2 Name : SQ_WI_SOL_OFFER_ATTRIB_UOBO1


Pre SQL : 



SQL Query : 
SELECT 
     1 AS BATCH_ID
  , NSOA.SK_OFFER_ATTRIBUTION_ID_INT AS OA_ATTRIB_ID
  , 0 AS ORDER_NUMBER
  , 0 AS HEADER_ID
  , '=' AS DATA_SOURCE
  , 0 AS LINE_ID
  , 0 AS PARENT_LINE_ID
  , '=' AS ORDERED_ITEM
  , 0 AS INVENTORY_ITEM_ID
  , NSOA.ATTRIBUTION_TOP_SKU_FLG    AS ATTRIBUTION_FLAG
  , NSOA.CISCO_BOOKED_ATTRIBUTION_FLG AS CISCO_BOOKED_FLAG
  , '=' BUNDLE_TYPE
  , NSOA.PRODUCT_ATTRIBUTED_QTY AS QUANTITY
  , NSOA.UNIT_LIST_PRICE_USD_AMT  AS ATTRIBUTED_UNIT_LIST_PRICE
  , NSOA.UNIT_SELLING_PRC_TRX_AMT AS ATTRIBUTED_UNIT_NET_PRICE
  , NSOA.BOOKINGS_PCT AS BOOKINGS_PCT
  , NSOA.ATTRIBUTION_PCT AS ATTRIBUTED_PCT
  , '=' AS PUBLISH_FLAG
  , '=' AS TRX_TYPE
  , 0 AS CREATED_BY
  , NSOA.EDW_CREATE_DTM AS CREATION_DATE
  , 0 AS LAST_UPDATED_BY
  , NSOA.EDW_UPDATE_DTM AS LAST_UPDATE_DATE
  , NSOA.SK_OFFER_ATTRIBUTION_ID_INT AS ORIG_OA_ATTRIB_ID
  , '=' AS ACTION_CODE
  , NSOA.EDW_CREATE_DTM AS CREATE_DATETIME
  , '=' AS GLOBAL_NAME
  , '=' AS SOURCE_DML_TYPE
  , NSOA.EDW_UPDATE_DTM AS SOURCE_COMMIT_TIME
  , NSOA.SALES_ORDER_LINE_KEY
  , NSOA.ATTRIBUTED_PRODUCT_KEY AS ATTRIBUTED_PRODUCT_KEY
  , NSOLH.PRODUCT_KEY AS BUNDLE_PRODUCT_KEY
  , NSOLH.ORDER_QTY AS BUNDLE_ORDER_QTY
  , NSOLH.BOOKINGS_PCT AS BUNDLE_BOOKINGS_PCT
  , NSOLH.UNIT_NET_PRICE_LOCAL_AMT AS BUNDLE_NET_PRICE_LOCAL_AMT
  , NULL AS BUNDLE_CISCO_BOOKED_FLAG
  , NSOLH.SS_CD
  , 'EDW' AS DV_DATA_SRC_CD
  , 'Y' AS VALID_FLG
  , 'NE' AS EXCEPTION_TYPE
  , NSOA.EXCEPTION_REASON_CD AS EXCEPTION_CODE /*Added this as part of OA-Q2FY15 */
   ,NSOA.TOP_SKU_SALES_ORDER_LINE_KEY  AS TOP_SKU_SALES_ORDER_LINE_KEY   /* Added as part of OA-Q3FY15*/
   ,NSOA.ATTRIBUTION_CD AS ATTRIBUTION_CD /* Added as part of OA-Q3FY15*/
   ,'=' AS ATTRIBUTION_CODE /*OA-Q1FY16*/
   ,NSOA.EXCEPTION_DETAIL_DESCR AS EXCEPTION_DETAIL /* Added as part of OA-Q1FY16*/
  FROM $$NRTNCRVWDB.N_SOL_OFFER_ATTRIBUTION_TV NSOA    /*Q1FY15 -- OA*/
  INNER JOIN $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT_HIST_TV NSOLH
   ON NSOA.TOP_SKU_SALES_ORDER_LINE_KEY = NSOLH.SALES_ORDER_LINE_KEY
   AND NSOLH.SS_CD = NSOA.SS_CD
   AND CAST(NSOLH.END_TV_DTM AS DATE) = '3500-01-01'  
   AND CAST(NSOA.END_TV_DTM AS DATE) = '3500-01-01' 
  WHERE EXISTS (
  /* consider only the Sales Order Lines that are present in WI */
   SELECT 1
   FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISO
   WHERE WISO.TOP_SKU_SALES_ORDER_LINE_KEY = NSOA.TOP_SKU_SALES_ORDER_LINE_KEY 
  )
  AND NOT EXISTS
  (
  /* Pull the attributed/offset lines that are not available in incremental source data ( no updates from source in the current incremental run) */
   SELECT 1
   FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISO
   WHERE WISO.TOP_SKU_SALES_ORDER_LINE_KEY = NSOA.TOP_SKU_SALES_ORDER_LINE_KEY
   AND WISO.OA_ATTRIB_ID = NSOA.SK_OFFER_ATTRIBUTION_ID_INT
  )


Post SQL : 



Target2 Name : WI_SOL_OFFER_ATTRIB_UOBO3


Pre SQL : 



Post SQL : 
COLLECT STATS $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO;
 
 UPDATE WISO
 FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISO,
 (
 SELECT TOP_SKU_SALES_ORDER_LINE_KEY, EXCEPTION_TYPE
 FROM(
  /* SOLs Invalid due to Attribution Percent of all ATTRIBUTED lines not summing to 100% */
 SELECT TOP_SKU_SALES_ORDER_LINE_KEY , CAST('ATTRIB_PCT_INVALID' AS VARCHAR(30)) AS EXCEPTION_TYPE, 
 1 AS EXCP_PRIORITY, SUM(COALESCE(ATTRIBUTED_PCT,999)) AS SUM_PCT
 FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISO
 WHERE ATTRIBUTED_PRODUCT_KEY <> BUNDLE_PRODUCT_KEY
 GROUP BY 1
 HAVING SUM_PCT  <> 100.00000000   /*OA-Q3FY15*/
 UNION 
 /* SOLs Invalid due to Attribution Percent of OFFSET lines not  equal to 100% OR Offset Quantity is not matching to Bundle Oty
 */
 SELECT TOP_SKU_SALES_ORDER_LINE_KEY , 'OFFSET_INVALID' AS EXCEPTION_TYPE, 2 AS EXCP_PRIORITY, 
 COALESCE(ATTRIBUTED_PCT,999) AS ATTRIBUTED_PCT
 FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISO
 WHERE (ATTRIBUTED_PRODUCT_KEY = BUNDLE_PRODUCT_KEY
 AND ATTRIBUTED_PCT  <> 100.00000000   /*OA-Q3FY15*/
  )
 UNION
 /* ATTRIBUTED SOLs without an OFFSET line */
 SELECT TOP_SKU_SALES_ORDER_LINE_KEY, 'NO_OFFSET_LINE' AS EXCEPTION_TYPE, 3 AS EXCP_PRIORITY, SUM(ATTRIBUTED_PCT) AS SUM_PCT
 FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISO
 WHERE ATTRIBUTED_PRODUCT_KEY <> BUNDLE_PRODUCT_KEY
  AND NOT EXISTS ( SELECT 1  
 FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISO1
 WHERE ATTRIBUTED_PRODUCT_KEY = BUNDLE_PRODUCT_KEY
  AND WISO1.TOP_SKU_SALES_ORDER_LINE_KEY =  WISO.TOP_SKU_SALES_ORDER_LINE_KEY)
 GROUP BY 1
 UNION
 /* CISCO_BOOKED_FLAG IS NULL */
 SELECT TOP_SKU_SALES_ORDER_LINE_KEY, 'CBF_IS_NULL' AS EXCEPTION_TYPE, 4 AS EXCP_PRIORITY,NULL
 FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISO
 WHERE WISO.CISCO_BOOKED_FLAG IS NULL
 GROUP BY 1 
 /*
 UNION
 --OFFSET lines without Attriuted line 
 SELECT TOP_SKU_SALES_ORDER_LINE_KEY, 'NO_ATTRIB_LINE' AS EXCEPTION_TYPE, 4 AS EXCP_PRIORITY, SUM(ATTRIBUTED_PCT) AS SUM_PCT
 FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISO
 WHERE (ATTRIBUTED_PRODUCT_KEY = BUNDLE_PRODUCT_KEY
 AND TOP_SKU_SALES_ORDER_LINE_KEY = SALES_ORDER_LINE_KEY)    --Added the filter condition for CISCO ONE req.-- OA-Q3FY15
 AND NOT EXISTS ( SELECT 1  
 FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISO1
 WHERE (ATTRIBUTED_PRODUCT_KEY <> BUNDLE_PRODUCT_KEY
 AND WISO1.TOP_SKU_SALES_ORDER_LINE_KEY =  WISO.TOP_SKU_SALES_ORDER_LINE_KEY)
 GROUP BY 1 
 */ 
 )A
 QUALIFY ROW_NUMBER() OVER(PARTITION BY TOP_SKU_SALES_ORDER_LINE_KEY ORDER BY EXCP_PRIORITY )=1
 )INVALID_SOL
 SET VALID_FLG = 'N'
 ,EXCEPTION_TYPE = INVALID_SOL.EXCEPTION_TYPE
 WHERE WISO.TOP_SKU_SALES_ORDER_LINE_KEY = INVALID_SOL.TOP_SKU_SALES_ORDER_LINE_KEY
 ;


Source3 Name : SQ_W_SOL_OFFER_ATTRIBUTION_UOBO


Pre SQL : 
DELETE FROM $$WORKDB.W_SOL_OFFER_ATTRIBUTION_UOBO ALL;


SQL Query : 
SELECT 
  OP.SK_OFFER_ATTRIBUTION_ID_INT, 
  OP.SS_CD,
  OP.SALES_ORDER_LINE_KEY, 
  OP.ATTRIBUTED_PRODUCT_KEY, 
  OP.SVC_CONTRACT_LINE_START_DT, 
  OP.SVC_CONTRACT_LINE_END_DT, 
  OP.ATTRIBUTION_PCT,
  OP.CISCO_BOOKED_ATTRIBUTION_FLG, 
  OP.UNIT_SELLING_PRC_TRX_AMT, 
  OP.BOOKINGS_PCT,
  OP.PRODUCT_ATTRIBUTED_QTY,
  OP.START_TV_DTM, 
  OP.END_TV_DTM, 
  OP.ACTION_CODE, 
  OP.DML_TYPE,
  OP.EXCEPTION_REASON_CD,
  OP.EXCEPTION_STATUS_CD,
  OP.ATTRIBUTION_TOP_SKU_FLG,
  OP.UNIT_LIST_PRICE_USD_AMT,
  OP.TOP_SKU_SALES_ORDER_LINE_KEY,
  OP.ATTRIBUTION_CD,
  OP.EXCEPTION_DETAIL_DESCR
  FROM
  (
  SELECT 
  TVOUTPUT.SK_OFFER_ATTRIBUTION_ID_INT, 
  TVOUTPUT.SS_CD,
  TVOUTPUT.SALES_ORDER_LINE_KEY, 
  TVOUTPUT.ATTRIBUTED_PRODUCT_KEY, 
  TVOUTPUT.SVC_CONTRACT_LINE_START_DT, 
  TVOUTPUT.SVC_CONTRACT_LINE_END_DT, 
  TVOUTPUT.ATTRIBUTION_PCT, 
  TVOUTPUT.CISCO_BOOKED_ATTRIBUTION_FLG, 
  TVOUTPUT.UNIT_SELLING_PRC_TRX_AMT, 
  TVOUTPUT.BOOKINGS_PCT, 
  TVOUTPUT.PRODUCT_ATTRIBUTED_QTY, 
  TVOUTPUT.START_TV_DTM, 
  COALESCE (MAX (CAST(TVOUTPUT.START_TV_DTM AS TIMESTAMP(0)) - INTERVAL '1' SECOND) OVER (PARTITION BY TVOUTPUT.SK_OFFER_ATTRIBUTION_ID_INT, TVOUTPUT.SS_CD ORDER BY TVOUTPUT.START_TV_DTM ASC ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING), TIMESTAMP '3500-01-01 00:00:00') AS END_TV_DTM, 
  TVOUTPUT.ACTION_CODE, 
  ROW_NUMBER () OVER (PARTITION BY TVOUTPUT.SK_OFFER_ATTRIBUTION_ID_INT, TVOUTPUT.SS_CD ORDER BY TVOUTPUT.START_TV_DTM ASC) AS RANK_INDEX, 
  (CASE WHEN RANK_INDEX = 1 AND NSOAT.SK_OFFER_ATTRIBUTION_ID_INT IS NOT NULL AND NSOAT.SS_CD IS NOT NULL THEN 'U' ELSE 'I' END) AS DML_TYPE ,
  /*Added this as part of OA-Q2FY15 */
  TVOUTPUT.EXCEPTION_REASON_CD,
  TVOUTPUT.EXCEPTION_STATUS_CD,
  TVOUTPUT.ATTRIBUTION_TOP_SKU_FLG,
  TVOUTPUT.UNIT_LIST_PRICE_USD_AMT,
  TVOUTPUT.TOP_SKU_SALES_ORDER_LINE_KEY,
  TVOUTPUT.ATTRIBUTION_CD,
  TVOUTPUT.EXCEPTION_DETAIL_DESCR
  FROM 
  ( 
  SELECT 
  TVINPUT.SK_OFFER_ATTRIBUTION_ID_INT, 
  TVINPUT.SS_CD,
  TVINPUT.SALES_ORDER_LINE_KEY, 
  TVINPUT.ATTRIBUTED_PRODUCT_KEY, 
  TVINPUT.SVC_CONTRACT_LINE_START_DT, 
  TVINPUT.SVC_CONTRACT_LINE_END_DT, 
  TVINPUT.ATTRIBUTION_PCT, 
  TVINPUT.CISCO_BOOKED_ATTRIBUTION_FLG, 
  TVINPUT.UNIT_SELLING_PRC_TRX_AMT, 
  TVINPUT.BOOKINGS_PCT, 
  TVINPUT.PRODUCT_ATTRIBUTED_QTY, 
  TVINPUT.START_TV_DTM, 
  TVINPUT.ACTION_CODE, 
  ROW_NUMBER () OVER (PARTITION BY TVINPUT.SK_OFFER_ATTRIBUTION_ID_INT, TVINPUT.SS_CD, 
  TVINPUT.SALES_ORDER_LINE_KEY, 
  TVINPUT.ATTRIBUTED_PRODUCT_KEY, 
  TVINPUT.ATTRIBUTION_PCT,
  TVINPUT.CISCO_BOOKED_ATTRIBUTION_FLG, 
  TVINPUT.UNIT_SELLING_PRC_TRX_AMT,
  TVINPUT.BOOKINGS_PCT, 
  TVINPUT.PRODUCT_ATTRIBUTED_QTY ORDER BY SOURCE_COMMIT_TIME DESC) AS ROW_NUM ,
  TVINPUT.EXCEPTION_REASON_CD,
  TVINPUT.EXCEPTION_STATUS_CD,
  TVINPUT.ATTRIBUTION_TOP_SKU_FLG,
  TVINPUT.UNIT_LIST_PRICE_USD_AMT,
  TVINPUT.TOP_SKU_SALES_ORDER_LINE_KEY,
  TVINPUT.ATTRIBUTION_CD,
  TVINPUT.EXCEPTION_DETAIL_DESCR
  FROM 
  ( 
  SELECT WISOA.OA_ATTRIB_ID AS SK_OFFER_ATTRIBUTION_ID_INT, 
  WISOA.SS_CD AS SS_CD,
  WISOA.SALES_ORDER_LINE_KEY AS SALES_ORDER_LINE_KEY, 
  WISOA.ATTRIBUTED_PRODUCT_KEY AS ATTRIBUTED_PRODUCT_KEY, 
  NSOL.RU_SERVICE_CONTRACT_START_DTM AS SVC_CONTRACT_LINE_START_DT, 
  NSOL.RU_SERVICE_CONTRACT_END_DTM AS SVC_CONTRACT_LINE_END_DT, 
  COALESCE(WISOA.ATTRIBUTED_PCT, -999.00) AS ATTRIBUTION_PCT, 
  COALESCE(WISOA.CISCO_BOOKED_FLAG,'=') AS CISCO_BOOKED_ATTRIBUTION_FLG, 
  COALESCE(WISOA.ATTRIBUTED_UNIT_NET_PRICE,0.0000000) AS UNIT_SELLING_PRC_TRX_AMT, 
  COALESCE(WISOA.BOOKINGS_PCT, 100) AS BOOKINGS_PCT, 
  COALESCE(WISOA.QUANTITY,0) AS PRODUCT_ATTRIBUTED_QTY, 
  WISOA.SOURCE_COMMIT_TIME AS START_TV_DTM, 
  'I' AS ACTION_CODE,
  WISOA.SOURCE_COMMIT_TIME,
  /*Added this as part of OA-Q2FY15 */
  COALESCE(WISOA.EXCEPTION_CODE,'UNKNOWN') AS EXCEPTION_REASON_CD,
  CASE WHEN WISOA.EXCEPTION_CODE IS NULL THEN CAST('SUCCESS' AS VARCHAR(20)) ELSE CAST('FAILURE' AS VARCHAR(20)) END AS EXCEPTION_STATUS_CD,
  COALESCE(WISOA.ATTRIBUTION_FLAG,'N') AS ATTRIBUTION_TOP_SKU_FLG,
  COALESCE(WISOA.ATTRIBUTED_UNIT_LIST_PRICE,0.0000000) AS UNIT_LIST_PRICE_USD_AMT,
  /* CASE WHEN WISOA.SS_CD='QTC' THEN -9999 WHEN WISOA.SS_CD='BV' THEN -8888 END AS TOP_SKU_SALES_ORDER_LINE_KEY  */
  WISOA.TOP_SKU_SALES_ORDER_LINE_KEY AS TOP_SKU_SALES_ORDER_LINE_KEY, /* OA- Q3FY15*/
  WISOA.ATTRIBUTION_CD AS ATTRIBUTION_CD, /*OA - Q3FY15 */
  COALESCE(WISOA.EXCEPTION_DETAIL,'UNKNOWN') AS  EXCEPTION_DETAIL_DESCR /* OA-Q1FY16*/
  FROM 
  $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISOA
  LEFT JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL 
  ON WISOA.TOP_SKU_SALES_ORDER_LINE_KEY=NSOL.SALES_ORDER_LINE_KEY 
  WHERE DV_DATA_SRC_CD = 'SRC'
  AND VALID_FLG = 'Y'
  
  UNION ALL 
  SELECT NSOA.SK_OFFER_ATTRIBUTION_ID_INT, 
  NSOA.SS_CD,
  NSOA.SALES_ORDER_LINE_KEY , 
  NSOA.ATTRIBUTED_PRODUCT_KEY, 
  NSOA.SVC_CONTRACT_LINE_START_DT, 
  NSOA.SVC_CONTRACT_LINE_END_DT, 
  NSOA.ATTRIBUTION_PCT, 
  NSOA.CISCO_BOOKED_ATTRIBUTION_FLG, 
  NSOA.UNIT_SELLING_PRC_TRX_AMT, 
  NSOA.BOOKINGS_PCT, 
  NSOA.PRODUCT_ATTRIBUTED_QTY, 
  NSOA.START_TV_DTM, 
  'X' AS ACTION_CODE,
  NSOA.EDW_CREATE_DTM AS SOURCE_COMMIT_TIME,
     /*Added this as part of OA-Q2FY15 */
  NSOA.EXCEPTION_REASON_CD,
  NSOA.EXCEPTION_STATUS_CD,
  NSOA.ATTRIBUTION_TOP_SKU_FLG,
  NSOA.UNIT_LIST_PRICE_USD_AMT,
  NSOA.TOP_SKU_SALES_ORDER_LINE_KEY,
  NSOA.ATTRIBUTION_CD,
  NSOA.EXCEPTION_DETAIL_DESCR
  FROM $$NRTNCRVWDB.N_SOL_OFFER_ATTRIBUTION_TV NSOA 
  WHERE CAST(NSOA.END_TV_DTM AS DATE)='3500-01-01' 
  AND EXISTS ( SELECT 1 FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISOA 
   WHERE 1=1
   AND DV_DATA_SRC_CD = 'SRC'
   AND VALID_FLG = 'Y'
   AND WISOA.OA_ATTRIB_ID=NSOA.SK_OFFER_ATTRIBUTION_ID_INT 
   AND WISOA.SS_CD = NSOA.SS_CD
  )
      
  ) TVINPUT 
  QUALIFY ROW_NUMBER () OVER (PARTITION BY TVINPUT.SK_OFFER_ATTRIBUTION_ID_INT, TVINPUT.SS_CD, TVINPUT.START_TV_DTM ORDER BY SOURCE_COMMIT_TIME DESC) =1 
  ) TVOUTPUT 
  LEFT JOIN $$NRTNCRVWDB.N_SOL_OFFER_ATTRIBUTION_TV NSOAT 
  ON TVOUTPUT.SK_OFFER_ATTRIBUTION_ID_INT=NSOAT.SK_OFFER_ATTRIBUTION_ID_INT 
  AND TVOUTPUT.SS_CD=NSOAT.SS_CD 
  AND NSOAT.END_TV_DTM='3500-01-01 00:00:00' 
  WHERE TVOUTPUT.ROW_NUM=1) OP


Post SQL : 



Target3 Name : W_SOL_OFFER_ATTRIBUTION_UOBO


Pre SQL : 



Post SQL : 
COLLECT STATS ON $$WORKDB.W_SOL_OFFER_ATTRIBUTION_UOBO;


Source4 Name : SQ_EX_XXOA_ORDER_ATTRIB_UO


Pre SQL : 
DELETE FROM $$EXCEPDB.EX_XXOA_ORDER_ATTRIB EXOA 
 WHERE EXISTS 
 (SELECT 1 FROM $$WORKDB.W_SOL_OFFER_ATTRIBUTION_UOBO WSOA
 INNER JOIN $$COMREFVWDB.N_SOURCE_SYSTEM_CODES NSSC 
 ON(NSSC.SOURCE_SYSTEM_CODE=WSOA.SS_CD)
 WHERE EXOA.OA_ATTRIB_ID=WSOA.SK_OFFER_ATTRIBUTION_ID_INT 
	AND EXOA.GLOBAL_NAME = NSSC.GLOBAL_NAME 
 )
;


SQL Query : 
SELECT WUOBO.BATCH_ID,
 WUOBO.OA_ATTRIB_ID,
 WUOBO.ORDER_NUMBER,
 WUOBO.HEADER_ID,
 WUOBO.DATA_SOURCE,
 WUOBO.LINE_ID,
 WUOBO.PARENT_LINE_ID,
 WUOBO.ORDERED_ITEM,
 WUOBO.INVENTORY_ITEM_ID,
 WUOBO.ATTRIBUTION_FLAG,
 WUOBO.CISCO_BOOKED_FLAG,
 WUOBO.BUNDLE_TYPE,
 WUOBO.QUANTITY,
 WUOBO.ATTRIBUTED_UNIT_LIST_PRICE,
 WUOBO.ATTRIBUTED_UNIT_NET_PRICE,
 WUOBO.BOOKINGS_PCT,
 WUOBO.ATTRIBUTED_PCT,
 WUOBO.PUBLISH_FLAG,
 WUOBO.TRX_TYPE,
 WUOBO.CREATED_BY,
 WUOBO.CREATION_DATE,
 WUOBO.LAST_UPDATED_BY,
 WUOBO.LAST_UPDATE_DATE,
 WUOBO.ORIG_OA_ATTRIB_ID,
 WUOBO.ACTION_CODE,
 WUOBO.CREATE_DATETIME,
 WUOBO.GLOBAL_NAME,
 WUOBO.SOURCE_DML_TYPE,
 WUOBO.SOURCE_COMMIT_TIME,
 WUOBO.EXCEPTION_TYPE,
 WUOBO.EXCEPTION_CODE, /*Added this as part of OA-Q2FY15 */
 WUOBO.ATTRIBUTION_CODE, /* Added as part of OA-Q1FY16*/
 WUOBO.EXCEPTION_DETAIL /* Added as part of OA-Q1FY16*/
  FROM  $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WUOBO
 WHERE 1=1
 AND WUOBO.DV_DATA_SRC_CD = 'SRC'
 AND (
  WUOBO.VALID_FLG = 'N'
 )
 AND NOT EXISTS
 (
  SELECT 1
  FROM $$EXCEPDB.EX_XXOA_ORDER_ATTRIB EXOA
  WHERE EXOA.OA_ATTRIB_ID = WUOBO.OA_ATTRIB_ID  
  AND EXOA.GLOBAL_NAME = WUOBO.GLOBAL_NAME
 )
  /*Q1FY15 - CR -Donot consider records that also have DELETES */
  AND NOT EXISTS (
 SELECT 1 FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_DELS WI_DELS
 WHERE WI_DELS.OA_ATTRIB_ID = WUOBO.OA_ATTRIB_ID
 AND WI_DELS.GLOBAL_NAME = WUOBO.GLOBAL_NAME
 )
 
 UNION
 
 SELECT STOA.BATCH_ID,
 STOA.OA_ATTRIB_ID,
 STOA.ORDER_NUMBER,
 STOA.HEADER_ID,
 STOA.DATA_SOURCE,
 STOA.LINE_ID,
 STOA.PARENT_LINE_ID,
 STOA.ORDERED_ITEM,
 STOA.INVENTORY_ITEM_ID,
 STOA.ATTRIBUTION_FLAG,
 STOA.CISCO_BOOKED_FLAG,
 STOA.BUNDLE_TYPE,
 STOA.QUANTITY,
 STOA.ATTRIBUTED_UNIT_LIST_PRICE,
 STOA.ATTRIBUTED_UNIT_NET_PRICE,
 STOA.BOOKINGS_PCT,
 STOA.ATTRIBUTED_PCT,
 STOA.PUBLISH_FLAG,
 STOA.TRX_TYPE,
 STOA.CREATED_BY,
 STOA.CREATION_DATE,
 STOA.LAST_UPDATED_BY,
 STOA.LAST_UPDATE_DATE,
 STOA.ORIG_OA_ATTRIB_ID,
 STOA.ACTION_CODE,
 STOA.CREATE_DATETIME,
 STOA.GLOBAL_NAME,
 STOA.SOURCE_DML_TYPE,
 STOA.SOURCE_COMMIT_TIME,
 STOA.EXCEPTION_TYPE,
 STOA.EXCEPTION_CODE,
 STOA.ATTRIBUTION_CODE, /*OA-Q1FY16*/
 STOA.EXCEPTION_DETAIL /*OA-Q1FY16*/
  FROM
 
 (
 SELECT BATCH_ID,
 OA_ATTRIB_ID,
 ORDER_NUMBER,
 HEADER_ID,
 DATA_SOURCE,
 LINE_ID,
 PARENT_LINE_ID,
 ORDERED_ITEM,
 INVENTORY_ITEM_ID,
 ATTRIBUTION_FLAG,
 CISCO_BOOKED_FLAG,
 BUNDLE_TYPE,
 QUANTITY,
 ATTRIBUTED_UNIT_LIST_PRICE,
 ATTRIBUTED_UNIT_NET_PRICE,
 BOOKINGS_PCT,
 ATTRIBUTED_PCT,
 PUBLISH_FLAG,
 TRX_TYPE,
 CREATED_BY,
 CREATION_DATE,
 LAST_UPDATED_BY,
 LAST_UPDATE_DATE,
 ORIG_OA_ATTRIB_ID,
 ACTION_CODE,
 CREATE_DATETIME,
 GLOBAL_NAME,
 SOURCE_DML_TYPE,
 SOURCE_COMMIT_TIME,
 'RI' AS EXCEPTION_TYPE,
 EXCEPTION_CODE, /*Added this as part of OA-Q2FY15 */
 ATTRIBUTION_CODE, /*OA-Q1FY16*/
 EXCEPTION_DETAIL /* Added as part of OA-Q1FY16*/
  FROM $$NRTSTGDB.ST_UO_XXOA_ORDER_ATTRIB
  WHERE SOURCE_DML_TYPE <>'DELETE'  /* Q1FY15 CR - OA Handle DELETES*/
 QUALIFY ROW_NUMBER () OVER (PARTITION BY OA_ATTRIB_ID ORDER BY SOURCE_COMMIT_TIME DESC, REFRESH_DATETIME DESC)=1   /* Q1FY15 CR - OA Handle DELETES-- Added REFRESH_DATETIME column as part of Q3FY15*/
 
 UNION ALL 
 
 SELECT BATCH_ID,
 OA_ATTRIB_ID,
 ORDER_NUMBER,
 HEADER_ID,
 DATA_SOURCE,
 LINE_ID,
 PARENT_LINE_ID,
 ORDERED_ITEM,
 INVENTORY_ITEM_ID,
 ATTRIBUTION_FLAG,
 CISCO_BOOKED_FLAG,
 BUNDLE_TYPE,
 QUANTITY,
 ATTRIBUTED_UNIT_LIST_PRICE,
 ATTRIBUTED_UNIT_NET_PRICE,
 BOOKINGS_PCT,
 ATTRIBUTED_PCT,
 PUBLISH_FLAG,
 TRX_TYPE,
 CREATED_BY,
 CREATION_DATE,
 LAST_UPDATED_BY,
 LAST_UPDATE_DATE,
 ORIG_OA_ATTRIB_ID,
 ACTION_CODE,
 CREATE_DATETIME,
 GLOBAL_NAME,
 SOURCE_DML_TYPE,
 SOURCE_COMMIT_TIME,
 'RI' AS EXCEPTION_TYPE,
 EXCEPTION_CODE ,/*Added this as part of OA-Q2FY15 */
 ATTRIBUTION_CODE, /* OA -Q1FY16*/
 EXCEPTION_DETAIL /* Added as part of OA-Q1FY16*/
  FROM $$NRTSTGDB.ST_BO_XXOA_ORDER_ATTRIB 
  WHERE SOURCE_DML_TYPE <>'DELETE'  /* Q1FY15 CR - OA Handle DELETES*/
QUALIFY ROW_NUMBER () OVER (PARTITION BY OA_ATTRIB_ID ORDER BY SOURCE_COMMIT_TIME DESC, REFRESH_DATETIME DESC)=1   /* Q1FY15 CR - OA Handle DELETES  --  Added REFRESH_DATETIME column as part of Q3FY15*/

 )STOA
 
WHERE   NOT EXISTS (
 /* Get records that are not processed to WI eg: RI check on ITEM_KEY, SALES_ORDER_LINE_KEY, PRODUCT_KEY of Bundle Line = -999 */
 SELECT 1
 FROM  $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_UOBO WISOA
 WHERE STOA.OA_ATTRIB_ID=WISOA.OA_ATTRIB_ID 
  AND STOA.GLOBAL_NAME = WISOA.GLOBAL_NAME 
  AND WISOA.DV_DATA_SRC_CD = 'SRC'
 )
 AND NOT EXISTS
 (
  SELECT 1
  FROM $$EXCEPDB.EX_XXOA_ORDER_ATTRIB EXOA
  WHERE EXOA.OA_ATTRIB_ID = STOA.OA_ATTRIB_ID  
  AND EXOA.GLOBAL_NAME = STOA.GLOBAL_NAME 
 )
   /*Q1FY15 - CR -Donot consider records that also have DELETES */
  AND NOT EXISTS (
 SELECT 1 FROM $$NRTSTGDB.WI_SOL_OFFER_ATTRIB_DELS WI_DELS
 WHERE WI_DELS.OA_ATTRIB_ID = STOA.OA_ATTRIB_ID
 AND WI_DELS.GLOBAL_NAME = STOA.GLOBAL_NAME
 )


Post SQL : 



Target4 Name : EX_XXOA_ORDER_ATTRIB


Pre SQL : 



Post SQL : 
COLLECT STATS ON $$EXCEPDB.EX_XXOA_ORDER_ATTRIB;