


Source1 Name : SQ_N_DAY1


Pre SQL : 



SQL Query : 
SELECT BK_CALENDAR_DATE 
FROM 	$$COMREFVWDB.N_DAY CAL,
	(SELECT FMONTH.FISCAL_MONTH_START_DATE,FMONTH.FISCAL_MONTH_END_DATE
 		FROM $$COMREFVWDB.N_FISCAL_MONTH FMONTH,  $$ETLVWDB.BKG_PROCESS_DT_CNTRL BKG_PRCDT
		WHERE 
			BKG_PRCDT.PROCESS_DATE BETWEEN  FMONTH.FISCAL_MONTH_START_DATE AND FMONTH.FISCAL_MONTH_END_DATE) NMONTH
WHERE CAL.BK_CALENDAR_DATE between NMONTH.FISCAL_MONTH_START_DATE and NMONTH.FISCAL_MONTH_END_DATE
UNION ALL
SELECT BK_CALENDAR_DATE 
FROM 	$$COMREFVWDB.N_DAY CAL,
	(SEL * FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR  
		WHERE FISCAL_YEAR_MONTH_INT > (SEL FISCAL_YEAR_MTH_NUMBER_INT FROM $$ETLVWDB.BKG_PROCESS_DT_CNTRL)
		QUALIFY  ROW_NUMBER() OVER ( ORDER BY FISCAL_YEAR_MONTH_INT ASC)  =1
	) NEXT_FIS_MNTH
	WHERE CAL.BK_CALENDAR_DATE between NEXT_FIS_MNTH.FISCAL_MONTH_START_DATE and NEXT_FIS_MNTH.FISCAL_MONTH_END_DATE


Post SQL : 



Target1 Name : WI_N_PROCESS_DATES_NBKG_MSR1


Pre SQL : 
DELETE FROM $$STGDB.WI_N_PROCESS_DATES_NBKG_MSR ALL;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_N_PROCESS_DATES_NBKG_MSR','D');


Source2 Name : SQ_MT_DRVD_NRT_BKG_TRX


Pre SQL : 



SQL Query : 
SELECT 
  BOOKINGS_MEASURE_KEY   ,        
  FORWARD_REVERSE_CODE        ,  
  TRANSACTION_DATETIME          ,
  TRANSACTION_SEQUENCE_ID_INT   ,
  SOURCE_SYSTEM_CODE           , 
  PROCESS_DATE                  ,
  BOOKINGS_PERCENTAGE   ,        
  NET_PRICE_AMOUNT           ,   
  SALES_CHANNEL_CODE       ,     
  SPLIT_PERCENTAGE,  /**R9**/
  0.00 TRADE_IN_AMOUNT               ,
  '='TRANSACTION_GROUPING_TYPE_CODE,
  TRANSACTION_QUANTITY          ,
  CDB_DATA_SOURCE_CODE         , 
  SALES_REP_NUMBER              ,
  SALES_CREDIT_TYPE_CODE   ,     
  DD_ITEM_TYPE_CODE_FLAG    ,    
  DD_RMA_FLAG                   ,
  DD_INTERNATIONAL_DEMO_FLAG    ,
  DD_REPLACEMENT_DEMO_FLAG      ,
  DD_REVENUE_FLAG               ,
  DD_OVERLAY_FLAG               ,
  DD_SALESREP_FLAG              ,
  DD_IC_REVENUE_FLAG           , 
  DD_CHARGES_FLAG               ,
  DD_MISC_FLAG                  ,
  DD_ACQUISITION_FLAG     ,      
  DD_SERVICE_FLAG              , 
  DD_CORP_BKG_FLAG           ,   
  DD_COMP_US_NET_PRICE_AMOUNT   ,
  DD_COMP_US_LIST_PRICE_AMOUNT  ,
  DD_COMP_US_COST_AMOUNT        ,
  DD_EXTENDED_QUANTITY          ,
  DD_COMP_US_HOLD_NET_PRICE_AMT ,
  DD_COMP_US_HOLD_LIST_PRICE_AMT,
  DD_COMP_US_HOLD_COST_AMOUNT   ,
  DD_EXTENDED_HOLD_QUANTITY     ,
  SALES_TERRITORY_KEY           ,
  CORP_BKG_RECOMPUTE_FLAG  ,     
  DD_COMP_US_STANDARD_PRICE_AMT ,
  'Fiscal Year' BK_FISCAL_CALENDAR_CODE       ,
  BK_FISCAL_YEAR_NUMBER_INT    , 
  BK_FISCAL_MONTH_NUMBER_INT ,   
  DV_FISCAL_YEAR_MTH_NUMBER_INT ,
  SALES_ORDER_KEY               ,
  SHIP_TO_CUSTOMER_KEY     ,     
  BILL_TO_CUSTOMER_KEY       ,   
  SOLD_TO_CUSTOMER_KEY      ,    
  PRODUCT_KEY                   ,
  SALES_ORDER_LINE_KEY ,         
  CANCEL_CODE ,
  EDW_CREATE_USER          ,     
  EDW_UPDATE_USER           ,    
  EDW_CREATE_DTM    ,       
  EDW_UPDATE_DTM  ,
  CONVERSION_RT, 
  BK_ISO_CURRENCY_CODE,
  ORDER_DTM,
  CANCELLED_FLG, /* R10 Cancel Flag */
  DV_REVENUE_RECOGNITION_FLG,   /* Added as part of true demand bkgs definition*/    
  DV_NET_SPREAD_FLG,         /* Added as part of true demand bkgs definition*/  
 RU_CISCO_BOOKED_DATETIME,
 BK_SO_NUMBER_INT,
 SALES_ORDER_OPERATING_UNIT,
 SALES_ORDER_CATEGORY_TYPE,
 DV_ATTRIBUTION_CD,
 DV_PRODUCT_KEY, 
 DV_SALES_ORDER_LINE_KEY,
 SK_OFFER_ATTRIBUTION_ID_INT,
 DV_LOCAL_EXTND_LIST_PRICE_AMT,
 LOCAL_UNIT_LIST_PRICE_AMT,
 DV_UNIT_LIST_PRICE_USD_AMT
 ,DV_PURCHASE_ADJ_DSCNT_USD_AMT /* Added as part of XaaS PA goponnus */
,POB_TYPE_CD /* Added as part of NRS MPOB Changes */
 ,NRS_TRANSITION_FLG/* Added as part of NRS PI3 Changes */
 ,SALES_MOTION_CD /* Added as part of Oct - 2017 rel */
,SUMMARY_QUOTE_FLG  /* Added as part of Oct - 2017 rel */
,DD_COMP_US_ORIG_LIST_PRICE
,DD_COMP_US_ORIG_EXT_LIST_PRICE
,RU_SERVICE_CONTRACT_START_DTM
,RU_SERVICE_CONTRACT_END_DTM
,DV_CONTRACT_DURATION
,DV_ANNUALIZED_FLG
,DV_ANNUALIZED_US_NET_AMT
,DV_MULTIYEAR_US_NET_AMT
,BOOKINGS_POLICY_CD
,SOURCE_REP_ANNUAL_USD_AMT
  FROM 
  (SEL BOOKINGS_MEASURE_KEY          
 ,BK_FISCAL_MONTH_NUMBER_INT    
 ,DD_EXTENDED_HOLD_QUANTITY     
 ,CONVERSION_DT                 
 ,SALES_REP_NUMBER              
 ,TRANSACTION_DATETIME          
 ,TRANSACTION_SEQUENCE_ID_INT   
 ,SALES_CHANNEL_CODE            
 ,CDB_DATA_SOURCE_CODE          
 ,SPLIT_PERCENTAGE              
 ,BK_FISCAL_YEAR_NUMBER_INT     
 ,DD_SERVICE_FLAG               
 ,DD_CORP_BKG_FLAG              
 ,DD_COMP_US_NET_PRICE_AMOUNT   
 ,DD_COMP_US_HOLD_NET_PRICE_AMT 
 ,SOLD_TO_CUSTOMER_KEY          
 ,BILL_TO_CUSTOMER_KEY          
 ,SHIP_TO_CUSTOMER_KEY          
 ,CONVERSION_RT                 
 ,SALES_ORDER_LINE_KEY          
 ,BK_SO_NUMBER_INT              
 ,PURCHASE_ORDER_NUMBER         
 ,BK_SO_SRC_CRT_DATETIME        
 ,FORWARD_REVERSE_CODE          
 ,BOOKINGS_PERCENTAGE           
 ,NET_PRICE_AMOUNT              
 ,TRANSACTION_QUANTITY          
 ,PROCESS_DATE                  
 ,BK_ISO_CURRENCY_CODE          
 ,SALES_ORDER_KEY               
 ,DD_ITEM_TYPE_CODE_FLAG        
 ,DD_RMA_FLAG                   
 ,DD_INTERNATIONAL_DEMO_FLAG    
 ,DD_REPLACEMENT_DEMO_FLAG      
 ,DD_REVENUE_FLAG               
 ,DD_OVERLAY_FLAG               
 ,DD_SALESREP_FLAG              
 ,DD_IC_REVENUE_FLAG            
 ,DD_CHARGES_FLAG               
 ,DD_MISC_FLAG                  
 ,DD_ACQUISITION_FLAG           
 ,CORP_BKG_RECOMPUTE_FLAG       
 ,DD_COMP_US_LIST_PRICE_AMOUNT  
 ,DD_COMP_US_COST_AMOUNT        
 ,DD_EXTENDED_QUANTITY          
 ,DD_COMP_US_HOLD_LIST_PRICE_AMT
 ,DD_COMP_US_HOLD_COST_AMOUNT   
 ,ES_LINE_SEQ_ID_INT            
 ,ORDER_DTM                     
 ,CANCELLED_FLG                 
 ,RU_CISCO_BOOKED_DATETIME      
 ,SALES_ORDER_CATEGORY_TYPE     
 ,SOURCE_SYSTEM_CODE            
 ,DD_COMP_US_STANDARD_PRICE_AMT 
 ,DV_FISCAL_YEAR_MTH_NUMBER_INT 
 ,SALES_ORDER_OPERATING_UNIT    
 ,PRODUCT_KEY                   
 ,SALES_TERRITORY_KEY           
 ,SALES_CREDIT_TYPE_CODE    
 ,CAST('=' AS CHAR(10)) AS CANCEL_CODE
 ,EDW_CREATE_USER          
 ,EDW_UPDATE_USER  
 ,EDW_CREATE_DTM
 ,EDW_UPDATE_DTM
 ,DV_REVENUE_RECOGNITION_FLG    
 ,DV_NET_SPREAD_FLG
 /* Added as part of OFFER ATTRIBUTION*/
 ,DV_ATTRIBUTION_CD
 ,DV_PRODUCT_KEY
 ,DV_SALES_ORDER_LINE_KEY
 ,SK_OFFER_ATTRIBUTION_ID_INT
,DV_LOCAL_EXTND_LIST_PRICE_AMT
 ,LOCAL_UNIT_LIST_PRICE_AMT
 ,DV_UNIT_LIST_PRICE_USD_AMT 
 ,PURCHASE_ADJ_DISCOUNT_USD_AMT  AS DV_PURCHASE_ADJ_DSCNT_USD_AMT/* Added as part of XaaS PA goponnus */
,NDNBT.POB_TYPE_CD /* Added as part of NRS MPOB Changes */
 ,NDNBT.NRS_TRANSITION_FLG/* Added as part of NRS PI3 Changes */
  ,NDNBT.SALES_MOTION_CD /* Added as part of Oct - 2017 rel */
   ,'N' AS SUMMARY_QUOTE_FLG  /* Added as part of Oct - 2017 rel */
    ,DD_COMP_US_ORIG_LIST_PRICE
   ,DD_COMP_US_ORIG_EXT_LIST_PRICE
,RU_SERVICE_CONTRACT_START_DTM
,RU_SERVICE_CONTRACT_END_DTM
,DV_CONTRACT_DURATION
,DV_ANNUALIZED_FLG
,DV_ANNUALIZED_US_NET_AMT
,DV_MULTIYEAR_US_NET_AMT
,BOOKINGS_POLICY_CD
,SOURCE_REP_ANNUAL_USD_AMT
 FROM 
 $$NRTNCRVWDB.MT_DRVD_NRT_BKG_TRX NDNBT
 INNER JOIN $$STGDB.WI_N_PROCESS_DATES_NBKG_MSR
  ON NDNBT.PROCESS_DATE = BK_CALENDAR_DATE 
 WHERE 
  NDNBT.EDW_UPDATE_DTM > '$$LastExtractDate'
  UNION ALL
  SEL BOOKINGS_MEASURE_KEY          
 ,BK_FISCAL_MONTH_NUMBER_INT    
 ,DD_EXTENDED_HOLD_QUANTITY     
 ,CONVERSION_DT                 
 ,SALES_REP_NUMBER              
 ,TRANSACTION_DATETIME          
 ,TRANSACTION_SEQUENCE_ID_INT   
 ,SALES_CHANNEL_CODE            
 ,CDB_DATA_SOURCE_CODE          
 ,SPLIT_PERCENTAGE              
 ,BK_FISCAL_YEAR_NUMBER_INT     
 ,DD_SERVICE_FLAG               
 ,DD_CORP_BKG_FLAG              
 ,DD_COMP_US_NET_PRICE_AMOUNT   
 ,DD_COMP_US_HOLD_NET_PRICE_AMT 
 ,SOLD_TO_CUSTOMER_KEY          
 ,BILL_TO_CUSTOMER_KEY          
 ,SHIP_TO_CUSTOMER_KEY          
 ,CONVERSION_RT                 
 ,SALES_ORDER_LINE_KEY          
 ,BK_SO_NUMBER_INT              
 ,PURCHASE_ORDER_NUMBER         
 ,BK_SO_SRC_CRT_DATETIME        
 ,FORWARD_REVERSE_CODE          
 ,BOOKINGS_PERCENTAGE           
 ,NET_PRICE_AMOUNT              
 ,TRANSACTION_QUANTITY          
 ,PROCESS_DATE                  
 ,BK_ISO_CURRENCY_CODE          
 ,SALES_ORDER_KEY               
 ,DD_ITEM_TYPE_CODE_FLAG        
 ,DD_RMA_FLAG                   
 ,DD_INTERNATIONAL_DEMO_FLAG    
 ,DD_REPLACEMENT_DEMO_FLAG      
 ,DD_REVENUE_FLAG               
 ,DD_OVERLAY_FLAG               
 ,DD_SALESREP_FLAG              
 ,DD_IC_REVENUE_FLAG            
 ,DD_CHARGES_FLAG               
 ,DD_MISC_FLAG                  
 ,DD_ACQUISITION_FLAG           
 ,CORP_BKG_RECOMPUTE_FLAG       
 ,DD_COMP_US_LIST_PRICE_AMOUNT  
 ,DD_COMP_US_COST_AMOUNT        
 ,DD_EXTENDED_QUANTITY          
 ,DD_COMP_US_HOLD_LIST_PRICE_AMT
 ,DD_COMP_US_HOLD_COST_AMOUNT   
 ,ES_LINE_SEQ_ID_INT            
 ,ORDER_DTM                     
 ,CANCELLED_FLG                 
 ,RU_CISCO_BOOKED_DATETIME      
 ,SALES_ORDER_CATEGORY_TYPE     
 ,SOURCE_SYSTEM_CODE            
 ,DD_COMP_US_STANDARD_PRICE_AMT 
 ,DV_FISCAL_YEAR_MTH_NUMBER_INT 
 ,SALES_ORDER_OPERATING_UNIT    
 ,PRODUCT_KEY                   
 ,SALES_TERRITORY_KEY           
 ,SALES_CREDIT_TYPE_CODE    
 ,CANCEL_CODE
 ,EDW_CREATE_USER          
 ,EDW_UPDATE_USER  
 ,EDW_CREATE_DTM
 ,EDW_UPDATE_DTM
 ,DV_REVENUE_RECOGNITION_FLG    
 ,DV_NET_SPREAD_FLG
 /* Added as part of OFFER ATTRIBUTION*/
 ,DV_ATTRIBUTION_CD
 ,DV_PRODUCT_KEY
 ,DV_SALES_ORDER_LINE_KEY
 ,SK_OFFER_ATTRIBUTION_ID_INT
 ,DV_LOCAL_EXTND_LIST_PRICE_AMT
 ,LOCAL_UNIT_LIST_PRICE_AMT
 ,DV_UNIT_LIST_PRICE_USD_AMT
 ,DV_PURCHASE_ADJ_DSCNT_USD_AMT /* Added as part of XaaS PA goponnus */
 ,NDNBT.POB_TYPE_CD /* Added as part of NRS MPOB Changes */
 ,NDNBT.NRS_TRANSITION_FLG /* Added as part of NRS PI3 Changes */
 ,NDNBT.SALES_MOTION_CD /* Added as part of Oct - 2017 rel */
 ,'N' AS SUMMARY_QUOTE_FLG  /* Added as part of Oct - 2017 rel */
  ,DD_COMP_US_ORIG_LIST_PRICE
   ,DD_COMP_US_ORIG_EXT_LIST_PRICE
,CAST(NULL AS TIMESTAMP(0))RU_SERVICE_CONTRACT_START_DTM
,CAST(NULL AS TIMESTAMP(0))RU_SERVICE_CONTRACT_END_DTM
,NULL AS DV_CONTRACT_DURATION
,'Y' AS DV_ANNUALIZED_FLG
,DD_COMP_US_NET_PRICE_AMOUNT AS DV_ANNUALIZED_US_NET_AMT
,0.0 AS DV_MULTIYEAR_US_NET_AMT
,'UNK' AS BOOKINGS_POLICY_CD
,0.0 AS SOURCE_REP_ANNUAL_USD_AMT
 FROM 
 $$NRTNCRVWDB.MT_DRVD_NRT_DEBOOKINGS_TRX NDNBT
 INNER JOIN $$STGDB.WI_N_PROCESS_DATES_NBKG_MSR
  ON NDNBT.PROCESS_DATE = BK_CALENDAR_DATE 
 WHERE (NDNBT.CANCEL_CODE='Lost Order' OR NDNBT.BOOKINGS_MEASURE_KEY < 0) AND NDNBT.EDW_UPDATE_DTM  >(SELECT EDW_UPDATE_DTM FROM $$STGDB.WI_DEBKG_MX_EDW_UPDATE_DTM)
  ) BKG


Post SQL : 



Target2 Name : WI_DRVD_ERP_CURR_CC_NBM3


Pre SQL : 
DELETE WI
FROM 	$$STGDB.WI_DRVD_ERP_CURR_CC_NBM WI,
$$NRTNCRVWDB.MT_DRVD_NRT_BKG_TRX NDNBT,
$$STGDB.WI_N_PROCESS_DATES_NBKG_MSR PD
WHERE WI.DRVD_NCR_BKG_TRX_KEY = NDNBT.BOOKINGS_MEASURE_KEY
AND WI.PROCESS_DATE = NDNBT.PROCESS_DATE
AND NDNBT.PROCESS_DATE = PD.BK_CALENDAR_DATE 
AND 	NDNBT.EDW_UPDATE_DTM > '$$LastExtractDate';

DELETE WI
FROM 	$$STGDB.WI_DRVD_ERP_CURR_CC_NBM WI,
$$NRTNCRVWDB.MT_DRVD_NRT_DEBOOKINGS_TRX NDNBT,
$$STGDB.WI_N_PROCESS_DATES_NBKG_MSR PD
WHERE WI.DRVD_NCR_BKG_TRX_KEY = NDNBT.BOOKINGS_MEASURE_KEY
AND WI.PROCESS_DATE = NDNBT.PROCESS_DATE
AND NDNBT.PROCESS_DATE = PD.BK_CALENDAR_DATE 
AND 	NDNBT.EDW_UPDATE_DTM > (SELECT EDW_UPDATE_DTM FROM $$STGDB.WI_DEBKG_MX_EDW_UPDATE_DTM);


Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_BOOKINGS_ERP_CURR_NBM','D');
CALL COLLECT_STATS_WRAP('$$STGDB','WI_DRVD_ERP_CURR_CC_NBM','D');


Source3 Name : SQ_WI_DRVD_ERP_CURR_CC_NBM4


Pre SQL : 



SQL Query : 
SELECT
DRVD_NCR_BKG_TRX_KEY   ,        
FORWARD_REVERSE_CODE        ,  
TRANSACTION_DATETIME          ,
TRANSACTION_SEQUENCE_ID_INT   ,
SOURCE_SYSTEM_CODE           , 
PROCESS_DATE                  ,
BOOKINGS_PERCENTAGE   ,        
NET_PRICE_AMOUNT           ,   
SALES_CHANNEL_CODE       ,     
SPLIT_PERCENTAGE,  /**R9**/
TRADE_IN_AMOUNT               ,
TRANSACTION_GROUPING_TYPE_CODE,
TRANSACTION_QUANTITY          ,
CDB_DATA_SOURCE_CODE         , 
SALES_REP_NUMBER              ,
SALES_CREDIT_TYPE_CODE   ,     
DD_ITEM_TYPE_CODE_FLAG    ,    
DD_RMA_FLAG                   ,
DD_INTERNATIONAL_DEMO_FLAG    ,
DD_REPLACEMENT_DEMO_FLAG      ,
DD_REVENUE_FLAG               ,
DD_OVERLAY_FLAG               ,
DD_SALESREP_FLAG              ,
DD_IC_REVENUE_FLAG           , 
DD_CHARGES_FLAG               ,
DD_MISC_FLAG                  ,
DD_ACQUISITION_FLAG     ,      
DD_SERVICE_FLAG              , 
DD_CORP_BKG_FLAG           ,   
DD_COMP_US_NET_PRICE_AMOUNT   ,
DD_COMP_US_LIST_PRICE_AMOUNT  ,
DD_COMP_US_COST_AMOUNT        ,
DD_EXTENDED_QUANTITY          ,
DD_COMP_US_HOLD_NET_PRICE_AMT ,
DD_COMP_US_HOLD_LIST_PRICE_AMT,
DD_COMP_US_HOLD_COST_AMOUNT   ,
DD_EXTENDED_HOLD_QUANTITY     ,
SALES_TERRITORY_KEY           ,
CORP_BKG_RECOMPUTE_FLAG  ,     
DD_COMP_US_STANDARD_PRICE_AMT ,
BK_FISCAL_CALENDAR_CODE       ,
BK_FISCAL_YEAR_NUMBER_INT    , 
BK_FISCAL_MONTH_NUMBER_INT ,   
DV_FISCAL_YEAR_MTH_NUMBER_INT ,
ERP_EC.SALES_ORDER_KEY               ,
ERP_EC.SHIP_TO_CUSTOMER_KEY     ,     
ERP_EC.BILL_TO_CUSTOMER_KEY       ,   
ERP_EC.SOLD_TO_CUSTOMER_KEY      ,    
ERP_EC.PRODUCT_KEY                   ,
ERP_EC.SALES_ORDER_LINE_KEY ,         
CANCEL_CODE ,
ERP_EC.EDW_CREATE_USER          ,     
ERP_EC.EDW_UPDATE_USER           ,    
ERP_EC.EDW_CREATE_DATETIME    ,       
ERP_EC.EDW_UPDATE_DATETIME  ,
CONVERSION_RT, 
BK_ISO_CURRENCY_CODE, 
ORDER_DTM , 
ERP_EC.RU_CISCO_BOOKED_DATETIME, 
ERP_EC.BK_SO_NUMBER_INT, 
ERP_EC.SALES_ORDER_OPERATING_UNIT, 
ERP_EC.SALES_ORDER_CATEGORY_TYPE,
ERP_EC.CANCELLED_FLG, /* R10 Cancel Flag */
ERP_EC.DV_REVENUE_RECOGNITION_FLG   , /* Added as part of true demand bkgs definition*/    
ERP_EC.DV_NET_SPREAD_FLG,     /* Added as part of true demand bkgs definition*/ 
/* Added as part of OFFER ATTRIBUTION*/
ERP_EC.DV_ATTRIBUTION_CD,
ERP_EC.DV_PRODUCT_KEY,
ERP_EC.DV_SALES_ORDER_LINE_KEY,
ERP_EC.SK_OFFER_ATTRIBUTION_ID_INT	  ,
  ERP_EC.DV_LOCAL_EXTND_LIST_PRICE_AMT,
     ERP_EC.LOCAL_UNIT_LIST_PRICE_AMT,
     ERP_EC.DV_UNIT_LIST_PRICE_USD_AMT
/* Added as part of Q1FY18 Pa goponnus */
,ERP_EC.PURCHASE_ADJ_DISCOUNT_USD_AMT
,ERP_EC.POB_TYPE_CD /* Added as part of NRS MPOB Changes */
,ERP_EC.NRS_TRANSITION_FLG /* Added as part of NRS PI3 Changes */
,ERP_EC.SALES_MOTION_CD /* Added as part of Oct - 2017 rel */
,NSO.SUMMARY_ORDER_FLG AS SUMMARY_QUOTE_FLG/* Changed as part of Aug - 2020 rel */
,ERP_EC.DD_COMP_US_ORIG_LIST_PRICE
,ERP_EC.DD_COMP_US_ORIG_EXT_LIST_PRICE
,NSOL.DV_INV_DTM AS DV_INV_DTM
,NSOL.BK_SO_SRC_CRT_DATETIME AS DV_COMPENSATION_DTM
,ERP_EC.RU_SERVICE_CONTRACT_START_DTM
,ERP_EC.RU_SERVICE_CONTRACT_END_DTM
,ERP_EC.DV_CONTRACT_DURATION
,ERP_EC.DV_ANNUALIZED_FLG
,ERP_EC.DV_ANNUALIZED_US_NET_AMT
,ERP_EC.DV_MULTIYEAR_US_NET_AMT
,ERP_EC.BOOKINGS_POLICY_CD
,ERP_EC.SOURCE_REP_ANNUAL_USD_AMT
FROM $$STGDB.WI_DRVD_ERP_CURR_CC_NBM ERP_EC
INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_TV NSO
	ON ERP_EC.SALES_ORDER_KEY = NSO.SALES_ORDER_KEY
INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_LINE_TV NSOL
	ON ERP_EC.DV_SALES_ORDER_LINE_KEY = NSOL.SALES_ORDER_LINE_KEY
/*
LEFT OUTER JOIN ( SELECT SALES_ORDER_LINE_KEY 
					FROM
                    (
					SELECT
					SALES_ORDER_LINE_KEY,
					SALES_MOTION_CD,
					DV_EFFECTIVE_DTM,
					EDW_UPDATE_DTM,
					SUM(DV_ALLOCATION_PCT) OVER(PARTITION BY SALES_ORDER_LINE_KEY ) SUM_ALLOCATION_PCT,
					CAST( DV_ALLOCATION_PCT/SUM_ALLOCATION_PCT AS DECIMAL(18,6) ) AS DV_ALLOCATION_PCT 
					FROM $$SLSORDVWDB.MT_SUMMARY_QUOTE_SOL_ALLOC 
                    WHERE DV_EXPIRATION_DTM = '3500-01-01 00:00:00' 
					) WI
                   GROUP BY 1 HAVING ROUND(SUM(DV_ALLOCATION_PCT)) = 1.00 ) SQ
ON  ERP_EC.DV_SALES_ORDER_LINE_KEY = SQ.SALES_ORDER_LINE_KEY*/
WHERE ERP_EC.PROCESS_DATE <= (SELECT PROCESS_DATE FROM $$ETLVWDB.BKG_PROCESS_DT_CNTRL)


Post SQL : 



Target3 Name : WI_BKGS_ERP_SO_CURR_NBM4


Pre SQL : 
DELETE FROM $$STGDB.WI_BKGS_ERP_SO_CURR_NBM ALL;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_BKGS_ERP_SO_CURR_NBM','D');

/* START Added as part of SQ Bookings - Dec 14th rel */  

UPDATE CURR_NBM
FROM
$$STGDB.WI_BKGS_ERP_SO_CURR_NBM CURR_NBM,
  (
  SELECT
   DRVD_NCR_BKG_TRX_KEY ,
   PROCESS_DATE 
   FROM $$STGDB.WI_BKGS_ERP_SO_CURR_NBM CURR_NBM
   WHERE DV_SALES_ORDER_LINE_KEY  NOT IN (
      SELECT DV_SALES_ORDER_LINE_KEY
      FROM  $$SLSORDVWDB.N_BOOKINGS_MEASURE 
      WHERE BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP' 
      AND SUMMARY_QUOTE_FLG = 'Y' 
      GROUP BY 1 )
   AND CURR_NBM.FORWARD_REVERSE_CODE = 'R' 
   AND CURR_NBM.SUMMARY_QUOTE_FLG = 'Y'
   AND CURR_NBM.CANCEL_CODE <> 'Lost Order' /* To handle scenario of debooking and booking processed with same process date */
   UNION
   /*Below union part is to handle multiple net change process dates processed with single bookings process date*/
   SELECT
   DRVD_NCR_BKG_TRX_KEY ,
   PROCESS_DATE 
   FROM $$STGDB.WI_BKGS_ERP_SO_CURR_NBM CURR_NBM
   WHERE DV_SALES_ORDER_LINE_KEY  NOT IN (
      SELECT DV_SALES_ORDER_LINE_KEY
      FROM  $$SLSORDVWDB.N_BOOKINGS_MEASURE 
      WHERE BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP' 
      AND SUMMARY_QUOTE_FLG = 'Y' 
      GROUP BY 1 )
   AND CURR_NBM.FORWARD_REVERSE_CODE = 'F' 
   AND CURR_NBM.SUMMARY_QUOTE_FLG = 'Y'
   QUALIFY RANK() OVER( PARTITION BY DV_SALES_ORDER_LINE_KEY ORDER BY PROCESS_DATE DESC ) > 1
   ) WI
SET SUMMARY_QUOTE_FLG = 'N'
WHERE CURR_NBM.DRVD_NCR_BKG_TRX_KEY = WI.DRVD_NCR_BKG_TRX_KEY 
   AND CURR_NBM.PROCESS_DATE = WI.PROCESS_DATE ;

/* END Added as part of SQ Bookings - Dec 14th rel */


Source4 Name : SQ_WI_BKGS_ERP_SO_CURR_NBM5


Pre SQL : 



SQL Query : 
SELECT 
ERP_EC.DRVD_NCR_BKG_TRX_KEY    AS BOOKINGS_MEASURE_KEY,
ERP_EC.SALES_ORDER_KEY     AS SALES_ORDER_KEY,
ERP_EC.SALES_ORDER_LINE_KEY    AS SALES_ORDER_LINE_KEY,
ERP_EC.PRODUCT_KEY     AS PRODUCT_KEY,
CASE 
WHEN SOURCE_SYSTEM_CODE='BV' 
THEN -8888 
WHEN SOURCE_SYSTEM_CODE='QTC' 
THEN -9999 
WHEN SOURCE_SYSTEM_CODE='CG' 
THEN -7777  
END AS AR_TRX_LINE_KEY,
CASE 
WHEN SOURCE_SYSTEM_CODE='BV' 
THEN -8888 
WHEN SOURCE_SYSTEM_CODE='QTC' 
THEN -9999 
WHEN SOURCE_SYSTEM_CODE='CG' 
THEN -7777  
END AS AR_TRX_KEY,
COALESCE(NSEC.END_CUSTOMER_KEY,-999)   AS END_CUSTOMER_KEY,
COALESCE(ERP_EC.BILL_TO_CUSTOMER_KEY,-999)  AS BILL_TO_CUSTOMER_KEY,
COALESCE(ERP_EC.SHIP_TO_CUSTOMER_KEY,-999)  AS SHIP_TO_CUSTOMER_KEY,
COALESCE(ERP_EC.SOLD_TO_CUSTOMER_KEY,-999)  AS SOLD_TO_CUSTOMER_KEY,
ERP_EC.TRANSACTION_DATETIME    AS TRANSACTION_DATETIME,
COALESCE(ERP_EC.SALES_TERRITORY_KEY,-999)  AS SALES_TERRITORY_KEY,
COALESCE(ERP_EC.SALES_REP_NUMBER,-999)   AS SALES_REP_NUMBER,
ERP_EC.PROCESS_DATE     AS BOOKINGS_PROCESS_DATE,
ERP_EC.DV_FISCAL_YEAR_MTH_NUMBER_INT   AS DV_FISCAL_YEAR_MTH_NUMBER_INT,
CAST(-9999 AS INTEGER)     AS BK_POS_TRANSACTION_ID_INT,
CAST(-9999 AS INTEGER)     AS BK_SALES_ADJ_LINE_NUMBER_INT,
CAST(-9999 AS INTEGER)     AS BK_SALES_ADJ_NUMBER_INT,
'UNKNOWN'      AS ADJUSTMENT_TYPE_CODE,
ERP_EC.SALES_CHANNEL_CODE    AS SALES_CHANNEL_CODE,
ERP_EC.SALES_CREDIT_TYPE_CODE    AS SALES_CREDIT_TYPE_CODE,
'UNKNOWN'      AS IDE_ADJUSTMENT_CODE,
'UNKNOWN'      AS ADJUSTMENT_CODE,
'ERP'       AS BKGS_MEASURE_TRANS_TYPE_CODE,
ERP_EC.CANCELLED_FLG    AS CANCELLED_FLG, /* R10 Cancel Flag */
COALESCE(ERP_EC.DD_ACQUISITION_FLAG, '=')  AS ACQUISITION_FLG,
ERP_EC.FORWARD_REVERSE_CODE    AS FORWARD_REVERSE_FLG,
'='       AS DISTRIBUTOR_OFFSET_FLG,
COALESCE(ERP_EC.DD_CORP_BKG_FLAG , '=')  AS CORPORATE_BOOKINGS_FLG,
COALESCE(ERP_EC.DD_OVERLAY_FLAG, '=')   AS OVERLAY_FLG,
COALESCE(ERP_EC.DD_IC_REVENUE_FLAG , '=')  AS IC_REVENUE_FLG,
COALESCE(ERP_EC.DD_CHARGES_FLAG , '=')   AS CHARGES_FLG,
COALESCE(ERP_EC.DD_SALESREP_FLAG , '=')  AS SALESREP_FLG,
COALESCE(ERP_EC.DD_MISC_FLAG , '=')   AS MISC_FLG,
COALESCE(ERP_EC.DD_SERVICE_FLAG  , '=')  AS SERVICE_FLG,
COALESCE(ERP_EC.DD_INTERNATIONAL_DEMO_FLAG,'=') AS INTERNATIONAL_DEMO_FLG,
COALESCE(ERP_EC.DD_REPLACEMENT_DEMO_FLAG , '=') AS REPLACEMENT_DEMO_FLG,
COALESCE(ERP_EC.DD_REVENUE_FLAG , '=')   AS REVENUE_FLG,
COALESCE(ERP_EC.DD_RMA_FLAG, '=')   AS RMA_FLG,
ERP_EC.TRADE_IN_AMOUNT     AS TRADE_IN_AMOUNT,
ERP_EC.DD_COMP_US_NET_PRICE_AMOUNT   AS DD_COMP_US_NET_PRICE_AMOUNT,
ERP_EC.DD_COMP_US_LIST_PRICE_AMOUNT   AS DD_COMP_US_LIST_PRICE_AMOUNT,
ERP_EC.DD_COMP_US_COST_AMOUNT    AS DD_COMP_US_COST_AMOUNT ,
ERP_EC.DD_EXTENDED_QUANTITY    AS DD_EXTENDED_QUANTITY  ,
ERP_EC.DD_COMP_US_HOLD_NET_PRICE_AMT   AS DD_COMP_US_HOLD_NET_PRICE_AMT,
ERP_EC.DD_COMP_US_HOLD_LIST_PRICE_AMT   AS DD_COMP_US_HOLD_LIST_PRICE_AMT,
ERP_EC.DD_COMP_US_HOLD_COST_AMOUNT   AS DD_COMP_US_HOLD_COST_AMOUNT ,
ERP_EC.DD_EXTENDED_HOLD_QUANTITY   AS DD_EXTENDED_HOLD_QUANTITY,
ERP_EC.DD_COMP_US_STANDARD_PRICE_AMT   AS DD_COMP_US_STANDARD_PRICE_AMT,
CAST(-999 AS INTEGER)     AS WIPS_ORIGINATOR_ID_INT,
CASE 
WHEN ERP_EC.SALES_CHANNEL_CODE  IN ('TWO TIER DISTRIBUTOR','2-TIER DISTRIBUTOR','Two Tier Distributor') 
THEN CAST(-777 AS Integer)
ELSE COALESCE(NSEC.END_CUSTOMER_KEY,-999) 
END       AS DV_END_CUSTOMER_KEY,
ERP_EC.CANCEL_CODE    AS CANCEL_CODE ,
ERP_EC.EDW_CREATE_USER     AS EDW_CREATE_USER,
ERP_EC.EDW_UPDATE_USER     AS EDW_UPDATE_USER,
CURRENT_TIMESTAMP(0)    AS EDW_CREATE_DATETIME,
CURRENT_TIMESTAMP(0)     AS EDW_UPDATE_DATETIME,
ERP_EC.CONVERSION_RT    AS CONVERSION_RT, 
ERP_EC.BK_ISO_CURRENCY_CODE   AS DD_TRX_CURRENCY_CD, 
ERP_EC.ORDER_DTM    AS CONVERSION_DT, 
ERP_EC.RU_CISCO_BOOKED_DATETIME   AS DD_CISCO_BOOKED_DTM, 
ERP_EC.BK_SO_NUMBER_INT    AS DD_BK_SO_NUMBER_INT,
ERP_EC.SALES_ORDER_OPERATING_UNIT  AS DD_SLS_ORD_OPERATING_UNIT_CD, 
ERP_EC.SALES_ORDER_CATEGORY_TYPE  AS DD_SALES_ORDER_CATEGORY_TYPE,
ERP_EC.SPLIT_PERCENTAGE    AS BOOKINGS_SPLIT_PCT,  /**R9**/
 ERP_EC.DV_REVENUE_RECOGNITION_FLG ,    /* Added as part of true demand bkgs definition*/    
ERP_EC.DV_NET_SPREAD_FLG,       /* Added as part of true demand bkgs definition*/
ERP_EC.DV_ATTRIBUTION_CD,               /* Added as part of Offer Attribution project*/
 ERP_EC.DV_PRODUCT_KEY,     /* Added as part of Offer Attribution project*/
 ERP_EC.DV_SALES_ORDER_LINE_KEY,         /* Added as part of Offer Attribution project*/
ERP_EC.SK_OFFER_ATTRIBUTION_ID_INT  ,    /* Added as part of Offer Attribution project*/  
ERP_EC.DV_LOCAL_EXTND_LIST_PRICE_AMT,
     ERP_EC.LOCAL_UNIT_LIST_PRICE_AMT,
     ERP_EC.DV_UNIT_LIST_PRICE_USD_AMT 
/* Added as part of PA goponnus */
,ERP_EC.PURCHASE_ADJ_DISCOUNT_USD_AMT
,ERP_EC.POB_TYPE_CD /* Added as part of NRS MPOB Changes */
,ERP_EC.NRS_TRANSITION_FLG /* Added as part of NRS PI3 Changes */
,ERP_EC.SALES_MOTION_CD /* Added as part of Oct - 2017 rel */
,ERP_EC.SUMMARY_QUOTE_FLG  /* Added as part of Oct - 2017 rel */
,ERP_EC.DD_COMP_US_ORIG_LIST_PRICE
,ERP_EC.DD_COMP_US_ORIG_EXT_LIST_PRICE
,ERP_EC.DV_INV_DTM
,ERP_EC.DV_COMPENSATION_DTM
,ERP_EC.RU_SERVICE_CONTRACT_START_DTM
,ERP_EC.RU_SERVICE_CONTRACT_END_DTM
,ERP_EC.DV_CONTRACT_DURATION
,ERP_EC.DV_ANNUALIZED_FLG
,ERP_EC.DV_ANNUALIZED_US_NET_AMT
,ERP_EC.DV_MULTIYEAR_US_NET_AMT
,ERP_EC.BOOKINGS_POLICY_CD
,ERP_EC.SOURCE_REP_ANNUAL_USD_AMT
FROM $$STGDB.WI_BKGS_ERP_SO_CURR_NBM ERP_EC
LEFT OUTER JOIN $$SLSORDVWDB.N_SOL_END_CUSTOMER NSEC
ON(ERP_EC.DV_SALES_ORDER_LINE_KEY  =  NSEC.SALES_ORDER_LINE_KEY)


Post SQL : 



Target4 Name : WI_BOOKINGS_ERP_CURR_NBM5


Pre SQL : 
DELETE FROM $$STGDB.WI_BOOKINGS_ERP_CURR_NBM ALL;


Post SQL : 
DELETE FROM $$STGDB.WI_DEBKG_MX_EDW_UPDATE_DTM;

INSERT INTO $$STGDB.WI_DEBKG_MX_EDW_UPDATE_DTM
SELECT MAX(EDW_UPDATE_DTM) FROM $$NRTNCRVWDB.MT_DRVD_NRT_DEBOOKINGS_TRX ;