


Source1 Name : SQ_W_ATTR_PRDT_NEW_RNWL_ACV


Pre SQL : 



SQL Query : 
SELECT
  ST.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
  ST.SK_RTR_ATTRIBUTION_ID,
  ST.ATTR_PRDT_KEY,
  ST.SALES_ORDER_LINE_KEY,
  ST.HQ_CR_PRTY_KEY,
  ST.TRANSACTION_CR_PARTY_KEY,
  ST.BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
  ST.BK_TECH_GROUP_ID,
  ST.BK_AS_ARCHITECTURE_NAME,
  ST.COVERED_PRDT_KEY,
  ST.ATTR_PRDT_QTY,
  ST.ATTR_PCT,
  ST.ATTR_NET_PRICE_LOCAL_AMT,
  ST.ATTR_EXTD_PRICE_LOCAL_AMT,
  ST.SALES_MOTION_CD,
  ST.SALES_MOTION_CONTEXT_NAME, 
  ST.ERP_CUST_ACCT_LOC_KEY,
  ST.AS_TS_CD,
  ST.SK_LINE_REF_NUM,
  ST.SK_ERP_BKGS_TRX_ID,
  ST.SK_RENEW_CONTRACT_LINE_ID,
  ST.SK_AS_PARENT_INVENTORY_ITEM_ID,
  ST.ITEM_CATEGORY_NAME,
  ST.ERP_TRX_VERSION_INT,
  ST.SS_CD,
  ST.SK_ATTRIBUTION_ID_INT,
  COALESCE(ATTR_PRDT_CLASS_NAME,'UNKNOWN') AS ATTR_PRDT_CLASS_NAME,
  (CASE WHEN  ITEM_CATEGORY_NAME NOT IN ('Billing', 'FLEXIBLE CONSUMPTION MODEL') AND RENEWAL_REF_CD  ='LINE REFERENCE NUMBER' THEN 
  (CASE WHEN RENEWAL_ERP_REF_VALUE<> 'UNKNOWN' THEN RENEWAL_ERP_REF_VALUE ELSE RENEWAL_REF_ID END) 
  ELSE RENEWAL_REF_ID END) AS RENEWAL_REF_ID,
  (CASE WHEN  ITEM_CATEGORY_NAME NOT IN ('Billing', 'FLEXIBLE CONSUMPTION MODEL') AND RENEWAL_REF_CD  ='LINE REFERENCE NUMBER' AND RENEWAL_ERP_REF_VALUE<> 'UNKNOWN'  THEN 'SO LINE ID'
  ELSE RENEWAL_REF_CD END) AS RENEWAL_REF_CD,
  ST.SMR_TAGGING_FAILURE_RSN_CD,
  ST.SALES_MOTION_TIMING_CD,
  ST.MANUAL_OVERRIDE_ROLE,
  ST.TOTAL_SERVICES_USD_AMT,
  ST.ACV_USD_AMT,
  ST.TCV_USD_AMT,
  ST.EXTENDED_PRICE_USD_AMT,
  ST.REQUESTING_CSCO_WRKR_PRTY_KEY,
  ST.SLS_MTN_CORRECTION_CASE_NUM,
  ST.SLS_MTN_CORRECTION_CMNT,
  CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM,
  USER  EDW_CREATE_USER,
  CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM,
  USER EDW_UPDATE_USER, 
  ST.START_TV_DTM,
  CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)) AS END_TV_DTM,     
 OFFER_ATTRIB_PRDT_KEY,  
  POS_TRANSACTION_ID_INT AS POS_TRANSACTION_ID_INT,
  ORDER_ORIGIN_CD,
 ST.SK_TRX_ID_INT,
 ST.SK_OPL_HEADER_ID_INT,
 'N' ACTION_CODE,
 'I' DML_TYPE,
 DV_RENEWAL_GAP_DAYS_CNT
  FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV ST
   WHERE  ORDER_ORIGIN_CD <> 'DISTI-DSV' AND 
   NOT EXISTS (SELECT 1 FROM  $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV N_ATTR_TV
                WHERE N_ATTR_TV.SK_ERP_BKGS_TRX_ID = ST.SK_ERP_BKGS_TRX_ID
       AND N_ATTR_TV.ERP_TRX_VERSION_INT = ST.ERP_TRX_VERSION_INT
  AND N_ATTR_TV.END_TV_DTM = '3500-01-01 00:00:00'
  AND ORDER_ORIGIN_CD <> 'DISTI-DSV' )
UNION ALL 
SELECT
  ST.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
  ST.SK_RTR_ATTRIBUTION_ID,
  ST.ATTR_PRDT_KEY,
  ST.SALES_ORDER_LINE_KEY,
  ST.HQ_CR_PRTY_KEY,
  ST.TRANSACTION_CR_PARTY_KEY,
  ST.BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
  ST.BK_TECH_GROUP_ID,
  ST.BK_AS_ARCHITECTURE_NAME,
  ST.COVERED_PRDT_KEY,
  ST.ATTR_PRDT_QTY,
  ST.ATTR_PCT,
  ST.ATTR_NET_PRICE_LOCAL_AMT,
  ST.ATTR_EXTD_PRICE_LOCAL_AMT,
  ST.SALES_MOTION_CD,
  ST.SALES_MOTION_CONTEXT_NAME, 
  ST.ERP_CUST_ACCT_LOC_KEY,
  ST.AS_TS_CD,
  ST.SK_LINE_REF_NUM,
  ST.SK_ERP_BKGS_TRX_ID,
  ST.SK_RENEW_CONTRACT_LINE_ID,
  ST.SK_AS_PARENT_INVENTORY_ITEM_ID,
  ST.ITEM_CATEGORY_NAME,
  ST.ERP_TRX_VERSION_INT,
  ST.SS_CD,
  ST.SK_ATTRIBUTION_ID_INT,
  COALESCE(ATTR_PRDT_CLASS_NAME,'UNKNOWN') AS ATTR_PRDT_CLASS_NAME,
  (CASE WHEN  ITEM_CATEGORY_NAME NOT IN ('Billing', 'FLEXIBLE CONSUMPTION MODEL') AND RENEWAL_REF_CD  ='LINE REFERENCE NUMBER' THEN 
  (CASE WHEN RENEWAL_ERP_REF_VALUE<> 'UNKNOWN' THEN RENEWAL_ERP_REF_VALUE ELSE RENEWAL_REF_ID END) 
  ELSE RENEWAL_REF_ID END) AS RENEWAL_REF_ID,
  (CASE WHEN  ITEM_CATEGORY_NAME NOT IN ('Billing', 'FLEXIBLE CONSUMPTION MODEL') AND RENEWAL_REF_CD  ='LINE REFERENCE NUMBER' AND RENEWAL_ERP_REF_VALUE<> 'UNKNOWN'  THEN 'SO LINE ID'
  ELSE RENEWAL_REF_CD END) AS RENEWAL_REF_CD,
  ST.SMR_TAGGING_FAILURE_RSN_CD,
  ST.SALES_MOTION_TIMING_CD,
  ST.MANUAL_OVERRIDE_ROLE,
  ST.TOTAL_SERVICES_USD_AMT,
  ST.ACV_USD_AMT,
  ST.TCV_USD_AMT,
  ST.EXTENDED_PRICE_USD_AMT,
  ST.REQUESTING_CSCO_WRKR_PRTY_KEY,
  ST.SLS_MTN_CORRECTION_CASE_NUM,
  ST.SLS_MTN_CORRECTION_CMNT,
  CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM,
  USER  EDW_CREATE_USER,
  CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM,
  USER EDW_UPDATE_USER, 
  ST.START_TV_DTM,
  CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)) AS END_TV_DTM,     
 OFFER_ATTRIB_PRDT_KEY,  
  POS_TRANSACTION_ID_INT AS POS_TRANSACTION_ID_INT,
  ORDER_ORIGIN_CD,
 ST.SK_TRX_ID_INT,
 ST.SK_OPL_HEADER_ID_INT,
 'N' ACTION_CODE,
 'I' DML_TYPE,
 DV_RENEWAL_GAP_DAYS_CNT
  FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV ST
   WHERE   ORDER_ORIGIN_CD = 'DISTI-DSV' AND 
   NOT EXISTS (SELECT 1 FROM  $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV N_ATTR_TV
                WHERE N_ATTR_TV.POS_TRANSACTION_ID_INT = ST.POS_TRANSACTION_ID_INT
       AND N_ATTR_TV.ERP_TRX_VERSION_INT = ST.ERP_TRX_VERSION_INT
  AND N_ATTR_TV.END_TV_DTM = '3500-01-01 00:00:00'
  AND ORDER_ORIGIN_CD = 'DISTI-DSV' )


Post SQL : 



Target1 Name : W_ATTR_PRDT_NEW_RNWL_ACV


Pre SQL : 
DELETE FROM $$WORKDB.W_ATTR_PRDT_NEW_RNWL_ACV ALL;


Post SQL : 
UPDATE W FROM $$WORKDB.W_ATTR_PRDT_NEW_RNWL_ACV W , $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ITM_SLSTRX_NRT TRX,
$$COMREFVWDB.N_PRODUCT NP,$$NRTNCRVWDB.N_XAAS_SO_SBSCRPTN_ATTRBTN_NRT XOA, $$COMREFVWDB.N_PRODUCT NP1
SET SALES_MOTION_CD='NEW',
EDW_UPDATE_USER='SVC_COMP_SOFTWARE'
WHERE 
W.SK_ERP_BKGS_TRX_ID=TRX.SK_TRX_ID_INT
AND TRX.SUBSCRIPTION_PRODUCT_KEY=NP.ITEM_KEY
AND W.SK_ATTRIBUTION_ID_INT=XOA.BK_OFFER_ATTRIBUTION_ID_INT
AND XOA.ORDERED_PRODUCT_KEY=NP1.ITEM_KEY
AND XOA.BK_OFFER_ATTRIBUTION_ID_INT > 0
AND W.SALES_MOTION_CD='UNKNOWN'
AND ( W.ITEM_CATEGORY_NAME IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' )
OR W.ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )
AND W.ORDER_ORIGIN_CD <> 'DISTI-DSV'
AND NP.MONETIZATION_TYPE_CD IN ('TERM')
AND NP.PRDT_SETUP_CLASSIFICATION_CD IN ('SOFTWARE')
AND NP1.GOODS_OR_SERVICE_TYPE='SERVICE';

UPDATE W FROM $$WORKDB.W_ATTR_PRDT_NEW_RNWL_ACV W , $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ITM_SLSTRX_NRT TRX,
$$COMREFVWDB.N_PRODUCT NP
SET SALES_MOTION_CD='NEW',
EDW_UPDATE_USER='SOWA_COMP_SOFTWARE'
WHERE
W.SK_ERP_BKGS_TRX_ID=TRX.SK_TRX_ID_INT
AND TRX.SUBSCRIPTION_PRODUCT_KEY=NP.ITEM_KEY
AND W.SALES_MOTION_CD='UNKNOWN'
AND ( W.ITEM_CATEGORY_NAME IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' )
OR W.ORDER_ORIGIN_CD IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN ) )
AND W.ORDER_ORIGIN_CD <> 'DISTI-DSV'
AND NP.GOODS_OR_SERVICE_TYPE = 'SERVICE'
AND NP.PRDT_SETUP_CLASSIFICATION_CD IN ('SOFTWARE');

UPDATE W FROM $$WORKDB.W_ATTR_PRDT_NEW_RNWL_ACV W , $$SLSORDVWDB.N_SALES_ORDER_LINE NSOL,
$$COMREFVWDB.N_PRODUCT NP,$$NRTNCRVWDB.N_SOL_OFFER_ATTRIBUTION NSOA, $$COMREFVWDB.N_PRODUCT NP1
SET SALES_MOTION_CD='NEW',
EDW_UPDATE_USER='SVC_COMP_SOFTWARE'
WHERE 
W.SALES_ORDER_LINE_KEY=NSOL.SALES_ORDER_LINE_KEY
AND NSOL.PRODUCT_KEY=NP.ITEM_KEY
AND W.SK_ATTRIBUTION_ID_INT=NSOA.SK_OFFER_ATTRIBUTION_ID_INT
AND NSOA.ATTRIBUTED_PRODUCT_KEY=NP1.ITEM_KEY
AND NSOA.SK_OFFER_ATTRIBUTION_ID_INT > 0
AND W.SALES_MOTION_CD='UNKNOWN'
AND W.ITEM_CATEGORY_NAME NOT IN ( 'Billing', 'FLEXIBLE CONSUMPTION MODEL' )
AND W.ORDER_ORIGIN_CD NOT IN ( SELECT ORDER_ORIGIN FROM $$ETLVWDB.EL_ORDER_ORIGIN )
AND W.ORDER_ORIGIN_CD <> 'DISTI-DSV'
AND NP.MONETIZATION_TYPE_CD IN ('TERM')
AND NP.PRDT_SETUP_CLASSIFICATION_CD IN ('SOFTWARE')
AND NP1.GOODS_OR_SERVICE_TYPE='SERVICE';


UPDATE W FROM $$WORKDB.W_ATTR_PRDT_NEW_RNWL_ACV W , $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE NPOS,
$$COMREFVWDB.N_PRODUCT NP,$$SLSORDVWDB.N_POS_TRX_LINE_OFFER_ATRBTN NPOA, $$COMREFVWDB.N_PRODUCT NP1
SET SALES_MOTION_CD='NEW',
EDW_UPDATE_USER='SVC_COMP_SOFTWARE'
WHERE 
W.POS_TRANSACTION_ID_INT = NPOS.BK_POS_TRANSACTION_ID_INT
AND NPOS.PRODUCT_KEY = NP.ITEM_KEY
AND W.SK_ATTRIBUTION_ID_INT = NPOA.BK_OFFER_ATTRIBUTION_ID_INT
AND NPOA.ATTRIBUTED_PRODUCT_KEY = NP1.ITEM_KEY
AND NPOA.BK_OFFER_ATTRIBUTION_ID_INT > 0
AND W.SALES_MOTION_CD = 'UNKNOWN'
AND W.ORDER_ORIGIN_CD IN ('DISTI-DSV') --  VALUE REQUIRED TO CHECK
AND NP.MONETIZATION_TYPE_CD IN ('TERM')
AND NP.PRDT_SETUP_CLASSIFICATION_CD IN ('SOFTWARE')
AND NP1.GOODS_OR_SERVICE_TYPE = 'SERVICE';

CALL COLLECT_STATS_WRAP('$$WORKDB','W_ATTR_PRDT_NEW_RNWL_ACV','D');