


Source1 Name : SQ_WI_POS_SCA_INCR_BKG


Pre SQL : 
DELETE FROM $$STGDB.WI_POS_SCA_INCR_BKG ALL;


SQL Query : 
SELECT 
	COALESCE(SCA.POS_SCAAC_KEY,-999) AS POS_SCAAC_KEY,
	BK_TRX.BK_POS_TRX_ID_INT AS PD_BK_POS_TRANSACTION_ID_INT,
	BK_TRX.BASE_LIST_UNIT_PRDT_PRICE_AMT as BASE_LIST_UNIT_PROD_PRICE_AMT ,
	BK_TRX.DSTRBTR_RPTD_CST_UNT_PRC_AMT AS DISTI_RPTD_COST_UNIT_PRICE_AMT,
	BK_TRX.VALIDATED_NET_UNT_PRC_USD_AMT as VLDTD_NET_UNIT_PRICE_USD_AMT,
	BK_TRX.VALUATION_PRICE_USD_AMT  as VALUATION_PRICE_USD_AMOUNT,
	COALESCE(SCA.PD_SALES_TERRITORY_KEY,-999) AS PD_SALES_TERRITORY_KEY,
	COALESCE(SCA.PD_SALES_REP_NUM,'UNKNOWN') AS PD_SALES_REP_NUM ,
	COALESCE(SCA.DISTRIBUTOR_OFFSET_FLG,'=') AS DISTRIBUTOR_OFFSET_FLG,
	COALESCE(SCA.PD_SALES_COMMISSION_PCT,0)  AS PD_SALES_COMMISSION_PCT,
	COALESCE(SCA.SK3_SC_ID_INT,-999) AS SC_ID_INT ,
	COALESCE(SCA.SOURCE_DELETED_FLG,'=') AS SOURCE_DELETED_FLG,
	BK_TRX.EDW_UPDATE_DTM AS LAST_UPDATED_DTM,
	CAST( BK_TRX.EDW_UPDATE_DTM AS DATE ) DV_LAST_UPDATED_DT,
	BK_TRX.EDW_UPDATE_DTM,
	CASE WHEN ( BK_TRX.EDW_UPDATE_DTM > COALESCE(SCA.SALES_CREDIT_START_DTM, CAST('1900-01-01 00:00:00' AS TIMESTAMP(0))))  
	           AND ( CAST(BK_TRX.EDW_UPDATE_DTM AS DATE) = CAST( COALESCE(SCA.SALES_CREDIT_START_DTM , CAST('1900-01-01 00:00:00' AS TIMESTAMP(0))) AS DATE ))
			THEN COALESCE(SCA.SALES_CREDIT_START_DTM, CAST('1900-01-01 00:00:00' AS TIMESTAMP(0)))  
         WHEN BK_TRX.EDW_UPDATE_DTM > COALESCE(SCA.SALES_CREDIT_START_DTM, CAST('1900-01-01 00:00:00' AS TIMESTAMP(0)))  THEN BK_TRX.EDW_UPDATE_DTM 
		    ELSE COALESCE( SCA.SALES_CREDIT_START_DTM, CAST('1900-01-01 00:00:00' AS TIMESTAMP(0)))
END START_DTM,
	COALESCE(SCA.EXPIRATION_DTM, CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))) AS END_TV_DTM,
	COALESCE(SCA.DISTRIBUTOR_BUCKET_FLG,'=') AS DISTRIBUTOR_BUCKET_FLG,
	BK_TRX.POS_TRX_LN_PRDT_QTY   ,
	COALESCE(SCA.SK_TRX_SC_ID_INT,-999) AS SK_TRX_SC_ID_INT ,
	'DSV_BKG' AS DSV_OR_POS_TYPE_CD, /*ADDED AS PART OF DSV Q1FY16*/
	 'N' AS POS_RETURN_ROLE /*ADDED AS PART OF DSV Q1FY16*/
	 /* ADDED AS PART OF JUNE 2018 RELEASE AMY-NRT SCOPE*/
,BK_TRX.RU_SERVICE_CONTRACT_START_DTM
,BK_TRX.RU_SERVICE_CONTRACT_END_DTM
,BK_TRX.RU_SRVC_CNTRCT_DRTN_MNTHS_CNT

	 QUALIFY RANK() OVER (PARTITION BY SCA.PD_BK_POS_TRANSACTION_ID_INT, SCA.DISTRIBUTOR_OFFSET_FLG ORDER BY END_TV_DTM DESC  )=1
FROM $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE_TV BK_TRX
LEFT JOIN $$NRTNCRVWDB.N_POS_SCA_ADJ_CNG_DRCT_NRT_TV SCA  /*ADDED AS PART OF DSV Q1FY16*/
ON SCA.PD_BK_POS_TRANSACTION_ID_INT= BK_TRX.BK_POS_TRX_ID_INT 
WHERE BK_TRX.EDW_UPDATE_DTM  >'$$LastExtractDate'
AND BK_TRX.EDW_UPDATE_DTM BETWEEN SCA.SALES_CREDIT_START_DTM AND SCA.EXPIRATION_DTM
/* AND START_DTM >'$$LastExtractDate' */


Post SQL : 



Target1 Name : WI_POS_SCA_INCR_BKG


Pre SQL : 



Post SQL : 
COLLECT STATS ON $$STGDB.WI_POS_SCA_INCR_BKG;


Source2 Name : SQ_WI_POS_SCA_INCR_BKG_SRC_OA


Pre SQL : 



SQL Query : 
/*Added the below Pipeline to fetch Incremental OA-DSV-BKGS Trx's from OA-POS Custom table - as part of OA-Q1FY16	*/
SELECT 
	COALESCE(SCA.POS_SCAAC_KEY,-999) AS POS_SCAAC_KEY,
	NPOS.BK_POS_TRANSACTION_ID_INT AS PD_BK_POS_TRANSACTION_ID_INT,
	BK_TRX.BASE_LIST_UNIT_PROD_PRICE_AMT as BASE_LIST_UNIT_PROD_PRICE_AMT ,
	BK_TRX.DISTI_RPTD_COST_UNIT_PRICE_AMT AS DISTI_RPTD_COST_UNIT_PRICE_AMT,
	BK_TRX.VLDTD_NET_UNIT_PRICE_USD_AMT as VLDTD_NET_UNIT_PRICE_USD_AMT,
	BK_TRX.VALUATION_PRICE_USD_AMOUNT  as VALUATION_PRICE_USD_AMOUNT,
	COALESCE(SCA.PD_SALES_TERRITORY_KEY,-999) AS PD_SALES_TERRITORY_KEY,
	COALESCE(SCA.PD_SALES_REP_NUM,'UNKNOWN') AS PD_SALES_REP_NUM ,
	COALESCE(SCA.DISTRIBUTOR_OFFSET_FLG,'=') AS DISTRIBUTOR_OFFSET_FLG,
	COALESCE(SCA.PD_SALES_COMMISSION_PCT,0)  AS PD_SALES_COMMISSION_PCT,
	COALESCE(SCA.SK3_SC_ID_INT,-999) AS SC_ID_INT ,
	COALESCE(SCA.SOURCE_DELETED_FLG,'=') AS SOURCE_DELETED_FLG,
	BK_TRX.EDW_UPDATE_DTM AS LAST_UPDATED_DTM,
	CAST( BK_TRX.EDW_UPDATE_DTM AS DATE ) DV_LAST_UPDATED_DT,
	BK_TRX.EDW_UPDATE_DTM,
	CASE WHEN ( NPOS.EDW_UPDATE_DTM > COALESCE(SCA.SALES_CREDIT_START_DTM, CAST('1900-01-01 00:00:00' AS TIMESTAMP(0))))  
	           AND ( CAST(NPOS.EDW_UPDATE_DTM AS DATE) = CAST( COALESCE(SCA.SALES_CREDIT_START_DTM , CAST('1900-01-01 00:00:00' AS TIMESTAMP(0))) AS DATE ))
			THEN COALESCE(SCA.SALES_CREDIT_START_DTM, CAST('1900-01-01 00:00:00' AS TIMESTAMP(0)))  
         WHEN NPOS.EDW_UPDATE_DTM > COALESCE(SCA.SALES_CREDIT_START_DTM, CAST('1900-01-01 00:00:00' AS TIMESTAMP(0)))  THEN NPOS.EDW_UPDATE_DTM 
		    ELSE COALESCE( SCA.SALES_CREDIT_START_DTM, CAST('1900-01-01 00:00:00' AS TIMESTAMP(0)))
END START_DTM,
	COALESCE(SCA.EXPIRATION_DTM, CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))) AS END_TV_DTM,
	COALESCE(SCA.DISTRIBUTOR_BUCKET_FLG,'=') AS DISTRIBUTOR_BUCKET_FLG,
	BK_TRX.POS_TRX_LINE_PRODUCT_QUANT   ,
	COALESCE(SCA.SK_TRX_SC_ID_INT,-999) AS SK_TRX_SC_ID_INT ,
	'DSV_BKG' AS DSV_OR_POS_TYPE_CD, /*ADDED AS PART OF DSV Q1FY16*/
	 'N' AS POS_RETURN_ROLE /*ADDED AS PART OF DSV Q1FY16*/
	 /* ADDED AS PART OF JUNE 2018 RELEASE AMY-NRT SCOPE*/
,BK_TRX.RU_SERVICE_CONTRACT_START_DTM
,BK_TRX.RU_SERVICE_CONTRACT_END_DTM
,BK_TRX.RU_SRVC_CNTRCT_DRTN_MNTHS_CNT  

FROM $$SLSORDVWDB.N_BKG_POS_TRANSACTION_LINE BK_TRX
INNER JOIN /*Added as part of Offer Attribution to Pull Incremental records from OA-Custom table*/
               (
              SELECT BK_POS_TRANSACTION_ID_INT,EDW_UPDATE_DTM
              FROM $$SLSORDVWDB.N_POS_TRX_LINE_OFFER_ATRBTN_TV
              WHERE END_TV_DTM='3500-01-01 00:00:00'
               AND  EDW_UPDATE_DTM  >  (SELECT LAST_EXTRACT_DATE FROM $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES
			   WHERE JOB_STREAM_ID='wf_WI_POS_SCA_INCR_BKG' AND TABLE_NAME='N_POS_TRX_LINE_OFFER_ATRBTN_TV') 
              QUALIFY ROW_NUMBER() OVER(PARTITION BY BK_POS_TRANSACTION_ID_INT ORDER BY EDW_UPDATE_DTM DESC)=1
              )  NPOS
ON NPOS.BK_POS_TRANSACTION_ID_INT=BK_TRX.BK_POS_TRANSACTION_ID_INT
INNER JOIN $$NRTNCRVWDB.N_POS_SCA_ADJ_CNG_DRCT_NRT_TV SCA  /*ADDED AS PART OF DSV Q1FY16*/
ON SCA.PD_BK_POS_TRANSACTION_ID_INT= BK_TRX.BK_POS_TRANSACTION_ID_INT 
AND SCA.END_TV_DTM='3500-01-01 00:00:00' 
WHERE NPOS.BK_POS_TRANSACTION_ID_INT NOT IN
(
SELECT PD_BK_POS_TRANSACTION_ID_INT FROM $$STGDB.WI_POS_SCA_INCR_BKG
GROUP BY 1
)


Post SQL : 



Target2 Name : WI_POS_SCA_INCR_BKG_TGT_OA


Pre SQL : 



Post SQL : 
COLLECT STATS ON $$STGDB.WI_POS_SCA_INCR_BKG ;

/*Updating the Last Extract date  to pull the incremental records-Q1FY16*/
UPDATE  $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES
SET LAST_EXTRACT_DATE=(SEL MAX(EDW_UPDATE_DTM) FROM $$SLSORDDB.N_POS_TRX_LINE_OFFER_ATRBTN_TV WHERE END_TV_DTM='3500-01-01 00:00:00') 
WHERE JOB_STREAM_ID='wf_WI_POS_SCA_INCR_BKG' AND TABLE_NAME='N_POS_TRX_LINE_OFFER_ATRBTN_TV';