


Source1 Name : SQ_WI_BOOKINGS_ERP_CURR_NBM1


Pre SQL : 



SQL Query : 
SELECT
  INNER_QUERY.BOOKINGS_MEASURE_KEY,
  INNER_QUERY.SALES_ORDER_KEY,
  INNER_QUERY.SALES_ORDER_LINE_KEY,
  INNER_QUERY.PRODUCT_KEY,
  INNER_QUERY.AR_TRX_LINE_KEY,
  INNER_QUERY.AR_TRX_KEY,
     INNER_QUERY.END_CUSTOMER_KEY,
     INNER_QUERY.BILL_TO_CUSTOMER_KEY,
     INNER_QUERY.SHIP_TO_CUSTOMER_KEY,
     INNER_QUERY.SOLD_TO_CUSTOMER_KEY,
     INNER_QUERY.DV_END_CUSTOMER_KEY,
     INNER_QUERY.TRANSACTION_DATETIME,
     INNER_QUERY.SALES_TERRITORY_KEY,
     INNER_QUERY.SALES_REP_NUMBER, 
     INNER_QUERY.BOOKINGS_PROCESS_DATE,
     INNER_QUERY.DV_FISCAL_YEAR_MTH_NUMBER_INT,
     INNER_QUERY.BK_POS_TRANSACTION_ID_INT,
     INNER_QUERY.BK_SALES_ADJ_LINE_NUMBER_INT,
     INNER_QUERY.BK_SALES_ADJ_NUMBER_INT,
     INNER_QUERY.ADJUSTMENT_TYPE_CODE,
     INNER_QUERY.SALES_CHANNEL_CODE,
     INNER_QUERY.SALES_CREDIT_TYPE_CODE,
     INNER_QUERY.IDE_ADJUSTMENT_CODE,
     INNER_QUERY.ADJUSTMENT_CODE,
     INNER_QUERY.BKGS_MEASURE_TRANS_TYPE_CODE,
     INNER_QUERY.CANCELLED_FLG,
     INNER_QUERY.CANCEL_CODE,
     INNER_QUERY.ACQUISITION_FLG,
     INNER_QUERY.FORWARD_REVERSE_FLG,
     INNER_QUERY.DISTRIBUTOR_OFFSET_FLG,
     INNER_QUERY.CORPORATE_BOOKINGS_FLG,
     INNER_QUERY.OVERLAY_FLG,
     INNER_QUERY.IC_REVENUE_FLG,
     INNER_QUERY.CHARGES_FLG,
     INNER_QUERY.SALESREP_FLG,
     INNER_QUERY.MISC_FLG,
     INNER_QUERY.SERVICE_FLG,
     INNER_QUERY.INTERNATIONAL_DEMO_FLG,
     INNER_QUERY.REPLACEMENT_DEMO_FLG,
     INNER_QUERY.REVENUE_FLG,
     INNER_QUERY.RMA_FLG,
     INNER_QUERY.TRADE_IN_AMOUNT,
     INNER_QUERY.DD_COMP_US_NET_PRICE_AMOUNT,
     INNER_QUERY.DD_COMP_US_LIST_PRICE_AMOUNT,
     INNER_QUERY.DD_COMP_US_COST_AMOUNT,
     INNER_QUERY.DD_EXTENDED_QUANTITY,
     INNER_QUERY.DD_COMP_US_HOLD_NET_PRICE_AMT,
     INNER_QUERY.DD_COMP_US_HOLD_LIST_PRICE_AMT,
     INNER_QUERY.DD_COMP_US_HOLD_COST_AMOUNT,
     INNER_QUERY.DD_EXTENDED_HOLD_QUANTITY,
     INNER_QUERY.DD_COMP_US_STANDARD_PRICE_AMT,
 CASE WHEN INNER_QUERY.WIPS_ORIGINATOR_ID_INT > 0 THEN INNER_QUERY.WIPS_ORIGINATOR_ID_INT
  WHEN Trim(INNER_QUERY.SALES_CHANNEL_CODE) IN ('DVAD' , 'Two Tier Distributor') THEN Coalesce(N_DISTI.BK_WIPS_ORIGINATOR_ID_INT,-999 ) 
  ELSE INNER_QUERY.WIPS_ORIGINATOR_ID_INT END AS WIPS_ORIGINATOR_ID_INT , /* Modified as part of SFP Rel */ 
     INNER_QUERY.EDW_CREATE_USER,
     INNER_QUERY.EDW_UPDATE_USER,
     INNER_QUERY.EDW_CREATE_DATETIME,
     INNER_QUERY.EDW_UPDATE_DATETIME,
     INNER_QUERY.CONVERSION_RT, 
     INNER_QUERY.CONVERSION_DT, 
     INNER_QUERY.DD_BK_SO_NUMBER_INT,
     INNER_QUERY.DD_CISCO_BOOKED_DTM,
     INNER_QUERY.DD_SALES_ORDER_CATEGORY_TYPE, 
     INNER_QUERY.DD_SLS_ORD_OPERATING_UNIT_CD, 
     INNER_QUERY.DD_TRX_CURRENCY_CD, 
     INNER_QUERY.DV_TRANSACTION_TYPE ,
     INNER_QUERY.ADJUSTMENT_DESCRIPTION_KEY,
     INNER_QUERY.ACTION_CODE,
     INNER_QUERY.DML_TYPE,
     INNER_QUERY.DV_TRANSACTION_NAME,
     INNER_QUERY.BOOKINGS_SPLIT_PCT,
     INNER_QUERY.DV_REVENUE_RECOGNITION_FLG,   /* Added as part of true demand bkgs definition*/    
     INNER_QUERY.DV_NET_SPREAD_FLG,            /* Added as part of true demand bkgs definition*/  
     INNER_QUERY.DV_ATTRIBUTION_CD,     /* Added as part of Offer Attribution Project*/  
     INNER_QUERY.DV_PRODUCT_KEY,      /* Added as part of Offer Attribution Project*/      
     INNER_QUERY.DV_SALES_ORDER_LINE_KEY,      /* Added as part of Offer Attribution Project*/      
     INNER_QUERY.SK_OFFER_ATTRIBUTION_ID_INT   /* Added as part of Offer Attribution Project*/ 
     ,CAL.FISCAL_YEAR_QUARTER_NUMBER_INT
     ,INNER_QUERY.AR_TRX_LINE_KEY AS DV_AR_TRX_LINE_KEY /*Added as part of Q3FY16-Offer Attribution*/
     ,-999 AS XAAS_OFFER_ATRBTN_REV_LINE_KEY /*Added as part of Q3FY16-Offer Attribution*/
     ,COALESCE(INNER_QUERY.DV_DEAL_ID,'-9999') AS  DV_DEAL_ID /*added for DEAL_ID*/
  ,INNER_QUERY.TSS_COUNTRY_FACTOR_KEY  /*4 columns added as part of BGM Q1FY17*/
  ,INNER_QUERY.DV_BKG_GROSS_MGN_AMOUNT
  ,INNER_QUERY.DV_BGM_FX_COST_AMOUNT
  ,INNER_QUERY.DV_FX_NET_PRICE_AMT   
  ,INNER_QUERY.DV_LOCAL_EXTND_LIST_PRICE_AMT  
  ,INNER_QUERY.LOCAL_UNIT_LIST_PRICE_AMT      
  ,INNER_QUERY.DV_UNIT_LIST_PRICE_USD_AMT     
  ,INNER_QUERY.DV_ORDER_VALUE_USD_AMOUNT    
  ,INNER_QUERY.DV_MTHLY_RCR_REV_TRXL_USD_AMT  
  ,INNER_QUERY.DV_INCRML_MTHY_RCRR_RV_USD_AMT 
  ,INNER_QUERY.DV_ANNLZD_MTHY_RCRR_RV_USD_AMT 
  ,INNER_QUERY.DV_INCRML_ANNL_RCRR_RV_USD_AMT 
 ,INNER_QUERY.PURCHASE_ADJ_DISCOUNT_USD_AMT
 ,INNER_QUERY.DV_BGM_NON_STANDARD_COST_AMT /*added as part product BGM - Q1FY18 release */
 ,INNER_QUERY.POB_TYPE_CD
 ,INNER_QUERY.NRS_TRANSITION_FLG
 ,INNER_QUERY.SALES_MOTION_CD /* Added as part of Oct - 2017 rel */
 ,INNER_QUERY.SUMMARY_QUOTE_FLG  /* Added as part of Oct - 2017 rel */
 ,INNER_QUERY.DV_BKG_REBATE
 ,INNER_QUERY.DV_FX_REBATE_PRICE_AMT
 ,INNER_QUERY.SK_SALES_MOTION_ATTRIB_KEY /* Added as part of SALES FY18 May12Rel */
 ,INNER_QUERY.DD_COMP_US_ORIG_LIST_PRICE
 ,INNER_QUERY.DD_COMP_US_ORIG_EXT_LIST_PRICE
 ,INNER_QUERY.DV_INV_DTM
 ,INNER_QUERY.DV_COMPENSATION_DTM 
,INNER_QUERY.RU_SERVICE_CONTRACT_START_DTM
,INNER_QUERY.RU_SERVICE_CONTRACT_END_DTM
,INNER_QUERY.DV_CONTRACT_DURATION
,INNER_QUERY.DV_ANNUALIZED_FLG
,INNER_QUERY.DV_ANNUALIZED_US_NET_AMT
,INNER_QUERY.DV_MULTIYEAR_US_NET_AMT
,INNER_QUERY.BOOKINGS_POLICY_CD
,INNER_QUERY.SOURCE_REP_ANNUAL_USD_AMT
   FROM
     (
     SELECT
     WBECN.BOOKINGS_MEASURE_KEY,
     WBECN.SALES_ORDER_KEY,
     WBECN.SALES_ORDER_LINE_KEY,
     WBECN.PRODUCT_KEY,
     WBECN.AR_TRX_LINE_KEY,
     WBECN.AR_TRX_KEY,
     WBECN.END_CUSTOMER_KEY,
     WBECN.BILL_TO_CUSTOMER_KEY,
     WBECN.SHIP_TO_CUSTOMER_KEY,
     WBECN.SOLD_TO_CUSTOMER_KEY,
     WBECN.DV_END_CUSTOMER_KEY,
     WBECN.TRANSACTION_DATETIME,
     WBECN.SALES_TERRITORY_KEY,
     WBECN.SALES_REP_NUMBER, 
     CASE WHEN NBM.BOOKINGS_PROCESS_DATE IS NOT NULL THEN NBM.BOOKINGS_PROCESS_DATE ELSE BKG_PRCDT.PROCESS_DATE END  BOOKINGS_PROCESS_DATE,
     WBECN.DV_FISCAL_YEAR_MTH_NUMBER_INT,
     WBECN.BK_POS_TRANSACTION_ID_INT,
     WBECN.BK_SALES_ADJ_LINE_NUMBER_INT,
     WBECN.BK_SALES_ADJ_NUMBER_INT,
     WBECN.ADJUSTMENT_TYPE_CODE,
     WBECN.SALES_CHANNEL_CODE,
     WBECN.SALES_CREDIT_TYPE_CODE,
     WBECN.IDE_ADJUSTMENT_CODE,
     WBECN.ADJUSTMENT_CODE,
     WBECN.BKGS_MEASURE_TRANS_TYPE_CODE,
     WBECN.CANCELLED_FLG,
     WBECN.CANCEL_CODE,
     WBECN.ACQUISITION_FLG,
     WBECN.FORWARD_REVERSE_FLG,
     WBECN.DISTRIBUTOR_OFFSET_FLG,
     WBECN.CORPORATE_BOOKINGS_FLG,
     WBECN.OVERLAY_FLG,
     WBECN.IC_REVENUE_FLG,
     WBECN.CHARGES_FLG,
     WBECN.SALESREP_FLG,
     WBECN.MISC_FLG,
     WBECN.SERVICE_FLG,
     WBECN.INTERNATIONAL_DEMO_FLG,
     WBECN.REPLACEMENT_DEMO_FLG,
     WBECN.REVENUE_FLG,
     WBECN.RMA_FLG,
     WBECN.TRADE_IN_AMOUNT,
     WBECN.DD_COMP_US_NET_PRICE_AMOUNT,
     WBECN.DD_COMP_US_LIST_PRICE_AMOUNT,
     WBECN.DD_COMP_US_COST_AMOUNT,
     WBECN.DD_EXTENDED_QUANTITY,
     WBECN.DD_COMP_US_HOLD_NET_PRICE_AMT,
     WBECN.DD_COMP_US_HOLD_LIST_PRICE_AMT,
     WBECN.DD_COMP_US_HOLD_COST_AMOUNT,
     WBECN.DD_EXTENDED_HOLD_QUANTITY,
     WBECN.DD_COMP_US_STANDARD_PRICE_AMT,
 COALESCE(NSL.BK_WIPS_ORIGINATOR_ID_INT,WBECN.WIPS_ORIGINATOR_ID_INT) AS WIPS_ORIGINATOR_ID_INT, /* Modified as part of SFP Rel */
     WBECN.EDW_CREATE_USER,
     WBECN.EDW_UPDATE_USER,
     WBECN.EDW_CREATE_DATETIME,
     WBECN.EDW_UPDATE_DATETIME,
     WBECN.CONVERSION_RT, 
     WBECN.ORDER_DTM AS CONVERSION_DT, 
     WBECN.BK_SO_NUMBER_INT AS DD_BK_SO_NUMBER_INT,
     WBECN.RU_CISCO_BOOKED_DATETIME AS DD_CISCO_BOOKED_DTM,
     WBECN.SALES_ORDER_CATEGORY_TYPE AS DD_SALES_ORDER_CATEGORY_TYPE, 
     WBECN.SALES_ORDER_OPERATING_UNIT AS DD_SLS_ORD_OPERATING_UNIT_CD, 
     WBECN.BK_ISO_CURRENCY_CODE AS DD_TRX_CURRENCY_CD, 
     NULL AS DV_TRANSACTION_TYPE ,
     NULL AS ADJUSTMENT_DESCRIPTION_KEY,
     '=' AS    ACTION_CODE,
     '=' AS    DML_TYPE,
     NULL AS DV_TRANSACTION_NAME,
     WBECN.BOOKINGS_SPLIT_PCT AS BOOKINGS_SPLIT_PCT,
        WBECN.DV_REVENUE_RECOGNITION_FLG,   /* Added as part of true demand bkgs definition*/    
        WBECN.DV_NET_SPREAD_FLG,            /* Added as part of true demand bkgs definition*/  
     WBECN.DV_ATTRIBUTION_CD,     /* Added as part of Offer Attribution Project*/  
        WBECN.DV_PRODUCT_KEY,      /* Added as part of Offer Attribution Project*/      
        WBECN.DV_SALES_ORDER_LINE_KEY,      /* Added as part of Offer Attribution Project*/      
     WBECN.SK_OFFER_ATTRIBUTION_ID_INT   /* Added as part of Offer Attribution Project*/ 
    ,COALESCE(NSL.BK_DEAL_ID,'-9999') AS  DV_DEAL_ID /*added for DEAL_ID*/
    ,CASE WHEN WBECN.SERVICE_FLG = 'Y'   AND WBECN.DD_COMP_US_NET_PRICE_AMOUNT <> 0 
  THEN
   CASE WHEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL  THEN  
     COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY)
    WHEN COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT) IS NOT NULL THEN
     COALESCE(L4_TSD.TSS_COUNTRY_FACTOR_KEY,L3_TSD.TSS_COUNTRY_FACTOR_KEY,L2_TSD.TSS_COUNTRY_FACTOR_KEY,L1_TSD.TSS_COUNTRY_FACTOR_KEY,-999) 
     ELSE -999 
   END 
 ELSE -999 END TSS_COUNTRY_FACTOR_KEY,
 
 CASE WHEN WBECN.SERVICE_FLG = 'Y'  AND WBECN.DD_COMP_US_NET_PRICE_AMOUNT <> 0 
   THEN
   CASE WHEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL  
       THEN  
     CAST( (WBECN.DD_COMP_US_NET_PRICE_AMOUNT - (COALESCE(TSS.COST_FACTOR_PCT,TSS1.COST_FACTOR_PCT)*
       (CASE WHEN DOLLAR_ADJUSTABLE_FLG='Y' THEN WBECN.DD_COMP_US_STANDARD_PRICE_AMT ELSE WBECN.DD_COMP_US_LIST_PRICE_AMOUNT END)/100)    
      )  AS DECIMAL(18,6) )   
    WHEN COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT) IS NOT NULL 
    THEN
     CAST( (WBECN.DD_COMP_US_NET_PRICE_AMOUNT *
      (COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT)/100) )  AS DECIMAL(18,6) )  
    ELSE 0
   END 
  ELSE 0
  END DV_BKG_GROSS_MGN_AMOUNT,
  
  
 CASE WHEN WBECN.SERVICE_FLG = 'Y'   AND WBECN.DD_COMP_US_NET_PRICE_AMOUNT <> 0 AND MCR.SALES_TERRITORY_KEY IS NOT NULL 
   THEN
    CASE WHEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL  
     THEN  
      CAST( ( (COALESCE(TSS.COST_FACTOR_PCT,TSS1.COST_FACTOR_PCT)*
       (CASE WHEN DOLLAR_ADJUSTABLE_FLG='Y' THEN WBECN.DD_COMP_US_STANDARD_PRICE_AMT ELSE WBECN.DD_COMP_US_LIST_PRICE_AMOUNT END)/100)    
       )  AS DECIMAL(18,6) )   
     WHEN COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT) IS NOT NULL 
     THEN
      CAST(COALESCE((COALESCE(MCR.ANNUAL_BUDGET_CONV_RT,0)/NULLIF(MCR.PL_CONVERSION_RT,0))*WBECN.DD_COMP_US_NET_PRICE_AMOUNT,0) * 
       (COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT))/100 AS DECIMAL(18,6) )  
     ELSE 0
    END 
   ELSE 0
   END DV_BGM_FX_COST_AMOUNT ,
 
 
 CASE WHEN (WBECN.SERVICE_FLG = 'Y' AND WBECN.DD_COMP_US_NET_PRICE_AMOUNT <> 0 AND 
 COALESCE(COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY),L4_TSD.TSS_COUNTRY_FACTOR_KEY,L3_TSD.TSS_COUNTRY_FACTOR_KEY,L2_TSD.TSS_COUNTRY_FACTOR_KEY,L1_TSD.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL )
 THEN COALESCE((COALESCE(MCR.ANNUAL_BUDGET_CONV_RT,0)/NULLIF(MCR.PL_CONVERSION_RT,0))*WBECN.DD_COMP_US_NET_PRICE_AMOUNT,0) 
 ELSE 0
 END AS DV_FX_NET_PRICE_AMT
 ,WBECN.DV_LOCAL_EXTND_LIST_PRICE_AMT 
 ,WBECN.LOCAL_UNIT_LIST_PRICE_AMT     
 ,WBECN.DV_UNIT_LIST_PRICE_USD_AMT 
 ,CAST(0.0 AS DECIMAL(18,6))DV_ORDER_VALUE_USD_AMOUNT    
 ,CAST(0.0 AS DECIMAL(18,6))DV_MTHLY_RCR_REV_TRXL_USD_AMT  
 ,CAST(0.0 AS DECIMAL(18,6))DV_INCRML_MTHY_RCRR_RV_USD_AMT 
 ,CAST(0.0 AS DECIMAL(18,6))DV_ANNLZD_MTHY_RCRR_RV_USD_AMT 
 ,CAST(0.0 AS DECIMAL(18,6))DV_INCRML_ANNL_RCRR_RV_USD_AMT
 ,WBECN.PURCHASE_ADJ_DISCOUNT_USD_AMT
 ,0 DV_BGM_NON_STANDARD_COST_AMT /*added as part product BGM - Q1FY18 release */
 ,WBECN.POB_TYPE_CD
 ,WBECN.NRS_TRANSITION_FLG
 ,WBECN.SALES_MOTION_CD /* Added as part of Oct - 2017 rel */
 ,COALESCE(WBECN.SUMMARY_QUOTE_FLG, 'N') SUMMARY_QUOTE_FLG,  /* Added as part of Oct - 2017 rel */
 /*REBATE BGM NET START */
CASE WHEN WBECN.SERVICE_FLG = 'Y' AND WBECN.DD_COMP_US_NET_PRICE_AMOUNT <> 0 
	THEN
		CASE WHEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL  
			THEN 	
				CAST( (WBECN.DD_COMP_US_NET_PRICE_AMOUNT - (COALESCE(TSS.REBATE_FACTOR_PCT,TSS1.REBATE_FACTOR_PCT) * WBECN.DD_COMP_US_NET_PRICE_AMOUNT /100)    
					)  AS DECIMAL(18,6) )   
			WHEN COALESCE(L4_TSD.REBATE_FACTOR_PCT,L3_TSD.REBATE_FACTOR_PCT,L2_TSD.REBATE_FACTOR_PCT,L1_TSD.REBATE_FACTOR_PCT,0) <> 0
			THEN
				CAST( (WBECN.DD_COMP_US_NET_PRICE_AMOUNT *
					(COALESCE(L4_TSD.REBATE_FACTOR_PCT,L3_TSD.REBATE_FACTOR_PCT,L2_TSD.REBATE_FACTOR_PCT,L1_TSD.REBATE_FACTOR_PCT)/100) )  AS DECIMAL(18,6) )		
			ELSE  WBECN.DD_COMP_US_NET_PRICE_AMOUNT
		END 
	ELSE  0
 END DV_BKG_REBATE,

CASE WHEN (WBECN.SERVICE_FLG = 'Y' AND DV_BKG_REBATE <> 0 AND 
COALESCE(COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY),L4_TSD.TSS_COUNTRY_FACTOR_KEY,L3_TSD.TSS_COUNTRY_FACTOR_KEY,L2_TSD.TSS_COUNTRY_FACTOR_KEY,L1_TSD.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL )
THEN COALESCE((COALESCE(MCR.ANNUAL_BUDGET_CONV_RT,0)/NULLIF(MCR.PL_CONVERSION_RT,0))*DV_BKG_REBATE,0) 
ELSE 0
END AS DV_FX_REBATE_PRICE_AMT,
/*REBATE BGM NET END */
-999 AS SK_SALES_MOTION_ATTRIB_KEY /* Added as part of SALES FY18 May12Rel */
,WBECN.DD_COMP_US_ORIG_LIST_PRICE
,WBECN.DD_COMP_US_ORIG_EXT_LIST_PRICE
,WBECN.DV_INV_DTM           
,WBECN.DV_COMPENSATION_DTM
,WBECN.RU_SERVICE_CONTRACT_START_DTM
,WBECN.RU_SERVICE_CONTRACT_END_DTM
,WBECN.DV_CONTRACT_DURATION
,WBECN.DV_ANNUALIZED_FLG
,WBECN.DV_ANNUALIZED_US_NET_AMT
,WBECN.DV_MULTIYEAR_US_NET_AMT
,WBECN.BOOKINGS_POLICY_CD
,WBECN.SOURCE_REP_ANNUAL_USD_AMT
  FROM 
     $$STGDB.WI_BOOKINGS_ERP_CURR_NBM WBECN
     LEFT OUTER JOIN $$SLSORDVWDB.N_BOOKINGS_MEASURE NBM
     ON WBECN.BOOKINGS_MEASURE_KEY=NBM.BOOKINGS_MEASURE_KEY
     AND NBM.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP' 
  AND NBM.BKGS_MEASURE_TRANS_TYPE_CODE = WBECN.BKGS_MEASURE_TRANS_TYPE_CODE 
   
    /*added for DEAL_ID*/  
   LEFT JOIN $$SLSORDVWDB.N_SALES_ORDER NSL
   ON WBECN.SALES_ORDER_KEY=NSL.SALES_ORDER_KEY 
   /*END-DEAL_ID*/  
   
   /*Below joins as part of BGM Q1FY17 Changes*/
   
 LEFT JOIN  $$COMREFVWDB.N_PRODUCT NP
 ON WBECN.PRODUCT_KEY=NP.ITEM_KEY
 
 LEFT JOIN $$COMREFVWDB.MT_ENDCUST_CUSTOMER_PARTY_HIER ENDCUST
 ON WBECN.END_CUSTOMER_KEY=ENDCUST.END_CUSTOMER_KEY
 
 LEFT JOIN $$COMREFVWDB.R_SALES_HIERARCHY HIER
 ON WBECN.SALES_TERRITORY_KEY=HIER.SALES_TERRITORY_KEY
 
 LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR TSS
 ON TSS.PRODUCT_KEY = WBECN.PRODUCT_KEY
 AND TSS.BK_ISO_COUNTRY_CD = ENDCUST.BRANCH_ISO_COUNTRY_CD                    
 AND TSS.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP'
 AND TSS.SALES_TERRITORY_NAME=HIER.L2_SALES_TERRITORY_NAME_CODE
 AND TSS.COUNTRY_FLG='Y'
 
  LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR TSS1
 ON TSS1.PRODUCT_KEY = WBECN.PRODUCT_KEY
 AND TSS1.BK_ISO_COUNTRY_CD = ENDCUST.BRANCH_ISO_COUNTRY_CD                    
 AND TSS1.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP'
 AND TSS1.SALES_TERRITORY_NAME=HIER.L1_SALES_TERRITORY_NAME_CODE
 AND TSS1.COUNTRY_FLG='Y'
 
 LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR  L4_TSD
 ON L4_TSD.SALES_TERRITORY_NAME=HIER.L4_SALES_TERRITORY_NAME_CODE
 AND L4_TSD.COUNTRY_FLG='N'
 
 LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR  L3_TSD
 ON L3_TSD.SALES_TERRITORY_NAME=HIER.L3_SALES_TERRITORY_NAME_CODE
 AND L3_TSD.COUNTRY_FLG='N'
 
 LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR  L2_TSD
 ON L2_TSD.SALES_TERRITORY_NAME=HIER.L2_SALES_TERRITORY_NAME_CODE
 AND L2_TSD.COUNTRY_FLG='N'
 LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR  L1_TSD
 ON L1_TSD.SALES_TERRITORY_NAME=HIER.L1_SALES_TERRITORY_NAME_CODE
 AND L1_TSD.COUNTRY_FLG='N'
 
  LEFT OUTER JOIN
 (
 SELECT CR.PL_CONVERSION_RT,CR.ANNUAL_BUDGET_CONV_RT,CR.FISCAL_YEAR_MONTH_NUM_INT,FX.SALES_TERRITORY_KEY
 FROM $$FINLGLVWDB.MT_MONTHLY_CONVERSION_RATE CR,
 $$SLSORDVWDB.MT_PROFITABILITY_FX_NORM FX,
 (SELECT (PDATE.FISCAL_YEAR_NUMBER_INT-5)*100+PDATE.FISCAL_MONTH_NUMBER_INT AS START_DATE,       
     CASE WHEN PDATE.FISCAL_MONTH_NUMBER_INT = 12 THEN (PDATE.FISCAL_YEAR_NUMBER_INT+1)*100+1 ELSE PDATE.FISCAL_YEAR_MTH_NUMBER_INT+1  END AS END_DATE
  FROM $$ETLVWDB.BKG_PROCESS_DT_CNTRL  PDATE
  )PDATE
 WHERE  CR.BK_FROM_CURRENCY_CD=FX.BK_CURRENCY_CD
 AND CR.FISCAL_YEAR_MONTH_NUM_INT   BETWEEN PDATE.START_DATE AND PDATE.END_DATE
 AND CR.BK_TO_CURRENCY_CD='USD'
 )MCR   
 ON WBECN.SALES_TERRITORY_KEY=MCR.SALES_TERRITORY_KEY
 AND  WBECN.DV_FISCAL_YEAR_MTH_NUMBER_INT=MCR.FISCAL_YEAR_MONTH_NUM_INT /*End of BGM Changes */
   ,(SELECT PROCESS_DATE FROM $$ETLVWDB.BKG_PROCESS_DT_CNTRL ) BKG_PRCDT
       
   ) INNER_QUERY
   INNER JOIN $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR CAL  /*added this join to derive new column quarter number*/
        ON INNER_QUERY.BOOKINGS_PROCESS_DATE=CAL.CALENDAR_DATE
   INNER JOIN $$COMREFVWDB.MT_ERP_POS_BILLTO MT_BILLTO 
      ON MT_BILLTO.BILL_TO_CUSTOMER_KEY = INNER_QUERY.BILL_TO_CUSTOMER_KEY
   LEFT JOIN $$SLSORDVWDB.N_CUST_ACCT_WITH_WIPS_DISTRI N_DISTI
      ON MT_BILLTO.ERP_CUSTOMER_ACCOUNT_KEY = N_DISTI.CUSTOMER_ACCT_KEY


Post SQL : 



Target1 Name : W_BOOKINGS_MEASURE1


Pre SQL : 
DELETE FROM $$WORKDB.W_BOOKINGS_MEASURE WHERE BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP';


Post SQL : 



Source2 Name : SQ_WI_BOOKINGS_ERP_EC_RETRO2


Pre SQL : 



SQL Query : 
SELECT
 WRET.BOOKINGS_MEASURE_KEY,
 WRET.SALES_ORDER_KEY,
 WRET.SALES_ORDER_LINE_KEY,
 WRET.PRODUCT_KEY,
 WRET.AR_TRX_LINE_KEY,
 WRET.AR_TRX_KEY,
 WRET.END_CUSTOMER_KEY,
 WRET.BILL_TO_CUSTOMER_KEY,
 WRET.SHIP_TO_CUSTOMER_KEY,
 WRET.SOLD_TO_CUSTOMER_KEY,
 WRET.DV_END_CUSTOMER_KEY,
 WRET.TRANSACTION_DATETIME,
 WRET.SALES_TERRITORY_KEY,
 WRET.SALES_REP_NUMBER,
 WRET.BOOKINGS_PROCESS_DATE,
 WRET.DV_FISCAL_YEAR_MTH_NUMBER_INT,
 WRET.BK_POS_TRANSACTION_ID_INT,
 WRET.BK_SALES_ADJ_LINE_NUMBER_INT,
 WRET.BK_SALES_ADJ_NUMBER_INT,
 WRET.ADJUSTMENT_TYPE_CODE,
 WRET.SALES_CHANNEL_CODE,
 WRET.SALES_CREDIT_TYPE_CODE,
 WRET.IDE_ADJUSTMENT_CODE,
 WRET.ADJUSTMENT_CODE,
 WRET.BKGS_MEASURE_TRANS_TYPE_CODE,
 WRET.CANCELLED_FLG,
 WRET.CANCEL_CODE,
 WRET.ACQUISITION_FLG,
 WRET.FORWARD_REVERSE_FLG,
 WRET.DISTRIBUTOR_OFFSET_FLG,
 WRET.CORPORATE_BOOKINGS_FLG,
 WRET.OVERLAY_FLG,
 WRET.IC_REVENUE_FLG,
 WRET.CHARGES_FLG,
 WRET.SALESREP_FLG,
 WRET.MISC_FLG,
 WRET.SERVICE_FLG,
 WRET.INTERNATIONAL_DEMO_FLG,
 WRET.REPLACEMENT_DEMO_FLG,
 WRET.REVENUE_FLG,
 WRET.RMA_FLG,
 WRET.TRADE_IN_AMOUNT,
 WRET.DD_COMP_US_NET_PRICE_AMOUNT,
 WRET.DD_COMP_US_LIST_PRICE_AMOUNT,
 WRET.DD_COMP_US_COST_AMOUNT,
 WRET.DD_EXTENDED_QUANTITY,
 WRET.DD_COMP_US_HOLD_NET_PRICE_AMT,
 WRET.DD_COMP_US_HOLD_LIST_PRICE_AMT,
 WRET.DD_COMP_US_HOLD_COST_AMOUNT,
 WRET.DD_EXTENDED_HOLD_QUANTITY,
 WRET.DD_COMP_US_STANDARD_PRICE_AMT,
CASE WHEN NSL.BK_WIPS_ORIGINATOR_ID_INT > 0 THEN NSL.BK_WIPS_ORIGINATOR_ID_INT
 WHEN TRIM(WRET.SALES_CHANNEL_CODE) IN ('DVAD' , 'Two Tier Distributor') THEN Coalesce(N_DISTI.BK_WIPS_ORIGINATOR_ID_INT,-999 )
 ELSE WRET.WIPS_ORIGINATOR_ID_INT END AS WIPS_ORIGINATOR_ID_INT , /* Modified as part of SFP Rel */
WRET.EDW_CREATE_USER,
 WRET.EDW_UPDATE_USER,
 WRET.EDW_CREATE_DATETIME,
 WRET.EDW_UPDATE_DATETIME,
 WRET.CONVERSION_RT, 
 WRET.CONVERSION_DT, 
 WRET.DD_BK_SO_NUMBER_INT,
 WRET.DD_CISCO_BOOKED_DTM,
 WRET.DD_SALES_ORDER_CATEGORY_TYPE, 
 WRET.DD_SLS_ORD_OPERATING_UNIT_CD, 
 WRET.DD_TRX_CURRENCY_CD, 
 NULL AS DV_TRANSACTION_TYPE,
 NULL AS ADJUSTMENT_DESCRIPTION_KEY, 
 '=' AS    ACTION_CODE,
 '=' AS    DML_TYPE,
 NULL AS DV_TRANSACTION_NAME,
 WRET.BOOKINGS_SPLIT_PCT AS BOOKINGS_SPLIT_PCT,
 WRET.DV_REVENUE_RECOGNITION_FLG,    /**Added as part of true demand bkgs definition*/   
 WRET.DV_NET_SPREAD_FLG ,            /**Added as part of true demand bkgs definition*/ 
 WRET.DV_ATTRIBUTION_CD,            /**Added as part of Offer Attribution Project**/
 WRET.DV_PRODUCT_KEY ,     /**Added as part of Offer Attribution Project**/
 WRET.DV_SALES_ORDER_LINE_KEY,         /**Added as part of Offer Attribution Project**/ 
 WRET.SK_OFFER_ATTRIBUTION_ID_INT,   /**Added as part of Offer Attribution Project**/
 WRET.RU_SERVICE_CONTRACT_START_DTM, /*Added as part of Q1FY16 AUG CD ICPM*/
 WRET.RU_SERVICE_CONTRACT_END_DTM , /*Added as part of Q1FY16 AUG CD ICPM*/
 WRET.DV_CONTRACT_DURATION , /*Added as part of Q1FY16 AUG CD ICPM*/
 WRET.DV_ANNUALIZED_FLG , /*Added as part of Q1FY16 AUG CD ICPM*/
 WRET.DV_ANNUALIZED_US_NET_AMT, /*Added as part of Q1FY16 AUG CD ICPM*/
 WRET.DV_MULTIYEAR_US_NET_AMT /*Added as part of Q1FY16 AUG CD ICPM*/
 ,CAL.FISCAL_YEAR_QUARTER_NUMBER_INT
 ,WRET.DV_AR_TRX_LINE_KEY /*Added as part of Q3FY16-Offer Attribution*/
 ,WRET.XAAS_OFFER_ATRBTN_REV_LINE_KEY /*Added as part of Q3FY16-Offer Attribution*/
 ,WRET.BK_DEAL_ID AS  DV_DEAL_ID 
 
 /*  Q1FY17 BGM changes starts here */
 ,CASE WHEN CURR_FISCAL_QTR. FISCAL_YEAR_MONTH_INT IS NOT NULL THEN
 CASE WHEN WRET.SERVICE_FLG = 'Y'  AND WRET.DD_COMP_US_NET_PRICE_AMOUNT <> 0 
   THEN
      CASE WHEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL  THEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY)
         WHEN COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT) IS NOT NULL THEN
          COALESCE(L4_TSD.TSS_COUNTRY_FACTOR_KEY,L3_TSD.TSS_COUNTRY_FACTOR_KEY,L2_TSD.TSS_COUNTRY_FACTOR_KEY,L1_TSD.TSS_COUNTRY_FACTOR_KEY,-999) 
         ELSE -999 
      END 
 ELSE -999 END ELSE WRET.TSS_COUNTRY_FACTOR_KEY END TSS_COUNTRY_FACTOR_KEY,
 
 CASE WHEN CURR_FISCAL_QTR. FISCAL_YEAR_MONTH_INT IS NOT NULL THEN
 CASE WHEN WRET.SERVICE_FLG = 'Y'  AND WRET.DD_COMP_US_NET_PRICE_AMOUNT <> 0 
   THEN
   CASE WHEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL  
       THEN  
     CAST( (WRET.DD_COMP_US_NET_PRICE_AMOUNT - (COALESCE(TSS.COST_FACTOR_PCT,TSS1.COST_FACTOR_PCT)*
       (CASE WHEN DOLLAR_ADJUSTABLE_FLG='Y' THEN WRET.DD_COMP_US_STANDARD_PRICE_AMT ELSE WRET.DD_COMP_US_LIST_PRICE_AMOUNT END)/100)    
      )  AS DECIMAL(18,6) )   
    WHEN COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT) IS NOT NULL 
    THEN
     CAST( (WRET.DD_COMP_US_NET_PRICE_AMOUNT *
      (COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT)/100) )  AS DECIMAL(18,6) )  
    ELSE 0
   END 
  ELSE 0 END ELSE WRET. DV_BKG_GROSS_MGN_AMOUNT 
  END DV_BKG_GROSS_MGN_AMOUNT,
  
  CASE WHEN CURR_FISCAL_QTR. FISCAL_YEAR_MONTH_INT IS NOT NULL THEN
 CASE WHEN WRET.SERVICE_FLG = 'Y'   AND WRET.DD_COMP_US_NET_PRICE_AMOUNT <> 0 AND MCR.SALES_TERRITORY_KEY IS NOT NULL 
   THEN
    CASE WHEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL  
     THEN  
      CAST( ( (COALESCE(TSS.COST_FACTOR_PCT,TSS1.COST_FACTOR_PCT)*
       (CASE WHEN DOLLAR_ADJUSTABLE_FLG='Y' THEN WRET.DD_COMP_US_STANDARD_PRICE_AMT ELSE WRET.DD_COMP_US_LIST_PRICE_AMOUNT END)/100)    
       )  AS DECIMAL(18,6) )   
     WHEN COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT) IS NOT NULL 
     THEN
      CAST(COALESCE((COALESCE(MCR.ANNUAL_BUDGET_CONV_RT,0)/NULLIF(MCR.PL_CONVERSION_RT,0))*WRET.DD_COMP_US_NET_PRICE_AMOUNT,0) * 
       (COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT))/100 AS DECIMAL(18,6) )  
     ELSE 0
    END 
   ELSE 0
   END
 ELSE WRET. DV_BGM_FX_COST_AMOUNT
  END DV_BGM_FX_COST_AMOUNT,
  
 CASE WHEN CURR_FISCAL_QTR. FISCAL_YEAR_MONTH_INT IS NOT NULL THEN
 CASE WHEN (WRET.SERVICE_FLG = 'Y' AND WRET.DD_COMP_US_NET_PRICE_AMOUNT <> 0 AND 
 COALESCE(COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY),L4_TSD.TSS_COUNTRY_FACTOR_KEY,L3_TSD.TSS_COUNTRY_FACTOR_KEY,L2_TSD.TSS_COUNTRY_FACTOR_KEY,L1_TSD.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL )
 THEN COALESCE((COALESCE(MCR.ANNUAL_BUDGET_CONV_RT,0)/NULLIF(MCR.PL_CONVERSION_RT,0))*WRET.DD_COMP_US_NET_PRICE_AMOUNT,0) 
 ELSE 0
 END 
 ELSE WRET.DV_FX_NET_PRICE_AMT END 
 AS DV_FX_NET_PRICE_AMT
 
 /*  Q1FY17 BGM changes ends here */
 
,WRET.DV_LOCAL_EXTND_LIST_PRICE_AMT 
,WRET.LOCAL_UNIT_LIST_PRICE_AMT     
,WRET.DV_UNIT_LIST_PRICE_USD_AMT 
,CAST(0.0 AS DECIMAL(18,6))DV_ORDER_VALUE_USD_AMOUNT    
,CAST(0.0 AS DECIMAL(18,6))DV_MTHLY_RCR_REV_TRXL_USD_AMT  
,CAST(0.0 AS DECIMAL(18,6))DV_INCRML_MTHY_RCRR_RV_USD_AMT 
,CAST(0.0 AS DECIMAL(18,6))DV_ANNLZD_MTHY_RCRR_RV_USD_AMT 
,CAST(0.0 AS DECIMAL(18,6))DV_INCRML_ANNL_RCRR_RV_USD_AMT	 
,0 AS DV_BGM_NON_STANDARD_COST_AMT /*added as part product BGM - Q1FY18 release */
,WRET.POB_TYPE_CD /* Added as part of NRS MPOB Changes */
,WRET.NRS_TRANSITION_FLG
,WRET.SALES_MOTION_CD /* Added as part of Oct - 2017 rel */
,WRET.SUMMARY_QUOTE_FLG, /* Added as part of Oct - 2017 rel */

   
/*REBATE BGM NET START */
CASE WHEN CURR_FISCAL_QTR. FISCAL_YEAR_MONTH_INT IS NOT NULL THEN
CASE WHEN SERVICE_FLG = 'Y' AND WRET.DD_COMP_US_NET_PRICE_AMOUNT <> 0 
	THEN
		CASE WHEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL  
			THEN 	
				CAST( (WRET.DD_COMP_US_NET_PRICE_AMOUNT - (COALESCE(TSS.REBATE_FACTOR_PCT,TSS1.REBATE_FACTOR_PCT)  * WRET.DD_COMP_US_NET_PRICE_AMOUNT /100)    
					)  AS DECIMAL(18,6) )   
			WHEN COALESCE(L4_TSD.REBATE_FACTOR_PCT,L3_TSD.REBATE_FACTOR_PCT,L2_TSD.REBATE_FACTOR_PCT,L1_TSD.REBATE_FACTOR_PCT,0) <> 0
			THEN
				CAST( (WRET.DD_COMP_US_NET_PRICE_AMOUNT *
					(COALESCE(L4_TSD.REBATE_FACTOR_PCT,L3_TSD.REBATE_FACTOR_PCT,L2_TSD.REBATE_FACTOR_PCT,L1_TSD.REBATE_FACTOR_PCT)/100) )  AS DECIMAL(18,6) )		
			ELSE  DD_COMP_US_NET_PRICE_AMOUNT
		END 
	ELSE  0 END ELSE WRET.DV_BKG_GROSS_MGN_AMOUNT
 END DV_BKG_REBATE,

CASE WHEN CURR_FISCAL_QTR. FISCAL_YEAR_MONTH_INT IS NOT NULL THEN
CASE WHEN (WRET.SERVICE_FLG = 'Y' AND DV_BKG_REBATE <> 0 AND 
COALESCE(COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY),L4_TSD.TSS_COUNTRY_FACTOR_KEY,L3_TSD.TSS_COUNTRY_FACTOR_KEY,L2_TSD.TSS_COUNTRY_FACTOR_KEY,L1_TSD.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL )
THEN COALESCE((COALESCE(MCR.ANNUAL_BUDGET_CONV_RT,0)/NULLIF(MCR.PL_CONVERSION_RT,0))*DV_BKG_REBATE,0) 
ELSE 0
END 
ELSE DV_FX_REBATE_PRICE_AMT
END AS DV_FX_REBATE_PRICE_AMT,
/*REBATE BGM NET END */
WRET.SK_SALES_MOTION_ATTRIB_KEY, /* Added as part of SALES FY18 May12Rel */
WRET.DD_COMP_US_ORIG_LIST_PRICE,
WRET.DD_COMP_US_ORIG_EXT_LIST_PRICE,
WRET.DV_INV_DTM     ,      
WRET.DV_COMPENSATION_DTM  ,
WRET.BOOKINGS_POLICY_CD,
WRET.SOURCE_REP_ANNUAL_USD_AMT
FROM 
 $$STGDB.WI_BOOKINGS_ERP_EC_RETRO WRET
 
 INNER JOIN $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR CAL   /*added this join to derive new column quarter number*/
 ON WRET.BOOKINGS_PROCESS_DATE=CAL.CALENDAR_DATE
 
 /*added for DEAL_ID*/ 
 LEFT JOIN $$SLSORDVWDB.N_SALES_ORDER NSL
 ON WRET.SALES_ORDER_KEY=NSL.SALES_ORDER_KEY 
 /*END-DEAL_ID*/  
 /*  Q1FY17 BGM changes starts here */
 
 LEFT JOIN  $$COMREFVWDB.N_PRODUCT NP
 ON WRET.PRODUCT_KEY=NP.ITEM_KEY  
 
 LEFT JOIN $$COMREFVWDB.MT_ENDCUST_CUSTOMER_PARTY_HIER ENDCUST
 ON WRET.END_CUSTOMER_KEY=ENDCUST.END_CUSTOMER_KEY     
 
 LEFT JOIN $$COMREFVWDB.R_SALES_HIERARCHY HIER
 ON WRET.SALES_TERRITORY_KEY=HIER.SALES_TERRITORY_KEY
 
  LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR TSS
 ON TSS.PRODUCT_KEY                    = WRET.PRODUCT_KEY
 AND TSS.BK_ISO_COUNTRY_CD = ENDCUST.BRANCH_ISO_COUNTRY_CD                    
 AND TSS.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP'
 AND TSS.SALES_TERRITORY_NAME=HIER.L2_SALES_TERRITORY_NAME_CODE
 AND TSS.COUNTRY_FLG='Y'
 
 LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR TSS1
 ON TSS1.PRODUCT_KEY                    = WRET.PRODUCT_KEY
 AND TSS1.BK_ISO_COUNTRY_CD = ENDCUST.BRANCH_ISO_COUNTRY_CD                    
 AND TSS1.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP'
 AND TSS1.SALES_TERRITORY_NAME=HIER.L1_SALES_TERRITORY_NAME_CODE
 AND TSS1.COUNTRY_FLG='Y'
 
 LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR  L4_TSD
 ON L4_TSD.SALES_TERRITORY_NAME=HIER.L4_SALES_TERRITORY_NAME_CODE
 AND L4_TSD.COUNTRY_FLG='N'
 
 LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR  L3_TSD
 ON L3_TSD.SALES_TERRITORY_NAME=HIER.L3_SALES_TERRITORY_NAME_CODE
 AND L3_TSD.COUNTRY_FLG='N'
 
 
 LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR  L2_TSD
 ON L2_TSD.SALES_TERRITORY_NAME=HIER.L2_SALES_TERRITORY_NAME_CODE
 AND L2_TSD.COUNTRY_FLG='N'
 
 LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR  L1_TSD
 ON L1_TSD.SALES_TERRITORY_NAME=HIER.L1_SALES_TERRITORY_NAME_CODE
 AND L1_TSD.COUNTRY_FLG='N'
 
 LEFT OUTER JOIN
 (
 SELECT CR.PL_CONVERSION_RT,CR.ANNUAL_BUDGET_CONV_RT,CR.FISCAL_YEAR_MONTH_NUM_INT,FX.SALES_TERRITORY_KEY
 FROM $$FINLGLVWDB.MT_MONTHLY_CONVERSION_RATE CR,
 $$SLSORDVWDB.MT_PROFITABILITY_FX_NORM FX,
 (SELECT (PDATE.FISCAL_YEAR_NUMBER_INT-5)*100+PDATE.FISCAL_MONTH_NUMBER_INT AS START_DATE,       
 CASE WHEN PDATE.FISCAL_MONTH_NUMBER_INT = 12 THEN (PDATE.FISCAL_YEAR_NUMBER_INT+1)*100+1 ELSE PDATE.FISCAL_YEAR_MTH_NUMBER_INT+1  END AS END_DATE
 FROM $$ETLVWDB.BKG_PROCESS_DT_CNTRL PDATE
 )PDATE
 WHERE  CR.BK_FROM_CURRENCY_CD=FX.BK_CURRENCY_CD
 AND CR.FISCAL_YEAR_MONTH_NUM_INT   BETWEEN PDATE.START_DATE AND PDATE.END_DATE
 AND CR.BK_TO_CURRENCY_CD='USD'
 )MCR   
 ON WRET.SALES_TERRITORY_KEY=MCR.SALES_TERRITORY_KEY
 AND  WRET.DV_FISCAL_YEAR_MTH_NUMBER_INT=MCR.FISCAL_YEAR_MONTH_NUM_INT 
 
 LEFT OUTER JOIN 
 (SELECT FISCAL_YEAR_MONTH_INT FROM $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR WHERE   CURRENT_FISCAL_QTR_FLAG        = 'Y' 
 UNION  
 SELECT FISCAL_YEAR_MONTH_INT FROM $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR WHERE  PREVIOUS_FISCAL_QTR_FLAG   = 'Y' 
 AND  1 =(  SELECT COUNT(*)   FROM $$COMREFVWDB.R_FISCAL_QUARTER_TO_YEAR  WHERE DATE= FISCAL_QUARTER_START_DATE  AND CURRENT_FISCAL_QTR_FLAG ='Y')) CURR_FISCAL_QTR
 ON WRET.DV_FISCAL_YEAR_MTH_NUMBER_INT=CURR_FISCAL_QTR. FISCAL_YEAR_MONTH_INT
 
INNER JOIN $$COMREFVWDB.MT_ERP_POS_BILLTO MT_BILLTO 
     ON MT_BILLTO.BILL_TO_CUSTOMER_KEY = WRET.BILL_TO_CUSTOMER_KEY
  LEFT JOIN $$SLSORDVWDB.N_CUST_ACCT_WITH_WIPS_DISTRI N_DISTI
     ON MT_BILLTO.ERP_CUSTOMER_ACCOUNT_KEY = N_DISTI.CUSTOMER_ACCT_KEY 


 /*  Q1FY17 BGM changes ends here */
 WHERE NOT EXISTS (SELECT 1 
 FROM $$WORKDB.W_BOOKINGS_MEASURE WBM
 WHERE WBM.BOOKINGS_MEASURE_KEY = WRET.BOOKINGS_MEASURE_KEY AND 
 WBM.BOOKINGS_PROCESS_DATE= WRET.BOOKINGS_PROCESS_DATE AND
 WBM.BKGS_MEASURE_TRANS_TYPE_CODE =WRET.BKGS_MEASURE_TRANS_TYPE_CODE)


Post SQL : 



Target2 Name : W_BOOKINGS_MEASURE2


Pre SQL : 



Post SQL : 
/*COMMENTED AS PART OF BGM Oct Monthly Release



DELETE FROM $$STGDB.WI_N_BOOKINGS_MEASURE_BGM WHERE BKGS_MEASURE_TRANS_TYPE_CODE  = 'ERP' ;

INSERT INTO $$STGDB.WI_N_BOOKINGS_MEASURE_BGM
SELECT 
 NRT.BOOKINGS_MEASURE_KEY ,     
 NRT.BKGS_MEASURE_TRANS_TYPE_CODE ,
 NRT.BOOKINGS_PROCESS_DATE ,
 NRT.DV_FISCAL_YEAR_MTH_NUMBER_INT ,

CASE WHEN NBF.COST_FACTOR_PCT IS NULL 
THEN 0
ELSE CAST( (NRT.DD_COMP_US_NET_PRICE_AMOUNT * (NBF.COST_FACTOR_PCT/100.0000) )  AS DECIMAL(18,6) )                                    
END  BGM_NON_STANDARD_COST_AMT ,

CASE WHEN NBF.COST_FACTOR_PCT IS NULL 
THEN 0
ELSE (DD_COMP_US_NET_PRICE_AMOUNT - DD_COMP_US_COST_AMOUNT) - BGM_NON_STANDARD_COST_AMT
END DV_BKG_GROSS_MGN_AMOUNT,


COALESCE((COALESCE(MCR.ANNUAL_BUDGET_CONV_RT,0)/NULLIF(MCR.PL_CONVERSION_RT,0))*NRT.DD_COMP_US_NET_PRICE_AMOUNT,0) AS FX_NET_PRICE_AMT,

CAST( (DD_COMP_US_COST_AMOUNT - (FX_NET_PRICE_AMT*(COALESCE(NBF.COST_FACTOR_PCT,0))/100.0000 ) )AS DECIMAL(18,6)) DV_BGM_FX_COST_AMOUNT 
  
FROM $$SLSORDVWDB.N_BOOKINGS_MEASURE  NRT


INNER JOIN (SELECT FISCAL_YEAR_MONTH_INT,FISCAL_YEAR_NUMBER_INT FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR WHERE CURRENT_FISCAL_MONTH_FLAG = 'Y') RFM
ON RFM.FISCAL_YEAR_MONTH_INT = NRT.DV_FISCAL_YEAR_MTH_NUMBER_INT

INNER JOIN  $$COMREFVWDB.R_PRODUCTS NP
ON NRT.PRODUCT_KEY=NP.ITEM_KEY

LEFT JOIN $$SLSORDVWDB.N_BOOKINGS_COST_FACTOR NBF
ON NBF.BK_PRODUCT_FAMILY_ID = NP.RU_BK_PRODUCT_FAMILY_ID
AND NBF.SALES_TERRITORY_KEY = NRT.SALES_TERRITORY_KEY
AND NBF.BK_FISCAL_YEAR_NUM_INT = NRT.DV_FISCAL_YEAR_MTH_NUMBER_INT/100


LEFT OUTER JOIN
(
SELECT CR.PL_CONVERSION_RT,CR.ANNUAL_BUDGET_CONV_RT,CR.FISCAL_YEAR_MONTH_NUM_INT,FX.SALES_TERRITORY_KEY
FROM $$FINLGLVWDB.MT_MONTHLY_CONVERSION_RATE CR,
$$SLSORDVWDB.MT_PROFITABILITY_FX_NORM FX,
(SELECT (PDATE.FISCAL_YEAR_NUMBER_INT-5)*100+PDATE.FISCAL_MONTH_NUMBER_INT AS START_DATE,       
    PDATE.FISCAL_YEAR_MTH_NUMBER_INT+1 AS END_DATE
                    FROM $$ETLVWDB.MBR_PROCESS_DATE PDATE
                    )PDATE
WHERE  CR.BK_FROM_CURRENCY_CD=FX.BK_CURRENCY_CD
AND CR.BK_TO_CURRENCY_CD='USD' 
AND CR.FISCAL_YEAR_MONTH_NUM_INT   BETWEEN PDATE.START_DATE AND PDATE.END_DATE
)MCR   
ON NRT.SALES_TERRITORY_KEY=MCR.SALES_TERRITORY_KEY
AND  NRT.DV_FISCAL_YEAR_MTH_NUMBER_INT=MCR.FISCAL_YEAR_MONTH_NUM_INT  

WHERE NRT.BKGS_MEASURE_TRANS_TYPE_CODE  = 'ERP'  
AND NRT.SERVICE_FLG = 'N' AND DD_COMP_US_NET_PRICE_AMOUNT <> 0 ;



UPDATE NBM FROM
$$WORKDB.W_BOOKINGS_MEASURE NBM ,$$STGDB.WI_N_BOOKINGS_MEASURE_BGM BGM
SET 
  DV_BKG_GROSS_MGN_AMOUNT		= BGM.DV_BKG_GROSS_MGN_AMOUNT
, DV_BGM_FX_COST_AMOUNT	=BGM.DV_BGM_FX_COST_AMOUNT
, DV_BGM_NON_STANDARD_COST_AMT =BGM.DV_BGM_NON_STANDARD_COST_AMT
, DV_FX_NET_PRICE_AMT =BGM.DV_FX_NET_PRICE_AMT
WHERE NBM.BOOKINGS_MEASURE_KEY          =BGM.BOOKINGS_MEASURE_KEY  
AND NBM.BOOKINGS_PROCESS_DATE=BGM.BOOKINGS_PROCESS_DATE        
AND NBM.BKGS_MEASURE_TRANS_TYPE_CODE=BGM.BKGS_MEASURE_TRANS_TYPE_CODE
AND NBM.DV_FISCAL_YEAR_MTH_NUMBER_INT = BGM.DV_FISCAL_YEAR_MTH_NUMBER_INT
 AND NBM.BKGS_MEASURE_TRANS_TYPE_CODE  = 'ERP'
 AND NBM.DV_FISCAL_YEAR_MTH_NUMBER_INT = (SELECT FISCAL_YEAR_MONTH_INT FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR WHERE CURRENT_FISCAL_MONTH_FLAG = 'Y') 
 ;
*/

CREATE VOLATILE TABLE W_BOOKINGS_MEASURE_TSS_BGM AS
(
SELECT
BOOKINGS_MEASURE_KEY,
BKGS_MEASURE_TRANS_TYPE_CODE,
BOOKINGS_PROCESS_DATE,
SALES_TERRITORY_KEY,
SALES_REP_NUMBER,
BGM_PERC
FROM
(
SELECT 
BOOKINGS_MEASURE_KEY,
BKGS_MEASURE_TRANS_TYPE_CODE,
BOOKINGS_PROCESS_DATE,
SALES_TERRITORY_KEY,
SALES_REP_NUMBER,
COALESCE(SUM(DV_BKG_GROSS_MGN_AMOUNT*100)/ NULLIFZERO (SUM(DV_BKG_REBATE_AMT)) ,0)AS BGM_PERC
FROM $$WORKDB.W_BOOKINGS_MEASURE
WHERE BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP'
AND SERVICE_FLG='Y'
GROUP BY 1,2,3,4,5
)BGM
WHERE (BGM_PERC >98 OR BGM_PERC <=0)
)
WITH DATA PRIMARY INDEX(BOOKINGS_MEASURE_KEY,BKGS_MEASURE_TRANS_TYPE_CODE,BOOKINGS_PROCESS_DATE,SALES_TERRITORY_KEY,SALES_REP_NUMBER) ON COMMIT PRESERVE ROWS;


UPDATE NBM FROM $$WORKDB.W_BOOKINGS_MEASURE NBM,
( SEL MIN(FISCAL_YEAR_MONTH_INT) START_MONTH,MAX(FISCAL_YEAR_MONTH_INT) END_MONTH
FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR WHERE FISCAL_YEAR_AGE BETWEEN 0 AND 3 AND FISCAL_MONTH_AGE>=0 )RFM
SET TSS_COUNTRY_FACTOR_KEY = -888,
DV_BKG_GROSS_MGN_AMOUNT = 0,
DV_BGM_FX_COST_AMOUNT = 0,
DV_FX_NET_PRICE_AMT=0,
DV_BKG_REBATE_AMT=0,
DV_FX_REBATE_PRICE_AMT=0
WHERE
NBM.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP'
AND NBM.SERVICE_FLG = 'Y' AND NBM.DD_COMP_US_NET_PRICE_AMOUNT <> 0
AND NBM.DV_FISCAL_YEAR_MTH_NUMBER_INT BETWEEN RFM.START_MONTH AND RFM.END_MONTH
AND (NBM.BOOKINGS_MEASURE_KEY,
NBM.BKGS_MEASURE_TRANS_TYPE_CODE,
NBM.BOOKINGS_PROCESS_DATE,
NBM.SALES_TERRITORY_KEY,
NBM.SALES_REP_NUMBER
) IN (SELECT BOOKINGS_MEASURE_KEY,
BKGS_MEASURE_TRANS_TYPE_CODE,
BOOKINGS_PROCESS_DATE,
SALES_TERRITORY_KEY,
SALES_REP_NUMBER
FROM W_BOOKINGS_MEASURE_TSS_BGM
);

UPDATE NBM FROM $$WORKDB.W_BOOKINGS_MEASURE NBM,
(SEL 
 NRT.BOOKINGS_MEASURE_KEY ,     
 NRT.BKGS_MEASURE_TRANS_TYPE_CODE,
 NRT.BOOKINGS_PROCESS_DATE,
  

CASE WHEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL  THEN 	
				COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY)
			WHEN COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT) IS NOT NULL THEN
				COALESCE(L4_TSD.TSS_COUNTRY_FACTOR_KEY,L3_TSD.TSS_COUNTRY_FACTOR_KEY,L2_TSD.TSS_COUNTRY_FACTOR_KEY,L1_TSD.TSS_COUNTRY_FACTOR_KEY,-999) 
ELSE -999 END TSS_COUNTRY_FACTOR_KEY,

CASE WHEN SERVICE_FLG = 'Y'  AND DD_COMP_US_NET_PRICE_AMOUNT <> 0 
                     THEN
                                        CASE WHEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL  
                                            THEN   
                                                                                CAST( (NRT.DD_COMP_US_NET_PRICE_AMOUNT - (COALESCE(TSS.COST_FACTOR_PCT,TSS1.COST_FACTOR_PCT)*
                                                                                                                        (CASE WHEN DOLLAR_ADJUSTABLE_FLG='Y' THEN NRT.DD_COMP_US_STANDARD_PRICE_AMT ELSE NRT.DD_COMP_US_LIST_PRICE_AMOUNT END)/100)    
                                                                                                    )  AS DECIMAL(18,6) )   
                                                            WHEN COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT) IS NOT NULL 
                                                            THEN
                                                                                CAST( (NRT.DD_COMP_US_NET_PRICE_AMOUNT *
                                                                                                    (COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT)/100) )  AS DECIMAL(18,6) )                                    
                                                            ELSE 0
                                        END 
                    ELSE 0
END DV_BKG_GROSS_MGN_AMOUNT,

 
CASE WHEN NRT.SERVICE_FLG = 'Y'   AND NRT.DD_COMP_US_NET_PRICE_AMOUNT <> 0 AND MCR.SALES_TERRITORY_KEY IS NOT NULL 
  THEN
   CASE WHEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL  
    THEN  
     CAST( ( (COALESCE(TSS.COST_FACTOR_PCT,TSS1.COST_FACTOR_PCT)*
      (CASE WHEN DOLLAR_ADJUSTABLE_FLG='Y' THEN NRT.DD_COMP_US_STANDARD_PRICE_AMT ELSE NRT.DD_COMP_US_LIST_PRICE_AMOUNT END)/100)    
      )  AS DECIMAL(18,6) )   
    WHEN COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT) IS NOT NULL 
    THEN
     CAST(COALESCE((COALESCE(MCR.ANNUAL_BUDGET_CONV_RT,0)/NULLIF(MCR.PL_CONVERSION_RT,0))*NRT.DD_COMP_US_NET_PRICE_AMOUNT,0) * 
      (COALESCE(L4_TSD.COST_FACTOR_PCT,L3_TSD.COST_FACTOR_PCT,L2_TSD.COST_FACTOR_PCT,L1_TSD.COST_FACTOR_PCT))/100 AS DECIMAL(18,6) )  
    ELSE 0
   END 
  ELSE 0
  END DV_BGM_FX_COST_AMOUNT ,


CASE WHEN (NRT.SERVICE_FLG = 'Y' AND NRT.DD_COMP_US_NET_PRICE_AMOUNT <> 0 AND 
COALESCE(COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY),L4_TSD.TSS_COUNTRY_FACTOR_KEY,L3_TSD.TSS_COUNTRY_FACTOR_KEY,L2_TSD.TSS_COUNTRY_FACTOR_KEY,L1_TSD.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL )
THEN COALESCE((COALESCE(MCR.ANNUAL_BUDGET_CONV_RT,0)/NULLIF(MCR.PL_CONVERSION_RT,0))*NRT.DD_COMP_US_NET_PRICE_AMOUNT,0) 
ELSE 0
END AS DV_FX_NET_PRICE_AMT,

/* REBATE BGM NET START */
CASE WHEN SERVICE_FLG = 'Y' AND DD_COMP_US_NET_PRICE_AMOUNT <> 0 
	THEN
		CASE WHEN COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL  
			THEN 	
				CAST( (NRT.DD_COMP_US_NET_PRICE_AMOUNT - (COALESCE(TSS.REBATE_FACTOR_PCT,TSS1.REBATE_FACTOR_PCT) * NRT.DD_COMP_US_NET_PRICE_AMOUNT /100)    
					)  AS DECIMAL(18,6) )   
			WHEN COALESCE(L4_TSD.REBATE_FACTOR_PCT,L3_TSD.REBATE_FACTOR_PCT,L2_TSD.REBATE_FACTOR_PCT,L1_TSD.REBATE_FACTOR_PCT,0) <> 0
			THEN
				CAST( (NRT.DD_COMP_US_NET_PRICE_AMOUNT *
					(COALESCE(L4_TSD.REBATE_FACTOR_PCT,L3_TSD.REBATE_FACTOR_PCT,L2_TSD.REBATE_FACTOR_PCT,L1_TSD.REBATE_FACTOR_PCT)/100) )  AS DECIMAL(18,6) )		
			ELSE  DD_COMP_US_NET_PRICE_AMOUNT
		END 
	ELSE  0
END DV_BKG_REBATE,

CASE WHEN (NRT.SERVICE_FLG = 'Y' AND DV_BKG_REBATE <> 0 AND 
COALESCE(COALESCE(TSS.TSS_COUNTRY_FACTOR_KEY, TSS1.TSS_COUNTRY_FACTOR_KEY),L4_TSD.TSS_COUNTRY_FACTOR_KEY,L3_TSD.TSS_COUNTRY_FACTOR_KEY,L2_TSD.TSS_COUNTRY_FACTOR_KEY,L1_TSD.TSS_COUNTRY_FACTOR_KEY) IS NOT NULL )
THEN COALESCE((COALESCE(MCR.ANNUAL_BUDGET_CONV_RT,0)/NULLIF(MCR.PL_CONVERSION_RT,0))*DV_BKG_REBATE,0) 
ELSE 0
END AS DV_FX_REBATE_PRICE_AMT
/* REBATE BGM NET END */

FROM $$WORKDB.W_BOOKINGS_MEASURE  NRT

INNER JOIN $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR RFM ON 1=1 
AND RFM.FISCAL_YEAR_AGE =3 
AND NRT.DV_FISCAL_YEAR_MTH_NUMBER_INT=RFM.FISCAL_YEAR_MONTH_INT
AND NRT.TSS_COUNTRY_FACTOR_KEY= -888 

LEFT JOIN  $$COMREFVWDB.N_PRODUCT NP
ON NRT.PRODUCT_KEY=NP.ITEM_KEY

LEFT JOIN $$COMREFVWDB.MT_ENDCUST_CUSTOMER_PARTY_HIER ENDCUST
ON NRT.END_CUSTOMER_KEY=ENDCUST.END_CUSTOMER_KEY

LEFT JOIN $$COMREFVWDB.R_SALES_HIERARCHY HIER
ON NRT.SALES_TERRITORY_KEY=HIER.SALES_TERRITORY_KEY

LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR TSS
ON TSS.PRODUCT_KEY                    = NRT.PRODUCT_KEY
AND TSS.BK_ISO_COUNTRY_CD = ENDCUST.BRANCH_ISO_COUNTRY_CD                    
AND TSS.BKGS_MEASURE_TRANS_TYPE_CODE ='ERP' 
AND TSS.SALES_TERRITORY_NAME=HIER.L2_SALES_TERRITORY_NAME_CODE
AND TSS.COUNTRY_FLG='X'


LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR TSS1
ON TSS1.PRODUCT_KEY                    = NRT.PRODUCT_KEY
AND TSS1.BK_ISO_COUNTRY_CD = ENDCUST.BRANCH_ISO_COUNTRY_CD                    
AND TSS1.BKGS_MEASURE_TRANS_TYPE_CODE ='ERP' 
AND TSS1.SALES_TERRITORY_NAME=HIER.L1_SALES_TERRITORY_NAME_CODE
AND TSS1.COUNTRY_FLG='X'

LEFT JOIN $$COMREFVWDB.R_SALES_HIERARCHY   SHRL
ON NRT.SALES_TERRITORY_KEY=SHRL.SALES_TERRITORY_KEY

LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR  L4_TSD
ON L4_TSD.SALES_TERRITORY_NAME=SHRL.L4_SALES_TERRITORY_NAME_CODE
AND L4_TSD.COUNTRY_FLG='N'

LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR  L3_TSD
ON L3_TSD.SALES_TERRITORY_NAME=SHRL.L3_SALES_TERRITORY_NAME_CODE
AND L3_TSD.COUNTRY_FLG='N'

LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR  L2_TSD
ON L2_TSD.SALES_TERRITORY_NAME=SHRL.L2_SALES_TERRITORY_NAME_CODE
AND L2_TSD.COUNTRY_FLG='N'
LEFT JOIN $$SLSORDVWDB.N_TSS_PRODUCT_COST_FACTOR  L1_TSD
ON L1_TSD.SALES_TERRITORY_NAME=SHRL.L1_SALES_TERRITORY_NAME_CODE
AND L1_TSD.COUNTRY_FLG='N'

LEFT OUTER JOIN
(
SELECT CR.PL_CONVERSION_RT,CR.ANNUAL_BUDGET_CONV_RT,CR.FISCAL_YEAR_MONTH_NUM_INT,FX.SALES_TERRITORY_KEY
FROM $$FINLGLVWDB.MT_MONTHLY_CONVERSION_RATE CR,
$$SLSORDVWDB.MT_PROFITABILITY_FX_NORM FX,
(SELECT (PDATE.FISCAL_YEAR_NUMBER_INT-5)*100+PDATE.FISCAL_MONTH_NUMBER_INT AS START_DATE,       
    PDATE.FISCAL_YEAR_MTH_NUMBER_INT+1 AS END_DATE
                    FROM $$ETLVWDB.MBR_PROCESS_DATE PDATE
                    )PDATE
WHERE  CR.BK_FROM_CURRENCY_CD=FX.BK_CURRENCY_CD
AND CR.BK_TO_CURRENCY_CD='USD' 
AND CR.FISCAL_YEAR_MONTH_NUM_INT   BETWEEN PDATE.START_DATE AND PDATE.END_DATE
)MCR   
ON NRT.SALES_TERRITORY_KEY=MCR.SALES_TERRITORY_KEY
AND  NRT.DV_FISCAL_YEAR_MTH_NUMBER_INT=MCR.FISCAL_YEAR_MONTH_NUM_INT   
WHERE
NRT.BKGS_MEASURE_TRANS_TYPE_CODE ='ERP' 
AND SERVICE_FLG = 'Y' AND DD_COMP_US_NET_PRICE_AMOUNT <> 0
) DVD

SET TSS_COUNTRY_FACTOR_KEY = DVD.TSS_COUNTRY_FACTOR_KEY,
DV_BKG_GROSS_MGN_AMOUNT = DVD.DV_BKG_GROSS_MGN_AMOUNT,
DV_BGM_FX_COST_AMOUNT = DVD.DV_BGM_FX_COST_AMOUNT,
DV_FX_NET_PRICE_AMT=DVD.DV_FX_NET_PRICE_AMT,
DV_BKG_REBATE_AMT=DVD.DV_BKG_REBATE,
DV_FX_REBATE_PRICE_AMT=DVD.DV_FX_REBATE_PRICE_AMT

WHERE  DVD.BOOKINGS_MEASURE_KEY =NBM.BOOKINGS_MEASURE_KEY
AND DVD.BKGS_MEASURE_TRANS_TYPE_CODE = NBM.BKGS_MEASURE_TRANS_TYPE_CODE
AND DVD.BOOKINGS_PROCESS_DATE = NBM.BOOKINGS_PROCESS_DATE;

CALL COLLECT_STATS_WRAP('$$WORKDB','W_BOOKINGS_MEASURE','D');


Source3 Name : SQ_N_BOOKINGS_MEASURE


Pre SQL : 



SQL Query : 
SELECT
BKG_TRX.BOOKINGS_MEASURE_KEY          ,
BKG_TRX.SALES_ORDER_KEY               ,
BKG_TRX.SALES_ORDER_LINE_KEY          ,
BKG_TRX.PRODUCT_KEY                   ,
BKG_TRX.AR_TRX_LINE_KEY               ,
BKG_TRX.AR_TRX_KEY                    ,
BKG_TRX.END_CUSTOMER_KEY              ,
BKG_TRX.BILL_TO_CUSTOMER_KEY          ,
BKG_TRX.SHIP_TO_CUSTOMER_KEY          ,
BKG_TRX.SOLD_TO_CUSTOMER_KEY          ,
BKG_TRX.DV_END_CUSTOMER_KEY           ,
BKG_TRX.TRANSACTION_DATETIME          ,
BKG_TRX.SALES_TERRITORY_KEY           ,
BKG_TRX.SALES_REP_NUMBER              ,
BKG_TRX.BOOKINGS_PROCESS_DATE         ,
BKG_TRX.DV_FISCAL_YEAR_MTH_NUMBER_INT ,
BKG_TRX.BK_POS_TRANSACTION_ID_INT     ,
BKG_TRX.BK_SALES_ADJ_LINE_NUMBER_INT  ,
BKG_TRX.BK_SALES_ADJ_NUMBER_INT       ,
BKG_TRX.ADJUSTMENT_TYPE_CODE          ,
BKG_TRX.SALES_CHANNEL_CODE            ,
BKG_TRX.SALES_CREDIT_TYPE_CODE        ,
BKG_TRX.IDE_ADJUSTMENT_CODE           ,
BKG_TRX.ADJUSTMENT_CODE               ,
BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE  ,
BKG_TRX.CANCELLED_FLG                 ,
BKG_TRX.CANCEL_CODE                   ,
BKG_TRX.ACQUISITION_FLG               ,
BKG_TRX.FORWARD_REVERSE_FLG           ,
BKG_TRX.DISTRIBUTOR_OFFSET_FLG        ,
BKG_TRX.CORPORATE_BOOKINGS_FLG        ,
BKG_TRX.OVERLAY_FLG                   ,
BKG_TRX.IC_REVENUE_FLG                ,
BKG_TRX.CHARGES_FLG                   ,
BKG_TRX.SALESREP_FLG                  ,
BKG_TRX.MISC_FLG                      ,
BKG_TRX.SERVICE_FLG                   ,
BKG_TRX.INTERNATIONAL_DEMO_FLG        ,
BKG_TRX.REPLACEMENT_DEMO_FLG          ,
BKG_TRX.REVENUE_FLG                   ,
BKG_TRX.RMA_FLG                       ,
BKG_TRX.TRADE_IN_AMOUNT               ,
BKG_TRX.DD_COMP_US_NET_PRICE_AMOUNT   ,
BKG_TRX.DD_COMP_US_LIST_PRICE_AMOUNT  ,
BKG_TRX.DD_COMP_US_COST_AMOUNT        ,
BKG_TRX.DD_EXTENDED_QUANTITY          ,
BKG_TRX.DD_COMP_US_HOLD_NET_PRICE_AMT ,
BKG_TRX.DD_COMP_US_HOLD_LIST_PRICE_AMT,
BKG_TRX.DD_COMP_US_HOLD_COST_AMOUNT   ,
BKG_TRX.DD_EXTENDED_HOLD_QUANTITY     ,
BKG_TRX.DD_COMP_US_STANDARD_PRICE_AMT ,
BKG_TRX.WIPS_ORIGINATOR_ID_INT        ,
BKG_TRX.EDW_CREATE_USER               ,
BKG_TRX.EDW_UPDATE_USER               ,
BKG_TRX.EDW_CREATE_DATETIME           ,
BKG_TRX.EDW_UPDATE_DATETIME           ,
BKG_TRX.CONVERSION_RT                 ,
BKG_TRX.CONVERSION_DT                 ,
BKG_TRX.DD_BK_SO_NUMBER_INT           ,
BKG_TRX.DD_CISCO_BOOKED_DTM           ,
BKG_TRX.DD_SALES_ORDER_CATEGORY_TYPE  ,
BKG_TRX.DD_SLS_ORD_OPERATING_UNIT_CD  ,
BKG_TRX.DD_TRX_CURRENCY_CD            ,
BKG_TRX.DV_TRANSACTION_TYPE           ,
BKG_TRX.ADJUSTMENT_DESCR_KEY          ,
BKG_TRX.DV_TRANSACTION_NAME           ,
BKG_TRX.BOOKINGS_SPLIT_PCT            ,
BKG_TRX.DV_REVENUE_RECOGNITION_FLG    ,
BKG_TRX.DV_NET_SPREAD_FLG             ,
BKG_TRX.REVENUE_TRANSFER_KEY          ,
BKG_TRX.DV_ATTRIBUTION_CD             ,
BKG_TRX.DV_PRODUCT_KEY                ,
BKG_TRX.DV_SALES_ORDER_LINE_KEY       ,
BKG_TRX.SK_OFFER_ATTRIBUTION_ID_INT   ,
BKG_TRX.DV_FMV_FLG                    ,
BKG_TRX.RU_SERVICE_CONTRACT_START_DTM ,
BKG_TRX.RU_SERVICE_CONTRACT_END_DTM   ,
BKG_TRX.DV_CONTRACT_DURATION          ,
BKG_TRX.DV_ANNUALIZED_FLG             ,
BKG_TRX.DV_ANNUALIZED_US_NET_AMT      ,
BKG_TRX.DV_MULTIYEAR_US_NET_AMT       ,
BKG_TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY   ,
BKG_TRX.DSV_FLG                       ,
BKG_TRX.DV_SOURCE_ORDER_NUM_INT       ,
BKG_TRX.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY,
BKG_TRX.FISCAL_YEAR_QUARTER_NUMBER_INT,
BKG_TRX.DV_AR_TRX_LINE_KEY            ,
BKG_TRX.XAAS_OFFER_ATRBTN_REV_LINE_KEY,
BKG_TRX.DV_DEAL_ID                    ,
BKG_TRX.TSS_COUNTRY_FACTOR_KEY        ,
BKG_TRX.DV_BKG_GROSS_MGN_AMOUNT       ,
BKG_TRX.DV_BGM_FX_COST_AMOUNT         ,
BKG_TRX.DV_FX_NET_PRICE_AMT           
/*ADDED THE BELOW COLUMNS AS PART OF RO PROJECT: RELEASE -Q3FY17 */
,CASE WHEN NSO.XCAT_FLG = 'Y' THEN NSO.XCAT_FLG ELSE     COALESCE(NP.XCAT_FLG,'N' ) END
,BKG_TRX.BK_OFFER_TYPE_NAME
,BKG_TRX.RECURRING_OFFER_FLG
,BKG_TRX.ELA_FLG
,BKG_TRX.DV_LOCAL_EXTND_LIST_PRICE_AMT 
,BKG_TRX.LOCAL_UNIT_LIST_PRICE_AMT     
,BKG_TRX.DV_UNIT_LIST_PRICE_USD_AMT
,BKG_TRX.DV_BGM_NON_STANDARD_COST_AMT /*added as part product BGM - Q1FY18 release */
,BKG_TRX.POB_TYPE_CD
,BKG_TRX.NRS_TRANSITION_FLG
,BKG_TRX.SALES_MOTION_CD /* Added as part of Oct - 2017 rel */
,BKG_TRX.SUMMARY_QUOTE_FLG  /* Added as part of Oct - 2017 rel */
,BKG_TRX.DV_BKG_REBATE_AMT
,BKG_TRX.DV_FX_REBATE_PRICE_AMT
,BKG_TRX.SK_SALES_MOTION_ATTRIB_KEY /* Added as part of SALES FY18 May12Rel */
,BKG_TRX.DD_COMP_US_ORIG_LIST_PRICE
,BKG_TRX.DD_COMP_US_ORIG_EXT_LIST_PRICE
,BKG_TRX.DV_INV_DTM
,BKG_TRX.DV_COMPENSATION_DTM
,BKG_TRX.BOOKINGS_POLICY_CD
,BKG_TRX.SOURCE_REP_ANNUAL_USD_AMT
FROM 
       $$SLSORDVWDB.N_BOOKINGS_MEASURE BKG_TRX
       INNER JOIN
				       (
				SEL FISCAL_YEAR_MONTH_INT FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR 
				WHERE 1=1
				AND FISCAL_YEAR_AGE BETWEEN 0 AND (SELECT CASE WHEN FISCAL_QUARTER_NUMBER_INT =1 THEN 4 ELSE 3 END FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR  WHERE FISCAL_MONTH_AGE=0 )
				AND FISCAL_MONTH_AGE >=0
				) CAL
				ON BKG_TRX.DV_FISCAL_YEAR_MTH_NUMBER_INT=CAL.FISCAL_YEAR_MONTH_INT
 INNER JOIN 
        $$SLSORDVWDB.N_SALES_ORDER_TV NSO
ON BKG_TRX.SALES_ORDER_KEY=NSO.SALES_ORDER_KEY
AND NSO.END_TV_DATETIME= '3500-01-01 00:00:00'
 INNER JOIN
( 
	SELECT	NP.ITEM_KEY, NP.XCAT_FLG 
	FROM	$$COMREFVWDB.N_PRODUCT NP ,
			
		              (
		SELECT	BKG_TRX.PRODUCT_KEY 
		FROM	$$SLSORDVWDB.N_BOOKINGS_MEASURE BKG_TRX 
					  		WHERE	BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP' 
		                   )  BKG_TRX	
	WHERE	BKG_TRX.PRODUCT_KEY=NP.ITEM_KEY 
						GROUP BY 1,2  ) NP
         ON BKG_TRX.PRODUCT_KEY=NP.ITEM_KEY
WHERE BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP'
AND NSO.EDW_UPDATE_DATETIME >= (SELECT LAST_EXTRACT_DATE FROM $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES
WHERE JOB_STREAM_ID='wf_W_BOOKINGS_MEASURE_ERP'
AND TABLE_NAME ='W_BOOKINGS_MEASURE_ERP')
AND BKG_TRX.XCAT_FLG <> (CASE WHEN NSO.XCAT_FLG = 'Y' THEN NSO.XCAT_FLG ELSE  COALESCE(NP.XCAT_FLG,'N' ) END)

UNION 
SELECT
BKG_TRX.BOOKINGS_MEASURE_KEY          ,
BKG_TRX.SALES_ORDER_KEY               ,
BKG_TRX.SALES_ORDER_LINE_KEY          ,
BKG_TRX.PRODUCT_KEY                   ,
BKG_TRX.AR_TRX_LINE_KEY               ,
BKG_TRX.AR_TRX_KEY                    ,
BKG_TRX.END_CUSTOMER_KEY              ,
BKG_TRX.BILL_TO_CUSTOMER_KEY          ,
BKG_TRX.SHIP_TO_CUSTOMER_KEY          ,
BKG_TRX.SOLD_TO_CUSTOMER_KEY          ,
BKG_TRX.DV_END_CUSTOMER_KEY           ,
BKG_TRX.TRANSACTION_DATETIME          ,
BKG_TRX.SALES_TERRITORY_KEY           ,
BKG_TRX.SALES_REP_NUMBER              ,
BKG_TRX.BOOKINGS_PROCESS_DATE         ,
BKG_TRX.DV_FISCAL_YEAR_MTH_NUMBER_INT ,
BKG_TRX.BK_POS_TRANSACTION_ID_INT     ,
BKG_TRX.BK_SALES_ADJ_LINE_NUMBER_INT  ,
BKG_TRX.BK_SALES_ADJ_NUMBER_INT       ,
BKG_TRX.ADJUSTMENT_TYPE_CODE          ,
BKG_TRX.SALES_CHANNEL_CODE            ,
BKG_TRX.SALES_CREDIT_TYPE_CODE        ,
BKG_TRX.IDE_ADJUSTMENT_CODE           ,
BKG_TRX.ADJUSTMENT_CODE               ,
BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE  ,
BKG_TRX.CANCELLED_FLG                 ,
BKG_TRX.CANCEL_CODE                   ,
BKG_TRX.ACQUISITION_FLG               ,
BKG_TRX.FORWARD_REVERSE_FLG           ,
BKG_TRX.DISTRIBUTOR_OFFSET_FLG        ,
BKG_TRX.CORPORATE_BOOKINGS_FLG        ,
BKG_TRX.OVERLAY_FLG                   ,
BKG_TRX.IC_REVENUE_FLG                ,
BKG_TRX.CHARGES_FLG                   ,
BKG_TRX.SALESREP_FLG                  ,
BKG_TRX.MISC_FLG                      ,
BKG_TRX.SERVICE_FLG                   ,
BKG_TRX.INTERNATIONAL_DEMO_FLG        ,
BKG_TRX.REPLACEMENT_DEMO_FLG          ,
BKG_TRX.REVENUE_FLG                   ,
BKG_TRX.RMA_FLG                       ,
BKG_TRX.TRADE_IN_AMOUNT               ,
BKG_TRX.DD_COMP_US_NET_PRICE_AMOUNT   ,
BKG_TRX.DD_COMP_US_LIST_PRICE_AMOUNT  ,
BKG_TRX.DD_COMP_US_COST_AMOUNT        ,
BKG_TRX.DD_EXTENDED_QUANTITY          ,
BKG_TRX.DD_COMP_US_HOLD_NET_PRICE_AMT ,
BKG_TRX.DD_COMP_US_HOLD_LIST_PRICE_AMT,
BKG_TRX.DD_COMP_US_HOLD_COST_AMOUNT   ,
BKG_TRX.DD_EXTENDED_HOLD_QUANTITY     ,
BKG_TRX.DD_COMP_US_STANDARD_PRICE_AMT ,
BKG_TRX.WIPS_ORIGINATOR_ID_INT        ,
BKG_TRX.EDW_CREATE_USER               ,
BKG_TRX.EDW_UPDATE_USER               ,
BKG_TRX.EDW_CREATE_DATETIME           ,
BKG_TRX.EDW_UPDATE_DATETIME           ,
BKG_TRX.CONVERSION_RT                 ,
BKG_TRX.CONVERSION_DT                 ,
BKG_TRX.DD_BK_SO_NUMBER_INT           ,
BKG_TRX.DD_CISCO_BOOKED_DTM           ,
BKG_TRX.DD_SALES_ORDER_CATEGORY_TYPE  ,
BKG_TRX.DD_SLS_ORD_OPERATING_UNIT_CD  ,
BKG_TRX.DD_TRX_CURRENCY_CD            ,
BKG_TRX.DV_TRANSACTION_TYPE           ,
BKG_TRX.ADJUSTMENT_DESCR_KEY          ,
BKG_TRX.DV_TRANSACTION_NAME           ,
BKG_TRX.BOOKINGS_SPLIT_PCT            ,
BKG_TRX.DV_REVENUE_RECOGNITION_FLG    ,
BKG_TRX.DV_NET_SPREAD_FLG             ,
BKG_TRX.REVENUE_TRANSFER_KEY          ,
BKG_TRX.DV_ATTRIBUTION_CD             ,
BKG_TRX.DV_PRODUCT_KEY                ,
BKG_TRX.DV_SALES_ORDER_LINE_KEY       ,
BKG_TRX.SK_OFFER_ATTRIBUTION_ID_INT   ,
BKG_TRX.DV_FMV_FLG                    ,
BKG_TRX.RU_SERVICE_CONTRACT_START_DTM ,
BKG_TRX.RU_SERVICE_CONTRACT_END_DTM   ,
BKG_TRX.DV_CONTRACT_DURATION          ,
BKG_TRX.DV_ANNUALIZED_FLG             ,
BKG_TRX.DV_ANNUALIZED_US_NET_AMT      ,
BKG_TRX.DV_MULTIYEAR_US_NET_AMT       ,
BKG_TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY   ,
BKG_TRX.DSV_FLG                       ,
BKG_TRX.DV_SOURCE_ORDER_NUM_INT       ,
BKG_TRX.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY,
BKG_TRX.FISCAL_YEAR_QUARTER_NUMBER_INT,
BKG_TRX.DV_AR_TRX_LINE_KEY            ,
BKG_TRX.XAAS_OFFER_ATRBTN_REV_LINE_KEY,
BKG_TRX.DV_DEAL_ID                    ,
BKG_TRX.TSS_COUNTRY_FACTOR_KEY        ,
BKG_TRX.DV_BKG_GROSS_MGN_AMOUNT       ,
BKG_TRX.DV_BGM_FX_COST_AMOUNT         ,
BKG_TRX.DV_FX_NET_PRICE_AMT           
/*ADDED THE BELOW COLUMNS AS PART OF RO PROJECT: RELEASE -Q3FY17 */
,CASE WHEN NSO.XCAT_FLG = 'Y' THEN NSO.XCAT_FLG ELSE     COALESCE(NP.XCAT_FLG,'N' ) END
,BKG_TRX.BK_OFFER_TYPE_NAME
,BKG_TRX.RECURRING_OFFER_FLG
,BKG_TRX.ELA_FLG
,BKG_TRX.DV_LOCAL_EXTND_LIST_PRICE_AMT 
,BKG_TRX.LOCAL_UNIT_LIST_PRICE_AMT     
,BKG_TRX.DV_UNIT_LIST_PRICE_USD_AMT  
,BKG_TRX.DV_BGM_NON_STANDARD_COST_AMT /*added as part product BGM - Q1FY18 release */
,BKG_TRX.POB_TYPE_CD
,BKG_TRX.NRS_TRANSITION_FLG
,BKG_TRX.SALES_MOTION_CD /* Added as part of Oct - 2017 rel */
,BKG_TRX.SUMMARY_QUOTE_FLG  /* Added as part of Oct - 2017 rel */
,BKG_TRX.DV_BKG_REBATE_AMT
,BKG_TRX.DV_FX_REBATE_PRICE_AMT
,BKG_TRX.SK_SALES_MOTION_ATTRIB_KEY /* Added as part of SALES FY18 May12Rel */
,BKG_TRX.DD_COMP_US_ORIG_LIST_PRICE
,BKG_TRX.DD_COMP_US_ORIG_EXT_LIST_PRICE
,BKG_TRX.DV_INV_DTM
,BKG_TRX.DV_COMPENSATION_DTM
,BKG_TRX.BOOKINGS_POLICY_CD
,BKG_TRX.SOURCE_REP_ANNUAL_USD_AMT

FROM 
       $$SLSORDVWDB.N_BOOKINGS_MEASURE BKG_TRX
       INNER JOIN
				       (
				SEL FISCAL_YEAR_MONTH_INT FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR 
				WHERE 1=1
				AND FISCAL_YEAR_AGE BETWEEN 0 AND (SELECT CASE WHEN FISCAL_QUARTER_NUMBER_INT =1 THEN 4 ELSE 3 END FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR  WHERE FISCAL_MONTH_AGE=0 )
				AND FISCAL_MONTH_AGE >=0
				) CAL
				ON BKG_TRX.DV_FISCAL_YEAR_MTH_NUMBER_INT=CAL.FISCAL_YEAR_MONTH_INT
 INNER JOIN 
        $$SLSORDVWDB.N_SALES_ORDER_TV NSO
ON BKG_TRX.SALES_ORDER_KEY=NSO.SALES_ORDER_KEY
AND NSO.END_TV_DATETIME= '3500-01-01 00:00:00'
 INNER JOIN
 $$COMREFVWDB.N_PRODUCT NP
         ON BKG_TRX.PRODUCT_KEY=NP.ITEM_KEY
WHERE BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP'
AND NP.EDW_UPDATE_DATETIME >= (SELECT LAST_EXTRACT_DATE FROM $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES
WHERE JOB_STREAM_ID='wf_W_BOOKINGS_MEASURE_ERP'
AND TABLE_NAME ='W_BOOKINGS_MEASURE_ERP')
AND BKG_TRX.XCAT_FLG <> (CASE WHEN NSO.XCAT_FLG = 'Y' THEN NSO.XCAT_FLG ELSE  COALESCE(NP.XCAT_FLG,'N' ) END)


Post SQL : 



Target3 Name : WI_OFFER_TYPE_RETRO_ERP1


Pre SQL : 
DELETE FROM $$STGDB.WI_OFFER_TYPE_RETRO_ERP ALL;


Post SQL : 
/*Commented as part of retro update removal in bookings Q4FY19
UPDATE  WI FROM $$STGDB.WI_OFFER_TYPE_RETRO_ERP WI
  ,$$COMREFVWDB.MT_OFFER_TYPE_PRDT_MAP PMAP
  ,$$SLSORDVWDB.N_SALES_ORDER_TV NSO
  SET 
  RECURRING_OFFER_FLG = PMAP.RECURRING_OFFER_FLG,
  BK_OFFER_TYPE_NAME = PMAP.BK_OFFER_TYPE_NAME,
   ELA_FLG= (CASE  WHEN    WI.XCAT_FLG   = 'Y' THEN 'Y' ELSE PMAP.ELA_FLG END) 
  WHERE PMAP.PRODUCT_KEY            = WI.PRODUCT_KEY
  AND   PMAP.DV_PRODUCT_KEY            = WI.DV_PRODUCT_KEY
  AND PMAP.BK_OFFER_ATTRBTN_TYPE_CD = WI.DV_ATTRIBUTION_CD
  AND  NSO.SALES_ORDER_KEY=WI.SALES_ORDER_KEY
 AND NSO.END_TV_DATETIME= '3500-01-01 00:00:00'
 AND  NOT EXISTS 
 (SELECT 1 FROM $$ETLVWDB.EL_RO_CSCC_SO_SRC_NAME EL
 WHERE NSO.BK_SO_SOURCE_NAME= EL.BK_SO_SOURCE_NAME
 AND EL.ACTIVE_IND='Y'
 );*/

 DELETE FROM $$STGDB.WI_SOL_OFFER_ATTR_BKGS_ERP_RO;
 
 INSERT INTO $$STGDB.WI_SOL_OFFER_ATTR_BKGS_ERP_RO
 (ENTERPRISE_SKU_KEY,
 ENTERPRISE_SKU ,
 SK_OFFER_ATTRIBUTION_ID_INT,
 ATTRIBUTION_CD,
 EDW_UPDATE_DTM )
SELECT 
NP.ITEM_KEY AS ENTERPRISE_SKU_KEY, 
NP.BK_PRODUCT_ID AS ENTERPRISE_SKU ,
NSOL.SK_OFFER_ATTRIBUTION_ID_INT, 
NSOL.ATTRIBUTION_CD ,
NSOL.EDW_UPDATE_DTM                 
FROM                        
$$COMREFVWDB.N_PRODUCT NP,                
$$NRTNCRVWDB.N_SOL_OFFER_ATTRIBUTION_TV NSOL
WHERE                
NP.ITEM_KEY=NSOL.ENTERPRISE_SKU_PRDT_KEY                              
AND NSOL.ENTERPRISE_SKU_PRDT_KEY<>-999
AND NSOL.ATTRIBUTION_CD IN (SELECT ATTRIBUTION_CD FROM $$ETLVWDB.EL_RO_OFFER_ATTRB_CODE)
AND NSOL.END_TV_DTM='3500-01-01 00:00:00';

CALL COLLECT_STATS_WRAP('$$STGDB','WI_SOL_OFFER_ATTR_BKGS_ERP_RO','D');

/*Commented as part of retro update removal in bookings Q4FY19
UPDATE  WBM 
FROM  $$STGDB.WI_OFFER_TYPE_RETRO_ERP WBM,
  (
SELECT  
BKG_TRX.BOOKINGS_MEASURE_KEY,
BKG_TRX.BOOKINGS_PROCESS_DATE,
BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE,
CASE WHEN  NOTV.BK_PARENT_OFFER_TYPE_NAME = 'Cisco One' THEN  ALLOC_ENT.BK_OFFER_TYPE_NAME ELSE  COALESCE(PMAP.BK_OFFER_TYPE_NAME,'Others') END AS BK_OFFER_TYPE_NAME,
COALESCE(PMAP.RECURRING_OFFER_FLG,'N') AS RECURRING_OFFER_FLG ,
CASE WHEN BKG_TRX.XCAT_FLG = 'Y' THEN 'Y' WHEN NOTV.BK_PARENT_OFFER_TYPE_NAME = 'Cisco One' THEN  ALLOC_ENT.ELA_FLG ELSE COALESCE(PMAP.ELA_FLG,'N') END AS ELA_FLG 
FROM $$STGDB.WI_OFFER_TYPE_RETRO_ERP BKG_TRX

INNER JOIN 
$$SLSORDVWDB.N_SALES_ORDER_TV NSO
ON BKG_TRX.SALES_ORDER_KEY=NSO.SALES_ORDER_KEY
AND NSO.END_TV_DATETIME= '3500-01-01 00:00:00'

LEFT OUTER JOIN  $$STGDB.WI_SOL_OFFER_ATTR_BKGS_ERP_RO NSOAT 
ON  NSOAT.SK_OFFER_ATTRIBUTION_ID_INT=BKG_TRX.SK_OFFER_ATTRIBUTION_ID_INT

LEFT OUTER JOIN $$COMREFVWDB.MT_OFFER_TYPE_PRDT_MAP ALLOC_ENT                       
ON ALLOC_ENT.DV_PRODUCT_KEY = NSOAT.ENTERPRISE_SKU_KEY                        
AND ALLOC_ENT.BK_OFFER_ATTRBTN_TYPE_CD = 'STANDALONE'    

LEFT OUTER JOIN $$COMREFVWDB.N_OFFER_TYPE NOTV
ON  ALLOC_ENT.BK_OFFER_TYPE_NAME=NOTV. BK_OFFER_TYPE_NAME           
 
LEFT OUTER JOIN $$COMREFVWDB.MT_OFFER_TYPE_PRDT_MAP PMAP                       
ON  PMAP.PRODUCT_KEY            = BKG_TRX.PRODUCT_KEY
AND PMAP.DV_PRODUCT_KEY            = BKG_TRX.DV_PRODUCT_KEY
AND PMAP.BK_OFFER_ATTRBTN_TYPE_CD = BKG_TRX.DV_ATTRIBUTION_CD             
        
WHERE  BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP' 
AND   BK_SO_SOURCE_NAME IN (SELECT BK_SO_SOURCE_NAME FROM $$ETLVWDB.EL_RO_CSCC_SO_SRC_NAME WHERE ACTIVE_IND='Y')
)PMAP
SET 
 BK_OFFER_TYPE_NAME = PMAP.BK_OFFER_TYPE_NAME,
  RECURRING_OFFER_FLG = PMAP.RECURRING_OFFER_FLG,
   ELA_FLG= PMAP.ELA_FLG,
   EDW_UPDATE_USER   =  USER,
  EDW_UPDATE_DATETIME = CURRENT_TIMESTAMP(0)
  WHERE WBM.BOOKINGS_MEASURE_KEY = PMAP.BOOKINGS_MEASURE_KEY AND
 WBM.BOOKINGS_PROCESS_DATE= PMAP.BOOKINGS_PROCESS_DATE AND
 WBM.BKGS_MEASURE_TRANS_TYPE_CODE=PMAP.BKGS_MEASURE_TRANS_TYPE_CODE;
 */


Source4 Name : SQ_WI_OFFER_TYPE_RETRO_ERP1


Pre SQL : 



SQL Query : 
SELECT
BKG_TRX.BOOKINGS_MEASURE_KEY          ,
BKG_TRX.SALES_ORDER_KEY               ,
BKG_TRX.SALES_ORDER_LINE_KEY          ,
BKG_TRX.PRODUCT_KEY                   ,
BKG_TRX.AR_TRX_LINE_KEY               ,
BKG_TRX.AR_TRX_KEY                    ,
BKG_TRX.END_CUSTOMER_KEY              ,
BKG_TRX.BILL_TO_CUSTOMER_KEY          ,
BKG_TRX.SHIP_TO_CUSTOMER_KEY          ,
BKG_TRX.SOLD_TO_CUSTOMER_KEY          ,
BKG_TRX.DV_END_CUSTOMER_KEY           ,
BKG_TRX.TRANSACTION_DATETIME          ,
BKG_TRX.SALES_TERRITORY_KEY           ,
BKG_TRX.SALES_REP_NUMBER              ,
BKG_TRX.BOOKINGS_PROCESS_DATE         ,
BKG_TRX.DV_FISCAL_YEAR_MTH_NUMBER_INT ,
BKG_TRX.BK_POS_TRANSACTION_ID_INT     ,
BKG_TRX.BK_SALES_ADJ_LINE_NUMBER_INT  ,
BKG_TRX.BK_SALES_ADJ_NUMBER_INT       ,
BKG_TRX.ADJUSTMENT_TYPE_CODE          ,
BKG_TRX.SALES_CHANNEL_CODE            ,
BKG_TRX.SALES_CREDIT_TYPE_CODE        ,
BKG_TRX.IDE_ADJUSTMENT_CODE           ,
BKG_TRX.ADJUSTMENT_CODE               ,
BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE  ,
BKG_TRX.CANCELLED_FLG                 ,
BKG_TRX.CANCEL_CODE                   ,
BKG_TRX.ACQUISITION_FLG               ,
BKG_TRX.FORWARD_REVERSE_FLG           ,
BKG_TRX.DISTRIBUTOR_OFFSET_FLG        ,
BKG_TRX.CORPORATE_BOOKINGS_FLG        ,
BKG_TRX.OVERLAY_FLG                   ,
BKG_TRX.IC_REVENUE_FLG                ,
BKG_TRX.CHARGES_FLG                   ,
BKG_TRX.SALESREP_FLG                  ,
BKG_TRX.MISC_FLG                      ,
BKG_TRX.SERVICE_FLG                   ,
BKG_TRX.INTERNATIONAL_DEMO_FLG        ,
BKG_TRX.REPLACEMENT_DEMO_FLG          ,
BKG_TRX.REVENUE_FLG                   ,
BKG_TRX.RMA_FLG                       ,
BKG_TRX.TRADE_IN_AMOUNT               ,
BKG_TRX.DD_COMP_US_NET_PRICE_AMOUNT   ,
BKG_TRX.DD_COMP_US_LIST_PRICE_AMOUNT  ,
BKG_TRX.DD_COMP_US_COST_AMOUNT        ,
BKG_TRX.DD_EXTENDED_QUANTITY          ,
BKG_TRX.DD_COMP_US_HOLD_NET_PRICE_AMT ,
BKG_TRX.DD_COMP_US_HOLD_LIST_PRICE_AMT,
BKG_TRX.DD_COMP_US_HOLD_COST_AMOUNT   ,
BKG_TRX.DD_EXTENDED_HOLD_QUANTITY     ,
BKG_TRX.DD_COMP_US_STANDARD_PRICE_AMT ,
BKG_TRX.WIPS_ORIGINATOR_ID_INT        ,
BKG_TRX.EDW_CREATE_USER               ,
BKG_TRX.EDW_UPDATE_USER               ,
BKG_TRX.EDW_CREATE_DATETIME           ,
BKG_TRX.EDW_UPDATE_DATETIME           ,
BKG_TRX.CONVERSION_RT                 ,
BKG_TRX.CONVERSION_DT                 ,
BKG_TRX.DD_BK_SO_NUMBER_INT           ,
BKG_TRX.DD_CISCO_BOOKED_DTM           ,
BKG_TRX.DD_SALES_ORDER_CATEGORY_TYPE  ,
BKG_TRX.DD_SLS_ORD_OPERATING_UNIT_CD  ,
BKG_TRX.DD_TRX_CURRENCY_CD            ,
BKG_TRX.DV_TRANSACTION_TYPE           ,
BKG_TRX.ADJUSTMENT_DESCR_KEY          ,
BKG_TRX.DV_TRANSACTION_NAME           ,
BKG_TRX.BOOKINGS_SPLIT_PCT            ,
BKG_TRX.DV_REVENUE_RECOGNITION_FLG    ,
BKG_TRX.DV_NET_SPREAD_FLG             ,
BKG_TRX.REVENUE_TRANSFER_KEY          ,
BKG_TRX.DV_ATTRIBUTION_CD             ,
BKG_TRX.DV_PRODUCT_KEY                ,
BKG_TRX.DV_SALES_ORDER_LINE_KEY       ,
BKG_TRX.SK_OFFER_ATTRIBUTION_ID_INT   ,
BKG_TRX.DV_FMV_FLG                    ,
BKG_TRX.RU_SERVICE_CONTRACT_START_DTM ,
BKG_TRX.RU_SERVICE_CONTRACT_END_DTM   ,
BKG_TRX.DV_CONTRACT_DURATION          ,
BKG_TRX.DV_ANNUALIZED_FLG             ,
BKG_TRX.DV_ANNUALIZED_US_NET_AMT      ,
BKG_TRX.DV_MULTIYEAR_US_NET_AMT       ,
BKG_TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY   ,
BKG_TRX.DSV_FLG                       ,
BKG_TRX.DV_SOURCE_ORDER_NUM_INT       ,
BKG_TRX.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY,
BKG_TRX.FISCAL_YEAR_QUARTER_NUMBER_INT,
BKG_TRX.DV_AR_TRX_LINE_KEY            ,
BKG_TRX.XAAS_OFFER_ATRBTN_REV_LINE_KEY,
BKG_TRX.DV_DEAL_ID                    ,
BKG_TRX.TSS_COUNTRY_FACTOR_KEY        ,
BKG_TRX.DV_BKG_GROSS_MGN_AMOUNT       ,
BKG_TRX.DV_BGM_FX_COST_AMOUNT         ,
BKG_TRX.DV_FX_NET_PRICE_AMT           
/*ADDED THE BELOW COLUMNS AS PART OF RO PROJECT: RELEASE -Q3FY17 */
,BKG_TRX.XCAT_FLG  AS XCAT_FLG
,PMAP.BK_OFFER_TYPE_NAME
,PMAP.RECURRING_OFFER_FLG
/*CHANGED AS PART 0F MAR 16 RELEASE -Q3FY17 */
,CASE    WHEN BKG_TRX.XCAT_FLG   = 'Y' THEN 'Y' ELSE PMAP.ELA_FLG  END AS ELA_FLG
,BKG_TRX.DV_LOCAL_EXTND_LIST_PRICE_AMT 
,BKG_TRX.LOCAL_UNIT_LIST_PRICE_AMT     
,BKG_TRX.DV_UNIT_LIST_PRICE_USD_AMT 
,BKG_TRX.DV_BGM_NON_STANDARD_COST_AMT /*added as part product BGM - Q1FY18 release */
,BKG_TRX.POB_TYPE_CD															 
,BKG_TRX.NRS_TRANSITION_FLG
,BKG_TRX.SALES_MOTION_CD /* Added as part of Oct - 2017 rel */
,BKG_TRX.SUMMARY_QUOTE_FLG  /* Added as part of Oct - 2017 rel */
,BKG_TRX.DV_BKG_REBATE_AMT  /* Added as part of Oct - 2017 rel */
,BKG_TRX.DV_FX_REBATE_PRICE_AMT
,BKG_TRX.SK_SALES_MOTION_ATTRIB_KEY /* Added as part of SALES FY18 May12Rel */
,BKG_TRX.DD_COMP_US_ORIG_LIST_PRICE
,BKG_TRX.DD_COMP_US_ORIG_EXT_LIST_PRICE
,BKG_TRX.DV_INV_DTM
,BKG_TRX.DV_COMPENSATION_DTM
,BKG_TRX.BOOKINGS_POLICY_CD
,BKG_TRX.SOURCE_REP_ANNUAL_USD_AMT
FROM 
       $$SLSORDVWDB.N_BOOKINGS_MEASURE BKG_TRX
       INNER JOIN
				       (
				SEL FISCAL_YEAR_MONTH_INT FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR 
				WHERE 1=1
				AND FISCAL_YEAR_AGE BETWEEN 0 AND (SELECT CASE WHEN FISCAL_QUARTER_NUMBER_INT =1 THEN 4 ELSE 3 END 
                FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR  WHERE FISCAL_MONTH_AGE=0 )
				and FISCAL_MONTH_AGE >=0
				) CAL
				ON BKG_TRX.DV_FISCAL_YEAR_MTH_NUMBER_INT=CAL.FISCAL_YEAR_MONTH_INT
INNER JOIN
				$$COMREFVWDB.MT_OFFER_TYPE_PRDT_MAP PMAP
     ON PMAP.PRODUCT_KEY            = BKG_TRX.PRODUCT_KEY
 AND   PMAP.DV_PRODUCT_KEY            = BKG_TRX.DV_PRODUCT_KEY
 AND PMAP.BK_OFFER_ATTRBTN_TYPE_CD = BKG_TRX.DV_ATTRIBUTION_CD  
 
INNER JOIN $$SLSORDVWDB.N_SALES_ORDER_TV NSO
   ON BKG_TRX.SALES_ORDER_KEY=NSO.SALES_ORDER_KEY
 AND NSO.END_TV_DATETIME= '3500-01-01 00:00:00'
WHERE BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP'

AND PMAP.EDW_UPDATE_DTM >= (SELECT LAST_EXTRACT_DATE FROM $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES
		WHERE JOB_STREAM_ID='wf_W_BOOKINGS_MEASURE_ERP'
			AND TABLE_NAME ='W_BOOKINGS_MEASURE_ERP')
/*Added as part of May21 RO */
   AND  NOT EXISTS 
 (SELECT 1 FROM $$ETLVWDB.EL_RO_CSCC_SO_SRC_NAME EL
 WHERE NSO.BK_SO_SOURCE_NAME= EL.BK_SO_SOURCE_NAME
 AND EL.ACTIVE_IND='Y'
 )
AND  NOT EXISTS  (SELECT 1 
 FROM $$STGDB.WI_OFFER_TYPE_RETRO_ERP  WI
 WHERE WI.BOOKINGS_MEASURE_KEY = BKG_TRX.BOOKINGS_MEASURE_KEY AND 
 WI.BOOKINGS_PROCESS_DATE= BKG_TRX.BOOKINGS_PROCESS_DATE AND
 WI.BKGS_MEASURE_TRANS_TYPE_CODE =BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE)
  AND 
 (
 BKG_TRX.BK_OFFER_TYPE_NAME <> PMAP.BK_OFFER_TYPE_NAME
 OR
BKG_TRX.RECURRING_OFFER_FLG <> PMAP.RECURRING_OFFER_FLG
OR
 /*CHANGED AS PART 0F MAR 16 RELEASE -Q3FY17 */
 -----BKG_TRX.ELA_FLG <>  PMAP.ELA_FLG
BKG_TRX.ELA_FLG <> (CASE    WHEN BKG_TRX.XCAT_FLG   = 'Y' THEN 'Y'  ELSE PMAP.ELA_FLG  END)
)
AND 1=2


Post SQL : 



Target4 Name : WI_OFFER_TYPE_RETRO_ERP3


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_OFFER_TYPE_RETRO_ERP','D');

 UPDATE $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES
 SET LAST_EXTRACT_DATE = CURRENT_TIMESTAMP(0)
WHERE JOB_STREAM_ID='wf_W_BOOKINGS_MEASURE_ERP'
AND TABLE_NAME ='W_BOOKINGS_MEASURE_ERP';


Source5 Name : SQ_WI_OFFER_TYPE_RETRO_ERP


Pre SQL : 



SQL Query : 
SELECT
BKG_TRX.BOOKINGS_MEASURE_KEY          ,
BKG_TRX.SALES_ORDER_KEY               ,
BKG_TRX.SALES_ORDER_LINE_KEY          ,
BKG_TRX.PRODUCT_KEY                   ,
BKG_TRX.AR_TRX_LINE_KEY               ,
BKG_TRX.AR_TRX_KEY                    ,
BKG_TRX.END_CUSTOMER_KEY              ,
BKG_TRX.BILL_TO_CUSTOMER_KEY          ,
BKG_TRX.SHIP_TO_CUSTOMER_KEY          ,
BKG_TRX.SOLD_TO_CUSTOMER_KEY          ,
BKG_TRX.DV_END_CUSTOMER_KEY           ,
BKG_TRX.TRANSACTION_DATETIME          ,
BKG_TRX.SALES_TERRITORY_KEY           ,
BKG_TRX.SALES_REP_NUMBER              ,
BKG_TRX.BOOKINGS_PROCESS_DATE         ,
BKG_TRX.DV_FISCAL_YEAR_MTH_NUMBER_INT ,
BKG_TRX.BK_POS_TRANSACTION_ID_INT     ,
BKG_TRX.BK_SALES_ADJ_LINE_NUMBER_INT  ,
BKG_TRX.BK_SALES_ADJ_NUMBER_INT       ,
BKG_TRX.ADJUSTMENT_TYPE_CODE          ,
BKG_TRX.SALES_CHANNEL_CODE            ,
BKG_TRX.SALES_CREDIT_TYPE_CODE        ,
BKG_TRX.IDE_ADJUSTMENT_CODE           ,
BKG_TRX.ADJUSTMENT_CODE               ,
BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE  ,
BKG_TRX.CANCELLED_FLG                 ,
BKG_TRX.CANCEL_CODE                   ,
BKG_TRX.ACQUISITION_FLG               ,
BKG_TRX.FORWARD_REVERSE_FLG           ,
BKG_TRX.DISTRIBUTOR_OFFSET_FLG        ,
BKG_TRX.CORPORATE_BOOKINGS_FLG        ,
BKG_TRX.OVERLAY_FLG                   ,
BKG_TRX.IC_REVENUE_FLG                ,
BKG_TRX.CHARGES_FLG                   ,
BKG_TRX.SALESREP_FLG                  ,
BKG_TRX.MISC_FLG                      ,
BKG_TRX.SERVICE_FLG                   ,
BKG_TRX.INTERNATIONAL_DEMO_FLG        ,
BKG_TRX.REPLACEMENT_DEMO_FLG          ,
BKG_TRX.REVENUE_FLG                   ,
BKG_TRX.RMA_FLG                       ,
BKG_TRX.TRADE_IN_AMOUNT               ,
BKG_TRX.DD_COMP_US_NET_PRICE_AMOUNT   ,
BKG_TRX.DD_COMP_US_LIST_PRICE_AMOUNT  ,
BKG_TRX.DD_COMP_US_COST_AMOUNT        ,
BKG_TRX.DD_EXTENDED_QUANTITY          ,
BKG_TRX.DD_COMP_US_HOLD_NET_PRICE_AMT ,
BKG_TRX.DD_COMP_US_HOLD_LIST_PRICE_AMT,
BKG_TRX.DD_COMP_US_HOLD_COST_AMOUNT   ,
BKG_TRX.DD_EXTENDED_HOLD_QUANTITY     ,
BKG_TRX.DD_COMP_US_STANDARD_PRICE_AMT ,
BKG_TRX.WIPS_ORIGINATOR_ID_INT        ,
BKG_TRX.EDW_CREATE_USER               ,
BKG_TRX.EDW_UPDATE_USER               ,
BKG_TRX.EDW_CREATE_DATETIME           ,
CURRENT_TIMESTAMP(0)         AS EDW_UPDATE_DATETIME           ,
BKG_TRX.CONVERSION_RT                 ,
BKG_TRX.CONVERSION_DT                 ,
BKG_TRX.DD_BK_SO_NUMBER_INT           ,
BKG_TRX.DD_CISCO_BOOKED_DTM           ,
BKG_TRX.DD_SALES_ORDER_CATEGORY_TYPE  ,
BKG_TRX.DD_SLS_ORD_OPERATING_UNIT_CD  ,
BKG_TRX.DD_TRX_CURRENCY_CD            ,
BKG_TRX.DV_TRANSACTION_TYPE           ,
BKG_TRX.ADJUSTMENT_DESCR_KEY          ,
BKG_TRX.DV_TRANSACTION_NAME           ,
BKG_TRX.BOOKINGS_SPLIT_PCT            ,
BKG_TRX.DV_REVENUE_RECOGNITION_FLG    ,
BKG_TRX.DV_NET_SPREAD_FLG             ,
BKG_TRX.REVENUE_TRANSFER_KEY          ,
BKG_TRX.DV_ATTRIBUTION_CD             ,
BKG_TRX.DV_PRODUCT_KEY                ,
BKG_TRX.DV_SALES_ORDER_LINE_KEY       ,
BKG_TRX.SK_OFFER_ATTRIBUTION_ID_INT   ,
BKG_TRX.DV_FMV_FLG                    ,
BKG_TRX.RU_SERVICE_CONTRACT_START_DTM ,
BKG_TRX.RU_SERVICE_CONTRACT_END_DTM   ,
BKG_TRX.DV_CONTRACT_DURATION          ,
BKG_TRX.DV_ANNUALIZED_FLG             ,
BKG_TRX.DV_ANNUALIZED_US_NET_AMT      ,
BKG_TRX.DV_MULTIYEAR_US_NET_AMT       ,
BKG_TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY   ,
BKG_TRX.DSV_FLG                       ,
BKG_TRX.DV_SOURCE_ORDER_NUM_INT       ,
BKG_TRX.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY,
BKG_TRX.FISCAL_YEAR_QUARTER_NUMBER_INT,
BKG_TRX.DV_AR_TRX_LINE_KEY            ,
BKG_TRX.XAAS_OFFER_ATRBTN_REV_LINE_KEY,
BKG_TRX.DV_DEAL_ID                    ,
BKG_TRX.TSS_COUNTRY_FACTOR_KEY        ,
BKG_TRX.DV_BKG_GROSS_MGN_AMOUNT       ,
BKG_TRX.DV_BGM_FX_COST_AMOUNT         ,
BKG_TRX.DV_FX_NET_PRICE_AMT           
,BKG_TRX.XCAT_FLG
,BKG_TRX.BK_OFFER_TYPE_NAME
,BKG_TRX.RECURRING_OFFER_FLG
,BKG_TRX.ELA_FLG
,BKG_TRX.DV_LOCAL_EXTND_LIST_PRICE_AMT 
,BKG_TRX.LOCAL_UNIT_LIST_PRICE_AMT     
,BKG_TRX.DV_UNIT_LIST_PRICE_USD_AMT 
,CAST(0.0 AS DECIMAL(18,6))DV_ORDER_VALUE_USD_AMOUNT    
,CAST(0.0 AS DECIMAL(18,6))DV_MTHLY_RCR_REV_TRXL_USD_AMT  
,CAST(0.0 AS DECIMAL(18,6))DV_INCRML_MTHY_RCRR_RV_USD_AMT 
,CAST(0.0 AS DECIMAL(18,6))DV_ANNLZD_MTHY_RCRR_RV_USD_AMT 
,CAST(0.0 AS DECIMAL(18,6))DV_INCRML_ANNL_RCRR_RV_USD_AMT 
,BKG_TRX.DV_BGM_NON_STANDARD_COST_AMT /*added as part product BGM - Q1FY18 release */
,BKG_TRX.POB_TYPE_CD
        ,  '=' AS     ACTION_CODE,
          '=' AS     DML_TYPE
,BKG_TRX.NRS_TRANSITION_FLG
,BKG_TRX.SALES_MOTION_CD /* Added as part of Oct - 2017 rel */
,BKG_TRX.SUMMARY_QUOTE_FLG  /* Added as part of Oct - 2017 rel */
,BKG_TRX.DV_BKG_REBATE_AMT
,BKG_TRX.DV_FX_REBATE_PRICE_AMT
,BKG_TRX.SK_SALES_MOTION_ATTRIB_KEY /* Added as part of SALES FY18 May12Rel */
,BKG_TRX.DD_COMP_US_ORIG_LIST_PRICE
,BKG_TRX.DD_COMP_US_ORIG_EXT_LIST_PRICE
  ,BKG_TRX.DV_INV_DTM
   ,BKG_TRX.DV_COMPENSATION_DTM
,BKG_TRX.BOOKINGS_POLICY_CD
,BKG_TRX.SOURCE_REP_ANNUAL_USD_AMT
  FROM 
     $$STGDB.WI_OFFER_TYPE_RETRO_ERP BKG_TRX
    WHERE NOT EXISTS (SELECT 1 
 FROM $$WORKDB.W_BOOKINGS_MEASURE WBM
 WHERE WBM.BOOKINGS_MEASURE_KEY = BKG_TRX.BOOKINGS_MEASURE_KEY AND 
 WBM.BOOKINGS_PROCESS_DATE= BKG_TRX.BOOKINGS_PROCESS_DATE AND
 WBM.BKGS_MEASURE_TRANS_TYPE_CODE =BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE)


Post SQL : 



Target5 Name : W_BOOKINGS_MEASURE


Pre SQL : 
UPDATE  WBM FROM $$WORKDB.W_BOOKINGS_MEASURE WBM
  ,$$SLSORDVWDB.N_SALES_ORDER_TV NSO
  ,$$COMREFVWDB.N_PRODUCT NP
  SET 
  XCAT_FLG  = (CASE WHEN NSO.XCAT_FLG = 'Y' THEN NSO.XCAT_FLG ELSE     COALESCE(NP.XCAT_FLG,'N' ) END),
  EDW_UPDATE_USER   =  USER,
  EDW_UPDATE_DATETIME = CURRENT_TIMESTAMP(0)
  WHERE NSO.SALES_ORDER_KEY            = WBM.SALES_ORDER_KEY
  AND   NP.ITEM_KEY            = WBM.PRODUCT_KEY
 AND NSO.END_TV_DATETIME= '3500-01-01 00:00:00'
  AND WBM.BKGS_MEASURE_TRANS_TYPE_CODE   ='ERP'
  AND WBM.XCAT_FLG <> (CASE WHEN NSO.XCAT_FLG = 'Y' THEN NSO.XCAT_FLG ELSE     COALESCE(NP.XCAT_FLG,'N' ) END);
  
   
  UPDATE  WBM FROM $$WORKDB.W_BOOKINGS_MEASURE WBM
  ,$$COMREFVWDB.MT_OFFER_TYPE_PRDT_MAP PMAP
  ,$$SLSORDVWDB.N_SALES_ORDER_TV NSO
  SET 
 BK_OFFER_TYPE_NAME = PMAP.BK_OFFER_TYPE_NAME,
  RECURRING_OFFER_FLG = PMAP.RECURRING_OFFER_FLG,		

   ELA_FLG= (CASE  WHEN    WBM.XCAT_FLG   = 'Y' THEN 'Y' ELSE PMAP.ELA_FLG END),
   EDW_UPDATE_USER   =  USER,
  EDW_UPDATE_DATETIME = CURRENT_TIMESTAMP(0)
  WHERE PMAP.PRODUCT_KEY            = WBM.PRODUCT_KEY
  AND   PMAP.DV_PRODUCT_KEY            = WBM.DV_PRODUCT_KEY
  AND PMAP.BK_OFFER_ATTRBTN_TYPE_CD = WBM.DV_ATTRIBUTION_CD
  AND WBM.BKGS_MEASURE_TRANS_TYPE_CODE   ='ERP'
    AND  NSO.SALES_ORDER_KEY=WBM.SALES_ORDER_KEY
 AND NSO.END_TV_DATETIME= '3500-01-01 00:00:00'
 /*Added as part of May21 RO */
 AND  NOT EXISTS 
 (SELECT 1 FROM $$ETLVWDB.EL_RO_CSCC_SO_SRC_NAME EL
 WHERE NSO.BK_SO_SOURCE_NAME= EL.BK_SO_SOURCE_NAME
 AND EL.ACTIVE_IND='Y'
 )
  AND( WBM.BK_OFFER_TYPE_NAME <> PMAP.BK_OFFER_TYPE_NAME
   OR
  WBM.RECURRING_OFFER_FLG <> PMAP.RECURRING_OFFER_FLG
  OR
 WBM.ELA_FLG<> (CASE  WHEN WBM.XCAT_FLG   = 'Y' THEN 'Y'  ELSE PMAP.ELA_FLG END)
   );         

/*Added as part of May21 RO */ 
UPDATE  WBM 
FROM $$WORKDB.W_BOOKINGS_MEASURE WBM,
  (
SELECT  
BKG_TRX.BOOKINGS_MEASURE_KEY,
BKG_TRX.BOOKINGS_PROCESS_DATE,
BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE,
CASE WHEN NOTV.BK_PARENT_OFFER_TYPE_NAME = 'Cisco One' 
THEN  ALLOC_ENT.BK_OFFER_TYPE_NAME ELSE  COALESCE(PMAP.BK_OFFER_TYPE_NAME,'Others') END AS BK_OFFER_TYPE_NAME,
COALESCE(PMAP.RECURRING_OFFER_FLG,'N') AS RECURRING_OFFER_FLG ,
CASE WHEN BKG_TRX.XCAT_FLG = 'Y' THEN 'Y' 
      WHEN NOTV.BK_PARENT_OFFER_TYPE_NAME = 'Cisco One' THEN  ALLOC_ENT.ELA_FLG 
	  ELSE COALESCE(PMAP.ELA_FLG,'N') END AS ELA_FLG 
	  FROM $$WORKDB.W_BOOKINGS_MEASURE BKG_TRX
INNER JOIN 
$$SLSORDVWDB.N_SALES_ORDER_TV NSO
ON BKG_TRX.SALES_ORDER_KEY=NSO.SALES_ORDER_KEY
AND NSO.END_TV_DATETIME= '3500-01-01 00:00:00'

LEFT OUTER JOIN $$STGDB.WI_SOL_OFFER_ATTR_BKGS_ERP_RO  NSOAT 
ON  NSOAT.SK_OFFER_ATTRIBUTION_ID_INT=BKG_TRX.SK_OFFER_ATTRIBUTION_ID_INT

LEFT OUTER JOIN $$COMREFVWDB.MT_OFFER_TYPE_PRDT_MAP ALLOC_ENT               
ON ALLOC_ENT.DV_PRODUCT_KEY = NSOAT.ENTERPRISE_SKU_KEY                        
AND ALLOC_ENT.BK_OFFER_ATTRBTN_TYPE_CD = 'STANDALONE'    

LEFT OUTER JOIN $$COMREFVWDB.N_OFFER_TYPE NOTV
ON  ALLOC_ENT.BK_OFFER_TYPE_NAME=NOTV. BK_OFFER_TYPE_NAME           
 
LEFT OUTER JOIN $$COMREFVWDB.MT_OFFER_TYPE_PRDT_MAP PMAP                           
ON  PMAP.PRODUCT_KEY            = BKG_TRX.PRODUCT_KEY
AND PMAP.DV_PRODUCT_KEY            = BKG_TRX.DV_PRODUCT_KEY
AND PMAP.BK_OFFER_ATTRBTN_TYPE_CD = BKG_TRX.DV_ATTRIBUTION_CD             
        
WHERE  BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP' 
AND   BK_SO_SOURCE_NAME IN (SELECT BK_SO_SOURCE_NAME FROM $$ETLVWDB.EL_RO_CSCC_SO_SRC_NAME WHERE ACTIVE_IND='Y')
)PMAP
SET 
 BK_OFFER_TYPE_NAME = PMAP.BK_OFFER_TYPE_NAME,
  RECURRING_OFFER_FLG = PMAP.RECURRING_OFFER_FLG,
   ELA_FLG= PMAP.ELA_FLG,
   EDW_UPDATE_USER   =  USER,
  EDW_UPDATE_DATETIME = CURRENT_TIMESTAMP(0)
  WHERE 
  WBM.BOOKINGS_MEASURE_KEY = PMAP.BOOKINGS_MEASURE_KEY AND 
  WBM.BOOKINGS_PROCESS_DATE= PMAP.BOOKINGS_PROCESS_DATE AND
  WBM.BKGS_MEASURE_TRANS_TYPE_CODE =PMAP.BKGS_MEASURE_TRANS_TYPE_CODE;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$WORKDB','W_BOOKINGS_MEASURE','D');


Source6 Name : SQ_N_BOOKINGS_MEASURE_CSCC


Pre SQL : 
INSERT INTO $$WORKDB.W_BOOKINGS_MEASURE
(
BOOKINGS_MEASURE_KEY          ,
SALES_ORDER_KEY               ,
SALES_ORDER_LINE_KEY          ,
PRODUCT_KEY                   ,
AR_TRX_LINE_KEY               ,
AR_TRX_KEY                    ,
END_CUSTOMER_KEY              ,
BILL_TO_CUSTOMER_KEY          ,
SHIP_TO_CUSTOMER_KEY          ,
SOLD_TO_CUSTOMER_KEY          ,
DV_END_CUSTOMER_KEY           ,
TRANSACTION_DATETIME          ,
SALES_TERRITORY_KEY           ,
SALES_REP_NUMBER              ,
BOOKINGS_PROCESS_DATE         ,
DV_FISCAL_YEAR_MTH_NUMBER_INT ,
BK_POS_TRANSACTION_ID_INT     ,
BK_SALES_ADJ_LINE_NUMBER_INT  ,
BK_SALES_ADJ_NUMBER_INT       ,
ADJUSTMENT_TYPE_CODE          ,
SALES_CHANNEL_CODE            ,
SALES_CREDIT_TYPE_CODE        ,
IDE_ADJUSTMENT_CODE           ,
ADJUSTMENT_CODE               ,
BKGS_MEASURE_TRANS_TYPE_CODE  ,
CANCELLED_FLG                 ,
CANCEL_CODE                   ,
ACQUISITION_FLG               ,
FORWARD_REVERSE_FLG           ,
DISTRIBUTOR_OFFSET_FLG        ,
CORPORATE_BOOKINGS_FLG        ,
OVERLAY_FLG                   ,
IC_REVENUE_FLG                ,
CHARGES_FLG                   ,
SALESREP_FLG                  ,
MISC_FLG                      ,
SERVICE_FLG                   ,
INTERNATIONAL_DEMO_FLG        ,
REPLACEMENT_DEMO_FLG          ,
REVENUE_FLG                   ,
RMA_FLG                       ,
TRADE_IN_AMOUNT               ,
DD_COMP_US_NET_PRICE_AMOUNT   ,
DD_COMP_US_LIST_PRICE_AMOUNT  ,
DD_COMP_US_COST_AMOUNT        ,
DD_EXTENDED_QUANTITY          ,
DD_COMP_US_HOLD_NET_PRICE_AMT ,
DD_COMP_US_HOLD_LIST_PRICE_AMT,
DD_COMP_US_HOLD_COST_AMOUNT   ,
DD_EXTENDED_HOLD_QUANTITY     ,
DD_COMP_US_STANDARD_PRICE_AMT ,
WIPS_ORIGINATOR_ID_INT        ,
EDW_CREATE_USER               ,
EDW_UPDATE_USER               ,
EDW_CREATE_DATETIME           ,
EDW_UPDATE_DATETIME           ,
CONVERSION_RT                 ,
CONVERSION_DT                 ,
DD_BK_SO_NUMBER_INT           ,
DD_CISCO_BOOKED_DTM           ,
DD_SALES_ORDER_CATEGORY_TYPE  ,
DD_SLS_ORD_OPERATING_UNIT_CD  ,
DD_TRX_CURRENCY_CD            ,
DV_TRANSACTION_TYPE           ,
ADJUSTMENT_DESCR_KEY          ,
DV_TRANSACTION_NAME           ,
BOOKINGS_SPLIT_PCT            ,
DV_REVENUE_RECOGNITION_FLG    ,
DV_NET_SPREAD_FLG             ,
REVENUE_TRANSFER_KEY          ,
DV_ATTRIBUTION_CD             ,
DV_PRODUCT_KEY                ,
DV_SALES_ORDER_LINE_KEY       ,
SK_OFFER_ATTRIBUTION_ID_INT   ,
DV_FMV_FLG                    ,
RU_SERVICE_CONTRACT_START_DTM ,
RU_SERVICE_CONTRACT_END_DTM   ,
DV_CONTRACT_DURATION          ,
DV_ANNUALIZED_FLG             ,
DV_ANNUALIZED_US_NET_AMT      ,
DV_MULTIYEAR_US_NET_AMT       ,
SO_SBSCRPTN_ITM_SLS_TRX_KEY   ,
DSV_FLG                       ,
DV_SOURCE_ORDER_NUM_INT       ,
DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY,
FISCAL_YEAR_QUARTER_NUMBER_INT,
DV_AR_TRX_LINE_KEY            ,
XAAS_OFFER_ATRBTN_REV_LINE_KEY,
DV_DEAL_ID                    ,
TSS_COUNTRY_FACTOR_KEY        ,
DV_BKG_GROSS_MGN_AMOUNT       ,
DV_BGM_FX_COST_AMOUNT         ,
DV_FX_NET_PRICE_AMT           ,
XCAT_FLG                      ,
BK_OFFER_TYPE_NAME            ,
RECURRING_OFFER_FLG           ,
ELA_FLG                       ,
DV_LOCAL_EXTND_LIST_PRICE_AMT ,
LOCAL_UNIT_LIST_PRICE_AMT     ,
DV_UNIT_LIST_PRICE_USD_AMT    ,
DV_ORDER_VALUE_USD_AMOUNT   ,
DV_MTHLY_RCR_REV_TRXL_USD_AMT ,
DV_INCRML_MTHY_RCRR_RV_USD_AMT,
DV_ANNLZD_MTHY_RCRR_RV_USD_AMT,
DV_INCRML_ANNL_RCRR_RV_USD_AMT,
ACTION_CODE                   ,
DML_TYPE,
POB_TYPE_CD,
NRS_TRANSITION_FLG            ,
SALES_MOTION_CD               ,
SUMMARY_QUOTE_FLG      ,
DV_BKG_REBATE_AMT,
DV_FX_REBATE_PRICE_AMT     ,
SK_SALES_MOTION_ATTRIB_KEY, /* Added as part of SALES FY18 May12Rel */           
DD_COMP_US_ORIG_LIST_PRICE,
DD_COMP_US_ORIG_EXT_LIST_PRICE
,DV_INV_DTM
,DV_COMPENSATION_DTM
,BOOKINGS_POLICY_CD	 	
,SOURCE_REP_ANNUAL_USD_AMT
 )
SELECT
BKG_TRX.BOOKINGS_MEASURE_KEY          ,
 BKG_TRX.SALES_ORDER_KEY               ,
 BKG_TRX.SALES_ORDER_LINE_KEY          ,
 BKG_TRX.PRODUCT_KEY                   ,
 BKG_TRX.AR_TRX_LINE_KEY               ,
 BKG_TRX.AR_TRX_KEY                    ,
 BKG_TRX.END_CUSTOMER_KEY              ,
 BKG_TRX.BILL_TO_CUSTOMER_KEY          ,
 BKG_TRX.SHIP_TO_CUSTOMER_KEY          ,
 BKG_TRX.SOLD_TO_CUSTOMER_KEY          ,
 BKG_TRX.DV_END_CUSTOMER_KEY           ,
 BKG_TRX.TRANSACTION_DATETIME          ,
 BKG_TRX.SALES_TERRITORY_KEY           ,
 BKG_TRX.SALES_REP_NUMBER              ,
 BKG_TRX.BOOKINGS_PROCESS_DATE         ,
 BKG_TRX.DV_FISCAL_YEAR_MTH_NUMBER_INT ,
 BKG_TRX.BK_POS_TRANSACTION_ID_INT     ,
 BKG_TRX.BK_SALES_ADJ_LINE_NUMBER_INT  ,
 BKG_TRX.BK_SALES_ADJ_NUMBER_INT       ,
 BKG_TRX.ADJUSTMENT_TYPE_CODE          ,
 BKG_TRX.SALES_CHANNEL_CODE            ,
 BKG_TRX.SALES_CREDIT_TYPE_CODE        ,
 BKG_TRX.IDE_ADJUSTMENT_CODE           ,
 BKG_TRX.ADJUSTMENT_CODE               ,
 BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE  ,
 BKG_TRX.CANCELLED_FLG                 ,
 BKG_TRX.CANCEL_CODE                   ,
 BKG_TRX.ACQUISITION_FLG               ,
 BKG_TRX.FORWARD_REVERSE_FLG           ,
 BKG_TRX.DISTRIBUTOR_OFFSET_FLG        ,
 BKG_TRX.CORPORATE_BOOKINGS_FLG        ,
 BKG_TRX.OVERLAY_FLG                   ,
 BKG_TRX.IC_REVENUE_FLG                ,
 BKG_TRX.CHARGES_FLG                   ,
 BKG_TRX.SALESREP_FLG                  ,
 BKG_TRX.MISC_FLG                      ,
 BKG_TRX.SERVICE_FLG                   ,
 BKG_TRX.INTERNATIONAL_DEMO_FLG        ,
 BKG_TRX.REPLACEMENT_DEMO_FLG          ,
 BKG_TRX.REVENUE_FLG                   ,
 BKG_TRX.RMA_FLG                       ,
 BKG_TRX.TRADE_IN_AMOUNT               ,
 BKG_TRX.DD_COMP_US_NET_PRICE_AMOUNT   ,
 BKG_TRX.DD_COMP_US_LIST_PRICE_AMOUNT  ,
 BKG_TRX.DD_COMP_US_COST_AMOUNT        ,
 BKG_TRX.DD_EXTENDED_QUANTITY          ,
 BKG_TRX.DD_COMP_US_HOLD_NET_PRICE_AMT ,
 BKG_TRX.DD_COMP_US_HOLD_LIST_PRICE_AMT,
 BKG_TRX.DD_COMP_US_HOLD_COST_AMOUNT   ,
 BKG_TRX.DD_EXTENDED_HOLD_QUANTITY     ,
 BKG_TRX.DD_COMP_US_STANDARD_PRICE_AMT ,
 BKG_TRX.WIPS_ORIGINATOR_ID_INT        ,
 BKG_TRX.EDW_CREATE_USER               ,
 BKG_TRX.EDW_UPDATE_USER               ,
 BKG_TRX.EDW_CREATE_DATETIME           ,
 CURRENT_TIMESTAMP(0)         AS EDW_UPDATE_DATETIME  ,
 BKG_TRX.CONVERSION_RT                 ,
 BKG_TRX.CONVERSION_DT                 ,
 BKG_TRX.DD_BK_SO_NUMBER_INT           ,
 BKG_TRX.DD_CISCO_BOOKED_DTM           ,
 BKG_TRX.DD_SALES_ORDER_CATEGORY_TYPE  ,
 BKG_TRX.DD_SLS_ORD_OPERATING_UNIT_CD  ,
 BKG_TRX.DD_TRX_CURRENCY_CD            ,
 BKG_TRX.DV_TRANSACTION_TYPE           ,
 BKG_TRX.ADJUSTMENT_DESCR_KEY          ,
 BKG_TRX.DV_TRANSACTION_NAME           ,
 BKG_TRX.BOOKINGS_SPLIT_PCT            ,
 BKG_TRX.DV_REVENUE_RECOGNITION_FLG    ,
 BKG_TRX.DV_NET_SPREAD_FLG             ,
 BKG_TRX.REVENUE_TRANSFER_KEY          ,
 BKG_TRX.DV_ATTRIBUTION_CD             ,
 BKG_TRX.DV_PRODUCT_KEY                ,
 BKG_TRX.DV_SALES_ORDER_LINE_KEY       ,
 BKG_TRX.SK_OFFER_ATTRIBUTION_ID_INT   ,
 BKG_TRX.DV_FMV_FLG                    ,
 BKG_TRX.RU_SERVICE_CONTRACT_START_DTM ,
 BKG_TRX.RU_SERVICE_CONTRACT_END_DTM   ,
 BKG_TRX.DV_CONTRACT_DURATION          ,
 BKG_TRX.DV_ANNUALIZED_FLG             ,
 BKG_TRX.DV_ANNUALIZED_US_NET_AMT      ,
 BKG_TRX.DV_MULTIYEAR_US_NET_AMT       ,
 BKG_TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY   ,
 BKG_TRX.DSV_FLG                       ,
 BKG_TRX.DV_SOURCE_ORDER_NUM_INT       ,
 BKG_TRX.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY,
 BKG_TRX.FISCAL_YEAR_QUARTER_NUMBER_INT,
 BKG_TRX.DV_AR_TRX_LINE_KEY            ,
 BKG_TRX.XAAS_OFFER_ATRBTN_REV_LINE_KEY,
 BKG_TRX.DV_DEAL_ID                    ,
 BKG_TRX.TSS_COUNTRY_FACTOR_KEY        ,
 BKG_TRX.DV_BKG_GROSS_MGN_AMOUNT       ,
 BKG_TRX.DV_BGM_FX_COST_AMOUNT         ,
 BKG_TRX.DV_FX_NET_PRICE_AMT   ,
 BKG_TRX.XCAT_FLG,
CASE WHEN  NOTV.BK_PARENT_OFFER_TYPE_NAME = 'Cisco One' 
THEN  ALLOC_ENT.BK_OFFER_TYPE_NAME ELSE  COALESCE(PMAP.BK_OFFER_TYPE_NAME,'Others') END AS BK_OFFER_TYPE_NAME_NEW,
 COALESCE(PMAP.RECURRING_OFFER_FLG,'N') AS RECURRING_OFFER_FLG_NEW,
CASE WHEN BKG_TRX.XCAT_FLG = 'Y' THEN 'Y' 
      WHEN NOTV.BK_PARENT_OFFER_TYPE_NAME = 'Cisco One' THEN  ALLOC_ENT.ELA_FLG 
   ELSE COALESCE(PMAP.ELA_FLG,'N') END AS ELA_FLG_NEW
 ,BKG_TRX.DV_LOCAL_EXTND_LIST_PRICE_AMT 
,BKG_TRX.LOCAL_UNIT_LIST_PRICE_AMT     
,BKG_TRX.DV_UNIT_LIST_PRICE_USD_AMT 
,CAST(0.0 AS DECIMAL(18,6))DV_ORDER_VALUE_USD_AMOUNT    
,CAST(0.0 AS DECIMAL(18,6))DV_MTHLY_RCR_REV_TRXL_USD_AMT  
,CAST(0.0 AS DECIMAL(18,6))DV_INCRML_MTHY_RCRR_RV_USD_AMT 
,CAST(0.0 AS DECIMAL(18,6))DV_ANNLZD_MTHY_RCRR_RV_USD_AMT 
,CAST(0.0 AS DECIMAL(18,6))DV_INCRML_ANNL_RCRR_RV_USD_AMT 
,'=' AS     ACTION_CODE
,'=' AS     DML_TYPE
,POB_TYPE_CD 
,NRS_TRANSITION_FLG   ,
SALES_MOTION_CD               ,
SUMMARY_QUOTE_FLG       ,
BKG_TRX.DV_BKG_REBATE_AMT   ,
BKG_TRX.DV_FX_REBATE_PRICE_AMT         ,
BKG_TRX.SK_SALES_MOTION_ATTRIB_KEY, /* Added as part of SALES FY18 May12Rel */
BKG_TRX.DD_COMP_US_ORIG_LIST_PRICE,
BKG_TRX.DD_COMP_US_ORIG_EXT_LIST_PRICE
,BKG_TRX.DV_INV_DTM
,BKG_TRX.DV_COMPENSATION_DTM
,BKG_TRX.BOOKINGS_POLICY_CD	 	
,BKG_TRX.SOURCE_REP_ANNUAL_USD_AMT
FROM 
$$SLSORDVWDB.N_BOOKINGS_MEASURE BKG_TRX
INNER JOIN
    (
    SEL FISCAL_YEAR_MONTH_INT FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR 
    WHERE 1=1
    AND FISCAL_YEAR_AGE BETWEEN 0 AND (SELECT CASE WHEN FISCAL_QUARTER_NUMBER_INT =1 THEN 4 ELSE 3 END 
    FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR  WHERE FISCAL_MONTH_AGE=0 )
    AND FISCAL_MONTH_AGE >=0
    ) CAL
    ON BKG_TRX.DV_FISCAL_YEAR_MTH_NUMBER_INT=CAL.FISCAL_YEAR_MONTH_INT
INNER JOIN 
$$SLSORDVWDB.N_SALES_ORDER_TV NSO
ON BKG_TRX.SALES_ORDER_KEY=NSO.SALES_ORDER_KEY
AND NSO.END_TV_DATETIME= '3500-01-01 00:00:00'

INNER JOIN $$STGDB.WI_SOL_OFFER_ATTR_BKGS_ERP_RO NSOAT 
ON  NSOAT.SK_OFFER_ATTRIBUTION_ID_INT=BKG_TRX.SK_OFFER_ATTRIBUTION_ID_INT

INNER JOIN $$COMREFVWDB.MT_OFFER_TYPE_PRDT_MAP ALLOC_ENT                       
ON ALLOC_ENT.DV_PRODUCT_KEY = NSOAT.ENTERPRISE_SKU_KEY                        
AND ALLOC_ENT.BK_OFFER_ATTRBTN_TYPE_CD = 'STANDALONE'    

INNER JOIN $$COMREFVWDB.N_OFFER_TYPE NOTV
ON  ALLOC_ENT.BK_OFFER_TYPE_NAME=NOTV. BK_OFFER_TYPE_NAME
AND NOTV.BK_PARENT_OFFER_TYPE_NAME = 'Cisco One'

LEFT OUTER JOIN $$COMREFVWDB.MT_OFFER_TYPE_PRDT_MAP PMAP                    
ON  PMAP.PRODUCT_KEY            = BKG_TRX.PRODUCT_KEY
AND PMAP.DV_PRODUCT_KEY            = BKG_TRX.DV_PRODUCT_KEY
AND PMAP.BK_OFFER_ATTRBTN_TYPE_CD = BKG_TRX.DV_ATTRIBUTION_CD   
        
WHERE  BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP' 
AND   BK_SO_SOURCE_NAME IN (SELECT BK_SO_SOURCE_NAME FROM $$ETLVWDB.EL_RO_CSCC_SO_SRC_NAME WHERE ACTIVE_IND='Y') 
AND NSOAT.EDW_UPDATE_DTM >= (SELECT LAST_EXTRACT_DATE FROM $$ETLVWDB.CTL_ETL_LAST_EXTRACT_DATES
WHERE JOB_STREAM_ID='wf_N_BOOKINGS_MEASURE' AND TABLE_NAME ='N_BOOKINGS_MEASURE_ERP') 
AND ( BKG_TRX.BK_OFFER_TYPE_NAME <> BK_OFFER_TYPE_NAME_NEW
OR BKG_TRX.ELA_FLG <> ELA_FLG_NEW
OR BKG_TRX.RECURRING_OFFER_FLG <> RECURRING_OFFER_FLG_NEW) 
AND NOT EXISTS  (SELECT 1 FROM $$WORKDB.W_BOOKINGS_MEASURE WI 
  WHERE WI.BOOKINGS_MEASURE_KEY = BKG_TRX.BOOKINGS_MEASURE_KEY
   AND WI.BOOKINGS_PROCESS_DATE= BKG_TRX.BOOKINGS_PROCESS_DATE
   AND WI.BKGS_MEASURE_TRANS_TYPE_CODE =BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE);


SQL Query : 
SELECT	   BKG_TRX.BOOKINGS_MEASURE_KEY          ,
		 BKG_TRX.SALES_ORDER_KEY               ,
         BKG_TRX.SALES_ORDER_LINE_KEY          ,
		 BKG_TRX.PRODUCT_KEY                   ,
         BKG_TRX.AR_TRX_LINE_KEY               ,
		 BKG_TRX.AR_TRX_KEY                    ,
         BKG_TRX.END_CUSTOMER_KEY              ,
		 BKG_TRX.BILL_TO_CUSTOMER_KEY          ,
         BKG_TRX.SHIP_TO_CUSTOMER_KEY          ,
		 BKG_TRX.SOLD_TO_CUSTOMER_KEY          ,
         BKG_TRX.DV_END_CUSTOMER_KEY           ,
		 BKG_TRX.TRANSACTION_DATETIME          ,
         BKG_TRX.SALES_TERRITORY_KEY           ,
		 BKG_TRX.SALES_REP_NUMBER              ,
         BKG_TRX.BOOKINGS_PROCESS_DATE         ,
		 BKG_TRX.DV_FISCAL_YEAR_MTH_NUMBER_INT ,
         BKG_TRX.BK_POS_TRANSACTION_ID_INT     ,
		 BKG_TRX.BK_SALES_ADJ_LINE_NUMBER_INT  ,
         BKG_TRX.BK_SALES_ADJ_NUMBER_INT       ,
		 BKG_TRX.ADJUSTMENT_TYPE_CODE          ,
         BKG_TRX.SALES_CHANNEL_CODE            ,
		 BKG_TRX.SALES_CREDIT_TYPE_CODE        ,
         BKG_TRX.IDE_ADJUSTMENT_CODE           ,
		 BKG_TRX.ADJUSTMENT_CODE               ,
         BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE  ,
		 BKG_TRX.CANCELLED_FLG                 ,
         BKG_TRX.CANCEL_CODE                   ,
		 BKG_TRX.ACQUISITION_FLG               ,
         BKG_TRX.FORWARD_REVERSE_FLG           ,
		 BKG_TRX.DISTRIBUTOR_OFFSET_FLG        ,
         BKG_TRX.CORPORATE_BOOKINGS_FLG        ,
		 BKG_TRX.OVERLAY_FLG                   ,
         BKG_TRX.IC_REVENUE_FLG                ,
		 BKG_TRX.CHARGES_FLG                   ,
         BKG_TRX.SALESREP_FLG                  ,
		 BKG_TRX.MISC_FLG                      ,
         BKG_TRX.SERVICE_FLG                   ,
		 BKG_TRX.INTERNATIONAL_DEMO_FLG        ,
         BKG_TRX.REPLACEMENT_DEMO_FLG          ,
		 BKG_TRX.REVENUE_FLG                   ,
         BKG_TRX.RMA_FLG                       ,
		 BKG_TRX.TRADE_IN_AMOUNT               ,
         BKG_TRX.DD_COMP_US_NET_PRICE_AMOUNT   ,
		 BKG_TRX.DD_COMP_US_LIST_PRICE_AMOUNT  ,
         BKG_TRX.DD_COMP_US_COST_AMOUNT        ,
		 BKG_TRX.DD_EXTENDED_QUANTITY          ,
         BKG_TRX.DD_COMP_US_HOLD_NET_PRICE_AMT ,
		 BKG_TRX.DD_COMP_US_HOLD_LIST_PRICE_AMT,
         BKG_TRX.DD_COMP_US_HOLD_COST_AMOUNT   ,
		 BKG_TRX.DD_EXTENDED_HOLD_QUANTITY     ,
         BKG_TRX.DD_COMP_US_STANDARD_PRICE_AMT ,
		 BKG_TRX.WIPS_ORIGINATOR_ID_INT        ,
         BKG_TRX.EDW_CREATE_USER               ,
		 BKG_TRX.EDW_UPDATE_USER               ,
         BKG_TRX.EDW_CREATE_DATETIME           ,
		 CURRENT_TIMESTAMP(0)         AS EDW_UPDATE_DATETIME  ,
         BKG_TRX.CONVERSION_RT                 ,
		 BKG_TRX.CONVERSION_DT                 ,
         BKG_TRX.DD_BK_SO_NUMBER_INT           ,
		 BKG_TRX.DD_CISCO_BOOKED_DTM           ,
         BKG_TRX.DD_SALES_ORDER_CATEGORY_TYPE  ,
		 BKG_TRX.DD_SLS_ORD_OPERATING_UNIT_CD  ,
         BKG_TRX.DD_TRX_CURRENCY_CD            ,
		 BKG_TRX.DV_TRANSACTION_TYPE           ,
         BKG_TRX.ADJUSTMENT_DESCR_KEY          ,
		 BKG_TRX.DV_TRANSACTION_NAME           ,
         BKG_TRX.BOOKINGS_SPLIT_PCT            ,
		 BKG_TRX.DV_REVENUE_RECOGNITION_FLG    ,
         BKG_TRX.DV_NET_SPREAD_FLG             ,
		 BKG_TRX.REVENUE_TRANSFER_KEY          ,
         BKG_TRX.DV_ATTRIBUTION_CD             ,
		 BKG_TRX.DV_PRODUCT_KEY                ,
         BKG_TRX.DV_SALES_ORDER_LINE_KEY       ,
		 BKG_TRX.SK_OFFER_ATTRIBUTION_ID_INT   ,
         BKG_TRX.DV_FMV_FLG                    ,
		 BKG_TRX.RU_SERVICE_CONTRACT_START_DTM ,
         BKG_TRX.RU_SERVICE_CONTRACT_END_DTM   ,
		 BKG_TRX.DV_CONTRACT_DURATION          ,
         BKG_TRX.DV_ANNUALIZED_FLG             ,
		 BKG_TRX.DV_ANNUALIZED_US_NET_AMT      ,
         BKG_TRX.DV_MULTIYEAR_US_NET_AMT       ,
		 BKG_TRX.SO_SBSCRPTN_ITM_SLS_TRX_KEY   ,
         BKG_TRX.DSV_FLG                       ,
		 BKG_TRX.DV_SOURCE_ORDER_NUM_INT       ,
         BKG_TRX.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY,
		 BKG_TRX.FISCAL_YEAR_QUARTER_NUMBER_INT,
         BKG_TRX.DV_AR_TRX_LINE_KEY            ,
		 BKG_TRX.XAAS_OFFER_ATRBTN_REV_LINE_KEY,
         BKG_TRX.DV_DEAL_ID                    ,
		 BKG_TRX.TSS_COUNTRY_FACTOR_KEY        ,
         BKG_TRX.DV_BKG_GROSS_MGN_AMOUNT       ,
		 BKG_TRX.DV_BGM_FX_COST_AMOUNT         ,
         BKG_TRX.DV_FX_NET_PRICE_AMT   ,
		BKG_TRX.XCAT_FLG ,  
		CASE    
    WHEN  ALLOC_ENT.BK_PARENT_OFFER_TYPE_NAME = 'Cisco One'  THEN  ALLOC_ENT.BK_OFFER_TYPE_NAME 
    ELSE  PMAP.BK_OFFER_TYPE_NAME 
		END    AS BK_OFFER_TYPE_NAME_NEW,  PMAP.RECURRING_OFFER_FLG AS RECURRING_OFFER_FLG_NEW ,
         CASE 
    WHEN BKG_TRX.XCAT_FLG = 'Y' THEN 'Y'        
    WHEN  ALLOC_ENT.BK_PARENT_OFFER_TYPE_NAME = 'Cisco One' THEN  ALLOC_ENT.ELA_FLG        
    ELSE PMAP.ELA_FLG 
		END    AS ELA_FLG_NEW  ,BKG_TRX.DV_LOCAL_EXTND_LIST_PRICE_AMT  ,
		BKG_TRX.LOCAL_UNIT_LIST_PRICE_AMT      ,
        BKG_TRX.DV_UNIT_LIST_PRICE_USD_AMT  ,
		CAST(0.0 AS DECIMAL(18,6))DV_ORDER_VALUE_USD_AMOUNT ,
		CAST(0.0 AS DECIMAL(18,6))DV_MTHLY_RCR_REV_TRXL_USD_AMT   ,
        CAST(0.0 AS DECIMAL(18,6))DV_INCRML_MTHY_RCRR_RV_USD_AMT  ,
		CAST(0.0 AS DECIMAL(18,
        6))DV_ANNLZD_MTHY_RCRR_RV_USD_AMT  ,
		CAST(0.0 AS DECIMAL(18,6))DV_INCRML_ANNL_RCRR_RV_USD_AMT ,
        BKG_TRX.DV_PURCHASE_ADJ_DSCNT_USD_AMT  ,
		BKG_TRX.DV_BGM_NON_STANDARD_COST_AMT  ,
        BKG_TRX.POB_TYPE_CD ,
		'=' AS     ACTION_CODE ,'=' AS     DML_TYPE ,
        BKG_TRX.NRS_TRANSITION_FLG ,
		BKG_TRX.SALES_MOTION_CD  ,BKG_TRX.SUMMARY_QUOTE_FLG   ,
        BKG_TRX.DV_BKG_REBATE_AMT ,
		BKG_TRX.DV_FX_REBATE_PRICE_AMT, BKG_TRX.SK_SALES_MOTION_ATTRIB_KEY  ,
        BKG_TRX.DD_COMP_US_ORIG_LIST_PRICE ,BKG_TRX.DD_COMP_US_ORIG_EXT_LIST_PRICE,
        BKG_TRX.DV_INV_DTM, BKG_TRX.DV_COMPENSATION_DTM 
		,BKG_TRX.BOOKINGS_POLICY_CD
       ,BKG_TRX.SOURCE_REP_ANNUAL_USD_AMT
FROM	    $$SLSORDVWDB.N_BOOKINGS_MEASURE BKG_TRX 
INNER JOIN                        (                 
	SELECT	   CALENDAR_DATE
	FROM	   $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR                  
	WHERE	   1=1                 
	    AND FISCAL_YEAR_AGE BETWEEN 0 AND (
		SELECT	   
				CASE    
		    WHEN FISCAL_QUARTER_NUMBER_INT =1 THEN 4 
		    ELSE 3 
				END                     
		FROM	   $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR  
		WHERE	   FISCAL_MONTH_AGE=0 )                 
	    AND FISCAL_MONTH_AGE >=0                 ) CAL                 
    ON BKG_TRX.BOOKINGS_PROCESS_DATE    =CAL.CALENDAR_DATE
    
    INNER JOIN  $$SLSORDVWDB.N_SALES_ORDER_TV NSO 
    ON BKG_TRX.SALES_ORDER_KEY=NSO.SALES_ORDER_KEY 
    AND NSO.END_TV_DATETIME= '3500-01-01 00:00:00'  
    
    /*LEFT OUTER JOIN     $$STGDB.WI_SOL_OFFER_ATTR_BKGS_ERP_RO  NSOAT  
    ON  NSOAT.SK_OFFER_ATTRIBUTION_ID_INT=BKG_TRX.SK_OFFER_ATTRIBUTION_ID_INT  
    */
    LEFT OUTER JOIN 
    ( 
	SELECT	  SK_OFFER_ATTRIBUTION_ID_INT, ALLOC_ENT.BK_OFFER_TYPE_NAME,
			ELA_FLG,BK_PARENT_OFFER_TYPE_NAME
	    FROM	$$COMREFVWDB.MT_OFFER_TYPE_PRDT_MAP  ALLOC_ENT                
	    INNER JOIN
	    $$STGDB.WI_SOL_OFFER_ATTR_BKGS_ERP_RO  NSOAT  
	    ON  ALLOC_ENT.DV_PRODUCT_KEY = NSOAT.ENTERPRISE_SKU_KEY    
	    INNER JOIN 
	     $$COMREFVWDB.N_OFFER_TYPE NOTV 
	    ON  ALLOC_ENT.BK_OFFER_TYPE_NAME=NOTV. BK_OFFER_TYPE_NAME  
	    WHERE	 BK_OFFER_ATTRBTN_TYPE_CD = 'STANDALONE'    
	    AND BK_PARENT_OFFER_TYPE_NAME = 'Cisco One' 
	    GROUP BY 1,2,3,4)ALLOC_ENT                        
           ON   ALLOC_ENT.SK_OFFER_ATTRIBUTION_ID_INT=BKG_TRX.SK_OFFER_ATTRIBUTION_ID_INT             
    
    
    /*LEFT OUTER JOIN $$COMREFVWDB.N_OFFER_TYPE NOTV 
    ON  ALLOC_ENT.BK_OFFER_TYPE_NAME=NOTV. BK_OFFER_TYPE_NAME            */  
    
    INNER JOIN   $$COMREFVWDB.MT_OFFER_TYPE_PRDT_MAP PMAP                            
    ON  PMAP.PRODUCT_KEY            = BKG_TRX.PRODUCT_KEY 
    AND PMAP.DV_PRODUCT_KEY            = BKG_TRX.DV_PRODUCT_KEY 
    AND PMAP.BK_OFFER_ATTRBTN_TYPE_CD = BKG_TRX.DV_ATTRIBUTION_CD                       
WHERE	    BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE = 'ERP'  
    AND   BK_SO_SOURCE_NAME IN (
	SELECT	   BK_SO_SOURCE_NAME 
	FROM	   $$ETLVWDB.EL_RO_CSCC_SO_SRC_NAME 
	WHERE	   ACTIVE_IND='Y')  --- Commenting as part of performance change 13/04/20
    AND ( BKG_TRX.BK_OFFER_TYPE_NAME <> BK_OFFER_TYPE_NAME_NEW 
    OR BKG_TRX.ELA_FLG <> ELA_FLG_NEW 
    OR BKG_TRX.RECURRING_OFFER_FLG <> RECURRING_OFFER_FLG_NEW ) 
    AND NOT EXISTS  (
	SELECT	   1 
	FROM	   $$WORKDB.W_BOOKINGS_MEASURE  WI    
	WHERE	   WI.BOOKINGS_MEASURE_KEY = BKG_TRX.BOOKINGS_MEASURE_KEY    
	    AND WI.BOOKINGS_PROCESS_DATE= BKG_TRX.BOOKINGS_PROCESS_DATE    
	    AND WI.BKGS_MEASURE_TRANS_TYPE_CODE =BKG_TRX.BKGS_MEASURE_TRANS_TYPE_CODE)


Post SQL : 



Target6 Name : W_BOOKINGS_MEASURE3


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$WORKDB','W_BOOKINGS_MEASURE','D');