


Source1 Name : SQ_WI_OPL_XXGCO_RTR_ATTRIBUTION


Pre SQL : 



SQL Query : 
SELECT
  ST.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
  ST.DEAL_QUOTE_LINE_KEY,
  ST.SK_RTR_ATTRIBUTION_ID,
  ST.SALES_ORDER_LINE_KEY,
  ST.ATTR_PRDT_KEY,
  ST.BK_QUOTE_NUM,
  ST.BK_SRC_EFFECTIVE_START_DT,
  ST.SRC_EFFECTIVE_END_DT,
  ST.COVERED_PRDT_KEY,
  ST.ATTR_PRDT_QTY,
  ST.ATTR_PCT,
  ST.ATTR_NET_PRICE_LOCAL_AMT,
  ST.ATTR_EXTD_PRICE_LOCAL_AMT,
  ST.SALES_MOTION_CD,
  ST.SALES_MOTION_CONTEXT_NAME,
  ST.SRC_CREATED_DTM,
  ST.DV_SRC_CREATED_DT,
  ST.SRC_CREATED_CSCO_WRKR_PRTY_KEY,
  ST.SRC_LAST_UPDATED_DTM,
  ST.DV_SRC_LAST_UPDATED_DT,
  ST.SRC_LST_UPD_CSCO_WRKR_PRTY_KEY,
  ST.ERP_CUST_ACCT_LOC_KEY,
  ST.AS_TS_CD,
  ST.SK_LINE_REF_NUM,
  ST.BK_AS_ARCHITECTURE_NAME,
  ST.BK_TECH_GROUP_ID,
  ST.BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
  ST.TRANSACTION_CR_PARTY_KEY,
  ST.SK_ERP_BKGS_TRX_ID,
  ST.SK_RENEW_CONTRACT_LINE_ID,
  ST.SK_AS_PARENT_INVENTORY_ITEM_ID,
  ST.ITEM_CATEGORY_NAME,
  ST.ERP_TRX_VERSION_INT,
  ST.SS_CD,
  ST.SK_ATTRIBUTION_ID_INT,
  CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM,
  USER  EDW_CREATE_USER,
  CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM,
  USER EDW_UPDATE_USER, 
  ST.START_TV_DTM,
  CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)) AS END_TV_DTM,
 COALESCE(ATTR_PRDT_CLASS_NAME,'UNKNOWN') AS ATTR_PRDT_CLASS_NAME,
 ST.HQ_CR_PRTY_KEY,
 ST.RENEWAL_REF_ID,
 ST.RENEWAL_REF_CD,
 ST.SMR_TAGGING_FAILURE_RSN_CD,
 ST.SALES_MOTION_TIMING_CD,
 ST.MANUAL_OVERRIDE_ROLE,           
 ST.REQUESTING_CSCO_WRKR_PRTY_KEY,                       
 ST.SLS_MTN_CORRECTION_CASE_NUM,                   
 ST.SLS_MTN_CORRECTION_CMNT, 
 'N' ACTION_CODE,
 'I' DML_TYPE
  FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIBUTION ST
   WHERE  NOT EXISTS (SELECT 1 FROM  $$SLSORDVWDB.N_ATTR_PRDT_AS_NEW_OR_RNWL_TV N_ATTR_TV
                WHERE N_ATTR_TV.SK_ERP_BKGS_TRX_ID = ST.SK_ERP_BKGS_TRX_ID
       AND N_ATTR_TV.ERP_TRX_VERSION_INT = ST.ERP_TRX_VERSION_INT
  AND N_ATTR_TV.END_TV_DTM = '3500-01-01 00:00:00')


Post SQL : 



Target1 Name : W_ATTR_PRDT_AS_NEW_OR_RNWL1


Pre SQL : 
DELETE FROM $$WORKDB.W_ATTR_PRDT_AS_NEW_OR_RNWL ALL;


Post SQL : 
INSERT INTO $$WORKDB.W_ATTR_PRDT_AS_NEW_OR_RNWL
SELECT
  ST.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
  ST.DEAL_QUOTE_LINE_KEY,
  ST.SK_RTR_ATTRIBUTION_ID,
  ST.SALES_ORDER_LINE_KEY,
  ST.ATTR_PRDT_KEY,
  ST.BK_QUOTE_NUM,
  ST.BK_SRC_EFFECTIVE_START_DT,
  ST.SRC_EFFECTIVE_END_DT,
  ST.COVERED_PRDT_KEY,
  ST.ATTR_PRDT_QTY,
  ST.ATTR_PCT,
  ST.ATTR_NET_PRICE_LOCAL_AMT,
  ST.ATTR_EXTD_PRICE_LOCAL_AMT,
  ST.SALES_MOTION_CD,
  ST.SALES_MOTION_CONTEXT_NAME,
  ST.SRC_CREATED_DTM,
  ST.DV_SRC_CREATED_DT,
  ST.SRC_CREATED_CSCO_WRKR_PRTY_KEY,
  ST.SRC_LAST_UPDATED_DTM,
  ST.DV_SRC_LAST_UPDATED_DT,
  ST.SRC_LST_UPD_CSCO_WRKR_PRTY_KEY,
  ST.ERP_CUST_ACCT_LOC_KEY,
  ST.AS_TS_CD,
  ST.SK_LINE_REF_NUM,
  ST.BK_AS_ARCHITECTURE_NAME,
  ST.BK_TECH_GROUP_ID,
  ST.BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
  ST.TRANSACTION_CR_PARTY_KEY,
  ST.SK_ERP_BKGS_TRX_ID,
  ST.SK_RENEW_CONTRACT_LINE_ID,
  ST.SK_AS_PARENT_INVENTORY_ITEM_ID,
  ST.ITEM_CATEGORY_NAME,
  ST.ERP_TRX_VERSION_INT,
  ST.SS_CD,
  ST.SK_ATTRIBUTION_ID_INT,
  CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM,
  USER  EDW_CREATE_USER,
  CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM,
  USER EDW_UPDATE_USER, 
  ST.START_TV_DTM,
  CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)) AS END_TV_DTM,
 COALESCE(ATTR_PRDT_CLASS_NAME,'UNKNOWN') AS ATTR_PRDT_CLASS_NAME,
 ST.HQ_CR_PRTY_KEY,
 ST.RENEWAL_REF_ID,
 ST.RENEWAL_REF_CD,
 ST.SMR_TAGGING_FAILURE_RSN_CD,
 ST.SALES_MOTION_TIMING_CD,
 ST.MANUAL_OVERRIDE_ROLE,           
 ST.REQUESTING_CSCO_WRKR_PRTY_KEY,                       
 ST.SLS_MTN_CORRECTION_CASE_NUM,                   
 ST.SLS_MTN_CORRECTION_CMNT, 
 'N' ACTION_CODE,
 'I' DML_TYPE
  FROM $$STGDB.WI_XAAS_NEW_RNWL_ACV_INCR ST
   WHERE  NOT EXISTS (SELECT 1 FROM  $$SLSORDVWDB.N_ATTR_PRDT_AS_NEW_OR_RNWL_TV N_ATTR_TV
                WHERE N_ATTR_TV.SK_ERP_BKGS_TRX_ID = ST.SK_ERP_BKGS_TRX_ID
       AND N_ATTR_TV.ERP_TRX_VERSION_INT = ST.ERP_TRX_VERSION_INT
  AND N_ATTR_TV.END_TV_DTM = '3500-01-01 00:00:00')
  AND NOT EXISTS ( SEL 1 FROM $$WORKDB.W_ATTR_PRDT_AS_NEW_OR_RNWL W
	WHERE W.SK_ERP_BKGS_TRX_ID = ST.SK_ERP_BKGS_TRX_ID ) ;
	
	
CALL COLLECT_STATS_WRAP('$$WORKDB','W_ATTR_PRDT_AS_NEW_OR_RNWL','D');