


Source1 Name : SQ_W_ATTR_PRDT_NEW_RNWL_ACV


Pre SQL : 



SQL Query : 
SELECT
  ST.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
  ST.SK_RTR_ATTRIBUTION_ID,
  ST.ATTR_PRDT_KEY,
  ST.SALES_ORDER_LINE_KEY,
  ST.HQ_CR_PRTY_KEY,
  ST.TRANSACTION_CR_PARTY_KEY,
  ST.BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
  ST.BK_TECH_GROUP_ID,
  ST.BK_AS_ARCHITECTURE_NAME,
  ST.COVERED_PRDT_KEY,
  ST.ATTR_PRDT_QTY,
  ST.ATTR_PCT,
  ST.ATTR_NET_PRICE_LOCAL_AMT,
  ST.ATTR_EXTD_PRICE_LOCAL_AMT,
  ST.SALES_MOTION_CD,
  ST.SALES_MOTION_CONTEXT_NAME, 
  ST.ERP_CUST_ACCT_LOC_KEY,
  ST.AS_TS_CD,
  ST.SK_LINE_REF_NUM,
  ST.SK_ERP_BKGS_TRX_ID,
  ST.SK_RENEW_CONTRACT_LINE_ID,
  ST.SK_AS_PARENT_INVENTORY_ITEM_ID,
  ST.ITEM_CATEGORY_NAME,
  ST.ERP_TRX_VERSION_INT,
  ST.SS_CD,
  ST.SK_ATTRIBUTION_ID_INT,
  COALESCE(ATTR_PRDT_CLASS_NAME,'UNKNOWN') AS ATTR_PRDT_CLASS_NAME,
  ST.RENEWAL_REF_ID,
  ST.RENEWAL_REF_CD,
  ST.SMR_TAGGING_FAILURE_RSN_CD,
  ST.SALES_MOTION_TIMING_CD,
  ST.MANUAL_OVERRIDE_ROLE,
  ST.TOTAL_SERVICES_USD_AMT,
  ST.ACV_USD_AMT,
  ST.TCV_USD_AMT,
  ST.EXTENDED_PRICE_USD_AMT,
  ST.REQUESTING_CSCO_WRKR_PRTY_KEY,
  ST.SLS_MTN_CORRECTION_CASE_NUM,
  ST.SLS_MTN_CORRECTION_CMNT,
  CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM,
  USER  EDW_CREATE_USER,
  CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM,
  USER EDW_UPDATE_USER, 
  ST.START_TV_DTM,
  CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)) AS END_TV_DTM,          
 'N' ACTION_CODE,
 'I' DML_TYPE
  FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIB_CV ST
   WHERE  NOT EXISTS (SELECT 1 FROM  $$SLSORDVWDB.N_ATTR_PRDT_NEW_RNWL_ACV_TV N_ATTR_TV
                WHERE N_ATTR_TV.SK_ERP_BKGS_TRX_ID = ST.SK_ERP_BKGS_TRX_ID
       AND N_ATTR_TV.ERP_TRX_VERSION_INT = ST.ERP_TRX_VERSION_INT
  AND N_ATTR_TV.END_TV_DTM = '3500-01-01 00:00:00')


Post SQL : 



Target1 Name : W_ATTR_PRDT_NEW_RNWL_ACV


Pre SQL : 
DELETE FROM $$WORKDB.W_ATTR_PRDT_NEW_RNWL_ACV ALL;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$WORKDB','W_ATTR_PRDT_NEW_RNWL_ACV','D');