


Source1 Name : SQ_EX_OPL_XXGCO_RTR_ATTRIBUTION


Pre SQL : 
CREATE VOLATILE TABLE ST_OPL_XXGCO_RTR_ATTRIBUTION_SET 
AS 
(  
SEL * FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIBUTION  ST
QUALIFY ROW_NUMBER() OVER(PARTITION BY RTR_ATTRIBUTION_ID, OA_ATTRIBUTION_ID, SS_CD ORDER BY TD_COMMIT_TIME DESC ) = 1 
) WITH DATA ON COMMIT PRESERVE ROWS;

DELETE FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIBUTION  ;

INSERT INTO $$STGDB.ST_OPL_XXGCO_RTR_ATTRIBUTION  
SEL * FROM ST_OPL_XXGCO_RTR_ATTRIBUTION_SET ;


SQL Query : 
SELECT 
 RTR_ATTRIBUTION_ID,
 TRX_ID,
 TRX_VERSION,
 ATTRIBUTED_EXT_NET_PRICE,
 ATTRIBUTED_UNIT_NET_PRICE,
 ATTRIBUTED_PERCENTAGE,
 ATTRIBUTED_QUANTITY,
 ENTERPRISE_SKU_INV_ITM_ID,
 COVERED_PRD_INV_ITM_ID,
 AS_PARENT_SKU_INV_ITM_ID,
 ARCHITECTURE_ID,
 TECHNOLOGY_ID,
 TXN_CR_PARTY_ID,
 START_DATE,
 END_DATE,
 ERP_HEADER_ID,
 ERP_LINE_ID,
 ERP_SO_NUMBER,
 ORDER_NUMBER,
 LINE_REF_NUMBER,
 INSTALL_SITE_LOCATION,
 QUOTE_LINE_ID,
 QUOTE_NUMBER,
 SALES_MOTION,
 SALES_MOTION_CONTEXT,
 AS_TS_FLAG,
 RENEW_CLE_ID,
 ITEM_CATEGORIZATION,
 RECGD_PERCENTAGE,
 RECGD_ATTRIB_EXT_NET_PRICE,
 SS_CD,
 OA_ATTRIBUTION_ID,
 OFFER_TYPE_ID,
 TD_COMMIT_TIME,
 ATTR_PRDT_CLASS_NAME,
 HQ_CR_PARTY_ID,
 RENEWAL_REF_TYPE ,
 RENEWAL_REF_VALUE,
 REASON_CODE,
 SALES_MOTION_TIMING,
 MANUAL_PROCESS_FLAG,           
 USER_ID,                       
 CASE_NUMBER,                   
 COMMENTS 
 FROM $$EXCEPDB.EX_OPL_XXGCO_RTR_ATTRIBUTION EX
 WHERE  NOT EXISTS
 (SELECT 1 FROM
 $$STGDB.ST_OPL_XXGCO_RTR_ATTRIBUTION ST
 WHERE ST.TRX_ID= EX.TRX_ID
 )


Post SQL : 



Target1 Name : ST_OPL_XXGCO_RTR_ATTRIBUTION


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','ST_OPL_XXGCO_RTR_ATTRIBUTION','D');


Source2 Name : SQ_SM_ATTR_PRDT_AS_NEW_OR_RNWL


Pre SQL : 



SQL Query : 
SELECT
 SM.MAX_RTR_KEY + RANK() OVER (ORDER BY RTR_ATTRIBUTION_ID, OA_ATTRIBUTION_ID, SS_CD) AS ATTR_PRDT_AS_NEW_OR_RNWL_KEY
 ,DT.RTR_ATTRIBUTION_ID AS SK_RTR_ATTRIBUTION_ID
 ,DT.SS_CD
 ,DT.OA_ATTRIBUTION_ID AS SK_ATTRIBUTION_ID_INT
 ,CURRENT_TIMESTAMP(0) EDW_CREATE_DTM 
 ,USER EDW_CREATE_USER
FROM (
   SELECT RTR_ATTRIBUTION_ID, OA_ATTRIBUTION_ID, SS_CD
     FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIBUTION ST
    WHERE NOT EXISTS
    ( SELECT SK_RTR_ATTRIBUTION_ID , SK_ATTRIBUTION_ID_INT, SS_CD
        FROM $$ETLVWDB.SM_ATTR_PRDT_AS_NEW_OR_RNWL SM
    WHERE ST.RTR_ATTRIBUTION_ID = SM.SK_RTR_ATTRIBUTION_ID
	AND ST.OA_ATTRIBUTION_ID = SM.SK_ATTRIBUTION_ID_INT
	AND ST.SS_CD = SM.SS_CD
     )
   GROUP BY 1,2,3   
 ) DT,
(
SELECT COALESCE(MAX(WI.ATTR_PRDT_AS_NEW_OR_RNWL_KEY),0)  MAX_RTR_KEY 
FROM ( SEL ATTR_PRDT_AS_NEW_OR_RNWL_KEY FROM $$ETLVWDB.SM_ATTR_PRDT_AS_NEW_OR_RNWL
		UNION ALL SEL ATTR_PRDT_AS_NEW_OR_RNWL_KEY FROM $$ETLVWDB.SM_ATTR_PRDT_NEW_RNWL_ACV
		) WI 
) SM


Post SQL : 



Target2 Name : SM_ATTR_PRDT_AS_NEW_OR_RNWL


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$TRANSLATIONDB','SM_ATTR_PRDT_AS_NEW_OR_RNWL','D');


Source3 Name : SQ_WI_OPL_XXGCO_RTR_ATTRIBUTION


Pre SQL : 



SQL Query : 
SELECT
                 SMXSS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
                 COALESCE(NSQL.SERVICE_QUOTE_LINE_KEY,-999) AS DEAL_QUOTE_LINE_KEY,
                 ST.RTR_ATTRIBUTION_ID AS SK_RTR_ATTRIBUTION_ID,
                 NSOL.SALES_ORDER_LINE_KEY,
                 NPA.ITEM_KEY AS ATTR_PRDT_KEY,
                 COALESCE(NSQL.BK_QUOTE_NUM,'UNKNOWN')  AS BK_QUOTE_NUM,
                 ST.START_DATE AS BK_SRC_EFFECTIVE_START_DT,
                 COALESCE(ST.END_DATE, CAST('3500-01-01' AS DATE)) AS SRC_EFFECTIVE_END_DT,
                 CURRENT_TIMESTAMP(0)  AS START_TV_DTM, 
                 COALESCE(NPC.ITEM_KEY,-999) AS COVERED_PRDT_KEY,
                 ST.ATTRIBUTED_QUANTITY AS ATTR_PRDT_QTY,
                 COALESCE(NULLIF(ST.ATTRIBUTED_PERCENTAGE,0), 0 ) AS ATTR_PCT,
                 COALESCE(ST.ATTRIBUTED_UNIT_NET_PRICE,0.0000) AS ATTR_NET_PRICE_LOCAL_AMT,
                 COALESCE(ST.ATTRIBUTED_EXT_NET_PRICE,0.0000) AS ATTR_EXTD_PRICE_LOCAL_AMT,
                 COALESCE(ST.SALES_MOTION, 'UNKNOWN' ) SALES_MOTION_CD,
                 COALESCE(ST.SALES_MOTION_CONTEXT,'UNKNOWN') AS SALES_MOTION_CONTEXT_NAME,
                 CAST(ST.TD_COMMIT_TIME AS TIMESTAMP(0)) AS SRC_CREATED_DTM,
                 CAST(ST.TD_COMMIT_TIME AS DATE) AS DV_SRC_CREATED_DT,
                 -999 AS SRC_CREATED_CSCO_WRKR_PRTY_KEY,
                 CAST(ST.TD_COMMIT_TIME AS TIMESTAMP(0)) AS SRC_LAST_UPDATED_DTM,
                 CAST(ST.TD_COMMIT_TIME AS DATE) DV_SRC_LAST_UPDATED_DT,
                 -999 AS SRC_LST_UPD_CSCO_WRKR_PRTY_KEY,
                 COALESCE(SITEUSE.ERP_CUST_ACCOUNT_LOCATION_KEY, -999 ) AS ERP_CUST_ACCT_LOC_KEY,
                 COALESCE(ST.AS_TS_FLAG,'UNK') AS AS_TS_CD,
                 COALESCE( ST.LINE_REF_NUMBER,-999 ) AS SK_LINE_REF_NUM,
                 COALESCE( ARCH.NAME, 'UNKNOWN' ) AS BK_AS_ARCHITECTURE_NAME,
                 COALESCE( TECH.NAME, 'UNKNOWN' ) AS BK_TECH_GROUP_ID,
                 COALESCE( OFFER.NAME,'UNKNOWN' ) AS BK_DV_ATTR_PRDT_OFFER_TYPE_NAME,
                 COALESCE(NP.PARTY_KEY,-999) AS TRANSACTION_CR_PARTY_KEY,
                 COALESCE(ST.TRX_ID,-999) AS SK_ERP_BKGS_TRX_ID,
                 COALESCE(ST.RENEW_CLE_ID,-999) AS SK_RENEW_CONTRACT_LINE_ID,
                 COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-999) AS SK_AS_PARENT_INVENTORY_ITEM_ID,
                 COALESCE(ST.ITEM_CATEGORIZATION,'UNKNOWN') AS ITEM_CATEGORY_NAME,
                 COALESCE(ST.TRX_VERSION,-999) AS ERP_TRX_VERSION_INT,
                 ST.RECGD_PERCENTAGE,
                 COALESCE(ST.RECGD_ATTRIB_EXT_NET_PRICE,0) AS RECGD_ATTRIB_EXT_NET_PRICE,
				ST.SS_CD,
				ST.OA_ATTRIBUTION_ID AS SK_ATTRIBUTION_ID_IN,
                ST.ATTR_PRDT_CLASS_NAME,
				COALESCE(NPHQ.PARTY_KEY,-999) AS HQ_CR_PRTY_KEY,
                ST.RENEWAL_REF_VALUE AS RENEWAL_REF_ID,
                ST.RENEWAL_REF_TYPE AS RENEWAL_REF_CD,
                ST.REASON_CODE AS SMR_TAGGING_FAILURE_RSN_CD,
                ST.SALES_MOTION_TIMING AS SALES_MOTION_TIMING_CD,
				ST.MANUAL_PROCESS_FLAG AS MANUAL_OVERRIDE_ROLE,           
				COALESCE(NCWP.CISCO_WORKER_PARTY_KEY,-999) AS REQUESTING_CSCO_WRKR_PRTY_KEY,                   
				ST.CASE_NUMBER AS SLS_MTN_CORRECTION_CASE_NUM,                   
				ST.COMMENTS AS SLS_MTN_CORRECTION_CMNT
  FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIBUTION ST 
            INNER JOIN (SELECT * FROM $$SLSORDVWDB.N_SALES_ORDER_LINE_TV WHERE CAST(END_TV_DATETIME AS DATE)='3500-01-01' 
      QUALIFY ROW_NUMBER() OVER(PARTITION BY SK_SO_LINE_ID_INT ORDER BY END_TV_DATETIME DESC) = 1)NSOL
             ON ST.ERP_LINE_ID = NSOL.SK_SO_LINE_ID_INT
             LEFT JOIN $$SERVICEVWDB.N_SERVICE_QUOTE_LINE NSQL
             ON COALESCE(ST.QUOTE_NUMBER,'UNKNOWN') = NSQL.BK_QUOTE_NUM
             AND COALESCE(ST.QUOTE_LINE_ID,-999) = COALESCE(NSQL.SK_QUOTE_LINE_ID_INT,-999)
            LEFT JOIN $$COMREFVWDB.N_PRODUCT NPC
             ON COALESCE(ST.COVERED_PRD_INV_ITM_ID,-1012624) = NPC.SK_INVENTORY_ITEM_ID_INT     
            INNER JOIN $$COMREFVWDB.N_PRODUCT NPA
             ON ST.ENTERPRISE_SKU_INV_ITM_ID = NPA.SK_INVENTORY_ITEM_ID_INT
            LEFT JOIN $$COMREFVWDB.N_PRODUCT NPP
             ON COALESCE(ST.AS_PARENT_SKU_INV_ITM_ID,-1012624) = NPP.SK_INVENTORY_ITEM_ID_INT
      LEFT JOIN $$COMREFVWDB.N_ERP_CUST_ACCT_LOC_USE SITEUSE
             ON COALESCE(ST.INSTALL_SITE_LOCATION,-999) = SITEUSE.SK_SITE_USE_ID_INT 
            LEFT JOIN $$COMREFVWDB.N_PARTY NP
             ON COALESCE(ST.TXN_CR_PARTY_ID,-999) = NP.PARTY_SSOT_PARTY_ID_INT
            AND NP.SS_CODE IN ('CR_MODS','CR')
            AND COALESCE(NP.STATUS_CODE,'A')='A'
             LEFT JOIN $$COMREFVWDB.N_PARTY NPHQ
             ON COALESCE(ST.HQ_CR_PARTY_ID,-999) = NPHQ.PARTY_SSOT_PARTY_ID_INT
              AND NPHQ.SS_CODE IN ('CR_MODS','CR')
            AND COALESCE(NPHQ.STATUS_CODE,'A')='A'
            /* INNER JOIN $$SLSORDVWDB.N_SOL_OFFER_ATTRIBUTION NSOA
   ON COALESCE(ST.OA_ATTRIBUTION_ID,-9999) = NSOA.SK_OFFER_ATTRIBUTION_ID_INT */
   LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_ARCH ARCH
   ON ST.ARCHITECTURE_ID = ARCH.ARCHITECTURE_ID
   LEFT JOIN $$ETLVWDB.EL_XXCAS_SLIMCS_TECH TECH
   ON ST.TECHNOLOGY_ID = TECH.TECHNOLOGY_ID
    LEFT JOIN $$ETLONLYDB.EL_XXCAS_SLIMCS_BIZ_SERVICES OFFER
    ON ST.OFFER_TYPE_ID = OFFER.BS_ID
	LEFT OUTER JOIN $$COMREFVWDB.N_CISCO_WORKER_PARTY_TV NCWP
	ON NCWP.CEC_ID||'@cisco.com'=ST.USER_ID
	AND NCWP.END_TV_DATE='3500-01-01'
    INNER JOIN $$ETLVWDB.SM_ATTR_PRDT_AS_NEW_OR_RNWL SMXSS
    ON SMXSS.SK_RTR_ATTRIBUTION_ID=ST.RTR_ATTRIBUTION_ID
    AND SMXSS.SK_ATTRIBUTION_ID_INT = ST.OA_ATTRIBUTION_ID
    AND SMXSS.SS_CD = ST.SS_CD


Post SQL : 



Target3 Name : WI_OPL_XXGCO_RTR_ATTRIBUTION


Pre SQL : 
DELETE FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIBUTION;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_OPL_XXGCO_RTR_ATTRIBUTION','D');


Source4 Name : SQ_ST_OPL_XXGCO_RTR_ATTRIBUTION


Pre SQL : 



SQL Query : 
SELECT 
 ST.RTR_ATTRIBUTION_ID,
 ST.TRX_ID,
 ST.TRX_VERSION,
 ST.ATTRIBUTED_EXT_NET_PRICE,
 ST.ATTRIBUTED_UNIT_NET_PRICE,
 ST.ATTRIBUTED_PERCENTAGE,
 ST.ATTRIBUTED_QUANTITY,
 ST.ENTERPRISE_SKU_INV_ITM_ID,
 ST.COVERED_PRD_INV_ITM_ID,
 ST.AS_PARENT_SKU_INV_ITM_ID,
 ST.ARCHITECTURE_ID,
 ST.TECHNOLOGY_ID,
 ST.TXN_CR_PARTY_ID,
 ST.START_DATE,
 ST.END_DATE,
 ST.ERP_HEADER_ID,
 ST.ERP_LINE_ID,
 ST.ERP_SO_NUMBER,
 ST.ORDER_NUMBER,
 ST.LINE_REF_NUMBER,
 ST.INSTALL_SITE_LOCATION,
 ST.QUOTE_LINE_ID,
 ST.QUOTE_NUMBER,
 ST.SALES_MOTION,
 ST.SALES_MOTION_CONTEXT,
 ST.AS_TS_FLAG,
 ST.RENEW_CLE_ID,
 ST.ITEM_CATEGORIZATION,
 ST.RECGD_PERCENTAGE,
 ST.RECGD_ATTRIB_EXT_NET_PRICE,
 ST.SS_CD,
 ST.OA_ATTRIBUTION_ID,
 ST.OFFER_TYPE_ID,
 ST.TD_COMMIT_TIME,
 ST.ATTR_PRDT_CLASS_NAME,
 ST.HQ_CR_PARTY_ID,
 ST.RENEWAL_REF_TYPE,            
 ST.RENEWAL_REF_VALUE,
 ST.REASON_CODE,
COALESCE(ST.SALES_MOTION_TIMING,'UNKNOWN')  AS SALES_MOTION_TIMING,
 ST.MANUAL_PROCESS_FLAG,           
 ST.USER_ID,                       
 ST.CASE_NUMBER,                   
 ST.COMMENTS 
 FROM
 $$STGDB.ST_OPL_XXGCO_RTR_ATTRIBUTION ST 
 INNER JOIN 
  (
   SELECT TRX_ID  
   FROM $$STGDB.ST_OPL_XXGCO_RTR_ATTRIBUTION STG 
   WHERE NOT EXISTS 
   (  
    SELECT 1 FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIBUTION WI
     WHERE WI.SK_RTR_ATTRIBUTION_ID  = STG.RTR_ATTRIBUTION_ID 
     AND WI.SK_ATTRIBUTION_ID_INT  = STG.OA_ATTRIBUTION_ID
     AND WI.SS_CD = STG.SS_CD
    ) 
      GROUP BY 1
  ) WK
 ON ST.TRX_ID = WK.TRX_ID


Post SQL : 



Target4 Name : EX_OPL_XXGCO_RTR_ATTRIBUTION1


Pre SQL : 
DELETE FROM $$EXCEPDB.EX_OPL_XXGCO_RTR_ATTRIBUTION ALL;


Post SQL : 
DELETE FROM $$STGDB.WI_OPL_XXGCO_RTR_ATTRIBUTION WK 
WHERE EXISTS ( SELECT 1 FROM $$EXCEPDB.EX_OPL_XXGCO_RTR_ATTRIBUTION EX WHERE EX.RTR_ATTRIBUTION_ID = WK.SK_RTR_ATTRIBUTION_ID) ;

CALL COLLECT_STATS_WRAP('$$EXCEPDB','EX_OPL_XXGCO_RTR_ATTRIBUTION','D');