ETL Name:	wf_MT_CS_DEAL_SVC_FIN_HIER_ALLOC.xml


Session 1: 	s_m_MT_CS_DEAL_SVC_FIN_HIER_ALLOC
Mapping 1: 	m_MT_CS_DEAL_SVC_FIN_HIER_ALLOC


Source1 Name : SQ_WI_CS_DEAL_SVC_FIN_HIER_ALLOC_pipe1


Pre SQL : 
DELETE FROM $$STGDB.WI_CS_DEAL_SVC_FIN_HIER_ALLOC ALL ;


SQL Query : 
SELECT 
 NPSG.BK_PRODUCT_SUBGROUP_ID, 
CAST(-999 AS VARCHAR(50))  APPROVED_DEAL_ID, 
  NSC.BK_SERVICE_CATEGORY_ID,
  NSC.SERVICE_CATEGORY_DESCRIPTION, 
  NTG.BK_TECHNOLOGY_GROUP_ID, 
  NTG.TECHNOLOGY_GROUP_CODE, 
  NTG.TECHNOLOGY_GROUP_DESCRIPTION, 
   NPSG.PRODUCT_SUBGROUP_DESCRIPTION, 
  NASA.BK_ALLOCATED_SERVC_GROUP_ID, 
  NASA.ALLOCATION_PERCENTAGE, 
  NASG.SERVICE_GROUP_DESCRIPTION,
  NPSG.RU_SERVICE_BRAND_CODE,
  NPSG.RU_SERVICE_LEVEL_GROUP_CODE,
  'SPA' AS DV_PRDT_SUB_GRP_ALLOC_SRC_CD
 FROM 
 $$COMREFVWDB.N_SERVICE_CATEGORY_TV NSC, 
 $$COMREFVWDB.N_TECHNOLOGY_GROUP_TV NTG, 
 $$COMREFVWDB.N_PRODUCT_SUBGROUP_TV NPSG, 
 $$COMREFVWDB.N_ADVANCED_SERVICE_ALLOC_TV NASA, 
 $$COMREFVWDB.N_ALLOCATED_SERVC_GROUP_TV NASG 
 WHERE 
  NSC.BK_TECHNOLOGY_GROUP_ID = NTG.BK_TECHNOLOGY_GROUP_ID 
 AND NTG.END_TV_DATE = DATE '3500-01-01' 
 AND NSC.END_TV_DATE = DATE '3500-01-01'
 AND NSC.BK_SERVICE_CATEGORY_ID = NASG.BK_SERVICE_CATEGORY_ID 
 AND NASG.END_TV_DATE = DATE '3500-01-01' 
 AND NASG.BK_ALLOCATED_SERVC_GROUP_ID = NASA.BK_ALLOCATED_SERVC_GROUP_ID 
 AND NASA.END_TV_DATE = DATE '3500-01-01' 
 AND NASA.BK_PRODUCT_SUBGROUP_ID = NPSG.BK_PRODUCT_SUBGROUP_ID 
 AND NPSG.END_TV_DATE = DATE '3500-01-01'
 AND NPSG.SERVICE_SUBGROUP_TYPE = 'Y' 
 GROUP BY  
  NSC.BK_SERVICE_CATEGORY_ID, 
  NSC.SERVICE_CATEGORY_DESCRIPTION, 
  NTG.BK_TECHNOLOGY_GROUP_ID, 
  NTG.TECHNOLOGY_GROUP_CODE, 
  NTG.TECHNOLOGY_GROUP_DESCRIPTION, 
  NPSG.BK_PRODUCT_SUBGROUP_ID, 
  NPSG.PRODUCT_SUBGROUP_DESCRIPTION, 
  NASA.BK_ALLOCATED_SERVC_GROUP_ID, 
  NASA.ALLOCATION_PERCENTAGE, 
  NASG.SERVICE_GROUP_DESCRIPTION,
  NPSG.RU_SERVICE_BRAND_CODE,
  NPSG.RU_SERVICE_LEVEL_GROUP_CODE


Post SQL : 



Target1 Name : WI_CS_DEAL_SVC_FIN_HIER_ALLOC1


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_CS_DEAL_SVC_FIN_HIER_ALLOC','V') ;


Source2 Name : SQ_WI_CS_DEAL_SVC_FIN_HIER_ALLOC_pipe2


Pre SQL : 



SQL Query : 
SELECT 
  NCSL.BK_PRODUCT_SUBGROUP_ID, 
  NCSL.BK_DEAL_ID   ,
  NSC.BK_SERVICE_CATEGORY_ID,
  NSC.SERVICE_CATEGORY_DESCRIPTION, 
  NTG.BK_TECHNOLOGY_GROUP_ID, 
  NTG.TECHNOLOGY_GROUP_CODE, 
  NTG.TECHNOLOGY_GROUP_DESCRIPTION, 
  NPSG.PRODUCT_SUBGROUP_DESCRIPTION, 
  NCSL.BK_ALLOCATED_SERVICE_GROUP_ID , 
  NCSL.ALLOCATED_SRV_GRP_ALLCTN_PCT , 
  NASG.SERVICE_GROUP_DESCRIPTION,
  NPSG.RU_SERVICE_BRAND_CODE,
  NPSG.RU_SERVICE_LEVEL_GROUP_CODE,
  'MDM' AS DV_PRDT_SUB_GRP_ALLOC_SRC_CD
FROM
  $$COMREFVWDB.N_CMBND_SERVICES_DSG_ALLC_LINK NCSL
  INNER JOIN  
  $$COMREFVWDB.N_PRODUCT_SUBGROUP_TV NPSG
 ON 
 NCSL.BK_PRODUCT_SUBGROUP_ID = NPSG.BK_PRODUCT_SUBGROUP_ID AND 
 NPSG.SERVICE_SUBGROUP_TYPE = 'Y'   AND  NCSL.Source_Deleted_Flg='N'  AND 
 NPSG.END_TV_DATE = DATE '3500-01-01'
 
 INNER JOIN 
 $$COMREFVWDB.N_ADVANCED_SERVICE_ALLOC_TV NASA
 ON  
 NASA.BK_PRODUCT_SUBGROUP_ID = NPSG.BK_PRODUCT_SUBGROUP_ID AND 
 NCSL.BK_ALLOCATED_SERVICE_GROUP_ID =   NASA.BK_ALLOCATED_SERVC_GROUP_ID   AND 
 NASA.END_TV_DATE = DATE '3500-01-01'
 
 INNER JOIN   
 $$COMREFVWDB.N_ALLOCATED_SERVC_GROUP_TV NASG 
 ON NASA.BK_ALLOCATED_SERVC_GROUP_ID = NASG.BK_ALLOCATED_SERVC_GROUP_ID 
 AND NASG.END_TV_DATE = DATE '3500-01-01' 

INNER JOIN    
$$COMREFVWDB.N_SERVICE_CATEGORY_TV NSC
 ON NSC.BK_SERVICE_CATEGORY_ID = NASG.BK_SERVICE_CATEGORY_ID 
 AND NSC.END_TV_DATE = DATE '3500-01-01'
  
  INNER JOIN   
  $$COMREFVWDB.N_TECHNOLOGY_GROUP_TV NTG
 ON NSC.BK_TECHNOLOGY_GROUP_ID = NTG.BK_TECHNOLOGY_GROUP_ID
 AND NTG.END_TV_DATE = DATE '3500-01-01'
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14


Post SQL : 



Target2 Name : WI_CS_DEAL_SVC_FIN_HIER_ALLOC2


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_CS_DEAL_SVC_FIN_HIER_ALLOC','V') ;


Source3 Name : SQ_WI_CS_DEAL_SVCFIN_HIER_ALC_PID_pipe3


Pre SQL : 



SQL Query : 
SELECT 
  SFH.BK_PRODUCT_SUBGROUP_ID        
 ,SFH.APPROVED_DEAL_ID              
 ,SFH.BK_SERVICE_CATEGORY_ID        
 ,SFH.SERVICE_CATEGORY_DESCRIPTION  
 ,SFH.BK_TECHNOLOGY_GROUP_ID        
 ,SFH.TECHNOLOGY_GROUP_CODE         
 ,SFH.TECHNOLOGY_GROUP_DESCRIPTION  
 ,SFH.PRODUCT_SUBGROUP_DESCRIPTION  
 ,SFH.BK_ALLOCATED_SERVC_GROUP_ID   
 ,SFH.ALLOCATION_PERCENTAGE         
 ,SFH.SERVICE_GROUP_DESCRIPTION     
 ,SFH.RU_SERVICE_BRAND_CODE         
 ,SFH.RU_SERVICE_LEVEL_GROUP_CODE   
 ,SFH.DV_PRDT_SUB_GRP_ALLOC_SRC_CD  
 ,RP.ITEM_KEY
FROM $$STGDB.WI_CS_DEAL_SVC_FIN_HIER_ALLOC SFH,
     $$COMREFVWDB.R_PRODUCTS RP
WHERE RP.RU_BK_SERVICE_PROD_SUBGROUP_ID = SFH.BK_PRODUCT_SUBGROUP_ID
 AND RP.GOODS_OR_SERVICE_TYPE = 'SERVICE'
 AND SFH.ALLOCATION_PERCENTAGE = 1 
 AND BK_PRODUCT_SUBGROUP_ID <> 'UNKNOWN'


Post SQL : 



Target3 Name : WI_CS_DEAL_SVCFIN_HIER_ALC_PID1


Pre SQL : 
DELETE FROM $$STGDB.WI_CS_DEAL_SVCFIN_HIER_ALC_PID ALL ;


Post SQL : 



Source4 Name : SQ_WI_CS_DEAL_SVCFIN_HIER_ALC_PID_pipe4


Pre SQL : 



SQL Query : 
SELECT 
	  SFH.BK_PRODUCT_SUBGROUP_ID        
 ,SFH.APPROVED_DEAL_ID              
 ,SFH.BK_SERVICE_CATEGORY_ID        
 ,SFH.SERVICE_CATEGORY_DESCRIPTION  
 ,SFH.BK_TECHNOLOGY_GROUP_ID        
 ,SFH.TECHNOLOGY_GROUP_CODE         
 ,SFH.TECHNOLOGY_GROUP_DESCRIPTION  
 ,SFH.PRODUCT_SUBGROUP_DESCRIPTION  
 ,SFH.BK_ALLOCATED_SERVC_GROUP_ID   
 ,SFH.ALLOCATION_PERCENTAGE         
 ,SFH.SERVICE_GROUP_DESCRIPTION     
 ,SFH.RU_SERVICE_BRAND_CODE         
 ,SFH.RU_SERVICE_LEVEL_GROUP_CODE   
 ,SFH.DV_PRDT_SUB_GRP_ALLOC_SRC_CD  
 ,RP.ITEM_KEY
FROM $$STGDB.WI_CS_DEAL_SVC_FIN_HIER_ALLOC SFH,
     $$COMREFVWDB.R_PRODUCTS RP 
WHERE RP.RU_BK_SERVICE_PROD_SUBGROUP_ID = SFH.BK_PRODUCT_SUBGROUP_ID
 AND RP.GOODS_OR_SERVICE_TYPE = 'SERVICE'
 AND BK_PRODUCT_SUBGROUP_ID <> 'UNKNOWN'    
 AND EXISTS ( SELECT 1 FROM $$COMREFVWDB.N_OFFR_PRDT_ATRBD_PRDTLNK_HIST OALK 
               WHERE OALK.OFFER_PRDT_KEY = RP.ITEM_KEY
               AND CURRENT_DATE BETWEEN OALK.START_DT AND OALK.END_DT 
               AND OALK.SOURCE_DELETED_FLG = 'N' )  
 AND NOT EXISTS ( SELECT 1 FROM $$STGDB.WI_CS_DEAL_SVCFIN_HIER_ALC_PID ST WHERE ST.ITEM_KEY = RP.ITEM_KEY )


Post SQL : 



Target4 Name : WI_CS_DEAL_SVCFIN_HIER_ALC_PID3


Pre SQL : 



Post SQL : 



Source5 Name : SQ_WI_CS_DEAL_SVCFIN_HIER_ALC_PID_pipe5


Pre SQL : 



SQL Query : 
SELECT 
   RP.RU_BK_SERVICE_PROD_SUBGROUP_ID   BK_PRODUCT_SUBGROUP_ID
   ,SFH.APPROVED_DEAL_ID
   ,RP.BK_BUSINESS_UNIT_ID AS BK_SERVICE_CATEGORY_ID
  ,RP.BUSINESS_UNIT_DESCRIPTION AS SERVICE_CATEGORY_DESCRIPTION  
  ,RP.BUSINESS_UNIT_DESCRIPTION AS BK_TECHNOLOGY_GROUP_ID  
  ,RP.TECHNOLOGY_GROUP_CODE         
  ,RP.TECHNOLOGY_GROUP_DESCRIPTION  
  ,RP.PRODUCT_SUBGROUP_DESCRIPTION  
  ,RP.RU_BK_ALLOCATED_SERVC_GROUP_ID BK_ALLOCATED_SERVC_GROUP_ID   
  ,CASE WHEN SFH.BK_SERVICE_CATEGORY_ID = 'TECHNICAL SUPPORT SERVICES' 
        THEN 1 ELSE SFH.ALLOCATION_PERCENTAGE END ALLOCATION_PERCENTAGE
  ,COALESCE(RP.RU_BK_ALLOCATED_SERVC_GROUP_ID, 'UNKNOWN' ) AS SERVICE_GROUP_DESCRIPTION     
  ,RP.RU_SERVICE_BRAND_CODE            
  ,RP.RU_SERVICE_LEVEL_GROUP_CODE
  ,SFH.DV_PRDT_SUB_GRP_ALLOC_SRC_CD
  ,RP.ITEM_KEY
FROM $$STGDB.WI_CS_DEAL_SVC_FIN_HIER_ALLOC SFH,
     $$COMREFVWDB.R_PRODUCTS RP
WHERE RP.RU_BK_SERVICE_PROD_SUBGROUP_ID = SFH.BK_PRODUCT_SUBGROUP_ID
  AND SFH.BK_PRODUCT_SUBGROUP_ID <> 'UNKNOWN'        
  AND ALLOCATION_PERCENTAGE = 1 
  AND EXISTS ( SEL 1 FROM $$COMREFVWDB.N_OFFR_PRDT_ATRBD_PRDTLNK_HIST OALK
               WHERE RP.ITEM_KEY = OALK.ATTRIBUTED_PRDT_KEY
                                                   AND CURRENT_DATE BETWEEN OALK.START_DT AND OALK.END_DT 
               AND OALK.SOURCE_DELETED_FLG = 'N' ) 
 AND NOT EXISTS ( SELECT 1 FROM $$STGDB.WI_CS_DEAL_SVCFIN_HIER_ALC_PID ST WHERE ST.ITEM_KEY = RP.ITEM_KEY )


Post SQL : 



Target5 Name : WI_CS_DEAL_SVCFIN_HIER_ALC_PID5


Pre SQL : 



Post SQL : 



Source6 Name : SQ_WI_CS_DEAL_SVCFIN_HIER_ALC_PID_pipe6


Pre SQL : 



SQL Query : 
SELECT 
	  SFH.BK_PRODUCT_SUBGROUP_ID        
 ,SFH.APPROVED_DEAL_ID              
 ,SFH.BK_SERVICE_CATEGORY_ID        
 ,SFH.SERVICE_CATEGORY_DESCRIPTION  
 ,SFH.BK_TECHNOLOGY_GROUP_ID        
 ,SFH.TECHNOLOGY_GROUP_CODE         
 ,SFH.TECHNOLOGY_GROUP_DESCRIPTION  
 ,SFH.PRODUCT_SUBGROUP_DESCRIPTION  
 ,SFH.BK_ALLOCATED_SERVC_GROUP_ID   
 ,SFH.ALLOCATION_PERCENTAGE         
 ,SFH.SERVICE_GROUP_DESCRIPTION     
 ,SFH.RU_SERVICE_BRAND_CODE         
 ,SFH.RU_SERVICE_LEVEL_GROUP_CODE   
 ,SFH.DV_PRDT_SUB_GRP_ALLOC_SRC_CD  
 ,RP.ITEM_KEY
FROM $$STGDB.WI_CS_DEAL_SVC_FIN_HIER_ALLOC SFH,
     $$COMREFVWDB.R_PRODUCTS RP
WHERE RP.RU_BK_SERVICE_PROD_SUBGROUP_ID = SFH.BK_PRODUCT_SUBGROUP_ID
  AND BK_PRODUCT_SUBGROUP_ID <> 'UNKNOWN'        
  AND NOT EXISTS ( SELECT 1 FROM $$STGDB.WI_CS_DEAL_SVCFIN_HIER_ALC_PID ST WHERE ST.ITEM_KEY = RP.ITEM_KEY )


Post SQL : 



Target6 Name : WI_CS_DEAL_SVCFIN_HIER_ALC_PID7


Pre SQL : 



Post SQL : 



Source7 Name : SQ_WI_CS_DEAL_SVCFIN_HIER_ALC_PID_pipe7


Pre SQL : 



SQL Query : 
SELECT 
	  SFH.BK_PRODUCT_SUBGROUP_ID        
 ,SFH.APPROVED_DEAL_ID              
 ,SFH.BK_SERVICE_CATEGORY_ID        
 ,SFH.SERVICE_CATEGORY_DESCRIPTION  
 ,SFH.BK_TECHNOLOGY_GROUP_ID        
 ,SFH.TECHNOLOGY_GROUP_CODE         
 ,SFH.TECHNOLOGY_GROUP_DESCRIPTION  
 ,SFH.PRODUCT_SUBGROUP_DESCRIPTION  
 ,SFH.BK_ALLOCATED_SERVC_GROUP_ID   
 ,SFH.ALLOCATION_PERCENTAGE         
 ,SFH.SERVICE_GROUP_DESCRIPTION     
 ,SFH.RU_SERVICE_BRAND_CODE         
 ,SFH.RU_SERVICE_LEVEL_GROUP_CODE   
 ,SFH.DV_PRDT_SUB_GRP_ALLOC_SRC_CD
 , -999 AS ITEM_KEY 
FROM $$STGDB.WI_CS_DEAL_SVC_FIN_HIER_ALLOC SFH
WHERE BK_PRODUCT_SUBGROUP_ID = 'UNKNOWN'


Post SQL : 



Target7 Name : WI_CS_DEAL_SVCFIN_HIER_ALC_PID9


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_CS_DEAL_SVCFIN_HIER_ALC_PID','D') ;


Source8 Name : SQ_WI_CS_DEAL_SVCFIN_HIER_ALC_DEL_pipe8


Pre SQL : 



SQL Query : 
SELECT
 BK_PRODUCT_SUBGROUP_ID        
 ,APPROVED_DEAL_ID              
 ,BK_SERVICE_CATEGORY_ID        
 ,SERVICE_CATEGORY_DESCRIPTION  
 ,BK_TECHNOLOGY_GROUP_ID        
 ,TECHNOLOGY_GROUP_CODE         
 ,TECHNOLOGY_GROUP_DESCRIPTION  
 ,PRODUCT_SUBGROUP_DESCRIPTION  
 ,BK_ALLOCATED_SERVC_GROUP_ID   
 ,ALLOCATION_PERCENTAGE         
 ,SERVICE_GROUP_DESCRIPTION     
 ,RU_SERVICE_BRAND_CODE         
 ,RU_SERVICE_LEVEL_GROUP_CODE   
 ,DV_PRDT_SUB_GRP_ALLOC_SRC_CD  
 ,ITEM_KEY              
FROM $$STGDB.WI_CS_DEAL_SVCFIN_HIER_ALC_PID ST
WHERE EXISTS ( SELECT 1 FROM $$COMREFVWDB.MT_CS_DEAL_SVC_FIN_HIER_ALLOC MT
					WHERE ST.ITEM_KEY = MT.ITEM_KEY 
					  AND ST.BK_PRODUCT_SUBGROUP_ID = MT.BK_PRODUCT_SUBGROUP_ID
					  AND ST.APPROVED_DEAL_ID = MT.APPROVED_DEAL_ID
					  AND ST.BK_SERVICE_CATEGORY_ID = MT.BK_SERVICE_CATEGORY_ID
					  AND ST.SERVICE_CATEGORY_DESCRIPTION = MT.SERVICE_CATEGORY_DESCRIPTION
					  AND ST.BK_TECHNOLOGY_GROUP_ID = MT.BK_TECHNOLOGY_GROUP_ID
					  AND ST.TECHNOLOGY_GROUP_CODE = MT.TECHNOLOGY_GROUP_CODE
					  AND ST.TECHNOLOGY_GROUP_DESCRIPTION = MT.TECHNOLOGY_GROUP_DESCRIPTION
					  AND ST.BK_PRODUCT_SUBGROUP_ID = MT.BK_PRODUCT_SUBGROUP_ID
					  AND ST.PRODUCT_SUBGROUP_DESCRIPTION = MT.PRODUCT_SUBGROUP_DESCRIPTION
					  AND ST.ALLOCATION_PERCENTAGE = MT.ALLOCATION_PERCENTAGE
					  AND ST.SERVICE_GROUP_DESCRIPTION = MT.SERVICE_GROUP_DESCRIPTION
					  AND ST.RU_SERVICE_BRAND_CODE = MT.RU_SERVICE_BRAND_CODE
					  AND ST.RU_SERVICE_LEVEL_GROUP_CODE = MT.RU_SERVICE_LEVEL_GROUP_CODE
                      AND ST.DV_PRDT_SUB_GRP_ALLOC_SRC_CD = MT.DV_PRDT_SUB_GRP_ALLOC_SRC_CD )


Post SQL : 



Target8 Name : WI_CS_DEAL_SVCFIN_HIER_ALC_DEL


Pre SQL : 
DELETE FROM $$STGDB.WI_CS_DEAL_SVCFIN_HIER_ALC_DEL ALL ;


Post SQL : 
DELETE FROM $$STGDB.WI_CS_DEAL_SVCFIN_HIER_ALC_DEL WHERE (ITEM_KEY, APPROVED_DEAL_ID, DV_PRDT_SUB_GRP_ALLOC_SRC_CD) IN (
SELECT ITEM_KEY, APPROVED_DEAL_ID, DV_PRDT_SUB_GRP_ALLOC_SRC_CD FROM $$STGDB.WI_CS_DEAL_SVCFIN_HIER_ALC_DEL GROUP BY 1,2,3 HAVING SUM(ALLOCATION_PERCENTAGE) <> 1.000
);

DELETE FROM $$STGDB.WI_CS_DEAL_SVCFIN_HIER_ALC_PID WI WHERE EXISTS (
SELECT 1 FROM $$STGDB.WI_CS_DEAL_SVCFIN_HIER_ALC_DEL DELS 
 WHERE WI.ITEM_KEY  = DELS.ITEM_KEY
   AND WI.APPROVED_DEAL_ID = DELS.APPROVED_DEAL_ID
   AND WI.DV_PRDT_SUB_GRP_ALLOC_SRC_CD = DELS.DV_PRDT_SUB_GRP_ALLOC_SRC_CD);

CALL COLLECT_STATS_WRAP('$$STGDB','WI_CS_DEAL_SVCFIN_HIER_ALC_DEL','D') ;
CALL COLLECT_STATS_WRAP('$$STGDB','WI_CS_DEAL_SVCFIN_HIER_ALC_PID','D') ;


Source9 Name : SQ_MT_CS_DEAL_SVC_FIN_HIER_ALLOC_pipe9


Pre SQL : 



SQL Query : 
SELECT
 BK_PRODUCT_SUBGROUP_ID        
 ,APPROVED_DEAL_ID              
 ,BK_SERVICE_CATEGORY_ID        
 ,SERVICE_CATEGORY_DESCRIPTION  
 ,BK_TECHNOLOGY_GROUP_ID        
 ,TECHNOLOGY_GROUP_CODE         
 ,TECHNOLOGY_GROUP_DESCRIPTION  
 ,PRODUCT_SUBGROUP_DESCRIPTION  
 ,BK_ALLOCATED_SERVC_GROUP_ID   
 ,ALLOCATION_PERCENTAGE         
 ,SERVICE_GROUP_DESCRIPTION     
 ,RU_SERVICE_BRAND_CODE         
 ,RU_SERVICE_LEVEL_GROUP_CODE   
 ,DV_PRDT_SUB_GRP_ALLOC_SRC_CD  
 ,ITEM_KEY                      
 ,CURRENT_TIMESTAMP(0) EDW_CREATE_DTM                
 ,USER AS EDW_CREATE_USER               
 ,CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM                
 ,USER AS EDW_UPDATE_USER               
FROM $$STGDB.WI_CS_DEAL_SVCFIN_HIER_ALC_PID ST
WHERE NOT EXISTS ( SELECT 1 FROM $$COMREFVWDB.MT_CS_DEAL_SVC_FIN_HIER_ALLOC MT
					WHERE ST.ITEM_KEY = MT.ITEM_KEY 
                                       AND ST.DV_PRDT_SUB_GRP_ALLOC_SRC_CD = MT.DV_PRDT_SUB_GRP_ALLOC_SRC_CD
                                        AND ST.APPROVED_DEAL_ID = MT.APPROVED_DEAL_ID )


Post SQL : 



Target9 Name : MT_CS_DEAL_SVC_FIN_HIER_ALLOC


Pre SQL : 
DELETE FROM $$COMREFVWDB.MT_CS_DEAL_SVC_FIN_HIER_ALLOC MT
WHERE EXISTS ( SELECT 1 FROM $$STGDB.WI_CS_DEAL_SVCFIN_HIER_ALC_PID WI
					WHERE MT.ITEM_KEY = WI.ITEM_KEY
                                       AND MT.APPROVED_DEAL_ID = WI.APPROVED_DEAL_ID
                                       AND MT.DV_PRDT_SUB_GRP_ALLOC_SRC_CD = WI.DV_PRDT_SUB_GRP_ALLOC_SRC_CD  )


Post SQL : 
CALL COLLECT_STATS_WRAP('$$COMREFDB','MT_CS_DEAL_SVC_FIN_HIER_ALLOC','D') ;