ETL Name:	wf_MT_SVC_FINANCE_HIERARCHY.xml


Session 1: 	s_m_MT_SVC_FINANCE_HIERARCHY
Mapping 1: 	m_MT_SVC_FINANCE_HIERARCHY


Source1 Name : SQ_WI_SVC_FINANCE_HIERARCHY_pipe1


Pre SQL : 



SQL Query : 
SELECT 
  NSC.BK_SERVICE_CATEGORY_ID, 
  NSC.SERVICE_CATEGORY_DESCRIPTION, 
  NTG.BK_TECHNOLOGY_GROUP_ID, 
  NTG.TECHNOLOGY_GROUP_CODE, 
  NTG.TECHNOLOGY_GROUP_DESCRIPTION, 
  NPSG.BK_PRODUCT_SUBGROUP_ID, 
  NPSG.PRODUCT_SUBGROUP_DESCRIPTION, 
  NASA.BK_ALLOCATED_SERVC_GROUP_ID, 
  NASA.ALLOCATION_PERCENTAGE, 
  NASG.SERVICE_GROUP_DESCRIPTION,
  NPSG.RU_SERVICE_BRAND_CODE,
  NPSG.RU_SERVICE_LEVEL_GROUP_CODE
 FROM 
 $$COMREFVWDB.N_SERVICE_CATEGORY_TV NSC, 
 $$COMREFVWDB.N_TECHNOLOGY_GROUP_TV NTG, 
 $$COMREFVWDB.N_PRODUCT_SUBGROUP_TV NPSG, 
 $$COMREFVWDB.N_ADVANCED_SERVICE_ALLOC_TV NASA, 
 $$COMREFVWDB.N_ALLOCATED_SERVC_GROUP_TV NASG 
 WHERE 
  NSC.BK_TECHNOLOGY_GROUP_ID = NTG.BK_TECHNOLOGY_GROUP_ID 
 AND NTG.END_TV_DATE = DATE '3500-01-01' 
 AND NSC.END_TV_DATE = DATE '3500-01-01'
 AND NSC.BK_SERVICE_CATEGORY_ID = NASG.BK_SERVICE_CATEGORY_ID 
 AND NASG.END_TV_DATE = DATE '3500-01-01' 
 AND NASG.BK_ALLOCATED_SERVC_GROUP_ID = NASA.BK_ALLOCATED_SERVC_GROUP_ID 
 AND NASA.END_TV_DATE = DATE '3500-01-01' 
 AND NASA.BK_PRODUCT_SUBGROUP_ID = NPSG.BK_PRODUCT_SUBGROUP_ID 
 AND NPSG.END_TV_DATE = DATE '3500-01-01'
 AND NPSG.SERVICE_SUBGROUP_TYPE = 'Y' 
 GROUP BY  
  NSC.BK_SERVICE_CATEGORY_ID, 
  NSC.SERVICE_CATEGORY_DESCRIPTION, 
  NTG.BK_TECHNOLOGY_GROUP_ID, 
  NTG.TECHNOLOGY_GROUP_CODE, 
  NTG.TECHNOLOGY_GROUP_DESCRIPTION, 
  NPSG.BK_PRODUCT_SUBGROUP_ID, 
  NPSG.PRODUCT_SUBGROUP_DESCRIPTION, 
  NASA.BK_ALLOCATED_SERVC_GROUP_ID, 
  NASA.ALLOCATION_PERCENTAGE, 
  NASG.SERVICE_GROUP_DESCRIPTION,
  NPSG.RU_SERVICE_BRAND_CODE,
  NPSG.RU_SERVICE_LEVEL_GROUP_CODE


Post SQL : 



Target1 Name : WI_SVC_FINANCE_HIERARCHY


Pre SQL : 
DELETE FROM  $$STGDB.WI_SVC_FINANCE_HIERARCHY ALL


Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_SVC_FINANCE_HIERARCHY','D') ;


Source2 Name : SQ_WI_SVC_FINANCE_HIERARCHY_PID_pipe2


Pre SQL : 



SQL Query : 
SELECT 
	 SFH.BK_SERVICE_CATEGORY_ID        
	,SFH.SERVICE_CATEGORY_DESCRIPTION  
	,SFH.BK_TECHNOLOGY_GROUP_ID        
	,SFH.TECHNOLOGY_GROUP_CODE         
	,SFH.TECHNOLOGY_GROUP_DESCRIPTION  
	,SFH.BK_PRODUCT_SUBGROUP_ID        
	,SFH.PRODUCT_SUBGROUP_DESCRIPTION  
	,SFH.BK_ALLOCATED_SERVC_GROUP_ID   
	,SFH.ALLOCATION_PERCENTAGE
	,SFH.SERVICE_GROUP_DESCRIPTION     
	,SFH.SERVICE_BRAND_CODE            
	,SFH.SERVICE_LEVEL_GROUP_CODE    
	,RP.ITEM_KEY
FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY SFH,
     $$COMREFVWDB.R_PRODUCTS RP
WHERE RP.RU_BK_SERVICE_PROD_SUBGROUP_ID = SFH.BK_PRODUCT_SUBGROUP_ID
 AND RP.GOODS_OR_SERVICE_TYPE = 'SERVICE'
 AND SFH.ALLOCATION_PERCENTAGE = 1 
 AND BK_PRODUCT_SUBGROUP_ID <> 'UNKNOWN'


Post SQL : 



Target2 Name : WI_SVC_FINANCE_HIERARCHY_PID1


Pre SQL : 
DELETE FROM  $$STGDB.WI_SVC_FINANCE_HIERARCHY_PID ALL


Post SQL : 



Source3 Name : SQ_WI_SVC_FINANCE_HIERARCHY_PID_pipe3


Pre SQL : 



SQL Query : 
SELECT 
	 SFH.BK_SERVICE_CATEGORY_ID        
	,SFH.SERVICE_CATEGORY_DESCRIPTION  
	,SFH.BK_TECHNOLOGY_GROUP_ID        
	,SFH.TECHNOLOGY_GROUP_CODE         
	,SFH.TECHNOLOGY_GROUP_DESCRIPTION  
	,SFH.BK_PRODUCT_SUBGROUP_ID        
	,SFH.PRODUCT_SUBGROUP_DESCRIPTION  
	,SFH.BK_ALLOCATED_SERVC_GROUP_ID   
	,SFH.ALLOCATION_PERCENTAGE
	,SFH.SERVICE_GROUP_DESCRIPTION     
	,SFH.SERVICE_BRAND_CODE            
	,SFH.SERVICE_LEVEL_GROUP_CODE 
	,RP.ITEM_KEY
FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY SFH,
     $$COMREFVWDB.R_PRODUCTS RP 
WHERE RP.RU_BK_SERVICE_PROD_SUBGROUP_ID = SFH.BK_PRODUCT_SUBGROUP_ID
 AND RP.GOODS_OR_SERVICE_TYPE = 'SERVICE'
 AND BK_PRODUCT_SUBGROUP_ID <> 'UNKNOWN'    
 AND EXISTS ( SELECT 1 FROM $$COMREFVWDB.N_OFFR_PRDT_ATRBD_PRDTLNK_HIST OALK 
               WHERE OALK.OFFER_PRDT_KEY = RP.ITEM_KEY
               AND CURRENT_DATE BETWEEN OALK.START_DT AND OALK.END_DT 
               AND OALK.SOURCE_DELETED_FLG = 'N' )  
 AND NOT EXISTS ( SELECT 1 FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY_PID ST WHERE ST.ITEM_KEY = RP.ITEM_KEY )


Post SQL : 



Target3 Name : WI_SVC_FINANCE_HIERARCHY_PID5


Pre SQL : 



Post SQL : 



Source4 Name : SQ_WI_SVC_FINANCE_HIERARCHY_PID_pipe4


Pre SQL : 



SQL Query : 
SELECT 
   RP.BK_BUSINESS_UNIT_ID AS BK_SERVICE_CATEGORY_ID
  ,RP.BUSINESS_UNIT_DESCRIPTION AS SERVICE_CATEGORY_DESCRIPTION  
  ,RP.BUSINESS_UNIT_DESCRIPTION AS BK_TECHNOLOGY_GROUP_ID  
  ,RP.TECHNOLOGY_GROUP_CODE         
  ,RP.TECHNOLOGY_GROUP_DESCRIPTION  
  ,RP.RU_BK_SERVICE_PROD_SUBGROUP_ID   BK_PRODUCT_SUBGROUP_ID
  ,RP.PRODUCT_SUBGROUP_DESCRIPTION  
  ,RP.RU_BK_ALLOCATED_SERVC_GROUP_ID BK_ALLOCATED_SERVC_GROUP_ID   
  ,CASE WHEN SFH.BK_SERVICE_CATEGORY_ID = 'TECHNICAL SUPPORT SERVICES' 
        THEN 1 ELSE SFH.ALLOCATION_PERCENTAGE END ALLOCATION_PERCENTAGE
  ,COALESCE(RP.RU_BK_ALLOCATED_SERVC_GROUP_ID, 'UNKNOWN' ) AS SERVICE_GROUP_DESCRIPTION     
  ,RP.RU_SERVICE_BRAND_CODE AS SERVICE_BRAND_CODE            
  ,RP.RU_SERVICE_LEVEL_GROUP_CODE AS SERVICE_LEVEL_GROUP_CODE
  ,RP.ITEM_KEY
FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY SFH,
     $$COMREFVWDB.R_PRODUCTS RP
WHERE RP.RU_BK_SERVICE_PROD_SUBGROUP_ID = SFH.BK_PRODUCT_SUBGROUP_ID
  AND SFH.BK_PRODUCT_SUBGROUP_ID <> 'UNKNOWN'        
  AND ALLOCATION_PERCENTAGE = 1 
  AND EXISTS ( SEL 1 FROM $$COMREFVWDB.N_OFFR_PRDT_ATRBD_PRDTLNK_HIST OALK
               WHERE RP.ITEM_KEY = OALK.ATTRIBUTED_PRDT_KEY
                                                   AND CURRENT_DATE BETWEEN OALK.START_DT AND OALK.END_DT 
               AND OALK.SOURCE_DELETED_FLG = 'N' ) 
 AND NOT EXISTS ( SELECT 1 FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY_PID ST WHERE ST.ITEM_KEY = RP.ITEM_KEY )


Post SQL : 



Target4 Name : WI_SVC_FINANCE_HIERARCHY_PID6


Pre SQL : 



Post SQL : 



Source5 Name : SQ_WI_SVC_FINANCE_HIERARCHY_PID_pipe5


Pre SQL : 



SQL Query : 
SELECT 
	 SFH.BK_SERVICE_CATEGORY_ID        
	,SFH.SERVICE_CATEGORY_DESCRIPTION  
	,SFH.BK_TECHNOLOGY_GROUP_ID        
	,SFH.TECHNOLOGY_GROUP_CODE         
	,SFH.TECHNOLOGY_GROUP_DESCRIPTION  
	,SFH.BK_PRODUCT_SUBGROUP_ID        
	,SFH.PRODUCT_SUBGROUP_DESCRIPTION  
	,SFH.BK_ALLOCATED_SERVC_GROUP_ID   
	,SFH.ALLOCATION_PERCENTAGE         
	,SFH.SERVICE_GROUP_DESCRIPTION     
	,SFH.SERVICE_BRAND_CODE            
	,SFH.SERVICE_LEVEL_GROUP_CODE
	,RP.ITEM_KEY
FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY SFH,
     $$COMREFVWDB.R_PRODUCTS RP
WHERE RP.RU_BK_SERVICE_PROD_SUBGROUP_ID = SFH.BK_PRODUCT_SUBGROUP_ID
  AND BK_PRODUCT_SUBGROUP_ID <> 'UNKNOWN'        
  AND NOT EXISTS ( SELECT 1 FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY_PID ST WHERE ST.ITEM_KEY = RP.ITEM_KEY )


Post SQL : 



Target5 Name : WI_SVC_FINANCE_HIERARCHY_PID7


Pre SQL : 



Post SQL : 



Source6 Name : SQ_WI_SVC_FINANCE_HIERARCHY_PID_pipe6


Pre SQL : 



SQL Query : 
SELECT 
	SFH.BK_SERVICE_CATEGORY_ID        
	,SFH.SERVICE_CATEGORY_DESCRIPTION  
	,SFH.BK_TECHNOLOGY_GROUP_ID        
	,SFH.TECHNOLOGY_GROUP_CODE         
	,SFH.TECHNOLOGY_GROUP_DESCRIPTION  
	,SFH.BK_PRODUCT_SUBGROUP_ID        
	,SFH.PRODUCT_SUBGROUP_DESCRIPTION  
	,SFH.BK_ALLOCATED_SERVC_GROUP_ID   
	,SFH.ALLOCATION_PERCENTAGE         
	,SFH.SERVICE_GROUP_DESCRIPTION     
	,SFH.SERVICE_BRAND_CODE            
	,SFH.SERVICE_LEVEL_GROUP_CODE
	, -999 AS ITEM_KEY 
FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY SFH
WHERE BK_PRODUCT_SUBGROUP_ID = 'UNKNOWN'


Post SQL : 



Target6 Name : WI_SVC_FINANCE_HIERARCHY_PID8


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP('$$STGDB','WI_SVC_FINANCE_HIERARCHY_PID','D') ;


Source7 Name : SQ_WI_SVC_FINANCE_HIERARCHY_DEL_pipe7


Pre SQL : 



SQL Query : 
SELECT
BK_SERVICE_CATEGORY_ID        
,SERVICE_CATEGORY_DESCRIPTION  
,BK_TECHNOLOGY_GROUP_ID        
,TECHNOLOGY_GROUP_CODE         
,TECHNOLOGY_GROUP_DESCRIPTION  
,BK_PRODUCT_SUBGROUP_ID        
,PRODUCT_SUBGROUP_DESCRIPTION  
,BK_ALLOCATED_SERVC_GROUP_ID   
,ALLOCATION_PERCENTAGE         
,SERVICE_GROUP_DESCRIPTION     
,SERVICE_BRAND_CODE            
,SERVICE_LEVEL_GROUP_CODE      
,ITEM_KEY                                   
FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY_PID ST
WHERE EXISTS ( SELECT 1 FROM $$COMREFVWDB.MT_SVC_FINANCE_HIERARCHY MT
					WHERE ST.ITEM_KEY = MT.ITEM_KEY 
					  AND ST.BK_SERVICE_CATEGORY_ID = MT.BK_SERVICE_CATEGORY_ID
					  AND ST.SERVICE_CATEGORY_DESCRIPTION = MT.SERVICE_CATEGORY_DESCRIPTION
					  AND ST.BK_TECHNOLOGY_GROUP_ID = MT.BK_TECHNOLOGY_GROUP_ID
					  AND ST.TECHNOLOGY_GROUP_CODE = MT.TECHNOLOGY_GROUP_CODE
					  AND ST.TECHNOLOGY_GROUP_DESCRIPTION = MT.TECHNOLOGY_GROUP_DESCRIPTION
					  AND ST.BK_PRODUCT_SUBGROUP_ID = MT.BK_PRODUCT_SUBGROUP_ID
					  AND ST.PRODUCT_SUBGROUP_DESCRIPTION = MT.PRODUCT_SUBGROUP_DESCRIPTION
					  AND ST.BK_ALLOCATED_SERVC_GROUP_ID  = MT.BK_ALLOCATED_SERVC_GROUP_ID
					  AND ST.ALLOCATION_PERCENTAGE = MT.ALLOCATION_PERCENTAGE
					  AND ST.SERVICE_GROUP_DESCRIPTION = MT.SERVICE_GROUP_DESCRIPTION
					  AND ST.SERVICE_BRAND_CODE = MT.SERVICE_BRAND_CODE
					  AND ST.SERVICE_LEVEL_GROUP_CODE = MT.SERVICE_LEVEL_GROUP_CODE
                      )


Post SQL : 



Target7 Name : WI_SVC_FINANCE_HIERARCHY_DEL1


Pre SQL : 
DELETE FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY_DEL ALL;


Post SQL : 
DELETE FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY_DEL WHERE ITEM_KEY IN (
SELECT ITEM_KEY FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY_DEL GROUP BY 1 HAVING SUM(ALLOCATION_PERCENTAGE) <> 1.000
);

DELETE FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY_PID WHERE ITEM_KEY IN (
SELECT ITEM_KEY FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY_DEL GROUP BY 1 ); 

CALL COLLECT_STATS_WRAP('$$STGDB','WI_SVC_FINANCE_HIERARCHY_DEL','D') ;
CALL COLLECT_STATS_WRAP('$$STGDB','WI_SVC_FINANCE_HIERARCHY_PID','D') ;


Source8 Name : SQ_MT_SVC_FINANCE_HIERARCHY_pipe8


Pre SQL : 



SQL Query : 
SELECT
BK_SERVICE_CATEGORY_ID        
,SERVICE_CATEGORY_DESCRIPTION  
,BK_TECHNOLOGY_GROUP_ID        
,TECHNOLOGY_GROUP_CODE         
,TECHNOLOGY_GROUP_DESCRIPTION  
,BK_PRODUCT_SUBGROUP_ID        
,PRODUCT_SUBGROUP_DESCRIPTION  
,BK_ALLOCATED_SERVC_GROUP_ID   
,ALLOCATION_PERCENTAGE         
,SERVICE_GROUP_DESCRIPTION     
,SERVICE_BRAND_CODE            
,SERVICE_LEVEL_GROUP_CODE      
,ITEM_KEY             
,USER AS EDW_CREATE_USER
,CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM
,USER AS EDW_UPDATE_USER
,CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM         
FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY_PID ST
WHERE NOT EXISTS ( SELECT 1 FROM $$COMREFVWDB.MT_SVC_FINANCE_HIERARCHY MT
					WHERE ST.ITEM_KEY = MT.ITEM_KEY )


Post SQL : 



Target8 Name : MT_SVC_FINANCE_HIERARCHY


Pre SQL : 
/* UPDATE MT FROM $$COMREFVWDB.MT_SVC_FINANCE_HIERARCHY MT,
	   $$STGDB.WI_SVC_FINANCE_HIERARCHY_PID WI
SET SERVICE_CATEGORY_DESCRIPTION  = WI.SERVICE_CATEGORY_DESCRIPTION
	,BK_TECHNOLOGY_GROUP_ID   = WI.BK_TECHNOLOGY_GROUP_ID
	,TECHNOLOGY_GROUP_CODE         = WI.TECHNOLOGY_GROUP_CODE
	,TECHNOLOGY_GROUP_DESCRIPTION = WI.TECHNOLOGY_GROUP_DESCRIPTION  
	,BK_PRODUCT_SUBGROUP_ID        = WI.BK_PRODUCT_SUBGROUP_ID
	,PRODUCT_SUBGROUP_DESCRIPTION  = WI.PRODUCT_SUBGROUP_DESCRIPTION
	,ALLOCATION_PERCENTAGE = WI.ALLOCATION_PERCENTAGE
	,SERVICE_GROUP_DESCRIPTION     = WI.SERVICE_GROUP_DESCRIPTION
	,SERVICE_BRAND_CODE            = WI.SERVICE_BRAND_CODE
	,SERVICE_LEVEL_GROUP_CODE    = WI.SERVICE_LEVEL_GROUP_CODE
	,EDW_UPDATE_USER = USER
	,EDW_UPDATE_DTM = CURRENT_TIMESTAMP(0)
WHERE MT.ITEM_KEY = WI.ITEM_KEY 
  AND MT.BK_SERVICE_CATEGORY_ID = WI.BK_SERVICE_CATEGORY_ID 
  AND MT.BK_ALLOCATED_SERVC_GROUP_ID = WI.BK_ALLOCATED_SERVC_GROUP_ID
  AND (
  MT.SERVICE_CATEGORY_DESCRIPTION <> WI.SERVICE_CATEGORY_DESCRIPTION
  OR MT.BK_TECHNOLOGY_GROUP_ID <> WI.BK_TECHNOLOGY_GROUP_ID
  OR MT.TECHNOLOGY_GROUP_CODE <> WI.TECHNOLOGY_GROUP_CODE
  OR MT.TECHNOLOGY_GROUP_DESCRIPTION <> WI.TECHNOLOGY_GROUP_DESCRIPTION
  OR MT.BK_PRODUCT_SUBGROUP_ID <> WI.BK_PRODUCT_SUBGROUP_ID
  OR MT.PRODUCT_SUBGROUP_DESCRIPTION <> WI.PRODUCT_SUBGROUP_DESCRIPTION
  OR MT.ALLOCATION_PERCENTAGE <> WI.ALLOCATION_PERCENTAGE
  OR MT.SERVICE_GROUP_DESCRIPTION <> WI.SERVICE_GROUP_DESCRIPTION
  OR MT.SERVICE_BRAND_CODE <> WI.SERVICE_BRAND_CODE
  OR MT.SERVICE_LEVEL_GROUP_CODE <> WI.SERVICE_LEVEL_GROUP_CODE  ) */  /* Commenting update else insert method, following delete else insert method */

DELETE FROM $$COMREFVWDB.MT_SVC_FINANCE_HIERARCHY MT
WHERE EXISTS ( SELECT 1 FROM $$STGDB.WI_SVC_FINANCE_HIERARCHY_PID WI
					WHERE MT.ITEM_KEY = WI.ITEM_KEY )


Post SQL : 
CALL COLLECT_STATS_WRAP('$$COMREFDB','MT_SVC_FINANCE_HIERARCHY','D') ;