ETL Name:	wf_MT_CS_DEAL_SVC_FIN_HIER_ME.xml


Session 1: 	s_m_MT_CS_DEAL_SVC_FIN_HIER_ME
Mapping 1: 	m_MT_CS_DEAL_SVC_FIN_HIER_ME


Source1 Name : SQ_MT_CS_DEAL_SVC_FIN_HIER_ALLOC


Pre SQL : 



SQL Query : 
SELECT
BK_PRODUCT_SUBGROUP_ID,
APPROVED_DEAL_ID,
BK_SERVICE_CATEGORY_ID,
SERVICE_CATEGORY_DESCRIPTION,
BK_TECHNOLOGY_GROUP_ID,
TECHNOLOGY_GROUP_CODE,
TECHNOLOGY_GROUP_DESCRIPTION,
PRODUCT_SUBGROUP_DESCRIPTION,
BK_ALLOCATED_SERVC_GROUP_ID,
ALLOCATION_PERCENTAGE,
SERVICE_GROUP_DESCRIPTION,
RU_SERVICE_BRAND_CODE,
RU_SERVICE_LEVEL_GROUP_CODE,
DV_PRDT_SUB_GRP_ALLOC_SRC_CD,
ITEM_KEY,
CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM,
USER AS EDW_CREATE_USER,
CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM,
USER AS EDW_UPDATE_USER
FROM
$$COMREFVWDB.MT_CS_DEAL_SVC_FIN_HIER_ALLOC


Post SQL : 



Target1 Name : MT_CS_DEAL_SVC_FIN_HIER_ME


Pre SQL : 
DELETE FROM $$COMREFVWDB.MT_CS_DEAL_SVC_FIN_HIER_ME ALL;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$COMREFDB','MT_CS_DEAL_SVC_FIN_HIER_ME','V');