ETL Name:	wf_N_XAAS_SCA_SLSTRX_NRT_DEF_NG.xml


Session 1: 	s_m_N_XAAS_SCA_SLSTRX_NRT_DEF_NG
Mapping 1: 	m_N_XAAS_SCA_SLSTRX_NRT_DEF_NG


Source1 Name : SQ_N_XAAS_SCA_SLS_TRX_NG_NRT


Pre SQL : 



SQL Query : 
SELECT 
WSFTTND.SLS_CREDIT_ASGNMT_SLS_TRX_KEY 
,WSFTTND.SO_SBSCRPTN_ITM_SLS_TRX_KEY   
,WSFTTND.BK_OFFER_ATTRIBUTION_ID_INT   
,WSFTTND.BK_ATTRIBUTION_SS_CD          
,WSFTTND.BK_SLS_TERR_ASSIGNMENT_TYPE_CD
,WSFTTND.ATTR_PRDT_AS_NEW_OR_RNWL_KEY  
,WSFTTND.SALES_CREDIT_USAGE_CD         
,WSFTTND.SALES_CREDIT_UNALLOCATED_FLG  
,WSFTTND.SLS_CREDIT_ASGNMT_MODE_CD     
,WSFTTND.SK_TRX_SPLIT_SC_ID_INT        
,WSFTTND.OVERLAY_TYPE                  
,WSFTTND.BK_SALES_REP_NUM              
,WSFTTND.BK_SLS_TERR_ASGNMT_TYPE_CD    
,WSFTTND.SALES_TERRITORY_KEY           
,WSFTTND.SRC_RPTD_REBOK_OTM_TERR_ID_INT
,WSFTTND.SRC_RPTD_REBOK_OTM_TERR_NAME  
,WSFTTND.SRC_RPTD_REBOK_OTM_TERR_TYP_CD
,WSFTTND.BK_SALES_CREDIT_TYPE_CODE     
,WSFTTND.BK_CREATED_BY_ERP_USER_NAME   
,WSFTTND.BK_SLS_CRDT_ASGNMT_RSN_CD     
,WSFTTND.SCA_CREATE_DTM                
,WSFTTND.DV_SCA_CREATE_DT              
,WSFTTND.SCA_LAST_UPDATE_DTM           
,WSFTTND.DV_SCA_LAST_UPDATE_DT         
,WSFTTND.SPLIT_PCT                     
,WSFTTND.EFFECTIVE_START_DTM           
,WSFTTND.DV_EFFECTIVE_START_DT         
,WSFTTND.EFFECTIVE_END_DTM             
,WSFTTND.DV_EFFECTIVE_END_DT           
,WSFTTND.SOURCE_COMMIT_DTM             
,WSFTTND.DV_SOURCE_COMMIT_DT           
,WSFTTND.UCRM_CASE_NUM                 
,WSFTTND.BK_TRX_SPLIT_BU_ID            
,WSFTTND.SK_TRX_SPLIT_ID_INT           
,WSFTTND.SALES_MOTION_CD               
,WSFTTND.SK_RTR_ATTRIBUTION_ID         
,WSFTTND.SPLIT_1_OFFER_ATTRIBITION_PCT 
,WSFTTND.SPLIT_2_NEW_RENEW_PCT         
,WSFTTND.TOTAL_SPLIT_PCT               
,WSFTTND.RU_REBOK_CHANNEL_FLG          
,WSFTTND.EDW_CREATE_DTM                
,WSFTTND.EDW_CREATE_USER               
,WSFTTND.EDW_UPDATE_DTM                
,WSFTTND.EDW_UPDATE_USER               

 FROM $$NRTNCRVWDB.N_XAAS_SCA_SLS_TRX_NG_NRT  WSFTTND
 WHERE 1=2


Post SQL : 



Target1 Name : N_XAAS_SCA_SLS_TRX_NG_NRT


Pre SQL : 



Post SQL : 
MERGE INTO  $$NRTNCRVWDB.N_XAAS_SCA_SLS_TRX_NG_NRT NXSCANRT
 USING  $$NRTSTGDB.WI_SCA_FOR_TSL_TRX_NRT_DEF_NG WSFTTND
 ON 
 WSFTTND.SLS_CREDIT_ASGNMT_SLS_TRX_KEY = NXSCANRT.SLS_CREDIT_ASGNMT_SLS_TRX_KEY 
 WHEN MATCHED THEN UPDATE 
 SET 
SALES_CREDIT_USAGE_CD = WSFTTND.SALES_CREDIT_USAGE_CD ,
SALES_CREDIT_UNALLOCATED_FLG = WSFTTND.SALES_CREDIT_UNALLOCATED_FLG ,
SLS_CREDIT_ASGNMT_MODE_CD = WSFTTND.SLS_CREDIT_ASGNMT_MODE_CD ,
SK_TRX_SPLIT_SC_ID_INT = WSFTTND.SK_TRX_SC_ID_INT ,
OVERLAY_TYPE = WSFTTND.OVERLAY_TYPE ,
BK_SALES_REP_NUM = WSFTTND.BK_SALES_REP_NUM ,
BK_SLS_TERR_ASGNMT_TYPE_CD = WSFTTND.BK_SLS_TERR_ASGNMT_TYPE_CD ,
SO_SBSCRPTN_ITM_SLS_TRX_KEY = WSFTTND.SO_SBSCRPTN_ITM_SLS_TRX_KEY ,
SALES_TERRITORY_KEY = WSFTTND.SALES_TERRITORY_KEY ,
SRC_RPTD_REBOK_OTM_TERR_ID_INT = WSFTTND.SRC_RPTD_RBK_OTM_TERR_ID_INT ,
SRC_RPTD_REBOK_OTM_TERR_NAME = WSFTTND.SRC_RPTD_RBK_OTM_TERR_NAME ,
SRC_RPTD_REBOK_OTM_TERR_TYP_CD = WSFTTND.SRC_RPTD_RBK_OTM_TERR_TYPE_CD ,
BK_SALES_CREDIT_TYPE_CODE = WSFTTND.BK_SALES_CREDIT_TYPE_CODE ,
BK_CREATED_BY_ERP_USER_NAME = WSFTTND.BK_CREATED_BY_ERP_USER_NAME ,
BK_SLS_CRDT_ASGNMT_RSN_CD = WSFTTND.BK_SLS_CRDT_ASGNMT_RSN_CD ,
SCA_CREATE_DTM = WSFTTND.SCA_CREATE_DTM ,
DV_SCA_CREATE_DT = WSFTTND.DV_SCA_CREATE_DT ,
SCA_LAST_UPDATE_DTM = WSFTTND.SCA_LAST_UPDATE_DTM ,
DV_SCA_LAST_UPDATE_DT = WSFTTND.DV_SCA_LAST_UPDATE_DT ,
SPLIT_PCT = WSFTTND.SPLIT_PCT ,
EFFECTIVE_START_DTM = WSFTTND.EFFECTIVE_START_DTM ,
DV_EFFECTIVE_START_DT = WSFTTND.DV_EFFECTIVE_START_DT ,
EFFECTIVE_END_DTM = WSFTTND.EFFECTIVE_END_DTM ,
DV_EFFECTIVE_END_DT = WSFTTND.DV_EFFECTIVE_END_DT ,
RU_REBOK_CHANNEL_FLG = WSFTTND.RU_REBOK_CHANNEL_FLG ,
SOURCE_COMMIT_DTM = WSFTTND.SOURCE_COMMIT_DTM ,
DV_SOURCE_COMMIT_DT = WSFTTND.DV_SOURCE_COMMIT_DT ,
EDW_CREATE_DTM = WSFTTND.EDW_CREATE_DTM ,
EDW_CREATE_USER = WSFTTND.EDW_CREATE_USER ,
EDW_UPDATE_DTM = WSFTTND.EDW_UPDATE_DTM ,
EDW_UPDATE_USER = WSFTTND.EDW_UPDATE_USER ,
UCRM_CASE_NUM = WSFTTND.UCRM_CASE_NUM,
ATTR_PRDT_AS_NEW_OR_RNWL_KEY = WSFTTND.ATTR_PRDT_AS_NEW_OR_RNWL_KEY ,
BK_SLS_TERR_ASSIGNMENT_TYPE_CD = WSFTTND.BK_SLS_TERR_ASGNMT_TYPE_CD,
BK_TRX_SPLIT_BU_ID = WSFTTND.TRX_SPLIT_BU_KEY,
SPLIT_1_OFFER_ATTRIBITION_PCT = WSFTTND.OA_SPLIT,
SPLIT_2_NEW_RENEW_PCT = WSFTTND.RTR_SPLIT,
SALES_MOTION_CD = WSFTTND.SALES_MOTION_CD  ,   
BK_OFFER_ATTRIBUTION_ID_INT = WSFTTND.SK_OFFER_ATTRIBUTION_ID_INT   ,
SK_RTR_ATTRIBUTION_ID  = WSFTTND.SK_RTR_ATTRIBUTION_ID_INT     ,
SK_TRX_SPLIT_ID_INT = WSFTTND.TRX_SPLIT_ID     ,
TOTAL_SPLIT_PCT  = WSFTTND.	TOTAL_SPLIT                   

 WHEN NOT MATCHED THEN
 INSERT 
 VALUES 
 (
WSFTTND.SLS_CREDIT_ASGNMT_SLS_TRX_KEY ,
WSFTTND.SO_SBSCRPTN_ITM_SLS_TRX_KEY   ,
WSFTTND.SK_OFFER_ATTRIBUTION_ID_INT   ,
'OPL',
WSFTTND.BK_SLS_TERR_ASGNMT_TYPE_CD    ,
WSFTTND.ATTR_PRDT_AS_NEW_OR_RNWL_KEY  ,
WSFTTND.SALES_CREDIT_USAGE_CD         ,
WSFTTND.SALES_CREDIT_UNALLOCATED_FLG  ,
WSFTTND.SLS_CREDIT_ASGNMT_MODE_CD     ,
WSFTTND.SK_TRX_SC_ID_INT              ,
WSFTTND.OVERLAY_TYPE                  ,
WSFTTND.BK_SALES_REP_NUM              ,
WSFTTND.BK_SLS_TERR_ASGNMT_TYPE_CD    ,
WSFTTND.SALES_TERRITORY_KEY           ,
WSFTTND.SRC_RPTD_RBK_OTM_TERR_ID_INT  ,
WSFTTND.SRC_RPTD_RBK_OTM_TERR_NAME    ,
WSFTTND.SRC_RPTD_RBK_OTM_TERR_TYPE_CD ,
WSFTTND.BK_SALES_CREDIT_TYPE_CODE     ,
WSFTTND.BK_CREATED_BY_ERP_USER_NAME   ,
WSFTTND.BK_SLS_CRDT_ASGNMT_RSN_CD     ,
WSFTTND.SCA_CREATE_DTM                ,
WSFTTND.DV_SCA_CREATE_DT              ,
WSFTTND.SCA_LAST_UPDATE_DTM           ,
WSFTTND.DV_SCA_LAST_UPDATE_DT         ,
WSFTTND.SPLIT_PCT                     ,
WSFTTND.EFFECTIVE_START_DTM           ,
WSFTTND.DV_EFFECTIVE_START_DT         ,
WSFTTND.EFFECTIVE_END_DTM             ,
WSFTTND.DV_EFFECTIVE_END_DT           ,
WSFTTND.SOURCE_COMMIT_DTM             ,
WSFTTND.DV_SOURCE_COMMIT_DT           ,
WSFTTND.UCRM_CASE_NUM                 ,
WSFTTND.TRX_SPLIT_BU_KEY              ,
WSFTTND.TRX_SPLIT_ID                  ,
WSFTTND.SALES_MOTION_CD               ,
WSFTTND.SK_RTR_ATTRIBUTION_ID_INT     ,
WSFTTND.OA_SPLIT                      ,
WSFTTND.RTR_SPLIT                     ,
WSFTTND.TOTAL_SPLIT                   ,
WSFTTND.RU_REBOK_CHANNEL_FLG          ,
WSFTTND.EDW_CREATE_DTM                ,
WSFTTND.EDW_CREATE_USER               ,
WSFTTND.EDW_UPDATE_DTM                ,
WSFTTND.EDW_UPDATE_USER       )