ETL Name:	wf_N_XAAS_SO_SBSCRPTN_ATTRBTN_NRT_NG.xml


Session 1: 	s_m_N_XAAS_SO_SBSCRPTN_ATTRBTN_NRT_NG
Mapping 1: 	m_N_XAAS_SO_SBSCRPTN_ATTRBTN_NRT_NG


Source1 Name : SQ_N_XAAS_SO_SBSCR_ATRB_NG_NRT_TV


Pre SQL : 



SQL Query : 
SELECT 
   WXSSA.BK_OFFER_ATTRIBUTION_ID_INT
   ,WXSSA.SK_TSL_UNIQUE_ID_INT
   ,WXSSA.ORDERED_PRODUCT_KEY
   ,WXSSA.ATTRIBUTION_FLG
   ,WXSSA.CISCO_BOOKED_FLG
   ,WXSSA.BUNDLE_TYPE_CD
   ,WXSSA.SKU_QTY
   ,WXSSA.ATTRIBUTED_UNIT_LIST_PRICE
   ,WXSSA.ATTRIBUTED_UNIT_NET_PRICE
   ,WXSSA.BOOKINGS_PCT
   ,WXSSA.ATTRIBUTION_PCT
   ,WXSSA.TSL_TRX_TYPE_CD
   ,WXSSA.TSL_EXCEPTION_REASON_CD
   ,WXSSA.ATTRIBUTED_EXTENDED_LIST_PRICE
   ,WXSSA.ATTRIBUTED_EXTENDED_NET_PRICE
   ,WXSSA.SBP_SUBSCRIPTION_CD
   ,WXSSA.SALES_VALUE_TRXL_AMT
   ,WXSSA.MTHLY_RCRR_REV_TRXL_AMT
   ,WXSSA.INCRMTL_MTHLY_RCRR_REVTRXL_AMT
   ,WXSSA.ANNUAL_RCRR_CHARGE_TRXL_AMT
   ,WXSSA.NON_RCRR_REV_TRXL_AMT
   ,WXSSA.INCRMTL_ANNL_RECUR_REVTRXL_AMT
   ,WXSSA.INCRMTL_MLTYR_RCRR_REVTRXL_AMT
   ,WXSSA.TOTAL_CONTRACT_VALUE_TRXL_AMT
   ,WXSSA.ATTRIBUTION_CD
   ,WXSSA.SK_ATTRIBUTION_ID_INT
   ,WXSSA.EXCEPTION_STATUS_CD
   ,WXSSA.SOURCE_COMMIT_DTM
   ,WXSSA.DV_SOURCE_COMMIT_DT
   ,WXSSA.SO_SBSCRPTN_ITM_SLS_TRX_KEY
   ,WXSSA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY
   ,WXSSA.CCW_WEB_ORDER_ID
   ,WXSSA.EXCEPTION_DETAIL_DESCR
   ,WXSSA.ORIGINAL_TRX_QTY
   ,WXSSA.EDW_CREATE_DTM
   ,WXSSA.EDW_CREATE_USER
   ,WXSSA.EDW_UPDATE_DTM
   ,WXSSA.EDW_UPDATE_USER
   ,WXSSA.ENTERPRISE_SKU_PRDT_KEY/*FY16-JUNE-CDR:thvarghe*/ 
    ,WXSSA.DV_NET_CHANGE_FLG
    ,WXSSA.START_TV_DTM    
    ,WXSSA.END_TV_DTM 
   ,WXSSA.PARENT_OFFER_ATTRIB_ID_INT /* 3 NRS MPOB columns added*/
   ,WXSSA.POB_TYPE_CD
   ,WXSSA.DV_POB_TOP_PRDT_KEY
   ,WXSSA.NRS_TRANSITION_FLG /*NRS PI3 CHANGES*/
 ,WXSSA.RECOGNIZED_SALES_VALUE_LOCAL_AMT
 ,WXSSA.ACV_ATTRIBUTION_PCT
  ,   WXSSA.PRICING_TERM_MTHS_CNT   /* SIGORANT ADDED AS PART OF Q2FY19 */ 
  ,WXSSA.AS_ARCHITECTURE_FLG
   FROM $$WORKDB.W_XAAS_SO_SBSCR_ATRB_NG_NRT WXSSA
    WHERE WXSSA.DML_TYPE='I'
    AND  NOT EXISTS
   (SELECT 1 FROM $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ATRB_NG_NRT_TV 
   NXSOA WHERE WXSSA.BK_OFFER_ATTRIBUTION_ID_INT=NXSOA.BK_OFFER_ATTRIBUTION_ID_INT AND NXSOA.START_TV_DTM=WXSSA.START_TV_DTM )


Post SQL : 



Target1 Name : N_XAAS_SO_SBSCRPN_ATRBN_NRT_TV1_NG


Pre SQL : 
UPDATE NXSSA FROM
  $$WORKDB.W_XAAS_SO_SBSCR_ATRB_NG_NRT WXSSA,
 $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ATRB_NG_NRT_TV NXSSA
  SET
  END_TV_DTM=WXSSA.END_TV_DTM,
  EDW_UPDATE_USER=WXSSA.EDW_UPDATE_USER,
  EDW_UPDATE_DTM=WXSSA.EDW_UPDATE_DTM
  WHERE 
  WXSSA.BK_OFFER_ATTRIBUTION_ID_INT=NXSSA.BK_OFFER_ATTRIBUTION_ID_INT
  AND
  WXSSA.START_TV_DTM=NXSSA.START_TV_DTM
  AND
  WXSSA.DML_TYPE='U'
  AND
  NXSSA.END_TV_DTM=CAST('3500-01-01 00:00:00' AS TIMESTAMP(0));


Post SQL : 
CALL COLLECT_STATS_WRAP('$$NRTNCRDB','N_XAAS_SO_SBSCR_ATRB_NG_NRT_TV','D');


Source2 Name : N_XAAS_SO_SBSCR_ATRB_NG_NRT


Pre SQL : 



SQL Query : 
SELECT 
    NXSSA.BK_OFFER_ATTRIBUTION_ID_INT
   ,NXSSA.SK_TSL_UNIQUE_ID_INT
   ,NXSSA.ORDERED_PRODUCT_KEY
   ,NXSSA.ATTRIBUTION_FLG
   ,NXSSA.CISCO_BOOKED_FLG
   ,NXSSA.BUNDLE_TYPE_CD
   ,NXSSA.SKU_QTY
   ,NXSSA.ATTRIBUTED_UNIT_LIST_PRICE
   ,NXSSA.ATTRIBUTED_UNIT_NET_PRICE
   ,NXSSA.BOOKINGS_PCT
   ,NXSSA.ATTRIBUTION_PCT
   ,NXSSA.TSL_TRX_TYPE_CD
   ,NXSSA.TSL_EXCEPTION_REASON_CD
   ,NXSSA.ATTRIBUTED_EXTENDED_LIST_PRICE
   ,NXSSA.ATTRIBUTED_EXTENDED_NET_PRICE
   ,NXSSA.SBP_SUBSCRIPTION_CD
   ,NXSSA.SALES_VALUE_TRXL_AMT
   ,NXSSA.MTHLY_RCRR_REV_TRXL_AMT
   ,NXSSA.INCRMTL_MTHLY_RCRR_REVTRXL_AMT
   ,NXSSA.ANNUAL_RCRR_CHARGE_TRXL_AMT
   ,NXSSA.NON_RCRR_REV_TRXL_AMT
   ,NXSSA.INCRMTL_ANNL_RECUR_REVTRXL_AMT
   ,NXSSA.INCRMTL_MLTYR_RCRR_REVTRXL_AMT
   ,NXSSA.TOTAL_CONTRACT_VALUE_TRXL_AMT
   ,NXSSA.ATTRIBUTION_CD
   ,NXSSA.SK_ATTRIBUTION_ID_INT
   ,NXSSA.EXCEPTION_STATUS_CD
   ,NXSSA.SOURCE_COMMIT_DTM
   ,NXSSA.DV_SOURCE_COMMIT_DT
   ,NXSSA.SO_SBSCRPTN_ITM_SLS_TRX_KEY
   ,NXSSA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY
   ,NXSSA.CCW_WEB_ORDER_ID
   ,NXSSA.EXCEPTION_DETAIL_DESCR
   ,NXSSA.ORIGINAL_TRX_QTY
   ,NXSSA.EDW_CREATE_DTM
   ,NXSSA.EDW_CREATE_USER
   ,NXSSA.EDW_UPDATE_DTM
   ,NXSSA.EDW_UPDATE_USER
   ,NXSSA.ENTERPRISE_SKU_PRDT_KEY/*FY16-JUNE-CDR:thvarghe*/
   ,NXSSA.DV_NET_CHANGE_FLG
  ,NXSSA.PARENT_OFFER_ATTRIB_ID_INT /* 3 NRS MPOB columns added*/
  ,NXSSA.POB_TYPE_CD
  ,NXSSA.DV_POB_TOP_PRDT_KEY
  ,NXSSA.NRS_TRANSITION_FLG /*NRS PI3 CHANGES*/
,NXSSA.RECOGNIZED_SALES_VALUE_LOCAL_AMT
,NXSSA.ACV_ATTRIBUTION_PCT
  ,   NXSSA.PRICING_TERM_MTHS_CNT   /* SIGORANT ADDED AS PART OF Q2FY19 */ 
    ,NXSSA.AS_ARCHITECTURE_FLG
   FROM $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ATRB_NG_NRT_TV NXSSA
   WHERE NXSSA.END_TV_DTM = CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))


Post SQL : 



Target2 Name : N_XAAS_SO_SBSCRPTN_ATTRBTN_NRT1_NG


Pre SQL : 
DELETE FROM $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ATRB_NG_NRT ALL;


Post SQL : 
CALL COLLECT_STATS_WRAP('$$NRTNCRDB','N_XAAS_SO_SBSCR_ATRB_NG_NRT','D');