ETL Name:	wf_N_XAAS_SLSCR_ASN_SLSTRX_NRT_NG.xml


Session 1: 	s_m_N_XAAS_SLSCR_ASN_SLSTRX_NRT_NG
Mapping 1: 	m_N_XAAS_SLSCR_ASN_SLSTRX_NRT_NG


Source1 Name : SQ_N_XAAS_SCA_SLS_TRX_NG_NRT


Pre SQL : 



SQL Query : 
SELECT
  WXSCALS.SLS_CREDIT_ASGNMT_SLS_TRX_KEY 
,WXSCALS.SO_SBSCRPTN_ITM_SLS_TRX_KEY   
,WXSCALS.BK_OFFER_ATTRIBUTION_ID_INT   
,WXSCALS.BK_ATTRIBUTION_SS_CD          
,WXSCALS.BK_SLS_TERR_ASSIGNMENT_TYPE_CD
,WXSCALS.ATTR_PRDT_AS_NEW_OR_RNWL_KEY  
,WXSCALS.SALES_CREDIT_USAGE_CD         
,WXSCALS.SALES_CREDIT_UNALLOCATED_FLG  
,WXSCALS.SLS_CREDIT_ASGNMT_MODE_CD     
,WXSCALS.SK_TRX_SPLIT_SC_ID_INT        
,WXSCALS.OVERLAY_TYPE                  
,WXSCALS.BK_SALES_REP_NUM              
,WXSCALS.BK_SLS_TERR_ASGNMT_TYPE_CD    
,WXSCALS.SALES_TERRITORY_KEY           
,WXSCALS.SRC_RPTD_REBOK_OTM_TERR_ID_INT
,WXSCALS.SRC_RPTD_REBOK_OTM_TERR_NAME  
,WXSCALS.SRC_RPTD_REBOK_OTM_TERR_TYP_CD
,WXSCALS.BK_SALES_CREDIT_TYPE_CODE     
,WXSCALS.BK_CREATED_BY_ERP_USER_NAME   
,WXSCALS.BK_SLS_CRDT_ASGNMT_RSN_CD     
,WXSCALS.SCA_CREATE_DTM                
,WXSCALS.DV_SCA_CREATE_DT              
,WXSCALS.SCA_LAST_UPDATE_DTM           
,WXSCALS.DV_SCA_LAST_UPDATE_DT         
,WXSCALS.SPLIT_PCT                     
,WXSCALS.EFFECTIVE_START_DTM           
,WXSCALS.DV_EFFECTIVE_START_DT         
,WXSCALS.EFFECTIVE_END_DTM             
,WXSCALS.DV_EFFECTIVE_END_DT           
,WXSCALS.SOURCE_COMMIT_DTM             
,WXSCALS.DV_SOURCE_COMMIT_DT           
,WXSCALS.UCRM_CASE_NUM                 
,WXSCALS.BK_TRX_SPLIT_BU_ID            
,WXSCALS.SK_TRX_SPLIT_ID_INT           
,WXSCALS.SALES_MOTION_CD               
,WXSCALS.SK_RTR_ATTRIBUTION_ID         
,WXSCALS.SPLIT_1_OFFER_ATTRIBITION_PCT 
,WXSCALS.SPLIT_2_NEW_RENEW_PCT         
,WXSCALS.TOTAL_SPLIT_PCT               
,WXSCALS.RU_REBOK_CHANNEL_FLG          
,WXSCALS.EDW_CREATE_DTM                
,WXSCALS.EDW_CREATE_USER               
,WXSCALS.EDW_UPDATE_DTM                
,WXSCALS.EDW_UPDATE_USER               
  FROM
   $$WORKDB.W_XAAS_SCA_SLS_TRX_NG_NRT WXSCALS
  WHERE WXSCALS.DML_TYPE='I' AND
  NOT EXISTS
  (
  SELECT 1 
  FROM
  $$NRTNCRDB.N_XAAS_SCA_SLS_TRX_NG_NRT  NXSCALS
        WHERE  NXSCALS.SLS_CREDIT_ASGNMT_SLS_TRX_KEY= WXSCALS.SLS_CREDIT_ASGNMT_SLS_TRX_KEY)


Post SQL : 



Target1 Name : N_XAAS_SCA_SLS_TRX_NG_NRT1


Pre SQL : 
UPDATE NSAT FROM 
  $$NRTNCRVWDB.N_XAAS_SCA_SLS_TRX_NG_NRT NSAT,
  $$WORKDB.W_XAAS_SCA_SLS_TRX_NG_NRT WSAT
  SET
  BK_SLS_TERR_ASGNMT_TYPE_CD=WSAT.BK_SLS_TERR_ASGNMT_TYPE_CD,
  EDW_UPDATE_DTM=CURRENT_TIMESTAMP(0),
  EDW_UPDATE_USER=USER,
  EFFECTIVE_END_DTM=WSAT.EFFECTIVE_END_DTM,
  DV_EFFECTIVE_END_DT=WSAT.DV_EFFECTIVE_END_DT,
  SLS_CREDIT_ASGNMT_MODE_CD=WSAT.SLS_CREDIT_ASGNMT_MODE_CD,
  BK_CREATED_BY_ERP_USER_NAME=WSAT.BK_CREATED_BY_ERP_USER_NAME,
  SPLIT_PCT=WSAT.SPLIT_PCT,
  BK_SALES_CREDIT_TYPE_CODE=WSAT.BK_SALES_CREDIT_TYPE_CODE,
  SO_SBSCRPTN_ITM_SLS_TRX_KEY=WSAT.SO_SBSCRPTN_ITM_SLS_TRX_KEY,
  BK_SALES_REP_NUM=WSAT.BK_SALES_REP_NUM,
  SALES_TERRITORY_KEY=WSAT.SALES_TERRITORY_KEY,
  SCA_CREATE_DTM = WSAT.SCA_CREATE_DTM,
  DV_SCA_CREATE_DT=WSAT.DV_SCA_CREATE_DT,
  SK_TRX_SPLIT_SC_ID_INT=WSAT.SK_TRX_SPLIT_SC_ID_INT,
  EFFECTIVE_START_DTM  = WSAT.EFFECTIVE_START_DTM,
  DV_EFFECTIVE_START_DT  = WSAT.DV_EFFECTIVE_START_DT,
  BK_SLS_CRDT_ASGNMT_RSN_CD = WSAT.BK_SLS_CRDT_ASGNMT_RSN_CD,
  SALES_CREDIT_USAGE_CD   = WSAT.SALES_CREDIT_USAGE_CD,   
  SALES_CREDIT_UNALLOCATED_FLG = WSAT.SALES_CREDIT_UNALLOCATED_FLG,
  SRC_RPTD_REBOK_OTM_TERR_ID_INT = WSAT.SRC_RPTD_REBOK_OTM_TERR_ID_INT,
  SRC_RPTD_REBOK_OTM_TERR_NAME    = WSAT.SRC_RPTD_REBOK_OTM_TERR_NAME,
  SRC_RPTD_REBOK_OTM_TERR_TYP_CD = WSAT.SRC_RPTD_REBOK_OTM_TERR_TYP_CD,
  OVERLAY_TYPE=WSAT.OVERLAY_TYPE,
  SCA_LAST_UPDATE_DTM= WSAT.SCA_LAST_UPDATE_DTM    ,
  DV_SCA_LAST_UPDATE_DT= WSAT.DV_SCA_LAST_UPDATE_DT,
  RU_REBOK_CHANNEL_FLG= WSAT.RU_REBOK_CHANNEL_FLG,
  SOURCE_COMMIT_DTM= WSAT.SOURCE_COMMIT_DTM,
  DV_SOURCE_COMMIT_DT= WSAT.DV_SOURCE_COMMIT_DT,
  UCRM_CASE_NUM = WSAT.UCRM_CASE_NUM,
  BK_TRX_SPLIT_BU_ID = WSAT.BK_TRX_SPLIT_BU_ID,
  SK_TRX_SPLIT_ID_INT = WSAT.SK_TRX_SPLIT_ID_INT,
  BK_OFFER_ATTRIBUTION_ID_INT = WSAT.BK_OFFER_ATTRIBUTION_ID_INT,
  SPLIT_1_OFFER_ATTRIBITION_PCT = WSAT.SPLIT_1_OFFER_ATTRIBITION_PCT,
  SK_RTR_ATTRIBUTION_ID = WSAT.SK_RTR_ATTRIBUTION_ID,
  SPLIT_2_NEW_RENEW_PCT = WSAT.SPLIT_2_NEW_RENEW_PCT,
  TOTAL_SPLIT_PCT = WSAT.TOTAL_SPLIT_PCT,
  ATTR_PRDT_AS_NEW_OR_RNWL_KEY = WSAT.ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
  SALES_MOTION_CD = WSAT.SALES_MOTION_CD
  WHERE
  WSAT.DML_TYPE='I'
  AND NSAT.SLS_CREDIT_ASGNMT_SLS_TRX_KEY= WSAT.SLS_CREDIT_ASGNMT_SLS_TRX_KEY;


Post SQL : 
UPDATE NSAT FROM 
  $$NRTNCRVWDB.N_XAAS_SCA_SLS_TRX_NG_NRT NSAT,
  $$WORKDB.W_XAAS_SCA_SLS_TRX_NG_NRT WSAT
  SET 
  EDW_UPDATE_DTM   =      CURRENT_TIMESTAMP(0)     ,
  EDW_UPDATE_USER =        USER     ,   
  EFFECTIVE_END_DTM =WSAT.EFFECTIVE_END_DTM,
  DV_EFFECTIVE_END_DT =WSAT.DV_EFFECTIVE_END_DT  
  WHERE NSAT.SALES_TERRITORY_KEY=WSAT.SALES_TERRITORY_KEY
  AND NSAT.BK_SALES_REP_NUM=WSAT.BK_SALES_REP_NUM
  AND NSAT.SO_SBSCRPTN_ITM_SLS_TRX_KEY=WSAT.SO_SBSCRPTN_ITM_SLS_TRX_KEY
  AND NSAT.BK_SLS_TERR_ASGNMT_TYPE_CD=WSAT.BK_SLS_TERR_ASGNMT_TYPE_CD
  AND WSAT.DML_TYPE='U' AND WSAT.ACTION_CODE='Y'
  AND NSAT.EFFECTIVE_END_DTM='3500-01-01 00:00:00';
 
 
 
 /*Update to End date default sales creditiing record*/
 UPDATE NSAT FROM                                                                   
  $$NRTNCRVWDB.N_XAAS_SCA_SLS_TRX_NG_NRT NSAT,                                                                  
 (                                                                         
 SELECT SO_SBSCRPTN_ITM_SLS_TRX_KEY,MIN(WSC.SCA_LAST_UPDATE_DTM) AS SCA_LAST_UPDATE_DTM FROM $$WORKDB.W_XAAS_SCA_SLS_TRX_NG_NRT WSC                                                             
   GROUP BY 1                                                                  
 )WSAT                                                              
 SET                                                                    
  EFFECTIVE_END_DTM=(WSAT.SCA_LAST_UPDATE_DTM-INTERVAL '1' SECOND),                                                               
 DV_EFFECTIVE_END_DT= (CAST(WSAT.SCA_LAST_UPDATE_DTM-INTERVAL '1' SECOND AS DATE)),                                                              
 EDW_UPDATE_DTM=CURRENT_TIMESTAMP(0),                                                             
 EDW_UPDATE_USER=USER                                                                     
 WHERE                                                                           
  WSAT.SO_SBSCRPTN_ITM_SLS_TRX_KEY=NSAT.SO_SBSCRPTN_ITM_SLS_TRX_KEY                                                                          
  AND NSAT.SK_TRX_SPLIT_SC_ID_INT<0 
 AND NSAT.SALES_CREDIT_UNALLOCATED_FLG='D' AND NSAT.EFFECTIVE_END_DTM = '3500-01-01 00:00:00';
  
  UPDATE NXSCANRT
 FROM $$NRTNCRVWDB.N_XAAS_SCA_SLS_TRX_NG_NRT NXSCANRT,
 (
 SELECT NSCA.SLS_CREDIT_ASGNMT_SLS_TRX_KEY, RSH.SALES_TERRITORY_KEY 
 FROM (SELECT * FROM $$NRTNCRVWDB.N_XAAS_SO_SBCR_ITM_STRX_NRT_TV WHERE END_TV_DTM ='3500-01-01 00:00:00') TSL
 INNER JOIN $$NRTNCRVWDB.N_SALES_ORDER_LINE_NRT SOL
   ON TSL.MINOR_LN_EXAAS_SUBSCR_SOL_KEY = SOL.SALES_ORDER_LINE_KEY
 AND TSL.SALES_CHANNEL_CD = 'Two Tier Distributor' 
 INNER JOIN $$NRTNCRVWDB.N_SALES_ORDER_NRT SO
 ON SO.SALES_ORDER_KEY = SOL.SALES_ORDER_KEY
                 AND SO.CUSTOMER_PO_TYPE_CD IN ('Resale','Stocking')
 INNER JOIN (
 SEL * 
  FROM $$NRTNCRVWDB.N_XAAS_SCA_SLS_TRX_NG_NRT SCA 
  WHERE  SCA.SK_TRX_SPLIT_SC_ID_INT < 0   and SK_TRX_SPLIT_SC_ID_INT > -1000000000
   AND SCA.EDW_CREATE_DTM >CURRENT_TIMESTAMP(0) - INTERVAL  '2' DAY ) NSCA
                 ON NSCA.SO_SBSCRPTN_ITM_SLS_TRX_KEY = TSL.SO_SBSCRPTN_ITM_SLS_TRX_KEY
 INNER JOIN (
 SELECT SALES_TERRITORY_KEY  
  FROM $$COMREFVWDB.R_SALES_HIERARCHY 
  WHERE L6_SALES_TERRITORY_DESCR ='WW Distribution-MISCL6') RSH 
   ON (RSH.SALES_TERRITORY_KEY <> NSCA.SALES_TERRITORY_KEY)
 ) DRVD
 SET SALES_TERRITORY_KEY = DRVD.SALES_TERRITORY_KEY,
   EDW_UPDATE_DTM=CURRENT_TIMESTAMP(0)
 WHERE NXSCANRT.SLS_CREDIT_ASGNMT_SLS_TRX_KEY = DRVD.SLS_CREDIT_ASGNMT_SLS_TRX_KEY  
 ;
 
  CALL COLLECT_STATS_WRAP('$$NRTNCRVWDB','N_XAAS_SCA_SLS_TRX_NG_NRT','D');