ETL Name:	wf_W_XAAS_SLSCR_ASN_SLSTRX_NRT_NG.xml


Session 1: 	s_m_W_XAAS_SLSCR_ASN_SLSTRX_NRT_NG
Mapping 1: 	m_W_XAAS_SLSCR_ASN_SLSTRX_NRT_NG


Source1 Name : SQ_SM_XAAS_SLSCR_ASN_SLSTRX_NRT_NG


Pre SQL : 
COLLECT STATS ON $$NRTSTGDB.ST_OTM_SLS_CRDT_TSL_XAAS_NRT_NG;


SQL Query : 
SELECT 
  RANK() OVER (ORDER BY TRX_SPLIT_SC_ID) + MAX_KEY  SLS_CREDIT_ASGNMT_SLS_TRX_KEY , 
  TRX_SPLIT_SC_ID    AS SK_TRX_SPLIT_SC_ID_INT,
  CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM,
  USER AS  EDW_CREATE_USER
  FROM 
  $$NRTSTGDB.ST_OTM_SLS_CRDT_TSL_XAAS_NRT_NG   SOSCTX,
  (SELECT COALESCE(MAX(SLS_CREDIT_ASGNMT_SLS_TRX_KEY ),0 )   MAX_KEY FROM  $$TRANSLATIONDB.SM_XAAS_SCA_SLS_TRX_NG_NRT) SMXSB
  WHERE  NOT EXISTS 
  ( SELECT 1 FROM $$TRANSLATIONDB.SM_XAAS_SCA_SLS_TRX_NG_NRT SMXSCA
  WHERE SOSCTX.TRX_SPLIT_SC_ID=SMXSCA.SK_TRX_SPLIT_SC_ID_INT
  )


Post SQL : 



Target1 Name : SM_XAAS_SCA_SLS_TRX_NG_NRT


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP ('$$TRANSLATIONDB','SM_XAAS_SCA_SLS_TRX_NG_NRT','D');


Source2 Name : SQ_EX_OTM_SLS_CRDT_TSL_XAAS_NRT_NG1


Pre SQL : 



SQL Query : 
SELECT 
   CDB_DEQUEUE_TIME              ,
   CREATION_DATE                 ,
   DEBIT_CREDIT_CODE             ,
   ETL_PROCESS_DTM               ,
   LAST_UPDATE_DATE              ,
   LATEST_SC_FLAG                ,
   ORDER_LINE_ID                 ,
   OTM_TERR_ID                   ,
   OTM_TERR_NAME                 ,
   OTM_TERR_TYPE_CODE            ,
   REBOK_CHANNEL_FLAG            ,
   SALESREP_NUMBER               ,
   SC_ASSIGNMENT_MODE_CODE       ,
   SC_LAST_UPD_DATE              ,
   SC_REASON_CODE                ,
   SC_SPLIT_PERCENT              ,
   SC_TYPE_CODE                  ,
   SC_UNALLOCATED                ,
   SC_USAGE_CODE                 ,
   SHR_NODE_ID                   ,
   TERRITORY_TYPE_CODE           ,
   TRX_ORIG_CODE                 ,
   TRX_SPLIT_SC_ID                     ,
   TRX_SOURCE_TYPE               ,
   USER_NAME                     ,
   ROLLUP_FLAG                   ,
   SC_ID                         ,
   SC_DUPLICATE_FLAG             ,
   CHANGE_TYPE_CODE              ,
   TRX_VERSION_CHANGE_FLG        ,
   DISTRIBUTOR_BUCKET_FLG        ,
   TRX_ID                        ,
   START_DTM                     ,
   EXPIRATION_DTM ,
   SOURCE_TRX_ID,
   SOURCE_COMMIT_DTM,
   DV_SOURCE_COMMIT_DT,
   UCRM_CASE_NUM,
   TRX_SPLIT_BU_KEY,
   TRX_SPLIT_ID,
   SPLIT_1_BU_KEY,
   SPLIT_1_PERCENTAGE,
   SPLIT_2_BU_KEY,
   SPLIT_2_PERCENTAGE,
   TOTAL_SPLIT
   FROM 
   $$EXCEPDB.EX_OTM_SLS_CRDT_TSL_XAAS_NRT_NG  STGE
    WHERE  NOT EXISTS
   (SELECT 1 FROM
   $$NRTSTGDB.ST_OTM_SLS_CRDT_TSL_XAAS_NRT_NG SOSCTX
   WHERE STGE.TRX_SPLIT_SC_ID=SOSCTX.TRX_SPLIT_SC_ID
   )


Post SQL : 



Target2 Name : ST_OTM_SLS_CRDT_TSL_XAAS_NRT_NG


Pre SQL : 



Post SQL : 
COLLECT STATS ON $$NRTSTGDB.ST_OTM_SLS_CRDT_TSL_XAAS_NRT_NG;


Source3 Name : SQ_W_XAAS_SLSCR_ASN_SLSTRX_NRT_NG


Pre SQL : 



SQL Query : 
SELECT
   SM.SLS_CREDIT_ASGNMT_SLS_TRX_KEY  AS SLS_CR_ASSGN_SALES_CREDIT_KEY,
   SMXSS.SO_SBSCRPTN_ITM_SLS_TRX_KEY,
   COALESCE(STG.SPLIT_1_BU_KEY,-9999) AS BK_OFFER_ATTRIBUTION_ID_INT,
   'OPL' AS BK_ATTRIBUTION_SS_CD,
   STG.TERRITORY_TYPE_CODE AS BK_SLS_TERR_ASSIGNMENT_TYPE_CD,
   COALESCE( RTR.ATTR_PRDT_AS_NEW_OR_RNWL_KEY, -999 )  AS ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
   COALESCE(STG.SC_USAGE_CODE,'R') AS SALES_CREDIT_USAGE_CD,
   COALESCE(STG.SC_UNALLOCATED,'N') AS SALES_CREDIT_UNALLOCATED_FLG, 
   COALESCE(STG.SC_ASSIGNMENT_MODE_CODE,'UNKNOWN') AS SLS_CREDIT_ASGNMT_MODE_CD ,
   STG.TRX_SPLIT_SC_ID AS SK_TRX_SPLIT_SC_ID_INT,
   CASE NSAT.BK_SLS_TERR_ASSIGNMENT_TYPE_CD 
   WHEN 'DR' THEN 'N'
   ELSE 'Y'
   END  OVERLAY_TYPE,
   NESR.SALES_REP_NUMBER AS SALES_REP_NUM,
   STG.TERRITORY_TYPE_CODE AS BK_SLS_TERR_ASGNMT_TYPE_CD,
   NSTT.SALES_TERRITORY_KEY AS SALES_TERRITORY_KEY,
   STG.OTM_TERR_ID AS SRC_RPTD_REBOK_OTM_TERR_ID_INT,
   STG.OTM_TERR_NAME AS SRC_RPTD_REBOK_OTM_TERR_NAME,  
   STG.OTM_TERR_TYPE_CODE AS SRC_RPTD_REBOK_OTM_TERR_TYP_CD,
   COALESCE (NSCT.BK_SALES_CREDIT_TYPE_CODE,'UNKNOWN') AS BK_SALES_CREDIT_TYPE_CODE,
   COALESCE (NEU.ERP_USER_NAME,'UNKNOWN') AS BK_CREATED_BY_ERP_USER_NAME,
   COALESCE (NSCAR.BK_SLS_CRDT_ASGNMNT_REASON_CD,'UNKNOWN') AS BK_SLS_CRDT_ASGNMT_RSN_CD, 
   COALESCE(STG.CREATION_DATE, CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))) AS SCA_CREATE_DTM,
   CAST(COALESCE(STG.CREATION_DATE, CAST('3500-01-01' AS DATE) ) AS DATE) DV_SCA_CREATE_DT,
   COALESCE(STG.LAST_UPDATE_DATE, CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))) AS SCA_LAST_UPDATE_DTM,   
   CAST(COALESCE(STG.LAST_UPDATE_DATE, CAST('3500-01-01' AS DATE) ) AS DATE) AS DV_SCA_LAST_UPDATE_DT,
   (STG.SC_SPLIT_PERCENT*100) AS SPLIT_PCT,
   COALESCE(STG.START_DTM,CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))) AS EFFECTIVE_START_DTM,
   CAST(COALESCE(STG.START_DTM , CAST('3500-01-01' AS DATE) ) AS DATE) AS  DV_EFFECTIVE_START_DT ,       
    (
  CASE 
   WHEN STG.LATEST_SC_FLAG='N' 
   AND STG.CREATION_DATE<>STG.LAST_UPDATE_DATE THEN COALESCE((STG.LAST_UPDATE_DATE- INTERVAL '1' SECOND),
    CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)))
   WHEN STG.LATEST_SC_FLAG='N' 
   AND STG.CREATION_DATE=STG.LAST_UPDATE_DATE THEN COALESCE(STG.LAST_UPDATE_DATE,
    CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)))
   WHEN STG.LATEST_SC_FLAG='Y' 
   AND STG.DEBIT_CREDIT_CODE='DEBIT' THEN COALESCE((STG.LAST_UPDATE_DATE- INTERVAL '1' SECOND),
    CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)))
   WHEN STG.LATEST_SC_FLAG='Y' THEN CAST('3500-01-01 00:00:00' AS TIMESTAMP(0) )
   END)  AS EFFECTIVE_END_DTM,
    CAST(EFFECTIVE_END_DTM AS DATE) AS DV_EFFECTIVE_END_DT ,
	 COALESCE(STG.SOURCE_COMMIT_DTM,CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))) AS SOURCE_COMMIT_DTM,
	    CAST(COALESCE(STG.DV_SOURCE_COMMIT_DT, CAST('3500-01-01' AS DATE) ) AS DATE) AS DV_SOURCE_COMMIT_DT,
    STG.UCRM_CASE_NUM AS UCRM_CASE_NUM,
	COALESCE(STG.TRX_SPLIT_BU_KEY,-999) as BK_TRX_SPLIT_BU_ID,
	COALESCE(STG.TRX_SPLIT_ID,-999) as SK_TRX_SPLIT_ID_INT,
	COALESCE( RTR.SALES_MOTION_CD, 'UNKNOWN') SALES_MOTION_CD,
	COALESCE(STG.SPLIT_2_BU_KEY,-999) AS SK_RTR_ATTRIBUTION_ID ,
	COALESCE(STG.SPLIT_1_PERCENTAGE,1.00) AS SPLIT_1_OFFER_ATTRIBITION_PCT,
	COALESCE(STG.SPLIT_2_PERCENTAGE,1.00) AS SPLIT_2_NEW_RENEW_PCT ,
	COALESCE(STG.TOTAL_SPLIT,1.00) AS TOTAL_SPLIT_PCT ,
   COALESCE (STG.REBOK_CHANNEL_FLAG,'N') AS RU_REBOK_CHANNEL_FLG, 
  

   CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM,
   USER  AS EDW_CREATE_USER ,
   CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM ,
   USER AS EDW_UPDATE_USER,
   COALESCE(STG.START_DTM,CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))) AS START_TV_DTM,
    (
  CASE 
   WHEN STG.LATEST_SC_FLAG='N' 
   AND STG.CREATION_DATE<>STG.LAST_UPDATE_DATE THEN COALESCE((STG.LAST_UPDATE_DATE- INTERVAL '1' SECOND),
    CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)))
   WHEN STG.LATEST_SC_FLAG='N' 
   AND STG.CREATION_DATE=STG.LAST_UPDATE_DATE THEN COALESCE(STG.LAST_UPDATE_DATE,
    CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)))
   WHEN STG.LATEST_SC_FLAG='Y' 
   AND STG.DEBIT_CREDIT_CODE='DEBIT' THEN COALESCE((STG.LAST_UPDATE_DATE- INTERVAL '1' SECOND),
    CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)))
   WHEN STG.LATEST_SC_FLAG='Y' THEN CAST('3500-01-01 00:00:00' AS TIMESTAMP(0) )
   END)  AS END_TV_DTM,
   STG.LATEST_SC_FLAG AS ACTION_CODE,
   CASE
   WHEN STG.DEBIT_CREDIT_CODE='CREDIT' THEN 'I'
   WHEN STG.DEBIT_CREDIT_CODE='DEBIT' THEN 'U'
   END AS DML_TYPE      
   FROM 
   $$NRTSTGDB.ST_OTM_SLS_CRDT_TSL_XAAS_NRT_NG  STG
   INNER JOIN  $$ETLVWDB.SM_XAAS_SO_SBSCR_ITMSLSTRX_NRT  SMXSS 
   ON STG.SOURCE_TRX_ID=SMXSS.SK_TRX_ID_INT
   INNER JOIN $$TRANSLATIONDB.SM_XAAS_SCA_SLS_TRX_NG_NRT SM
   ON STG.TRX_SPLIT_SC_ID =SM.SK_TRX_SPLIT_SC_ID_INT
   INNER JOIN $$SLSORDVWDB.N_SALES_CREDIT_TYPE_TV NSCT
   ON STG.SC_TYPE_CODE=NSCT.BK_SALES_CREDIT_TYPE_CODE 
   AND NSCT.END_TV_DATE='3500-01-01'
   INNER JOIN $$COMREFVWDB.N_ERP_USER NEU
   ON STG.USER_NAME=NEU.ERP_USER_NAME
   INNER JOIN $$COMREFVWDB.N_ERP_SALES_REP_TV NESR
  /* ON STG.SALESREP_NUMBER=NESR.SALES_REP_NUMBER*/
 ON STG.SALESREP_NUMBER=CAST(CAST(COALESCE(NULLIF(NESR.SALES_REP_NUMBER,'UNKNOWN'),-999) AS INTEGER) AS VARCHAR(30))
   AND NESR.END_TV_DATE='3500-01-01'
   INNER JOIN $$COMREFVWDB.N_SALES_TERRITORY_TV NSTT
   ON STG.SHR_NODE_ID=NSTT.SHARE_NODE_ID_INT
   AND NSTT.END_TV_DATE='3500-01-01'
   INNER JOIN $$SLSORDVWDB.N_SALES_CREDIT_ASGNMNT_REASON NSCAR
   ON COALESCE(STG.SC_REASON_CODE,'UNKNOWN')=COALESCE(NSCAR.BK_SLS_CRDT_ASGNMNT_REASON_CD,'UNKNOWN')
   INNER JOIN $$COMREFVWDB.N_SALES_TERR_ASSIGNMENT_TYPE NSAT
   ON STG.TERRITORY_TYPE_CODE=NSAT.BK_SLS_TERR_ASSIGNMENT_TYPE_CD   
   LEFT JOIN (SELECT * FROM $$ETLVWDB.EL_ATTR_PRDT_AS_NEW_OR_RNWL_NRT  QUALIFY ROW_NUMBER() OVER(PARTITION BY SK_RTR_ATTRIBUTION_ID ORDER BY EDW_UPDATE_DTM DESC)=1)RTR
   ON STG.SPLIT_2_BU_KEY = RTR.SK_RTR_ATTRIBUTION_ID


Post SQL : 



Target3 Name : W_XAAS_SCA_SLS_TRX_NG_NRT


Pre SQL : 
DELETE FROM $$WORKDB.W_XAAS_SCA_SLS_TRX_NG_NRT ALL;


Post SQL : 
COLLECT STATS ON $$WORKDB.W_XAAS_SCA_SLS_TRX_NG_NRT


Source4 Name : SQ_ST_OTM_SLS_CRDT_TSL_XAAS_NRT_NG


Pre SQL : 



SQL Query : 
SELECT 
  CDB_DEQUEUE_TIME              ,
  CREATION_DATE                 ,
  DEBIT_CREDIT_CODE             ,
  ETL_PROCESS_DTM               ,
  LAST_UPDATE_DATE              ,
  LATEST_SC_FLAG                ,
  ORDER_LINE_ID                 ,
  OTM_TERR_ID                   ,
  OTM_TERR_NAME                 ,
  OTM_TERR_TYPE_CODE            ,
  REBOK_CHANNEL_FLAG            ,
  SALESREP_NUMBER               ,
  SC_ASSIGNMENT_MODE_CODE       ,
  SC_LAST_UPD_DATE              ,
  SC_REASON_CODE                ,
  SC_SPLIT_PERCENT              ,
  SC_TYPE_CODE                  ,
  SC_UNALLOCATED                ,
  SC_USAGE_CODE                 ,
  SHR_NODE_ID                   ,
  TERRITORY_TYPE_CODE           ,
  TRX_ORIG_CODE                 ,
  TRX_SPLIT_SC_ID                     ,
  TRX_SOURCE_TYPE               ,
  USER_NAME                     ,
  ROLLUP_FLAG                   ,
  SC_ID                         ,
  SC_DUPLICATE_FLAG             ,
  CHANGE_TYPE_CODE              ,
  TRX_VERSION_CHANGE_FLG        ,
  DISTRIBUTOR_BUCKET_FLG        ,
  TRX_ID                        ,
  START_DTM                     ,
  EXPIRATION_DTM ,
  'RI' AS  EXCEPTION_TYPE,
  SOURCE_TRX_ID,
  SOURCE_COMMIT_DTM,
  DV_SOURCE_COMMIT_DT,
  UCRM_CASE_NUM ,
  TRX_SPLIT_BU_KEY,
   TRX_SPLIT_ID,
   SPLIT_1_BU_KEY,
   SPLIT_1_PERCENTAGE,
   SPLIT_2_BU_KEY,
   SPLIT_2_PERCENTAGE,
   TOTAL_SPLIT
  FROM 
  $$NRTSTGDB.ST_OTM_SLS_CRDT_TSL_XAAS_NRT_NG  STG
  WHERE NOT EXISTS  (
  SELECT 1 FROM $$ETLVWDB.SM_XAAS_SO_SBSCR_ITMSLSTRX_NRT  NXXT
  WHERE NXXT.SK_TRX_ID_INT=STG.SOURCE_TRX_ID)
  OR  NOT EXISTS ( SELECT 1 FROM  $$TRANSLATIONDB.SM_XAAS_SCA_SLS_TRX_NG_NRT  SM
  WHERE STG.TRX_SPLIT_SC_ID=SM.SK_TRX_SPLIT_SC_ID_INT)
  OR NOT EXISTS(
  SELECT 1 FROM  $$SLSORDVWDB.N_SALES_CREDIT_TYPE_TV NSCT
  WHERE STG.SC_TYPE_CODE=NSCT.BK_SALES_CREDIT_TYPE_CODE 
  AND NSCT.END_TV_DATE='3500-01-01')
  OR NOT EXISTS ( SELECT 1 FROM  $$COMREFVWDB.N_ERP_USER NEU
  WHERE  STG.USER_NAME=NEU.ERP_USER_NAME)
  OR NOT EXISTS ( SELECT 1 FROM  $$COMREFVWDB.N_ERP_SALES_REP_TV NESR
  WHERE STG.SALESREP_NUMBER=CAST(CAST(COALESCE(NULLIF(NESR.SALES_REP_NUMBER,'UNKNOWN'),-999) AS INTEGER) AS VARCHAR(30))
  AND NESR.END_TV_DATE='3500-01-01')
  OR NOT EXISTS( SELECT 1 FROM  $$COMREFVWDB.N_SALES_TERRITORY_TV NSTT
  WHERE STG.SHR_NODE_ID=NSTT.SHARE_NODE_ID_INT
  AND NSTT.END_TV_DATE='3500-01-01')
  OR NOT EXISTS (SELECT 1 FROM $$SLSORDVWDB.N_SALES_CREDIT_ASGNMNT_REASON NSCAR
  WHERE 
  STG.SC_REASON_CODE=NSCAR.BK_SLS_CRDT_ASGNMNT_REASON_CD)
  OR NOT EXISTS( SELECT 1 FROM  $$COMREFVWDB.N_SALES_TERR_ASSIGNMENT_TYPE NSAT
  WHERE 
  STG.TERRITORY_TYPE_CODE=NSAT.BK_SLS_TERR_ASSIGNMENT_TYPE_CD)
  OR NOT EXISTS ( SELECT 1 FROM $$ETLVWDB.EL_ATTR_PRDT_AS_NEW_OR_RNWL_NRT RTR
   WHERE STG.SPLIT_2_BU_KEY = RTR.SK_RTR_ATTRIBUTION_ID )


Post SQL : 



Target4 Name : EX_OTM_SLS_CRDT_TSL_XAAS_NRT_NG


Pre SQL : 
DELETE FROM $$EXCEPDB.EX_OTM_SLS_CRDT_TSL_XAAS_NRT_NG ALL;


Post SQL : 
COLLECT STATS ON $$EXCEPDB.EX_OTM_SLS_CRDT_TSL_XAAS_NRT_NG;