ETL Name:	wf_W_XAAS_SO_SBSCRPTN_ATTRBTN_NRT_NG.xml


Session 1: 	s_m_W_XAAS_SO_SBSCRPTN_ATTRBTN_NRT_NG
Mapping 1: 	m_W_XAAS_SO_SBSCRPTN_ATTRBTN_NRT_NG


Source1 Name : SQ_WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG


Pre SQL : 



SQL Query : 
SELECT 
         SXXOA.BATCH_ID
       , SXXOA.ATTRIBUTION_ID
       --, SXXOA.ORDER_NUMBER
       , SXXOA.LINE_REF_NUMBER
       , SXXOA.DATA_SOURCE
       , SXXOA.TRX_ID
       , SXXOA.PARENT_TRX_ID
       --, SXXOA.ORDERED_ITEM
       , SXXOA.INVENTORY_ITEM_ID
       , SXXOA.ATTRIBUTION_FLAG
       --, SXXOA.CISCO_BOOKED_FLAG
       , SXXOA.BUNDLE_TYPE
       , SXXOA.QUANTITY
       , SXXOA.ATTRIBUTED_UNIT_LIST_PRICE
       , SXXOA.ATTRIBUTED_UNIT_NET_PRICE
       , SXXOA.RECOGNIZED_PCT
       , SXXOA.ATTRIBUTED_PCT
       --, SXXOA.PUBLISH_FLAG
       , SXXOA.ATTRIBUTION_TYPE
       --, SXXOA.CREATED_BY
       --, SXXOA.CREATION_DATE
       --, SXXOA.LAST_UPDATED_BY
       --, SXXOA.LAST_UPDATE_DATE
       --, SXXOA.ORIG_OA_ATTRIB_ID
       , SXXOA.ACTION_CODE
       , SXXOA.CREATE_DATETIME
       --, SXXOA.SOURCE_DML_TYPE
       --, SXXOA.SOURCE_COMMIT_TIME
       , CASE WHEN (SXXOA.TRX_ID IS NOT NULL AND SXXOA.PARENT_TRX_ID IS NOT NULL)
    THEN  NXSSIST1.SO_SBSCRPTN_ITM_SLS_TRX_KEY
         ELSE -999 END  AS SO_SBSCRPTN_ITM_SLS_TRX_KEY 
       , NP.ITEM_KEY AS ORDERED_PRODUCT_KEY
       , NXSSIST.SUBSCRIPTION_PRODUCT_KEY AS BUNDLE_PRODUCT_KEY
       , 'SRC' AS DV_DATA_SRC_CD
       , 'Y' AS VALID_FLG
       , 'NE' AS EXCEPTION_TYPE
       , SXXOA.EXCEPTION_CODE AS EXCEPTION_CODE
       , NXSSIST.SO_SBSCRPTN_ITM_SLS_TRX_KEY AS PARENT_SO_SBSCRP_ITMSLSTRX_KEY
    ,SXXOA.ATTRIBUTED_EXT_LIST_PRICE
    ,SXXOA.ATTRIBUTED_EXT_NET_PRICE
    ,SXXOA.WEB_ORDER_ID
    ,NXSSIST.SRC_RPTD_SBSCRPTN_CD
    ,SXXOA.ATTRIBUTED_SALES_VALUE
    ,SXXOA.ATTRIBUTED_MRR
    ,SXXOA.ATTRIBUTED_IMRR
    ,SXXOA.ATTRIBUTED_ARR
    ,SXXOA.ATTRIBUTED_NRR
    ,SXXOA.ATTRIBUTED_IARR
    ,SXXOA.ATTRIBUTED_IMYARR
    ,SXXOA.TCV
    ,SXXOA.ATTRIBUTION_CODE
    ,CASE WHEN SXXOA.ATTRIBUTION_CODE IN ('OFFSET TOP SKU','OFFSET SUB SKU') THEN 'OFFSET' 
    WHEN SXXOA.ATTRIBUTION_CODE IN ('ATTRIBUTED SUB SKU', 'DEAL ATTRIBUTED SUB SKU') THEN 'ATTRIBUTED'
     WHEN SXXOA.ATTRIBUTION_CODE IN ('ATTRIBUTED MULTI LEVEL SUB SKU','DEAL ATTRIBUTED MULTI LEVEL SUB SKU') THEN 'BIB'
     WHEN SXXOA.ATTRIBUTION_CODE IN ('OFFSET MULTI LEVEL SUB SKU','DEAL OFFSET MULTI LEVEL SUB SKU') THEN 'BIB OFFSET'
     ELSE 'UNKNOWN' END AS ATTRIBUTION_CD  /* NRS MPOB Change */
    ,SXXOA.LINKED_ATTRIB_ID
    ,SXXOA.EXCEPTION_DETAIL
    ,NXSSIST.ACTION_CD
    ,NXSSIST.TRX_REASON_CD
    ,NXSSIST.SALES_VALUE_TRXL_AMT
    ,SXXOA.ENT_INVENTORY_ITEM_ID
    ,CASE WHEN ATTRIBUTION_CD IN ('BIB OFFSET', 'OFFSET' ) THEN NP.ITEM_KEY ELSE COALESCE(NP_ENT.ITEM_KEY,NXSSIST.SUBSCRIPTION_PRODUCT_KEY) END AS   ENTERPRISE_SKU_PRDT_KEY /*FY16-JUNE-CDR to derive ENT-SKU key:thvarghe*/
   /*added   as part of Q2FY18 Kafka OPL project*/
  ,SXXOA.PARENT_SUB_SKU_OFFSET_ID
  ,SXXOA.PARENT_SUB_SKU_ID
  ,SXXOA.MULTI_OA_BUNDLE_ENABLED
  ,SXXOA.ATTRIBUTION_DETAILS
  ,SXXOA.PARENT_LINE_REF_NUMBER
  ,SXXOA.ATTRIBUTED_ITEM
  ,SXXOA.RECOGNIZED_ATTR_SALES_VALUES
  ,SXXOA.RECOGNIZED_ATTR_TCV
  ,SXXOA.BOOKING_VERSION
  ,SXXOA.ERP_LINE_ID
  ,SXXOA.ERP_PARENT_LINE_ID 
  ,SXXOA.EDW_CREATE_DTM AS  CREATION_DATE
   /*NRS PI3 CHANGES*/ 
  ,COALESCE(CASE WHEN SXXOA.ATTRIBUTION_CODE  IN( 'OFFSET MULTI LEVEL SUB SKU','DEAL OFFSET MULTI LEVEL SUB SKU') THEN SXXOA.PARENT_SUB_SKU_OFFSET_ID  ELSE COALESCE(SXXOA.PARENT_SUB_SKU_ID,CXOA_MPOB.ATTRIBUTION_ID) END,-999) AS PARENT_OFFER_ATTRIB_ID_INT /* 4 NRS MPOB columns added*/  
   ,CASE SXXOA.ATTRIBUTION_DETAILS WHEN 'MPOB_INFLIGHT' THEN 'Y' ELSE 'N' END NRS_TRANSITION_FLG  /*NRS PI3 CHANGES*/ 
       ,SXXOA.ACV_ATTRIBUTION_PCT 
	     ,SXXOA.PRICING_TERM     /* SIGORANT ADDED AS PART OF Q2FY19 */ 
   ,CASE WHEN SXXOA.ATTRIBUTION_CODE IN ('DEAL ATTRIBUTED MULTI LEVEL SUB SKU', 'DEAL OFFSET MULTI LEVEL SUB SKU', 'DEAL ATTRIBUTED SUB SKU' ) THEN 'Y' ELSE 'N' END AS AS_ARCHITECTURE_FLG /*dbommise: Parallel OA changes Q3FY19 */
 FROM $$NRTSTGDB.ST_XAAS_XXOA_ORDER_ATTRIB_NRT_NG  SXXOA
         INNER JOIN $$NRTNCRVWDB.N_XAAS_SO_SBCR_ITM_STRX_NRT_TV    NXSSIST/* TOP SKU line */
         ON COALESCE(SXXOA.PARENT_TRX_ID, SXXOA.TRX_ID) = NXSSIST.SK_TRX_ID_INT 
   AND NXSSIST.END_TV_DTM=CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))
       INNER JOIN $$NRTNCRVWDB.N_XAAS_SO_SBCR_ITM_STRX_NRT_TV NXSSIST1 /* SUB SKU line */ 
          ON COALESCE(SXXOA.TRX_ID, SXXOA.PARENT_TRX_ID) = NXSSIST1.SK_TRX_ID_INT 
    AND NXSSIST1.END_TV_DTM=CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))
       INNER JOIN $$COMREFVWDB.N_PRODUCT NP 
         ON(SXXOA.INVENTORY_ITEM_ID = NP.SK_INVENTORY_ITEM_ID_INT) 
    LEFT JOIN $$COMREFVWDB.N_PRODUCT NP_ENT /*FY16-JUNE-CDR to derive ENT-SKU key:thvarghe*/
        ON(SXXOA.ENT_INVENTORY_ITEM_ID = NP_ENT.SK_INVENTORY_ITEM_ID_INT)    
    LEFT JOIN  (
  SELECT  ATTRIBUTION_ID,LINE_REF_NUMBER FROM $$STGDB.ST_SI_XXOA_ORDER_ATTRIB CXOA_1 
  WHERE  ATTRIBUTION_CODE='OFFSET TOP SKU' AND BUNDLE_TYPE IN 'Multiple Performance Obligations (MPOB)' AND DATA_SOURCE IN ('TSL','NGCCRM') AND LINE_REF_NUMBER>0 GROUP BY 1,2
  ) CXOA_MPOB
  ON SXXOA.PARENT_LINE_REF_NUMBER=CXOA_MPOB.LINE_REF_NUMBER
     WHERE NXSSIST.SUBSCRIPTION_PRODUCT_KEY <> -999
    AND DATA_SOURCE IN ('TSL','NGCCRM')
    QUALIFY ROW_NUMBER () OVER (PARTITION BY SXXOA.ATTRIBUTION_ID ORDER BY  SXXOA.CREATION_DATE DESC/*, REFRESH_DATETIME DESC*/ )=1   
     
       UNION  ALL
    
       SELECT 
         EXXOA.BATCH_ID
       , EXXOA.ATTRIBUTION_ID
       --, EXXOA.ORDER_NUMBER
       , EXXOA.LINE_REF_NUMBER
       , EXXOA.DATA_SOURCE
       , EXXOA.TRX_ID
       , EXXOA.PARENT_TRX_ID
       --, EXXOA.ORDERED_ITEM
       , EXXOA.INVENTORY_ITEM_ID
       , EXXOA.ATTRIBUTION_FLAG
       --, EXXOA.CISCO_BOOKED_FLAG
       , EXXOA.BUNDLE_TYPE
       , EXXOA.QUANTITY
       , EXXOA.ATTRIBUTED_UNIT_LIST_PRICE
       , EXXOA.ATTRIBUTED_UNIT_NET_PRICE
       , EXXOA.RECOGNIZED_PCT
       , EXXOA.ATTRIBUTED_PCT
       --, EXXOA.PUBLISH_FLAG
       , EXXOA.ATTRIBUTION_TYPE
       --, EXXOA.CREATED_BY
       --, EXXOA.CREATION_DATE
       --, EXXOA.LAST_UPDATED_BY
       --, EXXOA.LAST_UPDATE_DATE
       --, EXXOA.ORIG_OA_ATTRIB_ID
       , EXXOA.ACTION_CODE
       , EXXOA.CREATE_DATETIME
       --, EXXOA.SOURCE_DML_TYPE
       --, EXXOA.SOURCE_COMMIT_TIME
       , CASE WHEN (EXXOA.TRX_ID IS NOT NULL AND EXXOA.PARENT_TRX_ID IS NOT NULL) THEN  NXSSIST1.SO_SBSCRPTN_ITM_SLS_TRX_KEY
         ELSE -999 END  AS SO_SBSCRPTN_ITM_SLS_TRX_KEY 
       , NP.ITEM_KEY AS ORDERED_PRODUCT_KEY
       , NXSSIST.SUBSCRIPTION_PRODUCT_KEY AS BUNDLE_PRODUCT_KEY
       , 'SRC' AS DV_DATA_SRC_CD
       , 'Y' AS VALID_FLG
       , 'NE' AS EXCEPTION_TYPE
       , EXXOA.EXCEPTION_CODE AS EXCEPTION_CODE
       ,NXSSIST.SO_SBSCRPTN_ITM_SLS_TRX_KEY AS PARENT_SO_SBSCRP_ITMSLSTRX_KEY
    ,EXXOA.ATTRIBUTED_EXT_LIST_PRICE
    ,EXXOA.ATTRIBUTED_EXT_NET_PRICE
       ,EXXOA.WEB_ORDER_ID
    ,NXSSIST.SRC_RPTD_SBSCRPTN_CD
    ,EXXOA.ATTRIBUTED_SALES_VALUE
    ,EXXOA.ATTRIBUTED_MRR
    ,EXXOA.ATTRIBUTED_IMRR
    ,EXXOA.ATTRIBUTED_ARR
    ,EXXOA.ATTRIBUTED_NRR
    ,EXXOA.ATTRIBUTED_IARR
    ,EXXOA.ATTRIBUTED_IMYARR
    ,EXXOA.TCV
    ,EXXOA.ATTRIBUTION_CODE
    ,CASE WHEN EXXOA.ATTRIBUTION_CODE IN ('OFFSET TOP SKU','OFFSET SUB SKU') THEN 'OFFSET' 
    WHEN EXXOA.ATTRIBUTION_CODE IN ('ATTRIBUTED SUB SKU', 'DEAL ATTRIBUTED SUB SKU') THEN 'ATTRIBUTED'
    WHEN EXXOA.ATTRIBUTION_CODE IN ('ATTRIBUTED MULTI LEVEL SUB SKU','DEAL ATTRIBUTED MULTI LEVEL SUB SKU') THEN 'BIB'
    WHEN EXXOA.ATTRIBUTION_CODE IN ('OFFSET MULTI LEVEL SUB SKU','DEAL OFFSET MULTI LEVEL SUB SKU') THEN 'BIB OFFSET'
    ELSE 'UNKNOWN' END AS ATTRIBUTION_CD  /* NRS MPOB Change */
    ,EXXOA.LINKED_ATTRIB_ID
    ,EXXOA.EXCEPTION_DETAIL
    ,NXSSIST.ACTION_CD
    ,NXSSIST.TRX_REASON_CD
    ,NXSSIST.SALES_VALUE_TRXL_AMT
    ,EXXOA.ENT_INVENTORY_ITEM_ID
     ,CASE WHEN ATTRIBUTION_CD IN ('BIB OFFSET', 'OFFSET' ) THEN NP.ITEM_KEY ELSE COALESCE(NP_ENT.ITEM_KEY,NXSSIST.SUBSCRIPTION_PRODUCT_KEY) END AS ENTERPRISE_SKU_PRDT_KEY /*FY16-JUNE-CDR to derive ENT-SKU key:thvarghe*/
   /*added   as part of Q2FY18 Kafka OPL project*/
  ,EXXOA.PARENT_SUB_SKU_OFFSET_ID
  ,EXXOA.PARENT_SUB_SKU_ID
  ,EXXOA.MULTI_OA_BUNDLE_ENABLED
  ,EXXOA.ATTRIBUTION_DETAILS
  ,EXXOA.PARENT_LINE_REF_NUMBER
  ,EXXOA.ATTRIBUTED_ITEM
  ,EXXOA.RECOGNIZED_ATTR_SALES_VALUES
  ,EXXOA.RECOGNIZED_ATTR_TCV
  ,EXXOA.BOOKING_VERSION
  ,EXXOA.ERP_LINE_ID
  ,EXXOA.ERP_PARENT_LINE_ID 
  ,EXXOA.CREATION_DATE
  ,COALESCE(CASE WHEN EXXOA.ATTRIBUTION_CODE IN( 'OFFSET MULTI LEVEL SUB SKU','DEAL OFFSET MULTI LEVEL SUB SKU') THEN EXXOA.PARENT_SUB_SKU_OFFSET_ID  ELSE COALESCE(EXXOA.PARENT_SUB_SKU_ID,CXOA_MPOB.ATTRIBUTION_ID) END,-999) AS PARENT_OFFER_ATTRIB_ID_INT /* 4 NRS MPOB columns added*/  
  ,CASE EXXOA.ATTRIBUTION_DETAILS WHEN 'MPOB_INFLIGHT' THEN 'Y' ELSE 'N' END NRS_TRANSITION_FLG  /*NRS PI3 CHANGES*/ 
      ,EXXOA.ACV_ATTRIBUTION_PCT  
,EXXOA.PRICING_TERM     /* SIGORANT ADDED AS PART OF Q2FY19 */ 	  
 ,CASE WHEN EXXOA.ATTRIBUTION_CODE IN ('DEAL ATTRIBUTED MULTI LEVEL SUB SKU', 'DEAL OFFSET MULTI LEVEL SUB SKU', 'DEAL ATTRIBUTED SUB SKU' ) THEN 'Y' ELSE 'N' END AS AS_ARCHITECTURE_FLG /*dbommise: Parallel OA changes Q3FY19 */
 FROM $$EXCEPDB.EX_XAAS_XXOA_ORDER_ATTRIB_NRT_NG  EXXOA
         INNER JOIN $$NRTNCRVWDB.N_XAAS_SO_SBCR_ITM_STRX_NRT_TV   NXSSIST
         ON COALESCE(EXXOA.PARENT_TRX_ID, EXXOA.TRX_ID) = NXSSIST.SK_TRX_ID_INT 
   AND NXSSIST.END_TV_DTM=CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))
         INNER JOIN $$NRTNCRVWDB.N_XAAS_SO_SBCR_ITM_STRX_NRT_TV NXSSIST1
          ON COALESCE(EXXOA.TRX_ID, EXXOA.PARENT_TRX_ID) = NXSSIST1.SK_TRX_ID_INT 
    AND NXSSIST1.END_TV_DTM=CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))
          INNER JOIN $$COMREFVWDB.N_PRODUCT NP 
         ON(EXXOA.INVENTORY_ITEM_ID = NP.SK_INVENTORY_ITEM_ID_INT)
    LEFT JOIN $$COMREFVWDB.N_PRODUCT NP_ENT /*FY16-JUNE-CDR to derive ENT-SKU key:thvarghe*/
        ON(EXXOA.ENT_INVENTORY_ITEM_ID = NP_ENT.SK_INVENTORY_ITEM_ID_INT)    
        
 LEFT JOIN  (
  SELECT  ATTRIBUTION_ID,LINE_REF_NUMBER FROM $$EXCEPDB.EX_XAAS_XXOA_ORDER_ATTRIB_NRT_NG CXOA_1 
  WHERE  ATTRIBUTION_CODE='OFFSET TOP SKU' AND BUNDLE_TYPE IN 'Multiple Performance Obligations (MPOB)' AND DATA_SOURCE IN ('TSL','NGCCRM') AND LINE_REF_NUMBER>0 GROUP BY 1,2) CXOA_MPOB
  ON EXXOA.PARENT_LINE_REF_NUMBER=CXOA_MPOB.LINE_REF_NUMBER
       WHERE NXSSIST.SUBSCRIPTION_PRODUCT_KEY <> -999
    AND DATA_SOURCE IN ('TSL','NGCCRM')
 QUALIFY ROW_NUMBER () OVER (PARTITION BY EXXOA.ATTRIBUTION_ID ORDER BY  EXXOA.CREATION_DATE DESC/*, REFRESH_DATETIME DESC*/ )=1      
 
    /*Enable SBP records also :Q1FY17*/    
  UNION ALL   
  
  SELECT 
         SXXOA.BATCH_ID
       , SXXOA.ATTRIBUTION_ID
      -- , SXXOA.ORDER_NUMBER
       , SXXOA.LINE_REF_NUMBER
       , SXXOA.DATA_SOURCE
       , SXXOA.TRX_ID
       , SXXOA.PARENT_TRX_ID
       --, SXXOA.ORDERED_ITEM
       , SXXOA.INVENTORY_ITEM_ID
       , SXXOA.ATTRIBUTION_FLAG
       --, SXXOA.CISCO_BOOKED_FLAG
       , SXXOA.BUNDLE_TYPE
       , SXXOA.QUANTITY
       , SXXOA.ATTRIBUTED_UNIT_LIST_PRICE
       , SXXOA.ATTRIBUTED_UNIT_NET_PRICE
       , SXXOA.RECOGNIZED_PCT
       , SXXOA.ATTRIBUTED_PCT
       --, SXXOA.PUBLISH_FLAG
       , SXXOA.ATTRIBUTION_TYPE
       --, SXXOA.CREATED_BY
       --, SXXOA.CREATION_DATE
       --, SXXOA.LAST_UPDATED_BY
       --, SXXOA.LAST_UPDATE_DATE
       --, SXXOA.ORIG_OA_ATTRIB_ID
       , SXXOA.ACTION_CODE
       , SXXOA.CREATE_DATETIME
       --, SXXOA.SOURCE_DML_TYPE
       --, SXXOA.SOURCE_COMMIT_TIME
       , -999  AS SO_SBSCRPTN_ITM_SLS_TRX_KEY 
       , NP.ITEM_KEY AS ORDERED_PRODUCT_KEY
       , -999 AS BUNDLE_PRODUCT_KEY
       , 'SRC' AS DV_DATA_SRC_CD
       , 'Y' AS VALID_FLG
       , 'NE' AS EXCEPTION_TYPE
       , SXXOA.EXCEPTION_CODE AS EXCEPTION_CODE
       , -999  AS PARENT_SO_SBSCRP_ITMSLSTRX_KEY
    ,SXXOA.ATTRIBUTED_EXT_LIST_PRICE
    ,SXXOA.ATTRIBUTED_EXT_NET_PRICE
    ,SXXOA.WEB_ORDER_ID
    ,'UNK' AS SUBSCRIPTION_CODE
    ,SXXOA.ATTRIBUTED_SALES_VALUE
    ,SXXOA.ATTRIBUTED_MRR
    ,SXXOA.ATTRIBUTED_IMRR
    ,SXXOA.ATTRIBUTED_ARR
    ,SXXOA.ATTRIBUTED_NRR
    ,SXXOA.ATTRIBUTED_IARR
    ,SXXOA.ATTRIBUTED_IMYARR
    ,SXXOA.TCV
    ,SXXOA.ATTRIBUTION_CODE
    ,CASE WHEN SXXOA.ATTRIBUTION_CODE IN ('OFFSET TOP SKU','OFFSET SUB SKU') THEN 'OFFSET' 
    WHEN SXXOA.ATTRIBUTION_CODE IN ('ATTRIBUTED SUB SKU', 'DEAL ATTRIBUTED SUB SKU') THEN 'ATTRIBUTED'
    WHEN SXXOA.ATTRIBUTION_CODE IN ('ATTRIBUTED MULTI LEVEL SUB SKU','DEAL ATTRIBUTED MULTI LEVEL SUB SKU') THEN 'BIB'
     WHEN SXXOA.ATTRIBUTION_CODE IN ('OFFSET MULTI LEVEL SUB SKU','DEAL OFFSET MULTI LEVEL SUB SKU') THEN 'BIB OFFSET'  
     ELSE 'UNKNOWN' END AS ATTRIBUTION_CD  /* NRS MPOB Change */
    ,SXXOA.LINKED_ATTRIB_ID
    ,SXXOA.EXCEPTION_DETAIL
    , '='
    ,'='
    , 0
    ,SXXOA.ENT_INVENTORY_ITEM_ID
    ,CASE WHEN ATTRIBUTION_CD IN ('BIB OFFSET', 'OFFSET' ) THEN NP.ITEM_KEY ELSE COALESCE(NP_ENT.ITEM_KEY,NP_PAR.ITEM_KEY,-999) END AS ENTERPRISE_SKU_PRDT_KEY /*FY16-JUNE-CDR to derive ENT-SKU key:thvarghe*/
     /*added   as part of Q2FY18 Kafka OPL project*/
  ,SXXOA.PARENT_SUB_SKU_OFFSET_ID
  ,SXXOA.PARENT_SUB_SKU_ID
  ,SXXOA.MULTI_OA_BUNDLE_ENABLED
  ,SXXOA.ATTRIBUTION_DETAILS
  ,SXXOA.PARENT_LINE_REF_NUMBER
  ,SXXOA.ATTRIBUTED_ITEM
  ,SXXOA.RECOGNIZED_ATTR_SALES_VALUES
  ,SXXOA.RECOGNIZED_ATTR_TCV
  ,SXXOA.BOOKING_VERSION
  ,SXXOA.ERP_LINE_ID
  ,SXXOA.ERP_PARENT_LINE_ID  
  ,SXXOA.CREATION_DATE
   ,COALESCE(CASE WHEN SXXOA.ATTRIBUTION_CODE IN( 'OFFSET MULTI LEVEL SUB SKU','DEAL OFFSET MULTI LEVEL SUB SKU') THEN SXXOA.PARENT_SUB_SKU_OFFSET_ID  ELSE COALESCE(SXXOA.PARENT_SUB_SKU_ID,CXOA_MPOB.ATTRIBUTION_ID) END,-999) AS PARENT_OFFER_ATTRIB_ID_INT /* 4 NRS MPOB columns added*/  
   ,CASE SXXOA.ATTRIBUTION_DETAILS WHEN 'MPOB_INFLIGHT' THEN 'Y' ELSE 'N' END NRS_TRANSITION_FLG  /*NRS PI3 CHANGES*/ 
 ,SXXOA.ACV_ATTRIBUTION_PCT 
  ,   SXXOA.PRICING_TERM     /* SIGORANT ADDED AS PART OF Q2FY19 */  
  ,CASE WHEN SXXOA.ATTRIBUTION_CODE IN ('DEAL ATTRIBUTED MULTI LEVEL SUB SKU', 'DEAL OFFSET MULTI LEVEL SUB SKU', 'DEAL ATTRIBUTED SUB SKU' ) THEN 'Y' ELSE 'N' END AS AS_ARCHITECTURE_FLG  /*dbommise: Parallel OA changes Q3FY19 */
 FROM $$NRTSTGDB.ST_SBP_XXOA_ORDER_ATTRIB_NRT_NG  SXXOA
        INNER JOIN $$COMREFVWDB.N_PRODUCT NP 
         ON(SXXOA.INVENTORY_ITEM_ID = NP.SK_INVENTORY_ITEM_ID_INT)
     LEFT JOIN (SELECT TRX_ID,INVENTORY_ITEM_ID FROM $$NRTSTGDB.ST_SBP_XXOA_ORDER_ATTRIB_NRT_NG SXXOA WHERE SXXOA.ATTRIBUTION_CODE IN ('OFFSET TOP SKU','OFFSET SUB SKU')  GROUP BY 1,2)SXXOA_PAR
     ON SXXOA.PARENT_TRX_ID=SXXOA_PAR.TRX_ID
     LEFT JOIN $$COMREFVWDB.N_PRODUCT NP_PAR
     ON SXXOA_PAR.INVENTORY_ITEM_ID=NP_PAR.SK_INVENTORY_ITEM_ID_INT
      LEFT JOIN $$COMREFVWDB.N_PRODUCT NP_ENT /*FY16-JUNE-CDR to derive ENT-SKU key:thvarghe*/
        ON(SXXOA.ENT_INVENTORY_ITEM_ID = NP_ENT.SK_INVENTORY_ITEM_ID_INT)  
     LEFT JOIN  (
  SELECT  ATTRIBUTION_ID,LINE_REF_NUMBER FROM $$STGDB.ST_SI_XXOA_ORDER_ATTRIB CXOA_1 
  WHERE  ATTRIBUTION_CODE='OFFSET TOP SKU' AND BUNDLE_TYPE IN 'Multiple Performance Obligations (MPOB)' AND DATA_SOURCE='SBP' AND LINE_REF_NUMBER>0 GROUP BY 1,2) CXOA_MPOB
  ON SXXOA.PARENT_LINE_REF_NUMBER=CXOA_MPOB.LINE_REF_NUMBER
   WHERE DATA_SOURCE='SBP'   
        QUALIFY ROW_NUMBER () OVER (PARTITION BY SXXOA.ATTRIBUTION_ID ORDER BY  SXXOA.CREATION_DATE DESC/*, REFRESH_DATETIME DESC*/)=1   
     
       UNION  ALL
    
       SELECT 
         EXXOA.BATCH_ID
       , EXXOA.ATTRIBUTION_ID
       --, EXXOA.ORDER_NUMBER
       , EXXOA.LINE_REF_NUMBER
       , EXXOA.DATA_SOURCE
       , EXXOA.TRX_ID
       , EXXOA.PARENT_TRX_ID
       --, EXXOA.ORDERED_ITEM
       , EXXOA.INVENTORY_ITEM_ID
       , EXXOA.ATTRIBUTION_FLAG
       --, EXXOA.CISCO_BOOKED_FLAG
       , EXXOA.BUNDLE_TYPE
       , EXXOA.QUANTITY
       , EXXOA.ATTRIBUTED_UNIT_LIST_PRICE
       , EXXOA.ATTRIBUTED_UNIT_NET_PRICE
       , EXXOA.RECOGNIZED_PCT
       , EXXOA.ATTRIBUTED_PCT
       --, EXXOA.PUBLISH_FLAG
       , EXXOA.ATTRIBUTION_TYPE
       --, EXXOA.CREATED_BY
       --, EXXOA.CREATION_DATE
       --, EXXOA.LAST_UPDATED_BY
       --, EXXOA.LAST_UPDATE_DATE
       --, EXXOA.ORIG_OA_ATTRIB_ID
       , EXXOA.ACTION_CODE
       , EXXOA.CREATE_DATETIME
       --, EXXOA.SOURCE_DML_TYPE
       --, EXXOA.SOURCE_COMMIT_TIME
       , -999  AS SO_SBSCRPTN_ITM_SLS_TRX_KEY 
       , NP.ITEM_KEY AS ORDERED_PRODUCT_KEY
       , -999 AS BUNDLE_PRODUCT_KEY
       , 'SRC' AS DV_DATA_SRC_CD
       , 'Y' AS VALID_FLG
       , 'NE' AS EXCEPTION_TYPE
       , EXXOA.EXCEPTION_CODE AS EXCEPTION_CODE
       , -999  AS PARENT_SO_SBSCRP_ITMSLSTRX_KEY
    ,EXXOA.ATTRIBUTED_EXT_LIST_PRICE
    ,EXXOA.ATTRIBUTED_EXT_NET_PRICE
       ,EXXOA.WEB_ORDER_ID
    ,'UNK' AS SUBSCRIPTION_CODE
    ,EXXOA.ATTRIBUTED_SALES_VALUE
    ,EXXOA.ATTRIBUTED_MRR
    ,EXXOA.ATTRIBUTED_IMRR
    ,EXXOA.ATTRIBUTED_ARR
    ,EXXOA.ATTRIBUTED_NRR
    ,EXXOA.ATTRIBUTED_IARR
    ,EXXOA.ATTRIBUTED_IMYARR
    ,EXXOA.TCV
    ,EXXOA.ATTRIBUTION_CODE
    ,CASE WHEN EXXOA.ATTRIBUTION_CODE IN ('OFFSET TOP SKU','OFFSET SUB SKU') THEN 'OFFSET' 
  WHEN EXXOA.ATTRIBUTION_CODE IN ('ATTRIBUTED SUB SKU', 'DEAL ATTRIBUTED SUB SKU') THEN 'ATTRIBUTED'
  WHEN EXXOA.ATTRIBUTION_CODE IN ('ATTRIBUTED MULTI LEVEL SUB SKU','DEAL ATTRIBUTED MULTI LEVEL SUB SKU') THEN 'BIB'
    WHEN EXXOA.ATTRIBUTION_CODE IN ('OFFSET MULTI LEVEL SUB SKU','DEAL OFFSET MULTI LEVEL SUB SKU') THEN 'BIB OFFSET'  
     ELSE 'UNKNOWN' END AS ATTRIBUTION_CD /* NRS MPOB Change */
    ,EXXOA.LINKED_ATTRIB_ID
    ,EXXOA.EXCEPTION_DETAIL
    , '='
    ,'='
    , 0
    ,EXXOA.ENT_INVENTORY_ITEM_ID
    ,CASE WHEN ATTRIBUTION_CD IN ('BIB OFFSET', 'OFFSET' ) THEN NP.ITEM_KEY ELSE COALESCE(NP_ENT.ITEM_KEY,NP_PAR.ITEM_KEY,-999) END AS ENTERPRISE_SKU_PRDT_KEY /*FY16-JUNE-CDR to derive ENT-SKU key:thvarghe*/
   /*added   as part of Q2FY18 Kafka OPL project*/   
  ,EXXOA.PARENT_SUB_SKU_OFFSET_ID
  ,EXXOA.PARENT_SUB_SKU_ID
  ,EXXOA.MULTI_OA_BUNDLE_ENABLED
  ,EXXOA.ATTRIBUTION_DETAILS
  ,EXXOA.PARENT_LINE_REF_NUMBER
  ,EXXOA.ATTRIBUTED_ITEM
  ,EXXOA.RECOGNIZED_ATTR_SALES_VALUES
  ,EXXOA.RECOGNIZED_ATTR_TCV
  ,EXXOA.BOOKING_VERSION
  ,EXXOA.ERP_LINE_ID
  ,EXXOA.ERP_PARENT_LINE_ID 
  ,EXXOA.CREATION_DATE
  ,COALESCE(CASE WHEN EXXOA.ATTRIBUTION_CODE IN( 'OFFSET MULTI LEVEL SUB SKU','DEAL OFFSET MULTI LEVEL SUB SKU') THEN EXXOA.PARENT_SUB_SKU_OFFSET_ID  ELSE COALESCE(EXXOA.PARENT_SUB_SKU_ID,CXOA_MPOB.ATTRIBUTION_ID) END,-999) AS PARENT_OFFER_ATTRIB_ID_INT /* 4 NRS MPOB columns added*/  
  ,CASE EXXOA.ATTRIBUTION_DETAILS WHEN 'MPOB_INFLIGHT' THEN 'Y' ELSE 'N' END NRS_TRANSITION_FLG  /*NRS PI3 CHANGES*/ 
     ,EXXOA.ACV_ATTRIBUTION_PCT  
  ,   EXXOA.PRICING_TERM     /* SIGORANT ADDED AS PART OF Q2FY19 */ 	 
  , CASE WHEN EXXOA.ATTRIBUTION_CODE IN ('DEAL ATTRIBUTED MULTI LEVEL SUB SKU', 'DEAL OFFSET MULTI LEVEL SUB SKU', 'DEAL ATTRIBUTED SUB SKU' ) THEN 'Y' ELSE 'N' END AS AS_ARCHITECTURE_FLG  /*dbommise: Parallel OA changes Q3FY19 */
 FROM $$EXCEPDB.EX_SBP_XXOA_ORDER_ATTRIB_NRT_NG  EXXOA
        INNER JOIN $$COMREFVWDB.N_PRODUCT NP 
        ON(EXXOA.INVENTORY_ITEM_ID = NP.SK_INVENTORY_ITEM_ID_INT)
     LEFT JOIN (SELECT TRX_ID,INVENTORY_ITEM_ID FROM $$EXCEPDB.EX_SBP_XXOA_ORDER_ATTRIB_NRT_NG EXXOA WHERE EXXOA.ATTRIBUTION_CODE IN ('OFFSET TOP SKU','OFFSET SUB SKU')  GROUP BY 1,2)EXXOA_PAR
     ON EXXOA.PARENT_TRX_ID=EXXOA_PAR.TRX_ID
     LEFT JOIN $$COMREFVWDB.N_PRODUCT NP_PAR
     ON EXXOA_PAR.INVENTORY_ITEM_ID=NP_PAR.SK_INVENTORY_ITEM_ID_INT
      LEFT JOIN $$COMREFVWDB.N_PRODUCT NP_ENT /*FY16-JUNE-CDR to derive ENT-SKU key:thvarghe*/
        ON(EXXOA.ENT_INVENTORY_ITEM_ID = NP_ENT.SK_INVENTORY_ITEM_ID_INT)  
     LEFT JOIN  (
  SELECT  ATTRIBUTION_ID,LINE_REF_NUMBER FROM $$EXCEPDB.EX_SBP_XXOA_ORDER_ATTRIB_NRT_NG CXOA_1 
  WHERE  ATTRIBUTION_CODE='OFFSET TOP SKU' AND BUNDLE_TYPE IN 'Multiple Performance Obligations (MPOB)' AND DATA_SOURCE='SBP' AND LINE_REF_NUMBER>0 GROUP BY 1,2) CXOA_MPOB
  ON EXXOA.PARENT_LINE_REF_NUMBER=CXOA_MPOB.LINE_REF_NUMBER
  WHERE DATA_SOURCE='SBP'
  QUALIFY ROW_NUMBER () OVER (PARTITION BY EXXOA.ATTRIBUTION_ID ORDER BY  EXXOA.CREATION_DATE DESC/*, REFRESH_DATETIME DESC*/ )=1  
/*^^^^^^^^^^^^^*/


Post SQL : 



Target1 Name : WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT1_NG


Pre SQL : 
DELETE FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG ALL;
  
  COLLECT STATS ON $$NRTSTGDB.ST_XAAS_XXOA_ORDER_ATTRIB_NRT_NG;
   /*DELETE  EXCEPTION records that have latest updates from Source*/
  
  DELETE FROM $$EXCEPDB.EX_XAAS_XXOA_ORDER_ATTRIB_NRT_NG EXXOA
  WHERE EXISTS (SELECT 1 FROM $$NRTSTGDB.ST_XAAS_XXOA_ORDER_ATTRIB_NRT_NG SXXOA 
   WHERE EXXOA.ATTRIBUTION_ID = SXXOA.ATTRIBUTION_ID 
 );
 
 DELETE FROM $$EXCEPDB.EX_SBP_XXOA_ORDER_ATTRIB_NRT_NG EXXOA
  WHERE EXISTS (SELECT 1 FROM $$NRTSTGDB.ST_SBP_XXOA_ORDER_ATTRIB_NRT_NG SXXOA 
   WHERE EXXOA.ATTRIBUTION_ID = SXXOA.ATTRIBUTION_ID 
 );


Post SQL : 
COLLECT STATS $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG;
    
    UPDATE WIXSSBA
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA,
    (
    SELECT PARENT_SO_SBSCRP_ITMSLSTRX_KEY, EXCEPTION_TYPE
    FROM(
      /* TSLs  Invalid due to incorrect values for Attribution Code from Source  */
    SELECT PARENT_SO_SBSCRP_ITMSLSTRX_KEY , CAST('ATTRIB_CD_INVALID' AS VARCHAR(30)) AS EXCEPTION_TYPE, 
    1 AS EXCP_PRIORITY, CAST(0.00000000 AS DECIMAL(18,8)) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CODE IS NULL
    GROUP BY 1
      UNION 
     /* TSLs  Invalid due to Attribution Percent of all ATTRIBUTED lines not summing to 100% */
    SELECT PARENT_SO_SBSCRP_ITMSLSTRX_KEY , CAST('ATTRIB_PCT_INVALID' AS VARCHAR(30)) AS EXCEPTION_TYPE, 
    2 AS EXCP_PRIORITY, SUM(COALESCE(ATTRIBUTED_PCT,0)) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='ATTRIBUTED'
    GROUP BY 1
    HAVING SUM_PCT  <> 100.00000000 
    UNION 
    /* TSLs Invalid due to Attribution Percent of OFFSET lines not  equal to 100% */
    SELECT PARENT_SO_SBSCRP_ITMSLSTRX_KEY , 'OFFSET_INVALID' AS EXCEPTION_TYPE, 3 AS EXCP_PRIORITY, 
    COALESCE(ATTRIBUTED_PCT,999) AS ATTRIBUTED_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE (ATTRIBUTION_CD='OFFSET'
    AND ATTRIBUTED_PCT  <> 100.00000000 
     )
    UNION
    /* ATTRIBUTED TSLs  without an OFFSET line */
    SELECT PARENT_SO_SBSCRP_ITMSLSTRX_KEY, 'NO_OFFSET_LINE' AS EXCEPTION_TYPE, 4 AS EXCP_PRIORITY, SUM(ATTRIBUTED_PCT) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA1
    WHERE ATTRIBUTION_CD='ATTRIBUTED'
    AND NOT EXISTS ( SELECT 1  
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='OFFSET'
    AND WIXSSBA1.PARENT_SO_SBSCRP_ITMSLSTRX_KEY =  WIXSSBA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY)
    GROUP BY 1
    UNION
  /*OFFSET lines without Attriuted line-Not Considering Cisco-one Perpetual only */
    SELECT PARENT_SO_SBSCRP_ITMSLSTRX_KEY, 'NO_ATTRIB_LINE' AS EXCEPTION_TYPE, 5 AS EXCP_PRIORITY, SUM(ATTRIBUTED_PCT) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA1
    WHERE (ATTRIBUTION_CD='OFFSET'
    AND PARENT_SO_SBSCRP_ITMSLSTRX_KEY = SO_SBSCRPTN_ITM_SLS_TRX_KEY   )
    AND NOT(ATTRIBUTION_FLAG='N' AND PARENT_TRX_ID IS NULL)
    AND NOT EXISTS (SELECT 1  
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='ATTRIBUTED'
    AND WIXSSBA1.PARENT_SO_SBSCRP_ITMSLSTRX_KEY =  WIXSSBA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY)
    GROUP BY 1 
	
	UNION
	
	/* NRS MPOB Changes */
    
    /* BIB TSLs  without BIB OFFSET line */
    SELECT PARENT_SO_SBSCRP_ITMSLSTRX_KEY, 'NO_BIB_OFFSET_LINE' AS EXCEPTION_TYPE, 6 AS EXCP_PRIORITY, SUM(ATTRIBUTED_PCT) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA1
    WHERE ATTRIBUTION_CD='BIB'
    AND NOT EXISTS ( SELECT 1  
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='BIB OFFSET'
    AND WIXSSBA1.ATTRIBUTION_ID =  WIXSSBA.PARENT_OFFER_ATTRIB_ID_INT)
    GROUP BY 1

    UNION
  /* MPOB ATTRIBUTED Trxns without an MPOB OFFSET or MPOB line */
  
 SELECT PARENT_SO_SBSCRP_ITMSLSTRX_KEY, 'NO_BIB_OR_BIB_OFFSET_LINE' AS EXCEPTION_TYPE, 7 AS EXCP_PRIORITY, SUM(ATTRIBUTED_PCT) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA1
    WHERE ATTRIBUTION_CD='ATTRIBUTED'          AND WIXSSBA1.PARENT_SUB_SKU_ID IS NOT NULL
    AND (NOT EXISTS ( SELECT 1  
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='BIB OFFSET'
    AND WIXSSBA1.PARENT_OFFER_ATTRIB_ID_INT =  WIXSSBA.PARENT_OFFER_ATTRIB_ID_INT)
OR NOT EXISTS (SELECT 1  
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='BIB'
    AND WIXSSBA1.PARENT_OFFER_ATTRIB_ID_INT =  WIXSSBA.ATTRIBUTION_ID)) 
 GROUP BY 1
UNION
  /*BIB OFFSET lines without BIB line  */
    SELECT PARENT_SO_SBSCRP_ITMSLSTRX_KEY, 'NO_BIB_LINE' AS EXCEPTION_TYPE, 8 AS EXCP_PRIORITY, SUM(ATTRIBUTED_PCT) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA1
    WHERE (ATTRIBUTION_CD='BIB OFFSET'
    AND PARENT_SO_SBSCRP_ITMSLSTRX_KEY = SO_SBSCRPTN_ITM_SLS_TRX_KEY   )
    AND NOT(ATTRIBUTION_FLAG='N' AND PARENT_TRX_ID IS NULL)
    AND NOT EXISTS (SELECT 1  
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='BIB'
    AND WIXSSBA1.PARENT_OFFER_ATTRIB_ID_INT =  WIXSSBA.ATTRIBUTION_ID)
    GROUP BY 1 


UNION
     /* Lines Invalid due to MPOB Attribution Percent of all ATTRIBUTED lines not summing to MPOB LINE (BIB LINE)   */ 

    SELECT PARENT_SO_SBSCRP_ITMSLSTRX_KEY, 'MPOB_ATTRIB_PCT_INVALID' AS EXCEPTION_TYPE, 9 AS EXCP_PRIORITY, WIXSSBA1.ATTRIBUTED_PCT AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA1
    INNER JOIN ( SELECT WISO.PARENT_OFFER_ATTRIB_ID_INT, SUM(WISO.ATTRIBUTED_PCT)  ATTRIBUTED_PCT
   FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WISO
   WHERE (WISO.ATTRIBUTION_CD = 'ATTRIBUTED' AND WISO.PARENT_SUB_SKU_ID IS NOT NULL  )
HAVING  SUM(CAST(WISO.ATTRIBUTED_PCT AS DECIMAL(18,4)))  <>   ( SELECT CAST(WISO1.ATTRIBUTED_PCT AS DECIMAL(18,4))    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WISO1
   WHERE WISO1.ATTRIBUTION_CD =   'BIB'     AND WISO1.ATTRIBUTION_ID = WISO.PARENT_OFFER_ATTRIB_ID_INT )
     GROUP BY 1 ) WISO_SUB
                  ON  WIXSSBA1.PARENT_OFFER_ATTRIB_ID_INT = WISO_SUB.PARENT_OFFER_ATTRIB_ID_INT 
                 GROUP BY 1, 2, 3, 4

				 
    )A
    QUALIFY ROW_NUMBER() OVER(PARTITION BY PARENT_SO_SBSCRP_ITMSLSTRX_KEY ORDER BY EXCP_PRIORITY )=1
    )INVALID_TSL
    SET VALID_FLG = 'N'
    ,EXCEPTION_TYPE = INVALID_TSL.EXCEPTION_TYPE
    WHERE WIXSSBA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY = INVALID_TSL.PARENT_SO_SBSCRP_ITMSLSTRX_KEY
    AND WIXSSBA.DATA_SOURCE IN ('TSL','NGCCRM')
  ;     
 
 
    UPDATE WIXSSBA
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA,
    (
    SELECT PARENT_TRX_ID, EXCEPTION_TYPE
    FROM(
      /* TSLs  Invalid due to incorrect values for Attribution Code from Source  */
    SELECT COALESCE(TRX_ID,PARENT_TRX_ID) AS  PARENT_TRX_ID, CAST('ATTRIB_CD_INVALID' AS VARCHAR(30)) AS EXCEPTION_TYPE, 
    1 AS EXCP_PRIORITY, CAST(0.00000000 AS DECIMAL(18,8))AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CODE IS NULL
    GROUP BY 1
    UNION 
     /* TSLs  Invalid due to Attribution Percent of all ATTRIBUTED lines not summing to 100% */
    SELECT PARENT_TRX_ID , CAST('ATTRIB_PCT_INVALID' AS VARCHAR(30)) AS EXCEPTION_TYPE, 
    2 AS EXCP_PRIORITY, SUM(COALESCE(ATTRIBUTED_PCT,0)) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='ATTRIBUTED'
    GROUP BY 1
    HAVING SUM_PCT  <> 100.00000000 
    UNION 
    /* TSLs Invalid due to Attribution Percent of OFFSET lines not  equal to 100% */
    SELECT TRX_ID,'OFFSET_INVALID' AS EXCEPTION_TYPE, 3 AS EXCP_PRIORITY, 
    COALESCE(ATTRIBUTED_PCT,999) AS ATTRIBUTED_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE (ATTRIBUTION_CD='OFFSET'
    AND ATTRIBUTED_PCT  <> 100.00000000 
     )
    UNION
    /* ATTRIBUTED TSLs  without an OFFSET line */
    SELECT PARENT_TRX_ID, 'NO_OFFSET_LINE' AS EXCEPTION_TYPE, 4 AS EXCP_PRIORITY, SUM(ATTRIBUTED_PCT) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA1
    WHERE ATTRIBUTION_CD='ATTRIBUTED'
    AND NOT EXISTS (SELECT 1  
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='OFFSET'
    AND WIXSSBA1.PARENT_TRX_ID =  WIXSSBA.TRX_ID)
    GROUP BY 1
    UNION
  /*OFFSET lines without Attriuted line-Not Considering Cisco-one Perpetual only */
    SELECT TRX_ID, 'NO_ATTRIB_LINE' AS EXCEPTION_TYPE, 5 AS EXCP_PRIORITY, SUM(ATTRIBUTED_PCT) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA1
    WHERE ATTRIBUTION_CD='OFFSET'
    AND NOT(ATTRIBUTION_FLAG='N' AND PARENT_TRX_ID IS NULL)
    AND NOT EXISTS (SELECT 1  
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='ATTRIBUTED'
    AND WIXSSBA1.TRX_ID =  WIXSSBA.PARENT_TRX_ID)
    GROUP BY 1 
	
		
	/* NRS MPOB Changes */
     UNION
    /* BIB ATTRIBUTED TSLs  without an OFFSET line */
    SELECT PARENT_TRX_ID, 'NO_BIB_LINE' AS EXCEPTION_TYPE, 6 AS EXCP_PRIORITY, SUM(ATTRIBUTED_PCT) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA1
    WHERE ATTRIBUTION_CD='BIB OFFSET'
    AND NOT EXISTS (SELECT 1  
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='BIB'
    AND WIXSSBA1.PARENT_OFFER_ATTRIB_ID_INT =  WIXSSBA.ATTRIBUTION_ID)
    GROUP BY 1

    UNION
  /* MPOB ATTRIBUTED Trxns without an MPOB OFFSET or MPOB line */
  SELECT PARENT_TRX_ID, 'NO_BIB_OR_BIB_OFFSET_LINE' AS EXCEPTION_TYPE, 7 AS EXCP_PRIORITY, SUM(ATTRIBUTED_PCT) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA1
    WHERE ATTRIBUTION_CD='ATTRIBUTED' AND WIXSSBA1.PARENT_SUB_SKU_ID IS NOT NULL
    AND (NOT EXISTS ( SELECT 1  
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='BIB OFFSET'
    AND WIXSSBA1.PARENT_OFFER_ATTRIB_ID_INT =  WIXSSBA.PARENT_OFFER_ATTRIB_ID_INT)
OR NOT EXISTS (SELECT 1  
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='BIB'
    AND WIXSSBA1.PARENT_OFFER_ATTRIB_ID_INT =  WIXSSBA.ATTRIBUTION_ID)) 
 GROUP BY 1

    UNION
  /*BIB OFFSET lines without Attriuted line  */
    SELECT TRX_ID, 'NO_BIB_OFFSET_LINE' AS EXCEPTION_TYPE, 8 AS EXCP_PRIORITY, SUM(ATTRIBUTED_PCT) AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA1
    WHERE ATTRIBUTION_CD='BIB'
    AND NOT(ATTRIBUTION_FLAG='N' )
    AND NOT EXISTS (SELECT 1  
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA
    WHERE ATTRIBUTION_CD='BIB OFFSET'
    AND WIXSSBA1.ATTRIBUTION_ID =  WIXSSBA.PARENT_OFFER_ATTRIB_ID_INT)
    GROUP BY 1              
                
                
UNION
     /* Lines Invalid due to MPOB Attribution Percent of all ATTRIBUTED lines not summing to MPOB LINE (BIB LINE)   */ 

    SELECT PARENT_SO_SBSCRP_ITMSLSTRX_KEY, 'MPOB_ATTRIB_PCT_INVALID' AS EXCEPTION_TYPE, 9 AS EXCP_PRIORITY, WIXSSBA1.ATTRIBUTED_PCT AS SUM_PCT
    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSBA1
                INNER JOIN ( SELECT WISO.PARENT_OFFER_ATTRIB_ID_INT, SUM(WISO.ATTRIBUTED_PCT)  ATTRIBUTED_PCT
   FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WISO
   WHERE (WISO.ATTRIBUTION_CD = 'ATTRIBUTED' AND WISO.PARENT_SUB_SKU_ID IS NOT NULL )
HAVING  SUM(CAST(WISO.ATTRIBUTED_PCT AS DECIMAL(18,4)))  <>   ( SELECT CAST(WISO1.ATTRIBUTED_PCT AS DECIMAL(18,4))    FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WISO1
   WHERE WISO1.ATTRIBUTION_CD =   'BIB'     AND WISO1.ATTRIBUTION_ID = WISO.PARENT_OFFER_ATTRIB_ID_INT )
     GROUP BY 1 ) WISO_SUB
                  ON  WIXSSBA1.PARENT_OFFER_ATTRIB_ID_INT = WISO_SUB.PARENT_OFFER_ATTRIB_ID_INT 
                 GROUP BY 1, 2, 3, 4
    )A
    QUALIFY ROW_NUMBER() OVER(PARTITION BY PARENT_TRX_ID ORDER BY EXCP_PRIORITY )=1
    )INVALID_TSL
    SET VALID_FLG = 'N'
    ,EXCEPTION_TYPE = INVALID_TSL.EXCEPTION_TYPE
    WHERE COALESCE(WIXSSBA.TRX_ID,WIXSSBA.PARENT_TRX_ID) = INVALID_TSL.PARENT_TRX_ID
    AND WIXSSBA.DATA_SOURCE='SBP'
 ;


Source2 Name : SQ_EX_XAAS_XXOA_ORDER_ATTRIB_NRT_NG


Pre SQL : 



SQL Query : 
SELECT 
   WIXSSA.BATCH_ID,
   WIXSSA.ATTRIBUTION_ID,
   --WIXSSA.ORDER_NUMBER,
   WIXSSA.LINE_REF_NUMBER,
   WIXSSA.DATA_SOURCE,
   WIXSSA.TRX_ID,
   WIXSSA.PARENT_TRX_ID,
   --WIXSSA.ORDERED_ITEM,
   WIXSSA.INVENTORY_ITEM_ID,
   WIXSSA.ATTRIBUTION_FLAG,
   --WIXSSA.CISCO_BOOKED_FLAG,
   WIXSSA.BUNDLE_TYPE,
   WIXSSA.QUANTITY,
   WIXSSA.ATTRIBUTED_UNIT_LIST_PRICE,
   WIXSSA.ATTRIBUTED_UNIT_NET_PRICE,
   WIXSSA.RECOGNIZED_PCT,
   WIXSSA.ATTRIBUTED_PCT,
   --WIXSSA.PUBLISH_FLAG,
   WIXSSA.ATTRIBUTION_TYPE,
   --WIXSSA.CREATED_BY,
   --WIXSSA.CREATION_DATE,
   --WIXSSA.LAST_UPDATED_BY,
   --WIXSSA.LAST_UPDATE_DATE,
   --WIXSSA.ORIG_OA_ATTRIB_ID,
   WIXSSA.ACTION_CODE,
   WIXSSA.CREATE_DATETIME,
   --WIXSSA.SOURCE_DML_TYPE,
   --WIXSSA.SOURCE_COMMIT_TIME,
   WIXSSA.EXCEPTION_TYPE,
   WIXSSA.EXCEPTION_CODE,
   WIXSSA.ATTRIBUTED_EXT_LIST_PRICE,
   WIXSSA.ATTRIBUTED_EXT_NET_PRICE,
   WIXSSA.WEB_ORDER_ID,
   --WIXSSA.SUBSCRIPTION_CODE,
   WIXSSA.ATTRIBUTED_SALES_VALUE ,
   WIXSSA.ATTRIBUTED_MRR,
   WIXSSA.ATTRIBUTED_IMRR,
   WIXSSA.ATTRIBUTED_ARR,
   WIXSSA.ATTRIBUTED_NRR,
   WIXSSA.ATTRIBUTED_IARR,
   WIXSSA.ATTRIBUTED_IMYARR,
   WIXSSA.TCV,
   WIXSSA.ATTRIBUTION_CODE  ,
   WIXSSA.LINKED_ATTRIB_ID,
   WIXSSA.EXCEPTION_DETAIL,/* OA - Q1FY16*/
   WIXSSA.ENT_INVENTORY_ITEM_ID,/*FY16-JUNE-CDR:thvarghe*/
    /*added   as part of Q2FY18 Kafka OPL project*/ 
   WIXSSA.PARENT_SUB_SKU_OFFSET_ID,
   WIXSSA.PARENT_SUB_SKU_ID,
   WIXSSA.MULTI_OA_BUNDLE_ENABLED,
   WIXSSA.ATTRIBUTION_DETAILS,
   WIXSSA.PARENT_LINE_REF_NUMBER,
   WIXSSA.ATTRIBUTED_ITEM,
   WIXSSA.RECOGNIZED_ATTR_SALES_VALUES,
   WIXSSA.RECOGNIZED_ATTR_TCV,
   WIXSSA.BOOKING_VERSION,
   WIXSSA.ERP_LINE_ID,
   WIXSSA.ERP_PARENT_LINE_ID,
   WIXSSA.CREATION_DATE,
 WIXSSA.ACV_ATTRIBUTION_PCT,
   WIXSSA.PRICING_TERM    /* SIGORANT ADDED AS PART OF Q2FY19 */ 
   FROM  $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSA
      WHERE 
       WIXSSA.VALID_FLG = 'N'
      AND NOT EXISTS
      (
       SELECT 1
       FROM $$EXCEPDB.EX_XAAS_XXOA_ORDER_ATTRIB_NRT_NG EXXOA
       WHERE EXXOA.ATTRIBUTION_ID = WIXSSA.ATTRIBUTION_ID 
      )
      AND WIXSSA.DATA_SOURCE IN ('TSL','NGCCRM')
       
      UNION
      
      SELECT 
   SXXOA.BATCH_ID,
   SXXOA.ATTRIBUTION_ID,
   --SXXOA.ORDER_NUMBER,
   SXXOA.LINE_REF_NUMBER,
   SXXOA.DATA_SOURCE,
   SXXOA.TRX_ID,
   SXXOA.PARENT_TRX_ID,
   --SXXOA.ORDERED_ITEM,
   SXXOA.INVENTORY_ITEM_ID,
   SXXOA.ATTRIBUTION_FLAG,
   --SXXOA.CISCO_BOOKED_FLAG,
   SXXOA.BUNDLE_TYPE,
   SXXOA.QUANTITY,
   SXXOA.ATTRIBUTED_UNIT_LIST_PRICE,
   SXXOA.ATTRIBUTED_UNIT_NET_PRICE,
   SXXOA.RECOGNIZED_PCT,
   SXXOA.ATTRIBUTED_PCT,
   --SXXOA.PUBLISH_FLAG,
   SXXOA.ATTRIBUTION_TYPE,
   --SXXOA.CREATED_BY,
   --SXXOA.CREATION_DATE,
   --SXXOA.LAST_UPDATED_BY,
   --SXXOA.LAST_UPDATE_DATE,
   --SXXOA.ORIG_OA_ATTRIB_ID,
   SXXOA.ACTION_CODE,
   SXXOA.CREATE_DATETIME,
   --SXXOA.SOURCE_DML_TYPE,
   --SXXOA.SOURCE_COMMIT_TIME,
   SXXOA.EXCEPTION_TYPE,
   SXXOA.EXCEPTION_CODE,
   SXXOA.ATTRIBUTED_EXT_LIST_PRICE,
   SXXOA.ATTRIBUTED_EXT_NET_PRICE,   
   SXXOA.WEB_ORDER_ID,
   --SXXOA.SUBSCRIPTION_CODE,
   SXXOA.ATTRIBUTED_SALES_VALUE,
   SXXOA.ATTRIBUTED_MRR,
   SXXOA.ATTRIBUTED_IMRR,
   SXXOA.ATTRIBUTED_ARR,
   SXXOA.ATTRIBUTED_NRR,
   SXXOA.ATTRIBUTED_IARR,
   SXXOA.ATTRIBUTED_IMYARR,
   SXXOA.TCV,
   SXXOA.ATTRIBUTION_CODE  ,
   SXXOA.LINKED_ATTRIB_ID,
   SXXOA.EXCEPTION_DETAIL,/* OA-Q1FY16*/
   SXXOA.ENT_INVENTORY_ITEM_ID/*FY16-JUNE-CDR:thvarghe*/,
     /*added   as part of Q2FY18 Kafka OPL project*/ 
   SXXOA.PARENT_SUB_SKU_OFFSET_ID,
   SXXOA.PARENT_SUB_SKU_ID,
   SXXOA.MULTI_OA_BUNDLE_ENABLED,
   SXXOA.ATTRIBUTION_DETAILS,
   SXXOA.PARENT_LINE_REF_NUMBER,
   SXXOA.ATTRIBUTED_ITEM,
   SXXOA.RECOGNIZED_ATTR_SALES_VALUES,
   SXXOA.RECOGNIZED_ATTR_TCV,
   SXXOA.BOOKING_VERSION,
   SXXOA.ERP_LINE_ID,
   SXXOA.ERP_PARENT_LINE_ID,
   SXXOA.CREATION_DATE,
 SXXOA.ACV_ATTRIBUTION_PCT,
     SXXOA.PRICING_TERM     /* SIGORANT ADDED AS PART OF Q2FY19 */ 
      FROM
      (
      SELECT 
   BATCH_ID,
   ATTRIBUTION_ID,
   --ORDER_NUMBER,
   LINE_REF_NUMBER,
   DATA_SOURCE,
   TRX_ID,
   PARENT_TRX_ID,
   --ORDERED_ITEM,
   INVENTORY_ITEM_ID,
   ATTRIBUTION_FLAG,
   --CISCO_BOOKED_FLAG,
   BUNDLE_TYPE,
   QUANTITY,
   ATTRIBUTED_UNIT_LIST_PRICE,
   ATTRIBUTED_UNIT_NET_PRICE,
   RECOGNIZED_PCT,
   ATTRIBUTED_PCT,
   --PUBLISH_FLAG,
   ATTRIBUTION_TYPE,
   --CREATED_BY,
   --CREATION_DATE,
   --LAST_UPDATED_BY,
   --LAST_UPDATE_DATE,
   --ORIG_OA_ATTRIB_ID,
   ACTION_CODE,
   CREATE_DATETIME,
   --SOURCE_DML_TYPE,
   --SOURCE_COMMIT_TIME,
   'RI' AS EXCEPTION_TYPE,
   EXCEPTION_CODE,
   ATTRIBUTED_EXT_LIST_PRICE,
   ATTRIBUTED_EXT_NET_PRICE,   
   WEB_ORDER_ID,
   --SUBSCRIPTION_CODE,
   ATTRIBUTED_SALES_VALUE,
   ATTRIBUTED_MRR,
   ATTRIBUTED_IMRR,
   ATTRIBUTED_ARR,
   ATTRIBUTED_NRR,
   ATTRIBUTED_IARR,
   ATTRIBUTED_IMYARR,
   TCV,
   ATTRIBUTION_CODE  ,
   LINKED_ATTRIB_ID,
   EXCEPTION_DETAIL ,/* OA-Q1FY16*/
   ENT_INVENTORY_ITEM_ID/*FY16-JUNE-CDR:thvarghe*/,
     /*added   as part of Q2FY18 Kafka OPL project*/ 
   PARENT_SUB_SKU_OFFSET_ID,
   PARENT_SUB_SKU_ID,
   MULTI_OA_BUNDLE_ENABLED,
   ATTRIBUTION_DETAILS,
   PARENT_LINE_REF_NUMBER,
   ATTRIBUTED_ITEM,
   RECOGNIZED_ATTR_SALES_VALUES,
   RECOGNIZED_ATTR_TCV,
   BOOKING_VERSION,
   ERP_LINE_ID,
   ERP_PARENT_LINE_ID,
   CREATION_DATE,
 ACV_ATTRIBUTION_PCT,
  PRICING_TERM     /* SIGORANT ADDED AS PART OF Q2FY19 */ 
       FROM $$NRTSTGDB.ST_XAAS_XXOA_ORDER_ATTRIB_NRT_NG  
       QUALIFY ROW_NUMBER () OVER (PARTITION BY ATTRIBUTION_ID ORDER BY CREATION_DATE DESC/*, REFRESH_DATETIME DESC*/)=1  
      )SXXOA 
       
      WHERE   NOT EXISTS (
      /* Get records that are not processed to WI eg: RI check on ITEM_KEY, SO_SBSCRPTN_ITM_SLS_TRX_KEY, PRODUCT_KEY of Bundle Line = -999 */
      SELECT 1
      FROM  $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WXSSA
      WHERE SXXOA.ATTRIBUTION_ID=WXSSA.ATTRIBUTION_ID 
      )
      AND NOT EXISTS
      (
       SELECT 1
       FROM $$EXCEPDB.EX_XAAS_XXOA_ORDER_ATTRIB_NRT_NG EXXOA
       WHERE EXXOA.ATTRIBUTION_ID = SXXOA.ATTRIBUTION_ID  
      )


Post SQL : 



Target2 Name : EX_XAAS_XXOA_ORDER_ATTRIB_NRT1_NG


Pre SQL : 
DELETE FROM $$EXCEPDB.EX_XAAS_XXOA_ORDER_ATTRIB_NRT_NG EXXOA 
    WHERE EXISTS 
    (SELECT 1 FROM $$NRTSTGDB.W_XAAS_SO_SBSCRPN_ATRBN_NRT_NG WXSSA
    WHERE EXXOA.ATTRIBUTION_ID=WXSSA.BK_OFFER_ATTRIBUTION_ID_INT 
  AND WXSSA.TSL_TRX_TYPE_CD='BOOKING'
  );


Post SQL : 
COLLECT STATS ON $$EXCEPDB.EX_XAAS_XXOA_ORDER_ATTRIB_NRT_NG;


Source3 Name : SQ_EX_SBP_XXOA_ORDER_ATTRIB_NRT_NG


Pre SQL : 



SQL Query : 
SELECT 
   WIXSSA.BATCH_ID,
   WIXSSA.ATTRIBUTION_ID,
   --WIXSSA.ORDER_NUMBER,
   WIXSSA.LINE_REF_NUMBER,
   WIXSSA.DATA_SOURCE,
   WIXSSA.TRX_ID,
   WIXSSA.PARENT_TRX_ID,
   --WIXSSA.ORDERED_ITEM,
   WIXSSA.INVENTORY_ITEM_ID,
   WIXSSA.ATTRIBUTION_FLAG,
   --WIXSSA.CISCO_BOOKED_FLAG,
   WIXSSA.BUNDLE_TYPE,
   WIXSSA.QUANTITY,
   WIXSSA.ATTRIBUTED_UNIT_LIST_PRICE,
   WIXSSA.ATTRIBUTED_UNIT_NET_PRICE,
   WIXSSA.RECOGNIZED_PCT,
   WIXSSA.ATTRIBUTED_PCT,
   --WIXSSA.PUBLISH_FLAG,
   WIXSSA.ATTRIBUTION_TYPE,
   --WIXSSA.CREATED_BY,
   --WIXSSA.CREATION_DATE,
   --WIXSSA.LAST_UPDATED_BY,
   --WIXSSA.LAST_UPDATE_DATE,
   --WIXSSA.ORIG_OA_ATTRIB_ID,
   WIXSSA.ACTION_CODE,
   WIXSSA.CREATE_DATETIME,
   --WIXSSA.SOURCE_DML_TYPE,
   --WIXSSA.SOURCE_COMMIT_TIME,
   WIXSSA.EXCEPTION_TYPE,
   WIXSSA.EXCEPTION_CODE,
   WIXSSA.ATTRIBUTED_EXT_LIST_PRICE,
   WIXSSA.ATTRIBUTED_EXT_NET_PRICE,
   WIXSSA.WEB_ORDER_ID,
   --WIXSSA.SUBSCRIPTION_CODE,
   WIXSSA.ATTRIBUTED_SALES_VALUE ,
   WIXSSA.ATTRIBUTED_MRR,
   WIXSSA.ATTRIBUTED_IMRR,
   WIXSSA.ATTRIBUTED_ARR,
   WIXSSA.ATTRIBUTED_NRR,
   WIXSSA.ATTRIBUTED_IARR,
   WIXSSA.ATTRIBUTED_IMYARR,
   WIXSSA.TCV,
   WIXSSA.ATTRIBUTION_CODE  ,
   WIXSSA.LINKED_ATTRIB_ID,
   WIXSSA.EXCEPTION_DETAIL,/* OA - Q1FY16*/
   WIXSSA.ENT_INVENTORY_ITEM_ID/*FY16-JUNE-CDR:thvarghe*/,
   /*added   as part of Q2FY18 Kafka OPL project*/ 
   WIXSSA.PARENT_SUB_SKU_OFFSET_ID,
   WIXSSA.PARENT_SUB_SKU_ID,
   WIXSSA.MULTI_OA_BUNDLE_ENABLED,
   WIXSSA.ATTRIBUTION_DETAILS,
   WIXSSA.PARENT_LINE_REF_NUMBER,
   WIXSSA.ATTRIBUTED_ITEM,
   WIXSSA.RECOGNIZED_ATTR_SALES_VALUES,
   WIXSSA.RECOGNIZED_ATTR_TCV,
   WIXSSA.BOOKING_VERSION,
   WIXSSA.ERP_LINE_ID,
   WIXSSA.ERP_PARENT_LINE_ID,
   WIXSSA.CREATION_DATE,
 WIXSSA.ACV_ATTRIBUTION_PCT,
 WIXSSA.PRICING_TERM     /* SIGORANT ADDED AS PART OF Q2FY19 */ 
   FROM  $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSA
      WHERE 
       WIXSSA.VALID_FLG = 'N'
      AND NOT EXISTS
      (
       SELECT 1
       FROM $$EXCEPDB.EX_SBP_XXOA_ORDER_ATTRIB_NRT_NG EXXOA
       WHERE EXXOA.ATTRIBUTION_ID = WIXSSA.ATTRIBUTION_ID 
      )
      AND WIXSSA.DATA_SOURCE ='SBP'
       
      UNION
      
      SELECT 
   SXXOA.BATCH_ID,
   SXXOA.ATTRIBUTION_ID,
   --SXXOA.ORDER_NUMBER,
   SXXOA.LINE_REF_NUMBER,
   SXXOA.DATA_SOURCE,
   SXXOA.TRX_ID,
   SXXOA.PARENT_TRX_ID,
   --SXXOA.ORDERED_ITEM,
   SXXOA.INVENTORY_ITEM_ID,
   SXXOA.ATTRIBUTION_FLAG,
   --SXXOA.CISCO_BOOKED_FLAG,
   SXXOA.BUNDLE_TYPE,
   SXXOA.QUANTITY,
   SXXOA.ATTRIBUTED_UNIT_LIST_PRICE,
   SXXOA.ATTRIBUTED_UNIT_NET_PRICE,
   SXXOA.RECOGNIZED_PCT,
   SXXOA.ATTRIBUTED_PCT,
   --SXXOA.PUBLISH_FLAG,
   SXXOA.ATTRIBUTION_TYPE,
   --SXXOA.CREATED_BY,
   --SXXOA.CREATION_DATE,
   --SXXOA.LAST_UPDATED_BY,
   --SXXOA.LAST_UPDATE_DATE,
   --SXXOA.ORIG_OA_ATTRIB_ID,
   SXXOA.ACTION_CODE,
   SXXOA.CREATE_DATETIME,
   --SXXOA.SOURCE_DML_TYPE,
   --SXXOA.SOURCE_COMMIT_TIME,
   SXXOA.EXCEPTION_TYPE,
   SXXOA.EXCEPTION_CODE,
   SXXOA.ATTRIBUTED_EXT_LIST_PRICE,
   SXXOA.ATTRIBUTED_EXT_NET_PRICE,   
   SXXOA.WEB_ORDER_ID,
   --SXXOA.SUBSCRIPTION_CODE,
   SXXOA.ATTRIBUTED_SALES_VALUE,
   SXXOA.ATTRIBUTED_MRR,
   SXXOA.ATTRIBUTED_IMRR,
   SXXOA.ATTRIBUTED_ARR,
   SXXOA.ATTRIBUTED_NRR,
   SXXOA.ATTRIBUTED_IARR,
   SXXOA.ATTRIBUTED_IMYARR,
   SXXOA.TCV,
   SXXOA.ATTRIBUTION_CODE  ,
   SXXOA.LINKED_ATTRIB_ID,
   SXXOA.EXCEPTION_DETAIL,/* OA-Q1FY16*/
   SXXOA.ENT_INVENTORY_ITEM_ID/*FY16-JUNE-CDR:thvarghe*/,
   /*added   as part of Q2FY18 Kafka OPL project*/ 
   SXXOA.PARENT_SUB_SKU_OFFSET_ID,
   SXXOA.PARENT_SUB_SKU_ID,
   SXXOA.MULTI_OA_BUNDLE_ENABLED,
   SXXOA.ATTRIBUTION_DETAILS,
   SXXOA.PARENT_LINE_REF_NUMBER,
   SXXOA.ATTRIBUTED_ITEM,
   SXXOA.RECOGNIZED_ATTR_SALES_VALUES,
   SXXOA.RECOGNIZED_ATTR_TCV,
   SXXOA.BOOKING_VERSION,
   SXXOA.ERP_LINE_ID,
   SXXOA.ERP_PARENT_LINE_ID,
   SXXOA.CREATION_DATE,
 SXXOA.ACV_ATTRIBUTION_PCT
   ,   SXXOA.PRICING_TERM     /* SIGORANT ADDED AS PART OF Q2FY19 */ 
      FROM
      (
      SELECT 
   BATCH_ID,
   ATTRIBUTION_ID,
   --ORDER_NUMBER,
   LINE_REF_NUMBER,
   DATA_SOURCE,
   TRX_ID,
   PARENT_TRX_ID,
   --ORDERED_ITEM,
   INVENTORY_ITEM_ID,
   ATTRIBUTION_FLAG,
   --CISCO_BOOKED_FLAG,
   BUNDLE_TYPE,
   QUANTITY,
   ATTRIBUTED_UNIT_LIST_PRICE,
   ATTRIBUTED_UNIT_NET_PRICE,
   RECOGNIZED_PCT,
   ATTRIBUTED_PCT,
   --PUBLISH_FLAG,
   ATTRIBUTION_TYPE,
   --CREATED_BY,
   --CREATION_DATE,
   --LAST_UPDATED_BY,
   --LAST_UPDATE_DATE,
   --ORIG_OA_ATTRIB_ID,
   ACTION_CODE,
   CREATE_DATETIME,
   --SOURCE_DML_TYPE,
   --SOURCE_COMMIT_TIME,
   'RI' AS EXCEPTION_TYPE,
   EXCEPTION_CODE,
   ATTRIBUTED_EXT_LIST_PRICE,
   ATTRIBUTED_EXT_NET_PRICE,   
   WEB_ORDER_ID,
   --SUBSCRIPTION_CODE,
   ATTRIBUTED_SALES_VALUE,
   ATTRIBUTED_MRR,
   ATTRIBUTED_IMRR,
   ATTRIBUTED_ARR,
   ATTRIBUTED_NRR,
   ATTRIBUTED_IARR,
   ATTRIBUTED_IMYARR,
   TCV,
   ATTRIBUTION_CODE  ,
   LINKED_ATTRIB_ID,
   EXCEPTION_DETAIL ,/* OA-Q1FY16*/
   ENT_INVENTORY_ITEM_ID/*FY16-JUNE-CDR:thvarghe*/,
   /*added   as part of Q2FY18 Kafka OPL project*/ 
   PARENT_SUB_SKU_OFFSET_ID,
   PARENT_SUB_SKU_ID,
   MULTI_OA_BUNDLE_ENABLED,
   ATTRIBUTION_DETAILS,
   PARENT_LINE_REF_NUMBER,
   ATTRIBUTED_ITEM,
   RECOGNIZED_ATTR_SALES_VALUES,
   RECOGNIZED_ATTR_TCV,
   BOOKING_VERSION,
   ERP_LINE_ID,
   ERP_PARENT_LINE_ID,
   CREATION_DATE,
 ACV_ATTRIBUTION_PCT
  ,   PRICING_TERM     /* SIGORANT ADDED AS PART OF Q2FY19 */ 
   FROM $$NRTSTGDB.ST_SBP_XXOA_ORDER_ATTRIB_NRT_NG  
       QUALIFY ROW_NUMBER () OVER (PARTITION BY ATTRIBUTION_ID ORDER BY CREATION_DATE DESC/*, REFRESH_DATETIME DESC*/)=1  
      )SXXOA 
       
      WHERE   NOT EXISTS (
      /* Get records that are not processed to WI eg: RI check on ITEM_KEY, SO_SBSCRPTN_ITM_SLS_TRX_KEY, PRODUCT_KEY of Bundle Line = -999 */
      SELECT 1
      FROM  $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WXSSA
      WHERE SXXOA.ATTRIBUTION_ID=WXSSA.ATTRIBUTION_ID 
      AND DATA_SOURCE='SBP')
      AND NOT EXISTS
      (
       SELECT 1
       FROM $$EXCEPDB.EX_SBP_XXOA_ORDER_ATTRIB_NRT_NG EXXOA
       WHERE EXXOA.ATTRIBUTION_ID = SXXOA.ATTRIBUTION_ID  
      )


Post SQL : 



Target3 Name : EX_SBP_XXOA_ORDER_ATTRIB_NRT1_NG


Pre SQL : 
DELETE FROM $$EXCEPDB.EX_SBP_XXOA_ORDER_ATTRIB_NRT_NG EXXOA 
    WHERE EXISTS 
    (SELECT 1 FROM $$NRTSTGDB.W_XAAS_SO_SBSCRPN_ATRBN_NRT_NG WXSSA
    WHERE EXXOA.ATTRIBUTION_ID=WXSSA.BK_OFFER_ATTRIBUTION_ID_INT 
  AND WXSSA.TSL_TRX_TYPE_CD='ORDER'
  );


Post SQL : 
COLLECT STATS ON $$EXCEPDB.EX_SBP_XXOA_ORDER_ATTRIB_NRT_NG;


Source4 Name : SQ_WI_XAAS_SO_SBSCRN_ATRBTN_TV_NRT


Pre SQL : 



SQL Query : 
SELECT 
     WIXSSA.ATTRIBUTION_ID AS BK_OFFER_ATTRIBUTION_ID_INT
    ,WIXSSA.LINE_REF_NUMBER AS SK_TSL_UNIQUE_ID_INT
    ,WIXSSA.ORDERED_PRODUCT_KEY AS ORDERED_PRODUCT_KEY
    ,WIXSSA.ATTRIBUTION_FLAG AS ATTRIBUTION_FLG
    ,'Y' AS CISCO_BOOKED_FLG
    ,COALESCE(WIXSSA.BUNDLE_TYPE,'UNKNOWN') AS BUNDLE_TYPE_CD
    ,CASE  WHEN WIXSSA.TRX_REASON_CD <>'UNKNOWN' AND WIXSSA.SALES_VALUE_TRXL_AMT < 0.0000000 
    THEN (COALESCE(WIXSSA.QUANTITY,0) * -1)
      WHEN WIXSSA.ACTION_CD ='REMOVE' THEN (COALESCE(WIXSSA.QUANTITY,0) * -1)
      ELSE  COALESCE(WIXSSA.QUANTITY,0)   END AS SKU_QTY
    ,COALESCE(WIXSSA.ATTRIBUTED_UNIT_LIST_PRICE,0.0000000) AS ATTRIBUTED_UNIT_LIST_PRICE
    ,COALESCE(WIXSSA.ATTRIBUTED_UNIT_NET_PRICE,0.0000000) AS  ATTRIBUTED_UNIT_NET_PRICE
    ,COALESCE(WIXSSA.RECOGNIZED_PCT, 100) AS BOOKINGS_PCT
    ,COALESCE(WIXSSA.ATTRIBUTED_PCT, -999.00) AS ATTRIBUTION_PCT
    ,COALESCE(WIXSSA.ATTRIBUTION_TYPE, 'UNKNOWN') AS TSL_TRX_TYPE_CD 
    ,COALESCE(WIXSSA.EXCEPTION_CODE,'UNKNOWN') AS TSL_EXCEPTION_REASON_CD
    ,COALESCE(WIXSSA.ATTRIBUTED_EXT_LIST_PRICE,0.0000000) AS ATTRIBUTED_EXTENDED_LIST_PRICE
    ,COALESCE(WIXSSA.ATTRIBUTED_EXT_NET_PRICE,0.0000000) AS  ATTRIBUTED_EXTENDED_NET_PRICE 
    ,COALESCE(WIXSSA.SUBSCRIPTION_CODE,'UNKNOWN') AS SBP_SUBSCRIPTION_CD
    ,COALESCE(WIXSSA.ATTRIBUTED_SALES_VALUE,0.0000000) AS SALES_VALUE_TRXL_AMT
    ,COALESCE(WIXSSA.ATTRIBUTED_MRR,0.0000000) AS MTHLY_RCRR_REV_TRXL_AMT
    ,COALESCE(WIXSSA.ATTRIBUTED_IMRR,0.0000000) AS INCRMTL_MTHLY_RCRR_REVTRXL_AMT
    ,COALESCE(WIXSSA.ATTRIBUTED_ARR,0.0000000) AS ANNUAL_RCRR_CHARGE_TRXL_AMT
    ,COALESCE(WIXSSA.ATTRIBUTED_NRR,0.0000000) AS NON_RCRR_REV_TRXL_AMT
    ,COALESCE(WIXSSA.ATTRIBUTED_IARR,0.0000000) AS INCRMTL_ANNL_RECUR_REVTRXL_AMT
    ,COALESCE(WIXSSA.ATTRIBUTED_IMYARR,0.0000000) AS INCRMTL_MLTYR_RCRR_REVTRXL_AMT
    ,COALESCE(WIXSSA.TCV,0.0000000) AS TOTAL_CONTRACT_VALUE_TRXL_AMT
    ,WIXSSA.ATTRIBUTION_CD AS ATTRIBUTION_CD
    ,COALESCE(WIXSSA.LINKED_ATTRIB_ID,-999) AS SK_ATTRIBUTION_ID_INT
    ,CASE WHEN WIXSSA.EXCEPTION_CODE IS NULL THEN CAST('SUCCESS' AS VARCHAR(20)) ELSE CAST('FAILURE' AS VARCHAR(20)) END AS EXCEPTION_STATUS_CD
    ,WIXSSA.CREATION_DATE AS SOURCE_COMMIT_DTM
    ,CAST(WIXSSA.CREATION_DATE  AS DATE) AS DV_SOURCE_COMMIT_DT
    ,WIXSSA.SO_SBSCRPTN_ITM_SLS_TRX_KEY AS SO_SBSCRPTN_ITM_SLS_TRX_KEY
    ,WIXSSA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY AS PARENT_SO_SBSCRP_ITMSLSTRX_KEY
    ,COALESCE(WIXSSA.WEB_ORDER_ID,'UNKNOWN') AS CCW_WEB_ORDER_ID
    ,COALESCE(WIXSSA.EXCEPTION_DETAIL,'UNKNOWN') AS EXCEPTION_DETAIL_DESCR
    ,COALESCE(WIXSSA.QUANTITY,0.0000000) AS ORIGINAL_TRX_QTY
    ,CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM
    ,USER AS EDW_CREATE_USER
    ,CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM
    ,USER AS EDW_UPDATE_USER,
    WIXSSA.ENTERPRISE_SKU_PRDT_KEY AS ENTERPRISE_SKU_PRDT_KEY
    ,'Y' AS DV_NET_CHANGE_FLG
    ,WIXSSA.CREATION_DATE AS START_TV_DTM
    ,COALESCE(WIXSSA.RECOGNIZED_ATTR_SALES_VALUES,0.0000000)
     ,COALESCE(WIXSSA.PARENT_OFFER_ATTRIB_ID_INT,-999 ) /* 3 NRS MPOB columns added*/
   ,CASE  WHEN WIXSSA.BUNDLE_TYPE = 'Multiple Performance Obligations (MPOB)' THEN 'MPOB' /*This WHEN Covers BIB, BIB OFFSET & Stand Alone OFFSET*/
    WHEN (WIXSSA.ATTRIBUTION_CD  = 'ATTRIBUTED' AND  WIXOA_MPOB.ATTRIBUTION_ID IS NOT NULL ) THEN 'MPOB' 
   ELSE 'UNKNOWN'  END AS POB_TYPE_CD
   ,COALESCE(WIXOA_MPOB.ORDERED_PRODUCT_KEY,-999)  AS DV_POB_TOP_PRDT_KEY
    ,WIXSSA.NRS_TRANSITION_FLG AS NRS_TRANSITION_FLG /*NRS PI3 CHANGES*/
 ,COALESCE(WIXSSA.ACV_ATTRIBUTION_PCT,0.0000000)
 ,COALESCE(WIXSSA.PRICING_TERM,1)  AS  PRICING_TERM_MTHS_CNT   /* SIGORANT ADDED AS PART OF Q2FY19 */
 ,WIXSSA.AS_ARCHITECTURE_FLG 
    FROM 
    $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG WIXSSA
     LEFT OUTER JOIN  (SELECT BK_OFFER_ATTRIBUTION_ID_INT FROM $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ATRB_NG_NRT  GROUP BY 1 )NXSSA
   ON WIXSSA.ATTRIBUTION_ID=NXSSA.BK_OFFER_ATTRIBUTION_ID_INT
    LEFT JOIN $$NRTSTGDB.WI_XAAS_SO_SBSCRPTN_ATRBTN_NRT_NG  WIXOA_MPOB ON WIXOA_MPOB.BUNDLE_TYPE = 'Multiple Performance Obligations (MPOB)' AND WIXOA_MPOB.AS_ARCHITECTURE_FLG = 'N' AND  /*dbommise: Parallel OA changes Q3FY19 */ 
     ((WIXOA_MPOB.ATTRIBUTION_ID  = WIXSSA.PARENT_SUB_SKU_ID  AND WIXOA_MPOB.ATTRIBUTION_CD = 'BIB' ) OR
 ( WIXSSA.PARENT_SUB_SKU_ID  IS NULL  AND WIXOA_MPOB.TRX_ID  = WIXSSA.PARENT_TRX_ID AND  WIXOA_MPOB.ATTRIBUTION_CD = 'OFFSET'  AND WIXSSA.DATA_SOURCE  = 'TSL' 
 AND WIXOA_MPOB.DATA_SOURCE=WIXSSA.DATA_SOURCE  )  OR 
 (WIXSSA.PARENT_SUB_SKU_ID  IS NULL  AND WIXOA_MPOB.LINE_REF_NUMBER  = WIXSSA.PARENT_LINE_REF_NUMBER AND  WIXOA_MPOB.ATTRIBUTION_CD = 'OFFSET'  AND WIXSSA.DATA_SOURCE  = 'SBP'
 AND WIXOA_MPOB.DATA_SOURCE=WIXSSA.DATA_SOURCE   ) )   /*Added the join as part of NRS MPOB Changes*/
    WHERE  WIXSSA.VALID_FLG = 'Y'


Post SQL : 



Target4 Name : WI_XAAS_SO_SBSCRN_ATRBTN_TV_NRT1_NG


Pre SQL : 
DELETE FROM  $$NRTSTGDB.WI_XAAS_SO_SBSCRN_ATRBTN_TV_NRT_NG ALL;


Post SQL : 
COLLECT STATS ON $$NRTSTGDB.WI_XAAS_SO_SBSCRN_ATRBTN_TV_NRT_NG;
 
 
 UPDATE  WI
 FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRN_ATRBTN_TV_NRT_NG WI,
      (SELECT BK_OFFER_ATTRIBUTION_ID_INT,START_TV_DTM,SALES_VALUE_TRXL_AMT,SKU_QTY,RECOGNIZED_SALES_VALUE_LOCAL_AMT,PRICING_TERM_MTHS_CNT,ATTRIBUTED_UNIT_LIST_PRICE        FROM
   $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ATRB_NG_NRT_TV WHERE END_TV_DTM=CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))) NRT_TV
 SET DV_NET_CHANGE_FLG='N'
 WHERE NRT_TV.BK_OFFER_ATTRIBUTION_ID_INT=WI.BK_OFFER_ATTRIBUTION_ID_INT
 --AND   NRT_TV.START_TV_DTM=WI.START_TV_DTM
 AND(NRT_TV.SALES_VALUE_TRXL_AMT=WI.SALES_VALUE_TRXL_AMT
 AND NRT_TV.SKU_QTY=WI.SKU_QTY
 AND NRT_TV.RECOGNIZED_SALES_VALUE_LOCAL_AMT=WI.RECOGNIZED_ATTR_SALES_VALUES
 AND NRT_TV.PRICING_TERM_MTHS_CNT=WI.PRICING_TERM_MTHS_CNT /*SIGORANT ADDED AS PART OF Q2FY19 */
AND NRT_TV.ATTRIBUTED_UNIT_LIST_PRICE=WI.ATTRIBUTED_UNIT_LIST_PRICE     );
 
 /*
 UPDATE $$NRTSTGDB.WI_XAAS_SO_SBSCRN_ATRBTN_TV_NRT_NG WI
 SET DV_NET_CHANGE_FLG='Y'
 WHERE BK_OFFER_ATTRIBUTION_ID_INT 
 NOT IN (SELECT BK_OFFER_ATTRIBUTION_ID_INT FROM $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ATRB_NG_NRT_TV
 );
 */


Source5 Name : SQ_W_XAAS_SO_SBSCR_ATRB_NG_NRT


Pre SQL : 
DELETE FROM $$WORKDB.W_XAAS_SO_SBSCR_ATRB_NG_NRT ALL;


SQL Query : 
SELECT
  TV_OUTPUT.BK_OFFER_ATTRIBUTION_ID_INT   
 ,TV_OUTPUT.SO_SBSCRPTN_ITM_SLS_TRX_KEY          
 ,TV_OUTPUT.PARENT_SO_SBSCRP_ITMSLSTRX_KEY           
 ,TV_OUTPUT.SK_TSL_UNIQUE_ID_INT               
 ,TV_OUTPUT.ORDERED_PRODUCT_KEY              
 ,TV_OUTPUT.ATTRIBUTION_FLG                
 ,TV_OUTPUT.CISCO_BOOKED_FLG                       
 ,TV_OUTPUT.BUNDLE_TYPE_CD    
 ,TV_OUTPUT.SKU_QTY     
 ,TV_OUTPUT.ATTRIBUTED_UNIT_LIST_PRICE                  
 ,TV_OUTPUT.ATTRIBUTED_UNIT_NET_PRICE               
 ,TV_OUTPUT.BOOKINGS_PCT               
 ,TV_OUTPUT.ATTRIBUTION_PCT       
 ,TV_OUTPUT.TSL_TRX_TYPE_CD
 ,TV_OUTPUT.TSL_EXCEPTION_REASON_CD 
 ,TV_OUTPUT.ATTRIBUTED_EXTENDED_LIST_PRICE           
 ,TV_OUTPUT.ATTRIBUTED_EXTENDED_NET_PRICE          
 ,TV_OUTPUT.SBP_SUBSCRIPTION_CD       
 ,TV_OUTPUT.SALES_VALUE_TRXL_AMT
 ,TV_OUTPUT.MTHLY_RCRR_REV_TRXL_AMT   
 ,TV_OUTPUT.INCRMTL_MTHLY_RCRR_REVTRXL_AMT         
 ,TV_OUTPUT.ANNUAL_RCRR_CHARGE_TRXL_AMT
 ,TV_OUTPUT.NON_RCRR_REV_TRXL_AMT
 ,TV_OUTPUT.INCRMTL_ANNL_RECUR_REVTRXL_AMT 
 ,TV_OUTPUT.INCRMTL_MLTYR_RCRR_REVTRXL_AMT                
 ,TV_OUTPUT.TOTAL_CONTRACT_VALUE_TRXL_AMT         
 ,TV_OUTPUT.ATTRIBUTION_CD           
 ,TV_OUTPUT.SK_ATTRIBUTION_ID_INT             
 ,TV_OUTPUT.EXCEPTION_STATUS_CD           
 ,TV_OUTPUT.SOURCE_COMMIT_DTM   
 ,TV_OUTPUT.DV_SOURCE_COMMIT_DT
 ,TV_OUTPUT.CCW_WEB_ORDER_ID              
 ,TV_OUTPUT.EXCEPTION_DETAIL_DESCR        
 ,TV_OUTPUT.ORIGINAL_TRX_QTY   
,TV_OUTPUT.ENTERPRISE_SKU_PRDT_KEY  
,TV_OUTPUT.PARENT_OFFER_ATTRIB_ID_INT  /*Added as part of NRS changes*/
,TV_OUTPUT.POB_TYPE_CD
,TV_OUTPUT.DV_POB_TOP_PRDT_KEY
,TV_OUTPUT.NRS_TRANSITION_FLG 
,TV_OUTPUT.DV_NET_CHANGE_FLG
,TV_OUTPUT.RECOGNIZED_ATTR_SALES_VALUES
 ,TV_OUTPUT.ACV_ATTRIBUTION_PCT
 ,TV_OUTPUT.PRICING_TERM_MTHS_CNT   /* SIGORANT ADDED AS PART OF Q2FY19 */ 
 ,TV_OUTPUT.AS_ARCHITECTURE_FLG
 ,CURRENT_TIMESTAMP(0) EDW_CREATE_DTM
 ,USER  EDW_CREATE_USER
 ,CURRENT_TIMESTAMP(0)  EDW_UPDATE_DTM
 ,USER EDW_UPDATE_USER  
 ,TV_OUTPUT.START_TV_DTM            
 ,COALESCE(MAX (TV_OUTPUT.START_TV_DTM - INTERVAL '1' SECOND) OVER (PARTITION BY TV_OUTPUT.BK_OFFER_ATTRIBUTION_ID_INT
                         ORDER BY TV_OUTPUT.START_TV_DTM ASC ROWS BETWEEN 1 
                       FOLLOWING AND 1 FOLLOWING), CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))) AS END_TV_DTM
,'N' ACTION_CODE
 ,(CASE WHEN ROW_NUMBER () OVER (PARTITION BY TV_OUTPUT.BK_OFFER_ATTRIBUTION_ID_INT ORDER BY TV_OUTPUT.START_TV_DTM ASC) = 1 AND NXSAN1.BK_OFFER_ATTRIBUTION_ID_INT IS NOT NULL 
 THEN 'U' ELSE 'I' END) AS DML_TYPE
 FROM(
 SELECT
  TV_INPUT.BK_OFFER_ATTRIBUTION_ID_INT   
 ,TV_INPUT.SK_TSL_UNIQUE_ID_INT          
 ,TV_INPUT.ORDERED_PRODUCT_KEY           
 ,TV_INPUT.ATTRIBUTION_FLG               
 ,TV_INPUT.CISCO_BOOKED_FLG              
 ,TV_INPUT.BUNDLE_TYPE_CD                
 ,TV_INPUT.SKU_QTY                       
 ,TV_INPUT.ATTRIBUTED_UNIT_LIST_PRICE    
 ,TV_INPUT.ATTRIBUTED_UNIT_NET_PRICE     
 ,TV_INPUT.BOOKINGS_PCT                  
 ,TV_INPUT.ATTRIBUTION_PCT               
 ,TV_INPUT.TSL_TRX_TYPE_CD               
 ,TV_INPUT.TSL_EXCEPTION_REASON_CD       
 ,TV_INPUT.ATTRIBUTED_EXTENDED_LIST_PRICE
 ,TV_INPUT.ATTRIBUTED_EXTENDED_NET_PRICE 
 ,TV_INPUT.SBP_SUBSCRIPTION_CD           
 ,TV_INPUT.SALES_VALUE_TRXL_AMT          
 ,TV_INPUT.MTHLY_RCRR_REV_TRXL_AMT       
 ,TV_INPUT.INCRMTL_MTHLY_RCRR_REVTRXL_AMT
 ,TV_INPUT.ANNUAL_RCRR_CHARGE_TRXL_AMT   
 ,TV_INPUT.NON_RCRR_REV_TRXL_AMT         
 ,TV_INPUT.INCRMTL_ANNL_RECUR_REVTRXL_AMT
 ,TV_INPUT.INCRMTL_MLTYR_RCRR_REVTRXL_AMT
 ,TV_INPUT.TOTAL_CONTRACT_VALUE_TRXL_AMT 
 ,TV_INPUT.ATTRIBUTION_CD                
 ,TV_INPUT.SK_ATTRIBUTION_ID_INT         
 ,TV_INPUT.EXCEPTION_STATUS_CD           
 ,TV_INPUT.SOURCE_COMMIT_DTM             
 ,TV_INPUT.DV_SOURCE_COMMIT_DT           
 ,TV_INPUT.SO_SBSCRPTN_ITM_SLS_TRX_KEY   
 ,TV_INPUT.PARENT_SO_SBSCRP_ITMSLSTRX_KEY
 ,TV_INPUT.CCW_WEB_ORDER_ID              
 ,TV_INPUT.EXCEPTION_DETAIL_DESCR        
 ,TV_INPUT.ORIGINAL_TRX_QTY                            
 ,TV_INPUT.ENTERPRISE_SKU_PRDT_KEY       
 ,TV_INPUT.DV_NET_CHANGE_FLG
 ,TV_INPUT.START_TV_DTM 
 ,TV_INPUT.PARENT_OFFER_ATTRIB_ID_INT
 ,TV_INPUT.POB_TYPE_CD
 ,TV_INPUT.DV_POB_TOP_PRDT_KEY
 ,TV_INPUT.NRS_TRANSITION_FLG
 ,TV_INPUT.RECOGNIZED_ATTR_SALES_VALUES
 ,TV_INPUT.ACV_ATTRIBUTION_PCT
 ,TV_INPUT.PRICING_TERM_MTHS_CNT   /* SIGORANT ADDED AS PART OF Q2FY19 */ 
 ,TV_INPUT.AS_ARCHITECTURE_FLG
 FROM(
 SELECT
  WISAN.BK_OFFER_ATTRIBUTION_ID_INT   
 ,WISAN.SK_TSL_UNIQUE_ID_INT          
 ,WISAN.ORDERED_PRODUCT_KEY           
 ,WISAN.ATTRIBUTION_FLG               
 ,WISAN.CISCO_BOOKED_FLG              
 ,WISAN.BUNDLE_TYPE_CD                
 ,WISAN.SKU_QTY                       
 ,WISAN.ATTRIBUTED_UNIT_LIST_PRICE    
 ,WISAN.ATTRIBUTED_UNIT_NET_PRICE     
 ,WISAN.RECOGNIZED_PCT   as BOOKINGS_PCT               
 ,WISAN.ATTRIBUTION_PCT               
 ,WISAN.TSL_TRX_TYPE_CD               
 ,WISAN.TSL_EXCEPTION_REASON_CD       
 ,WISAN.ATTRIBUTED_EXTENDED_LIST_PRICE
 ,WISAN.ATTRIBUTED_EXTENDED_NET_PRICE 
 ,WISAN.SBP_SUBSCRIPTION_CD           
 ,WISAN.SALES_VALUE_TRXL_AMT          
 ,WISAN.MTHLY_RCRR_REV_TRXL_AMT       
 ,WISAN.INCRMTL_MTHLY_RCRR_REVTRXL_AMT
 ,WISAN.ANNUAL_RCRR_CHARGE_TRXL_AMT   
 ,WISAN.NON_RCRR_REV_TRXL_AMT         
 ,WISAN.INCRMTL_ANNL_RECUR_REVTRXL_AMT
 ,WISAN.INCRMTL_MLTYR_RCRR_REVTRXL_AMT
 ,WISAN.TOTAL_CONTRACT_VALUE_TRXL_AMT 
 ,WISAN.ATTRIBUTION_CD                
 ,WISAN.SK_ATTRIBUTION_ID_INT         
 ,WISAN.EXCEPTION_STATUS_CD           
 ,WISAN.SOURCE_COMMIT_DTM             
 ,WISAN.DV_SOURCE_COMMIT_DT           
 ,WISAN.SO_SBSCRPTN_ITM_SLS_TRX_KEY   
 ,WISAN.PARENT_SO_SBSCRP_ITMSLSTRX_KEY
 ,WISAN.CCW_WEB_ORDER_ID              
 ,WISAN.EXCEPTION_DETAIL_DESCR        
 ,WISAN.ORIGINAL_TRX_QTY                            
 ,WISAN.ENTERPRISE_SKU_PRDT_KEY       
 ,WISAN.DV_NET_CHANGE_FLG
 ,WISAN.START_TV_DTM 
 ,WISAN.PARENT_OFFER_ATTRIB_ID_INT
 ,WISAN.POB_TYPE_CD
 ,WISAN.DV_POB_TOP_PRDT_KEY
 ,WISAN.NRS_TRANSITION_FLG 
 ,WISAN.RECOGNIZED_ATTR_SALES_VALUES  
 ,WISAN.ACV_ATTRIBUTION_PCT   
, WISAN.PRICING_TERM_MTHS_CNT   /* SIGORANT ADDED AS PART OF Q2FY19 */  
,WISAN.AS_ARCHITECTURE_FLG
 FROM $$NRTSTGDB.WI_XAAS_SO_SBSCRN_ATRBTN_TV_NRT_NG WISAN   
 UNION ALL
 SELECT
  NXSAN.BK_OFFER_ATTRIBUTION_ID_INT   
 ,NXSAN.SK_TSL_UNIQUE_ID_INT          
 ,NXSAN.ORDERED_PRODUCT_KEY           
 ,NXSAN.ATTRIBUTION_FLG               
 ,NXSAN.CISCO_BOOKED_FLG              
 ,NXSAN.BUNDLE_TYPE_CD                
 ,NXSAN.SKU_QTY                       
 ,NXSAN.ATTRIBUTED_UNIT_LIST_PRICE    
 ,NXSAN.ATTRIBUTED_UNIT_NET_PRICE     
 ,NXSAN.BOOKINGS_PCT                         
 ,NXSAN.ATTRIBUTION_PCT               
 ,NXSAN.TSL_TRX_TYPE_CD               
 ,NXSAN.TSL_EXCEPTION_REASON_CD       
 ,NXSAN.ATTRIBUTED_EXTENDED_LIST_PRICE
 ,NXSAN.ATTRIBUTED_EXTENDED_NET_PRICE 
 ,NXSAN.SBP_SUBSCRIPTION_CD           
 ,NXSAN.SALES_VALUE_TRXL_AMT          
 ,NXSAN.MTHLY_RCRR_REV_TRXL_AMT       
 ,NXSAN.INCRMTL_MTHLY_RCRR_REVTRXL_AMT
 ,NXSAN.ANNUAL_RCRR_CHARGE_TRXL_AMT   
 ,NXSAN.NON_RCRR_REV_TRXL_AMT         
 ,NXSAN.INCRMTL_ANNL_RECUR_REVTRXL_AMT
 ,NXSAN.INCRMTL_MLTYR_RCRR_REVTRXL_AMT
 ,NXSAN.TOTAL_CONTRACT_VALUE_TRXL_AMT 
 ,NXSAN.ATTRIBUTION_CD                
 ,NXSAN.SK_ATTRIBUTION_ID_INT         
 ,NXSAN.EXCEPTION_STATUS_CD           
 ,NXSAN.SOURCE_COMMIT_DTM             
 ,NXSAN.DV_SOURCE_COMMIT_DT           
 ,NXSAN.SO_SBSCRPTN_ITM_SLS_TRX_KEY   
 ,NXSAN.PARENT_SO_SBSCRP_ITMSLSTRX_KEY
 ,NXSAN.CCW_WEB_ORDER_ID              
 ,NXSAN.EXCEPTION_DETAIL_DESCR        
 ,NXSAN.ORIGINAL_TRX_QTY                            
 ,NXSAN.ENTERPRISE_SKU_PRDT_KEY       
 ,'N' DV_NET_CHANGE_FLG
 ,NXSAN.START_TV_DTM
 ,NXSAN.PARENT_OFFER_ATTRIB_ID_INT
 ,NXSAN.POB_TYPE_CD
 ,NXSAN.DV_POB_TOP_PRDT_KEY
 ,NXSAN.NRS_TRANSITION_FLG  
 ,NXSAN.RECOGNIZED_SALES_VALUE_LOCAL_AMT
 ,NXSAN.ACV_ATTRIBUTION_PCT 
,   NXSAN.PRICING_TERM_MTHS_CNT   /* 
ORANT ADDED AS PART OF Q2FY19 */  
,NXSAN.AS_ARCHITECTURE_FLG
 FROM $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ATRB_NG_NRT_TV  NXSAN   
 WHERE
      NXSAN.END_TV_DTM = CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))
   AND EXISTS (SELECT 1 FROM  $$NRTSTGDB.WI_XAAS_SO_SBSCRN_ATRBTN_TV_NRT_NG ST
               WHERE ST.BK_OFFER_ATTRIBUTION_ID_INT =NXSAN.BK_OFFER_ATTRIBUTION_ID_INT)  
 )TV_INPUT
 QUALIFY ROW_NUMBER () OVER (PARTITION BY TV_INPUT.BK_OFFER_ATTRIBUTION_ID_INT, TV_INPUT.START_TV_DTM 
  ORDER BY TV_INPUT.START_TV_DTM DESC) = 1
 )TV_OUTPUT
 LEFT JOIN
  $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ATRB_NG_NRT_TV NXSAN1
  ON 
  TV_OUTPUT.BK_OFFER_ATTRIBUTION_ID_INT=NXSAN1.BK_OFFER_ATTRIBUTION_ID_INT
  AND 
  NXSAN1.END_TV_DTM= CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))


Post SQL : 



Target5 Name : W_XAAS_SO_SBSCR_ATRB_NG_NRT


Pre SQL : 



Post SQL : 
COLLECT STATS ON $$WORKDB.W_XAAS_SO_SBSCR_ATRB_NG_NRT;


 INSERT INTO $$COMREFVWDB.R_TRX_PRODUCT
 SEL DISTINCT ORDERED_PRODUCT_KEY,CURRENT_TIMESTAMP(0),'EDW_XAAS_NRT_USER',CURRENT_TIMESTAMP(0),'EDW_XAAS_NRT_USER' FROM
 $$WORKDB.W_XAAS_SO_SBSCR_ATRB_NG_NRT WHERE ORDERED_PRODUCT_KEY NOT IN (SELECT DISTINCT PRODUCT_KEY FROM $$COMREFVWDB.R_TRX_PRODUCT);