ETL Name:	wf_WI_SCA_FOR_TSL_TRX_NRT_DEF_NG.xml


Session 1: 	s_m_WI_SCA_FOR_TSL_TRX_NRT_DEF_NG
Mapping 1: 	m_WI_SCA_FOR_TSL_TRX_NRT_DEF_NG


Source1 Name : SQ_WI_SCA_FOR_TSL_TRX_NRT_DEF


Pre SQL : 
DELETE FROM $$NRTSTGDB.WI_SCA_FOR_TSL_TRX_NRT_DEF_NG;


SQL Query : 
SELECT
   SSCAN.SLS_CREDIT_ASGNMT_SLS_TRX_KEY  AS SLS_CREDIT_ASGNMT_SLS_TRX_KEY,
   'R' AS SALES_CREDIT_USAGE_CD,
   'D' AS SALES_CREDIT_UNALLOCATED_FLG, 
   'UNKNOWN' AS SLS_CREDIT_ASGNMT_MODE_CD ,
   WISC.TRX_SPLIT_SC_ID AS SK_TRX_SC_ID_INT,
   '=' OVERLAY_TYPE,
    CASE WHEN NDEF.BK_ISO_COUNTRY_CODE IS NULL THEN
  COALESCE(NDSC.SALES_REP_NUMBER,'UNKNOWN')
  ELSE
  COALESCE(NDEF.SALES_REP_NUMBER,'UNKNOWN') END AS SALES_REP_NUM,
   'DR' AS BK_SLS_TERR_ASSIGNMENT_TYPE_CD,
   WISC.SO_SBSCRPTN_ITM_SLS_TRX_KEY,
  COALESCE(NDEF.SALES_TERRITORY_KEY,-999)   SALES_TERRITORY_KEY,
   -999 AS SRC_RPTD_REBOK_OTM_TERR_ID_INT,
   -999 AS SRC_RPTD_REBOK_OTM_TERR_NAME,  
   -999 AS SRC_RPTD_REBOK_OTM_TERR_TYP_CD,
   'UNKNOWN' AS BK_SALES_CREDIT_TYPE_CODE,
   'UNKNOWN' AS BK_CREATED_BY_ERP_USER_NAME,
   'UNKNOWN' AS BK_SLS_CRDT_ASGNMT_RSN_CD, 
   WISC.TSL_PROCESSED_DTM AS SCA_CREATE_DTM,
   CAST(TSL_PROCESSED_DTM AS DATE) DV_SCA_CREATE_DT,
   WISC.SOURCE_COMMIT_DTM AS SCA_LAST_UPDATE_DTM,   
   CAST(WISC.SOURCE_COMMIT_DTM AS DATE) AS DV_SCA_LAST_UPDATE_DT,
   NDSC.SPLIT_PCT AS SPLIT_PCT,
   WISC.SOURCE_COMMIT_DTM AS EFFECTIVE_START_DTM,
   CAST(WISC.SOURCE_COMMIT_DTM AS DATE) AS  DV_EFFECTIVE_START_DT ,       
    '3500-01-01 00:00:00' AS EFFECTIVE_END_DTM,
    CAST( '3500-01-01' AS DATE) AS DV_EFFECTIVE_END_DT ,
   'N' AS REBOK_CHANNEL_FLG, 
   WISC.SOURCE_COMMIT_DTM AS SOURCE_COMMIT_DTM,
   CAST(WISC.SOURCE_COMMIT_DTM AS DATE) AS DV_SOURCE_COMMIT_DT,
   CURRENT_TIMESTAMP(0) AS EDW_CREATE_DTM,
   USER  AS EDW_CREATE_USER ,
   CURRENT_TIMESTAMP(0) AS EDW_UPDATE_DTM ,
   USER AS EDW_UPDATE_USER,
   '=' AS UCRM_CASE_NUM,
   -999 TRX_SPLIT_BU_KEY,
   -999 TRX_SPLIT_ID,
   -999 SK_OFFER_ATTRIBUTION_ID_INT,
   1.00 OA_SPLIT,
   -999 SK_RTR_ATTRIBUTION_ID_INT ,
   1.00 RTR_SPLIT,
   1.00 TOTAL_SPLIT,
   -999 ATTR_PRDT_AS_NEW_OR_RNWL_KEY,
   'UNKNOWN' SALES_MOTION_CD,
  'N' ACTION_CODE, 
  CASE
  WHEN NXSASN.SLS_CREDIT_ASGNMT_SLS_TRX_KEY  IS NOT NULL 
  THEN 'U' ELSE 'I' END AS DML_TYPE 
  FROM 
  (SELECT SPLIT_PCT,SALES_REP_NUMBER, SALES_TERRITORY_KEY,START_TV_DT, END_TV_DT 
  FROM $$NRTNCRVWDB.N_CNTRY_SLS_CREDIT_DEFAULT_TV WHERE BK_ISO_COUNTRY_CODE='UNK' AND END_TV_DT='3500-01-01' AND BK_TRX_SOURCE_TYPE_CD = 'ORDLN' 
  ) NDSC,
  $$NRTSTGDB.WI_DEFAULT_TSL_SC_NG WISC
  INNER JOIN $$COMREFVWDB.N_CSTMR_ACCT_LOCATR_ASGN_TV ASGN
   ON WISC.SHIP_TO_CUST_ACCT_LOC_USE_KEY = ASGN.ERP_CUST_ACCOUNT_LOCATION_KEY AND ASGN.END_TV_DATE='3500-01-01'
  INNER JOIN $$COMREFVWDB.N_POSTAL_ADDRESS_LOCATOR_TV LOC
   ON ASGN.LOCATOR_KEY = LOC.LOCATOR_KEY AND LOC.END_TV_DATE='3500-01-01'
  INNER JOIN $$ETLVWDB.SM_XAAS_SCA_SLS_TRX_NG_NRT SSCAN 
   ON WISC.TRX_SPLIT_SC_ID=SSCAN.SK_TRX_SPLIT_SC_ID_INT
  LEFT OUTER JOIN $$NRTNCRVWDB.N_CNTRY_SLS_CREDIT_DEFAULT_TV NDEF
   ON NDEF.BK_ISO_COUNTRY_CODE = LOC.ISO_COUNTRY_CODE AND NDEF.END_TV_DT='3500-01-01'
   AND NDEF.BK_TRX_SOURCE_TYPE_CD = 'ORDLN' 
  LEFT JOIN $$NRTNCRVWDB.N_XAAS_SCA_SLS_TRX_NG_NRT NXSASN
   ON SSCAN.SLS_CREDIT_ASGNMT_SLS_TRX_KEY = NXSASN.SLS_CREDIT_ASGNMT_SLS_TRX_KEY
  AND NXSASN.EFFECTIVE_END_DTM= CAST('3500-01-01 00:00:00' AS TIMESTAMP(0))


Post SQL : 



Target1 Name : WI_SCA_FOR_TSL_TRX_NRT_DEF1


Pre SQL : 



Post SQL : 
COLLECT STATS  ON $$NRTSTGDB.WI_SCA_FOR_TSL_TRX_NRT_DEF_NG;
 
 UPDATE WSFCTND 
  FROM
 $$NRTSTGDB.WI_SCA_FOR_TSL_TRX_NRT_DEF_NG WSFCTND,
 (SELECT SLS_CREDIT_ASGNMT_SLS_TRX_KEY,DL.SALES_TERRITORY_KEY  
                     FROM (SEL * FROM $$NRTNCRVWDB.N_XAAS_SO_SBCR_ITM_STRX_NRT_TV WHERE END_TV_DTM=CAST('3500-01-01 00:00:00' AS TIMESTAMP(0)))NSO
                  INNER JOIN $$NRTSTGDB.WI_SCA_FOR_TSL_TRX_NRT_DEF_NG WSFCTND
                  ON WSFCTND.SO_SBSCRPTN_ITM_SLS_TRX_KEY = NSO.SO_SBSCRPTN_ITM_SLS_TRX_KEY
                  INNER JOIN $$SLSORDVWDB.N_DEAL DL
                  ON NSO.BK_DEAL_ID = DL.BK_DEAL_ID
                  INNER JOIN $$COMREFVWDB.R_SALES_HIERARCHY E
                  ON E.SALES_TERRITORY_KEY=DL.SALES_TERRITORY_KEY
                  INNER JOIN $$ETLVWDB.EL_NON_GEO_THEATERS  EN
                  ON E.L1_SALES_TERRITORY_NAME_CODE = EN.L1_SALES_TERRITORY_NAME_CODE                
  ) QTR
 SET
 SALES_TERRITORY_KEY = QTR.SALES_TERRITORY_KEY
 WHERE WSFCTND.SLS_CREDIT_ASGNMT_SLS_TRX_KEY = QTR.SLS_CREDIT_ASGNMT_SLS_TRX_KEY   ;