ETL Name:	wf_WI_DRVD_XAAS_BKGS_TRX_NRT_R_NG.xml


Session 1: 	s_m_WI_DRVD_XAAS_BKGS_TRX_NRT_R_NG
Mapping 1: 	m_WI_DRVD_XAAS_BKGS_TRX_NRT_R_NG


Source1 Name : SQ_WI_XAAS_ITM_SLS_TRX_INCR_NRT_R_NG


Pre SQL : 



SQL Query : 
SELECT 
  DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY AS SO_SBSCRPTN_ITM_SLS_TRX_KEY,
  PROCESS_DATE,TRANSACTION_DATETIME,SLS_CREDIT_ASGNMT_SLS_TRX_KEY
  FROM $$NRTSTGDB.WI_DRVD_XAAS_BKGS_TRX_NRT_F_NG
  WHERE 1=1
  QUALIFY ROW_NUMBER () OVER (PARTITION BY DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY,PROCESS_DATE ORDER BY TRANSACTION_DATETIME DESC)=1


Post SQL : 



Target1 Name : WI_XAAS_ITM_SLS_TRX_INCR_NRT_R1_NG


Pre SQL : 
DELETE  FROM  $$NRTSTGDB.WI_XAAS_ITM_SLS_TRX_INCR_NRT_R_NG ALL;


Post SQL : 
COLLECT STATS ON $$NRTSTGDB.WI_XAAS_ITM_SLS_TRX_INCR_NRT_R_NG ;


Source2 Name : SQ_WI_DRVD_XAAS_BKGS_TRX_NRT_R_NG


Pre SQL : 



SQL Query : 
SELECT             
  TMP1.PRODUCT_KEY                   
  ,TMP1.END_CUSTOMER_KEY              
  ,TMP1.BILL_TO_CUSTOMER_KEY          
  ,TMP1.SHIP_TO_CUSTOMER_KEY          
  ,TMP1.SOLD_TO_CUSTOMER_KEY          
  ,TMP1.TRANSACTION_DATETIME          
  ,TMP1.SALES_TERRITORY_KEY           
  ,TMP1.SALES_REP_NUMBER              
  ,TMP1.PROCESS_DATE                  
  ,TMP1.DV_FISCAL_YEAR_MTH_NUMBER_INT 
  ,TMP1.ADJUSTMENT_TYPE_CODE          
  ,TMP1.SALES_CHANNEL_CODE            
  ,TMP1.SALES_CREDIT_TYPE_CODE        
  ,TMP1.ADJUSTMENT_CODE               
  ,TMP1.BKGS_MEASURE_TRANS_TYPE_CODE  
  ,TMP1.CANCELLED_FLG                 
  ,TMP1.CANCEL_CODE                   
  ,TMP1.ACQUISITION_FLG               
  ,TMP1.FORWARD_REVERSE_FLG           
  ,TMP1.DISTRIBUTOR_OFFSET_FLG        
  ,TMP1.CORPORATE_BOOKINGS_FLG        
  ,TMP1.OVERLAY_FLG                   
  ,TMP1.IC_REVENUE_FLG                
  ,TMP1.CHARGES_FLG                   
  ,TMP1.SALESREP_FLG                  
  ,TMP1.MISC_FLG                      
  ,TMP1.SERVICE_FLG                   
  ,TMP1.INTERNATIONAL_DEMO_FLG        
  ,TMP1.REPLACEMENT_DEMO_FLG          
  ,TMP1.REVENUE_FLG                   
  ,TMP1.RMA_FLG                       
  ,TMP1.DD_COMP_US_NET_PRICE_AMOUNT   
  ,TMP1.DD_COMP_US_LIST_PRICE_AMOUNT  
  ,TMP1.DD_COMP_US_STANDARD_PRICE_AMT 
  ,TMP1.CONVERSION_RT                 
  ,TMP1.CONVERSION_DT                 
  ,TMP1.DD_CISCO_BOOKED_DTM           
  ,TMP1.DD_SALES_ORDER_CATEGORY_TYPE  
  ,TMP1.DD_SLS_ORD_OPERATING_UNIT_CD  
  ,TMP1.DD_TRX_CURRENCY_CD            
  ,TMP1.DV_TRANSACTION_TYPE           
  ,TMP1.DV_TRANSACTION_NAME           
  ,TMP1.BOOKINGS_SPLIT_PCT            
  ,TMP1.DV_SOURCE_ORDER_NUM_INT       
  ,TMP1.DV_DEAL_ID                    
  ,TMP1.DV_PURCHASE_ORDER_NUM         
  ,TMP1.DV_BOOKED_DT                  
  ,TMP1.DV_REVENUE_RECOGNITION_FLG    
  ,TMP1.DV_NET_SPREAD_FLG             
  ,TMP1.DV_PRODUCT_KEY                
  ,TMP1.DV_ATTRIBUTION_CD             
  ,TMP1.DV_FMV_FLG                    
  ,ROW_NUMBER() OVER (ORDER BY TMP1.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY,TRANSACTION_DATETIME ASC) + TMP2.MAX_VAL AS  TRANSACTION_SEQUENCE_ID_INT  
  ,TMP1.TSL_TRX_SOURCE_COMMIT_DTM     
  ,TMP1.RBK_SC_SOURCE_COMMIT_DTM      
  ,TMP1.SO_SBSCRPTN_ITM_SLS_TRX_KEY   
  ,TMP1.SALES_VALUE_TRXL_AMT          
  ,TMP1.TRANSACTION_QUANTITY          
  ,TMP1.DV_END_CUSTOMER_KEY           
  ,TMP1.DV_COMP_US_COST_AMT           
  ,TMP1.WEB_ORDER_ID                  
  ,TMP1.DV_LATEST_RECORD_FLG          
  ,TMP1.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY
  ,TMP1.SK_OFFER_ATTRIBUTION_ID_INT 
  ,TMP1.DV_LOCAL_EXTND_LIST_PRICE_AMT
  ,TMP1.LOCAL_UNIT_LIST_PRICE_AMT
  ,TMP1.DV_UNIT_LIST_PRICE_USD_AMT
  ,TMP1.DV_TOTAL_CNTRCT_VAL_USD_AMT
  ,TMP1.DV_MTHLY_RCR_REV_TRXL_USD_AMT
  ,TMP1.DV_INCRML_MTHY_RCRR_RV_USD_AMT
  ,TMP1.DV_ANNLZD_MTHY_RCRR_RV_USD_AMT
  ,TMP1.DV_INCRML_ANNL_RCRR_RV_USD_AMT
 ,TMP1.DV_PURCHASE_ADJ_DSCNT_USD_AMT /* Q1FY18 PA */ 
  /* ADDED AS PART OF Q2FY18 XAAS */
  ,TMP1.DV_COMP_US_HOLD_NET_PRICE_AMT
  ,TMP1.DV_COMP_US_HOLD_LIST_PRICE_AMT
  ,TMP1.DV_COMP_US_HOLD_COST_AMT
  ,TMP1.DV_EXTENDED_HOLD_QTY
  ,TMP1.BOOKING_PCT
  /* END Q2FY18 XAAS */
 ,TMP1.POB_TYPE_CD  /*NRS MPOB CHANGE */
	 /* Jun2018 Release - Start */ 
	,TMP1.RU_SERVICE_CONTRACT_START_DTM 
	,TMP1.RU_SERVICE_CONTRACT_END_DTM
	,TMP1.DV_CONTRACT_DURATION 
	,TMP1.DV_ANNUALIZED_FLG 
	,TMP1.DV_ANNUALIZED_US_NET_AMT --multiply with -1 to be taken care in 'R' etl in below inner SQL
	,TMP1.DV_MULTIYEAR_US_NET_AMT --multiply with -1 to be taken care in 'R' etl in below inner SQL
	/* Jun2018 Release - End */
  ,TMP1.SALES_MOTION_CD
     FROM
     (
      SELECT
     WLIR.SLS_CREDIT_ASGNMT_SLS_TRX_KEY,
     MTDNBT.SALES_REP_NUMBER,
     MTDNBT.SO_SBSCRPTN_ITM_SLS_TRX_KEY,
     MTDNBT.SALES_TERRITORY_KEY,
     MTDNBT.SALES_CREDIT_TYPE_CODE,
     MTDNBT.ADJUSTMENT_CODE,
     MTDNBT.ADJUSTMENT_TYPE_CODE ,
       (MTDNBT.SALES_VALUE_TRXL_AMT*-1) AS SALES_VALUE_TRXL_AMT,
     MTDNBT.DD_TRX_CURRENCY_CD ,
     MTDNBT.DV_BOOKED_DT ,
       (MTDNBT.TRANSACTION_QUANTITY*-1) AS TRANSACTION_QUANTITY,
     MTDNBT.TSL_TRX_SOURCE_COMMIT_DTM ,
     MTDNBT.RBK_SC_SOURCE_COMMIT_DTM,
     MTDNBT.PRODUCT_KEY,
    /* Commented as part of OA- Q1FY16 CURRENT_TIMESTAMP(0) AS TRANSACTION_DATETIME, */
     WLIR.TRANSACTION_DATETIME,
     WLIR.PROCESS_DATE PROCESS_DATE,
     /* Added below 4 columns as part of OA-Q1FY16*/
     MTDNBT.DV_ATTRIBUTION_CD ,
     MTDNBT.SK_OFFER_ATTRIBUTION_ID_INT ,
     MTDNBT.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY ,
     MTDNBT.DV_PRODUCT_KEY ,
    /*ADDED AS PART OF OPL Q4FY17*/
     (MTDNBT.DD_COMP_US_STANDARD_PRICE_AMT*-1) AS DD_COMP_US_STANDARD_PRICE_AMT,
     (MTDNBT.DV_COMP_US_COST_AMT *-1) AS DV_COMP_US_COST_AMT,
     (MTDNBT.DD_COMP_US_LIST_PRICE_AMOUNT*-1) AS DD_COMP_US_LIST_PRICE_AMOUNT,
     (MTDNBT.DD_COMP_US_NET_PRICE_AMOUNT*-1) AS DD_COMP_US_NET_PRICE_AMOUNT
     ,MTDNBT.END_CUSTOMER_KEY AS END_CUSTOMER_KEY
     ,MTDNBT.BILL_TO_CUSTOMER_KEY 
     ,MTDNBT.SHIP_TO_CUSTOMER_KEY 
     ,MTDNBT.SOLD_TO_CUSTOMER_KEY 
     ,RFMY.FISCAL_YEAR_MONTH_INT AS DV_FISCAL_YEAR_MTH_NUMBER_INT 
     ,MTDNBT.SALES_CHANNEL_CODE 
     ,MTDNBT.BKGS_MEASURE_TRANS_TYPE_CODE
     ,MTDNBT.CANCELLED_FLG
     ,MTDNBT.CANCEL_CODE     
     ,MTDNBT.ACQUISITION_FLG 
     ,'R' AS FORWARD_REVERSE_FLG
              ,MTDNBT.DISTRIBUTOR_OFFSET_FLG
     ,MTDNBT.CORPORATE_BOOKINGS_FLG 
     ,MTDNBT.OVERLAY_FLG 
     ,MTDNBT.IC_REVENUE_FLG        
     ,MTDNBT.CHARGES_FLG      
     ,MTDNBT.SALESREP_FLG                  
     ,MTDNBT.MISC_FLG                
     ,MTDNBT.SERVICE_FLG 
     ,MTDNBT.INTERNATIONAL_DEMO_FLG 
     ,MTDNBT.REPLACEMENT_DEMO_FLG 
     ,MTDNBT.REVENUE_FLG
     ,MTDNBT.RMA_FLG
     ,MTDNBT.CONVERSION_DT              
     ,MTDNBT.CONVERSION_RT                 
     ,MTDNBT.DD_CISCO_BOOKED_DTM 
     ,MTDNBT.DD_SALES_ORDER_CATEGORY_TYPE 
     ,MTDNBT.DD_SLS_ORD_OPERATING_UNIT_CD 
     ,MTDNBT.DV_TRANSACTION_TYPE  
     ,MTDNBT.DV_TRANSACTION_NAME  
     ,MTDNBT.BOOKINGS_SPLIT_PCT 
     ,MTDNBT.DV_SOURCE_ORDER_NUM_INT 
     ,MTDNBT.DV_DEAL_ID 
     ,MTDNBT.DV_PURCHASE_ORDER_NUM
     ,MTDNBT.DV_REVENUE_RECOGNITION_FLG 
     ,MTDNBT.DV_NET_SPREAD_FLG 
     ,MTDNBT.DV_FMV_FLG
     ,MTDNBT.DV_END_CUSTOMER_KEY
     ,MTDNBT.WEB_ORDER_ID AS WEB_ORDER_ID
     ,'N' AS DV_LATEST_RECORD_FLG
    ,(MTDNBT.DV_LOCAL_EXTND_LIST_PRICE_AMT *-1) AS     DV_LOCAL_EXTND_LIST_PRICE_AMT
     ,(MTDNBT.LOCAL_UNIT_LIST_PRICE_AMT * -1) AS        LOCAL_UNIT_LIST_PRICE_AMT
     ,(MTDNBT.DV_UNIT_LIST_PRICE_USD_AMT * -1) AS       DV_UNIT_LIST_PRICE_USD_AMT
     ,(MTDNBT.DV_TOTAL_CNTRCT_VAL_USD_AMT  * -1) AS     DV_TOTAL_CNTRCT_VAL_USD_AMT
     ,(MTDNBT.DV_MTHLY_RCR_REV_TRXL_USD_AMT  * -1) AS   DV_MTHLY_RCR_REV_TRXL_USD_AMT
     ,(MTDNBT.DV_INCRML_MTHY_RCRR_RV_USD_AMT * -1) AS   DV_INCRML_MTHY_RCRR_RV_USD_AMT
     ,(MTDNBT.DV_ANNLZD_MTHY_RCRR_RV_USD_AMT * -1) AS   DV_ANNLZD_MTHY_RCRR_RV_USD_AMT
     ,(MTDNBT.DV_INCRML_ANNL_RCRR_RV_USD_AMT * -1) AS   DV_INCRML_ANNL_RCRR_RV_USD_AMT
     ,(MTDNBT.DV_PURCHASE_ADJ_DSCNT_USD_AMT * -1) AS    DV_PURCHASE_ADJ_DSCNT_USD_AMT
        /* ADDED AS PART OF Q2FY18 XAAS */  
     ,(MTDNBT.DV_COMP_US_HOLD_NET_PRICE_AMT*-1) AS DV_COMP_US_HOLD_NET_PRICE_AMT
     ,(MTDNBT.DV_COMP_US_HOLD_LIST_PRICE_AMT *-1) AS DV_COMP_US_HOLD_LIST_PRICE_AMT
     ,(MTDNBT.DV_COMP_US_HOLD_COST_AMT*-1) AS DV_COMP_US_HOLD_COST_AMT
     ,(MTDNBT.DV_EXTENDED_HOLD_QTY*-1) AS DV_EXTENDED_HOLD_QTY
  ,MTDNBT.BOOKING_PCT
  /* END Q2FY18 XAAS */
,MTDNBT.POB_TYPE_CD  /*NRS MPOB CHANGE */  
	 /* Jun2018 Release - Start */ 
	,MTDNBT.RU_SERVICE_CONTRACT_START_DTM 
	,MTDNBT.RU_SERVICE_CONTRACT_END_DTM
	,MTDNBT.DV_CONTRACT_DURATION 
	,MTDNBT.DV_ANNUALIZED_FLG 
	,(MTDNBT.DV_ANNUALIZED_US_NET_AMT*-1) AS DV_ANNUALIZED_US_NET_AMT 
	,(MTDNBT.DV_MULTIYEAR_US_NET_AMT*-1) AS DV_MULTIYEAR_US_NET_AMT 
	/* Jun2018 Release - End */
	,MTDNBT.SALES_MOTION_CD
     FROM
     $$NRTNCRVWDB.MT_DRVD_XAAS_BKGS_TRX_NG_NRT  MTDNBT
     INNER JOIN 
    $$NRTSTGDB.WI_XAAS_ITM_SLS_TRX_INCR_NRT_R_NG  WLIR
     ON 
     MTDNBT.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY = WLIR.SO_SBSCRPTN_ITM_SLS_TRX_KEY
     AND 
     MTDNBT.PROCESS_DATE <> WLIR.PROCESS_DATE
     AND
     MTDNBT.FORWARD_REVERSE_FLG = 'F'
 /*AND MTDNBT.DV_LATEST_RECORD_FLG='Y'  */
        INNER JOIN $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR RFMY
            ON WLIR.PROCESS_DATE 
            BETWEEN RFMY.FISCAL_MONTH_START_DATE AND RFMY.FISCAL_MONTH_END_DATE
     QUALIFY RANK () OVER (PARTITION BY MTDNBT.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY ORDER BY MTDNBT.PROCESS_DATE DESC) = 1
  
      )TMP1,
     (SELECT COALESCE(MAX(TRANSACTION_SEQUENCE_ID_INT),0)  MAX_VAL FROM $$ETLVWDB.SM_XAAS_BKG_TRX_NRT_NG) TMP2


Post SQL : 



Target2 Name : WI_DRVD_XAAS_BKGS_TRX_NRT_R1_NG


Pre SQL : 
DELETE FROM $$NRTSTGDB.WI_DRVD_XAAS_BKGS_TRX_NRT_R_NG  ALL;


Post SQL : 
COLLECT STATS ON 
$$NRTSTGDB.WI_DRVD_XAAS_BKGS_TRX_NRT_R_NG;

/* NRS PI3 CHANGE */

UPDATE   $$NRTSTGDB.WI_DRVD_XAAS_BKGS_TRX_NRT_R_NG WIDXBTNR 
SET NRS_TRANSITION_FLG = 'Y'  
WHERE EXISTS 
(SELECT 1 FROM $$NRTNCRVWDB.N_XAAS_SO_SBSCR_ATRB_NG_NRT NXSSA WHERE NXSSA.NRS_TRANSITION_FLG = 'Y' 
AND NXSSA.PARENT_SO_SBSCRP_ITMSLSTRX_KEY  = WIDXBTNR.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY ) ;


Source3 Name : SQ_SM_XAAS_BKG_TRX_NRT_NG


Pre SQL : 



SQL Query : 
SELECT
  RANK() OVER (ORDER BY WIMDNBTF.TRANSACTION_SEQUENCE_ID_INT)+ SMDNBTKR_MAX.MAX_DRVD_BKG_VAL DRVD_NCR_BKG_TRX_KEY,
  WIMDNBTF.TRANSACTION_SEQUENCE_ID_INT TRANSACTION_SEQUENCE_ID_INT,
  EDW_CREATE_USER,
  EDW_CREATE_DTM 
  FROM
  (
  SELECT 
  WI1.TRANSACTION_SEQUENCE_ID_INT TRANSACTION_SEQUENCE_ID_INT,
  USER  EDW_CREATE_USER,
  CURRENT_TIMESTAMP(0) EDW_CREATE_DTM 
  FROM 
 $$NRTSTGDB.WI_DRVD_XAAS_BKGS_TRX_NRT_R_NG WI1 
  )WIMDNBTF,
  (SELECT COALESCE(MAX(DRVD_XAAS_BKG_TRX_KEY),0) MAX_DRVD_BKG_VAL FROM $$ETLVWDB.SM_XAAS_BKG_TRX_NRT_NG)SMDNBTKR_MAX
  WHERE
  NOT EXISTS
  (
  SELECT 1 FROM $$ETLVWDB.SM_XAAS_BKG_TRX_NRT_NG SMDNBTKR WHERE SMDNBTKR.TRANSACTION_SEQUENCE_ID_INT = WIMDNBTF.TRANSACTION_SEQUENCE_ID_INT)


Post SQL : 



Target3 Name : SM_XAAS_BKG_TRX_NRT_NG2


Pre SQL : 



Post SQL : 
CALL COLLECT_STATS_WRAP ('$$TRANSLATIONDB','SM_XAAS_BKG_TRX_NRT_NG','D');
   
   DELETE FROM $$NRTSTGDB.WI_DRVD_XAAS_BKG_TRX_DEL_NRT_NG ALL;
    
    INSERT INTO $$NRTSTGDB.WI_DRVD_XAAS_BKG_TRX_DEL_NRT_NG
    SELECT 
   MTDNBT_DEL.DRVD_XAAS_BKGS_KEY            ,
   MTDNBT_DEL.PRODUCT_KEY                   ,
   MTDNBT_DEL.END_CUSTOMER_KEY              ,
   MTDNBT_DEL.BILL_TO_CUSTOMER_KEY          ,
   MTDNBT_DEL.SHIP_TO_CUSTOMER_KEY          ,
   MTDNBT_DEL.SOLD_TO_CUSTOMER_KEY          ,
   MTDNBT_DEL.TRANSACTION_DATETIME          ,
   MTDNBT_DEL.SALES_TERRITORY_KEY           ,
   MTDNBT_DEL.SALES_REP_NUMBER              ,
   MTDNBT_DEL.PROCESS_DATE                  ,
   MTDNBT_DEL.DV_FISCAL_YEAR_MTH_NUMBER_INT ,
   MTDNBT_DEL.ADJUSTMENT_TYPE_CODE          ,
   MTDNBT_DEL.SALES_CHANNEL_CODE            ,
   MTDNBT_DEL.SALES_CREDIT_TYPE_CODE        ,
   MTDNBT_DEL.ADJUSTMENT_CODE               ,
   MTDNBT_DEL.BKGS_MEASURE_TRANS_TYPE_CODE  ,
   MTDNBT_DEL.CANCELLED_FLG                 ,
   MTDNBT_DEL.CANCEL_CODE                   ,
   MTDNBT_DEL.ACQUISITION_FLG               ,
   MTDNBT_DEL.FORWARD_REVERSE_FLG           ,
   MTDNBT_DEL.DISTRIBUTOR_OFFSET_FLG        ,
   MTDNBT_DEL.CORPORATE_BOOKINGS_FLG        ,
   MTDNBT_DEL.OVERLAY_FLG                   ,
   MTDNBT_DEL.IC_REVENUE_FLG                ,
   MTDNBT_DEL.CHARGES_FLG                   ,
   MTDNBT_DEL.SALESREP_FLG                  ,
   MTDNBT_DEL.MISC_FLG                      ,
   MTDNBT_DEL.SERVICE_FLG                   ,
   MTDNBT_DEL.INTERNATIONAL_DEMO_FLG        ,
   MTDNBT_DEL.REPLACEMENT_DEMO_FLG          ,
   MTDNBT_DEL.REVENUE_FLG                   ,
   MTDNBT_DEL.RMA_FLG                       ,
   MTDNBT_DEL.DD_COMP_US_NET_PRICE_AMOUNT   ,
   MTDNBT_DEL.DD_COMP_US_LIST_PRICE_AMOUNT  ,
   MTDNBT_DEL.DD_COMP_US_STANDARD_PRICE_AMT ,
   MTDNBT_DEL.CONVERSION_RT                 ,
   MTDNBT_DEL.CONVERSION_DT                 ,
   MTDNBT_DEL.DD_CISCO_BOOKED_DTM           ,
   MTDNBT_DEL.DD_SALES_ORDER_CATEGORY_TYPE  ,
   MTDNBT_DEL.DD_SLS_ORD_OPERATING_UNIT_CD  ,
   MTDNBT_DEL.DD_TRX_CURRENCY_CD            ,
   MTDNBT_DEL.DV_TRANSACTION_TYPE           ,
   MTDNBT_DEL.DV_TRANSACTION_NAME           ,
   MTDNBT_DEL.BOOKINGS_SPLIT_PCT            ,
   MTDNBT_DEL.DV_SOURCE_ORDER_NUM_INT       ,
   MTDNBT_DEL.DV_DEAL_ID                    ,
   MTDNBT_DEL.DV_PURCHASE_ORDER_NUM         ,
   MTDNBT_DEL.DV_BOOKED_DT                  ,
   MTDNBT_DEL.DV_REVENUE_RECOGNITION_FLG    ,
   MTDNBT_DEL.DV_NET_SPREAD_FLG             ,
   MTDNBT_DEL.DV_PRODUCT_KEY                ,
   MTDNBT_DEL.DV_ATTRIBUTION_CD             ,
   MTDNBT_DEL.DV_FMV_FLG                    ,
   MTDNBT_DEL.TRANSACTION_SEQUENCE_ID_INT   ,
   MTDNBT_DEL.TSL_TRX_SOURCE_COMMIT_DTM     ,
   MTDNBT_DEL.RBK_SC_SOURCE_COMMIT_DTM      ,
   MTDNBT_DEL.SO_SBSCRPTN_ITM_SLS_TRX_KEY   ,
   MTDNBT_DEL.SALES_VALUE_TRXL_AMT          ,
   MTDNBT_DEL.TRANSACTION_QUANTITY          ,
   MTDNBT_DEL.DV_END_CUSTOMER_KEY    ,
   MTDNBT_DEL.EDW_CREATE_USER               ,
   MTDNBT_DEL.EDW_UPDATE_USER               ,
   MTDNBT_DEL.EDW_CREATE_DATETIME           ,
   MTDNBT_DEL.EDW_UPDATE_DATETIME           ,
   MTDNBT_DEL.DV_COMP_US_COST_AMT           ,
   MTDNBT_DEL.WEB_ORDER_ID                  ,
   MTDNBT_DEL.DV_LATEST_RECORD_FLG          ,
   /* Added below 2 columns as part of OA - Q1FY16*/
   MTDNBT_DEL.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY,
   MTDNBT_DEL.SK_OFFER_ATTRIBUTION_ID_INT
   ,MTDNBT_DEL.DV_LOCAL_EXTND_LIST_PRICE_AMT 
   ,MTDNBT_DEL.LOCAL_UNIT_LIST_PRICE_AMT     
   ,MTDNBT_DEL.DV_UNIT_LIST_PRICE_USD_AMT 
   ,MTDNBT_DEL.DV_TOTAL_CNTRCT_VAL_USD_AMT    
   ,MTDNBT_DEL.DV_MTHLY_RCR_REV_TRXL_USD_AMT  
   ,MTDNBT_DEL.DV_INCRML_MTHY_RCRR_RV_USD_AMT 
   ,MTDNBT_DEL.DV_ANNLZD_MTHY_RCRR_RV_USD_AMT 
   ,MTDNBT_DEL.DV_INCRML_ANNL_RCRR_RV_USD_AMT    
    ,MTDNBT_DEL.DV_PURCHASE_ADJ_DSCNT_USD_AMT
   /* ADDED AS PART OF Q2FY18 XAAS */    
    ,MTDNBT_DEL.DV_COMP_US_HOLD_NET_PRICE_AMT   
    ,MTDNBT_DEL.DV_COMP_US_HOLD_LIST_PRICE_AMT  
    ,MTDNBT_DEL.DV_COMP_US_HOLD_COST_AMT        
    ,MTDNBT_DEL.DV_EXTENDED_HOLD_QTY     
    ,MTDNBT_DEL.BOOKING_PCT   
    /* END Q2FY18 XAAS */
	 /* Jun2018 Release - Start */ 
	,MTDNBT_DEL.RU_SERVICE_CONTRACT_START_DTM 
	,MTDNBT_DEL.RU_SERVICE_CONTRACT_END_DTM
	,MTDNBT_DEL.DV_CONTRACT_DURATION 
	,MTDNBT_DEL.DV_ANNUALIZED_FLG 
	,MTDNBT_DEL.DV_ANNUALIZED_US_NET_AMT
	,MTDNBT_DEL.DV_MULTIYEAR_US_NET_AMT 
	/* Jun2018 Release - End */
	,MTDNBT_DEL.SALES_MOTION_CD
FROM 
   $$NRTNCRVWDB.MT_DRVD_XAAS_BKGS_TRX_NG_NRT MTDNBT_DEL WHERE EXISTS 
   (SELECT 1 FROM $$NRTSTGDB.WI_XAAS_ITM_SLS_TRX_INCR_NRT_R_NG WLIR_DEL 
   WHERE MTDNBT_DEL.DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY  = WLIR_DEL.SO_SBSCRPTN_ITM_SLS_TRX_KEY 
    AND MTDNBT_DEL.PROCESS_DATE = WLIR_DEL.PROCESS_DATE);
    
    INSERT INTO $$NRTNCRVWDB.MT_DRVD_XAAS_BKG_TRX_DEL_NG
    SELECT
    DRVD_XAAS_BKGS_KEY            ,
   PRODUCT_KEY                   ,
   END_CUSTOMER_KEY              ,
   BILL_TO_CUSTOMER_KEY          ,
   SHIP_TO_CUSTOMER_KEY          ,
   SOLD_TO_CUSTOMER_KEY          ,
   TRANSACTION_DATETIME          ,
   SALES_TERRITORY_KEY           ,
   SALES_REP_NUMBER              ,
   PROCESS_DATE                  ,
   DV_FISCAL_YEAR_MTH_NUMBER_INT ,
   ADJUSTMENT_TYPE_CODE          ,
   SALES_CHANNEL_CODE            ,
   SALES_CREDIT_TYPE_CODE        ,
   ADJUSTMENT_CODE               ,
   BKGS_MEASURE_TRANS_TYPE_CODE  ,
   CANCELLED_FLG                 ,
   CANCEL_CODE                   ,
   ACQUISITION_FLG               ,
   FORWARD_REVERSE_FLG           ,
   DISTRIBUTOR_OFFSET_FLG        ,
   CORPORATE_BOOKINGS_FLG        ,
   OVERLAY_FLG                   ,
   IC_REVENUE_FLG                ,
   CHARGES_FLG                   ,
   SALESREP_FLG                  ,
   MISC_FLG                      ,
   SERVICE_FLG                   ,
   INTERNATIONAL_DEMO_FLG        ,
   REPLACEMENT_DEMO_FLG          ,
   REVENUE_FLG                   ,
   RMA_FLG                       ,
   DD_COMP_US_NET_PRICE_AMOUNT   ,
   DD_COMP_US_LIST_PRICE_AMOUNT  ,
   DD_COMP_US_STANDARD_PRICE_AMT ,
   CONVERSION_RT                 ,
   CONVERSION_DT                 ,
   DD_CISCO_BOOKED_DTM           ,
   DD_SALES_ORDER_CATEGORY_TYPE  ,
   DD_SLS_ORD_OPERATING_UNIT_CD  ,
   DD_TRX_CURRENCY_CD            ,
   DV_TRANSACTION_TYPE           ,
   DV_TRANSACTION_NAME           ,
   BOOKINGS_SPLIT_PCT            ,
   DV_SOURCE_ORDER_NUM_INT       ,
   DV_DEAL_ID                    ,
   DV_PURCHASE_ORDER_NUM         ,
   DV_BOOKED_DT                  ,
   DV_REVENUE_RECOGNITION_FLG    ,
   DV_NET_SPREAD_FLG             ,
   DV_PRODUCT_KEY                ,
   DV_ATTRIBUTION_CD             ,
   DV_FMV_FLG                    ,
   TRANSACTION_SEQUENCE_ID_INT   ,
   TSL_TRX_SOURCE_COMMIT_DTM     ,
   RBK_SC_SOURCE_COMMIT_DTM      ,
   SO_SBSCRPTN_ITM_SLS_TRX_KEY   ,
   SALES_VALUE_TRXL_AMT          ,
   TRANSACTION_QUANTITY          ,
   DV_END_CUSTOMER_KEY     ,
   EDW_CREATE_USER               ,
   EDW_UPDATE_USER               ,
   EDW_CREATE_DATETIME           ,
   EDW_UPDATE_DATETIME           ,
   DV_COMP_US_COST_AMT           ,
   WEB_ORDER_ID                  ,
   DV_LATEST_RECORD_FLG        ,
   /* Added below 2 columns as part of OA - Q1FY16*/
   DV_SO_SBSCRPTN_ITM_SLS_TRX_KEY,
   SK_OFFER_ATTRIBUTION_ID_INT
   ,DV_LOCAL_EXTND_LIST_PRICE_AMT 
    ,LOCAL_UNIT_LIST_PRICE_AMT     
    ,DV_UNIT_LIST_PRICE_USD_AMT 
    ,DV_TOTAL_CNTRCT_VAL_USD_AMT    
    ,DV_MTHLY_RCR_REV_TRXL_USD_AMT  
    ,DV_INCRML_MTHY_RCRR_RV_USD_AMT 
    ,DV_ANNLZD_MTHY_RCRR_RV_USD_AMT 
    ,DV_INCRML_ANNL_RCRR_RV_USD_AMT   
     ,DV_PURCHASE_ADJ_DSCNT_USD_AMT
    /* ADDED AS PART OF Q2FY18 XAAS  */   
    ,DV_COMP_US_HOLD_NET_PRICE_AMT   
    ,DV_COMP_US_HOLD_LIST_PRICE_AMT  
    ,DV_COMP_US_HOLD_COST_AMT        
    ,DV_EXTENDED_HOLD_QTY     
    ,BOOKING_PCT   
    /* END Q2FY18 XAAS */ 
	 /* Jun2018 Release - Start */ 
	,RU_SERVICE_CONTRACT_START_DTM 
	,RU_SERVICE_CONTRACT_END_DTM
	,DV_CONTRACT_DURATION 
	,DV_ANNUALIZED_FLG 
	,DV_ANNUALIZED_US_NET_AMT
	,DV_MULTIYEAR_US_NET_AMT 
	/* Jun2018 Release - End */
	,SALES_MOTION_CD
 FROM $$NRTSTGDB.WI_DRVD_XAAS_BKG_TRX_DEL_NRT_NG;